### ISSUE TITLE
FNX-4713 ⁃ As an engineer I would like to know when the Nightly task fails

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1005]

**Comment by vesta0** [comment]
@boek will speak to RelEng

**Comment by boek** [comment]
Hey @mozilla-mobile/releng, currently we have a notification set for the scheduling task at: https://github.com/mozilla-mobile/fenix/blob/master/.taskcluster.yml#L128. This task rarely (if ever) fails. So I would love to send a notification if the build task fails

**Comment by JohanLorenzo** [comment]
This makes sense and I agree with the provided fix. Thanks guys for looping us in and 👍 for pushing this fix quickly 😃

**Comment by pocmo** [comment]
https://tools.taskcluster.net/groups/L4z4BabYQFi-OTDU-DIQTg/tasks/L4z4BabYQFi-OTDU-DIQTg/runs/0/logs/public%2Flogs%2Flive.log

```
 + python automation/taskcluster/decision_task_nightly.py --track nightly --commit --output /opt/fenix/app/build/outputs/apk --apk armGreenfield/release/app-arm-greenfield-release-unsigned.apk --apk x86Greenfield/release/app-x86-greenfield-release-unsigned.apk --apk aarch64Greenfield/release/app-aarch64-greenfield-release-unsigned.apk --date 2019-03-26T12:15:32.299Z
Traceback (most recent call last):
  File "automation/taskcluster/decision_task_nightly.py", line 172, in <module>
    nightly(apks, result.track, result.commit, result.date)
  File "automation/taskcluster/decision_task_nightly.py", line 132, in nightly
    build_task_id, build_task = generate_build_task(apks, is_staging)
  File "automation/taskcluster/decision_task_nightly.py", line 69, in generate_build_task
    routes=["notify.email.fenix-eng-notifications@mozilla.com.on-failed"]
TypeError: build_task() got an unexpected keyword argument 'routes'
```
