### ISSUE TITLE
FNX-3281 ⁃ AssertionError: Play/Pause button clicked without play/pause state.

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#10091]
https://sentry.prod.mozaws.net/operations/fenix/issues/7930907/

```
AssertionError: Play/Pause button clicked without play/pause state.
    at -$$LambdaGroup$js$RIBXZ0u1hawZuzfmD2tv7epTSVw.onClick(java-style lambda group:97)
    at android.view.View.performClick(View.java:7161)
    at android.view.View.performClickInternal(View.java:7133)
    at android.view.View.access$3500(View.java:804)
    at android.view.View$PerformClick.run(View.java:27416)
...
(7 additional frame(s) were not displayed)

Play/Pause button clicked without play/pause state.
```

**Comment by mcarare** [comment]
This happens when the play/pause button can be clicked even though it is not visible, as the tab's MediaState is `MediaState.State.NONE`.

**Comment by sv-sdeiac** [comment]
Hi, I can confirm that this issue is fixed using the latest version of Firefox Preview Nightly 4/24 #21150607.
The crash is not anymore presented but #10180 was filled for a possible regression.

Devices:
- Google Pixel (Android 10);
- Samsung Galaxy Note 8 (Android 9);
- LG G7 fit (Android 8.1).
