### ISSUE TITLE
FNX-3307 ⁃ [Crash] Open settings after signing into your account

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#10137]
## Steps to reproduce
1. Sign in with valid credentials.
(2. Install Dark Reader add-on, and NoScript Security Suite add-on - **not necessary**)
1. Browse a few pages - I had 6, twitter.com was one of them.
1. Scroll and watch a few videos on Twitter.
1. From the Twitter tab, tap on the three-dot menu - settings. 

### Expected behavior
The settings page is opened.

### Actual behavior
Fenix crashes 3/5 times. Not 100% reproducible.

### Device information
* Android device: OnePlus 5T (Android 9), HTC 10 (Android 8)
* Fenix version: 4/23 Nightly build

[crash.txt](https://github.com/mozilla-mobile/fenix/files/4521447/crash.txt)

**Comment by csadilek** [comment]
Just looked to make sure it's not add-on related. Looks like a problem in`updateAccountUI`:

```
ava.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:2)
        at org.mozilla.fenix.settings.SettingsFragment.updateAccountUIState(SettingsFragment.kt:16)
        at org.mozilla.fenix.settings.SettingsFragment.onCreate(SettingsFragment.kt:7)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:5)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:59)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:54)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by sflorean** [comment]
I was able to reproduce this without having addons installed. 
1. Log in with a valid account.
2. Open twitter.
3. Tap on "Log in" -> password field.
4. Tap on 3dotmenu - Settings. 
 Results: Fenix crashes. 

Not reproducible when I'm not signed with a Firefox account.

**Comment by softvision-miralobontiu** [comment]
Hi all, 
Step 2 (install some add-ons) is not necessary, the crash is not linked to add-ons at all.
I edited the STR and the title of the issue.

**Comment by csadilek** [comment]
I think this was fixed as https://github.com/mozilla-mobile/fenix/issues/10204. Can't repro anymore :).

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200511 from 5/11`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200511-101328](https://user-images.githubusercontent.com/51314259/81534870-72830c80-9371-11ea-967d-68c9ea337295.gif)



<details>
    <summary>Video of the reported issue (dropdown)</summary>

![20200511-101111 (1)](https://user-images.githubusercontent.com/51314259/81534765-3e0f5080-9371-11ea-86af-ea918ab06be8.gif)



</details>
