### ISSUE TITLE
FNX3-13808 ⁃ crash when trying to delete a session

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1032]
I have a session on my home screen and when I try to delete the session Fenix crashes.

2019-03-15 08:56:11.376 28655-28655/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 28655
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
        at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:209)
        at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:256)
        at mozilla.components.feature.session.bundling.db.BundleDao_Impl.deleteBundle(BundleDao_Impl.java:131)
        at mozilla.components.feature.session.bundling.SessionBundleStorage.remove(SessionBundleStorage.kt:98)
        at org.mozilla.fenix.home.HomeFragment$openSessionMenu$1$2.invoke(HomeFragment.kt:366)
        at org.mozilla.fenix.home.HomeFragment$openSessionMenu$1$2.invoke(HomeFragment.kt:59)
        at org.mozilla.fenix.home.SessionBottomSheetFragment$onCreateView$2.onClick(SessionBottomSheetFragment.kt:55)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24779)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
2019-03-15 08:56:11.380 1736-4728/? E/ActivityManager: App crashed! Process: org.mozilla.fenix.debug

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 92559622195f44d1f715ae002809cf6e00eacecf

**Comment by boek** [comment]
Ah yeah, the APIs changed in a-c. We just have to update them in Fenix
