### ISSUE TITLE
[Bug][a11y] The app crash when you open a PiP screen using Talkback

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla-mobile/fenix#10388]
### Prerequisites
The talkback option is enabled from the Android settings.

## Steps to reproduce
1. Open a video in youtube.com;
2. Go to full-screen;
3. Display the Picture-in-picture video mode.

### Expected behavior
The Picture-in-Picture mode is displayed and the user can interact with the floating screen.

### Actual behavior
The app crash when the PiP mode is displayed.

### Device information

Android device: Samsung Galaxy Note S8 (Android 9).
Fenix version: Firefox Preview Nightly 4/30 #21210606.
Not reproducible using LG G7 Fit (Android 8.1).
[crashTalkback-PiP.txt](https://github.com/mozilla-mobile/fenix/files/4572922/crashTalkback-PiP.txt)

**Comment by ekager** [comment]
>     
>     --------- beginning of crash
> 2020-05-04 08:49:40.245 24733-24733/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.mozilla.fenix.nightly, PID: 24733
>     java.lang.IllegalStateException: enterPictureInPictureMode: Device doesn't support picture-in-picture mode.
>         at android.os.Parcel.createException(Parcel.java:1974)
>         at android.os.Parcel.readException(Parcel.java:1934)
>         at android.os.Parcel.readException(Parcel.java:1884)
>         at android.app.IActivityManager$Stub$Proxy.enterPictureInPictureMode(IActivityManager.java:8877)
>         at android.app.Activity.enterPictureInPictureMode(Activity.java:2241)
>         at org.mozilla.fenix.browser.BaseBrowserFragment.onHomePressed(BaseBrowserFragment.kt:6)
>         at org.mozilla.fenix.HomeActivity.onUserLeaveHint(HomeActivity.kt:5)
>         at android.app.Activity.performUserLeaving(Activity.java:7631)
>         at android.app.Instrumentation.callActivityOnUserLeaving(Instrumentation.java:1475)
>         at android.app.ActivityThread.performUserLeavingActivity(ActivityThread.java:4202)
>         at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4187)
>         at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
>         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7073)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
>      Caused by: android.os.RemoteException: Remote stack trace:
>         at com.android.server.am.ActivityManagerService.ensureValidPictureInPictureActivityParamsLocked(ActivityManagerService.java:11494)
>         at com.android.server.am.ActivityManagerService.enterPictureInPictureMode(ActivityManagerService.java:11362)
>         at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2507)
>         at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4140)
>         at android.os.Binder.execTransact(Binder.java:739)
