### ISSUE TITLE
FNX-3524 ⁃ [Bug] Very slow performance and crashes when opening a PNG image of a map in a new tab

### ISSUE THREAD

**Issue by anotherus3r** [mozilla-mobile/fenix#10410]
## Steps to reproduce
1. Go to this link: https://ourworldindata.org/grapher/total-confirmed-cases-of-covid-19-per-million-people?year=2020-05-04
1. Tap the download button below the map.
1. Tap and hold on the image next to "Save as .png".
1. Tap "Open image in new tab".

### Expected behavior
Opens image in new tab without any problems.

### Actual behavior
Opens new tab with image, but browser slows down significantly. Closing the tab resolves performance issues.

### Device information
* Android device: Huawei Mate 20, Android 10
* Fenix version: Firefox Preview Nightly 200504 06:01 (Build #21250608)

![Screenshot](https://user-images.githubusercontent.com/1082253/81132699-2a449400-8f04-11ea-8bb2-952dcd92db52.png)UNITO-UNDERSCORE!20200505-190914!
![Screenshot](https://user-images.githubusercontent.com/1082253/81132706-2f094800-8f04-11ea-8e99-66b56bf3e288.png)UNITO-UNDERSCORE!20200505-190951!

**Comment by eliserichards** [comment]
Possibly related to mozilla-mobile/android-components#1159

**Comment by liuche** [comment]
Added some screenshots:
- definitely `blob:` file type, which explains a) crash when saving image through long-press, b) "cannot download this file type"
- the new tab is a `data:img/png;base64` so maybe the file is just too big? Also says the filesize is only 0.53 MB

**Comment by csadilek** [comment]
The blob: download works now, but there are two more problems here:

- Crash: Long-pressing on the map and "saving as image" actually triggers a download for the map image (a rather big data URI). The URI is part of the download object which is stored as intent extras:

```
 java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1486032 bytes
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1621)
        at android.app.ContextImpl.startService(ContextImpl.java:1571)
        at android.content.ContextWrapper.startService(ContextWrapper.java:669)
        at mozilla.components.feature.downloads.manager.FetchDownloadManager.download(FetchDownloadManager.kt:8)
        at mozilla.components.feature.downloads.DownloadsFeature.access$processDownload(DownloadsFeature.kt:16)
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
        at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:6)
        at kotlinx.coroutines.CoroutineScopeKt.emitAllImpl$FlowKt__ChannelsKt(CoroutineScope.kt:14)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

- Performance issue: When opening the data URI in a new tab (instead of saving it) we hit: https://github.com/mozilla-mobile/fenix/issues/1824 and https://github.com/mozilla-mobile/android-components/issues/5249 respectively.

**Comment by csadilek** [comment]
Thanks for filing! The performance issue is fixed now on master and will be in tomorrow's Nightly.

Let's dupe the encountered crash to https://github.com/mozilla-mobile/android-components/issues/5217 which needs a bigger refactoring to work: https://github.com/mozilla-mobile/android-components/issues/7050
