### ISSUE TITLE
[Bug] `gradlew lint` remains stuck in an infinite loop and eats up all available memory

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-mobile/fenix#10439]
## Steps to reproduce
```sh
./gradlew lint
```

### Expected behavior
This command eventually finishes.

### Actual behavior
It's somewhat stuck in a infinite loop. I discovered this bug while working on https://github.com/mozilla-mobile/fenix/pull/10316. It's easily visible in CI and I was able to reproduce it locally. There's probably a memory leak somewhere because this stacktrace came up:

```
[task 2020-05-04T15:24:30.418Z] > Task :app:lint
[task 2020-05-04T15:53:19.218Z] > Task :app:lint FAILED
[task 2020-05-04T15:53:19.218Z] 
[task 2020-05-04T15:53:19.218Z] FAILURE: Build failed with an exception.
[task 2020-05-04T15:53:19.218Z] 
[task 2020-05-04T15:53:19.218Z] * What went wrong:
[task 2020-05-04T15:53:19.218Z] Execution failed for task ':app:lint'.
[task 2020-05-04T15:53:19.218Z] > Lint infrastructure error
[task 2020-05-04T15:53:19.218Z]   Caused by: java.lang.reflect.InvocationTargetException
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-05-04T15:53:19.218Z]   	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-05-04T15:53:19.218Z]   	at com.android.tools.lint.gradle.api.ReflectiveLintRunner.runLint(ReflectiveLintRunner.kt:38)
[task 2020-05-04T15:53:19.218Z]   	at com.android.build.gradle.tasks.LintBaseTask.runLint(LintBaseTask.java:100)
[task 2020-05-04T15:53:19.218Z]   	at com.android.build.gradle.tasks.LintGlobalTask.lint(LintGlobalTask.java:47)
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-05-04T15:53:19.218Z]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-05-04T15:53:19.218Z]   	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-05-04T15:53:19.218Z]   	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
[task 2020-05-04T15:53:19.218Z]   	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
[task 2020-05-04T15:53:19.218Z]   	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
[task 2020-05-04T15:53:19.218Z]   	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[task 2020-05-04T15:53:19.220Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
[task 2020-05-04T15:53:19.221Z]   	at java.util.Optional.orElseGet(Optional.java:267)
[task 2020-05-04T15:53:19.221Z]   	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
[task 2020-05-04T15:53:19.222Z]   	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
[task 2020-05-04T15:53:19.222Z]   	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
[task 2020-05-04T15:53:19.222Z]   	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
[task 2020-05-04T15:53:19.223Z]   	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
[task 2020-05-04T15:53:19.223Z]   	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
[task 2020-05-04T15:53:19.223Z]   	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
[task 2020-05-04T15:53:19.224Z]   	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
[task 2020-05-04T15:53:19.226Z]   	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
[task 2020-05-04T15:53:19.228Z]   	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
[task 2020-05-04T15:53:19.229Z]   	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
[task 2020-05-04T15:53:19.231Z]   	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
[task 2020-05-04T15:53:19.233Z]   	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
[task 2020-05-04T15:53:19.234Z]   	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
[task 2020-05-04T15:53:19.235Z]   	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
[task 2020-05-04T15:53:19.236Z]   	at java.util.Optional.map(Optional.java:215)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[task 2020-05-04T15:53:19.236Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
[task 2020-05-04T15:53:19.237Z]   	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-05-04T15:53:19.238Z]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-05-04T15:53:19.238Z]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-05-04T15:53:19.238Z]   	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-05-04T15:53:19.238Z]   	at java.lang.Thread.run(Thread.java:748)
[task 2020-05-04T15:53:19.239Z]   Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-05-04T15:53:19.239Z]   	at java.util.HashMap.newNode(HashMap.java:1750)
[task 2020-05-04T15:53:19.239Z]   	at java.util.HashMap.putVal(HashMap.java:642)
[task 2020-05-04T15:53:19.239Z]   	at java.util.HashMap.putMapEntries(HashMap.java:515)
[task 2020-05-04T15:53:19.239Z]   	at java.util.HashMap.putAll(HashMap.java:785)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.getProperties(DefaultConvention.java:259)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.internal.metaobject.CompositeDynamicObject.getProperties(CompositeDynamicObject.java:79)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.api.internal.project.DefaultProject$5.create(DefaultProject.java:1058)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.api.internal.project.DefaultProject$5.create(DefaultProject.java:1055)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:467)
[task 2020-05-04T15:53:19.239Z]   	at org.gradle.api.internal.project.DefaultProject.getProperties(DefaultProject.java:1055)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.ide.ModelBuilder.getDependencies(ModelBuilder.java:795)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.ide.ModelBuilder.createUnitTestsJavaArtifact(ModelBuilder.java:720)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.ide.ModelBuilder.createVariant(ModelBuilder.java:616)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.ide.ModelBuilder.buildAndroidProject(ModelBuilder.java:406)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.ide.ModelBuilder.buildAll(ModelBuilder.java:195)
[task 2020-05-04T15:53:19.240Z]   	at com.android.build.gradle.internal.AppModelBuilder.buildAll(AppModelBuilder.kt:62)
[task 2020-05-04T15:53:19.240Z]   	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder$1$1.create(DefaultToolingModelBuilderRegistry.java:104)
[task 2020-05-04T15:53:19.240Z]   	at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:133)
[task 2020-05-04T15:53:19.240Z]   	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder$1.call(DefaultToolingModelBuilderRegistry.java:100)
[task 2020-05-04T15:53:19.240Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
[task 2020-05-04T15:53:19.241Z]   	at org.gradle.tooling.provider.model.internal.DefaultToolingModelBuilderRegistry$BuildOperationWrappingToolingModelBuilder.buildAll(DefaultToolingModelBuilderRegistry.java:97)
[task 2020-05-04T15:53:19.242Z]   	at com.android.tools.lint.gradle.LintGradleExecution.createAndroidProject(LintGradleExecution.java:365)
[task 2020-05-04T15:53:19.242Z]   	at com.android.tools.lint.gradle.LintGradleProject$ProjectSearch.createAndroidProject(LintGradleProject.java:881)
[task 2020-05-04T15:53:19.242Z]   	at com.android.tools.lint.gradle.LintGradleProject$ProjectSearch.getAndroidProject(LintGradleProject.java:892)
[task 2020-05-04T15:53:19.242Z]   	at com.android.tools.lint.gradle.LintGradleProject$ProjectSearch.getProject(LintGradleProject.java:904)
[task 2020-05-04T15:53:19.242Z]   	at com.android.tools.lint.gradle.LintGradleClient.createLintRequest(LintGradleClient.java:211)
```

https://firefox-ci-tc.services.mozilla.com/tasks/AACHCCH9Qa6To11S8AFsew/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FAACHCCH9Qa6To11S8AFsew%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L57665

I ran the same command with --debug and it showed it was struggling to get free RAM. I don't have the logs anymore, though.

**Comment by bsautner** [comment]
did you ever figure this out? We have this problem in our android app's build - our app is huge and when i google "Lint infrastructure error" i get four results including this thread which is worrisome. Happy to collaborate

**Comment by JohanLorenzo** [comment]
Hi @bsautner! 

Thank you for leaving a comment here! As far as I know, no one has looked into this issue since it was filed. So far, we've worked around it by using `./gradlew lintDebug`

https://github.com/mozilla-mobile/fenix/blob/4ebb070ed7d481ed660899d4cc1d1f92ef04959e/taskcluster/ci/lint/kind.yml#L71-L72

Would it work for you?

**Comment by n0m0r3pa1n** [comment]
No update I guess. Just one more issue in a 2.3k :)

**Comment by yvolk** [comment]
I encountered the same problem, but found this article about a solution using timeouts introduction. It also mentions the same Lint freezing: 
> Android Lint task was always getting frozen due some live-lock / race condition which was very hard to track, since logs offered no meaningful clue if the issue was at Android Gradle Plugin level or at Gradle build system level"

See https://ubiratansoares.dev/post/timeouts-and-your-big-gradle-project/

**Comment by n0m0r3pa1n** [comment]
Running app:lintDebug instead of app:lint resolves the issue.
