### ISSUE TITLE
FNX-4309 ⁃ [Bug] Nightly crashed on first page load

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#10471]
## Steps to reproduce
start browser
visit a page

### Expected behavior
not crash

### Actual behavior
crashed

### Device information
* Android device: one plus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment]
```
05-07 11:01:37.613  7831  7891 D ServiceAllocator: org.mozilla.gecko.process.GeckoChildProcessServices$tab0 updateBindings: IDLE priority, 6 importance, 0 successful binds, 0 failed binds, 2 successful unbinds, 0 failed unbinds
05-07 11:01:37.633  7831  7831 D GeckoSession: handleMessage GeckoView:StateUpdated uri=null
05-07 11:01:37.633  3483  3483 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{34252cc V.ED..... ......ID 0,0-1080,810 #7f080004 app:id/LatinkeyboardBaseView}
05-07 11:01:37.665  7831  7831 D AndroidRuntime: Shutting down VM
05-07 11:01:37.666  7831  7831 E AndroidRuntime: FATAL EXCEPTION: main
05-07 11:01:37.666  7831  7831 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 7831
05-07 11:01:37.666  7831  7831 E AndroidRuntime: java.lang.IllegalStateException: Cannot add item decoration during a scroll  or layout
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:4)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.assertNotInLayoutOrScroll(LinearLayoutManager.java:3)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.addItemDecoration(RecyclerView.java:2)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.addItemDecoration(RecyclerView.java:9)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at org.mozilla.fenix.HomeActivity$onCreateView$adapter$1.invoke(HomeActivity.kt:7)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at mozilla.components.browser.tabstray.TabsAdapter.onCreateViewHolder(TabsAdapter.kt:1)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:118)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:125)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:12)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:45)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:15)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:9)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:34)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:3)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:13)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:11)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.View.measure(View.java:23190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2725)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1575)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1858)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:696)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-07 11:01:37.666  7831  7831 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mcarare** [comment]
Thank you for reporting this!  related issue:  https://github.com/mozilla-mobile/fenix/issues/10453.

**Comment by pocmo** [comment]
Closing in favor of #10471.

**Comment by andreicristianpetcu** [comment]
@pocmo https://github.com/mozilla-mobile/fenix/issues/10453
