### ISSUE TITLE
FNX-4317 ⁃ [Bug]Onboarding crash on android 5 & 6 devices

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10482]
## Steps to reproduce
1. Install Fenix Nightly Nightly build 200507 from 5/7 and launch it
1. Swipe down on the onboarding screen

### Expected behavior
No issues

### Actual behavior
After swiping a bit down Fenix crashes

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly build 200507 from 5/7

### Notes
Video
![20200507-150057](https://user-images.githubusercontent.com/51314259/81292758-d7d6b500-9074-11ea-837a-987a259ef038.gif)

Logcat 

```kotlin
 --------- beginning of crash
05-07 15:01:04.698 15735-15735/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 15735
    android.view.InflateException: Binary XML file line #61: Binary XML file line #61: Error inflating class ImageButton
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.android.tools.r8.GeneratedOutlineSupport.outline4(outline)
        at org.mozilla.fenix.home.sessioncontrol.SessionControlAdapter.onCreateViewHolder(SessionControlAdapter.kt:1)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:118)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:14)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:152)
        at android.app.ActivityThread.main(ActivityThread.java:5507)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.view.InflateException: Binary XML file line #61: Error inflating class ImageButton
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.android.tools.r8.GeneratedOutlineSupport.outline4(outline) 
        at org.mozilla.fenix.home.sessioncontrol.SessionControlAdapter.onCreateViewHolder(SessionControlAdapter.kt:1) 
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:118) 
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7) 
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28) 
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:14) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.app.ActivityThread.main(ActivityThread.java:5507) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/onboarding_light_theme.xml from drawable resource ID #0x7f080225
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2654)
        at android.content.res.Resources.loadDrawable(Resources.java:2554)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
        at android.view.View.<init>(View.java:3964)
        at android.widget.ImageView.<init>(ImageView.java:145)
        at android.widget.ImageButton.<init>(ImageButton.java:84)
        at android.widget.ImageButton.<init>(ImageButton.java:80)
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:3)
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:2)
        at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:1)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:29)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:21)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.android.tools.r8.GeneratedOutlineSupport.outline4(outline) 
        at org.mozilla.fenix.home.sessioncontrol.SessionControlAdapter.onCreateViewHolder(SessionControlAdapter.kt:1) 
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:118) 
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7) 
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28) 
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:14) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.app.ActivityThread.main(ActivityThread.java:5507) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$onboarding_light_theme__0.xml from color state list resource ID #0x7f080099
        at android.content.res.Resources.loadColorStateListForCookie(Resources.java:2764)
        at android.content.res.Resources.loadColorStateList(Resources.java:2713)
        at android.content.res.TypedArray.getColor(TypedArray.java:439)
        at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1605)
        at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1584)
        at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:666)
        at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:571)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2644)
        at android.content.res.Resources.loadDrawable(Resources.java:2554) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:870) 
        at android.view.View.<init>(View.java:3964) 
        at android.widget.ImageView.<init>(ImageView.java:145) 
        at android.widget.ImageButton.<init>(ImageButton.java:84) 
        at android.widget.ImageButton.<init>(ImageButton.java:80) 
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:3) 
        at androidx.appcompat.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:2) 
        at androidx.appcompat.app.AppCompatViewInflater.createImageButton(AppCompatViewInflater.java:1) 
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:29) 
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:21) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.android.tools.r8.GeneratedOutlineSupport.outline4(outline) 
        at org.mozilla.fenix.home.sessioncontrol.SessionControlAdapter.onCreateViewHolder(SessionControlAdapter.kt:1) 
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:2) 
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:118) 
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:7) 
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:28) 
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:14) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.app.ActivityThread.main(ActivityThread.java:5507) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #16: invalid color state list tag gradient
    	at android.content.res.ColorSta
```

@Mugurell -Please review :relaxed:

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 5/8 - Fenix doesn't crash.
Tested with OnePlus A3 (Android 6.0.1), and Samsung Galaxy Tab A6 (Android 5.1.1). On Samsung device, with android 5, the "red items" are back on onboarding (please see #8982)

<img src="https://user-images.githubusercontent.com/40694158/81389177-18d8d300-9122-11ea-832a-8c27d7ef8709.gif" width="300" height="550" />  

<img src="https://user-images.githubusercontent.com/40694158/81389186-1c6c5a00-9122-11ea-98fa-35e006cc0b0a.gif" width="300" height="550" />
