### ISSUE TITLE
FNX-4382 ⁃ ConcurrentModificationException

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#10559]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7680981/?referrer=github_plugin

```
ConcurrentModificationException: None
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
    at mozilla.telemetry.glean.GleanInternalAPI$initialize$1.invokeSuspend(Glean.kt:16)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
...
(6 additional frame(s) were not displayed)
```

**Comment by ekager** [comment]
Looks to be a Glean issue? Should we move this to AC?

**Comment by liuche** [comment]
Duping to #10170
