### ISSUE TITLE
[Bug] Crash in site permissions

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#10572]
## Steps to reproduce
Ensure firefox had no mic android permission
Open a site and click on the lock icon
Click on the microphone permisson, blocked by Android
Allow
Click on blocked 
Nothing happens
Click again a few times
Crash

### Device information
* Android device: Asus Zenfone (LineageOS)
* Fenix version: Fenix Nightly

**Comment by kbrosnan** [comment]
Assuming LineageOS 16. This is likely just a different way to trigger #5663 / https://bugzilla.mozilla.org/show_bug.cgi?id=1604056

**Comment by Amejia481** [comment]
I'm not able to reproduce the issue on a Pixel 3 with Android 10

**Comment by s-ankur** [comment]
I was able to reproduce it in Redmi Note 4 with latest Nightly. 
![GifMaker_lowquality](https://user-images.githubusercontent.com/33252312/81760781-ad8f5800-94b7-11ea-812b-80387aa97a6b.gif)

**Comment by s-ankur** [comment]
Ensure firefox had no mic android permission, camera permission
Ensure mic site permission is set to blocked
Open a site and click on the lock icon
Click on the microphone permisson, blocked by Android
Allow
Click on blocked
Nothing happens [Already a bug since the site permissions menu should open here]
Click again a few times or on camera permission
Crash

**Comment by ekager** [comment]
Maybe related to this Beta review? 
<img width="463" alt="Screen Shot 2020-07-31 at 8 54 58 PM" src="https://user-images.githubusercontent.com/25442310/89090312-204df800-d370-11ea-8bc7-30e05c230f97.png">

**Comment by s-ankur** [comment]
019f226b-df48-4e86-bb75-fefdd44c9ee9
java.util.NoSuchElementException: Array is empty.
----
java.util.NoSuchElementException: Array is empty.
	at kotlin.collections.ArraysKt.first(Unknown Source:14)
	at org.mozilla.fenix.settings.PhoneFeature$Companion.findFeatureBy(PhoneFeature.kt:4)
	at org.mozilla.fenix.settings.quicksettings.QuickSettingsSheetDialogFragment.onRequestPermissionsResult(QuickSettingsSheetDialogFragment.kt:2)
	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:7)
	at android.app.Activity.requestPermissions(Activity.java:4478)
	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:5)
	at androidx.fragment.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:5)
	at androidx.fragment.app.Fragment.requestPermissions(Fragment.java:3)
	at org.mozilla.fenix.settings.quicksettings.QuickSettingsSheetDialogFragment$onCreateView$1.invoke(QuickSettingsSheetDialogFragment.kt:5)
	at org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsController.handlePermissionToggled(QuickSettingsController.kt:5)
	at org.mozilla.fenix.settings.quicksettings.QuickSettingsInteractor.onPermissionToggled(QuickSettingsInteractor.kt:1)
	at org.mozilla.fenix.settings.quicksettings.WebsitePermissionsView$bindPermission$1.onClick(WebsitePermissionsView.kt:1)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
