### ISSUE TITLE
FNX-4493 ⁃ [Bug] Crash in [@ java.lang.AssertionError: at org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.bindService(ServiceAllocator.java)]

### ISSUE THREAD

**Issue by hertz1** [mozilla-mobile/fenix#10715]
This bug is for crash report [bp-0d8158e2-8ca6-41cd-99a0-19e450200517](https://crash-stats.mozilla.org/report/index/0d8158e2-8ca6-41cd-99a0-19e450200517).

```
Java stack trace:

java.lang.AssertionError
	at org.mozilla.gecko.process.ServiceAllocator$InstanceInfo.bindService(ServiceAllocator.java:3)
	at org.mozilla.gecko.process.GeckoProcessManager$ChildConnection.bind(GeckoProcessManager.java:6)
	at org.mozilla.gecko.process.GeckoProcessManager.start(GeckoProcessManager.java:7)
	at org.mozilla.gecko.process.GeckoProcessManager.lambda$start$4(GeckoProcessManager.java:2)
	at org.mozilla.gecko.process.-$$Lambda$GeckoProcessManager$f3c4adslVLFeRpGUG7Noos477nk.run(Unknown Source:20)
	at org.mozilla.gecko.util.XPCOMEventTarget.runOnLauncherThread(XPCOMEventTarget.java:3)
	at org.mozilla.gecko.process.GeckoProcessManager.start(GeckoProcessManager.java:4)
```

**Comment by hertz1** [comment]
It's being fixed in [Bug 1630229](https://bugzilla.mozilla.org/show_bug.cgi?id=1630229).
