### ISSUE TITLE
FNX-4531 ⁃ [Bug] Intermittent UI test error: videoPlaybackSystemNotificationTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#10756]
Firebase: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.6606eaebeafc7818/testcases/1/test-cases

```
 androidx.test.uiautomator.UiObjectNotFoundException: for text= "Video_Test_Page"
at androidx.test.uiautomator.UiCollection.getChildByText(UiCollection.java:126)
at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:215)
at org.mozilla.fenix.ui.robots.NotificationRobot.verifySystemNotificationExists(NotificationRobot.kt:28)
at org.mozilla.fenix.ui.MediaNotificationTest$videoPlaybackSystemNotificationTest$3.invoke(MediaNotificationTest.kt:57)
at org.mozilla.fenix.ui.MediaNotificationTest$videoPlaybackSystemNotificationTest$3.invoke(MediaNotificationTest.kt:27)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openNotificationShade(BrowserRobot.kt:350)
at org.mozilla.fenix.ui.MediaNotificationTest.videoPlaybackSystemNotificationTest(MediaNotificationTest.kt:56) 
```

**Comment by AaronMT** [comment]
The notification shade is blocking the test during the run which is causing the test to fail. (@sv-ohorvath)

**Comment by AaronMT** [comment]
Can consolidate this and https://github.com/mozilla-mobile/fenix/issues/10762 same thing.

**Comment by isabelrios** [comment]
What I can see from video on https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6337539131377699799/executions/bs.6606eaebeafc7818/video is that the notification is shown before the video test  page is completely loaded
