### ISSUE TITLE
FNX-4567 ⁃ [Bug]Native code crash when trying to sign in on Twitter

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#10794]
## Steps to reproduce
1. Navigate to twitter.com
1. Sign in with valid credentials

### Expected behavior
User is signed in 

### Actual behavior
Native code crash

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: 
• Beta 5.1.0-beta.1 from 5/19
• Nightly 200520 from 5/20

### Notes
Crashed consecutively 2x on Beta, submitted the following crash reports:
• https://crash-stats.mozilla.org/report/index/3a211e76-6e22-45d0-b53d-52fab0200520
• https://crash-stats.mozilla.org/report/index/afe93306-309b-4455-9a3e-0cbab0200520

► Log

```kotlin
05-20 11:27:52.840 1304-1784/? I/ActivityManager: Process org.mozilla.fenix.beta:tab0 (pid 15223) has died
05-20 11:27:52.840 1304-1784/? W/ActivityManager: Scheduling restart of crashed service org.mozilla.fenix.beta/org.mozilla.gecko.process.GeckoChildProcessServices$tab0 in 1000ms
05-20 11:27:52.843 725-725/? I/Zygote: Process 15223 exited due to signal (11)
05-20 11:27:52.845 15175-15196/? W/GeckoEventDispatcher: No listener for GeckoView:WebExtension:Disconnect
05-20 11:27:52.846 1304-1339/? V/ActivityManager: killProcessGroupAsync took 5 ms for PID 15223 on thread 14
05-20 11:27:52.850 15175-15175/? D/GeckoNetworkManager: Incoming event disableNotifications for state OnWithListeners -> OnNoListeners
05-20 11:27:52.858 15175-15211/? I/Gecko: [Parent 15175, Unnamed thread 7f75544240] WARNING: waitpid failed pid:15223 errno:10: file /builds/worker/checkouts/gecko/ipc/chromium/src/base/process_util_posix.cc, line 237
05-20 11:27:52.869 1304-2238/? I/ActivityManager: Start proc 16018:org.mozilla.fenix.beta:mozilla.components.lib.crash.CrashHandler/u0a286 for service org.mozilla.fenix.beta/mozilla.components.lib.crash.handler.CrashHandlerService
05-20 11:27:52.869 2088-7779/? I/TiresiasImpl: TiresiasImpl.resetSession():1227 resetSession(): Reset failed, no active session.
05-20 11:27:52.871 15175-16011/? E/GeckoEditable: Remote call failed
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:527)
        at org.mozilla.gecko.IGeckoEditableChild$Stub$Proxy.onKeyEvent(IGeckoEditableChild.java:17)
        at org.mozilla.geckoview.GeckoEditable.onKeyEvent(GeckoEditable.java:7)
        at org.mozilla.geckoview.GeckoEditable.sendCharKeyEvents(GeckoEditable.java:7)
        at org.mozilla.geckoview.GeckoEditable.icPerformAction(GeckoEditable.java:19)
        at org.mozilla.geckoview.GeckoEditable.icOfferAction(GeckoEditable.java:9)
        at org.mozilla.geckoview.GeckoEditable.replace(GeckoEditable.java:10)
        at org.mozilla.geckoview.GeckoEditable.replace(GeckoEditable.java:16)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.mozilla.geckoview.GeckoEditable.invoke(GeckoEditable.java:4)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy10.replace(Unknown Source)
        at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:691)
        at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
        at org.mozilla.geckoview.GeckoInputConnection.commitText(GeckoInputConnection.java:6)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:152)
        at org.mozilla.geckoview.GeckoInputConnection$9.run(GeckoInputConnection.java:6)
        at java.lang.Thread.run(Thread.java:818)
05-20 11:27:52.871 15175-16011/? E/GeckoEditable: Remote call failed
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:527)
        at org.mozilla.gecko.IGeckoEditableChild$Stub$Proxy.onImeRequestCommit(IGeckoEditableChild.java:4)
        at org.mozilla.geckoview.GeckoEditable.setBatchMode(GeckoEditable.java:6)
        at org.mozilla.geckoview.GeckoInputConnection.endBatchEdit(GeckoInputConnection.java:7)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:407)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:152)
        at org.mozilla.geckoview.GeckoInputConnection$9.run(GeckoInputConnection.java:6)
        at java.lang.Thread.run(Thread.java:818)
05-20 11:27:53.101 15175-15175/? D/AutofillSupport: clear()
05-20 11:27:53.101 15175-15175/? W/GeckoSession: Attempted to close a GeckoSession that was already closed.
05-20 11:27:53.129 15175-15175/? W/GeckoEventDispatcher: No listener for GeckoView:AccessibilityEnabled
05-20 11:27:53.131 15175-15401/? I/Gecko: [GFX1-]: Failed to create EGLContext!: 0x300c
05-20 11:27:53.150 16018-16031/? E/mozac/CrashReporter: CrashHandlerService received native code crash
05-20 11:27:53.152 16018-16031/? I/mozac/CrashReporter: Received crash: NativeCodeCrash(minidumpPath=/data/user/0/org.mozilla.fenix.beta/files/mozilla/Crash Reports/pending/4990b832-b861-9823-3220-485ad47e9a14.dmp, minidumpSuccess=false, extrasPath=/data/user/0/org.mozilla.fenix.beta/files/mozilla/Crash Reports/pending/4990b832-b861-9823-3220-485ad47e9a14.extra, isFatal=false, breadcrumbs=[], uuid=addf5cb2-d665-4a0f-8550-33b8a0be4ae5)
05-20 11:27:53.184 1304-2237/? I/ActivityManager: Start proc 16032:org.mozilla.fenix.beta:tab0/u0a286 for service org.mozilla.fenix.beta/org.mozilla.gecko.process.GeckoChildProcessServices$tab0
05-20 11:27:53.186 15175-15217/? D/ServiceAllocator: org.mozilla.gecko.process.GeckoChildProcessServices$tab0 updateBindings: BACKGROUND priority, 0 importance, 2 successful binds, 0 failed binds, 0 successful unbinds, 0 failed unbinds
05-20 11:27:53.215 16018-16031/? I/mozac/CrashReporter: Invoking non-fatal PendingIntent
05-20 11:27:53.215 1304-1835/? I/ActivityManager: START u0 {flg=0x14000000 cmp=org.mozilla.fenix.beta/org.mozilla.fenix.HomeActivity (has extras)} from uid 10286 pid -1 on display 0
05-20 11:27:53.219 16018-16031/? I/art: System.exit called, status: 0
05-20 11:27:53.219 16018-16031/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-20 11:27:53.222 15175-15195/? I/mozac/CrashReporter: Crash report submitted to 1 telemetry services
```

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both the latest **`Nightly Build 200527 from 5/27`** & **`Beta 5.1.0-beta.2  from 5/27`** using a OnePlus A3 (Android 6.0.1)
