### ISSUE TITLE
FNX-4641 ⁃ Push Storage Error: "Could not open database file"

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#10867]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8487654/?referrer=github_plugin

```
StorageError: Error(

Storage Error: "Could not open database file \"/data/data/org.mozilla.fenix.nightly/files/push.sqlite\"")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:10)
    at mozilla.appservices.push.PushManager.<init>(PushManager.kt:12)
    at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:13)
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:10)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(4 additional frame(s) were not displayed)

PushError$Rust: Error(

Storage Error: "Could not open database file \"/data/data/org.mozilla.fenix.nightly/files/push.sqlite\"")
    at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$exceptionHandler$1.handleException(CoroutineExceptionHandler.kt:5)
    at androidx.transition.CanvasUtils.handleCoroutineException(CanvasUtils.java:2)
    at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:2)
    at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:17)
    at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:21)
...
(8 additional frame(s) were not displayed)

[INFO] Error(

Storage Error: "Could not open database file \"/data/data/org.mozilla.fenix.nightly/files/push.sqlite\"")
```

**Comment by jonalmeida** [comment]
It looks like this is from a single rooted device. We should probably close it.
