### ISSUE TITLE
FNX-4653 ⁃ [Bug] Crash on a dealer locator

### ISSUE THREAD

**Issue by massic80** [mozilla-mobile/fenix#10880]
## Steps to reproduce
Visit 
https://www.gruppoapi.com/ricerca-stazioni-servizio

### Expected behavior
It should display the map for the gas stations

### Actual behavior
It crashes

### Device information
* Android device: Asus Zenfone 4 Max
* Fenix version:
Nightly 200523 06:00 (Build #21440607)
43.0.20200520190033, 3aa8dc692
GV: 78.0a1-20200520033931
AS: 0.59.0
I also tried on a parallel Firefox Mobile Nightly (based on the same source) installation and got the same result.
Anything is OK on Chrome

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/report/index/e2b8b902-2128-4421-bf4f-d1be60200523

```
java.lang.IllegalArgumentException
	at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:12)
	at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:70)
	at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:18)
	at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by ekager** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/7142

**Comment by sv-ohorvath** [comment]
Not crashing anymore in today's Nightly 6/5. Verified as fixed on Pixel 4 (Android 10)
