### ISSUE TITLE
FNX-12159 ⁃ [Bug] Can't change language on local builds

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#11259]
## Steps to reproduce
Build geckoNightlyDebug or geckoBetaDebug and install on real phone (XZ1 Android 10) or emulator (api 29).
Tried fennecNightly and fennecBeta with my own key but no luck. Can't change on local builds.

### Expected behavior
I can change language.

### Actual behavior
Can't change language.

![](https://user-images.githubusercontent.com/17825767/83876325-5ccef000-a741-11ea-8c0c-09fe76e5e82d.png)

### Device information
* Android device: Xperia XZ1 Android 10
* Emulator: 

```
Name: Pixel_3a_API_29

CPU/ABI: Intel Atom (x86_64)

Path: C:\Users\calis\.android\avd\Pixel_3a_API_29_1.avd

Target: default [Default Android System Image] (API level 29)

Skin: pixel_3a

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_3a

hw.lcd.width: 1080

hw.initialOrientation: Portrait

image.androidVersion.api: 29

tag.id: default

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel 3a API 29

hw.gpu.mode: host

hw.ramSize: 2048

PlayStore.enabled: false

fastboot.forceColdBoot: yes

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2220

vm.heapSize: 512

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-29\default\x86_64\

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_3a_API_29

hw.lcd.density: 440

hw.arc: false

hw.device.hash2: MD5:0e6953ebf01bdc6b33a2f54746629c50

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: no

hw.trackBall: no

hw.battery: yes

hw.sdCard: no

tag.display: Default Android System Image

runtime.network.latency: none

disk.dataPartition.size: 2G

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

* Fenix version: master

**Comment by ekager** [comment]
Hm I'm not seeing this on master. Are you connected to a network? Are you also seeing this on Nightly?

**Comment by hakkikaancaliskan** [comment]
@ekager Yes, i have network. On all build variants. On emulator and real device.

**Comment by ekager** [comment]
What happens if you try to search?

**Comment by hakkikaancaliskan** [comment]
Sadly nothing :(
![Screenshot_1591381985](https://user-images.githubusercontent.com/17825767/83911201-89502f80-a774-11ea-9440-3e56be24f94a.png)

**Comment by hakkikaancaliskan** [comment]
```
2020-06-11 23:15:29.057 29910-29910/org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation; ~duration=17 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:592)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:123)
        at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:99)
        at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:42)
        at org.mozilla.fenix.settings.advanced.LocaleManagerExtensionKt.getSelectedLocale(LocaleManagerExtension.kt:39)
        at org.mozilla.fenix.settings.advanced.LocaleManagerExtensionKt.getSelectedLocale$default(LocaleManagerExtension.kt:37)
        at org.mozilla.fenix.settings.advanced.LocaleSettingsFragment.getStore(LocaleSettingsFragment.kt:94)
        at org.mozilla.fenix.settings.advanced.LocaleSettingsFragment.onCreateView(LocaleSettingsFragment.kt:43)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

@ekager looks like problem is strictmode, how can i close it to test?

**Comment by hakkikaancaliskan** [comment]
Oh no, found the problem. I've printed out foundLocalesString in build.gradle (fetches from there) and it's empty, maybe it can't read on my computer???
![resim](https://user-images.githubusercontent.com/17825767/84438649-90c57c00-ac3f-11ea-836d-07dcc553df52.png)

**Comment by hakkikaancaliskan** [comment]
Can't tokenize('/'). If I convert / to \ i get this `unexpected token`

![resim](https://user-images.githubusercontent.com/17825767/84442211-d71dd980-ac45-11ea-84a8-03f79a9ab491.png)

**Comment by hakkikaancaliskan** [comment]
```
fileTree("src/main/res").visit { FileVisitDetails details ->
        if(details.file.path.endsWith("strings.xml")){
            String separator = "\\"
            def languageCode = details.file.parent.replaceAll(Pattern.quote(separator), "\\\\").tokenize("\\\\").last().replaceAll('values-','').replaceAll('-r','-')

            println("tokenized: " + details.file.parent.replaceAll(Pattern.quote(separator), "\\\\").tokenize("\\\\"))

            languageCode = (languageCode == "values") ? "en-US" : languageCode
            foundLocales.append("\"").append(languageCode).append("\"").append(",")
        }
    }
```

I've solved with hacky way.

![resim](https://user-images.githubusercontent.com/17825767/84443189-c8382680-ac47-11ea-8185-7b14d098732e.png)
