### ISSUE TITLE
java.lang.IllegalStateException: Compositor must be ready before pixels can be captured

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#11297]
Compositor must be ready before pixels can be captured

> java.lang.IllegalStateException: Compositor must be ready before pixels can be captured
	at org.mozilla.geckoview.GeckoDisplay$ScreenshotBuilder.capture(GeckoDisplay.java:27)
	at org.mozilla.geckoview.GeckoDisplay.capturePixels(GeckoDisplay.java:1)
	at org.mozilla.geckoview.GeckoView$Display.capturePixels(GeckoView.java:3)
	at org.mozilla.geckoview.GeckoView.capturePixels(GeckoView.java:1)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.captureThumbnail(GeckoEngineView.kt:2)
	at org.mozilla.fenix.browser.BrowserAnimator$captureEngineViewAndDrawStatically$$inlined$let$lambda$1.invokeSuspend(BrowserAnimator.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
	at androidx.core.app.AppOpsManagerCompat.startCoroutineCancellable(AppOpsManagerCompat.java:1)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:18)
	at kotlinx.coroutines.AwaitKt.launch(Await.kt:6)
	at kotlinx.coroutines.AwaitKt.launch$default(Await.kt:2)
	at org.mozilla.fenix.browser.BrowserAnimator.captureEngineViewAndDrawStatically(BrowserAnimator.kt:2)
	at org.mozilla.fenix.browser.BrowserAnimator$beginAnimateInIfNecessary$1.invokeSuspend(BrowserAnimator.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5358)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/?query=9b13807b4eee4a0394c32e245ef7bb0d

**Comment by kglazko** [comment]
Does this result in a crash? Or what happens?

**Comment by leela52452** [comment]
> Does this result in a crash? Or what happens?

crash

**Comment by kglazko** [comment]
Thank you for letting me know! I've categorized it as a crash.

**Comment by kbrosnan** [comment]
Looks like this was a common crash about 20-25 days ago. The rate of crashes has tapered off significantly. Looks to be fixed by  https://github.com/mozilla-mobile/android-components/issues/6680


* Sentry issue: [FENIX-FENNEC-BETA-X8](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8053505/)
* Sentry issue: [FENIX-56T](https://sentry.prod.mozaws.net/operations/fenix/issues/7735773/)
* Sentry issue: [FENIX-FENNEC-NIGHTLY-2DC](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8615851/)
