### ISSUE TITLE
[Bug] Synced Tabs Crash RemoteTabProviderException

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#11294]
* [x] AS bug: https://github.com/mozilla/application-services/issues/3214

RemoteTabProviderException

Protobuf decode error: failed to decode Protobuf message: unexpected end group tag

>mozilla.appservices.remotetabs.RemoteTabProviderException: Protobuf decode error: failed to decode Protobuf message: unexpected end group tag
    at mozilla.appservices.remotetabs.rust.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs(RemoteTabsProvider.kt:14)
    at mozilla.components.browser.storage.sync.RemoteTabsStorage$store$2.invokeSuspend(RemoteTabsStorage.kt:16)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/8617877/?query=RemoteTabProviderException

**Comment by liuche** [comment]
@eoger  👀

**Comment by ekager** [comment]
jira issue is https://jira.mozilla.com/browse/SYNC-1382

**Comment by thomcc** [comment]
We believe v61.0.3 has a fix for this https://github.com/mozilla/application-services/releases/tag/v61.0.3. We're preparing a workaround if that proves not to be the actual issue, which is possible since we were only able to *mostly* repro the issue in question.

**Comment by liuche** [comment]
There's an AC PR to bump AS to 61.0.4, and once that lands, we should remove this feature flag. (And if this doesn't work out, we can re-flag it)

**Comment by ekager** [comment]
We're now on 61.0.6 we should keep an eye on Sentry for a day or two to see if these crashes go down.

**Comment by thomcc** [comment]
This looks like it's still had a couple errors come in under 61.0.6 :(

I'll reopen the issue on the a-s side and prepare a patch switching from protobufs to JSON, which shouldn't have this sort of issue.

**Comment by kbrosnan** [comment]
Also https://github.com/mozilla-mobile/android-components/issues/7426
