### ISSUE TITLE
FNX-12276 ⁃ [Bug]Tabs Tray: Crash kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11360]
## Prerequisites
Have a tabs opened in Normal Browsing
Don't have any open tabs in PB

## Steps to reproduce
1. Open the Tabs Tray
1. Put Fenix in background
1. Resume Fenix
1. From the Tabs Tray tap the PB Open tabs

### Expected behavior
Properly switches to the PB Open tabs

### Actual behavior
Crash

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
* Fenix version: **`Nightly Build 200609 from 6/9`**

### Notes
► Video
![20200609-123003](https://user-images.githubusercontent.com/51314259/84134889-e9cfbd00-aa51-11ea-9326-cc5839bca4cd.gif)

c637dbea-535b-4225-9899-8b3ed6ed0151

## kotlin.KotlinNullPointerException
```
kotlin.KotlinNullPointerException
at kotlin.jvm.internal.ArrayIteratorKt.throwNpe(ArrayIterator.kt:1)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment$onViewCreated$1.invoke(TabTrayDialogFragment.kt:5)
at org.mozilla.fenix.tabtray.TabTrayView.onTabSelected(TabTrayView.kt:6)
at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:15)
at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1)
at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:6)
at android.view.View.performClickInternal(View.java:7236)
at android.view.View.access$3600(View.java:801)
at android.view.View$PerformClick.run(View.java:27892)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** and **`Beta 5.2.0-beta.2 from 6/16`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200618-112349](https://user-images.githubusercontent.com/51314259/84997162-df4eab00-b156-11ea-9a8b-6a60807dd989.gif)
