### ISSUE TITLE
[Bug] crash  invalid value for param: totalBytes

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/fenix#11415]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8644245/?query=is%3Aunresolved%20level%3Afatal

This looks like it started June 5, and has been increasing in crashes since then. Doesn't look like a ton but maybe it's an easy fix?

> java.lang.IllegalArgumentException:  invalid value for param: totalBytes
	at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1220)
	at android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1206)
	at mozilla.components.feature.downloads.AbstractFetchDownloadService.addToDownloadSystemDatabaseCompat$feature_downloads_release(AbstractFetchDownloadService.kt:18)
	at mozilla.components.feature.downloads.AbstractFetchDownloadService.updateDownloadNotification$feature_downloads_release(AbstractFetchDownloadService.kt:5)
	at mozilla.components.feature.downloads.AbstractFetchDownloadService.access$updateDownloadNotification(AbstractFetchDownloadService.kt:5)
	at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$2.invokeSuspend(AbstractFetchDownloadService.kt:7)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5358)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)

**Comment by liuche** [comment]
@kglazko do you know what might be causing this?

(Also, do you prefer I tag you, or should I wait for the normal triage/nomination process to happen? I was going through sentry because I'm cutting a release and saw that this was showing up on Nightly)

**Comment by rvandermeulen** [comment]
If it helps, I noticed when filing the upstream Bugzilla bug that these crashes first started with the 20200603092905 Nightly build.

**Comment by Amejia481** [comment]
> @kglazko do you know what might be causing this?
> 
> (Also, do you prefer I tag you, or should I wait for the normal triage/nomination process to happen? I was going through sentry because I'm cutting a release and saw that this was showing up on Nightly)

I believe this is the same as https://github.com/mozilla-mobile/android-components/issues/7401#issuecomment-644851586, we also opened [a bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1632594#c5) to fix the issue on GV

**Comment by Amejia481** [comment]
We put a [patch on](https://github.com/mozilla-mobile/android-components/pull/7400/files)  `45.0.20200616130058`  It should be already fixed on nightly, if you see new occurrences please let me know.

**Comment by liuche** [comment]
Great! Looks like that made it into the AC 46 release that is going out with 5.2, so I'll look for this as I monitor the release and will close this if it's gone!

**Comment by ekager** [comment]
@liuche looking at the Sentry link this looks resolved?

**Comment by liuche** [comment]
Yep! looks good, let's close it.
