### ISSUE TITLE
FNX-12353 ⁃ [Bug]Tabs Tray: Beta 5.2.0-beta.1 Crash : java.lang.IllegalArgumentException: Session with same ID already exists

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11420]
## Prerequisites
Have an open tab

## Steps to reproduce
1. Open the Tabs Tray
1. Put Fenix in background
1. Resume Fenix
1. Swipe delete the tab and tap Undo

### Expected behavior
The tab should remain displayed in the Tabs Tray

### Actual behavior
Crash

### Device information
* Android device: 
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)
* Fenix version: Beta 5.2.0-beta.1 from 6/10

### Notes
❗ Not reproducible on the latest Nightly Build 20610 from 6/10

► Video
![20200610-153940 (1)](https://user-images.githubusercontent.com/51314259/84270125-de07f780-ab32-11ea-8f40-126fcd20d41c.gif)

► Crash Report
3bf04a29-06c2-4ba2-814a-b0fbf209d1bf
java.lang.IllegalArgumentException: Session with same ID already exists

* Sentry: https://sentry.prod.mozaws.net/operations/fenix-beta/?query=cf9af139b30a48f989b48cdd9eef4306
* Socorro: https://crash-stats.mozilla.org/report/index/bp-d28851fd-85b3-49e0-9a02-902720200610
----

```kotlin
java.lang.IllegalArgumentException: Session with same ID already exists
at mozilla.components.browser.session.LegacySessionManager.addInternal(LegacySessionManager.kt:15)
at mozilla.components.browser.session.LegacySessionManager.addInternal$default(LegacySessionManager.kt:1)
at mozilla.components.browser.session.LegacySessionManager.add(LegacySessionManager.kt:2)
at mozilla.components.browser.session.SessionManager.add(SessionManager.kt:19)
at mozilla.components.browser.session.SessionManager.add$default(SessionManager.kt:1)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment$onTabClosed$$inlined$let$lambda$1.invokeSuspend(TabTrayDialogFragment.kt:3)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment$onTabClosed$$inlined$let$lambda$1.invoke(TabTrayDialogFragment.kt:2)
at org.mozilla.fenix.utils.UndoKt$allowUndo$2$snackbar$1$1.invokeSuspend(Undo.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
at androidx.core.app.AppOpsManagerCompat.startCoroutineCancellable(AppOpsManagerCompat.java:1)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:18)
at kotlinx.coroutines.AwaitKt.launch(Await.kt:6)
at kotlinx.coroutines.AwaitKt.launch$default(Await.kt:2)
at org.mozilla.fenix.utils.UndoKt$allowUndo$2$snackbar$1.invoke(Undo.kt:2)
at org.mozilla.fenix.components.FenixSnackbar$setAction$$inlined$apply$lambda$1.onClick(FenixSnackbar.kt:1)
at android.view.View.performClick(View.java:5233)
at android.view.View$PerformClick.run(View.java:21209)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5507)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on both **`Nightly 200618 from 6/18`** and **`Beta 5.2.0-beta.2 from 6/16`** using the following devices:
• Google Pixel 4 XL (10)
• OnePlus 6T (Android 9)
• Samsung Galaxy S9 (Android 8)
• Nexus 9 (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)
• Xiaomi Mi Pad 2 (Android 5.1)

► Video
![20200618-113952](https://user-images.githubusercontent.com/51314259/84998714-dbbc2380-b158-11ea-9400-e83e2cb736f5.gif)
