### ISSUE TITLE
FNX2-13569 ⁃ [Bug]Tabs Tray: Native code crash after deleting and undoing deletion of reader mode tabs

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#11685]
## Steps to reproduce
1. Navigate to: https://en.wikipedia.org/wiki/Main_Page
1. Switch to Reader mode
1. In a new tab open https://en.wikipedia.org/wiki/Main_Page
1. Switch to Reader mode
1. Open the Tabs Tray
1. Swipe Delete the **Highlighted Tab**
1. Undo
1. Swipe Delete the **Other Tab**
1. Undo
1. Swipe Delete the **Highlighted Tab**

### Expected behavior
The deletion undo should properly work

### Actual behavior
Native code crash

### Device information
* Android device: OnePlus A3 (Android 6.0.1)
* Fenix version: Nightly 200617 from 6/17

### Notes
[Logcat](https://github.com/mozilla-mobile/fenix/files/4792142/read.txt)
❗ No Socorro link

► Video
![20200617-142020](https://user-images.githubusercontent.com/51314259/84893577-20d44d00-b0a8-11ea-8868-58702d925345.gif)

Related to #11683

**Comment by csadilek** [comment]
This look like (similar signature): https://bugzilla.mozilla.org/show_bug.cgi?id=1644561

**Comment by sv-ohorvath** [comment]
Verified as fixed on latest Nightly build 7/7. Device: HTC Desire 820 (Android 6.0.1)

**Comment by AndiAJ** [comment]
Hi, managed to reproduce it on RC 81.1.1 using a OnePlus A3 (Android 6.0.1)

22e2b1e0-b858-410f-aacd-daa715f99b89
java.lang.IllegalArgumentException: Session with same ID already exists
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=061ec2ed742d4e028a4dab48b5db21f5
* Socorro: https://crash-stats.mozilla.org/report/index/bp-5678f498-eef9-4b43-8761-db6750200918
----
java.lang.IllegalArgumentException: Session with same ID already exists
at mozilla.components.browser.session.LegacySessionManager.addInternal(LegacySessionManager.kt:13)
at mozilla.components.browser.session.LegacySessionManager.addInternal$default(LegacySessionManager.kt:1)
at mozilla.components.browser.session.LegacySessionManager.add(LegacySessionManager.kt:2)
at mozilla.components.browser.session.SessionManager.add(SessionManager.kt:16)
at mozilla.components.browser.session.SessionManager.add$default(SessionManager.kt:1)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment$showUndoSnackbarForTab$1.invokeSuspend(TabTrayDialogFragment.kt:3)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment$showUndoSnackbarForTab$1.invoke(TabTrayDialogFragment.kt:2)
at org.mozilla.fenix.utils.UndoKt$allowUndo$2$snackbar$1$1.invokeSuspend(Undo.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
at androidx.core.app.AppOpsManagerCompat.startCoroutineCancellable(AppOpsManagerCompat.java:1)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:17)
at kotlinx.coroutines.AwaitKt.launch(Await.kt:6)
at kotlinx.coroutines.AwaitKt.launch$default(Await.kt:2)
at org.mozilla.fenix.utils.UndoKt$allowUndo$2$snackbar$1.invoke(Undo.kt:2)
at org.mozilla.fenix.components.FenixSnackbar$setAction$$inlined$apply$lambda$1.onClick(FenixSnackbar.kt:1)
at android.view.View.performClick(View.java:5233)
at android.view.View$PerformClick.run(View.java:21209)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5507)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by AndiAJ** [comment]
Reproducible Firefox Beta 82.0.0-beta.2 using a OnePlus A3 (Android 6.0.1)
