### ISSUE TITLE
FNX-12705 ⁃ [Bug] Intermittent failure threeDotMenuItemsTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#11725]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=306716916&repo=fenix

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:372)
at org.mozilla.fenix.ui.ThreeDotMenuMainTest.threeDotMenuItemsTest(ThreeDotMenuMainTest.kt:60)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

There are these before:
06-17 19:16:49.214: I/MockWebServer(9732): MockWebServer[33170] done accepting connections: Socket closed
06-17 19:16:49.218: W/lla.fenix.debu(9732): Accessing hidden field Landroid/app/Activity;->mResultCode:I (light greylist, reflection)
06-17 19:16:49.218: D/StrictMode(9732): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultCode:I
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.lang.Class.getDeclaredField(Native Method)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:469)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule$1.run(ActivityTestRule.java:415)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Handler.handleCallback(Handler.java:873)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Looper.loop(Looper.java:193)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.lang.reflect.Method.invoke(Native Method)
06-17 19:16:49.218: D/StrictMode(9732): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-17 19:16:49.218: D/StrictMode(9732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-17 19:16:49.218: W/lla.fenix.debu(9732): Accessing hidden field Landroid/app/Activity;->mResultData:Landroid/content/Intent; (light greylist, reflection)
06-17 19:16:49.218: D/StrictMode(9732): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultData:Landroid/content/Intent;
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.lang.Class.getDeclaredField(Native Method)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:472)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
06-17 19:16:49.218: D/StrictMode(9732): 	at androidx.test.rule.ActivityTestRule$1.run(ActivityTestRule.java:415)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Handler.handleCallback(Handler.java:873)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.os.Looper.loop(Looper.java:193)
06-17 19:16:49.218: D/StrictMode(9732): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
06-17 19:16:49.218: D/StrictMode(9732): 	at java.lang.reflect.Method.invoke(Native Method)
06-17 19:16:49.218: D/StrictMode(9732): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-17 19:16:49.218: D/StrictMode(9732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sv-ohorvath** [comment]
Saw this too late, I'll close it in favor of https://github.com/mozilla-mobile/fenix/issues/11764
