### ISSUE TITLE
FNX-4851 ⁃ Fenix crashing when visiting scalar-conf.com

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#1177]
Stack trace doesn't really have anything useful. Must be happening inside GV

```
2019-03-25 12:40:39.300 12584-12725/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: org.mozilla.fenix.debug, PID: 12584
    java.lang.Exception: data is null
        at org.mozilla.geckoview.GeckoSession$CallbackResult.sendError(GeckoSession.java:267)
        at org.mozilla.gecko.EventDispatcher$JavaCallbackDelegate$1.run(EventDispatcher.java:466)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at org.mozilla.gecko.util.GeckoBackgroundThread.run(GeckoBackgroundThread.java:41)
```

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-64](https://sentry.prod.mozaws.net/operations/fenix/issues/5329507/)

**Comment by cpeterso** [comment]
I filed a GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1538942

**Comment by cpeterso** [comment]
This crash should be fixed once Fenix and RB update to a new GV 67 Beta build.

**Comment by vesta0** [comment]
@kbrosnan how can we verify that this crash has been fixed?

**Comment by kbrosnan** [comment]
Using a current build with Gecko 68 works.
