### ISSUE TITLE
[Crash]  06-21 15:44:16.315 W/GeckoLinker(32103): /data/app/org.mozilla.fenix-1/lib/arm/libsoftokn3.so: unhandled flags #8 not handled

### ISSUE THREAD

**Issue by WKSuperPower** [mozilla-mobile/fenix#11791]
## Steps to reproduce
Go to Setting --> About Firefox Preview --> Crashes --> Socorro

### Expected behavior
Fenix should fall back to the list of reported issues when pressing the back button

### Actual behavior
Fenix crashes by pressing the device back button:

06-21 15:44:16.315 W/GeckoLinker(32103): /data/app/org.mozilla.fenix-1/lib/arm/libsoftokn3.so: Relocation to NULL @0x00023ffc for symbol "__cxa_type_match"

06-21 15:44:16.315 W/GeckoLinker(32103): /data/app/org.mozilla.fenix-1/lib/arm/libfreebl3.so: unhandled flags #8 not handled

06-21 15:44:14.523 W/GeckoLinker(32103): /data/app/org.mozilla.fenix-1/lib/arm/liblgpllibs.so: unhandled flags #8 not handled

### Device information
* Android device: 5.1.1 (API 22)
* Fenix version: 5.1.0

**Comment by WKSuperPower** [comment]
java.lang.IllegalStateException
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6917)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by Diana-Rus** [comment]
Hi, I can reproduce this issue with Sony Xperia Z5 (Android 7) on latest Firefox Preview Nightly 6/22

Note:
- I could not reproduce the issue with Samsung Galaxy S9 (Android 8), after the page loads and then tapping back, the app will close without generating a crash.

Crash Signature: libc.so@0x49e48
Crash link: https://crash-stats.mozilla.org/report/index/490f0073-c987-47ce-b1ca-d33480200622#tab-details

**Comment by WKSuperPower** [comment]
> Hi, I can reproduce this issue with Sony Xperia Z5 (Android 7) on latest Firefox Preview Nightly 6/22
> 
> Note:
> 
>     * I could not reproduce the issue with Samsung Galaxy S9 (Android 8), after the page loads and then tapping back, the app will close without generating a crash.
> 
> 
> Crash Signature: libc.so@0x49e48
> Crash link: https://crash-stats.mozilla.org/report/index/490f0073-c987-47ce-b1ca-d33480200622#tab-details

@Diana-Rus In my, the Crash Signature is: java.lang.IllegalStateException

Crash Link: 
https://crash-stats.mozilla.org/report/index/4443d4e2-817e-4182-9068-914600200621

**Comment by Diana-Rus** [comment]
Hey, yes seems to count when you do the back action, in case you do it while the page is loading seems to generate the crash with Signature: libc.so@0x49e48.

The crash with signature java.lang.IllegalStateException: FragmentManager has been destroyed, seems that can be generated after the first crash, if accessing the Socorro link multiple times, and same amount of tapping the back button, over 10 - 15 times and it will first be generated without a Socorro link.
Only the second time of encountering the crash, will the Socorro and Sentry link be present.

Sentry link: https://sentry.prod.mozaws.net/operations/fenix-nightly/?query=86a5020fef03402c87e15bc3353ea06b
Crash link: https://crash-stats.mozilla.org/report/index/bp-66accd70-1cf9-40c7-aa4a-0cdfd0200622

First crash - under same signature - java.lang.IllegalStateException: FragmentManager has been destroyed - (when no link to socorro is present)
-  java.lang.IllegalStateException: Unable to get current module info in ModuleManager created with non-module Context
        at com.google.android.chimera.config.ModuleManager.getCurrentModule(:com.google.android.gms@201817021@20.18.17 (040408-311416286):2)
        at aeid.a(:com.google.android.gms@201817021@20.18.17 (040408-311416286):3)
        at aeig.b(:com.google.android.gms@201817021@20.18.17 (040408-311416286):9)
        at aeeo.a(Unknown Source)
        at rjt.a(:com.google.android.gms@201817021@20.18.17 (040408-311416286):0)
        at rgd.c(:com.google.android.gms@201817021@20.18.17 (040408-311416286):1)
        at rgb.b(:com.google.android.gms@201817021@20.18.17 (040408-311416286):1)
        at rir.b(:com.google.android.gms@201817021@20.18.17 (040408-311416286):6)
        at rir.c(:com.google.android.gms@201817021@20.18.17 (040408-311416286):5)
        at rir.a(:com.google.android.gms@201817021@20.18.17 (040408-311416286):57)
        at riv.handleMessage(:com.google.android.gms@201817021@20.18.17 (040408-311416286):69)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at adxm.a(:com.google.android.gms@201817021@20.18.17 (040408-311416286):2)
        at adxm.dispatchMessage(:com.google.android.gms@201817021@20.18.17 (040408-311416286):14)
        at android.os.Looper.loop(Looper.java:241)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2020-06-22 15:30:02.734 12220-12220/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: FragmentManager has been destroyed

Second crash - under the same signature: 
- java.lang.IllegalStateException: FragmentManager has been destroyed
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Note: 
- When tapping on the back button after accessing Sentry link, it will be trigger, the same goes when tapping on the Sentry link
- I'll also make a rectification that I can reproduce the crash Signature: libc.so@0x49e48 and the crash with signature java.lang.IllegalStateException: FragmentManager has been destroyed with Samsung Galaxy S9 (Android 8) as well.

**Comment by Diana-Rus** [comment]
> crash with Signature: libc.so@0x49e48

I'll create a new ticket for this crash as it happens with other pages as well.
