### ISSUE TITLE
FNX-4857 ⁃ Fenix crashes when clicking on a search term

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#1187]
## Steps to reproduce
* Search for "test"
* Click on search term (not an actual page link)
* observe crash

### Device information
* Latest build on play store.
* Android device: Samsung S10e
* Fenix version: 1.0.1913

**Comment by agi90** [comment]
```
03-26 22:42:42.162 16440 16440 E AndroidRuntime: FATAL EXCEPTION: main
03-26 22:42:42.162 16440 16440 E AndroidRuntime: Process: org.mozilla.fenix, PID: 16440
03-26 22:42:42.162 16440 16440 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | No enum constant org.mozilla.fenix.GleanMetrics.Events.performedSearchKeys.search_suggestion
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:2)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:3)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:5)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:4)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:4)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:13)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.search.awesomebar.AwesomeBarUIView$searchUseCase$1.invoke(AwesomeBarUIView.kt:1)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at mozilla.components.feature.search.SearchUseCases$SearchUseCase$DefaultImpls.invoke$default(SearchUseCases.kt:1)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at mozilla.components.feature.awesomebar.provider.SearchSuggestionProvider$createMultipleSuggestions$$inlined$forEachIndexed$lambda$2.invoke(SearchSuggestionProvider.kt:1)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at mozilla.components.browser.awesomebar.layout.DefaultSuggestionViewHolder$Default$bind$1.onClick(DefaultSuggestionViewHolder.kt:1)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.view.View.performClick(View.java:7352)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7318)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.view.View.access$3200(View.java:846)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27801)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7032)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: No enum constant org.mozilla.fenix.GleanMetrics.Events.performedSearchKeys.search_suggestion
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at java.lang.Enum.valueOf(Enum.java:258)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.GleanMetrics.Events$performedSearchKeys.valueOf(Unknown Source:2)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.components.metrics.GleanMetricsServiceKt$wrapper$4.invoke(GleanMetricsService.kt:1)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.components.metrics.GleanMetricsService.track(GleanMetricsService.kt:8)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.components.metrics.Metrics.track(Metrics.kt:6)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at org.mozilla.fenix.search.SearchFragment$onStart$2.accept(SearchFragment.kt:11)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:2)
03-26 22:42:42.162 16440 16440 E AndroidRuntime: 	... 18 more
```

**Comment by Verdi** [comment]
This happens for me too. Also when I just type and hit the go (right arrow on keyboard) button.
### Device
Nokia 3.1
Fenix version: 1.0.1913

**Comment by Verdi** [comment]
The latest nightly (3/26 @4:32 pm) fixes this for me.

Version: 1.0.1913 
Build #: 10851633
Gecko: 67.0-20190318154932

**Comment by bsurd** [comment]
Verified on multiple devices with the latest build, the issue is no longer reproducible.
