### ISSUE TITLE
FNX-12894 ⁃ [Bug][crash] Fenix crashes when opening the bookmark folders

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#11892]
## Prerequisites
Make sure you are signed in with a valid FxA account and have multiple bookmarks folders, and sub-folders.

## Steps to reproduce
Go to Bookmarks and enter in all parent folders, and child folders, "visiting" all the bookmarks within the folders.

### Expected behavior
The user can move from one folder to another without issues.

### Actual behavior
5c22c1e3-900b-47c5-ad8d-cae26fa0f716
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

* Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/?query=c99124e0d67344f5aea560e190400602
* Socorro: https://crash-stats.mozilla.org/report/index/bp-762ae33c-a899-4982-90fa-3d51e0200624
----
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
at android.view.ViewGroup.addViewInner(ViewGroup.java:4944)
at android.view.ViewGroup.addView(ViewGroup.java:4775)
at android.view.ViewGroup.addView(ViewGroup.java:4747)
at androidx.appcompat.widget.Toolbar.addSystemView(Toolbar.java:10)
at androidx.appcompat.widget.Toolbar.setTitle(Toolbar.java:13)
at androidx.appcompat.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:4)
at androidx.appcompat.app.ToolbarActionBar.setWindowTitle(ToolbarActionBar.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl.setTitle(AppCompatDelegateImpl.java:5)
at androidx.appcompat.app.AppCompatActivity.onTitleChanged(AppCompatActivity.java:2)
at android.app.Activity.setTitle(Activity.java:5915)
at org.mozilla.fenix.library.LibraryPageView.updateToolbar(LibraryPageView.kt:1)
at org.mozilla.fenix.library.LibraryPageView.setUiForNormalMode(LibraryPageView.kt:7)
at org.mozilla.fenix.library.bookmarks.BookmarkView.update(BookmarkView.kt:19)
at org.mozilla.fenix.library.bookmarks.BookmarkFragment$onViewCreated$1.invoke(BookmarkFragment.kt:3)
at mozilla.components.lib.state.ext.FragmentKt$consumeFrom$1.invokeSuspend(Fragment.kt:8)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:180)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

### Device information
* Android device: HTC 10 (Android 8)
* Fenix version: 6/24 Nightly

**Comment by ekager** [comment]
CC @ValentinTimisica could this be a regression from https://github.com/mozilla-mobile/fenix/pull/11721 since this just started happening a few days ago it looks like?

**Comment by ekager** [comment]
I'm not sure we should be dynamically using `setupNavigationToolbar`. Maybe we could just remove all of those calls (and keep the back button and close button for the root bookmark fragment for now). AFAICT that maybe solves the issue?

**Comment by ValentinTimisica** [comment]
Ok @ekager, I'll try a speculative fix by removing the dynamic calls to `setupNavigationToolbar `.

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 6/29, and on Beta 78.0.1-beta.1, with HTC 10 (Android 8), and Samsung Galaxy Tab S6 (Android 9).
