### ISSUE TITLE
FNX-12905 ⁃ [CRASH] java.lang.IllegalStateException: FragmentManager has been destroyed

### ISSUE THREAD

**Issue by RealGJ** [mozilla-mobile/fenix#11905]
Crashed while browsing on GitHub blog

Details : df20fc9f-2a0b-458e-9e11-72880534ba5b
java.lang.IllegalStateException: FragmentManager has been destroyed

* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/?query=d506527b60e04b37b322b7710da2c289
* Socorro: https://crash-stats.mozilla.org/report/index/bp-a8b44af9-6392-4b9e-beae-8c3c80200624
----
java.lang.IllegalStateException: FragmentManager has been destroyed
at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:754)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Fenix : Nightly 200624 06:01 (Build #2015748083)
AC: 47.0.20200623130149, 88694edfb
GV: 79.0a1-20200622093309
AS: 61.0.2

Device : Xiaomi Redmi Note 4 Android 7.0

**Comment by ekager** [comment]
Hi @RealGJ thanks for this report! Did you do anything before this crash happened? Were you in private mode/normal mode? Did you open this link from outside Fenix? Did you press back or close the tab? Thanks!

**Comment by RealGJ** [comment]
@ekager yes. I opened that link from Reddit app. And pressed back button when finished reading. Browsing mode was normal with strict tracking protection. Add ons installed : Ublock origin, dark reader, https everywhere.

**Comment by ekager** [comment]
Okay thank you! I landed #11924 yesterday which I think should fix this, but let me know if you keep seeing it in Nightly. 
Closing for #8374
