### ISSUE TITLE
[Bug] Intermittent debug(T) java.lang.AssertionError: Verification failed: call 2 of 3: TabCollectionStorage(tabCollectionStorage#33).renameCollection(eq(TabCollection(#35)), eq(name))) was not called

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#11943]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=307464047&repo=fenix

```
[task 2020-06-25T01:55:17.012Z] SUITE: org.mozilla.fenix.collections.DefaultCollectionCreationControllerTest
[task 2020-06-25T01:55:17.110Z]   TEST: GIVEN previous step was NameCollection AND tabCollections is empty AND one or fewer tabs are open WHEN stepBack is called THEN null should be returned
[task 2020-06-25T01:55:19.410Z]   SUCCESS
[task 2020-06-25T01:55:19.411Z] 
[task 2020-06-25T01:55:19.411Z]   TEST: WHEN select all is called THEN add all should be dispatched
[task 2020-06-25T01:55:19.810Z]   SUCCESS
[task 2020-06-25T01:55:19.810Z] 
[task 2020-06-25T01:55:19.810Z]   TEST: GIVEN list of collections WHEN default collection number is required THEN return next default number
[task 2020-06-25T01:55:19.910Z]   SUCCESS
[task 2020-06-25T01:55:19.910Z] 
[task 2020-06-25T01:55:19.910Z]   TEST: GIVEN collection WHEN renameCollection is called THEN collection should be renamed
[task 2020-06-25T01:55:20.311Z]   FAILURE
[task 2020-06-25T01:55:20.313Z] 
[task 2020-06-25T01:55:20.313Z] java.lang.AssertionError: Verification failed: call 2 of 3: TabCollectionStorage(tabCollectionStorage#33).renameCollection(eq(TabCollection(#35)), eq(name))) was not called
[task 2020-06-25T01:55:20.314Z] 	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
[task 2020-06-25T01:55:20.314Z] 	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
[task 2020-06-25T01:55:20.315Z] 	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
[task 2020-06-25T01:55:20.315Z] 	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:60)
[task 2020-06-25T01:55:20.315Z] 	at io.mockk.impl.eval.VerifyBlockEvaluator.verify(VerifyBlockEvaluator.kt:30)
[task 2020-06-25T01:55:20.315Z] 	at io.mockk.MockKDsl.internalVerify(API.kt:118)
[task 2020-06-25T01:55:20.315Z] 	at io.mockk.MockKDsl.internalVerify$default(API.kt:109)
[task 2020-06-25T01:55:20.316Z] 	at io.mockk.MockKDsl.internalVerifyAll(API.kt:192)
[task 2020-06-25T01:55:20.316Z] 	at io.mockk.MockKKt.verifyAll(MockK.kt:195)
[task 2020-06-25T01:55:20.316Z] 	at io.mockk.MockKKt.verifyAll$default(MockK.kt:192)
[task 2020-06-25T01:55:20.316Z] 	at org.mozilla.fenix.collections.DefaultCollectionCreationControllerTest$GIVEN collection WHEN renameCollection is called THEN collection should be renamed$1.invokeSuspend(DefaultCollectionCreationControllerTest.kt:118)
[task 2020-06-25T01:55:20.316Z] 	at org.mozilla.fenix.collections.DefaultCollectionCreationControllerTest$GIVEN collection WHEN renameCollection is called THEN collection should be renamed$1.invoke(DefaultCollectionCreationControllerTest.kt)
[task 2020-06-25T01:55:20.321Z] 	at kotlinx.coroutines.test.TestBuildersKt$runBlockingTest$deferred$1.invokeSuspend(TestBuilders.kt:50)
[task 2020-06-25T01:55:20.322Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-06-25T01:55:20.322Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[task 2020-06-25T01:55:20.322Z] 	at kotlinx.coroutines.test.TestCoroutineDispatcher.dispatch(TestCoroutineDispatcher.kt:50)
[task 2020-06-25T01:55:20.322Z] 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:288)
[task 2020-06-25T01:55:20.322Z] 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
[task 2020-06-25T01:55:20.323Z] 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
[task 2020-06-25T01:55:20.323Z] 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
[task 2020-06-25T01:55:20.323Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async(Builders.common.kt:89)
[task 2020-06-25T01:55:20.323Z] 	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
[task 2020-06-25T01:55:20.323Z] 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.async$default(Builders.common.kt:82)
[task 2020-06-25T01:55:20.324Z] 	at kotlinx.coroutines.BuildersKt.async$default(Unknown Source)
[task 2020-06-25T01:55:20.324Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:49)
[task 2020-06-25T01:55:20.324Z] 	at kotlinx.coroutines.test.TestBuildersKt.runBlockingTest(TestBuilders.kt:72)
[task 2020-06-25T01:55:20.324Z] 	at org.mozilla.fenix.collections.DefaultCollectionCreationControllerTest.GIVEN collection WHEN renameCollection is called THEN collection should be renamed(DefaultCollectionCreationControllerTest.kt:112)
[task 2020-06-25T01:55:20.324Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-25T01:55:20.325Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-25T01:55:20.325Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-25T01:55:20.325Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-25T01:55:20.325Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-06-25T01:55:20.325Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-06-25T01:55:20.326Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-06-25T01:55:20.326Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-06-25T01:55:20.326Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-06-25T01:55:20.326Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2020-06-25T01:55:20.326Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2020-06-25T01:55:20.327Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2020-06-25T01:55:20.327Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-06-25T01:55:20.327Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-06-25T01:55:20.327Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-06-25T01:55:20.327Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-06-25T01:55:20.328Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-06-25T01:55:20.328Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-06-25T01:55:20.328Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-06-25T01:55:20.328Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-06-25T01:55:20.329Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-06-25T01:55:20.329Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-06-25T01:55:20.329Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-06-25T01:55:20.329Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-25T01:55:20.330Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-25T01:55:20.330Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-25T01:55:20.330Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-25T01:55:20.330Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-06-25T01:55:20.331Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-06-25T01:55:20.331Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-06-25T01:55:20.331Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-06-25T01:55:20.331Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-06-25T01:55:20.332Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-06-25T01:55:20.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-06-25T01:55:20.332Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-06-25T01:55:20.332Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-06-25T01:55:20.333Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-06-25T01:55:20.333Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-06-25T01:55:20.334Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-06-25T01:55:20.334Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-06-25T01:55:20.334Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-06-25T01:55:20.334Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-06-25T01:55:20.334Z] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mcarare** [comment]
cc @NotWoods.
