### ISSUE TITLE
RemoteTabProviderException: Protobuf decode error: failed to decode Protobuf message: invalid tag value: 0

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12162]
* https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8825532/?referrer=github_plugin
* BZ-1649808

```
RemoteTabProviderException: Protobuf decode error: failed to decode Protobuf message: invalid tag value: 0
    at mozilla.appservices.remotetabs.rust.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.remotetabs.RemoteTabsProvider.setLocalTabs(RemoteTabsProvider.kt:14)
    at mozilla.components.browser.storage.sync.RemoteTabsStorage$store$2.invokeSuspend(RemoteTabsStorage.kt:16)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
...
(2 additional frame(s) were not displayed)

Protobuf decode error: failed to decode Protobuf message: invalid tag value: 0
```

**Comment by kbrosnan** [comment]
https://github.com/mozilla-mobile/android-components/issues/7426

**Comment by ekager** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/7560

**Comment by ekager** [comment]
Going to close this because it seems resolved on Nightly https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/8619850/?query=is%3Aunresolved%20RemoteTabProviderException

**Comment by Amejia481** [comment]
This could be a regression as we starting [to see reports on newer versions ](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8825532).

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/773158/115567126-e8ce0580-a288-11eb-83ec-8b1f6894e56a.png">

**Comment by Amejia481** [comment]
AS versions
![image](https://user-images.githubusercontent.com/773158/115571062-a1e20f00-a28c-11eb-9cbb-6ba9da69fe10.png)
