### ISSUE TITLE
[Bug] Firefox Nightly not working on Android 11 after update

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/fenix#12242]
## Prerequisites
Install Firefox Preview on the device.

## Steps to reproduce
1. Go to Play Store and search for Firefox Nightly.
1. Update the app.
1. Tap on Open.
1. Tap on the app icon from the device home screen.

### Expected behavior
Step 3 & 4: Firefox Nightly opens.

### Actual behavior
Step 3: crash.
Step 4: The app doesn't open.

### Notes:
Not reproducible with Firefox Nightly for Developers or Firefox Preview Nightly for Developers.

### Device information
* Android device: Google Pixel 3 (Android 11 RPB1.200504.020).
* Fenix version: Firefox Nightly 7/2.

[crash.txt](https://github.com/mozilla-mobile/fenix/files/4869496/crash.txt)

**Comment by kbrosnan** [comment]
```
    java.lang.UnsatisfiedLinkError Native library (comsunjnaandroid-aarch64libjnidispatch.so) not found in resource path (.)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java12)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java35)
        at com.sun.jna.Native.clinit(Native.java12)
        at com.sun.jna.StringArray.init(StringArray.java5)
        at com.sun.jna.StringArray.init(StringArray.java3)
        at mozilla.telemetry.glean.private.CounterMetricType.init(CounterMetricType.kt4)
        at mozilla.components.lib.crash.GleanMetrics.CrashMetrics.clinit(CrashMetrics.kt5)
        at mozilla.components.lib.crash.service.GleanCrashReporterService.init(GleanCrashReporterService.kt20)
        at org.mozilla.fenix.components.Analytics$crashReporter$2.invoke(Analytics.kt24)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt6)
        at org.mozilla.fenix.components.Analytics.getCrashReporter(Unknown Source7)
        at org.mozilla.fenix.FenixApplication.setupInAllProcesses(FenixApplication.kt1)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt2)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java6607)
        at android.app.ActivityThread.access$1300(ActivityThread.java233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java1896)
        at android.os.Handler.dispatchMessage(Handler.java106)
        at android.os.Looper.loop(Looper.java223)
        at android.app.ActivityThread.main(ActivityThread.java7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java941)
```

**Comment by Amejia481** [comment]
I'm unable to replicate, I'm using Android 11 with nightly 

```
Nightly 200914 06:05 (Build #2015763827)
AC: 59.0.20200911130559, d974933d4
GV: 82.0a1-20200908095243
AS: 61.0.13
11:07
Monday 9/14 @ 6:12 AM
```

**Comment by sflorean** [comment]
@Amejia481 Tested on Google Pixel 3 (Android 11) & Google Pixel 4 XL (Android 11) and we couldn't reproduce the problem; we updated Nightly from 09/15 to 09/16 and we also used a Nightly build from a month ago and perform an update.

**Comment by Amejia481** [comment]
Thanks @sflorean. I will close this issue, feel free to reopen if need it.
