### ISSUE TITLE
FNX2-15133 ⁃ [Bug] Firefox nightly crashing

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#12277]
## Steps to reproduce
Open any website and minimize the browser
Open any link from other app which should open in custom tab..
From custom tab click open in browser
Firefox is crashing

### Expected behavior
Firefox should open properly

### Actual behavior
Crashing

### Device information
* Android device: ? A10
* Fenix version: ? Latest nightly

26b0f567-d616-4c5c-a768-57568c9215b9

## java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: ExternalAppBrowserActivity
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: ExternalAppBrowserActivity
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:17)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onEngineSession(EngineViewPresenter.kt:2)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$2$2.emit(Collect.kt:3)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7500)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:12)
	... 16 more

![Screenshot](https://user-images.githubusercontent.com/58127841/86511769-b6cbdf80-bdeb-11ea-8de1-99294a69831c.jpg)UNITO-UNDERSCORE!20200704-165438!

![Screenshot](https://user-images.githubusercontent.com/58127841/86511785-ce0acd00-bdeb-11ea-8fef-c15223921f8d.jpg)UNITO-UNDERSCORE!20200704-171437!

**Comment by sheikh-azharuddin** [comment]
Seems this is happening whenever I click open in browser from custom tab....

**Comment by rafalopilowski1** [comment]
Adding information as I've reproduced this bug on my device.

In my case:
 - Open up "https://github.com/mozilla-mobile/fenix/projects/49" as a Custom Tab
 - Open it on Firefox Nightly using a option in a 3-dot menu

[Screencasst of the issue](https://streamable.com/ypsjmv) - cut as it includes another bug.

Device: OnePlus 6 (Android 10)

Fenix version:
> Nightly 200705 06:01 (Build #21870613)
> AC: 49.0.20200702190156, bafa9299b
> GV: 80.0a1-20200702094606
> AS: 61.0.7

Socorro:
- [https://crash-stats.mozilla.org/report/index/579acd16-0316-4a41-998c-d18f40200705](https://crash-stats.mozilla.org/report/index/579acd16-0316-4a41-998c-d18f40200705)
- [https://crash-stats.mozilla.org/report/index/a9c89276-d6b2-4d40-a6c4-565fd0200705](https://crash-stats.mozilla.org/report/index/a9c89276-d6b2-4d40-a6c4-565fd0200705)
- [https://crash-stats.mozilla.org/report/index/b9489d96-740d-4c1f-8832-5bdb20200705](https://crash-stats.mozilla.org/report/index/b9489d96-740d-4c1f-8832-5bdb20200705)

**Comment by Diana-Rus** [comment]
Hi, managed to reproduce with Google Pixel 3XL (Android 9) and Samsung Galaxy S9 (Android 8) on latest Nightly 7/6
Crash link: https://crash-stats.mozilla.org/report/index/bp-0c27ef1a-bb36-4abd-9ff6-fd9570200706

**Comment by ekager** [comment]
closing for https://github.com/mozilla-mobile/fenix/issues/12311
