### ISSUE TITLE
Intermittent UI test failure - ContextMenusTest.verifyContextMixedVariations & verifyContextSaveImage

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12309]
### Firebase Test Run:
verifyContextMixedVariations
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8712962153730277231/executions/bs.16a40ba158b15435/testcases/2/test-cases

verifyContextSaveImage
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8712962153730277231/executions/bs.60d469271a6aaee6/testcases/2/test-cases

### Stacktrace:
Both with the same error: 
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.longClickMatchingText(BrowserRobot.kt:300)

### Build: 
7/6/2020

**Comment by sv-ohorvath** [comment]
cc @AaronMT
