### ISSUE TITLE
FNX-13355 ⁃ [Bug] Crash in Logins

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12312]
## Steps to reproduce
Open setting/logins and passwords
Click on saved logins and quickly click on sync logins (sync logins screen opens)
Use fingerprints scanner

### Expected behavior
Step 2 should not be possible

### Actual behavior
Crash
Log:

```
fcbef9d4-1c31-4951-ace3-4eeea8fb722c
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=b5d3013033624c9fb499ef2e00b481f3
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-dbc9b51b-b9d4-4945-8357-b6dda0200706
----
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:2)
	at org.mozilla.fenix.settings.logins.SavedLoginsAuthFragment$onCreate$1.onAuthenticationSucceeded(SavedLoginsAuthFragment.kt:2)
	at androidx.biometric.BiometricFragment$2$2.run(BiometricFragment.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


```

### Device information
* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200708 from 7/8`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

The Save logins and passwords, Sync logins and Saved logins are disabled after the user exits the Saved logins section.
