### ISSUE TITLE
[Crash] java.lang.NullPointerException: at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#12362]
https://crash-stats.mozilla.org/signature/?product=Fenix&version=79.0.0-beta.5&signature=java.lang.NullPointerException%3A%20at%20android.app.ApplicationPackageManager.resolveActivity%28ApplicationPackageManager.java%29&date=%3E%3D2020-06-30T19%3A41%3A00.000Z&date=%3C2020-07-07T19%3A41%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#summary

https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/8968459/?query=release%3A%22org.mozilla.firefox_beta-79.0.0-beta.5%22%20nullpointerexception

Top crasher 8 in Fenix 79.0.0-beta.5, appears to be a startup crash.

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference
    at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java:1008)
    at mozilla.components.support.utils.Browsers.findKnownBrowsers(Browsers.kt:7)
    at mozilla.components.support.utils.Browsers.access$findKnownBrowsers(Browsers.kt:1)
    at mozilla.components.support.utils.Browsers.<init>(Browsers.kt:5)
    at mozilla.components.support.utils.Browsers$Companion.all(Browsers.kt:1)
    at org.mozilla.fenix.utils.BrowsersCache.all(BrowsersCache.kt:3)
    at org.mozilla.fenix.FenixApplication$warmBrowsersCache$1.invokeSuspend(FenixApplication.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

- - -
I briefly looked into this: the only device affected is "H96 Max RK3318" (according to sentry) which is an Android TV device. Since we don't officially support Android TV, I would propose a low priority.

**Comment by kbrosnan** [comment]
This looks to be resolved from Sentry and Crash-stats
