### ISSUE TITLE
FNX2-15224 ⁃ closePrivateTabsNotificationTest androidx.test.uiautomator.UiObjectNotFoundException

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12406]
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7414240579579755759/executions/bs.3b6f6a1415b60725/testcases/2/test-cases

```
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.android.systemui:id/notification_stack_scroller]
at androidx.test.uiautomator.UiScrollable.scrollBackward(UiScrollable.java:496)
at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:544)
at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:563)
at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:265)
at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:213)
at org.mozilla.fenix.ui.robots.NotificationRobot.verifySystemNotificationExists(NotificationRobot.kt:28)
at org.mozilla.fenix.ui.robots.NotificationRobot$Transition.clickClosePrivateTabsNotification(NotificationRobot.kt:70)
at org.mozilla.fenix.ui.TabbedBrowsingTest.closePrivateTabsNotificationTest(TabbedBrowsingTest.kt:221)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**Comment by sv-ohorvath** [comment]
This is an old issue that hasn't appeared again so I think we can close it.
