### ISSUE TITLE
(onProcessKilled) Crash while browsing: IllegalArgumentException: Display not attached

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#12436]
Just ran into this while testing something else in Fenix. Don't have exact STR but I was opening/closing/switching tabs and toggling PB and then backgrounded the app I think? (did NOT have to do with custom tabs though)
Going to file just to keep open in case someone else runs into it as well. 
(cc @pocmo ) 

```
java.lang.IllegalArgumentException: Display not attached
        at org.mozilla.geckoview.GeckoSession.releaseDisplay(GeckoSession.java:2438)
        at org.mozilla.geckoview.GeckoView.releaseSession(GeckoView.java:393)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:436)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.rebind(GeckoEngineView.kt:150)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.access$rebind(GeckoEngineView.kt:27)
        at mozilla.components.browser.engine.gecko.GeckoEngineView$observer$1.onProcessKilled(GeckoEngineView.kt:68)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onKill$2.invoke(GeckoEngineSession.kt:649)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1$onKill$2.invoke(GeckoEngineSession.kt:612)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
        at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createContentDelegate$1.onKill(GeckoEngineSession.kt:649)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:370)
        at org.mozilla.geckoview.GeckoSession$2.handleMessage(GeckoSession.java:359)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:90)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by pocmo** [comment]
This is an interesting stacktrace.

The call goes through `onProcessKilled()` which means that the content process got killed by Android (It did not crash, but Android is reclaiming system resources by killing it), which also makes it very likely that you backgrounded the app, as you said.

In that situation, under the hood, we are creating a new `GeckoSession`, restoring the last state for it, and then we try to render the new `GeckoSession`. And that's where it is crashing with `Display not attached` here.

We implemented this in:
- https://github.com/mozilla-mobile/android-components/issues/3310
- https://bugzilla.mozilla.org/show_bug.cgi?id=1557096
- https://github.com/mozilla-mobile/fenix/issues/1577

Back then this situation was easy to reproduce by using `kill -9` on the content process. Maybe that can help reproducing this crash here now.

I'm going to move this into the AC sprint too.

**Comment by pocmo** [comment]
I tried to reproduce this with the STR from https://github.com/mozilla-mobile/fenix/issues/1577 but wasn't successful.

**Comment by pocmo** [comment]
I found some similar stacktraces on Sentry and merged them together.

**Comment by pocmo** [comment]
Sentry issue: [FENIX-53P](https://sentry.prod.mozaws.net/operations/fenix/issues/7683882/?referrer=github_plugin)

**Comment by pocmo** [comment]
After https://github.com/mozilla-mobile/android-components/issues/7867 lands in AC we can rewrite that logic in AC. Instead of recreating a GeckoSession and restoring it, we will be able to "suspend" the whole tab, only keeping it's `EngineSessionState`. So that an individual tab will only be restored when it is needed the next time.

**Comment by liuche** [comment]
We're doing a crash sprint, and wondering what the next work is here, and whether we can pick up/split any of this work.

**Comment by pocmo** [comment]
Patch landed in AC.
Fenix counter part: https://github.com/mozilla-mobile/fenix/pull/14823

**Comment by ekager** [comment]
Should we close this since #14823 has landed?

**Comment by pocmo** [comment]
Yes, let's close it. I have some other issues for other white screen problems.. :)
