### ISSUE TITLE
[Bug] Crash while uploading Gif to google images

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12494]
## Steps to reproduce
Turn on Desktop mode
Open google images and click ont he camera icon to upload image
Choose a gif

### Expected behavior
Upload properly

### Actual behavior
Crash

```
f7333b47-1545-4238-8cae-ef4d48e26525
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=72649, result=-1, data=Intent { dat=content://media/external/file/109537 typ=image/gif flg=0x1 }} to activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.IllegalStateException: cursor.getString(nameIndex) must not be null
----
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=72649, result=-1, data=Intent { dat=content://media/external/file/109537 typ=image/gif flg=0x1 }} to activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.IllegalStateException: cursor.getString(nameIndex) must not be null
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: cursor.getString(nameIndex) must not be null
	at kotlin.jvm.internal.ArrayIteratorKt.checkExpressionValueIsNotNull(ArrayIterator.kt:1)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.toFileUri(GeckoPromptDelegate.kt:9)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toFileUri(GeckoPromptDelegate.kt:1)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onFilePrompt$onSelectSingle$1.invoke(GeckoPromptDelegate.kt:3)
	at mozilla.components.feature.prompts.file.FilePicker.handleFilePickerIntentResult$feature_prompts_release(FilePicker.kt:6)
	at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:5)
	at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
	at androidx.core.app.AppOpsManagerCompat.consumePromptFrom$default(AppOpsManagerCompat.java:1)
	at mozilla.components.feature.prompts.file.FilePicker.onActivityResult(FilePicker.kt:1)
	at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$onActivityResult$1.invoke(BaseBrowserFragment.kt:3)
	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.withFeature(ViewBoundFeatureWrapper.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:1)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:7)
	at android.app.Activity.dispatchActivityResult(Activity.java:7462)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
	... 11 more


```

### Device information
* Android device: ?
* Fenix version: ?

**Comment by AndiAJ** [comment]
Hi @s-ankur , I **wasn't able to reproduce** this issue on the latest **`Fenix Nightly Build 200713 from 7/13`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200713-150427](https://user-images.githubusercontent.com/51314259/87303423-d1086a80-c51b-11ea-844b-59db0a229ae9.gif)

**Comment by s-ankur** [comment]
After some testing I found that it only happens when using simplemobiletools gallery app and it is not limited to google images but happens on any site where you can upload images
![2](https://user-images.githubusercontent.com/33252312/87305829-a19b3300-c506-11ea-9c77-bcfe31010863.gif)

**Comment by Amejia481** [comment]
This was fixed by https://github.com/mozilla-mobile/android-components/pull/8104 let's ask QA to verify

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 200831`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

► Video
![20200831-135214](https://user-images.githubusercontent.com/51314259/91713302-2b27c280-eb92-11ea-85b4-335957f420a4.gif)
