### ISSUE TITLE
Intermittent debug(ui-test-x86) openNewPrivateTabTest androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#12501]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=309554927&repo=fenix

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatTextView{id=2131362849, res-name=tab_tray_empty_view, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@1c4e0dd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Your open tabs will be shown here., input-type=0, ime-target=false, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.TabDrawerRobotKt.assertNoTabsOpenedText(TabDrawerRobot.kt:197)
at org.mozilla.fenix.ui.robots.TabDrawerRobotKt.access$assertNoTabsOpenedText(TabDrawerRobot.kt:1)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.verifyNoTabsOpened(TabDrawerRobot.kt:47)
at org.mozilla.fenix.ui.TabbedBrowsingTest$openNewPrivateTabTest$7.invoke(TabbedBrowsingTest.kt:99)
at org.mozilla.fenix.ui.TabbedBrowsingTest$openNewPrivateTabTest$7.invoke(TabbedBrowsingTest.kt:38)
at org.mozilla.fenix.ui.robots.TabDrawerRobot$Transition.toggleToNormalTabs(TabDrawerRobot.kt:132)
at org.mozilla.fenix.ui.TabbedBrowsingTest.openNewPrivateTabTest(TabbedBrowsingTest.kt:98)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatTextView{id=2131362849, res-name=tab_tray_empty_view, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@1c4e0dd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Your open tabs will be shown here., input-type=0, ime-target=false, has-links=false}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:15)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:15)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:10)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sv-ohorvath** [comment]
Video: here: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6657667609192566463/executions/bs.627f6c44cd2ab1fc/videos

**Comment by sv-ohorvath** [comment]
Haven't seen this in a long time, so I'm going to close this issue for now.
