### ISSUE TITLE
FNX2-15294 ⁃ [Bug] debug(ui-test-x86) createBookmarkFolderTest java.lang.IllegalStateException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#12500]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=309554927&repo=fenix

java.lang.IllegalStateException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$createBookmarkFolderTest$3.invoke(BookmarksTest.kt:135)
at org.mozilla.fenix.ui.BookmarksTest$createBookmarkFolderTest$3.invoke(BookmarksTest.kt:35)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:169)
at org.mozilla.fenix.ui.BookmarksTest.createBookmarkFolderTest(BookmarksTest.kt:128)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
This is a dupe of https://github.com/mozilla-mobile/fenix/issues/10911
