### ISSUE TITLE
[Bug] no user facing error when sync fails due to network connectivity

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#12644]
Originally reported in https://github.com/mozilla-mobile/fenix/issues/12625

### Steps to reproduce
1. Internet is off 
1. Sync Now option is pressed
1. The app crashes with the following logs: 

```
07-16 12:59:48.739  9182  9182 E AndroidRuntime: FATAL EXCEPTION: main
07-16 12:59:48.739  9182  9182 E AndroidRuntime: Process: org.mozilla.fenix, PID: 9182
07-16 12:59:48.739  9182  9182 E AndroidRuntime: mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(Unknown Source:11)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-16 12:59:48.739  9182  9182 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
07-16 12:59:48.742  9182  9182 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5", breadcrumbs=[], uuid=1d7b92e1-2a82-40e1-ba19-ab3ccf0109e7)
```

**Comment by kbrosnan** [comment]
This is being handled by https://github.com/mozilla-mobile/android-components/issues/7748
