### ISSUE TITLE
[Bug] Custom Tab switch causes crash

### ISSUE THREAD

**Issue by Kreuger** [mozilla-mobile/fenix#12699]
## Steps to reproduce
When I open a link in another app it gives me the custom tab view. When I click "open in Firefox nightly", the app crashes. 

### Expected behavior
Open the link

### Actual behavior
App crashes

### Device information
* Android device: 10
* Fenix version: 200706 build # 2015750387

**Comment by ekager** [comment]
I can't repro in Nightly 200718 Build #22000612 

Do you have an update available in the play store? Otherwise could you get the crash report from about:crashes?

**Comment by Kreuger** [comment]
6c41d11c-81b5-4060-9c31-58e82721fe93
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: ExternalAppBrowserActivity
----
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity Other activity: ExternalAppBrowserActivity
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:17)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onEngineSession(EngineViewPresenter.kt:2)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$2$2.emit(Collect.kt:3)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:12)
	... 16 more

**Comment by ekager** [comment]
That looks like this resolved crash: https://github.com/mozilla-mobile/fenix/issues/12311

You may have the wrong channel of Nightly (esp if it hasn't updated in a while) 

This is the Nightly channel https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en_US

**Comment by ekager** [comment]
The active full featured browsers are:

* Nightly <[org.mozilla.fenix](https://play.google.com/store/apps/details?id=org.mozilla.fenix)>
* Beta <[org.mozilla.firefox_beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta)>
* Release <[org.mozilla.firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox)>

**Comment by Kreuger** [comment]
Yeah I havent changed over yet. I wasnt aware that this was fixed. I guess I will have to switch.
