### ISSUE TITLE
Crash in [@ org.mozilla.geckoview.GeckoResult$UncaughtException: at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#12728]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=org.mozilla.geckoview.GeckoResult%24UncaughtException%3A%20at%20org.mozilla.geckoview.GeckoResult.dispatchLocked%28GeckoResult.java%29

bz-1644999
```
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
	at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:14)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:5)
	at -$$LambdaGroup$ks$UtaWBn0vzFfZ64mP0sa7JCFLt3Q.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:83)
	at -$$LambdaGroup$ks$_HIPVZOvbmOxwps1M61uurZH_lk.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:15)
	at mozilla.components.browser.engine.gecko.GeckoEngine$installWebExtension$$inlined$apply$lambda$3.onValue(GeckoEngine.kt:14)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
```

**Comment by csadilek** [comment]
There's a second very much related crash as well which can be reproduced reliably by turning on "Don't keep activities."

STR:
- Install add-on
- Once installation dialog is displayed, switch to another app and back

Crash:
```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment mozilla.components.feature.addons.ui.AddonInstallationDialogFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:7)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:1)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:1)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:8)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:10)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:2)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:2)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:1)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:5)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:23)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:42)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:2)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:1)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:1)
        at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:27)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
        at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
```

This needs a bigger change to `AddonInstallationDialogFragment` so I am moving this back to A-C after all 😂
