### ISSUE TITLE
Intermittent UI test failure - testStrictVisitContentShield and testStrictVisitContentNotification

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12896]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6190519808130850622/executions/bs.998970f5f79cf6cc/testcases/3/test-cases

Failed 1 out of 2

### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull$default(WaitNotNull.kt:19)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:98)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:1)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot.verifyEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:31)`

**Comment by sv-ohorvath** [comment]
testStrictVisitProtectionSheet also failed with the same error: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8144815642330288966/executions/bs.46293623a2f85f7c/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Left a comment on https://github.com/mozilla-mobile/fenix/issues/7907 about this

**Comment by sv-ohorvath** [comment]
See also (for the same or similar error): 
https://github.com/mozilla-mobile/fenix/issues/13830
https://github.com/mozilla-mobile/fenix/issues/14524
