### ISSUE TITLE
FNX2-15554 ⁃ Crash in [@ java.lang.ClassCastException: at org.mozilla.fenix.settings.search.SearchEngineListPreference.makeButtonFromSearchEngine(SearchEngineListPreference.kt:2)]

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12929]
## Steps to reproduce
Click **Settings** and click **Search**.

### Expected behavior
Settings about **Search**.

### Actual behavior
Crash.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200725 06:01
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T (ARM64, ARMv8.2-A)

**Comment by lomomcat** [comment]
**Crash Code**

_java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
----
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.makeButtonFromSearchEngine(SearchEngineListPreference.kt:2)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.access$makeButtonFromSearchEngine(SearchEngineListPreference.kt:1)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.refreshSearchEngineViews(SearchEngineListPreference.kt:18)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.reload(SearchEngineListPreference.kt:2)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.onBindViewHolder(SearchEngineListPreference.kt:3)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:3)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:145)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:125)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:812)
	at android.view.View.layout(View.java:22228)
	at android.view.ViewGroup.layout(ViewGroup.java:6395)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3314)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2810)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1883)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8038)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
	at android.view.Choreographer.doCallbacks(Choreographer.java:793)
	at android.view.Choreographer.doFrame(Choreographer.java:728)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7573)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)_

**Comment by hwinnemoe** [comment]
I can reproduce on Nightly 200725 06:01 (Build #22070612), just accessing _Search_ in the _Setttings_ crashes with:

e61ee1fa-fa5e-4f5f-bdd5-7137831ad8c5
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=10086caf041d45418e3a270b4cad0dcd
----
```
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.makeButtonFromSearchEngine(SearchEngineListPreference.kt:2)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.access$makeButtonFromSearchEngine(SearchEngineListPreference.kt:1)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.refreshSearchEngineViews(SearchEngineListPreference.kt:18)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.reload(SearchEngineListPreference.kt:2)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.onBindViewHolder(SearchEngineListPreference.kt:3)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:3)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:145)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:125)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2685)
	at android.view.View.layout(View.java:16722)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2175)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1935)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This commit https://github.com/mozilla-mobile/fenix/commit/b3b7566fcfb926b489d0161a5e55c48458d3a8fc introduced a new LinearLayout in the Search Layout with https://github.com/mozilla-mobile/fenix/commit/b3b7566fcfb926b489d0161a5e55c48458d3a8fc#diff-5919d313ccf3173a1143d11a97b75394R5 in order to resolve #12804.

**Comment by hakkikaancaliskan** [comment]
Sorry for this crash, I'm looking for a fix.

**Comment by sflorean** [comment]
Verified as fixed on Nightly 7/27 with Xiaomi Redmi Note 8T (Android 9).
