### ISSUE TITLE
[Bug]Crash Code Report(Always Crash)

### ISSUE THREAD

**Issue by lomomcat** [mozilla-mobile/fenix#12954]
## Steps to reproduce
Click **Settings** and click **Search**, then select a search engine that is different from the default search engine.

### Expected behavior
Select successfully.

### Actual behavior
Crash.

### Device information
* Android device: Xiaomi Redmi Note 8 Pro
* Fenix version: Nightly 200726 10:10
* Android Version: 10 (MIUI 12, latest patch)
* SoC: MediaTek Helio G90T (ARM64, ARMv8.2-A)

**Comment by lomomcat** [comment]
**Crash Code**

2fa9fa22-0795-4adf-be69-4d6939c8bbed
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
----
```
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to androidx.constraintlayout.widget.ConstraintLayout
	at org.mozilla.fenix.settings.search.SearchEngineListPreference.onCheckedChanged(SearchEngineListPreference.kt:3)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
	at org.mozilla.fenix.settings.search.SearchEngineListPreference$makeButtonFromSearchEngine$1.onClick(SearchEngineListPreference.kt:1)
	at android.view.View.performClick(View.java:7252)
	at android.view.View.performClickInternal(View.java:7225)
	at android.view.View.access$3600(View.java:822)
	at android.view.View$PerformClick.run(View.java:27743)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7573)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by lomomcat** [comment]
@hakkikaancaliskan

**Comment by hakkikaancaliskan** [comment]
Damn.
@ekager could you please take a look at this?

**Comment by Glitchy-Tozier** [comment]
This is reproducible on Samsung Galaxy S9 and LG G6.

**Comment by Furax-31** [comment]
Same. A5 2017. 

Fenix version: Nightly 200726 10:10

**Comment by hakkikaancaliskan** [comment]
This crash fixed a long time ago
