### ISSUE TITLE
FNX2-15587 ⁃ Intermittent UI test failure - SettingsBasicsTest.selectNewDefaultSearchEngine

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#12968]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6873365255910920049/executions/bs.e49c1ff69e04d03/testcases/1/test-cases

### Stacktrace:
`androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 605, 797 and precision: 16, 16' on view 'with text: is "DuckDuckGo"'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobotKt.selectDefaultSearchEngine(SettingsSubMenuSearchRobot.kt:128)`

**Comment by sv-ohorvath** [comment]
This one, settingsMenuBasicsItemsTests,  fails with a similar error, performing a single click at some coordinates, which not how the code was written: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7416004993250552039/executions/bs.8341dd60b6a58ce7/testcases/1/test-cases

**Comment by AaronMT** [comment]
It's possible that for some reason animations might have been enabled on emulators at the time of running. Does this reproduce locally? Is it still happening?

**Comment by sv-ohorvath** [comment]
@AaronMT yes, it is reproducing locally. Won't see them on master anymore, because they are now disabled.

**Comment by sv-ohorvath** [comment]
possible cause: https://github.com/mozilla-mobile/fenix/issues/12929
