### ISSUE TITLE
[Bug]Can't download large files from thinkbroadband.com using a Google Pixel 3a (Android 10)

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#12979]
## Steps to reproduce
1. Navigate to https://www.thinkbroadband.com/download
1. Tap to download the 512mb Large File
1. Tap to download the  200mb Large File

### Expected behavior
Both files can be downloaded

### Actual behavior
Download failed error

### Device information
* Android device: Google Pixel 3a (Android 10)
* Fenix version: Nightly 200727 from 7/27

### Notes
❗ Not reproducible on the following devices:
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200727-162409](https://user-images.githubusercontent.com/51314259/88547125-f8842a80-d025-11ea-9eab-b85e9c6874cd.gif)

@Amejia481 - Please review :relaxed:

**Comment by Amejia481** [comment]
@AndiAJ if it's not much trouble could please upload the logcat entries when the error is shown? :)

**Comment by AndiAJ** [comment]
Sure, no problem 😃 

► 512mb file download

```kotlin
2020-07-27 16:34:47.770 10633-10661/? I/StreamController: cleanUpControllerScope(nowcards-15-158fa18-d429)
2020-07-27 16:34:51.500 1057-1057/? W/adbd: timeout expired while flushing socket, closing
2020-07-27 16:34:52.144 2150-2209/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():175 call()
2020-07-27 16:34:52.144 2150-2209/? I/PeriodicStatsRunner: PeriodicStatsRunner.call():179 No submit PeriodicStats since input started.
2020-07-27 16:34:53.720 25909-25909/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2020-07-27 16:34:53.738 25909-25909/? D/GeckoSession: handleMessage GeckoView:PageStart uri=http://ipv4.download.thinkbroadband.com/512MB.zip
2020-07-27 16:34:53.809 25909-25909/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2020-07-27 16:34:53.852 25909-25909/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2020-07-27 16:34:53.853 25909-25909/? I/SessionStorage/AutoSave: Save: Load finished
2020-07-27 16:34:53.861 25909-26017/? D/SessionStorage/AutoSave: Saved state to disk [7ms]
2020-07-27 16:34:53.863 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
2020-07-27 16:34:53.864 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
2020-07-27 16:34:53.932 25909-26115/? D/ThumbnailStorage: Saved thumbnail to disk (id = db643bbe-51e2-46fa-95ba-ea6f92074afc, generationId = 1000)
2020-07-27 16:34:54.736 25909-25909/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2020-07-27 16:34:55.325 25909-26017/? D/AbstractFetchDownloadService: Starting download for http://ipv4.download.thinkbroadband.com/512MB.zip 
2020-07-27 16:34:55.328 1382-3226/? E/InputDispatcher: Window handle Window{3c733df u0 org.mozilla.fenix/org.mozilla.fenix.App} has no registered input channel
2020-07-27 16:34:55.336 1382-1382/? W/NotificationService: Removed summary didn't match old notification: old=0|org.mozilla.fenix|100|null|10547, removed=0|org.mozilla.fenix|100|null|10547
2020-07-27 16:34:55.345 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
2020-07-27 16:34:55.346 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
2020-07-27 16:34:55.415 25909-26017/? D/AbstractFetchDownloadService: Fetching download for http://ipv4.download.thinkbroadband.com/512MB.zip 
2020-07-27 16:34:55.449 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:34:55.451 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:34:55.453 23972-23991/? E/SQLiteDatabase: Error inserting bucket_display_name=Download owner_package_name=org.mozilla.fenix parent=8 volume_name=external_primary _display_name=512MB.zip mime_type=application/zip _data=/storage/emulated/0/Download/512MB.zip _size=536870912 title=512MB group_id=50457899 is_download=true is_pending=1 date_added=1595856895 primary_directory=Download bucket_id=540528482 media_type=0 relative_path=Download/
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2713)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3254)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2903)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-07-27 16:34:55.454 25909-26017/? E/AbstractFetchDownloadService: Unable to complete download for http://ipv4.download.thinkbroadband.com/512MB.zip marked as FAILED
    java.io.IOException: Failed to register download with content resolver
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:27)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:15)
        at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:12)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:2)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:3)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
2020-07-27 16:34:55.480 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:34:55.681 1775-1775/? I/chatty: uid=10072(com.android.systemui) identical 2 lines
2020-07-27 16:34:55.682 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:34:55.729 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|401674967|null|10547

```


► 200mb file download

```kotlin
2020-07-27 16:36:56.037 786-1083/? I/netd: tetherGetStats() <3.33ms>
2020-07-27 16:36:57.561 1057-1057/? W/adbd: timeout expired while flushing socket, closing
2020-07-27 16:36:59.140 25909-25909/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2020-07-27 16:36:59.149 25909-25909/? D/GeckoSession: handleMessage GeckoView:PageStart uri=http://ipv4.download.thinkbroadband.com/200MB.zip
2020-07-27 16:36:59.173 786-27995/? E/ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
2020-07-27 16:36:59.221 25909-25909/? D/GeckoSession: handleMessage GeckoView:ProgressChanged uri=null
2020-07-27 16:36:59.222 25909-25909/? D/GeckoSession: handleMessage GeckoView:PageStop uri=null
2020-07-27 16:36:59.222 25909-25909/? I/SessionStorage/AutoSave: Save: Load finished
2020-07-27 16:36:59.226 25909-26017/? D/SessionStorage/AutoSave: Saved state to disk [4ms]
2020-07-27 16:36:59.277 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
2020-07-27 16:36:59.278 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
2020-07-27 16:36:59.323 25909-26113/? D/ThumbnailStorage: Saved thumbnail to disk (id = db643bbe-51e2-46fa-95ba-ea6f92074afc, generationId = 1034)
2020-07-27 16:36:59.962 25909-26017/? D/AbstractFetchDownloadService: Starting download for http://ipv4.download.thinkbroadband.com/200MB.zip 
2020-07-27 16:36:59.967 786-28001/? E/ResolverController: No valid NAT64 prefix (100, <unspecified>/0)
2020-07-27 16:36:59.969 1382-2630/? E/InputDispatcher: Window handle Window{debbaa7 u0 org.mozilla.fenix/org.mozilla.fenix.App} has no registered input channel
2020-07-27 16:36:59.971 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3138 
2020-07-27 16:36:59.972 2150-2150/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1808 
2020-07-27 16:36:59.974 1382-1382/? W/NotificationService: Removed summary didn't match old notification: old=0|org.mozilla.fenix|100|null|10547, removed=0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.083 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.085 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.087 25909-26017/? D/AbstractFetchDownloadService: Fetching download for http://ipv4.download.thinkbroadband.com/200MB.zip 
2020-07-27 16:37:00.097 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.098 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.117 23972-23991/? E/SQLiteDatabase: Error inserting bucket_display_name=Download owner_package_name=org.mozilla.fenix parent=8 volume_name=external_primary _display_name=200MB.zip mime_type=application/zip _data=/storage/emulated/0/Download/200MB.zip _size=209715200 title=200MB group_id=47655623 is_download=true is_pending=1 date_added=1595857020 primary_directory=Download bucket_id=540528482 media_type=0 relative_path=Download/
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:879)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1599)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1468)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2713)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3254)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2903)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-07-27 16:37:00.118 25909-26017/? E/AbstractFetchDownloadService: Unable to complete download for http://ipv4.download.thinkbroadband.com/200MB.zip marked as FAILED
    java.io.IOException: Failed to register download with content resolver
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.useFileStream$feature_downloads_release(AbstractFetchDownloadService.kt:27)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$performDownload$1.invoke(AbstractFetchDownloadService.kt:15)
        at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:12)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:2)
        at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:3)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
2020-07-27 16:37:00.144 25909-25909/? D/GeckoSession: handleMessage GeckoView:StateUpdated uri=null
2020-07-27 16:37:00.185 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.187 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:00.220 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|975168758|null|10547
2020-07-27 16:37:01.258 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:01.262 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|100|null|10547
2020-07-27 16:37:01.293 1775-1775/? D/InterruptionStateProvider: No heads up: unimportant notification: 0|org.mozilla.fenix|975168758|null|10547
```

**Comment by Amejia481** [comment]
@AndiAJ did you remember the previous steps to replicate the issue? I'm having a hard time to simulate.

**Comment by AndiAJ** [comment]
Hey @Amejia481 , can't repro anymore the issue on neither **`Nightly Build 200730`** and **`Fenix Beta 80.0.0-beta-1`** ☺️ 

► Video
![20200731-075526](https://user-images.githubusercontent.com/51314259/89002883-e1378c80-d306-11ea-945b-83cece2ad172.gif)

I'll go ahead and close this issue.
