### ISSUE TITLE
FNX-455 ⁃ [Telemetry] Add Adjust campaignID to metrics ping

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/fenix#1298]
It was identified that some basic / core pings are not included "for free" in the new Glean SDK baseline ping. This ticket is about including the additional pings product wants to track

#### Description & Product Manager 
* As a product marketing manager, I want to know from what campaign users installed the app from.

#### What questions will you answer with this data?
* By knowing what cohort/campaign the user came from allows us to understand their usage better

#### Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
* Be able to understand from what campaign users came from

#### What probes (suggested, if applicable)
* adjustID, see row 23 in https://docs.google.com/spreadsheets/d/1P2_aGEE9OtjM3x71d0GBhnHDhzxEL02xEHuKn1no23E/edit#gid=0

### Dependencies (Added by PM and Eng)
* Core ping / baseline ping, see comment here

### Acceptance Criteria (Added by PM)
* Baseline pings can be queried via re:dash
* We are sending telemetry events for the actions listed in the requirements
* We have documented the telemetry
* We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry
* NOT an AC: Data science to create dashboard or further graphs (this will be a separate issue, this issue is only about hooking up the events described and that they can be queried in re-dash)

**Comment by bbinto** [comment]
@vesta0 this can wait until after Beta

**Comment by liuche** [comment]
This is for putting the LeanPlum marketing campaignId into Glean. @liuche will check on this.

**Comment by sblatz** [comment]
@liuche any update on this? I'm happy to look into this with you.

**Comment by liuche** [comment]
Sorry for not updating here! It's fine to include Adjust campaignIds into Glean ping, but we should check if this proposal changes.

**Comment by sblatz** [comment]
QA may need to link up with marketing to have a fake campaign to test this against.

@lwa-moz

**Comment by lwa-moz** [comment]
For testing, we can use: https://app.adjust.com/ou6v41x?campaign=Glean_test_campaign&adgroup=Glean_test_adgroup&creative=Glean_test_creative

**Comment by abodea** [comment]
Hi, @sblatz and @lwa-moz I tested this issue trying the build from [above](https://app.adjust.com/ou6v41x?campaign=Glean_test_campaign&adgroup=Glean_test_adgroup&creative=Glean_test_creative) but note that the `campaignID` wasn't generated.
@sblatz if this should be tested on other build than the re-release this should still be in `v2.1` milestone?
- I was thinking I should sync with the marketing team to see what is the best approach for testing this. 
- Also, note that I couldn't check on the Fenix v2.1.0-rc.1 as I didn't have any campaign on that build.
- I modified the bug title as this is referring to `metrics` and not `baseline`.
#### Here you can find the metrics generated on the Loren build:
```Kotlin
{
      "metrics": {
        "boolean": {
          "metrics.default_browser": false
        },
        "string": {
          "experiments.metrics.active_experiment": "c"
        },
        "string_list": {
          "metrics.mozilla_products": [
            "org.mozilla.firefox",
            "org.mozilla.fenix",
            "mozilla.lockbox"
          ]
        }
      },
      "ping_info": {
        "ping_type": "metrics",
        "experiments": {
          "fenix-test-2019-08-05": {
            "branch": "c"
          }
        },
        "seq": 7,
        "start_time": "2019-09-30T06:14-04:00",
        "end_time": "2019-09-30T06:15-04:00"
      },
      "client_info": {
        "telemetry_sdk_build": "12.0.0",
        "first_run_date": "2019-09-30-04:00",
        "os": "Android",
        "android_sdk_version": "28",
        "os_version": "9",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a XL",
        "architecture": "arm64-v8a",
        "app_channel": "release",
        "app_build": "12610151",
        "app_display_version": "2.0.0",
        "client_id": "b8ddb0d5-6692-44fa-bb55-27a5cc5f09dd"
      }
    }

Based on my comment I will remove the qa:needed until further information.

**Comment by sblatz** [comment]
I updated this to v2.2 as it didn't get in to v2.1. I can investigate to see why the campaignId is not generated.

**Comment by sblatz** [comment]
I have reached out to Loren to get access to Adjust to keep testing this further. Unfortunately we cannot debug this any more without having access to the console itself 😕

**Comment by sblatz** [comment]
@lwa-moz is reaching out to the Adjust team to see if we can get some help on this ticket. 
https://github.com/mozilla-mobile/fenix/pull/5896 is my current progress.

**Comment by sblatz** [comment]
I'm timeboxing E2 more effort for this next sprint.

**Comment by liuche** [comment]
We're getting close, but there are problems with our Adjust integration. Will keep working w/ Loren on this. We should keep pushing on this because it's important.

**Comment by sblatz** [comment]
For QA to test this, please take the following steps:

Before beginning: Retrieve your Google Advertising ID. You can find this in the "Adjust Insights" app on the google play store. Also, make sure the device you're using has not previously installed Fenix. if it has, ask me to remove your device's information from the adjust dashboard. 

1. Make sure no versions of Firefox Preview are installed on your device.

2. Replace `GOOGLE_ADVERTISING_ID` in the link below with your advertising ID. 
For example: 
`f8bc12a4-932a-4a16-a959-4f5626fc3402` becomes 
` https://app.adjust.com/ou6v41x?campaign=social&adgroup=twitter&creative=fr-gtm&gpsadid=f8bc12a4-932a-4a16-a959-4f5626fc3402`
https://app.adjust.com/ou6v41x?campaign=social&adgroup=twitter&creative=fr-gtm&gpsadid=GOOGLE_ADVERTISING_ID

3. Click that link on the device you're wanting to test. It should redirect you to the play store. Do NOT install Fenix from the play store. 

4. Grab the APK for your device here and install it: https://tools.taskcluster.net/groups/b-q2a5bCRWK86nFalo0OUw/tasks/DwAyxjSQSUSB961ogktnrw/runs/0/artifacts (let me know if you don't have permission to see this)

5. Launch the app. Wait 10 seconds on the home screen

6. Force close the app and launch it again. The metric should now be sent in the core ping.

**Comment by AndiAJ** [comment]
Hi, @sblatz when trying to launch the app I've noticed this error in the log:

` 8625-8625/org.mozilla.fenix.debug E/glean/GleanDebugActivity: Glean is not initialized. It may be disabled by the application.`

Please be kind and create a debug APK that has Glean enabled.

**Comment by sblatz** [comment]
Nightly APK can be found here: https://tools.taskcluster.net/index/project.mobile.fenix.v2.nightly/latest

**Comment by AndiAJ** [comment]
@sblatz - I've retried with the new debug build you've sent but I've bumped in this startup crash:

```Kotlin
--------- beginning of crash
2019-11-06 11:47:00.733 15453-15487/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: Gecko
   Process: org.mozilla.fenix.debug, PID: 15453
   java.lang.Exception: Error loading gecko libraries
       at org.mozilla.gecko.mozglue.GeckoLoader.loadGeckoLibsNative(Native Method)
       at org.mozilla.gecko.mozglue.GeckoLoader.loadGeckoLibs(GeckoLoader.java:478)
       at org.mozilla.gecko.GeckoThread.loadGeckoLibs(GeckoThread.java:271)
       at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:289)
       at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:448)
2019-11-06 11:47:00.733 15453-15487/org.mozilla.fenix.debug I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.Exception: Error loading gecko libraries, breadcrumbs=[])
2019-11-06 11:47:00.735 15453-15487/org.mozilla.fenix.debug I/mozac/CrashReporter: Showing prompt
2019-11-06 11:47:00.743 1177-4689/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10177
2019-11-06 11:47:00.748 768-768/? D/android.hardware.power@1.3-service.bonito-libperfmgr: LAUNCH ON
2019-11-06 11:47:00.759 15453-15487/org.mozilla.fenix.debug I/Process: Sending signal. PID: 15453 SIG: 9
2019-11-06 11:47:00.763 1177-1198/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-11-06 11:47:00.763 1177-1198/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-11-06 11:47:00.775 691-691/? I/Zygote: Process 15453 exited due to signal (9)
2019-11-06 11:47:00.775 1177-3950/? I/ActivityManager: Process org.mozilla.fenix.debug (pid 15453) has died: fore TOP
2019-11-06 11:47:00.775 1177-1201/? W/libprocessgroup: kill(-15453, 9) failed: No such process
2019-11-06 11:47:00.775 1177-1201/? I/libprocessgroup: Successfully killed process cgroup uid 10177 pid 15453 in 0ms
2019-11-06 11:47:00.779 571-608/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen org.mozilla.fenix.debug#0
2019-11-06 11:47:00.779 571-608/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen org.mozilla.fenix.debug#0
2019-11-06 11:47:00.780 1177-1320/? W/WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5512 com.android.server.wm.WindowManagerService.removeWindow:1641 com.android.server.wm.Session.remove:226
2019-11-06 11:47:00.797 1177-1197/? I/ActivityManager: Displayed org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity: +1s384ms
2019-11-06 11:47:00.802 1177-1200/? I/ActivityManager: Start proc 15499:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashReporter/u0a177 for activity org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity
`

**Comment by AndiAJ** [comment]
Hi @sblatz good news! The last debug build you've sent works! :smiley:

On the other hand, I've generated two metrics pings and it looks like the "metrics.adjust_campaign": doesn't get populated, in my case with **06c7a972-acf2-480a-8a9f-c865d1cfa1e9** (Google advertising ID from the Adjust Insights app)

[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t071100)

**I'll remove the QA needed label until further notice.**

From the Logcat :

```kotlin
2019-11-08 04:00:00.189 8956-9132/org.mozilla.fenix.debug D/glean/PingUploadWorker: Processing persisted pings at /data/user/0/org.mozilla.fenix.debug/glean_data/pending_pings
2019-11-08 04:00:00.190 8956-9132/org.mozilla.fenix.debug D/glean/PingUploadWorker: Processing ping: 796ea639-8f2d-4e9e-bae5-7ba4145b1df0
2019-11-08 04:00:00.198 8956-9132/org.mozilla.fenix.debug D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fenix-debug/metrics/1/796ea639-8f2d-4e9e-bae5-7ba4145b1df0
    {
      "client_info": {
        "android_sdk_version": "28",
        "app_build": "1",
        "app_channel": "release",
        "app_display_version": "1.0.1945",
        "architecture": "arm64-v8a",
        "client_id": "7cfa1d49-4270-4432-8376-433e14dbcb30",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a XL",
        "first_run_date": "2019-11-07+02:00",
        "os": "Android",
        "os_version": "9",
        "telemetry_sdk_build": "19.1.0"
      },
      "metrics": {
        "boolean": {
          "metrics.default_browser": false
        },
        "string": {
          "metrics.adjust_campaign": "",
          "metrics.total_uri_count": "0"
        },
        "string_list": {
          "metrics.mozilla_products": [
            "org.mozilla.firefox"
          ]
        }
      },
      "ping_info": {
        "end_time": "2019-11-08T04:00+02:00",
        "ping_type": "metrics",
        "seq": 1,
        "start_time": "2019-11-07T14:39+02:00"
      }
    }
2019-11-08 04:00:00.209 8956-9132/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/metrics/1/796ea639-8f2d-4e9e-bae5-7ba4145b1df0
2019-11-08 04:00:01.250 8956-9132/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Ping successfully sent (200)
___________________________________________________________________________________________________________

2019-11-09 04:00:00.157 9247-9418/org.mozilla.fenix.debug D/glean/PingUploadWorker: Processing persisted pings at /data/user/0/org.mozilla.fenix.debug/glean_data/pending_pings
2019-11-09 04:00:00.158 9247-9418/org.mozilla.fenix.debug D/glean/PingUploadWorker: Processing ping: 454575a7-f266-4289-9b3e-99fa8fddcfb0
2019-11-09 04:00:00.165 9247-9418/org.mozilla.fenix.debug D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fenix-debug/metrics/1/454575a7-f266-4289-9b3e-99fa8fddcfb0
    {
      "client_info": {
        "android_sdk_version": "28",
        "app_build": "1",
        "app_channel": "release",
        "app_display_version": "1.0.1945",
        "architecture": "arm64-v8a",
        "client_id": "7cfa1d49-4270-4432-8376-433e14dbcb30",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a XL",
        "first_run_date": "2019-11-07+02:00",
        "os": "Android",
        "os_version": "9",
        "telemetry_sdk_build": "19.1.0"
      },
      "metrics": {
        "boolean": {
          "metrics.default_browser": false
        },
        "string": {
          "metrics.adjust_campaign": "",
          "metrics.total_uri_count": "0"
        },
        "string_list": {
          "metrics.mozilla_products": [
            "org.mozilla.firefox"
          ]
        }
      },
      "ping_info": {
        "end_time": "2019-11-09T04:00+02:00",
        "ping_type": "metrics",
        "seq": 2,
        "start_time": "2019-11-08T04:00+02:00"
      }
    }
2019-11-09 04:00:00.170 9247-9418/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix-debug/metrics/1/454575a7-f266-4289-9b3e-99fa8fddcfb0
2019-11-09 04:00:00.384 9247-9418/org.mozilla.fenix.debug D/glean/ConceptFetchHttpUploader: Ping successfully sent (200)
`

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest debug build sent by Sawyer. 
```kotlin

   "string": {
          "metrics.adjust_campaign": "social",
          "metrics.total_uri_count": "0"
        },

```
[Logcat](https://github.com/mozilla-mobile/fenix/files/3820764/AdjustCampaignID.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-t071102)

@sblatz - Great job! 😄
