### ISSUE TITLE
[Bug] Crash in PWA  java.lang.IllegalArgumentException: Value to select is not in list

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#12998]
Sentry link: https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+Value+to+select+is+not+in+list&statsPeriod=14d

## Steps to reproduce
I don't know the exact steps for this but somehow I was able to get a custom tab like adress bar on a pwa(proxx.app). Then clicking on open in firefox nightly caused this crash

```
d154cceb-39fa-4ebb-897a-eb65c36f6101
java.lang.IllegalArgumentException: Value to select is not in list
----
java.lang.IllegalArgumentException: Value to select is not in list
	at mozilla.components.browser.session.LegacySessionManager.select(LegacySessionManager.kt:9)
	at mozilla.components.browser.session.SessionManager.select(SessionManager.kt:1)
	at org.mozilla.fenix.components.toolbar.DefaultBrowserToolbarController.handleToolbarItemInteraction(BrowserToolbarController.kt:82)
	at org.mozilla.fenix.components.toolbar.BrowserInteractor.onBrowserToolbarMenuItemTapped(BrowserInteractor.kt:1)
	at org.mozilla.fenix.customtabs.ExternalAppBrowserFragment$initializeUI$$inlined$also$lambda$1.invoke(ExternalAppBrowserFragment.kt:3)
	at org.mozilla.fenix.customtabs.-$$LambdaGroup$ks$kUJ3hKe1jMjWpKBcwxkjEHe8iuI.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:1)
	at mozilla.components.browser.menu.item.-$$LambdaGroup$js$qlJR7lRP9zTXPbhRa0IgzpQbl74.onClick(java-style lambda group:4)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


```

### Device information
* Android device: Asus Zenfone
* Fenix version: fenix nightly

**Comment by s-ankur** [comment]
Ok found the str:
1. Pin the app to the screen
2. Press back (custom tab bar appears)
3. Click open in firefox

**Comment by abodea** [comment]
Hi, @s-ankur I wasn't able to reproduce this issue on the latest Nightly 8/3 with Google Pixel 4 XL (11).
Can you please provide a video/gif when you reproduce the issue?

**Comment by s-ankur** [comment]
@abodea take a look
![GifMaker_lowquality](https://user-images.githubusercontent.com/33252312/89199341-0872b000-d5cc-11ea-9e47-c47e9ae3e1f1.gif)

**Comment by abodea** [comment]
Can you please give me the link for the PWA you are using?

**Comment by s-ankur** [comment]
This happens on any pwa. I just reproduced it for proxx.app for example

**Comment by abodea** [comment]
Thank you for the information @s-ankur!
I was thinking at that too as I didn't use LineageOS and I don't have a device available with that.
I will keep investigating and get back with more information.

**Comment by BranescuMihai** [comment]
It probably is a OS specific bug, so until we're able to reproduce, I'll add a waiting label

**Comment by bifleming** [comment]
Per Chenxia:  low crash signature so removing from Hershey sprint.
