### ISSUE TITLE
FNX2-15617 ⁃ AddonsManagementFragment.access$showInstallationDialog: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#13018]
https://sentry.prod.mozaws.net/share/issue/ca34c07eccf14f99bd4367020c6da549/

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
    at androidx.fragment.app.DialogFragment.show(DialogFragment.java:5)
    at org.mozilla.fenix.addons.AddonsManagementFragment.access$showInstallationDialog(AddonsManagementFragment.kt:19)
    at org.mozilla.fenix.addons.-$$LambdaGroup$ks$LN3THPxD9zCyCA3vk2WzVj4sFf0.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:58)
    at mozilla.components.feature.addons.-$$LambdaGroup$ks$_HIPVZOvbmOxwps1M61uurZH_lk.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:13)
    at mozilla.components.browser.engine.gecko.GeckoEngine$installWebExtension$$inlined$apply$lambda$3.onValue(GeckoEngine.kt:6)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

org.mozilla.geckoview.UncaughtException: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8347)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/android-components/issues/7782 which was fixed in A-C.
