### ISSUE TITLE
FNX2-15619 ⁃ Intermittent UI test failure - SettingsAboutTest.verifyAboutFirefoxPreview

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13021]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8101451781503674348/executions/bs.4b65f279ec4abb42/testcases/2/test-cases

Failed 2/2 tries.

### Stacktrace:
`androidx.test.espresso.PerformException: Error performing 'single click' on view '(with id: org.mozilla.fenix.debug:id/menuButton)'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:368)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.navigateBackToAboutPage(SettingsSubMenuAboutRobot.kt:68)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:78)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:63)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:45)
at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:78)
at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:24)
at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:114)
at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:77)`

**Comment by AaronMT** [comment]
(@sv-ohorvath)

This fails on ```    navigateBackToAboutPage(::assertPrivacyNotice)```
I think the issue is that after the call to `navigateBackToAboutPage(::assertSupport)` we're not in the home screen anymore and `navigateBackToAboutPage` assumes we're in the home-screen

```Kotlin
private fun navigateBackToAboutPage(itemToInteract: () -> Unit) {
    homeScreen {
    }.openThreeDotMenu {
    }.openSettings {
    }.openAboutFirefoxPreview {
        itemToInteract()
    }
}

and openThreeDotMenu is looking for `R.id.menu` when it should be looking for `mozac_browser_toolbar_menu`
