### ISSUE TITLE
[Bug] Crash when using QR Code at Synced tabs level: @kotlin.KotlinNullPointerException: at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:36)

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13064]
## Pre-requisites:
* Be logged in on Firefox Desktop Nightly
* Make a clear data of the browser
    1. Steps to reproduce

1. Open browser go to Settings/ Sign in with a QR code.
1. Tap on the "Allow" button from the dialog box.
1. On Firefox Nightly desktop go to firefox.com/pair and tap on the "Show code" button.
1. Scan the provided QR code with the device with latest Nightly.
1. Confirme pairing on mobile.
1. Confirme pairing on desktop.
1. Go to Settings/Synced tabs.
1. Wait a couple of seconds.
    1. Expected behavior
No crash happening
    1. Actual behavior
Crash present
    1. Device information

* Android device: Google Pixel 3XL (Android 9)
* Fenix version: Nightly 7/26 AC: 52.0.2020072530253
* Firefox Nightly Desktop: 81.0a1 (2020-07-28) (64-bit)

Crash link: https://crash-stats.mozilla.org/report/index/94cb06ca-cd4a-4ca2-8034-59c9c0200729
Note: Reproduced on RB, issue: 1280
AC issue: #7536
Similar java stack trace to: #12201
<details closed><summary>*Fenix Java stacktrace Nightly 7/27*</summary>

android.view.ViewRootImpl$CalledFromWrongThreadException
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7753)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3773)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:917)
	at android.view.View.setFlags(View.java:14096)
	at android.view.View.setVisibility(View.java:9992)
	at org.mozilla.fenix.sync.SyncedTabsLayout.startLoading(SyncedTabsLayout.kt:1)
	at mozilla.components.feature.syncedtabs.controller.DefaultController.refreshSyncedTabs(DefaultController.kt:2)
	at mozilla.components.feature.syncedtabs.presenter.DefaultPresenter$SyncedTabsAccountObserver.onAuthenticated(DefaultPresenter.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$3.invoke(FxaAccountManager.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers(Unknown Source:7)
	at mozilla.components.service.fxa.manager.FxaAccountManager.postAuthenticated(FxaAccountManager.kt:13)
	at mozilla.components.service.fxa.manager.FxaAccountManager$postAuthenticated$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
</details>

**Comment by Diana-Rus** [comment]
Issue still reproduces: https://github.com/mozilla-mobile/android-components/issues/7536#issuecomment-667049532

**Comment by kbrosnan** [comment]
A-C looks to have fixed the issue.
