### ISSUE TITLE
FNX2-18797 ⁃ [Bug] Crash java.lang.ClassCastException: at org.mozilla.fenix.components.toolbar.BrowserToolbarView.expand(BrowserToolbarView.kt:3)

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/fenix#13119]
## Prerequisites
- Have a PWA installed. (I used twitter)
- Have a custom tab opened in PWA in background
### Steps to reproduce
1. Open browser and have one tab opened.
2. Go to Menu/Settings/Customize and set toolbar at the top.
3. Go to the tab opened at step 1.
4. Go to PWA and tap on the more options from PWA and choose "Open in Firefox Beta"
5. In browser to Menu/Settings/Customize and set toolbar at the bottom.
6. Go back to the tab.
7. Go to PWA open an article to have custom tab opened.
8. Tap on the more options from PWA and choose "Open in Firefox Beta".

### Expected behavior
The custom tab is opened.
### Actual behavior
Crash is present.
### Device information

* Android device: Samsung Galaxy S9 (Android 8) and Google Pixel 3 XL (Android 9)
* Fenix version: Fenix Beta 80.0.0 - beta.1 (Build #2015754977), Fenix Nightly 200730 (Build #22120630)

Beta
**Crash Link - Samsung Galaxy S9 (Android 8):** https://crash-stats.mozilla.org/report/index/bp-3574d800-76bb-401b-a472-d69f90200730
**Crash Link - Google Pixel 3XL (Android 9):** https://crash-stats.mozilla.org/report/index/e36ea8b9-d7dd-469d-99ad-768040200730

Nightly:
**Crash Link - Samsung Galaxy S9 (Android 8):** https://crash-stats.mozilla.org/report/index/bp-52712188-5fa1-4116-b423-421560200730

<details closed><summary>Samsung Galaxy S9 - Java stack trace</summary>
java.lang.ClassCastException
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView.expand(BrowserToolbarView.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$17.onSessionSelected(BaseBrowserFragment.kt:2)
	at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.session.LegacySessionManager.select(LegacySessionManager.kt:7)
	at mozilla.components.browser.session.LegacySessionManager.addInternal(LegacySessionManager.kt:13)
	at mozilla.components.browser.session.LegacySessionManager.addInternal$default(LegacySessionManager.kt:1)
	at mozilla.components.browser.session.LegacySessionManager.add(LegacySessionManager.kt:2)
	at mozilla.components.browser.session.SessionManager.add(SessionManager.kt:19)
	at mozilla.components.browser.session.SessionManager.add$default(SessionManager.kt:1)
	at mozilla.components.feature.tabs.TabsUseCases$AddNewTabUseCase.invoke(TabsUseCases.kt:4)
	at mozilla.components.feature.tabs.TabsUseCases$AddNewTabUseCase.invoke$default(TabsUseCases.kt:2)
	at mozilla.components.feature.tabs.TabsUseCases$AddNewTabUseCase.invoke(TabsUseCases.kt:1)
	at androidx.core.app.AppOpsManagerCompat.invoke$default(AppOpsManagerCompat.java:4)
	at org.mozilla.fenix.HomeActivity.openToBrowserAndLoad(HomeActivity.kt:10)
	at org.mozilla.fenix.HomeActivity.openToBrowserAndLoad$default(HomeActivity.kt:1)
	at org.mozilla.fenix.search.DefaultSearchController.openSearchOrUrl(SearchController.kt:5)
	at org.mozilla.fenix.search.DefaultSearchController.handleUrlCommitted(SearchController.kt:6)
	at org.mozilla.fenix.search.SearchInteractor.onUrlCommitted(SearchInteractor.kt:1)
	at org.mozilla.fenix.search.toolbar.ToolbarView$$special$$inlined$apply$lambda$1.invoke(ToolbarView.kt:4)
	at mozilla.components.browser.toolbar.BrowserToolbar.onUrlEntered$browser_toolbar_release(BrowserToolbar.kt:1)
	at mozilla.components.browser.toolbar.edit.EditToolbar$$special$$inlined$apply$lambda$2.invoke(EditToolbar.kt:2)
	at mozilla.components.ui.autocomplete.-$$LambdaGroup$ks$9_fkSK7DtinkLAKrijGuEFpfNFk.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:13)
	at mozilla.components.ui.autocomplete.InlineAutocompleteEditTextKt$sam$android_view_View_OnKeyListener$0.onKey(Unknown Source:6)
	at android.view.View.dispatchKeyEvent(View.java:12353)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1855)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:592)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:15)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:471)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5590)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5453)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5003)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4969)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5106)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5163)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5003)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4969)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7719)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7659)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7620)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4595)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

<details>

**Comment by Diana-Rus** [comment]
Reproducible on Firefox 79.0.2 with Samsung Galaxy S9 (Android 8).
Crash Link: https://crash-stats.mozilla.org/report/index/75665361-0174-41e7-a3f1-518cf0200803

**Comment by liuche** [comment]
This one seems to have decreased to almost nothing in release! https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=is%3Aunresolved+BrowserToolbarView&statsPeriod=14d
