### ISSUE TITLE
Intermittent verifyPageMainMenuItemsListInPortraitNormalModeTest Expected: has item: has descendant: with text: is "Test_Page_1" 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#13163]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=311571822&repo=fenix

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'has item: has descendant: with text: is "Test_Page_1"' doesn't match the selected view.
Expected: has item: has descendant: with text: is "Test_Page_1"
Got: "RecyclerView{id=2131362936, res-name=top_sites_list, visibility=VISIBLE, width=550, height=214, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4aadb47, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=44.0, child-count=3}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertExistingTopSitesTabs(HomeScreenRobot.kt:693)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertExistingTopSitesTabs(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyExistingTopSitesTabs(HomeScreenRobot.kt:111)
at org.mozilla.fenix.ui.SmokeTest$verifyPageMainMenuItemsListInPortraitNormalModeTest$25.invoke(SmokeTest.kt:108)
at org.mozilla.fenix.ui.SmokeTest$verifyPageMainMenuItemsListInPortraitNormalModeTest$25.invoke(SmokeTest.kt:27)
at org.mozilla.fenix.ui.robots.TabDrawerRobot$Transition.openHomeScreen(TabDrawerRobot.kt:142)
at org.mozilla.fenix.ui.SmokeTest.verifyPageMainMenuItemsListInPortraitNormalModeTest(SmokeTest.kt:107)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: 'has item: has descendant: with text: is "Test_Page_1"' doesn't match the selected view.
Expected: has item: has descendant: with text: is "Test_Page_1"
Got: "RecyclerView{id=2131362936, res-name=top_sites_list, visibility=VISIBLE, width=550, height=214, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@4aadb47, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=44.0, child-count=3}"
at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:15)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:15)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:10)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sv-ohorvath** [comment]
will be fixed on https://github.com/mozilla-mobile/fenix/issues/13217
