### ISSUE TITLE
[Bug] Crash @ mozilla.appservices.logins.LoginsStorageException: at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4) 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13253]
## Steps to reproduce
1. Just updated Fenix Nightly.
2. Twitter PWA was already installed.
3. Close Fenix.
4. Insert login credentials and submit on the Twitter PWA.
### Expected behavior
Logged in.
### Actual behavior
App crashed.
Cannot reproduce again with the same STR.
Crash report: [Socorro](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=mozilla.appservices.logins.LoginsStorageException%3A%20at%20mozilla.appservices.logins.rust.RustError.intoException%28RustError.kt%3A4%29&date=%3E%3D2020-07-28T11%3A58%3A00.000Z&date=%3C2020-08-04T11%3A58%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1)

Looks like it's growing, but could be related to more installs: https://crash-stats.mozilla.org/signature/?product=Fenix&signature=mozilla.appservices.logins.LoginsStorageException%3A%20at%20mozilla.appservices.logins.rust.RustError.intoException%28RustError.kt%3A4%29

### Device information

* Android device: HTC Nexus 9 (Android 7.1.1)
* Fenix version: Nightly 8/4

**Comment by liuche** [comment]
@ekager do you think this is a bug in AS that we should push over?

**Comment by ekager** [comment]
Crash Log: 
```
mozilla.appservices.logins.LoginsStorageException
	at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:4)
	at mozilla.appservices.logins.DatabaseLoginsStorage.potentialDupesIgnoringUsername(DatabaseLoginsStorage.kt:24)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getPotentialDupesIgnoringUsername$2.invokeSuspend(SyncableLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getPotentialDupesIgnoringUsername$2.invoke(SyncableLoginsStorage.kt)
	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getPotentialDupesIgnoringUsername(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.DefaultLoginValidationDelegate$getPotentialDupesIgnoringUsernameAsync$1.invokeSuspend(DefaultLoginValidationDelegate.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```
