### ISSUE TITLE
Intermittent UI test failure - tabMediaControlButtonTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#13284]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8498317768625901405/executions/bs.e6b6f5ca5b5337de/testcases/2/test-cases

### Stacktrace:
` java.lang.NullPointerException
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot.clickMediaPlayerPlayButton(BrowserRobot.kt:337)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:128)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:29)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:106)
at org.mozilla.fenix.ui.MediaNotificationTest.tabMediaControlButtonTest(MediaNotificationTest.kt:126)
at java.lang.reflect.Method.invoke(Native Method) `
### Build:

**Comment by sv-ohorvath** [comment]
The test is failing with a different error now: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8043842123572528467/executions/bs.16ef90c519665c2b/testcases/2/test-cases
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.mozilla.fenix.ui.robots.BrowserRobot.waitForPlaybackToStart(BrowserRobot.kt:344)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:129)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:29)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:107)
at org.mozilla.fenix.ui.MediaNotificationTest.tabMediaControlButtonTest(MediaNotificationTest.kt:126`


And I have the feeling videoPlaybackSystemNotificationTest is also failing for the same reason: From the video, in both cases it seems that pressing the play button doesn't start the playback

videoPlaybackSystemNotificationTest:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8043842123572528467/executions/bs.55e0f8673fb78da8/testcases/2/test-cases
`androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Pause, RESOURCE_ID=android:id/action0]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.NotificationRobot.clickMediaSystemNotificationControlButton(NotificationRobot.kt:59)
at org.mozilla.fenix.ui.MediaNotificationTest$videoPlaybackSystemNotificationTest$3.invoke(MediaNotificationTest.kt:66)
at org.mozilla.fenix.ui.MediaNotificationTest$videoPlaybackSystemNotificationTest$3.invoke(MediaNotificationTest.kt:29)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openNotificationShade(BrowserRobot.kt:405)
at org.mozilla.fenix.ui.MediaNotificationTest.videoPlaybackSystemNotificationTest(MediaNotificationTest.kt:64)`

**Comment by sv-ohorvath** [comment]
Moving to https://github.com/mozilla-mobile/fenix/issues/15754 to avoid keeping duplicates.
