### ISSUE TITLE
IllegalStateException: FragmentManager has been destroyed

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#13285]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6578223/

```
IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
...
(5 additional frame(s) were not displayed)

FragmentManager has been destroyed
```

**Comment by kbrosnan** [comment]
This still happens occasionally.

https://crash-stats.mozilla.org/signature/?product=Fenix&_sort=-date&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java)

**Comment by rpappalax** [comment]
Also hitting this intermittently on UI test in Firebase:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6923402968023229892/executions/bs.88c9f5b07912dc68/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Crashed again on 12/19 in UI tests: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6816091270075232443/executions/bs.b4a138a0bfd86ff2
`java.lang.IllegalStateException: FragmentManager has been destroyed
     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 15638
java.lang.IllegalStateException: FragmentManager has been destroyed
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1795)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1855)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by sv-ohorvath** [comment]
Crashed again on 12/26/20 in UI tests: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8045773042123214655/executions/bs.8604c5927b145c5b/testcases/3/test-cases
