### ISSUE TITLE
Intermittent UI test failure - MediaNotificationTest.tabMediaControlButtonTest

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#13283]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8498317768625901405/executions/bs.e6b6f5ca5b5337de/testcases/2/test-cases

### Stacktrace:
` java.lang.NullPointerException
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot.clickMediaPlayerPlayButton(BrowserRobot.kt:337)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:128)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$2.invoke(MediaNotificationTest.kt:29)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:106) `

**Comment by sv-ohorvath** [comment]
Seen this on https://github.com/mozilla-mobile/fenix/issues/12645 as well. I'll add this info to that issue and close so we don't keep duplicate bugs with the same error.
