### ISSUE TITLE
FNX-14489 ⁃ [Bug] RemoteServiceException: Bad notification for startForeground: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#13308]
Unfortunately the exception doesn't reveal where the problem is and if it is Fenix or AC code. We may have to check our foreground services. Interestingly only on Android 8 devices so far.

```
android.app.RemoteServiceException: Bad notification for startForeground: java.util.ConcurrentModificationException
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

https://sentry.prod.mozaws.net/share/issue/bc752fc30588485184f605ce1aa86810/

**Comment by rocketsroger** [comment]
> CC @rocketsroger - I think you recently investigated this.

I investigated the newly linked Sentry issue.  However, I don't think it is the same as the original issue.  I'll open a new issue to track the new crash.

**Comment by rocketsroger** [comment]
Created https://github.com/mozilla-mobile/fenix/issues/18400 for the new crash.
