### ISSUE TITLE
FNX-14564 ⁃ Intermittent UI test failure - BookmarksTest.copyBookmarkURLTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#13384]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6759362972106451104/executions/bs.e6e16fa65525668/testcases/1/test-cases

Flaky, failed 1/2.

Not sure if it failed because of https://github.com/mozilla-mobile/fenix/issues/11364 or other reasons. 
### Stacktrace:
`java.lang.IllegalStateException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$copyBookmarkURLTest$3.invoke(BookmarksTest.kt:196)
at org.mozilla.fenix.ui.BookmarksTest$copyBookmarkURLTest$3.invoke(BookmarksTest.kt:35)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:170)
at org.mozilla.fenix.ui.BookmarksTest.copyBookmarkURLTest(BookmarksTest.kt:194)`
### Build:

**Comment by sv-ohorvath** [comment]
Same error https://github.com/mozilla-mobile/fenix/issues/10911
