### ISSUE TITLE
[Bug] Crash on opening link from external app

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#13437]
## Steps to reproduce
Can't reproduce consistently but these are the steps when it does happen

From another app, open a link(not custom tab(
Quickly press back repeatedly

### Expected behavior
Leave the app
### Actual behavior
Crash 
```

50ed7601-9683-4e97-b080-2de0e69759d3
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 223644510 Other activity: HomeActivity hashcode 12607951
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=0ec26803453245b486c3e63a357f38fe
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-41e815ce-7df8-4186-9646-573630200809
----
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 223644510 Other activity: HomeActivity hashcode 12607951
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:21)
	at mozilla.components.feature.session.engine.EngineViewPresenter.onEngineSession(EngineViewPresenter.kt:1)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onEngineSession(EngineViewPresenter.kt:1)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$2$2.emit(Collect.kt:3)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:12)
	... 17 more
```

### Device information

* Android device: Asus Zenfone (LineageOS 16)
* Fenix version: Nightly

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/android-components/issues/7960
