### ISSUE TITLE
FNX-14627 ⁃ Intermittent UI test failure - <SettingsBasicsTest.toggleShowVisitedSitesAndBookmarks>

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#13447]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8476421568069324837

Provide a Firebase test run report link here showcasing the problem
### Stacktrace:
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 2 tests, received 0'. Check device logcat for details

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8476421568069324837/executions/bs.87ad3b8177e56b28/testcases/1/logs

**Comment by sv-ohorvath** [comment]
Old issue, haven't seen this in a while so I'm closing it for now.

**Comment by mcarare** [comment]
New failure: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6897193512975365979

`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot.clickAddBookmarkButton(ThreeDotMenuMainRobot.kt:84)
at org.mozilla.fenix.ui.SettingsBasicsTest$toggleShowVisitedSitesAndBookmarks$7.invoke(SettingsBasicsTest.kt:124)
at org.mozilla.fenix.ui.SettingsBasicsTest$toggleShowVisitedSitesAndBookmarks$7.invoke(SettingsBasicsTest.kt:29)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:407)
at org.mozilla.fenix.ui.SettingsBasicsTest.toggleShowVisitedSitesAndBookmarks(SettingsBasicsTest.kt:123)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
`

**Comment by sv-ohorvath** [comment]
Flaky on 1/15: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7533277522827784987/executions/bs.164d43a6569ccd52/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/20: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7622971180691263822/executions/bs.5ff8631ed787d2ac/testcases/2/test-cases
