### ISSUE TITLE
FNX3-22137 ⁃ [Fretboard][Crash] RejectedExecutionException

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/fenix#13549]
https://sentry.prod.mozaws.net/operations/focus-android/issues/4773894/?query=is:unresolved

```
java.util.concurrent.RejectedExecutionException: Task mozilla.components.service.fretboard.scheduler.jobscheduler.SyncJob$onStartJob$1@f95a456 rejected from java.util.concurrent.ThreadPoolExecutor@b4d5cd7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]

ava.util.concurrent.RejectedExecutionException: Task mozilla.components.service.fretboard.scheduler.jobscheduler.SyncJob$onStartJob$1@f95a456 rejected from java.util.concurrent.ThreadPoolExecutor@b4d5cd7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
    at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:584)
    at mozilla.components.service.fretboard.scheduler.jobscheduler.SyncJob.onStartJob(SyncJob.kt:19)
    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5727)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:926)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)

java.lang.RuntimeException: java.util.concurrent.RejectedExecutionException: Task mozilla.components.service.fretboard.scheduler.jobscheduler.SyncJob$onStartJob$1@f95a456 rejected from java.util.concurrent.ThreadPoolExecutor@b4d5cd7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 9]
    at android.app.job.JobService$JobHandler.handleMessage(JobService.java:130)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:5727)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:926)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
```

**Comment by data-sync-user** [comment]
➤ Jeff Boek commented:

Just logging crashes from Sentry, if this belongs in Focus feel free to move it!

**Comment by data-sync-user** [comment]
➤ Sebastian Kaspari commented:

fretboard is no longer supported.
