### ISSUE TITLE
Intermittent UI test failure - <StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle>

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#13830]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7798447958200020942/executions/bs.3cfeff6d3b9d62ae/testcases/1/test-cases
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull$default(WaitNotNull.kt:19)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:98)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:1)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot.verifyEnhancedTrackingProtectionShield(EnhancedTrackingProtectionRobot.kt:31)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitDisableExceptionToggle$5.invoke(StrictEnhancedTrackingProtectionTest.kt:172)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitDisableExceptionToggle$5.invoke(StrictEnhancedTrackingProtectionTest.kt:36)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.enhancedTrackingProtection(EnhancedTrackingProtectionRobot.kt:86)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle(StrictEnhancedTrackingProtectionTest.kt:171)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by sv-ohorvath** [comment]
See also (for the same or similar error): 
https://github.com/mozilla-mobile/fenix/issues/12896
https://github.com/mozilla-mobile/fenix/issues/14524
