### ISSUE TITLE
[Bug] Intermittent closeTabTest 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#13877]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=313205625&repo=fenix

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.verifySnackBarText(TabDrawerRobot.kt:77)
at org.mozilla.fenix.ui.TabbedBrowsingTest$closeTabTest$1$5.invoke(TabbedBrowsingTest.kt:171)
at org.mozilla.fenix.ui.TabbedBrowsingTest$closeTabTest$1$5.invoke(TabbedBrowsingTest.kt:41)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:385)
at org.mozilla.fenix.ui.TabbedBrowsingTest.closeTabTest(TabbedBrowsingTest.kt:168)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by rpappalax** [comment]
seeing this once again today: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7543632078584895162/executions/bs.11c89a9936b89a/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Failed again: sometimes just flaky, other times consistent 2 out of 2 fails: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6381147232444032779/executions/bs.a81d0214cd92fa99/testcases/2/test-cases

**Comment by rpappalax** [comment]
same comment as Oana:
commit log:
https://github.com/mozilla-mobile/fenix/runs/1025380853
https://github.com/mozilla-mobile/fenix/runs/1027320829

failure 2/2:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9140652420472775937/executions/bs.b88c261e2f963a58/test-cases

failure 2/2:

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8073250484795287600/executions/bs.a2a4c8616bd52aef/testcases/2/test-cases

**Comment by rpappalax** [comment]
@sv-ohorvath this may help
```
androidx.test.espresso.PerformException: Error performing 'fast swipe' on view '(with id: org.mozilla.fenix.debug:id/mozac_browser_tabstray_title and with text: is "Test_Page_4")'. 
```

**Comment by sv-ohorvath** [comment]
This test is almost identical to closePrivateTabTest which doesn't fail, the only difference is that in the latter the tab is always closed at the end of the test, so the test only runs with one tab at a time.
While closeTabTest runs with multiple tabs opened, causing flakiness due to other existing issues with the tabs tray.
In the end, I've decided to make the test shorter to prevent flakiness so this will test only basic steps of closing a single tab.
I'll shorten the closePrivateTabTest as well because testing with 4 pages but only one open at a time is redundant.
