### ISSUE TITLE
[Bug] Long press on item in downloads crashes app

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#13974]
## Steps to reproduce
Go to downloads from the three dot menu and long press on any item.

### Expected behavior
The item should be selected.

### Actual behavior
The app crashes

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200820 03:27 (Build #2015759003)
AC: 56.0.20200819190136, fb5d4191c
GV: 81.0a1-20200818092452
AS: 61.0.10

**Comment by mcarare** [comment]
AFAIK this is not fully implemented yet, and it was release just in Nightly. Thank you for report, we will keep this in mind.

**Comment by sflorean** [comment]
### Device information
* Android device: Samsung Galaxy Note 10(Android 10), Google Pixel 3 (Android 11).
* Fenix version: Nightly 8/20

2c720efd-c734-4797-b646-8c180dee9b12
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=b37eabfe150e4db296f8720d6a2870a2
* Socorro: https://crash-stats.mozilla.org/report/index/bp-1a204375-68aa-4448-8693-50c750200820
----
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
at org.mozilla.fenix.library.downloads.DownloadInteractor.select(DownloadInteractor.kt:3)
at org.mozilla.fenix.library.LibrarySiteItemView$setSelectionInteractor$2.onLongClick(LibrarySiteItemView.kt:2)
at android.view.View.performLongClickInternal(View.java:7959)
at android.view.View.performLongClick(View.java:7909)
at android.view.View.performLongClick(View.java:7927)
at android.view.View$CheckForLongPress.run(View.java:29320)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8016)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by Amejia481** [comment]
cc @kglazko

**Comment by sflorean** [comment]
Extra info: after the crash, all downloaded items are not displayed in Downloads. 
cc @kglazko

**Comment by kglazko** [comment]
Thank you for reporting this. At this time, we don't support "selecting" downloads so I think any behavior tied to a long press needs to be disabled. In terms of the items not being displayed anymore, right now they only persist across a session. There is an AC issue currently in progress for persisting the items on memory and restoring them @sflorean 

I will address disabling actions tied to a long press in a corresponding PR.

**Comment by madb1lly** [comment]
Hi all,
Me too, Nokia 8 with Android 9, latest Nightly.
Cheers 🙂
