### ISSUE TITLE
FNX-5005 ⁃ [Bug] crash: action_browserFragment_to_homeFragment is unknown to this NavController

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1406]
### Steps to reproduce
1. make sure Fenix is your default browser
1. open a link from twitter (probably the same happens from other apps as well)
1. press the home button

### Expected behavior
You're on the home screen.

### Actual behavior
Fenix crashes.

```
2019-04-05 09:08:24.487 9782-9782/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 9782
    java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.debug:id/action_browserFragment_to_homeFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:816)
        at androidx.navigation.NavController.navigate(NavController.java:757)
        at androidx.navigation.NavController.navigate(NavController.java:743)
        at androidx.navigation.NavController.navigate(NavController.java:875)
        at org.mozilla.fenix.components.toolbar.ToolbarIntegration$$special$$inlined$let$lambda$2.invoke(ToolbarIntegration.kt:57)
        at org.mozilla.fenix.components.toolbar.ToolbarIntegration$$special$$inlined$let$lambda$2.invoke(ToolbarIntegration.kt:24)
        at mozilla.components.concept.toolbar.Toolbar$ActionButton$createView$$inlined$also$lambda$1.onClick(Toolbar.kt:183)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24779)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 3ad204712a7321ffc8b472cf261407fa16a5c8b3

**Comment by cadeyrn** [comment]
Fenix no longer crashes for me with the STR from the initial report.
