### ISSUE TITLE
IllegalStateException: swipeRefresh must not be null

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#14125]
https://sentry.prod.mozaws.net/share/issue/916107d83867487a81a9aa6a4b2284f9/
```
IllegalStateException: swipeRefresh must not be null
    at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$2.emit(Collect.kt:4)
    at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$1$1.emit(Collect.kt:5)
...
(10 additional frame(s) were not displayed)

swipeRefresh must not be null
```

**Comment by agi** [comment]
I get this crash whenever I restart a PWA.

STR:

- open a PWA (like twitter)
- press HOME button
- reopen PWA from launcher
- crash

**Comment by ekager** [comment]
Possible dupe of #13388

**Comment by agi** [comment]
FWIW I can't reproduce this anymore.
