### ISSUE TITLE
IllegalStateException  SET SESSION: Current activity: HomeActivity hashcode 25933713 Other activity: HomeActivity hashcode 89910851 Display already acquired

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#14225]
[Bug] Custom tabs remains on android app switcher and crashes

## Steps to reproduce
Open a link in custom tab via clicking in telegram x
Example link: https://ty.gl/ppaiss3xc

### Expected behavior
When i exit custom tab via pressing X or back button, custom tab should be removed from app switcher

### Actual behavior
It remains.
Also when i click to open it in app switcher, android throws me back to home screen and after that when i click to firefox app, it crashes.
![resim](https://user-images.githubusercontent.com/17825767/91313635-44a9c280-e7be-11ea-937a-45446ad61c2b.png)
![resim](https://user-images.githubusercontent.com/17825767/91313665-4d9a9400-e7be-11ea-8ef4-312a0fa8511c.png)

### Device information

* Android device: XZ1 Android 10
* Fenix version: both 26/8 nightly and 80.0.1-beta2

**Comment by hokonch** [comment]
I was about to file a new crash report, but it seems to be almost the same with this issue, so I post here.

## Steps to reproduce
Tested with Telegram 7.01 (latest)

1. Open app link on Telegram
2. Tap "Open in Firefox Nightly"
3. You can see another Firefox in the recent screen and switch it.
4. Add a Private tab and you will see suddenly Firefox quitting
5. Restart Firefox 
6. Switch the another Firefox
7. Open the Private tab
8. Crash

## Crash Report
a141c7af-59eb-4544-b21e-4918a8257a64
java.lang.IllegalStateException: SET SESSION: Current activity: ExternalAppBrowserActivity hashcode 201832333 Other activity: HomeActivity hashcode 138825512
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=d9a21bbee16543379aabf4a956134a45
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-294dc788-1779-4ce4-bc91-a39ad0200909
----
```
java.lang.IllegalStateException: SET SESSION: Current activity: ExternalAppBrowserActivity hashcode 201832333 Other activity: HomeActivity hashcode 138825512
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:21)
	at mozilla.components.feature.session.engine.EngineViewPresenter.onTabToRender(EngineViewPresenter.kt:4)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:1)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:15)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:7)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:12)
	... 16 more
```

## Screen Record
![mozilla-mobile_fenix_issues_14225](https://user-images.githubusercontent.com/54430032/92637191-7c168400-f313-11ea-8db7-2652987173c7.gif)

**Comment by liuche** [comment]
Looks like it's being worked on in AC: https://github.com/mozilla-mobile/android-components/issues/7960

**Comment by pocmo** [comment]
Telegram sets the NEW_TASK flag and this causes us to start in a new task - outside of the telegram task. That is different than what apps like gmail do. Anyhow, leaving with `finishAndRemoveTask()` seems to fix that [and even send us back to Telegram]. So far this doesn't seem to have any negative side effects.

**Comment by hakkikaancaliskan** [comment]
I can confirm my problem is fixed.

**Comment by pocmo** [comment]
Awesome, thank you!
