### ISSUE TITLE
Loading default top sites causes StrictMode disk read violations

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#14252]
We [temporarily disabled StrictMode](https://github.com/mozilla-mobile/fenix/blob/5f92de58ae8497739be6e1dd59da127b1441844e/app/src/main/java/org/mozilla/fenix/components/Core.kt#L271) for top sites as it was a breaking change from AC that we needed to land. However, we should change this so that we are no longer causing a violation.

```
2020-08-26 17:33:05.491 org.mozilla.fenix.debug D/StrictMode: StrictMode policy violation; ~duration=118 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:592)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:787)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:439)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:178)
        at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:123)
        at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:99)
        at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:42)
        at org.mozilla.fenix.settings.advanced.LocaleManagerExtensionKt.getSelectedLocale(LocaleManagerExtension.kt:39)
        at org.mozilla.fenix.settings.advanced.LocaleManagerExtensionKt.getSelectedLocale$default(LocaleManagerExtension.kt:37)
        at org.mozilla.fenix.components.Core$topSiteStorage$2.invoke(Core.kt:278)
        at org.mozilla.fenix.components.Core$topSiteStorage$2.invoke(Core.kt:74)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.components.Core.getTopSiteStorage(Unknown Source:2)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$2.invoke(HomeFragment.kt:201)
        at org.mozilla.fenix.home.HomeFragment$onCreateView$2.invoke(HomeFragment.kt:117)
        at org.mozilla.fenix.components.StoreProviderFactory.create(StoreProvider.kt:42)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at org.mozilla.fenix.components.StoreProvider$Companion.get(StoreProvider.kt:46)
        at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:195)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
    	at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt
```

cc: @gabrielluong

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5615)

**Comment by mcomella** [comment]
Thanks for filing.

Triage: we should try to avoid introducing new StrictMode suppressions and it's easier to fix closer to when this lands so so putting as high priority in the inter-team bug list.

**Comment by Mugurell** [comment]
Hey @gabrielluong 
This ticket got into our sprint but saw that you are working on https://github.com/mozilla-mobile/android-components/issues/8491 which could also solve this.
Do you think this would be the case and so you should be the owner of this too or the changes you are working on will not touch this scenario?

**Comment by liuche** [comment]
Makes sense, @gabrielluong will handle this work in the above-mentioned ticket.

**Comment by mcomella** [comment]
Triage: can tackle as part of the homescreen improvements: P1.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807366

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
