### ISSUE TITLE
[Bug] Crash on editing a bookmark feilds to be completely blank

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14450]
## Steps to 
Save bookmark
Edit it
Erase both feilds

### Expected behavior
No crash. Error maybe

### Actual behavior
Crash
```
`1a163380-1c8b-4439-bae8-24672f4f0a68
java.util.ConcurrentModificationException
----
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at mozilla.components.lib.crash.service.SentryService.report(SentryService.kt:29)
	at mozilla.components.lib.crash.CrashReporter$submitCaughtException$1.invokeSuspend(CrashReporter.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

`
```
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Correction: you need to only set the. Url to be blank

**Comment by s-ankur** [comment]
Also happens with invalid urls

**Comment by kleintom** [comment]
See also #14331
