### ISSUE TITLE
java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#14580]
https://sentry.prod.mozaws.net/operations/firefox/issues/9297930

```
java.lang.NoSuchFieldException: _handled
    at java.lang.Class.getDeclaredField(Class.java:929)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:251)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:49)
    at kotlinx.coroutines.CompletedExceptionally.<clinit>(CompletedExceptionally.kt)
    at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:3)
    at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:4)
    at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:2)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:3)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:1)
    at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:5)
    at androidx.core.app.AppOpsManagerCompat.cancel$default(AppOpsManagerCompat.java:1)
    at androidx.lifecycle.BlockRunner$cancel$1.invokeSuspend(CoroutineLiveData.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

java.lang.RuntimeException: java.lang.NoSuchFieldException: _handled
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:270)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:49)
    at kotlinx.coroutines.CompletedExceptionally.<clinit>(CompletedExceptionally.kt)
    at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:3)
    at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:4)
    at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:2)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:3)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:1)
    at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:5)
    at androidx.core.app.AppOpsManagerCompat.cancel$default(AppOpsManagerCompat.java:1)
    at androidx.lifecycle.BlockRunner$cancel$1.invokeSuspend(CoroutineLiveData.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

java.lang.ExceptionInInitializerError: null
    at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:3)
    at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:4)
    at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:2)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:3)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:1)
    at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:5)
    at androidx.core.app.AppOpsManagerCompat.cancel$default(AppOpsManagerCompat.java:1)
    at androidx.lifecycle.BlockRunner$cancel$1.invokeSuspend(CoroutineLiveData.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

kotlinx.coroutines.CompletionHandlerException: Exception in completion handler ChildContinuation[CancellableContinuation(DispatchedContinuation[androidx.room.TransactionExecutor@cc297cd, Continuation at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:80)@8b7ab93]){RemoveReceiveOnCancel[ReceiveHasNext@332d07d0]}@1d6de3c9] for DispatchedCoroutine{Cancelling}@39a76ace
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:7)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:3)
    at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:4)
    at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:20)
    at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:11)
    at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:1)
    at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:5)
    at androidx.core.app.AppOpsManagerCompat.cancel$default(AppOpsManagerCompat.java:1)
    at androidx.lifecycle.BlockRunner$cancel$1.invokeSuspend(CoroutineLiveData.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.AwaitKt.resume(Await.kt:11)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:5)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:2)
    at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by liuche** [comment]
What features rely on Room? I can think of Top Sites and Downloads at the moment.

**Comment by Amejia481** [comment]
There are others too, like add-ons, recent sites, containers, logins ... etc. It's difficult to determent by the stack trace :(

**Comment by amedyne** [comment]
Still occurring, need to investigate further.
