### ISSUE TITLE
[Bug] crash on editing system time with close tabs option

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#14736]
## Steps to reproduce
Select the close tabs-> after one day option in settings (don't close settings)
Change the day from system settings. I don't know if this would happen if the day changes naturally
### Expected behavior
Tabs closed
### Actual behavior
Completely white screen on returning from settings 
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly 200903 06:04 (Build #2015761715)
AC: 58.0.20200901190136, 478151899
GV: 82.0a1-20200831091558
AS: 61.0.13

**Comment by s-ankur** [comment]
```
f3521d8a-bb2b-4f4f-aa26-e11ed3ddf9cc
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 4070 ("DefaultDispatcher-worker-6")
----
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 4070 ("DefaultDispatcher-worker-6")
	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:7)
	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoDisplay.setDynamicToolbarMaxHeight(GeckoDisplay.java:1)
	at org.mozilla.geckoview.GeckoView$Display.setDynamicToolbarMaxHeight(GeckoView.java:3)
	at org.mozilla.geckoview.GeckoView.setDynamicToolbarMaxHeight(GeckoView.java:1)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.setDynamicToolbarMaxHeight(GeckoEngineView.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.initializeEngineView(BaseBrowserFragment.kt:15)
	at org.mozilla.fenix.browser.BaseBrowserFragment.fullScreenChanged(BaseBrowserFragment.kt:27)
	at org.mozilla.fenix.browser.BaseBrowserFragment.access$fullScreenChanged(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19.onSessionSelected(BaseBrowserFragment.kt:1)
	at mozilla.components.browser.session.LegacySessionManager$remove$$inlined$synchronized$lambda$2.invoke(LegacySessionManager.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.session.LegacySessionManager.remove(LegacySessionManager.kt:17)
	at mozilla.components.browser.session.SessionManager.remove(SessionManager.kt:1)
	at mozilla.components.browser.session.SessionManager.remove$default(SessionManager.kt:2)
	at mozilla.components.feature.tabs.TabsUseCases$DefaultRemoveTabUseCase.invoke(TabsUseCases.kt:3)
	at mozilla.components.feature.tabs.TabsUseCases$DefaultRemoveTabUseCase.invoke(TabsUseCases.kt:2)
	at org.mozilla.fenix.HomeActivity$onResume$2.invokeSuspend(HomeActivity.kt:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)


```
Found a crash

**Comment by ekager** [comment]
Seems low priority because of the current known STR include changing the system time.

**Comment by s-ankur** [comment]
I am not sure this won't happen on something like timezone changes etc
