### ISSUE TITLE
[Bug] failed DatabaseLoginsStorage.unlock should not be fatal - restoring on another device crashes Fenix

### ISSUE THREAD

**Issue by ildar** [mozilla-mobile/fenix#14771]
## Steps to reproduce
1. make a backup
2. restore on the different device (phone)

### Actual behavior
Crash. The reason is in that `/data/data/org.mozilla.fenix/databases/logins.sqlite` is encrypted, but Fenix dies on it on the different device.

```
09-05 03:26:22.311 16949 16973 E AndroidRuntime: Process: org.mozilla.fenix, PID: 16949
09-05 03:26:22.311 16949 16973 E AndroidRuntime: mozilla.appservices.logins.InvalidKeyException: Error executing SQL: file is not a database
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.appservices.logins.rust.RustError.intoException(RustError.kt:13)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.appservices.logins.DatabaseLoginsStorage.unlock(DatabaseLoginsStorage.kt:14)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.LoginStorageConnection.init$service_sync_logins_release(SyncableLoginsStorage.kt:4)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$conn$2.invoke(SyncableLoginsStorage.kt:1)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getConn(SyncableLoginsStorage.kt)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.access$getConn$p(SyncableLoginsStorage.kt:1)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invokeSuspend(SyncableLoginsStorage.kt:6)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invoke(SyncableLoginsStorage.kt)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at mozilla.components.service.sync.logins.SyncableLoginsStorage.warmUp(SyncableLoginsStorage.kt:1)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$3$1$1.invokeSuspend(FenixApplication.kt:11)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
09-05 03:26:22.311 16949 16973 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kbrosnan** [comment]
This is a common crash in nightly

**Comment by ildar** [comment]
Should be fixed IMHO as crashes aren't pretty.

**Comment by ildar** [comment]
Is it fixed?
