### ISSUE TITLE
[Bug] Crash when trying to access downloads

### ISSUE THREAD

**Issue by B0pol** [mozilla-mobile/fenix#14772]
## Steps to reproduce
I don't really remember as it was few days ago. I think I have downloaded a picture, erased it and it produced this bug few hours later
### Expected behavior
Not to crash everytime I try to access downloads from three dots menu
### Actual behavior
Crash everytime I try to access downloads 
### Device information

* Android device: Pocophone F1, android 9, 
* Fenix version: nightly 200905

### Additional info

Here is the crash report from about:crashes

6d5426f1-e8cc-4659-a8c6-94311bda268f
java.lang.NumberFormatException: For input string: "null"
 * Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=4cc62880189a4049a334150d3cca861e
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-3d679343-d3f0-42b0-93f3-ab0ff0200905
----
java.lang.NumberFormatException: For input string: "null"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at org.mozilla.fenix.library.downloads.viewholders.DownloadsListItemViewHolder.bind(DownloadsListItemViewHolder.kt:3)
	at org.mozilla.fenix.library.downloads.DownloadAdapter.onBindViewHolder(DownloadAdapter.kt:3)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:146)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:120)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20693)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2799)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2316)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Diana-Rus** [comment]
Hi, i've tried to reproduce this crash but wasn't able to.
- Are you still encountering it on latest Nightly?
- In case you still reproduce this issue could you provide a video with it and extra details?
- Did you have any add-ons installed? 
A similar crash report was present under #14024 and was fixed in the meantime.

**Comment by Amejia481** [comment]
cc @kglazko

**Comment by B0pol** [comment]
@Diana-Rus  

1. Yes
2. Things have changed a bit. I can now access Downloads because I have downloaded more files, but if I scroll down, the crash happens, therefore I guess it's not instantly crashing now because this file is not shown when "downloads" is opened.

Video: 
<img src="https://user-images.githubusercontent.com/58657617/92516144-0f1cc480-f215-11ea-8620-78ee3770f2dc.gif" width="300">
3. Ublock origin, https everywhere, dark reader, privacy badger, search by image. Btw there is a "extensions" tab in sorroco which is empty, is it a known bug?

**Comment by B0pol** [comment]
Btw, sometimes I get notification for "download failed" retry / cancel. If I retry, it tries to download "null", fails and the notification disappear…

**Comment by liuche** [comment]
Download "null" may be #13798

@kglazko do you think this is some fallout from the Downloads deletion changes we made?

**Comment by Amejia481** [comment]
Addressed in https://github.com/mozilla-mobile/fenix/commit/6c68e79a222fabfb32f785513979bf7c9c9bee72

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on  **`RC 83.1.0-rc.1`** using the following devices:
• Samsung Galaxy Tab S6 (Android 10)
• Motorola Moto G6 (Android 8)
• Nexus 9 (Android 7.1.1)
• OnePlus A3 (Android 6.0.1)

**Comment by Amejia481** [comment]
Thanks AndiAJ :)
