### ISSUE TITLE
[Bug]IllegalArgumentException: URI scheme must be http or https

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/fenix#14812]
## Steps to reproduce
Unknown. Seems to be related to `performDownload`

### Device information

* Android device: Android 6, 7, 8, 9 (43% on android 9)
* Fenix version: org.mozilla.firefox_beta-77.0.0-beta.2
 

[Sentry link](https://sentry.prod.mozaws.net/operations/firefox-beta/issues/8536256/)

Stacktrace:
`java.lang.IllegalArgumentException: URI scheme must be http or https
    at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:12)
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:70)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.performDownload$feature_downloads_release(AbstractFetchDownloadService.kt:12)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.startDownloadJob$feature_downloads_release(AbstractFetchDownloadService.kt:3)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService$onStartCommand$1.invokeSuspend(AbstractFetchDownloadService.kt:5)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)`

Stacktrace somewhat similar to https://github.com/mozilla-mobile/fenix/issues/7522

**Comment by Amejia481** [comment]
This is going to be fixed after we land https://github.com/mozilla-mobile/android-components/issues/8312 as we are not going to `GeckoViewFetchClient`  use anymore on downloads, at least on Nightly.

**Comment by pocmo** [comment]
@Amejia481 Wouldn't we still use the client for resume etc.? (Or later retries?)

**Comment by Amejia481** [comment]
I talked with @snorp about it and he said we should be able to do it with the new api

**Comment by Amejia481** [comment]
The crash is only present in old versions of AC([sentry nightly](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8595438/events/)) in this patch https://github.com/mozilla-mobile/android-components/commit/d9976c65d233b270096668bdc4eda90f800a043d we started to mark downloads as FAILED instead of crashing.  

I think we can close this.
