### ISSUE TITLE
FNX-5057 ⁃ IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1483]
https://sentry.prod.mozaws.net/operations/fenix/issues/5506422/

```
IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.get(ArrayList.java:437)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.createControlGroupForCameraPermission$feature_sitepermissions_release(SitePermissionsFeature.kt:3)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.createPrompt(SitePermissionsFeature.kt:48)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature.onContentPermissionRequested$feature_sitepermissions_release(SitePermissionsFeature.kt:9)
    at mozilla.components.feature.sitepermissions.SitePermissionsFeature$SitePermissionsRequestObserver$onContentPermissionRequested$1.invokeSuspend(SitePermissionsFeature.kt:5)
...
(28 additional frame(s) were not displayed)

Index: 1, Size: 1
```

### STR:
* open https://webrtc.github.io/samples/src/content/devices/input-output/
* Accept the Camera/Microphone access
* Tap on the video source drop down
* Select camera 2
* Crash

**Comment by mauryat** [comment]
@kbrosnan can I work on this?

**Comment by Amejia481** [comment]
This will be fix with this PR https://github.com/mozilla-mobile/fenix/pull/1452

**Comment by pocmo** [comment]
This should have been fixed with the latest AC snapshots. Can you please verify this in a recent Fenix Nightly? Tentatively removing the a-c label already.

**Comment by bsurd** [comment]
Tested with the STR provided on a Nexus 6P, Honor 8 and Pixel, everything worked as expected,
