### ISSUE TITLE
Crash in [@ java.io.IOException: at java.io.BufferedWriter.ensureOpen(BufferedWriter.java)]

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14859]
look at this crash report clearing icon cache solve the startup crash
https://crash-stats.mozilla.org/report/index/754ee1a2-c261-4da7-9b21-363100200908

**Comment by kbrosnan** [comment]
Java stack trace:
```
java.io.IOException
	at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
	at java.io.BufferedWriter.write(BufferedWriter.java:221)
	at java.io.Writer.write(Writer.java:157)
	at java.io.Writer.append(Writer.java:227)
	at com.jakewharton.disklrucache.DiskLruCache.get(DiskLruCache.java)
	at mozilla.components.browser.icons.utils.IconDiskCache.getResources(IconDiskCache.kt)
	at mozilla.components.browser.icons.preparer.DiskIconPreparer.prepare(DiskIconPreparer.kt)
	at mozilla.components.browser.icons.BrowserIconsKt.access$prepare(BrowserIcons.kt)
	at mozilla.components.browser.icons.BrowserIcons.access$loadIconInternal(BrowserIcons.kt)
	at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```
