### ISSUE TITLE
[Bug][regression] Crash when signing-in via pairing on Beta 81.1.1-beta.3

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/fenix#14973]
## Steps to reproduce
1. Make sure to have a clean profile.
2. From the Onboarding tour tap on "Sign in to Firefox".
3. Tap on "Ready to scan".

OR
Go to Settings - Turn on Sync and try signing-in via pairing.

### Expected behavior
The user can scan the QR code from desktop.

### Actual behavior
Fenix crashes.

### Device information
* Android device: all
* Fenix version: Beta 81.1.1-beta.3
* Not reproducible on RC 80.1.3, 9/11 Nightly, nor Beta 81.1.0-beta.2

<img src="https://user-images.githubusercontent.com/40694158/92879266-90db4080-f415-11ea-8f5d-5bf3f840b9ab.gif" width="300" height="550" />

**Crash info:**
f40682f6-39ef-42ec-892a-3a6dd80fd10d
androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.mozilla.fenix.settings.PairFragment: calling Fragment constructor caused an exception
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=73638a1a82dc457b86e2ae06d2a8214f
* Socorro: https://crash-stats.mozilla.org/report/index/bp-44c07aec-bdfe-4248-9f0c-f433e0200911
----
androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.mozilla.fenix.settings.PairFragment: calling Fragment constructor caused an exception
at androidx.fragment.app.Fragment.instantiate(Fragment.java:6)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:1)
at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:1)
at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:10)
at androidx.navigation.NavController.navigate(NavController.java:31)
at androidx.navigation.NavController.navigate(NavController.java:20)
at androidx.navigation.NavController.navigate(NavController.java:55)
at org.mozilla.fenix.settings.account.-$$LambdaGroup$js$qmSQ2BPgMZ_4xjq_qfjLk9BD1yk.onClick(java-style lambda group:7)
at android.view.View.performClick(View.java:7353)
at android.widget.TextView.performClick(TextView.java:14210)
at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:2)
at android.view.View.performClickInternal(View.java:7319)
at android.view.View.access$3200(View.java:846)
at android.view.View$PerformClick.run(View.java:27890)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7258)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:3)
... 20 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
at androidx.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:1)
at org.mozilla.fenix.settings.PairFragment.<init>(PairFragment.kt:3)
... 23 more

**Comment by liuche** [comment]
What's weird is that the bug says this isn't reproducible on Fenix Nightly 9/11 - I cut from master, so either the changes didn't make the Nightly last night, or this is something that is different in AC between 58 and the 57 dot release.

**Comment by sflorean** [comment]
Verified as fixed on Beta 81.1.1-beta.4 with the following devices:
- Samsung Galaxy Note 10 (Android 10)
- OnePlus A3 (Android 6.0.1)
- Google Pixel 4XL (Android 10)
- Samsung Galaxy Tab S3 (Android 8)
- Nexus 9 (Android 7.1.1)
- Xiaomi Mi Pad 2 (Android 5.1)
