### ISSUE TITLE
Crash in [@ java.lang.ClassCastException: at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java)] [@ org.mozilla.fenix.browser.BaseBrowserFragment.assignSitePermissionsRules(BaseBrowserFragment.kt)]

### ISSUE THREAD

**Issue by ale82to** [mozilla-mobile/fenix#14986]
suddenly I could not load any website in today nighlty I could just open the app loadinging home, both tapping a top sites and performing a search made fenix crash.
the only solution since I have root was to deleting database folder in data /app.
very annoying here s the soccorro can please someone explain what's Goin on?
https://crash-stats.mozilla.org/report/index/34ecc0c0-4461-486c-ba48-eea3e0200911

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9573460/?query=ClassCastException

**Comment by kbrosnan** [comment]
```
java.lang.ClassCastException
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:252)
	at org.mozilla.fenix.utils.Settings.getSitePermissionsPhoneFeatureAction(Settings.kt)
	at org.mozilla.fenix.utils.Settings.getSitePermissionsPhoneFeatureAction$default(Settings.kt)
	at org.mozilla.fenix.utils.Settings.getSitePermissionsCustomSettingsRules(Settings.kt)
	at org.mozilla.fenix.browser.BaseBrowserFragment.assignSitePermissionsRules(BaseBrowserFragment.kt)
	at org.mozilla.fenix.browser.BaseBrowserFragment.initializeUI(BaseBrowserFragment.kt)
	at org.mozilla.fenix.browser.BrowserFragment.initializeUI(BrowserFragment.kt)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by Amejia481** [comment]
Did you remember any steps previous to the crash? Any site that you visited that required you site permissions?

**Comment by kbrosnan** [comment]
Looks like this can be hit by going to http://http-login.badssl.com/

**Comment by Amejia481** [comment]
Thanks!

**Comment by kbrosnan** [comment]
Eugen pointed out that this is a different stack,

**Comment by Amejia481** [comment]
> Looks like this can be hit by going to http://http-login.badssl.com/
> 
> 1671137

I navigated to http://http-login.badssl.com/ and I wasn't able to replicate the crash,  Is there any additional step to replicate? 
There is a very low number of [crashes on nightly less than 10, only one user](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9573460/?query=ClassCastException),  there are not report on new versions, and I wasn't able to find any event neither in beta nor stable, very likely to be fixed now in nightly. 



@ale82to are you still able to replicate this issue?

**Comment by Amejia481** [comment]
I will close this issue feel free to reopen if needed.
