### ISSUE TITLE
[Bug] opening an empty page with window.open() in custom tab causes unresponsive browser

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15052]
## Steps to reproduce
Open 
https://trianguloy.github.io/githubPages/javascriptEval/javascriptEval.html?window.open() in custom tab and click on the run button

### Expected behavior
Not sure
### Actual behavior
You are navigated to browser from main app. Browser seems unresponsive. Clicking on toolbar or tabs tray does nothing

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
Opening it in a normal tab, clicking run and then adding to home screen causes a crash
```
d13e61fb-7d20-427e-a2d4-d0a85adefe0c
java.lang.IllegalArgumentException: id cannot be empty
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=43377c292e9b409194dbf2a4430783a1
* Socorro: https://crash-stats.mozilla.org/report/index/bp-147974aa-555d-4315-bb32-f3a5e0200913
----
java.lang.IllegalArgumentException: id cannot be empty
at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:96)
at android.content.pm.ShortcutInfo$Builder.<init>(ShortcutInfo.java:934)
at androidx.core.content.pm.ShortcutInfoCompat.toShortcutInfo(ShortcutInfoCompat.java:1)
at androidx.core.content.pm.ShortcutManagerCompat.requestPinShortcut(ShortcutManagerCompat.java:3)
at mozilla.components.feature.pwa.WebAppShortcutManager.requestPinShortcut(WebAppShortcutManager.kt:18)
at mozilla.components.feature.pwa.WebAppUseCases$AddToHomescreenUseCase.invoke(WebAppUseCases.kt:2)
at org.mozilla.fenix.shortcut.CreateShortcutFragment$onViewCreated$2$1.invokeSuspend(CreateShortcutFragment.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:18)
at androidx.core.app.AppOpsManagerCompat.startCoroutineCancellable(AppOpsManagerCompat.java:1)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:17)
at kotlinx.coroutines.AwaitKt.launch(Await.kt:6)
at kotlinx.coroutines.AwaitKt.launch$default(Await.kt:2)
at org.mozilla.fenix.shortcut.CreateShortcutFragment$onViewCreated$2.onClick(CreateShortcutFragment.kt:2)
at android.view.View.performClick(View.java:6608)
at android.view.View.performClickInternal(View.java:6585)
at android.view.View.access$3100(View.java:785)
at android.view.View$PerformClick.run(View.java:25921)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

 
```
