### ISSUE TITLE
[Bug] KotlinNullPointerException: ExternalAppBrowserFragment.access$getBrowserToolbarView

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#15086]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/8980763/?referrer=github_plugin

```
KotlinNullPointerException: None
    at kotlin.jvm.internal.ArrayIteratorKt.throwNpe(ArrayIterator.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment.getBrowserToolbarView(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.customtabs.ExternalAppBrowserFragment.access$getBrowserToolbarView$p(ExternalAppBrowserFragment.kt:1)
    at org.mozilla.fenix.customtabs.ExternalAppBrowserFragment$initializeUI$$inlined$also$lambda$3.invoke(ExternalAppBrowserFragment.kt:2)
    at mozilla.components.feature.pwa.feature.WebAppHideToolbarFeature$start$$inlined$apply$lambda$1$4.emit(Collect.kt:4)
...
(16 additional frame(s) were not displayed)
```

Looks like the `browserToolbarView.view` is reference is assumed to be non-null (not sure if that's something that has changed).

**Comment by jonalmeida** [comment]
I can reproduce this crash quite easily with a PWA open and then trying to scroll up.

https://crash-stats.mozilla.org/report/index/c4d14feb-d22c-4aef-b1ce-2a89e0200915

**Comment by kbrosnan** [comment]
See also 

* https://github.com/mozilla-mobile/android-components/issues/8405
* https://github.com/mozilla-mobile/android-components/issues/8305

**Comment by jonalmeida** [comment]
Note that this crash is in beta.

**Comment by liuche** [comment]
I'm going to dupe this to #15116 bc there's STR.
