### ISSUE TITLE
[Bug] FennecLoginsMPImporter: Failed to check MP validity

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#15106]
Every now and then I see this error in the log. (Firefox Nightly)

```
 FennecLoginsMPImporter  E  Failed to check MP validity
                         E  java.lang.IllegalStateException: Check failed.
                         E      at mozilla.components.support.migration.FennecLoginsMigration.derValue(FennecLoginsMigration.kt:9)
                         E      at mozilla.components.support.migration.FennecLoginsMigration.derDecodeKey4Entry(FennecLoginsMigration.kt:1)
                         E      at mozilla.components.support.migration.FennecLoginsMigration.isMasterPasswordValid$support_migration_release(FennecLoginsMigration.kt:6)
                         E      at mozilla.components.support.migration.FennecLoginsMPImporter.hasMasterPassword(FennecLoginsMPImporter.kt:1)
                         E      at org.mozilla.fenix.components.tips.providers.MasterPasswordTipProvider$shouldDisplay$2.invoke(MasterPasswordTipProvider.kt:2)
                         E      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
                         E      at org.mozilla.fenix.components.tips.providers.MasterPasswordTipProvider.getShouldDisplay(Unknown Source:2)
                         E      at org.mozilla.fenix.components.tips.FenixTipManager.getTip(TipManager.kt:3)
                         E      at org.mozilla.fenix.home.HomeFragment.onStart(HomeFragment.kt:31)
                         E      at androidx.fragment.app.Fragment.performStart(Fragment.java:5)
                         E      at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:3)
                         E      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:28)
                         E      at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
                         E      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
                         E      at androidx.fragment.app.FragmentManager.completeExecute(FragmentManager.java:8)
                         E      at androidx.fragment.app.FragmentManager$StartEnterTransitionListener.completeTransaction(FragmentManager.java:7)
                         E      at androidx.fragment.app.FragmentManager.executePostponedTransaction(FragmentManager.java:15)
                         E      at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:13)
                         E      at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
                         E      at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
                         E      at android.os.Handler.handleCallback(Handler.java:938)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:223)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7656)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by eliserichards** [comment]
MP = Master Password

Possibly related to https://github.com/mozilla-mobile/fenix/issues/13926

**Comment by grigoryk** [comment]
- The `every now and then` part seems problematic here, why are we hitting this API more than exactly once?
- underlying API should short-circuit for non "ex-fennec" installs. currently it doesn't
- I'm surprised there are fennec logins db files present on a non-migrated nightly install. That's... unexpected

**Comment by grigoryk** [comment]
I think we can close this now that https://github.com/mozilla-mobile/android-components/pull/8440 landed.
