### ISSUE TITLE
[Bug] Crash on scanning random QR code while pairing 

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15166]
## Steps to reproduce
Open up pairing using QR code
Scan any QR code other than pairing one

### Expected behavior
Just tell me it's incorrect

### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by s-ankur** [comment]
```
f3521d8a-bb2b-4f4f-aa26-e11ed3ddf9cc
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 4070 ("DefaultDispatcher-worker-6")
----
java.lang.IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 4070 ("DefaultDispatcher-worker-6")
	at org.mozilla.gecko.util.ThreadUtils.assertOnThread(ThreadUtils.java:7)
	at org.mozilla.gecko.util.ThreadUtils.assertOnUiThread(ThreadUtils.java:2)
	at org.mozilla.geckoview.GeckoDisplay.setDynamicToolbarMaxHeight(GeckoDisplay.java:1)
	at org.mozilla.geckoview.GeckoView$Display.setDynamicToolbarMaxHeight(GeckoView.java:3)
	at org.mozilla.geckoview.GeckoView.setDynamicToolbarMaxHeight(GeckoView.java:1)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.setDynamicToolbarMaxHeight(GeckoEngineView.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.initializeEngineView(BaseBrowserFragment.kt:15)
	at org.mozilla.fenix.browser.BaseBrowserFragment.fullScreenChanged(BaseBrowserFragment.kt:27)
	at org.mozilla.fenix.browser.BaseBrowserFragment.access$fullScreenChanged(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19.onSessionSelected(BaseBrowserFragment.kt:1)
	at mozilla.components.browser.session.LegacySessionManager$remove$$inlined$synchronized$lambda$2.invoke(LegacySessionManager.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.session.LegacySessionManager.remove(LegacySessionManager.kt:17)
	at mozilla.components.browser.session.SessionManager.remove(SessionManager.kt:1)
	at mozilla.components.browser.session.SessionManager.remove$default(SessionManager.kt:2)
	at mozilla.components.feature.tabs.TabsUseCases$DefaultRemoveTabUseCase.invoke(TabsUseCases.kt:3)
	at mozilla.components.feature.tabs.TabsUseCases$DefaultRemoveTabUseCase.invoke(TabsUseCases.kt:2)
	at org.mozilla.fenix.HomeActivity$onResume$2.invokeSuspend(HomeActivity.kt:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)


```

**Comment by sflorean** [comment]
@s-ankur this is still the case for you? Wasn't able to reproduce on latest Nightly.

**Comment by s-ankur** [comment]
Neither can I, but it was inconsistent to begin with

**Comment by sflorean** [comment]
I will close this based on the above comments. Fell free to re-open or file a new issue if it is the case.
