### ISSUE TITLE
FNX-5076 ⁃ RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.la...

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#1519]
https://sentry.prod.mozaws.net/operations/fenix/issues/5516076/

```
NoSuchMethodException: org.mozilla.fenix.GleanMetrics.Events$appOpenedKeys.getValue []
    at org.mozilla.fenix.components.metrics.GleanMetricsServiceKt$wrapper$1.invoke(GleanMetricsService.kt:1)
    at org.mozilla.fenix.components.metrics.GleanMetricsService.track(GleanMetricsService.kt:25)
    at org.mozilla.fenix.components.metrics.ReleaseMetricController.track(Metrics.kt:7)
    at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:34)
...
(17 additional frame(s) were not displayed)

RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.NoSuchMethodException: org.mozilla.fenix.GleanMetrics.Events$appOpenedKeys.getValue []
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3249)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
...
(7 additional frame(s) were not displayed)

Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.NoSuchMethodException: org.mozilla.fenix.GleanMetrics.Events$appOpenedKeys.getValue []
```

**Comment by kbrosnan** [comment]
Fixed by f36da2d8f22e769294b42fbd0f2081e835071225
