### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15191]
Sentry exception -> https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9508326/?query=is%3Aunresolved

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
    at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
    at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
    at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:17)
    at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:1)
    at mozilla.components.feature.prompts.PromptFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:6)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:15)
    at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Amejia481** [comment]
cc @ekager I think this is related to this [patch](https://github.com/mozilla-mobile/android-components/blob/8e0b3010027af35265dba1ef4ca18b6f6a0c4295/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L241)

**Comment by ekager** [comment]
Hmm `LoginPicker` isn't a `DialogFragment` though and it was first seen Sept 1 🤔

**Comment by Amejia481** [comment]
👍

**Comment by Amejia481** [comment]
That could be a good idea!
