### ISSUE TITLE
[Bug] Crash in pwa

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#15217]
## Steps to reproduce
Open a pwa covid19india.org
 wait for a bit
### Expected behavior
It does not crash
### Actual behavior
Crash
### Device information

* Android device: ?Asus Zenfone
* Fenix version: ? Nightly

**Comment by s-ankur** [comment]
```
45eac5e4-1af5-4217-9e5f-a20a485a8e30
kotlin.UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=1c79318c34ee4e3ba16efabd1d62f717
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-0a60132d-db08-4da2-9ab8-b38eb0200919
----
kotlin.UninitializedPropertyAccessException: lateinit property browserToolbar has not been initialized
	at kotlin.jvm.internal.ArrayIteratorKt.throwUninitializedPropertyAccessException(ArrayIterator.kt:2)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.tryToScrollVertically$browser_toolbar_release(BrowserToolbarBottomBehavior.kt:7)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior$createGestureDetector$1.invoke(BrowserToolbarBottomBehavior.kt:3)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$gestureDetector$1.invoke(BrowserGestureDetector.kt:5)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector$CustomScrollDetectorListener.onScroll(BrowserGestureDetector.kt:1)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:625)
	at mozilla.components.browser.toolbar.behavior.BrowserGestureDetector.handleTouchEvent$browser_toolbar_release(BrowserGestureDetector.kt:4)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:2)
	at mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior.onInterceptTouchEvent(BrowserToolbarBottomBehavior.kt:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:13)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:3)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
	at android.view.View.dispatchPointerEvent(View.java:12752)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5113)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4916)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7099)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7068)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7029)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7173)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7225)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:690)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


```

**Comment by s-ankur** [comment]
Also reported by @klint

**Comment by anotherus3r** [comment]
Is this the same issue as in #15116? That one has been fixed.

**Comment by s-ankur** [comment]
Aah sorry, haven't updated
