### ISSUE TITLE
[Bug] Crash after retrying failed download

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#15226]
I don't know what triggered it exactly but here's the stacktrace:

8eea040b-022b-4604-8012-a21e2a7fefcb
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: downloads.id (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 11:Try again)
----
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: downloads.id (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 11:Try again)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:923)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:810)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:1)
	at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.java:3)
	at mozilla.components.feature.downloads.db.DownloadDao_Impl$5.call(DownloadDao_Impl.java:2)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### Device information

* Android device: Huawei Nova 6
* Fenix version: Nightly 200918 15:19 (Build #2015764667)
AC: 60.0.20200917190518, a1a5c582c
GV: 82.0a1-20200912220312
AS: 61.0.13

**Comment by Amejia481** [comment]
Thanks for reporting, we are tracking the issue here https://github.com/mozilla-mobile/fenix/issues/15012
