### ISSUE TITLE
Navigation action/destination action_addonsManagementFragment_to_addonDetailsFragmen cannot be found

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15268]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9517377/?query=is%3Aunresolved

```
java.lang.IllegalArgumentException: Navigation action/destination org.mozilla.fenix:id/action_addonsManagementFragment_to_addonDetailsFragment cannot be found from the current destination Destination(org.mozilla.fenix:id/addonDetailsFragment) class=org.mozilla.fenix.addons.AddonDetailsFragment
    at androidx.navigation.NavController.navigate(NavController.java:19)
    at androidx.navigation.NavController.navigate(NavController.java:55)
    at org.mozilla.fenix.addons.AddonsManagementView.onAddonItemClicked(AddonsManagementView.kt:5)
    at mozilla.components.feature.addons.ui.-$$LambdaGroup$js$jde1zyJAQ2sQN7UuakvwrarHOQQ.onClick(java-style lambda group:5)
    at android.view.View.performClick(View.java:5076)
    at android.view.View$PerformClick.run(View.java:20279)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5910)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by Amejia481** [comment]
Very low volume.

**Comment by mcarare** [comment]
This looks like it could be happening on slow devices, if you can trigger two `onAddonItemClicked` events. Should not be possible, normally, but in can be prevented using `navigateSafe` extension.

**Comment by Amejia481** [comment]
> This looks like it could be happening on slow devices, if you can trigger two `onAddonItemClicked` events. Should not be possible, normally, but in can be prevented using `navigateSafe` extension.

Thanks for taking a look :). 

Do you think that it could be happen in other instances? I found that we are using `navController.navigate` in other places,  I was thinking about filing a new issue, what do you think?

![image](https://user-images.githubusercontent.com/773158/93887647-f8ff1180-fcb4-11ea-882b-3785cdec77b3.png)

**Comment by mcarare** [comment]
It would be worth investigating. Other possible STR for this kind of navigation error could be clicking on a view that triggers navigation and quickly pressing back button, and thus changing current destination before navigation takes place.

**Comment by mcarare** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/15299.
