### ISSUE TITLE
Not allowed to start service Intent { cmp=org.mozilla.fenix/.session.PrivateNotificationService }

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15269]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9402755/?query=is%3Aunresolved

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.fenix/.session.PrivateNotificationService }: app is in background uid UidRecord{700fc26 u0a582 TPSL idle change:cached procs:3 proclist:12382,25669,25798, seq(0,0,0)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
    at android.app.ContextImpl.startService(ContextImpl.java:1611)
    at android.content.ContextWrapper.startService(ContextWrapper.java:677)
    at mozilla.components.feature.privatemode.notification.PrivateNotificationFeature$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
    at mozilla.components.feature.privatemode.notification.PrivateNotificationFeature$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:5)
    at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7073)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7197)

**Comment by Amejia481** [comment]
Still happening on the new Sentry.
https://sentry.io/organizations/mozilla/issues/3264313123/?project=6375561&query=is%3Aunresolved+level
