### ISSUE TITLE
A migration from 3 to 2 was required but not found

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15309]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9303990/?query=is%3Aunresolved

```
A migration from 3 to 2 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.

java.lang.IllegalStateException: A migration from 3 to 2 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
    at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:15)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.java:5)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
    at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
    at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
    at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
    at mozilla.components.feature.pwa.db.ManifestDao_Impl.recentManifestsCount(ManifestDao_Impl.java:3)
    at mozilla.components.feature.pwa.ManifestStorage$recentManifestsCount$2.invokeSuspend(ManifestStorage.kt:3)
    at mozilla.components.feature.pwa.ManifestStorage$recentManifestsCount$2.invoke(ManifestStorage.kt)
    at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
    at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
    at mozilla.components.feature.pwa.ManifestStorage.recentManifestsCount(ManifestStorage.kt:1)
    at mozilla.components.feature.pwa.ManifestStorage.recentManifestsCount$default(ManifestStorage.kt:2)
    at mozilla.components.feature.pwa.WebAppShortcutManager.recentlyUsedWebAppsCount(WebAppShortcutManager.kt:1)
    at org.mozilla.fenix.HomeActivity$captureSnapshotTelemetryMetrics$1.invokeSuspend(HomeActivity.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by Amejia481** [comment]
Low volume

**Comment by ekager** [comment]
I'm not sure this is really a crash in the wild or if it just happens when devs overwrite their apps with mismatching versions 🤔

**Comment by Amejia481** [comment]
That sounds like a good explanation, I think we could  close this issue
