### ISSUE TITLE
Intermittent ui-test-x86 failure: org.mozilla.fenix.ui.HistoryTest visitedUrlHistoryTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#15319]
Failed both runs but green on next push.

Log: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8824761659099782053/executions/bs.54444216bb7f9386/testcases/1/test-cases

java.lang.IllegalStateException: activityTestRule.activit…ewById(R.id.history_list) must not be null
at org.mozilla.fenix.ui.HistoryTest$visitedUrlHistoryTest$4.invoke(HistoryTest.kt:86)
at org.mozilla.fenix.ui.HistoryTest$visitedUrlHistoryTest$4.invoke(HistoryTest.kt:33)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openHistory(ThreeDotMenuMainRobot.kt:179)
at org.mozilla.fenix.ui.HistoryTest.visitedUrlHistoryTest(HistoryTest.kt:84)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by rpappalax** [comment]
last previous recorded failure was 2019-09.

**Comment by isabelrios** [comment]
Faling (1/2) on Sept25th: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5929264583686434434/executions/bs.8dcbcf0fb32a2710/test-cases

**Comment by Archaeopteryx** [comment]
Log for multiSelectionToolbarItemsTest: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6742719690826177827/executions/bs.67b906b1d5be2fda/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Old issue, no reported fail recently. Closing
