### ISSUE TITLE
Unable to find explicit activity class {com.whatsapp/com.whatsapp.ContactPicker}

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15310]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/8951548/?query=is%3Aunresolved

```
Unable to find explicit activity class {com.whatsapp/com.whatsapp.ContactPicker}; have you declared this activity in your AndroidManifest.xml?

android.content.ActivityNotFoundException: Unable to find explicit activity class {com.whatsapp/com.whatsapp.ContactPicker}; have you declared this activity in your AndroidManifest.xml?
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1965)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1648)
    at android.app.Activity.startActivityForResult(Activity.java:4502)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
    at android.app.Activity.startActivityForResult(Activity.java:4460)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:3)
    at android.app.Activity.startActivity(Activity.java:4821)
    at android.app.Activity.startActivity(Activity.java:4789)
    at org.mozilla.fenix.share.DefaultShareController.handleShareToApp(ShareController.kt:13)
    at org.mozilla.fenix.share.ShareInteractor.onShareToApp(ShareInteractor.kt:1)
    at org.mozilla.fenix.share.viewholders.AppViewHolder$1.onClick(AppViewHolder.kt:2)
    at android.view.View.performClick(View.java:6311)
    at android.view.View$PerformClick.run(View.java:24823)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6719)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mcarare** [comment]
I cannot find steps to reproduce this. But we can avoid the crash by also catching `ActivityNotFoundException `.

**Comment by mcarare** [comment]
Closed by:https://github.com/mozilla-mobile/fenix/pull/15420.

**Comment by Amejia481** [comment]
Thanks @mcarare !
