### ISSUE TITLE
WorkManager is not initialized properly.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15354]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9308948/?query=is%3Aunresolved

```
Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalStateException: WorkManager is not initialized properly. You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.


java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
    at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:9)
    at org.mozilla.fenix.FenixApplication.setupInMainProcessOnly(FenixApplication.kt:98)
    at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:4)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4797)
    at android.app.ActivityThread.access$1600(ActivityThread.java:157)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5527)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4800)
    at android.app.ActivityThread.access$1600(ActivityThread.java:157)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5527)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by Amejia481** [comment]
Low volume.

**Comment by ekager** [comment]
Last seen 3 months ago. Going to close for now
