### ISSUE TITLE
Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#15353]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9270149/?query=is%3Aunresolved

```
Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class fragment


java.lang.IllegalStateException: DialogFragment 0 doesn't exist in the FragmentManager
    at androidx.navigation.fragment.DialogFragmentNavigator.onRestoreState(DialogFragmentNavigator.java:6)
    at androidx.navigation.NavController.setGraph(NavController.java:13)
    at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:22)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:5)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:23)
    at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:42)
    at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:2)
    at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:1)
    at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:1)
    at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:22)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
    at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
    at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
    at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:26)
    at android.app.Activity.performCreate(Activity.java:6942)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
    at android.app.ActivityThread.-wrap14(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class fragment
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
    at android.app.ActivityThread.-wrap14(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410
```

**Comment by Amejia481** [comment]
Low volume.
