### ISSUE TITLE
Crash in [@ NumberFormatException: For input string: "null"]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#15398]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9601500/

Similar to #14024

```
NumberFormatException: For input string: "null"
    at java.lang.Long.parseLong(Long.java:594)
    at java.lang.Long.parseLong(Long.java:636)
    at org.mozilla.fenix.library.downloads.viewholders.DownloadsListItemViewHolder.bind(DownloadsListItemViewHolder.kt:3)
    at org.mozilla.fenix.library.downloads.DownloadAdapter.onBindViewHolder(DownloadAdapter.kt:3)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
...
(68 additional frame(s) were not displayed)

For input string: "null"
```

**Comment by Amejia481** [comment]
cc @kglazko

**Comment by Amejia481** [comment]
Also in nightly https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9553181/?query=is%3Aunresolved

**Comment by Amejia481** [comment]
Closed in favour of https://github.com/mozilla-mobile/fenix/issues/14772
