### ISSUE TITLE
FxaException Crash on Nightly

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15412]
Nightly crashed in the background, don't have any specific STR.
```
mozilla.appservices.fxaclient.FxaException$Network
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
	at mozilla.appservices.fxaclient.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:9)
	at mozilla.components.service.fxa.FirefoxAccount.getTokenServerEndpointURL(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:13)
	at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```
https://crash-stats.mozilla.org/report/index/b863a75c-40c3-4cf8-ada2-70cdb0200925

cc @grigoryk

**Comment by hwinnemoe** [comment]
See also https://github.com/mozilla-mobile/android-components/issues/8492

**Comment by grigoryk** [comment]
Should be fixed by https://github.com/mozilla-mobile/android-components/pull/8498

**Comment by grigoryk** [comment]
Sentry issue: [FIREFOX-NIGHTLY-6AA](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8905012/?referrer=github_plugin)

**Comment by kbrosnan** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/issues/8492
