### ISSUE TITLE
[Bug] Crash in SyncLoginsPreferenceView CalledFromWrongThreadException

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/fenix#15428]
New but low volume crash in SyncLoginsPreferenceView https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659547/?query=is%3Aunresolved%20CalledFromWrongThreadException

```
android.view.CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8038)
    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1279)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at android.view.View.requestLayout(View.java:23120)
    at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:2)
    at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:4)
    at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:3)
    at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:2)
    at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:3)
    at androidx.preference.PreferenceGroupAdapter.onPreferenceChange(PreferenceGroupAdapter.java:2)
    at androidx.preference.Preference.notifyChanged(Preference.java:2)
    at androidx.preference.Preference.setSummary(Preference.java:4)
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:4)
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.access$updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:1)
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView$1.onAuthenticated(SyncLoginsPreferenceView.kt:1)
    at mozilla.components.service.fxa.manager.FxaAccountManager$accountStateSideEffects$6.invoke(FxaAccountManager.kt:3)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
    at mozilla.components.service.fxa.manager.FxaAccountManager.notifyObservers
    at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:10)
    at mozilla.components.service.fxa.manager.FxaAccountManager$processQueue$2.invokeSuspend(FxaAccountManager.kt:41)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by s-ankur** [comment]
Dupe into https://github.com/mozilla-mobile/fenix/issues/15432?

**Comment by grigoryk** [comment]
Yup, fixed by https://github.com/mozilla-mobile/fenix/commit/3aef8ae58f2c9c9d6fdbe8b7ce54f8f958028062
