### ISSUE TITLE
CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15432]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659547/?referrer=github_plugin

```
CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:4)
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView.access$updateSyncPreferenceStatus(SyncLoginsPreferenceView.kt:1)
    at org.mozilla.fenix.settings.logins.SyncLoginsPreferenceView$1.onAuthenticated(SyncLoginsPreferenceView.kt:1)
...
(28 additional frame(s) were not displayed)

Only the original thread that created a view hierarchy can touch its views.
```

**Comment by s-ankur** [comment]
@grigoryk can you also close #15428
