### ISSUE TITLE
IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 777 ("DefaultDispatcher-worker-4")

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15436]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9650035/?referrer=github_plugin

```
IllegalThreadStateException: Expected thread 2 ("main"), but running on thread 777 ("DefaultDispatcher-worker-4")
    at org.mozilla.fenix.browser.BaseBrowserFragment.initializeEngineView(BaseBrowserFragment.kt:5)
    at org.mozilla.fenix.browser.BaseBrowserFragment.fullScreenChanged(BaseBrowserFragment.kt:30)
    at org.mozilla.fenix.browser.BaseBrowserFragment.access$fullScreenChanged(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$20.onSessionSelected(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.HomeActivity$onResume$2.invokeSuspend(HomeActivity.kt:19)
...
(18 additional frame(s) were not displayed)

Expected thread 2 ("main"), but running on thread 777 ("DefaultDispatcher-worker-4")
```

**Comment by grigoryk** [comment]
From the stacktrace, the root cause here is that in HomeActivity@onResume we're removing tabs on a background thread, which will end up triggering a session switch and bunch of "must be on a UI thread" work (e.g. `setDynamicToolbarMaxHeight`)

Introduced by https://github.com/mozilla-mobile/fenix/pull/13886

**Comment by grigoryk** [comment]
cc @ekager

**Comment by grigoryk** [comment]
Sentry issue: [FIREFOX-NIGHTLY-7Z7](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9649253/?referrer=github_plugin)
