### ISSUE TITLE
IllegalStateException: Fragment BrowserFragment{8f69ba3} (9e1dee6f-f84d-417b-b6d9-910011930473)} did not return a View f...

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15580]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9505093/?referrer=github_plugin

```
IllegalStateException: Fragment BrowserFragment{8f69ba3} (9e1dee6f-f84d-417b-b6d9-910011930473)} did not return a View from onCreateView() or this was called before onCreateView().
    at org.mozilla.fenix.browser.BaseBrowserFragment.fullScreenChanged(BaseBrowserFragment.kt:3)
    at org.mozilla.fenix.browser.BaseBrowserFragment.access$fullScreenChanged(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$3$16.invoke(BaseBrowserFragment.kt:3)
...
(16 additional frame(s) were not displayed)

Fragment BrowserFragment{8f69ba3} (9e1dee6f-f84d-417b-b6d9-910011930473)} did not return a View from onCreateView() or this was called before onCreateView().
```

**Comment by grigoryk** [comment]
This was shipped in 81.1.1 - https://sentry.prod.mozaws.net/operations/firefox/issues/9617962/?query=is%3Aunresolved%20IllegalStateException - steady volume of daily crashes.
