### ISSUE TITLE
[Bug] Crash on rotation: Failed to initialize GeckoRuntime from onConfigurationChanged (debug builds only)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15751]
## Steps to reproduce
- Create debug build
- Load a page
- Rotate the phone

### Expected behavior
No crash.

### Actual behavior
Crash.

### Device information

* Android device: P2
* Fenix version: master 1cc2ecdc7

---

Trace:
> 2020-10-07 09:53:28.824 30159-30159/org.mozilla.fenix.debug E/ExceptionHandler: Uncaught exception handled: 
    java.lang.RuntimeException: GeckoRuntime is shutting down
        at mozilla.components.browser.engine.gecko.GeckoEngine$2.onShutdown(GeckoEngine.kt:105)
        at org.mozilla.geckoview.GeckoRuntime$1.handleMessage(GeckoRuntime.java:254)
        at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:301)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Before this, I saw (but perhaps unrelated):
> 2020-10-07 09:53:23.533 30185-30228/org.mozilla.fenix.debug E/GeckoConsole: [JavaScript Error: "TypeError: can't access property "sendAsyncMessage", this._manager.messageManager is null" {file: "chrome://geckoview/content/geckoview.js" line: 512}]

---

I cannot reproduce if I comment out the profiler marker line: https://github.com/mozilla-mobile/fenix/blob/1cc2ecdc7ce0c52509f5cc7f2b9450a139cbcd09/app/src/main/java/org/mozilla/fenix/StrictModeManager.kt#L130

I'm guessing what is happening is that gecko is unavailable, or just throws an exception, if accessed during configuration change.

**Comment by mcomella** [comment]
I can reproduce the error if I comment out the profiler and add:
```
android.util.Log.e("lol", "${components.core.engine.version.major}")
```

To the `FenixApplication.onConfigurationChanged` method. I think this is an ac or GV bug so I'll try to ask about it over there.
