### ISSUE TITLE
[Bug] Unable to run unit tests in AS: org.junit.AssumptionViolatedException: Robolectric doesn't support legacy mode after P

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#15752]
## Steps to reproduce
- Open `IntentReceiverActivityTest`
- Run tests in AS

### Expected behavior
Tests run

### Actual behavior
Tests are ignored.

Trace:
> org.junit.AssumptionViolatedException: Robolectric doesn't support legacy mode after P
> at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:258)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:63)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:215)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:96)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

Also:
> [Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.

But I think this is unrelated.

### Device information

* Android device: N/A
* Fenix version: master 1cc2ecdc7ce0c52509f5cc7f2b9450a139cbcd09

---

Workaround is to run unit tests via command line:
```
./gradlew testdebugunittest
./gradlew testdebugunittest --tests "*IntentReceiverActivity*"
```

**Comment by mcomella** [comment]
This is a big problem because I do not know how to run the debugger on unit tests now.

**Comment by mcomella** [comment]
I can't reproduce anymore – must have been a local intermittent.
