### ISSUE TITLE
IllegalStateException: Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#15812]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9752170/?referrer=github_plugin

```
IllegalStateException: Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
    at org.mozilla.fenix.settings.PairFragment$onViewCreated$2.invoke(PairFragment.kt:3)
...
(7 additional frame(s) were not displayed)

Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8032)

**Comment by eliserichards** [comment]
```
java.lang.IllegalStateException: Fragment PairFragment{76fc44d} (c18ac462-998c-4c18-a3bb-2c9f6b9e6b7f)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
    at org.mozilla.fenix.settings.PairFragment$onViewCreated$2.invoke(PairFragment.kt:3)
    at mozilla.components.feature.qr.QrFeature$scanCompleteListener$1.onScanComplete(QrFeature.kt:3)
    at mozilla.components.feature.qr.QrFragment$scanCompleteListener$1$onScanComplete$$inlined$apply$lambda$1.run(QrFragment.kt:5)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6776)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```

**Comment by Amejia481** [comment]
Same issue but a bit different stack trace

Sentry nightly 
https://sentry.io/organizations/mozilla/issues/3258708974/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&sort=freq&statsPeriod=14d

```
java.lang.IllegalStateException: Fragment PairFragment{795ef40} (7ae9f15d-b071-409c-a3dd-0d905ed9f659) not associated with a fragment manager.
    at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
    at androidx.navigation.fragment.NavHostFragment.findNavController(NavHostFragment.java:3)
    at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:1)
    at org.mozilla.fenix.settings.PairFragment$onViewCreated$1.invoke(PairFragment.kt:4)
    at mozilla.components.feature.qr.QrFeature$scanCompleteListener$1.onScanComplete(QrFeature.kt:5)
    at androidx.room.QueryInterceptorDatabase$$ExternalSyntheticLambda2.run
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6740)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
