### ISSUE TITLE
Intermittent UI test failure - verifyAboutFirefoxPreview

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#15847]
### Firebase Test Run:
Flaky test, 1/2 tries:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6129090638534714506/executions/bs.d115dbf271ae48bd/testcases/2/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/menuButton)
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) gr=CENTER sim={adjust=pan} ty=APPLICATION fmt=TRANSPARENT wanim=0x7f140008
fl=DIM_BEHIND LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@26b05f9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-->ViewStub{id=16908682, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@af9993e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-->FrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1722, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ceb539f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=1}
|
+--->CoordinatorLayout{id=2131362909, res-name=tabLayout, visibility=VISIBLE, width=1080, height=1722, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@fa73cec, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---->ExtendedFloatingActionButton{id=2131362610, res-name=new_tab_button, desc=Add tab, visibility=VISIBLE, width=176, height=176, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@94d08b5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=860.0, y=1502.0, text=Private, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---->ConstraintLayout{id=2131362927, res-name=tab_wrapper, visibility=VISIBLE, width=1080, height=1722, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@83b8abb, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=607.0, child-count=6}
|
+----->View{id=2131362358, res-name=handle, visibility=VISIBLE, width=108, height=8, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@d413bd8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=486.0, y=22.0}
|
+----->ConstraintLayout{id=2131362396, res-name=infoBanner, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@6127b31, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=0}
|
+----->AppCompatTextView{id=2131362922, res-name=tab_tray_empty_view, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@4d9216, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Your open tabs will be shown here., input-type=0, ime-target=false, has-links=false}
|
+----->ConstraintLayout{id=2131362987, res-name=topBar, visibility=VISIBLE, width=1080, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@3129633, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=30.0, child-count=6}
|
+------>AppCompatImageButton{id=2131362310, res-name=exit_multi_select, desc=Exit multiselect mode, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@71fadf0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------>AppCompatTextView{id=2131362599, res-name=multiselect_title, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@71c5f69, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}
|
+------>AppCompatTextView{id=2131362146, res-name=collect_multi_select, desc=Save selected tabs to collection, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@5ccdee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Save, input-type=0, ime-target=false, has-links=false}
|
+------>TabLayout{id=2131362916, res-name=tab_layout, visibility=VISIBLE, width=540, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@256628f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+------->SlidingTabIndicator{id=-1, visibility=VISIBLE, width=540, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a69b91c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-------->TabView{id=-1, desc=1 open tab. Tap to switch tabs., visibility=VISIBLE, width=270, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=true, layout-params=android.widget.LinearLayout$LayoutParams@a6098ab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+--------->AppCompatImageView{id=-1, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=true, layout-params=android.widget.LinearLayout$LayoutParams@8e74b08, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+--------->AppCompatTextView{id=-1, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=true, layout-params=android.widget.LinearLayout$LayoutParams@38792a1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}
|
+--------->FrameLayout{id=2131362176, res-name=counter_root, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=true, layout-params=android.widget.LinearLayout$LayoutParams@8ecacc6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=102.0, y=77.0, child-count=2}
|
+---------->AppCompatImageView{id=2131362175, res-name=counter_box, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=true, layout-params=android.widget.FrameLayout$LayoutParams@8e1487, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---------->AppCompatTextView{id=2131362177, res-name=counter_text, visibility=VISIBLE, width=19, height=44, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=true, layout-params=android.widget.FrameLayout$LayoutParams@e2a0fb4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=23.0, y=11.0, text=1, input-type=0, ime-target=false, has-links=false}
|
+-------->TabView{id=-1, desc=Private tabs, visibility=VISIBLE, width=270, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@876cf52, tag=null, root-is-layout-requested=false, has-input-connection=false, x=270.0, y=0.0, child-count=2}
|
+--------->AppCompatImageView{id=-1, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@92d7223, tag=null, root-is-layout-requested=false, has-input-connection=false, x=102.0, y=77.0}
|
+--------->AppCompatTextView{id=-1, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b327320, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}
|
+------>AppCompatImageButton{id=2131362923, res-name=tab_tray_new_tab, desc=Add tab, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e4ef4d9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------>AppCompatImageButton{id=2131362924, res-name=tab_tray_overflow, desc=Open tabs menu, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f0e8e9e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=948.0, y=45.0}
|
+----->View{id=2131362252, res-name=divider, visibility=VISIBLE, width=1080, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@4db0d7f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=251.0}
|
+----->RecyclerView{id=2131362929, res-name=tabsTray, visibility=VISIBLE, width=1080, height=1468, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e9ba14c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=254.0, child-count=2}
|
+------>MaterialButton{id=-1, visibility=VISIBLE, width=1036, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@310595, tag=null, root-is-layout-requested=false, has-input-connection=false, x=22.0, y=265.0, text=Save to collection, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+------>ConstraintLayout{id=2131362915, res-name=tab_item, visibility=VISIBLE, width=1080, height=243, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@79d029b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}
|
+------->AppCompatImageButton{id=2131362674, res-name=play_pause_button, desc=Pause, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=false, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@3878638, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------->CardView{id=2131362536, res-name=mozac_browser_tabstray_card, visibility=VISIBLE, width=254, height=190, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@c9fd376, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=22.0, child-count=3}
|
+-------->AppCompatImageView{id=2131362209, res-name=default_tab_thumbnail, visibility=VISIBLE, width=254, height=190, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5bf2d77, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-------->TabThumbnailView{id=2131362540, res-name=mozac_browser_tabstray_thumbnail, desc=Open Tab, visibility=VISIBLE, width=254, height=190, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@34acde4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-------->FrameLayout{id=2131362810, res-name=selected_mask, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@fadb102, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--------->AppCompatImageView{id=2131362122, res-name=checkmark, desc=Selected, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@26f2a13, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------->AppCompatTextView{id=2131362541, res-name=mozac_browser_tabstray_title, visibility=VISIBLE, width=650, height=120, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@5d8e450, tag=null, root-is-layout-requested=false, has-input-connection=false, x=298.0, y=0.0, text=https://support.mozilla.org/en-US/products/mobile?as=u&utm_source=inproduct, input-type=0, ime-target=false, has-links=false}
|
+------->AppCompatTextView{id=2131362542, res-name=mozac_browser_tabstray_url, visibility=VISIBLE, width=650, height=53, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@8c9c649, tag=null, root-is-layout-requested=false, has-input-connection=false, x=298.0, y=120.0, text=support.mozilla.org, input-type=0, ime-target=false, has-links=false}
|
+------->AppCompatImageButton{id=2131362537, res-name=mozac_browser_tabstray_close, desc=Close tab , visibility=VISIBLE, width=132, height=243, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@dc9db4e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=948.0, y=0.0}
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c18546f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1788.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:368)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.navigateBackToAboutPage(SettingsSubMenuAboutRobot.kt:73)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:83)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:63)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:45)`
### Build: 
10/12/20

**Comment by sv-ohorvath** [comment]
Failed 2/2, on 11/2: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8183125839606248686/executions/bs.6fbe87b199f0075b/testcases/2/test-cases
