### ISSUE TITLE
Application crashes on attempt to proceed with http-login.

### ISSUE THREAD

**Issue by alex-berdnikov** [mozilla-mobile/fenix#15889]
## Steps to reproduce
1. Open https://badssl.com/
2. Find http-login option and click it. 

### Expected behavior
Application doesn't crash.

### Actual behavior
Application crashes

### Device information
Nokia 6.1 2018 
Samsung A01 Android 10

* Android device: Android 10
* Fenix version: 200706

In fact I observe this behavior in all GeckoView-based browsers and initially I discovered this bug working with GeckoView in the app I work on in my company. Here's a stacktrace from my logcat:

2020-10-14 14:25:17.674 18416-18416/com.app.downloadmanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.downloadmanager, PID: 18416
    java.lang.ClassCastException: org.mozilla.gecko.util.GeckoBundle cannot be cast to java.lang.String
        at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:343)
        at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:354)
        at org.mozilla.geckoview.Autofill$Node$Builder.<init>(Autofill.java:789)
        at org.mozilla.geckoview.Autofill$Support.addNode(Autofill.java:1099)
        at org.mozilla.geckoview.Autofill$Support.handleMessage(Autofill.java:994)
        at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:301)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7857)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by liuche** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1671278

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
