### ISSUE TITLE
[Bug] java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.fenix/.downloads.DownloadService (has extras) }

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#15927]
This is our top crash on nightly 10/15.

https://crash-stats.mozilla.org/report/index/a1820c4d-e0af-4dc0-9ed5-b919b0201015

```
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$$special$$inlined$CoroutineExceptionHandler$1$lambda$1.run(Store.kt:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	... 3 more
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.mozilla.fenix/.downloads.DownloadService (has extras) }: app is in background uid UidRecord{cb8f2d0 u0a204 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1631)
	at android.app.ContextImpl.startService(ContextImpl.java:1586)
	at android.content.ContextWrapper.startService(ContextWrapper.java:669)
	at mozilla.components.feature.downloads.DownloadMiddleware.sendDownloadIntent(DownloadMiddleware.kt:4)
	at mozilla.components.feature.downloads.DownloadMiddleware.invoke(DownloadMiddleware.kt:17)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.feature.media.middleware.MediaMiddleware.invoke(MediaMiddleware.kt:39)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:4)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$$inlined$forEach$lambda$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

**Comment by liuche** [comment]
Looks like it could be similar to #15269, maybe a background crash?

**Comment by Amejia481** [comment]
Do we have the STR?

**Comment by Amejia481** [comment]
Do we have some reports on sentry?

**Comment by liuche** [comment]
Good question! I took a look on Sentry, and the closest I could find (by comparing the redacted stacktrace from crash-stats) is this [issue](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.RuntimeException%3A%20at%20com.android.internal.os.RuntimeInit%24MethodAndArgsCaller.run%28RuntimeInit.java%29#summary).

If I open up the [crash-stats summary](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.RuntimeException%3A%20at%20com.android.internal.os.RuntimeInit%24MethodAndArgsCaller.run%28RuntimeInit.java%29#summary) for this issue, it looks mostly 81, some Nightly, no 82 - so maybe it is actually already fixed.

**Comment by Amejia481** [comment]
I remembered we put a patch on ac [58.0.0](https://github.com/mozilla-mobile/android-components/commit/21332cf60a569d8cdc0334b9c4d32124b98b37db) for a very similar issue ([same stack trace](https://github.com/mozilla-mobile/fenix/issues/14852)). I'm not able to find the crash on Sentry, It looks like is already fixed. Do you think that we should keep investigating?

**Comment by liuche** [comment]
Thank you for the links! I'll close this one since I'm not seeing it on 82 anymore. Sorry for the bother 😅

**Comment by Amejia481** [comment]
> Thank you for the links! I'll close this one since I'm not seeing it on 82 anymore. Sorry for the bother 😅

Not a problem at all :)
