### ISSUE TITLE
[Crash] ConcurrentModificationException org.mozilla.fenix.wifi.WifiConnectionMonitor

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#15934]
Followup to #14680 

The main `ObserverRegistry` crash was resolved (see [Sebastian's comment](https://github.com/mozilla-mobile/fenix/issues/14680#issuecomment-688686650)), but there is another related crash that we are seeing:

```
java.util.ConcurrentModificationException: null
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
    at org.mozilla.fenix.wifi.WifiConnectionMonitor$frameworkListener$1.onAvailable(WifiConnectionMonitor.kt:2)
    at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3322)
    at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3607)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.os.HandlerThread.run(HandlerThread.java:67)
```

Sentry: https://sentry.prod.mozaws.net/share/issue/4234e7770c9f4d05abd2c60f63aafb3c/

**Comment by AndiAJ** [comment]
Managed to reproduce it on **`82.0.0-beta.6`** using a OnePlus A3 (Android 6.0.1) on https://www.walkinto.in/tour/WyKhAFf0iXZJgF2CKzAj7

8346bcbb-5448-409b-97bd-f275bb46894e
java.util.ConcurrentModificationException
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=bba951eef99b4260a26a1e7cce002b7a
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=04288cd1909148ef9b94c76b3da4043d
* Socorro: https://crash-stats.mozilla.org/report/index/bp-cddcf565-5d1b-4795-b9b0-9bc800201016
* Socorro: https://crash-stats.mozilla.org/report/index/bp-0b955d98-a872-4cfa-bd48-2e1900201016
----
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
at org.mozilla.fenix.wifi.WifiConnectionMonitor$frameworkListener$1.onAvailable(WifiConnectionMonitor.kt:2)
at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2345)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:152)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by liuche** [comment]
Looking at crash-stats for this (learned from kevin!), this looks pretty low incidence. However, if these are reliable steps to reproduce, this could be worthwhile to fix.

https://bugzilla.mozilla.org/show_bug.cgi?id=1644043

**Comment by AndiAJ** [comment]
Managed to reproduce it on **`Firefox 82.1.2`** using a OnePlus A3 (Android 6.0.1) on https://www.cbssports.com/

947c27bc-f053-4f8c-8ac4-df595242a581
java.util.ConcurrentModificationException
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=8ff2eafb63e9413b82c55234bd9a70e0
* Socorro: https://crash-stats.mozilla.org/report/index/bp-abfc4259-9e8d-4a2a-a74d-8a4670201030
----
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
at org.mozilla.fenix.wifi.WifiConnectionMonitor$frameworkListener$1.onAvailable(WifiConnectionMonitor.kt:2)
at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2345)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:152)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Amejia481** [comment]
The fix is should be in nightly now, QA team could please help us to verify? :)

**Comment by AndiAJ** [comment]
Managed to reproduce it on **`83.0.0-beta.4`** using a OnePlus A3 (Android 6.0.1) on https://www.walkinto.in/tour/WyKhAFf0iXZJgF2CKzAj7

ac633eb7-bdb4-438c-941e-100596597663
java.util.ConcurrentModificationException
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=af3bf350a66146eb8692b95d19d89909
* Socorro: https://crash-stats.mozilla.org/report/index/bp-d4ddc61c-a17e-4438-a50b-7ae720201109
----
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
at org.mozilla.fenix.wifi.WifiConnectionMonitor$frameworkListener$1.onAvailable(WifiConnectionMonitor.kt:2)
at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2345)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:152)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Amejia481** [comment]
> Managed to reproduce it on **`83.0.0-beta.4`** using a OnePlus A3 (Android 6.0.1) on https://www.walkinto.in/tour/WyKhAFf0iXZJgF2CKzAj7
> 
> ac633eb7-bdb4-438c-941e-100596597663
> java.util.ConcurrentModificationException
> 
>     * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=af3bf350a66146eb8692b95d19d89909
> 
>     * Socorro: https://crash-stats.mozilla.org/report/index/bp-d4ddc61c-a17e-4438-a50b-7ae720201109
> 
> 
> java.util.ConcurrentModificationException
> at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
> at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
> at org.mozilla.fenix.wifi.WifiConnectionMonitor$frameworkListener$1.onAvailable(WifiConnectionMonitor.kt:2)
> at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:2345)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:152)
> at android.os.HandlerThread.run(HandlerThread.java:61)

For the fix to be on **`83.0.0-beta.4`** we need to uplift the patch,  before it, I just want to confirm @AndiAJ  the issue is not reproducible in nightly?

**Comment by AndiAJ** [comment]
Hi @Amejia481 , **verified as fixed** on the **`latest Nightly Build 201110`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

Checked 10 times each of the following websites on each of the above mentioned devices:
• https://www.cbssports.com/
• https://videojs.github.io/autoplay-tests/plain/attr/autoplay.html
• https://www.walkinto.in/tour/WyKhAFf0iXZJgF2CKzAj7

✔️ **No crash encountered in 90 attempts** 🥳 

**I'll keep an eye on this matter in the upcoming Beta | RC builds.** 👀

**Comment by Amejia481** [comment]
Thanks @AndiAJ!
