### ISSUE TITLE
[Bug] Crash when changing language and going to Turn on Sync

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/fenix#16016]
## Steps to reproduce
1. Launch Fenix and go to Settings - Language;
2. Change the language to Tajik;
3. Tap the back arrow to return to Settings;
4. Tap Turn on Sync;
### Expected behavior
The sign in page in displayed.
### Actual behavior
The app crashes: https://crash-stats.mozilla.org/report/index/742fd630-44b4-468b-a9e1-130870201019#tab-details
`java.lang.IndexOutOfBoundsException: setSpan (-1 ... 9) starts before 0
at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:497)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:197)
at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:184)
at android.text.SpannableString.setSpan(SpannableString.java:60)
at androidx.core.app.AppOpsManagerCompat.addUnderline(AppOpsManagerCompat.java:4)
at org.mozilla.fenix.settings.account.TurnOnSyncFragment.onCreateView(TurnOnSyncFragment.kt:17)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

### Notes
This is also reproducible when changing to other language: Francais, Spanish, Albanian, Indonesia. 
I had noticed that this is reproducible when the screen goes dark for 1 second after changing the language.

![20201019_102753](https://user-images.githubusercontent.com/48799384/96414531-ea454500-11f5-11eb-8dc0-0ce01375d0fc.gif)

### Device information

* Android device: Samsung Galaxy Tab S6 (Android 10), Pixel 2 (Android 9), Pixel 3 (Android 11)
* Fenix version: Release 82.1.0-rc.2, Release 82.1.0-rc.1, Beta 82.0.0-beta.6, Beta 82.0.0-beta.5
Not reproducible on Beta 82.0.0-beta.4 and Nightly 10/19.

**Comment by mcarare** [comment]
@liuche I am not sure if this commit: https://github.com/mozilla-mobile/fenix/pull/15338/commits/a650586788687e537621ebf39715575ab263173c has made it 82.1.0-rc.2.
The problem might be that the uplifted strings (`sign_in_create_account_text`)are in a different format than the code before 82.1.0-rc.2 expects.

**Comment by ekager** [comment]
This is the STR for #16063

**Comment by ebalazs-sv** [comment]
I will close this as duplicate to https://github.com/mozilla-mobile/fenix/issues/16063.
