### ISSUE TITLE
RuntimeExceptionandroid.app.ActivityThread in handleServiceArgs

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16034]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8619785/

```

Unable to start service org.mozilla.fenix.downloads.DownloadService@b790f17 with Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat=https://redreader.org/... flg=0x10000000 pkg=org.mozilla.fenix cmp=org.mozilla.fenix/.HomeActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }: java.lang.IllegalArgumentException: Receiver not registered: mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@7ee9f04

java.lang.IllegalArgumentException: Receiver not registered: mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@7ee9f04
    at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
    at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1376)
    at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.unregisterNotificationActionsReceiver$feature_downloads_release(AbstractFetchDownloadService.kt:1)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.clearAllDownloadsNotificationsAndJobs$feature_downloads_release(AbstractFetchDownloadService.kt:11)
    at mozilla.components.feature.downloads.AbstractFetchDownloadService.onTaskRemoved(AbstractFetchDownloadService.kt:1)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3690)
    at android.app.ActivityThread.-wrap23(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

java.lang.RuntimeException: Unable to start service org.mozilla.fenix.downloads.DownloadService@b790f17 with Intent { act=android.intent.action.VIEW cat=[mozilla.components.pwa.category.SHORTCUT] dat=https://redreader.org/... flg=0x10000000 pkg=org.mozilla.fenix cmp=org.mozilla.fenix/.HomeActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }: java.lang.IllegalArgumentException: Receiver not registered: mozilla.components.feature.downloads.AbstractFetchDownloadService$broadcastReceiver$2$1@7ee9f04
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
    at android.app.ActivityThread.-wrap23(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by Amejia481** [comment]
I think we can close this issue as we are not seeing more new reports
