### ISSUE TITLE
[Bug] Crash on deleting bookmarks folder

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16096]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
I was deleting a bookmarks folder while not signed in to synce
```
670e6271-4517-4703-9cca-fb9cfe07baf3
java.lang.NullPointerException
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=055f8e7b94124a0890cbd93954f69cc6
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-4029d057-af99-47e1-931d-94b710201021
----
java.lang.NullPointerException
	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.refreshBookmarks(BookmarkFragment.kt:8)
	at org.mozilla.fenix.library.bookmarks.BookmarkFragment$refreshBookmarks$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### Device information

* Android device: Asus Zenfone
* Fenix version: Nightly

**Comment by sv-ohorvath** [comment]
I reproduced this crash on 90.0.0-beta1 while deleting bookmarks folders as well:
412139c4-735f-41ab-99ee-e7717c584356
java.lang.NullPointerException
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=68246aec3b9c478f80a36e538118aed6
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-15bea101-c37a-4d94-a3d3-d4ac10210602
----
`java.lang.NullPointerException
	at org.mozilla.fenix.library.bookmarks.BookmarkFragment.refreshBookmarks(BookmarkFragment.kt:8)
	at org.mozilla.fenix.library.bookmarks.BookmarkFragment$refreshBookmarks$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`
