### ISSUE TITLE
[Bug] StrictEnhancedTrackingProtection tests fail with A-C, GV update (master not affected): no ETP pop up displayed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#16113]
All tests in [StrictEnhancedTrackingProtectionTest]((https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/java/org/mozilla/fenix/ui/StrictEnhancedTrackingProtectionTest.kt) ) have failed 2/2 in Firebase not intermittent.

## Steps to reproduce
Go for example to bb.com. The tests use [trackingPage.html](https://github.com/mozilla-mobile/fenix/blob/master/app/src/androidTest/assets/pages/trackingPage.html)

### Expected behavior
There is a first time ETP pop-up message in the lower left corner, right above the ETP shield is displayed.
<img width="142" alt="Captura de pantalla 2020-10-22 a las 14 02 08" src="https://user-images.githubusercontent.com/1897507/96869112-554d8080-146f-11eb-8e47-63aebe20367f.png">

### Actual behavior
The pop up is not shown
<img width="142" alt="Captura de pantalla 2020-10-22 a las 13 31 44" src="https://user-images.githubusercontent.com/1897507/96867420-f981f800-146c-11eb-9c78-8ebad7c6931f.png">

### Device information
* Android device: Pixel 3, API28
* Fenix version: release v83.0.0 branch and [PR](https://github.com/mozilla-mobile/fenix/pull/16094) to update A-C to 64.0.20201020190149
 
**Tests affected:**
testStrictVisitSheetDetails
testStrictVisitProtectionSheet
testStrictVisitDisableExceptionToggle
testStrictVisitDisable
testStrictVisitContentNotification

**Stacktrace**
It does not give much info since the error is related to the element, the pop up, not being shown:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:91)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:1)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot.verifyEnhancedTrackingProtectionNotice(EnhancedTrackingProtectionRobot.kt:29)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitSheetDetails$3.invoke(StrictEnhancedTrackingProtectionTest.kt:200)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitSheetDetails$3.invoke(StrictEnhancedTrackingProtectionTest.kt:36)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.enhancedTrackingProtection(EnhancedTrackingProtectionRobot.kt:86)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitSheetDetails(StrictEnhancedTrackingProtectionTest.kt:199)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by csadilek** [comment]
This was a regression in GV 84.0.20201021095128, which is fixed in today's GV 84.0.20201022093646. We're currently publishing a new A-C to upgrade. Verified that the tests pass with the version. No change needed in Fenix.
