### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java)]

### ISSUE THREAD

**Issue by J41319** [mozilla-mobile/fenix#16144]
Firefox crashes when downloading and canceling download and starts it again in private window.

## Steps to reproduce

I'm having problems with version 82 of Firefox, since the downloads don't start, I put a file to download and it doesn't download, I cancel and try again the problem persists, so if I open the link in a private window the browser crashes. I managed to reproduce this problem for the time being only on the apkmirror website.

### Expected behavior

The browser should not crash when doing the above process.

### Actual behavior

The browser crashes.

### Device information

* Android device: Xiaomi Mi A3
* Fenix version: 82.1.1 (Build #2015770923)
AC:60.0.5, a1a471ddc
GV:82.0-20201014125134
AS:63.0.0
 
NOTE: If I delete the data from the browser and try to download, they start normally, but later the problem returns. I cannot download from Github too.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/5428872/logcat.txt)
[record-20201023-065209.zip](https://github.com/mozilla-mobile/fenix/files/5428880/record-20201023-065209.zip)

**Comment by kbrosnan** [comment]
```
10-23 06:46:38.751 E/ExceptionHandler(2400): Uncaught exception handled: 
10-23 06:46:38.751 E/ExceptionHandler(2400): java.lang.IllegalStateException: FragmentManager has been destroyed
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:2)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:3)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:5)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at mozilla.components.feature.downloads.DownloadsFeature.showAppDownloaderDialog$feature_downloads_release(DownloadsFeature.kt:5)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at mozilla.components.feature.downloads.DownloadsFeature.processDownload$feature_downloads_release(DownloadsFeature.kt:10)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:4)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:11)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at android.os.Handler.handleCallback(Handler.java:883)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at android.os.Looper.loop(Looper.java:214)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at java.lang.reflect.Method.invoke(Native Method)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-23 06:46:38.751 E/ExceptionHandler(2400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
10-23 06:46:38.752 I/GoogleInputMethodService(2601): GoogleInputMethodService.onStartInput():1858 
10-23 06:46:38.754 I/mozac/CrashReporter(2400): Received crash: UncaughtExceptionCrash(timestamp=1603446398751, throwable=java.lang.IllegalStateException: FragmentManager has been destroyed, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=true, intent=android.intent.action.MAIN, instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=onAttach(), data={instance=20949369, activityInstance=224670007, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=20949369, activityInstance=224670007, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=onStart(), data={instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=onResume(), data={instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:32 GMT-03:00 2020), Breadcrumb(message=recreate(), data={instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onPause(), data={finishing=false, instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onStop(), data={finishing=false, instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onDestroyView(), data={instance=20949369, activityInstance=224670007, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onDetach(), data={instance=20949369, activityInstance=224670007, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onDestroy(), data={finishing=false, instance=224670007}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onCreate(), data={recreated=true, intent=android.intent.action.MAIN, instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onAttach(), data={instance=238586297, activityInstance=230702052, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=238586297, activityInstance=230702052, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onStart(), data={instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=onResume(), data={instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:35 GMT-03:00 2020), Breadcrumb(message=recreate(), data={instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:38 GMT-03:00 2020), Breadcrumb(message=onPause(), data={finishing=false, instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:38 GMT-03:00 2020), Breadcrumb(message=onStop(), data={finishing=false, instance=230702052}, category=HomeActivity, level=INFO, type=DEFAULT, date=Fri Oct 23 06:46:38 GMT-03:00 2020), Breadcrumb(message=onDestroyView(), data={instance=238586297, activityInstance=230702052, activityName=Hom
```


https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A%20at%20androidx.fragment.app.FragmentManager.ensureExecReady%28FragmentManager.java%29

https://sentry.prod.mozaws.net/operations/firefox/issues/9621034/
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9002033/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8921956/

**Comment by Amejia481** [comment]
@J41319  we put a patch in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). I was able to download the file there, would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will work for you too :)

**Comment by Amejia481** [comment]
QA team could you please verify if this issue is fixed on nightly. Thanks in advance!

**Comment by J41319** [comment]
> @J41319 we put a patch in [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix). I was able to download the file there, would you mind trying on [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) to see if it's fixed for you? Hopefully it will work for you too :)

I tested the version nightly and it worked normally, I was able to make downloads, I hope this fix will arrive as soon as possible in the stable version. 😀

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201103`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
