### ISSUE TITLE
[Bug]App hangs and exit without any tip.

### ISSUE THREAD

**Issue by zoumi** [mozilla-mobile/fenix#16172]
## Steps to reproduce
No step. It happens sometimes.
### Device information

* Android device: ?
HuaWei STF-AL00
* Fenix version: ?
 82

Here is logcat:
[fenix.log](https://github.com/mozilla-mobile/fenix/files/5436607/fenix.log)

**Comment by kbrosnan** [comment]
Does this stop happening if you switch keyboard apps?

```
10-26 10:40:19.865  1337  1357 V WindowManager: addWindow: Window{137584f u0 Application Not Responding: org.mozilla.firefox} 
10-26 10:40:20.258 27728 27728 E AndroidRuntime: FATAL EXCEPTION: main
10-26 10:40:20.258 27728 27728 E AndroidRuntime: Process: org.mozilla.firefox, PID: 27728
10-26 10:40:20.258 27728 27728 E AndroidRuntime: java.lang.StackOverflowError: stack size 8MB
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at java.util.concurrent.atomic.AtomicInteger.decrementAndGet(AtomicInteger.java:196)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:1)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:12)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.gecko.util.ThreadUtils.runOnUiThread(ThreadUtils.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable.toggleSoftInput(GeckoEditable.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable.onCreateInputConnection(GeckoEditable.java:12)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.SessionTextInput.onCreateInputConnection(SessionTextInput.java:1)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.onCreateInputConnection(GeckoView.java:2)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at huawei.android.view.inputmethod.HwSecImmHelper.isPasswordInputType(HwSecImmHelper.java:142)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at huawei.android.view.inputmethod.HwSecImmHelper.hideSoftInputFromWindow(HwSecImmHelper.java:65)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1216)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow(InputMethodManager.java:1178)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.SessionTextInput$DefaultDelegate.hideSoftInput(SessionTextInput.java:4)
10-26 10:40:20.258 27728 27728 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoEditable$7.run(GeckoEditable.java:9)
REPEAT TO FILL 50000+ LINES OF LOG
```

**Comment by kbrosnan** [comment]
If you have some time please try the [Nightly build](https://play.google.com/store/apps/details?id=org.mozilla.fenix)

**Comment by makotokato** [comment]
This seems to be huawei only issue.

@zoumi  
What software keyboard do you use?

**Comment by zoumi** [comment]
@makotokato Thanks, I will try another input APP.
If you want to dig out the bug, you can test with this http://www.ucbug.com/shouji/44155.html (my version is 8.2.6.244).

**Comment by zoumi** [comment]
@makotokato I have try another input APP (http://www.xinshuru.com/index.html?p=win). The bug is still there.
I have used firefox 68 for a long time. And it worked fine.

**Comment by zoumi** [comment]
The step to  reproduce:
1,Open bing.com
2.Input something in the search box
3,Click the button to start searching  --->fenix hangs

**Comment by kbrosnan** [comment]
Going to move this to Bugzilla as that is were we track IME issues.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673681

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by zoumi** [comment]
Thanks, follow the bugzilla link, I found that it's HuaWei's secure input cause this problem. After disabling the  secure input feature, fenix work well now.
The secure input feature is default ON. We can disable it by this way:
https://jingyan.baidu.com/article/2a138328dc8353074a134f1d.html

It's will be nice if fenix can tip HuaWei phone users.
