### ISSUE TITLE
[Bug] FATAL: Blank screen on launch, unable to do anything

### ISSUE THREAD

**Issue by julKali** [mozilla-mobile/fenix#16297]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

From one app launch to the next, Fenix suddenly stopped showing anything except a blank screen (see screenshot attached).
I updated to the most recent version, but it still persists.
The only thing I can do is drag to refresh which leads to the spinner being displayed as usual but spinning forever. In the attached logcat file, this moment is marked as `--------- beginning of system`.

![Screenshot_20201031-121053](https://user-images.githubusercontent.com/17690423/97777735-7189a580-1b72-11eb-9fa0-7b0fd8b11c7f.png)

[fenix_logcat.txt](https://github.com/mozilla-mobile/fenix/files/5468943/fenix_logcat.txt)

### Device information

* Android device: Nokia TA-1012 running Android 9
* Fenix version: Cannot tell from the app but according to Play Store: Nightly 201028 17:00

**Comment by kbrosnan** [comment]
Do not see anything when I looked at logcat, if you filtered it then there may be missing data.

**Comment by kbrosnan** [comment]
Agi pointed out that I missed 

```
10-31 12:13:44.936 16810 16810 I ResourcesCompat: Failed to retrieve rebase() method
10-31 12:13:44.936 16810 16810 I ResourcesCompat: java.lang.NoSuchMethodException: rebase []
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at java.lang.Class.getMethod(Class.java:2068)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at java.lang.Class.getDeclaredMethod(Class.java:2047)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at androidx.core.content.res.ResourcesCompat$ThemeCompat$ImplApi23.rebase(ResourcesCompat.java:3)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.rebase1(ColorStateListInflaterCompat.java:3)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at androidx.appcompat.app.AppCompatDelegateImpl.attachBaseContext2(AppCompatDelegateImpl.java:77)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at androidx.appcompat.app.AppCompatActivity.attachBaseContext(AppCompatActivity.java:1)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at mozilla.components.support.locale.LocaleAwareAppCompatActivity.attachBaseContext(LocaleAwareAppCompatActivity.kt:2)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at org.mozilla.fenix.HomeActivity.access$attachBaseContext$s-594849490(HomeActivity.kt:1)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at org.mozilla.fenix.HomeActivity$attachBaseContext$1.invoke(HomeActivity.kt:1)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at org.mozilla.fenix.StrictModeManager.resetAfter(StrictModeManager.kt:8)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at org.mozilla.fenix.HomeActivity.attachBaseContext(HomeActivity.kt:1)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.Activity.attach(Activity.java:7051)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2888)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.os.Looper.loop(Looper.java:198)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at android.app.ActivityThread.main(ActivityThread.java:6729)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-31 12:13:44.936 16810 16810 I ResourcesCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by kbrosnan** [comment]
Placing this on the AC top 10 to see if this is an addressable issue.

**Comment by jonalmeida** [comment]
This looks related to https://github.com/mozilla-mobile/fenix/issues/16775, we should re-test or observe the crash rate after the fix there lands.
