### ISSUE TITLE
[Bug] Crash when opening top site in private tab

### ISSUE THREAD

**Issue by mobd** [mozilla-mobile/fenix#16442]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
- Restart the app
- Long press a pinned site and open it in a private tab.

### Actual behavior
App crashes:

e997da13-e7f8-4cbb-a704-c2a13ea1024b
java.lang.IllegalStateException: Fragment BrowserFragment{7abb8c2} (6d797f21-8e7e-4175-b9a9-02f7864b4f6e)} not attached to a context.
----
java.lang.IllegalStateException: Fragment BrowserFragment{7abb8c2} (6d797f21-8e7e-4175-b9a9-02f7864b4f6e)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.assignSitePermissionsRules(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.access$assignSitePermissionsRules(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$18.invoke(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.utils.Settings$setSitePermissionSettingListener$1.invoke(Settings.kt:3)
	at org.mozilla.fenix.settings.OnSharedPreferenceChangeListener.onSharedPreferenceChanged(OnSharedPreferenceChangeListener.kt:1)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:612)
	at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0$SharedPreferencesImpl$EditorImpl(SharedPreferencesImpl.java:618)
	at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

### Device information

* Android device: Huawei Nova 6 (Android 10)
* Fenix version: Nightly 201106 17:01 (Build #2015774091)

**Comment by sflorean** [comment]
@mobd Thanks for the report! Wasn't able to reproduce it on Nightly 11/10. Do you have any other steps, website link?

**Comment by mobd** [comment]
@sflorean hi, I just noticed it only happens if it's the first thing you do after opening the browser, I'll update the report. It happens with every site I've tried so I doubt that matters

**Comment by mobd** [comment]
@sflorean I found another way to trigger the same crash:
- In settings, go to private browsing, set "open links in a private tab" to true
- Close the browser
- In any other app, select some text, click share, and choose firefox from the android share menu

When I first tried this, it searched for the selected text in a regular tab instead of a private one and didn't crash. But after closing the app again and doing the same thing it crashes everytime, so you may need to restart the app several times to get it to respect the changed settings

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 14/12** with **Google Pixel 4 XL (11).**
Note that I shared more than 15 tabs and I didn't encounter any crashes.
Also, I tried to share words from specific webpages, and no crash there.
