### ISSUE TITLE
[Bug] Going to downloads in the firefox stable crashes the app

### ISSUE THREAD

**Issue by Aryvd** [mozilla-mobile/fenix#16470]
### Steps to reproduce
Clicking on three dot menu -> Downloads 

### Expected behavior
Downloads menu opens with a list of all downloads and the browser doesn't crash

### Actual behavior
Downloads menu shows blank for a second before crashing

### Device information

* Android device: Redmi Note 7S 3GB MIUI Global 11.0.5
* Fenix version: 82.1.3 stable

Note : MIUI optimization is disabled 

### Crash report sent by MIUI

java.lang.NumberFormatException: For input string: "null"
	at java.lang.Long.parseLong(Long.java:594)
	at java.lang.Long.parseLong(Long.java:636)
	at org.mozilla.fenix.library.downloads.viewholders.DownloadsListItemViewHolder.bind(DownloadsListItemViewHolder.kt:3)
	at org.mozilla.fenix.library.downloads.DownloadAdapter.onBindViewHolder(DownloadAdapter.kt:3)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:146)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:120)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
	at android.view.View.layout(View.java:21964)
	at android.view.ViewGroup.layout(ViewGroup.java:6317)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3161)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2671)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1799)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:854)
	at android.view.Choreographer.doFrame(Choreographer.java:789)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Amejia481** [comment]
Duplicated of https://github.com/mozilla-mobile/fenix/issues/14772
