### ISSUE TITLE
[Bug auto found][Crash] java.lang.RuntimeException: StrictMode ThreadPolicy violation

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16502]
## Steps to reproduce
The crash happened during automation tests runs:
BookmarksTest#openSelectionInNewTabTest:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4637729245088233219/executions/bs.e4dc60e9f8bf5506/testcases/1/test-cases
SettingsPrivacyTest#loginsAndPasswordsTest:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4637729245088233219/executions/bs.7ee20609521213a5/testcases/2/test-cases

[firebase crash log.txt](https://github.com/mozilla-mobile/fenix/files/5523050/firebase.crash.log.txt)

Stacktrace:
`java.lang.RuntimeException: StrictMode ThreadPolicy violation
at android.os.StrictMode$AndroidBlockGuardPolicy.onThreadPolicyViolation(StrictMode.java:1705)
at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$handleViolationWithTimingAttempt$0(StrictMode.java:1619)
at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$9nBulCQKaMajrWr41SB7f7YRT1I.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:256)
at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:301)
at mozilla.components.support.ktx.android.content.IntPreference.getValue(SharedPreferences.kt:50)
at mozilla.components.support.ktx.android.content.IntPreference.getValue(SharedPreferences.kt:44)
at org.mozilla.fenix.onboarding.FenixOnboarding.getOnboardedVersion(Unknown Source:7)
at org.mozilla.fenix.onboarding.FenixOnboarding.userHasBeenOnboarded(FenixOnboarding.kt:30)
at org.mozilla.fenix.home.CurrentMode.getCurrentMode(Mode.kt:55)
at org.mozilla.fenix.home.HomeFragment$onCreateView$2.invoke(HomeFragment.kt:196)
at org.mozilla.fenix.home.HomeFragment$onCreateView$2.invoke(HomeFragment.kt:111)
at org.mozilla.fenix.components.StoreProviderFactory.create(StoreProvider.kt:42)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
at org.mozilla.fenix.components.StoreProvider$Companion.get(StoreProvider.kt:46)
at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:191)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2236)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2009)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1965)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:304)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:723)
at android.app.Activity.performStart(Activity.java:7157)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)`

### Device information

* Android device: Pixel 2 (Android 9) Firebase virtual device 
* Fenix version: Debug 11/10

**Comment by sv-ohorvath** [comment]
Still crashing sometimes: https://crash-stats.mozilla.org/report/index/24e8c374-f42f-4c18-b5c5-2a9b70201214
