### ISSUE TITLE
Fragment ShareFragment{97ccecb} (4a5dd9ff-7c68-43df-b52f-6cbd12eb82f3)} not attached to a context

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16538]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/7135873/

```
java.lang.IllegalStateException: Fragment ShareFragment{97ccecb} (4a5dd9ff-7c68-43df-b52f-6cbd12eb82f3)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
    at org.mozilla.fenix.share.ShareFragment.consumePrompt(ShareFragment.kt:1)
    at org.mozilla.fenix.share.ShareFragment.access$consumePrompt(ShareFragment.kt:1)
    at org.mozilla.fenix.share.ShareFragment$onCreateView$1.invoke(ShareFragment.kt:3)
    at org.mozilla.fenix.share.DefaultShareController$shareToDevicesWithRetry$1.invokeSuspend(ShareController.kt:11)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6864)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8758)

**Comment by mcarare** [comment]
See https://github.com/mozilla-mobile/fenix/issues/20208 for STR.

**Comment by mystiquewolf** [comment]
wontfix makes this bug sad... it prefers to stay in the backlog instead...

**Comment by mystiquewolf** [comment]
Happy birthday, my little buggie!
