### ISSUE TITLE
AutocompleteRequest Cannot confirm/dismiss a Prompt twice.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16539]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9514284

```
java.lang.RuntimeException: Cannot confirm/dismiss a Prompt twice.
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$BasePrompt.confirm(GeckoSession.java:5)
    at org.mozilla.geckoview.GeckoSession$PromptDelegate$AutocompleteRequest.confirm(GeckoSession.java:2)
    at mozilla.components.browser.engine.gecko.prompt.-$$LambdaGroup$ks$l04uV7dUmf6bB3wi8mBVf1nzQ3g.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:3)
    at mozilla.components.feature.prompts.login.LoginPicker$onLoginSelected$1.invoke(LoginPicker.kt:3)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
    at androidx.core.app.AppOpsManagerCompat.consumePromptFrom$default(AppOpsManagerCompat.java:1)
    at mozilla.components.feature.prompts.login.LoginPicker.onLoginSelected(LoginPicker.kt:1)
    at mozilla.components.feature.prompts.login.LoginSelectBar$listAdapter$1.invoke(LoginSelectBar.kt:3)
    at mozilla.components.feature.prompts.login.LoginViewHolder.onClick(BasicLoginAdapter.kt:1)
    at android.view.View.performClick(View.java:7201)
    at android.view.View.performClickInternal(View.java:7170)
    at android.view.View.access$3500(View.java:806)
    at android.view.View$PerformClick.run(View.java:27562)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Amejia481** [comment]
https://github.com/mozilla-mobile/android-components/issues/8464

**Comment by Amejia481** [comment]
No new entries on sentry
