### ISSUE TITLE
[Bug] Crash relating to file chooser

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#16590]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click on a link a few times which opens the system file and media chooser 
Click back a few times
### Expected behavior
No crash
### Actual behavior
`
f9071464-c076-43c7-a2be-dcebb14b42bb
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{c95968} (97eb5d93-c6c8-4b57-8dff-90b340fd55c0)} not associated with a fragment manager.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=98d76ac2958b4ab684db9af00df0cf19
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-97cb0660-38b9-4dc1-af13-a0b9b0201116
----
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{c95968} (97eb5d93-c6c8-4b57-8dff-90b340fd55c0)} not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:16)
	at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:1)
	at mozilla.components.feature.prompts.PromptFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:6)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

`
### Device information

* Android device: Redmi Note 4 MiUI
* Fenix version: Nightly

**Comment by Amejia481** [comment]
We don't see new reports on sentry, please feel free to reopen if it's needed.
