### ISSUE TITLE
NumberFormatExceptionjava.lang.Integer in parseInt fatal for input string: "undefined"

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16623]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9812825/

```
java.lang.NumberFormatException: For input string: "undefined"
    at java.lang.Integer.parseInt(Integer.java:615)
    at java.lang.Integer.valueOf(Integer.java:801)
    at org.mozilla.geckoview.MediaSession$Metadata.fromBundle(MediaSession.java:16)
    at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:9)
    at org.mozilla.geckoview.MediaSession$Handler.handleMessage(MediaSession.java:1)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
    at org.mozilla.gecko.EventDispatcher$2.run(EventDispatcher.java:1)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Amejia481** [comment]
This looks like a gv bug as there is not AC or Fenix as part of the stack trace, I opened this ticker for the team to take a look https://bugzilla.mozilla.org/show_bug.cgi?id=1677838

**Comment by kbrosnan** [comment]
Looks like this was accepted by GV closing in favor of the GV bug.
