### ISSUE TITLE
Fragment BrowserFragment{1f7910 (033bb425-16db-4d95-9080-347934f9f166)} not attached to a context.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#16624]
Very high volume 3k 🔥 
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/5790542/

```
java.lang.IllegalStateException: Fragment BrowserFragment{1f7910 (033bb425-16db-4d95-9080-347934f9f166)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at org.mozilla.fenix.ext.FragmentKt.getRequireComponents(Fragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:7)
    at org.mozilla.fenix.browser.BrowserFragment.setToolbarBehavior(BrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment.access$setToolbarBehavior(BrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment$subscribeToSession$observer$1.onLoadingStateChanged(BrowserFragment.kt:2)
    at -$$LambdaGroup$ks$87Yg77QvoR94VDGBojvpOmbVHXA.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:10)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:5)
    at mozilla.components.browser.session.Session.notifyObservers(Session.kt)
    at mozilla.components.browser.session.Session.notifyObservers(Session.kt:3)
    at mozilla.components.browser.session.Session.access$notifyObservers(Session.kt:1)
    at mozilla.components.browser.session.Session$$special$$inlined$observable$4.afterChange(Delegates.kt:2)
    at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:4)
    at mozilla.components.browser.session.Session.setLoading(Session.kt)
    at mozilla.components.browser.session.engine.EngineObserver.onLoadingStateChange(EngineObserver.kt:1)
    at -$$LambdaGroup$ks$2BBRo6CDVagyGSa1xIYz6sK7poI.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:8)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:5)
    at mozilla.components.concept.engine.EngineSession.notifyObservers(EngineSession.kt)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createProgressDelegate$1.onPageStart(GeckoEngineSession.kt:2)
    at org.mozilla.geckoview.GeckoSession$4.handleMessage(GeckoSession.java:5)
    at org.mozilla.geckoview.GeckoSession$4.handleMessage(GeckoSession.java:1)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
    at android.os.Handler.handleCallback(Handler.java:836)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:203)
    at android.app.ActivityThread.main(ActivityThread.java:6251)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by csadilek** [comment]
@Amejia481 this looks really old though e.g. happening 100% with A-C 0.56.5 (note 0. not 56.)

**Comment by Amejia481** [comment]
Yes, let's close it, it's only happening in old builds
