### ISSUE TITLE
[Bug] Should not prompt to try grid layout if already using grid layout in tab view

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#16735]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

0. have grid layout enabled.
1. go to tab switcher

### Expected behavior

I don't see a prompt for "Change the layout of open tabs. Go to settings and select grid under tab view".

### Actual behavior

I see a prompt for "Change the layout of open tabs. Go to settings and select grid under tab view", which must be dismissed. 

![signal-2020-11-24-215120](https://user-images.githubusercontent.com/152493/100177253-b4a01580-2e9f-11eb-872a-1fe380cf955c.png)

### Device information

* Android device: Pixel 2
* Fenix version: Nightly 201123 17:01 (Build #2015777355)
AC: 68.0.20201122190139, 52be4ca37
GV: 85.0a1-20201122093438
AS: 67.0.0

**Comment by AndiAJ** [comment]
**Reproducible** on the latest **Nightly 201126** using the following devices:
• Google Pixel 3a (Android 11)
• Google Pixel 2 (Android 9)

**Comment by sflorean** [comment]
@mcarare Tested on Nightly 11/27 and a crash is displayed when trying to enable the prompt. **Not reproducible on Nightly 11/26 or in list view.**
Devices:
- Google Pixel 3a (Android 11)
- OnePlus A3 (Android 6.0.1)
- Pixel 3 (Android 11)

STR:
Start Nightly with a clean profile.
Enable grid view.
Open 6 tabs - wikipedia.
Tap on tabs counter in order to open tabs tray. 

8f3312da-febb-45f3-87af-325bd56a00bd
java.lang.ClassCastException: org.mozilla.fenix.browser.InfoBanner cannot be cast to kotlin.Unit
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=378eb37f835c41b6b3c9ded8c179ed82
* Socorro: https://crash-stats.mozilla.org/report/index/bp-24c2054c-194c-45d5-a601-467750201127
----
java.lang.ClassCastException: org.mozilla.fenix.browser.InfoBanner cannot be cast to kotlin.Unit
at org.mozilla.fenix.tabtray.TabTrayView.<init>(TabTrayView.kt:87)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment.onViewCreated(TabTrayDialogFragment.kt:36)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201203`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)
