### ISSUE TITLE
App crashes when displaying recently closed tabs info banner.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#16759]
@mcarare Tested on Nightly 11/27 and a crash is displayed when trying to enable the prompt. **Not reproducible on Nightly 11/26 or in list view.**
Devices:
- Google Pixel 3a (Android 11)
- OnePlus A3 (Android 6.0.1)
- Pixel 3 (Android 11)

STR:
Start Nightly with a clean profile.
Enable grid view.
Open 6 tabs - wikipedia.
Tap on tabs counter in order to open tabs tray. 

8f3312da-febb-45f3-87af-325bd56a00bd
java.lang.ClassCastException: org.mozilla.fenix.browser.InfoBanner cannot be cast to kotlin.Unit
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=378eb37f835c41b6b3c9ded8c179ed82
* Socorro: https://crash-stats.mozilla.org/report/index/bp-24c2054c-194c-45d5-a601-467750201127
----
java.lang.ClassCastException: org.mozilla.fenix.browser.InfoBanner cannot be cast to kotlin.Unit
at org.mozilla.fenix.tabtray.TabTrayView.<init>(TabTrayView.kt:87)
at org.mozilla.fenix.tabtray.TabTrayDialogFragment.onViewCreated(TabTrayDialogFragment.kt:36)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

_Originally posted by @sflorean in https://github.com/mozilla-mobile/fenix/issues/16735#issuecomment-734900845_

**Comment by jonalmeida** [comment]
Sentry issue: [FIREFOX-NIGHTLY-8RP](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10023979/?referrer=github_plugin)

Linking to the Sentry dashboard.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`Nightly Build 201203`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

**Comment by Piping** [comment]
My firefox after uotgade kept crashing on the exact issue. How can I fix it? The browser is not usable anymore.

**Comment by lindongbin** [comment]
https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.ClassCastException%3A%20at%20org.mozilla.fenix.tabtray.TabTrayView.%3Cinit%3E%28TabTrayView.kt%3A86%29&date=%3E%3D2020-12-26T09%3A16%3A00.000Z&date=%3C2021-01-02T09%3A16%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1

crash on 84.1.2
