### ISSUE TITLE
Crash in [@ java.lang.NullPointerException: at org.mozilla.fenix.components.toolbar.DefaultToolbarIntegration.<init>(ToolbarIntegration.kt:16)] on Kindle devices

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/fenix#16775]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

User reporting crash in SUMO under https://support.mozilla.org/en-US/questions/1315624

Sentry link with crash logs: https://sentry.prod.mozaws.net/operations/firefox/issues/10023896/?query=is%3Aunresolved%20NullPointerException%20toolbar

### Device information

* Android device: Amazon Fire HD 10 2019, Amazon Android 7.3.1.6
* Fenix version: 83 (taken from Kitsune), installed from GPS

**Comment by yoasif** [comment]
Other reports say that this is due to the "Follow device theme" setting: https://www.reddit.com/r/firefox/comments/k45117/if_firefox_is_crashing_on_your_kindle_fire_hd_set/

**Comment by kbrosnan** [comment]
Crash report: https://crash-stats.mozilla.org/report/index/da2d9181-dbf8-489b-b934-27cca0201130

Java stack trace:
```
java.lang.NullPointerException
	at org.mozilla.fenix.components.toolbar.DefaultToolbarIntegration.<init>(ToolbarIntegration.kt:16)
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView.<init>(BrowserToolbarView.kt:88)
	at org.mozilla.fenix.browser.BaseBrowserFragment.initializeUI$app_nightly(BaseBrowserFragment.kt:54)
	at org.mozilla.fenix.browser.BrowserFragment.initializeUI$app_nightly(BrowserFragment.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mcarare** [comment]
No devices to test this on, but we should follow sentry reports to see if any crashes occur with Fenix versions that include this fix.
