### ISSUE TITLE
Instrumented test crashed: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16889]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce

One of the UI tests failed on Firebase with a crash:
Test name: org.mozilla.fenix.ui.SmokeTest#openMainMenuAddTopSiteTest

### Expected behavior
From the video, it looks like the test is trying to load a webpage on a freshly installed app.

### Actual behavior
Test report: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5291967431887756400/executions/bs.9445c464ee1d141e

Stacktrace:
`Fatal exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
     FATAL EXCEPTION: DefaultDispatcher-worker-14
Process: org.mozilla.fenix.debug, PID: 14263
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.lifecycle.LifecycleRegistry.calculateTargetState(LifecycleRegistry.java:162)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:183)
	at mozilla.components.lib.state.ext.StoreExtensionsKt.flow(StoreExtensions.kt:155)
	at mozilla.components.lib.state.ext.FragmentKt.consumeFlow(Fragment.kt:94)
	at mozilla.components.lib.state.ext.FragmentKt.consumeFlow$default(Fragment.kt:84)
	at org.mozilla.fenix.browser.BaseBrowserFragment.observeTabSource$app_debug(BaseBrowserFragment.kt:866)
	at org.mozilla.fenix.browser.BaseBrowserFragment$onViewCreated$1.invokeSuspend(BaseBrowserFragment.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

[IndexOutOfBounds-logcat.txt](https://github.com/mozilla-mobile/fenix/files/5651288/IndexOutOfBounds-logcat.txt)

### Device information

* Android device: Pixel 2 (API 28, Android 9)
* Fenix version: 12/7 Debug build

**Comment by sv-ohorvath** [comment]
I was able to reproduce this locally and got the same crash report as: https://github.com/mozilla-mobile/fenix/issues/16886
https://crash-stats.mozilla.org/report/index/d1023bae-2d20-4bbf-80cc-01a160201207

**Comment by ekager** [comment]
Probably also fixed by https://github.com/mozilla-mobile/fenix/pull/17053/
