### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.changeBookmarkParentFolderTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16913]
### Firebase Test Run:
Failed 1/2 tries
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8274980681831704477/executions/bs.c9ed8abd9187125e/testcases/1/test-cases
### Stacktrace:
`java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$changeBookmarkParentFolderTest$3.invoke(BookmarksTest.kt:467)
at org.mozilla.fenix.ui.BookmarksTest$changeBookmarkParentFolderTest$3.invoke(BookmarksTest.kt:34)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:167)
at org.mozilla.fenix.ui.BookmarksTest.changeBookmarkParentFolderTest(BookmarksTest.kt:465)`
### Build:  
Debug 12/8

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
