### ISSUE TITLE
Intermittent UI test failure - SmokeTest.swipeToSwitchTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16959]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5967813237957896382/executions/bs.bd459300d5b9c347/testcases/3/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:86)
at org.mozilla.fenix.ui.SmokeTest$swipeToSwitchTabTest$5.invoke(SmokeTest.kt:426)
at org.mozilla.fenix.ui.SmokeTest$swipeToSwitchTabTest$5.invoke(SmokeTest.kt:33)
at org.mozilla.fenix.ui.robots.SearchRobot$Transition.submitQuery(SearchRobot.kt:161)
at org.mozilla.fenix.ui.SmokeTest.swipeToSwitchTabTest(SmokeTest.kt:424)`
### Build: 
Debug 12/10

**Comment by sv-ohorvath** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/commit/9d5ec47ec34f818ca3843fe067b9bf44c2b01402

**Comment by isabelrios** [comment]
Just failed today Dec 10th 1/2, re-opening...
 java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:95)
at org.mozilla.fenix.ui.SmokeTest$swipeToSwitchTabTest$5.invoke(SmokeTest.kt:426)
at org.mozilla.fenix.ui.SmokeTest$swipeToSwitchTabTest$5.invoke(SmokeTest.kt:33)
at org.mozilla.fenix.ui.robots.SearchRobot$Transition.submitQuery(SearchRobot.kt:161)
at org.mozilla.fenix.ui.SmokeTest.swipeToSwitchTabTest(SmokeTest.kt:424)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
Flaky on 12/16: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5152169490681586987/executions/bs.25a449b6467a87dd/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/18: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6039556852474871713/executions/bs.c5fa95679e83cd4e/testcases/3/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/24: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7269207572937503256/executions/bs.d99125414c535263/testcases/2/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 1/27: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5834104574376919215/executions/bs.1854b66bb4b4870e/testcases/3/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on Master on 1/31: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9094945104115736781/executions/bs.f9e18a34c8b1ad81/testcases/3/test-cases
