### ISSUE TITLE
Intermittent UI test failure - SmokeTest.mainMenuAddToHomeScreenTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#16966]
### Firebase Test Run:
Flaky, failed 1/2 tries
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8200393172003902004/executions/bs.d8edd3f25010a929/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:86)
at org.mozilla.fenix.ui.SmokeTest$mainMenuAddToHomeScreenTest$5.invoke(SmokeTest.kt:233)
at org.mozilla.fenix.ui.SmokeTest$mainMenuAddToHomeScreenTest$5.invoke(SmokeTest.kt:33)
at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:62)
at org.mozilla.fenix.ui.SmokeTest.mainMenuAddToHomeScreenTest(SmokeTest.kt:232)`
### Build: 
Debug 12/10

**Comment by sv-ohorvath** [comment]
Failure in verifyPageContent(). Might be fixed by changes just landed in this PR: https://github.com/mozilla-mobile/fenix/pull/16962
I'll keep monitoring and see if it appears again.

**Comment by sv-ohorvath** [comment]
Still flaky, failed 1 out of 2 on 12/16: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8216664517897201438/executions/bs.6097133d9b92e946/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
Flaky on 12/25 on master: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6299530087336913567/executions/bs.41d393700705fae0/testcases/1/test-cases
