### ISSUE TITLE
Firefox Nightly Crashes

### ISSUE THREAD

**Issue by technicos** [mozilla-mobile/fenix#16990]
Firefox Nightly crashes after vpn is dropped.

e5595f89-361b-4670-9e67-c885ab1432b8
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: org.mozilla.experiments.nimbus.ErrorException$RequestError: Error sending request: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=cecbbcdcbb624e4688b448f15e0030d2
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-faa68b68-47e0-4460-8eaf-41b1e0201212
----
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: org.mozilla.experiments.nimbus.ErrorException$RequestError: Error sending request: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2880)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: org.mozilla.experiments.nimbus.ErrorException$RequestError: Error sending request: [no-sentry] Network error: Java error: "fetch error: org.mozilla.geckoview.WebRequestError: Request failed, error=0x25, category=0x5"
	at org.mozilla.experiments.nimbus.Error.intoException(nimbus.kt:9)
	at org.mozilla.experiments.nimbus.NimbusClient.getExperimentBranch(nimbus.kt:10)
	at mozilla.components.service.nimbus.Nimbus.getExperimentBranch(Nimbus.kt:1)
	at org.mozilla.fenix.home.HomeMenu$coreMenuItems$2.invoke(HomeMenu.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at org.mozilla.fenix.home.HomeMenu.<init>(HomeMenu.kt:23)
	at org.mozilla.fenix.home.HomeFragment.onViewCreated(HomeFragment.kt:9)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:6)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:3)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:26)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:1)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:5)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1372)
	at android.app.Activity.performStart(Activity.java:7110)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2765)
	... 9 more

@

**Comment by csadilek** [comment]
@technicos Thanks for filing! This should already be fixed in latest Nightly 201211 17:01.

Duping to https://github.com/mozilla-mobile/fenix/issues/16886.

**Comment by technicos** [comment]
> @technicos Thanks for filing! This should already be fixed in latest Nightly 201211 17:01.
> 
> Duping to #16886.

Got it. Thank you for the reference.
