### ISSUE TITLE
Crash in [@ java.lang.ClassCastException: at org.mozilla.fenix.tabtray.TabTrayView.<init>(TabTrayView.kt:86)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#17029]
Crash report: https://crash-stats.mozilla.org/report/index/d1551ed9-ea27-421c-8fc6-592650201214
Not showing up on Release 83 
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/10122251/
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10023979/

Java stack trace:
```
java.lang.ClassCastException: org.mozilla.fenix.browser.InfoBanner cannot be cast to kotlin.Unit
	at org.mozilla.fenix.tabtray.TabTrayView.<init>(TabTrayView.kt:86)
	at org.mozilla.fenix.tabtray.TabTrayDialogFragment.onViewCreated(TabTrayDialogFragment.kt:36)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:21)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:28)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by kbrosnan** [comment]
Dupe of https://github.com/mozilla-mobile/fenix/issues/16759
