### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.multipleSelectionShareButtonTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17021]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8421082588275638479/executions/bs.efc1affdedbb6b4e/testcases/1/test-cases
### Stacktrace:
`java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$multipleSelectionShareButtonTest$3.invoke(BookmarksTest.kt:411)
at org.mozilla.fenix.ui.BookmarksTest$multipleSelectionShareButtonTest$3.invoke(BookmarksTest.kt:34)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:167)
at org.mozilla.fenix.ui.BookmarksTest.multipleSelectionShareButtonTest(BookmarksTest.kt:409)`
### Build: 
Debug 12/14

**Comment by sv-ohorvath** [comment]
Flaky again on 12/16: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7966931840443472143/executions/bs.f7c24fe487f2db63/testcases/1/test-cases

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
