### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.copyBookmarkURLTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17095]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5797098403556412572/executions/bs.38f8e58e6907f44f/testcases/1/test-cases
### Stacktrace:
`java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$copyBookmarkURLTest$3.invoke(BookmarksTest.kt:188)
at org.mozilla.fenix.ui.BookmarksTest$copyBookmarkURLTest$3.invoke(BookmarksTest.kt:34)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:167)
at org.mozilla.fenix.ui.BookmarksTest.copyBookmarkURLTest(BookmarksTest.kt:186)`
### Build: 
Debug 12/16

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
