### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.editBookmarkTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17094]
### Firebase Test Run:
Flaky, but failed on 2 different test runs on 12/6
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9113695952861788340/executions/bs.a4c91089eeb2c61f/testcases/1/test-cases
### Stacktrace:
`java.lang.NullPointerException: activityTestRule.activit…wById(R.id.bookmark_list) must not be null
at org.mozilla.fenix.ui.BookmarksTest$editBookmarkTest$3.invoke(BookmarksTest.kt:162)
at org.mozilla.fenix.ui.BookmarksTest$editBookmarkTest$3.invoke(BookmarksTest.kt:34)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:167)
at org.mozilla.fenix.ui.BookmarksTest.editBookmarkTest(BookmarksTest.kt:160)`
### Build: 
Debug 12/16

**Comment by sv-ohorvath** [comment]
Same error on: 
https://github.com/mozilla-mobile/fenix/issues/17021
https://github.com/mozilla-mobile/fenix/issues/16913
https://github.com/mozilla-mobile/fenix/issues/16671

**Comment by sv-ohorvath** [comment]
This, along with some other Bookmarks tests, failed after an AC upgrade and we haven't seen this failure since more than a month ago. Closing the issue and will reopen if it occurs again.
