### ISSUE TITLE
[Bug] Fenix crash sometimes when I switch tabs

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [mozilla-mobile/fenix#17234]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open tab list after I opened multiple tabs

### Expected behavior
Firefox should be safe to switch tabs, and prevent memory leaks

### Actual behavior
Firefox freezes when I open the tab list, then crash.
See my last two crash reports:
https://crash-stats.mozilla.org/report/index/075ba805-5c55-4e87-95c6-912d10201226
https://crash-stats.mozilla.org/report/index/7e2ab0e1-3ef4-40b4-86c7-dcc730201226

### Device information

* Android device: Android 7.0, Galaxy S6
* Fenix version: 84.1.2

**Comment by KrasnayaPloshchad** [comment]
This bug seems happened exclusively after opening multiple pages from Wikimedia sites.

**Comment by toxpal** [comment]
It happens for me for about 1 week... On some sites if I open multiple tabs and try to switch, Fennec freezes for a second or two, and then crashes. Happens on some websites only, but it never crashed before.

Xperia 5 II/Android 10.

Latest update didn't solve the issue, it drives me crazy.

**Comment by sflorean** [comment]
I wasn't able to reproduce the crash on Xiaomi Redmi Note 8T (Android 9) or Pixel 3 (Android 11) on latest Nightly. @KrasnayaPloshchad do you have some additional steps? Thank you!

**Comment by toxpal** [comment]
@sflorean I was able to re-produce the issue on wikimedia site on the first try. This is what I did - launched app with no tabs, typed wikimedia.org and waited for website to load. Then I opened 8 tabs (by clicking first 8 links) in background. Once I tried to switch tabs, app freezed and crashed (and suggested to send a report to Mozilla).

Just to let you know, this issue happens with many other sites too. Usually it's needed to open 5+ tabs at least.

**Comment by KrasnayaPloshchad** [comment]
> @KrasnayaPloshchad do you have some additional steps? Thank you!

No, no more steps, that’s all, and the problems happened randomly and suddenly.

**Comment by KrasnayaPloshchad** [comment]
> @KrasnayaPloshchad do you have some additional steps? Thank you!

I found this can also reproduce with various sites running MediaWiki software, they are listed [here](https://m.mediawiki.org/wiki/Sites_using_MediaWiki/en). BTW I think Fenix need more improves for its memory manage mechanism to reduce the crash.

**Comment by KrasnayaPloshchad** [comment]
Here are summaries of today’s crashes for me:


```
5b195baf-cb31-46fe-b7c2-1db5d350978e
<native crash>
----
<native crash>
```

```
a85cf816-9f3a-4125-95de-b52c42322772
java.lang.OutOfMemoryError: Failed to allocate a 1701292 byte allocation with 1158640 free bytes and 1131KB until OOM
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=1d020951f266441e8435bc0a1106d588
----
java.lang.OutOfMemoryError: Failed to allocate a 1701292 byte allocation with 1158640 free bytes and 1131KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1179)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
	at android.content.res.Resources.getDrawable(Resources.java:1640)
	at android.content.Context.getDrawable(Context.java:525)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:1)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:9)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:1)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:1)
	at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:7)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:8)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:37)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:13)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:193)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:1)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:6)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:3)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:26)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:1)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:5)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
	at android.app.Activity.performStart(Activity.java:6959)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2890)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

```
3abb8aee-5473-41da-8992-6d2ff4a87e54
<native crash>
----
<native crash>
```

```
dbb540d8-9115-4ff0-984e-46b51508cb8a
<native crash>
----
<native crash>
```

```
b2a65036-083f-4a92-b231-d37d5e93a31e
<native crash>
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-c0970f95-e175-40bb-9a9b-7f6f10210111
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-5db4ba98-8014-4c35-a4a1-8b5cd0210111
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-8f6bc778-6855-44a3-8327-f65d00210111
----
<native crash>
```

**Comment by sflorean** [comment]
@KrasnayaPloshchad this is still reproducible for you?

**Comment by KrasnayaPloshchad** [comment]
I’m very hard to reproduce now (v86.1.1). If anyone who feel reproducible, let me know.

**Comment by KrasnayaPloshchad** [comment]
It’s still reproducible with Firefox Nightly

Nightly 210210 17:03 (Build #2015792523)
AC: 73.0.20210209203620, fbf61006d
GV: 87.0a1-20210209092956
AS: 69.0.0

**Comment by KrasnayaPloshchad** [comment]
I saw there are two conditions can cause the browser crash as this:
1. The website integrated series of complex styles
2. The webpage used lots of images

91.0a1 (Build #2015819403)
AC: 91.0.20210629143047, 8904b55efe
GV: 91.0a1-20210629092640
AS: 79.0.0

**Comment by chartmix** [comment]
I think I have the same problem and Firefox (Beta) crashes every day 1-2 times when switching tabs.
It's happening since long ago. See issue #19991
Has it something to do with low RAM? 
I'm no expert but what is needed to solve it? 
Most of the time I send feedback and it says App not responding.

**Comment by KrasnayaPloshchad** [comment]
This is still reproduced to me sometimes, but I believe for most people, when they suffered the crash as this, they doesn’t feedback but abandon Fenix anyway, so I hope developers find the way for fix.
