### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.deleteMultipleSelectionTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17309]
### Firebase Test Run:
Flaky, failed 1/2
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6303712677038501074/executions/bs.313bf4093bd5b936/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot.clickAddBookmarkButton(ThreeDotMenuMainRobot.kt:84)
at org.mozilla.fenix.ui.robots.BrowserRobot$createBookmark$3.invoke(BrowserRobot.kt:299)
at org.mozilla.fenix.ui.robots.BrowserRobot$createBookmark$3.invoke(BrowserRobot.kt:47)`
### Build: 
Master 1/4/21

From the video it looks like the main menu is opened before the browser manages to completely load the second webpage, so the bookmark button is not in the correct state.

See also: https://github.com/mozilla-mobile/fenix/issues/13447 (for the same error)

**Comment by sv-ohorvath** [comment]
Flaky on 1/20: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7150731363913616220/executions/bs.fa03f857eb4d8a88/testcases/1/test-cases
