### ISSUE TITLE
Crashing when opening a new private tab (84.1.2)

### ISSUE THREAD

**Issue by Chubby-Unicorn** [mozilla-mobile/fenix#17327]
Firefox for android 84.1.2
Android 9
Launcher: Nova - 6.2.18

The app crashes if a video from within the app is playing in PiP and you press "New Private Tab" from the along press app menu. It loads all the way into making the tab, then crashed the whole app. It only seems to happen if the video is playing, and it is a private tab, not a regular tab. I've replicated it a few times on both youtube and 9anime.

The latest report is as follows (sorry, for not spoiler thing): 
6f50b8fc-ecaf-43c6-953d-d9c6afdafa61
java.lang.IllegalStateException: Fragment BrowserFragment{d657680} (0ea33f95-434a-4241-ab3b-04998b99704f)} not attached to a context.
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=14721408d9a84b8189c991eb56f6fb10
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-4084e431-4161-403d-97a4-78e3d0210106
----
java.lang.IllegalStateException: Fragment BrowserFragment{d657680} (0ea33f95-434a-4241-ab3b-04998b99704f)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.getSessionById(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.removeSessionIfNeeded(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onBackPressed(BaseBrowserFragment.kt:4)
	at org.mozilla.fenix.browser.BrowserFragment.onBackPressed(BrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.access$pipModeChanged(BaseBrowserFragment.kt:2)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$2.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:11)
	at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$19$1$1.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by ekager** [comment]
Can you reproduce the same crash on Nightly? I'm seeing weird behavior where the new private tab opens in the PiP window, but it doesn't crash for me.
