### ISSUE TITLE
FNX3-15780 ⁃ [Bug] crash when opening bookmarks

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#1732]
### Steps to reproduce
1. open bookmarks in your library

### Expected behavior
No crash.

### Actual behavior
    2019-04-17 21:20:54.107 14200-14279/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
        Process: org.mozilla.fenix.debug, PID: 14200
        mozilla.appservices.places.InternalPanic: assertion failed: `(left == right)`
          left: `ReadOnly`,
         right: `ReadWrite`: coop_transaction must only be called on the ReadWrite connection
            at mozilla.appservices.places.RustError.intoException(RustError.kt:61)
            at mozilla.appservices.places.PlacesReaderConnection.getBookmarksTree(PlacesConnection.kt:878)
            at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invokeSuspend(PlacesBookmarksStorage.kt:34)
            at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getTree$2.invoke(Unknown Source:10)
            at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
            at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
            at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
            at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.getTree$suspendImpl(PlacesBookmarksStorage.kt:33)
            at mozilla.components.browser.storage.sync.PlacesBookmarksStorage.getTree(Unknown Source:0)
            at mozilla.components.concept.storage.BookmarksStorage$DefaultImpls.getTree$default(BookmarksStorage.kt:19)
            at org.mozilla.fenix.library.bookmarks.BookmarkFragment$onViewCreated$1.invokeSuspend(BookmarkFragment.kt:333)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
            at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision f5babaf47d7f1f13b8dcb8cc151bc113618d085b

**Comment by colintheshots** [comment]
This seems to be new in the last 24 hours or so. We just upgraded application-services, so I'll look into what changed.

**Comment by vesta0** [comment]
@colintheshots FYI crash also happens when I add a new bookmark and click on EDIT (same route)

**Comment by colintheshots** [comment]
Yes, that's the same crash on the same API call, but on a different screen. Something changed in our Rust dependency. I'm having them look into it.

**Comment by sv-ohorvath** [comment]
Verified as fixed on 4/21 build.
