### ISSUE TITLE
[Bug] Firefox nightly crashing every second

### ISSUE THREAD

**Issue by SuperTux88** [mozilla-mobile/fenix#17334]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

```
01-06 13:33:58.882 22743 22743 E AndroidRuntime: FATAL EXCEPTION: main
01-06 13:33:58.882 22743 22743 E AndroidRuntime: Process: org.mozilla.fenix, PID: 22743
01-06 13:33:58.882 22743 22743 E AndroidRuntime: org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at org.json.JSON.typeMismatch(JSON.java:111)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:163)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at org.json.JSONObject.<init>(JSONObject.java:176)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$SessionState.fromString(GeckoSession.java:1)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tab(BrowserStateReader.kt:69)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.access$browsingSession(BrowserStateReader.kt:11)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReader.read(BrowserStateReader.kt:3)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:3)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at mozilla.components.feature.tabs.TabsUseCases$RestoreUseCase$invoke$2.invokeSuspend(TabsUseCases.kt:5)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-06 13:33:58.882 22743 22743 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: Uncaught exception handled: 
01-06 13:33:58.883 22743 22743 E ExceptionHandler: org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at org.json.JSON.typeMismatch(JSON.java:111)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at org.json.JSONObject.<init>(JSONObject.java:163)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at org.json.JSONObject.<init>(JSONObject.java:176)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at org.mozilla.geckoview.GeckoSession$SessionState.fromString(GeckoSession.java:1)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tab(BrowserStateReader.kt:69)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.access$browsingSession(BrowserStateReader.kt:11)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at mozilla.components.browser.session.storage.serialize.BrowserStateReader.read(BrowserStateReader.kt:3)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:3)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at mozilla.components.feature.tabs.TabsUseCases$RestoreUseCase$invoke$2.invokeSuspend(TabsUseCases.kt:5)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
01-06 13:33:58.883 22743 22743 E ExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
01-06 13:33:58.885 22743 22743 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(timestamp=1609936438885, throwable=org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject, breadcrumbs=[], uuid=81b656d7-c286-4742-ba9f-3bebfa725769)
```

## Steps to reproduce

Try to use my phone with having Firefox Nightly installed

### Expected behavior

Being able to use my phone.

### Actual behavior

Firefox crashing every second interrupting whatever I try to do, only to just crash again when I click the "close" button.

### Device information

* Android device: Blackberry KEY 2
* Fenix version: Nightly 210105 17:01

**Comment by pukafever** [comment]
I do confirm this bug on my phone:
 
- Samsung Galaxy S8 (SM-G950F)
- Android 9
- Nightly 210105 17:01

To solve the issue, you need to kill the app from the Android settings page.

**Comment by SuperTux88** [comment]
Oh yes, I just found out that force-stopping the app seems to stop the crashes (rebooting didn't help), but I have no idea for how long until something triggers Firefox to start again.

**Comment by Ruin0x11** [comment]
Same error, and force stopping doesn't work. I can't access anything from Firefox anymore.

**Comment by SuperTux88** [comment]
Force-stopping doesn't "fix" the problems, but it makes the crashes every second stop (at least for a while), so I can at least use the rest of my phone again without being interrupted by the crash popup every second.

![image](https://user-images.githubusercontent.com/458548/103781641-e8da2a80-5036-11eb-86f1-868c73f55613.png)

It looks like the "close" button on the crash popup doesn't actually close Firefox and it still tries to restart and then gets stuck in a crash loop. I'm not sure if I should open a second bug report to fix the "close" button to actually work and not restart.

**Comment by Ruin0x11** [comment]
To be clear, this is not just about Firefox crashing in the background all the time. It's also now impossible to open Firefox at all since it crashes immediately on startup. This should get fixed as soon as possible.

**Comment by kbrosnan** [comment]
Tracked by https://github.com/mozilla-mobile/android-components/issues/9332

**Comment by kbrosnan** [comment]
This should be fixed with the Nightly 210106 17:02 build.
