### ISSUE TITLE
Intermittent UI test failure - SmokeTest.noCrashWithAddonInstalledTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#17416]
### Firebase Test Run:
Failed 1 out of 2 tries:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8052980965356929009/executions/bs.3df2fa55dee69f2a/testcases/2/test-cases
### Stacktrace:
`androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:65)
at org.mozilla.fenix.ui.SmokeTest$noCrashWithAddonInstalledTest$11.invoke(SmokeTest.kt:613)
at org.mozilla.fenix.ui.SmokeTest$noCrashWithAddonInstalledTest$11.invoke(SmokeTest.kt:39)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openReportSiteIssue(ThreeDotMenuMainRobot.kt:268)
at org.mozilla.fenix.ui.SmokeTest.noCrashWithAddonInstalledTest(SmokeTest.kt:612)`
### Build: 
Debug 1/12

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9366)

**Comment by sv-ohorvath** [comment]
Couldn't reproduce or find a cause for this. Since it didn't fain in more than a month, I think we can close it and reopen if needed.

**Comment by sv-ohorvath** [comment]
Failed 1/2 tries again on 6/2: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6578523094523668247/executions/bs.548089d118477759/testcases/1/test-cases

**Comment by AndiAJ** [comment]
Flaky 1x on 4/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7840431478926272883/executions/bs.72b06bd18d86ced4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9173902444937625627/executions/bs.ad113be6ca58cf91/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{afd416e} (50059bef-9032-4f9b-bec6-807671dcb4c4) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5724556385792669296/executions/bs.f37164b8f0e63ce1/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{253dfe2} (c76f4f62-487a-46f8-bba9-177a4f0e7835) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8224077566715442354/executions/bs.50be2929ff751390/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{cb0b522} (3639bc75-1d18-48c5-a99c-b660157adbde) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7359284100500311315/executions/bs.ebb92f9f35686fc3/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 5/12: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8959582965103883565/details?stepId=bs.52723c1dc2c3171b&testCaseId=1&query=et.f2e75fe54a1faa5f&deeplink=true)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8457130337559163922/executions/bs.34917ea1aad989c9/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{4f58ecb} (b02b7c3f-e9ed-44d4-92e3-ca95defeef59) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6792710109858401798/executions/bs.956aff048d7fb67/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{8af2cc0} (49737988-f166-4a02-97a6-e12f5b9c5cf5) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5601265167547199173/executions/bs.468dfae2ac61945f/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{924390c} (d6ca5d8a-cfbc-40d3-8410-ffe72e1646d7) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5344484766244397594/executions/bs.13cf6d0a03029cbc/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{d0d871e} (8b74e929-b009-4e1c-8ede-994bee99940e) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by sv-ohorvath** [comment]
Hopefully fixed in https://github.com/mozilla-mobile/fenix/pull/25613
