### ISSUE TITLE
[Crash] NullPointerException when invalidating toolbar in response to reader updates

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#17441]
This started spiking today on 84.1.4, likely triggered by opening the app through an LP push notification. Cause is the `_browserToolbarView` being `null`: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L150

```
java.lang.NullPointerException: null
    at org.mozilla.fenix.browser.BaseBrowserFragment.getBrowserToolbarView$app_release(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment$initializeUI$$inlined$also$lambda$2$1.invoke(BrowserFragment.kt:8)
    at mozilla.components.feature.readerview.ReaderViewFeature.maybeNotifyReaderStatusChange$feature_readerview_release(ReaderViewFeature.kt:2)
    at mozilla.components.feature.readerview.ReaderViewFeature$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:7)
    at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:7)
    at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:3)
    at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:6)
    at mozilla.components.feature.readerview.ReaderViewFeature$start$1$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:8)
    at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at android.os.Handler.handleCallback(Handler.java:907)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:216)
    at android.app.ActivityThread.main(ActivityThread.java:7625)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by csadilek** [comment]
Sentry:
https://sentry.prod.mozaws.net/operations/firefox/issues/10242344/
https://sentry.prod.mozaws.net/operations/firefox/issues/10249486/

**Comment by csadilek** [comment]
The problem in this case is that the we pass a lambda to an A-C feature which will invoke it asynchronously whenever it hears back from the reader content script. By the time the lambda is invoked the fragment could already be detached (which we handle), but the view can also already be destroyed (which don't handle). For now we're just fixing this specific case here in Fenix, but we should think about a generic solution to this problem in A-C.

The features are all bound the view, using our `ViewBoundFeatureWrapper`, but that doesn't prevent them from accepting lambdas and invoke them even if the view is detached.

**Comment by Amejia481** [comment]
> The problem in this case is that the we pass a lambda to an A-C feature which will invoke it asynchronously whenever it hears back from the reader content script. By the time the lambda is invoked the fragment could already be detached (which we handle), but the view can also already be destroyed (which we don't handle). For now we're just fixing this specific case here in Fenix, but we should think about a generic solution to this problem in A-C.
> 
> The features are all bound to the view, using our `ViewBoundFeatureWrapper`, but that doesn't prevent them from accepting lambdas and invoke them even if the view is detached.

Some interesting fact in ac is all of our features are [LifecycleAwareFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/support/base/src/main/java/mozilla/components/support/base/feature/LifecycleAwareFeature.kt) that subsequently inherits from `LifecycleObserver`, this mean inside every feature we are able to know if the feature is already has been stopped if so we should not have to notify the lambdas any more, we could explore more avenues and see how they play.

**Comment by csadilek** [comment]
> Some interesting fact in ac is all of our features are LifecycleAwareFeature...

@Amejia481 That's what I thought too at first, but in this case the feature (reader view) already behaves correctly and doesn't notify the lambda if the feature is stopped. So we know in this case the feature and fragment were started but the view was null. We have seen various of these cases before when implementing `consumeFlow` and `consumeFrom` (see big comment [here](https://github.com/mozilla-mobile/android-components/blob/a9c8b530c74b7a33234969fe77907e74d1addbc8/components/lib/state/src/main/java/mozilla/components/lib/state/ext/Fragment.kt#L61)). So I am thinking if we go down that path we're gonna need to include the view as well as we did in `consumeFrom`. Need to think about this some more...

**Comment by Amejia481** [comment]
Thanks for the clarification.
