### ISSUE TITLE
[Bug] Native rust network connections are dropped

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#17585]
Pressing the Sync button reveals some errors in the logcat when network connections go through concept-fetch viaduct:

```
2021-01-22 21:20:16.394 4681-4718/? E/FxaDeviceConstellation: Error while running: polling for device commands
    mozilla.appservices.fxaclient.FxaException$Network: Network error: [no-sentry] Network error: Java error: "fetch error: No direct method <init>(Ljava/lang/String;Lmozilla/components/concept/fetch/Request$Method;Lmozilla/components/concept/fetch/MutableHeaders;Lkotlin/Pair;Lkotlin/Pair;Lmozilla/components/concept/fetch/Request$Body;Lmozilla/components/concept/fetch/Request$Redirect;Lmozilla/components/concept/fetch/Request$CookiePolicy;Z)V in class Lmozilla/components/concept/fetch/Request; or its super classes (declaration of \'mozilla.components.concept.fetch.Request\' appears in base.apk)"
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:5)
        at mozilla.appservices.fxaclient.FirefoxAccount.pollDeviceCommands(FirefoxAccount.kt:12)
        at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2$events$2.invokeSuspend(FxaDeviceConstellation.kt:2)
        at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2$events$2.invoke(FxaDeviceConstellation.kt:2)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:18)
        at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2.invokeSuspend(FxaDeviceConstellation.kt:5)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by jonalmeida** [comment]
The line in question is:

```
"fetch error: No direct method <init>(Ljava/lang/String;Lmozilla/components/concept/fetch/Request$Method;Lmozilla/components/concept/fetch/MutableHeaders;Lkotlin/Pair;Lkotlin/Pair;Lmozilla/components/concept/fetch/Request$Body;Lmozilla/components/concept/fetch/Request$Redirect;Lmozilla/components/concept/fetch/Request$CookiePolicy;Z)V in class Lmozilla/components/concept/fetch/Request; or its super classes (declaration of \'mozilla.components.concept.fetch.Request\' appears in base.apk)"
```

This looks like a class signature that doesn't match what a-s is using, which may be because app services is [using concept-fetch from the 63.0.0 release](https://github.com/mozilla/application-services/blob/051e1c39505bfd65efbb2735812538b46341b3d0/build.gradle#L7) but there was a signature change to the `Request` class that [landed recently](https://github.com/mozilla-mobile/android-components/pull/9395).

My hunch is if we update a-s to use the latest version of concept-fetch, then update a-c to use _that_ new version of a-s, we shouldn't see these errors any more.

**Comment by jonalmeida** [comment]
## Related bugs

Some possible fallout:
 - https://github.com/mozilla-mobile/fenix/issues/17575
 - https://github.com/mozilla-mobile/fenix/issues/17328

**Comment by jonalmeida** [comment]
I've put up a PR to upgrade the a-c version that app services compiles against: https://github.com/mozilla/application-services/pull/3830

Maybe we should consider backing out the breaking change in A-C for today to fix nightly if that is quicker.

**Comment by jonalmeida** [comment]
We decided offline to revert the A-C patch for today until we get an app services release next week.

**Comment by jonalmeida** [comment]
The next nightly should have a temporary fix with the backed out a-c changes.

**Comment by jonalmeida** [comment]
This is now fixed.
