### ISSUE TITLE
StorageStatsMetricsTest: debug(T) test failure - random test - java.lang.NullPointerException - at mozilla.telemetry.glean.private.MemoryDistributionMetricType.testGetValue(MemoryDistributionMetricType.kt:128)

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#17725]
debug(T) failed for the latest push to fenix master and a rerun failed for the same issue but during the execution of a different test:
* [Log 1](https://treeherder.mozilla.org/logviewer?job_id=328423550&repo=fenix)
* [Log 2](https://treeherder.mozilla.org/logviewer?job_id=328423786&repo=fenix)

```
  TEST: Updating SearchFragmentState from SearchState - shortcuts disabled
  FAILURE

java.lang.NullPointerException
	at mozilla.telemetry.glean.private.MemoryDistributionMetricType.testGetValue(MemoryDistributionMetricType.kt:128)
	at mozilla.telemetry.glean.private.MemoryDistributionMetricType.testGetValue$default(MemoryDistributionMetricType.kt:123)
	at org.mozilla.fenix.perf.StorageStatsMetricsTest.WHEN reporting THEN the values from the storageStats are accumulated(StorageStatsMetricsTest.kt:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jonalmeida** [comment]
I'm seeing this test failure consistently for [some PRs](https://github.com/mozilla-mobile/fenix/issues/17734) as well as one that [depends on a release](https://github.com/mozilla-mobile/fenix/pull/17732).

**Comment by pocmo** [comment]
Looking at `master` it appears to have started randomly? It also happened on `releases_v86.0.0`.

For me it seems to be failing consistently. But not with the `OutOfMemory` error mentioned above:

```
java.lang.NullPointerException
	at mozilla.telemetry.glean.private.MemoryDistributionMetricType.testGetValue(MemoryDistributionMetricType.kt:128)
	at mozilla.telemetry.glean.private.MemoryDistributionMetricType.testGetValue$default(MemoryDistributionMetricType.kt:123)
	at org.mozilla.fenix.perf.StorageStatsMetricsTest.WHEN reporting THEN the values from the storageStats are accumulated(StorageStatsMetricsTest.kt:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Robolectric] org.mozilla.fenix.perf.StorageStatsMetricsTest.WHEN reporting THEN the query duration is measured: sdk=28; resources=BINARY

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.mozilla.fenix.perf.StorageStatsMetricsTest.WHEN reporting THEN the query duration is measured(StorageStatsMetricsTest.kt:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Process finished with exit code 255
```

**Comment by mcomella** [comment]
I stepped through in the debugger and when we call `accumulate`, we take the branch acting like the SDK is disabled: https://github.com/mozilla/glean/blob/70444f6d184ed5ec1443fd8da6bedf2867630f26/glean-core/android/src/main/java/mozilla/telemetry/glean/private/MemoryDistributionMetricType.kt#L56-L58

So we never record the value and the test fails because the ping is missing from glean. (I think the `NullPointerException` error message is unintuitive. See https://bugzilla.mozilla.org/show_bug.cgi?id=1655112)

Since we didn't update this code, I'm guessing the glean SDK got upgraded, we changed some build configurations, or something.

To be explicit, **I'm not planning to own fixing the rest of this issue** as the issue is unrelated to any changes I've made.

**Comment by csadilek** [comment]
@mcomella Isn't this simply a problem of the metric being expired as of today: https://github.com/mozilla-mobile/fenix/pull/17704/

That would also explain why it started failing today without a change :)

/cc @pocmo @jonalmeida @Amejia481

**Comment by csadilek** [comment]
Verified that tests pass locally again after landing https://github.com/mozilla-mobile/fenix/pull/17704.

**Comment by mcomella** [comment]
> as well as one that [depends on a release](https://github.com/mozilla-mobile/fenix/pull/17732).

Do we need to uplift this change then, too? I'm guessing the next beta will go out but the probe will be expired there... 🤦
