### ISSUE TITLE
[Bug] Intermittent OOM crash when opening tab tray in PBM

### ISSUE THREAD

**Issue by hwinnemoe** [mozilla-mobile/fenix#17756]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

I have experienced OOM crashes when using PBM and opening up the tab tray with the tab tray view set to `Grid`. I can force these crashes by creating memory pressure with other Firefox instances and opening tabs as reported in #17234 and #4151, but it also happens without many or even single tabs in PBM every other day.

Looking at the crash signature, this crash seems to have become significantly more frequent with the production release of **Firefox 83.1.0** on Nov 18, 2020: https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.OutOfMemoryError%3A%20at%20dalvik.system.VMRuntime.newNonMovableArray%28Native%20Method%29&date=%3E%3D2020-11-02T11%3A55%3A00.000Z&date=%3C2021-02-02T11%3A55%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs.

Among other changes, this release includes the code changes for the tab tray grid view, although still deactivated behind a feature flag. My vague theory is that the memory consumption of the tab tray view has increased since then and memory pressure events do not get called quickly enough to vacate memory for the browser to avoid OOM crashes.

## Steps to reproduce
1. Set the tab tray view to `Grid` (may not be required)
1. Use the browser in PBM
2. Open the tab tray

### Expected behavior
The tab tray opens.

### Actual behavior
Intermittently, the browser crashes. See some examples crashes:

<details>
<summary>
<b>Crash report with Fenix code in strack trace</b>
</summary>

510527e8-2694-45d7-9151-021a2f9b58c1
java.lang.OutOfMemoryError: Failed to allocate a 1249932 byte allocation with 688600 free bytes and 672KB until OOM
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=d233f262e2ed48c4a100d1e64b826bbc
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-c29e6c61-6b8d-4ceb-b554-60d0b0210125
----
```
java.lang.OutOfMemoryError: Failed to allocate a 1249932 byte allocation with 688600 free bytes and 672KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2647)
	at android.content.res.Resources.loadDrawable(Resources.java:2552)
	at android.content.res.Resources.getDrawable(Resources.java:813)
	at android.content.Context.getDrawable(Context.java:458)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:1)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:9)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:1)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:1)
	at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:7)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:8)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:37)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:13)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:189)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)
	at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:1)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
</details>

<details>
<summary>
<b>Another crash report</b>
</summary>

466c17ee-972a-4a22-bb35-f85b49e22ea4
java.lang.OutOfMemoryError: Failed to allocate a 451596 byte allocation with 380672 free bytes and 371KB until OOM
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=7eb0eac9223547d39a24acf332b69dae
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-ca05f50f-6b8a-42ec-9bc1-d7e420210131
----
```
java.lang.OutOfMemoryError: Failed to allocate a 451596 byte allocation with 380672 free bytes and 371KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
	at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.draw(VectorDrawableCompat.java:27)
	at android.widget.ImageView.onDraw(ImageView.java:1246)
	at android.view.View.draw(View.java:16270)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16273)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.updateDisplayListIfDirty(View.java:15262)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16273)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16273)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16273)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:1)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:5)
	at android.view.View.draw(View.java:16273)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:17)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15262)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15262)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15262)
	at android.view.View.draw(View.java:16040)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16273)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2697)
	at android.view.View.updateDisplayListIfDirty(View.java:15267)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2619)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2438)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2071)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
</details>

### Device information

* Device vendor / model and Android version: Sony Xperia Z2, Android 6.0.1
* Firefox for Android version: Nightly 210201 17:01 (Build #2015790793)
AC: 73.0.20210131143119, 697903231
GV: 87.0a1-20210129095945
AS: 69.0.0

**Comment by hwinnemoe** [comment]
This does still happen, see https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.OutOfMemoryError%3A%20at%20dalvik.system.VMRuntime.newNonMovableArray%28Native%20Method%29&date=%3E%3D2021-02-04T00%3A00%3A00.000Z&date=%3C2021-08-04T00%3A00%3A00.000Z#graphs

About 400 daily crashes, which is less than 6 months ago, but this may just be due to users replacing their devices since the majority of crashes happen on API level 24 and lower.
