### ISSUE TITLE
Crash in [@ android.view.InflateException: at android.view.LayoutInflater.createView(LayoutInflater.java)]

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#17759]
Steps to reproduce (not sure the first 4 steps have anything to do with this):
1. Sign in with a valid account.
2. Have multiple tabs opened, I had 18.
3. Have several bookmarks.
4. uBlock Origin add-on is installed and enabled.
5. On a loaded page, insert about:crashcontent, then tap on "Restore page" button.
6. Go to tinyurl.com/y83pwn5x.
7. Open the Crash details and tap the Reports tab. Tap on "Show filters" from the upper right corner, then tap on any of the "From" calendar fields.

Crash report: https://crash-stats.mozilla.org/report/index/7da2a71e-e648-4f66-8c4b-a151b0210202

fb5ce766-8237-472a-980b-1d02835b3c28
android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=8cf6793f69984e6d88dcf917d334bb9f
* Socorro: https://crash-stats.mozilla.org/report/index/bp-7da2a71e-e648-4f66-8c4b-a151b0210202
Java stack trace:
```
android.view.InflateException
	at android.view.LayoutInflater.createView(LayoutInflater.java:640)
	at org.mozilla.fenix.perf.PerformanceInflater.onCreateView(PerformanceInflater.kt:2)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:135)
	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:103)
	at mozilla.components.feature.prompts.dialog.TimePickerDialogFragment.onCreateDialog(TimePickerDialogFragment.kt:23)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:4)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:28)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by mcomella** [comment]
Looking at socorro, this crash only occurs on API 21-22. The most common device manufacturer that crashes is Samsung (but that may just be because more users use Samsung?).

**Comment by MarcLeclair** [comment]
Hey @softvision-miralobontiu, I tested with the following:

- G5+ with API 26 -> got no crash
- Created a test to test an XML layout inflation of `TimePicker` and it worked through fenix (so the test passed)
- Used an Emulator with API 21 ( more specifically Pixel 3A with 4GB ram and 10GB disk space) x86 -> no crash.
If the crash still exist, it might be related to samsung only I'm starting to think.

**Comment by softvision-miralobontiu** [comment]
I tried to reproduce the crash on the Beta 86.0.0-beta.4 build with the same device, Samsung Galaxy Tab A6 (Android 5.1.1).
I will close this issue.

**Comment by lobontiumira** [comment]
I'll reopen the issue since I just got the same crash on Beta 87.0.0-beta.5 with the same device Samsung Galaxy Tab A6 (Android 5.1.1).
The steps were:
1. Sign in with a valid account.
2. Have multiple tabs opened, I had 27.
3. On a loaded page, insert about:crashcontent, then tap on "Restore page" button.
4. Go to tinyurl.com/y83pwn5x.
5. Open the Crash details and tap the Reports tab. Tap on "Show filters" from the upper right corner, then tap on any of the "From" calendar fields.

3e780fc0-c0fe-494e-a5f7-9a96af7453dd
android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=7bcd2db2158a48fc99ffd9bb6c8a9b4f
* Socorro: https://crash-stats.mozilla.org/report/index/bp-09d59937-7554-4290-bc36-6bccd0210312
----
```
android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
at android.view.LayoutInflater.createView(LayoutInflater.java:640)
at org.mozilla.fenix.perf.PerformanceInflater.onCreateView(PerformanceInflater.kt:2)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)
at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
at android.app.TimePickerDialog.<init>(TimePickerDialog.java:135)
at android.app.TimePickerDialog.<init>(TimePickerDialog.java:103)
at mozilla.components.feature.prompts.dialog.TimePickerDialogFragment.onCreateDialog(TimePickerDialogFragment.kt:23)
at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:4)
at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:28)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:51)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6939)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:614)
... 29 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.widget.TimePicker$TimePickerDelegate.onRtlPropertiesChanged(int)' on a null object reference
at android.widget.TimePicker.onRtlPropertiesChanged(TimePicker.java:193)
at android.view.View.resolvePadding(View.java:14637)
at android.view.ViewGroup.resolvePadding(ViewGroup.java:6455)
at android.view.View.initializeScrollbarsInternal(View.java:5019)
at android.view.View.<init>(View.java:4438)
at android.view.ViewGroup.<init>(ViewGroup.java:513)
at android.widget.FrameLayout.<init>(FrameLayout.java:115)
at android.widget.TimePicker.<init>(TimePicker.java:84)
at android.widget.TimePicker.<init>(TimePicker.java:80)
at android.widget.TimePicker.<init>(TimePicker.java:76)
... 32 more

```

**Comment by st3fan** [comment]
@mcomella why is `at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)` in that stack trace?

**Comment by mcomella** [comment]
> @mcomella why is `at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)` in that stack trace?

@st3fan We wrap the system's `LayoutInflater` in order to monitor it. Specifically, inflation is a slow operation so we're counting the number of inflations we do on start up and, when the count increases, we fail a test so devs will hopefully rethink adding an additional inflation.

By necessity, it's a hacky implementation ([source](https://searchfox.org/mozilla-mobile/rev/1512a8bcc81fce803854e1044e5d11351afd3ea1/fenix/app/src/main/java/org/mozilla/fenix/perf/PerformanceInflater.kt#45-70)) so I can see why this went wrong – we'll look into it.

**Comment by MarcLeclair** [comment]
QA needed: I think the crash should be fix but I Don't have any API 21/ 22 devices to test this on.

**Comment by lobontiumira** [comment]
I was not able to reproduce the crash on the 4/9 Nightly build with Samsung Galaxy Tab A6 (Android 5.1.1).
