### ISSUE TITLE
[Bug] Crash org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#17762]
**This is a high priority for us** because I believe it's causing some of our perf tests to permafail.

We had a failure in a our browsertime performance tests for the latest nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1690230. The log says:
```
02-02 06:06:09.245  8150  8292 E AndroidRuntime: FATAL EXCEPTION: pool-32-thread-1
02-02 06:06:09.245  8150  8292 E AndroidRuntime: Process: org.mozilla.fenix, PID: 8150
02-02 06:06:09.245  8150  8292 E AndroidRuntime: org.mozilla.experiments.nimbus.ErrorException$ResponseError: Error in network response: 
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at org.mozilla.experiments.nimbus.Error.intoException(nimbus.kt:13)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at org.mozilla.experiments.nimbus.NimbusClient.fetchExperiments(nimbus.kt:7)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at mozilla.components.service.nimbus.Nimbus.fetchExperimentsOnThisThread(Nimbus.kt:1)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at mozilla.components.service.nimbus.Nimbus.access$fetchExperimentsOnThisThread(Nimbus.kt:1)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at mozilla.components.service.nimbus.Nimbus$fetchExperiments$1.invokeSuspend(Nimbus.kt:2)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-02 06:06:09.245  8150  8292 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
02-02 06:06:09.259  1541  1967 I ActivityManager: Start proc 8381:org.mozilla.fenix:mozilla.components.lib.crash.CrashReporter/u0a119 for activity org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity
```

In [the code where it crashes](https://searchfox.org/mozilla-mobile/rev/54f068d545436c92e1ca0d2004d99891a65eda3b/android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt#264-271):
```
    private fun fetchExperimentsOnThisThread() {
        try {
            nimbus.fetchExperiments()
            notifyObservers { onExperimentsFetched() }
        } catch (e: ErrorException.RequestError) {
            logger.info("Error fetching experiments from endpoint: $e")
        }
    }
```

We're only catching `RequestError`s, but not `ResponseError`s. I speculate browsertime hit this (in permafail?) because it might only replays specific network requests in order to make results consistent.

To reproduce this locally, you'd have to cause a nimbus endpoint to not return or to return bad results – maybe with MockWebServer?

* Device vendor / model and Android version: Moto G5
* Firefox for Android version: Nightly 210202

**Comment by pocmo** [comment]
A new Nightly just went out and unfortunately we weren't able to stop it.
