### ISSUE TITLE
[Bug] Firefox usually exit unexpectedly (without any crash report), It seems usually happened when I switching tabs. 

### ISSUE THREAD

**Issue by 0x391F** [mozilla-mobile/fenix#17908]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
It seems usually happened when I switching tabs. 
### Device information

* Device vendor / model and Android version: 10
* Firefox for Android version: 85.1.2 (go to Settings -> About Firefox)

**Comment by Amejia481** [comment]
Would you mind checking in the About Firefox -> Crashes ([steps](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information)) section?

**Comment by 0x391F** [comment]
> Would you mind checking in the About Firefox -> Crashes ([steps](https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information)) section?

No, there is nothing.

**Comment by Amejia481** [comment]
Which is the manufacture and model of your device?

**Comment by 0x391F** [comment]
It's Huawei Honor 20S.

**Comment by 0x391F** [comment]
1eea53be-46f2-4979-a783-081afe48aa33
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-8df2cd7c-880c-495d-ba3e-547b50210221
----
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:5)
	at mozilla.components.feature.sitepermissions.SitePermissionsFeature.onContentPermissionRequested$feature_sitepermissions_release(SitePermissionsFeature.kt:26)
	at mozilla.components.feature.sitepermissions.SitePermissionsFeature.onContentPermissionRequested$feature_sitepermissions_release$default(SitePermissionsFeature.kt:2)
	at mozilla.components.feature.sitepermissions.SitePermissionsFeature$setupPermissionRequestsCollector$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:21)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:7)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:3)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:6)
	at mozilla.components.feature.sitepermissions.SitePermissionsFeature$setupPermissionRequestsCollector$1$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8347)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by 0x391F** [comment]
> 1eea53be-46f2-4979-a783-081afe48aa33
> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
> 
>     * Socorro: https://crash-stats.mozilla.org/report/index/bp-8df2cd7c-880c-495d-ba3e-547b50210221
> 
> 
> java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
> at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:6)
> at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:12)
> at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
> at androidx.fragment.app.DialogFragment.show(DialogFragment.java:5)
> at mozilla.components.feature.sitepermissions.SitePermissionsFeature.onContentPermissionRequested$feature_sitepermissions_release(SitePermissionsFeature.kt:26)
> at mozilla.components.feature.sitepermissions.SitePermissionsFeature.onContentPermissionRequested$feature_sitepermissions_release$default(SitePermissionsFeature.kt:2)
> at mozilla.components.feature.sitepermissions.SitePermissionsFeature$setupPermissionRequestsCollector$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:21)
> at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:7)
> at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:3)
> at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:6)
> at mozilla.components.feature.sitepermissions.SitePermissionsFeature$setupPermissionRequestsCollector$1$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:8)
> at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
> at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
> at android.os.Handler.handleCallback(Handler.java:900)
> at android.os.Handler.dispatchMessage(Handler.java:103)
> at android.os.Looper.loop(Looper.java:219)
> at android.app.ActivityThread.main(ActivityThread.java:8347)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

_________________________________________
The most recent crash.

**Comment by mariansima** [comment]
Could not reproduce this issue on Samsung A8 SM-A530F Android 9 Firefox 93.0a1 2021-08-29
