### ISSUE TITLE
[Bug] Crashing 5 seconds after restart on Leagoo Leapad 10S

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/fenix#17945]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

From https://www.reddit.com/r/firefox/comments/lbed7s/forced_shut_down_after_5_seconds/

## Steps to reproduce

Start Firefox.

### Expected behavior

Stable Firefox, like Firefox 84. 

### Actual behavior

Crashes shortly after startup.

### Device information

* Device vendor / model and Android version: Leagoo Leapad 10S. Android 7
* Firefox for Android version: v85.1.1, v85.1.2

Log: 
[gistfile1.txt](https://github.com/mozilla-mobile/fenix/files/5956878/gistfile1.txt)

**Comment by kbrosnan** [comment]
```

``

**Comment by kbrosnan** [comment]
```
02-05 16:10:07.291 V/SQLiteCursor( 9150): java.lang.Throwable: stacktrace
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:117)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase$1.newCursor(FrameworkSQLiteDatabase.java:2)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:52)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1321)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:4)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:1)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:1)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:2)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:1)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-05 16:10:07.291 V/SQLiteCursor( 9150):       at java.lang.Thread.run(Thread.java:818)
02-05 16:10:07.292 I/CursorWindowStats( 9150): Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
02-05 16:10:07.292 D/SQLiteCursor( 9150): received count(*) from native_fill_window: 1
02-05 16:10:07.295 V/SQLiteCursor( 9150): Cursor close object=232254281
02-05 16:10:07.297 V/SQLiteCursor( 9150): Cursor open object=34970702
02-05 16:10:07.297 V/SQLiteCursor( 9150): java.lang.Throwable: stacktrace
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:117)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase$1.newCursor(FrameworkSQLiteDatabase.java:2)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:52)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1321)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:4)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:4)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:266)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:2)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:1)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-05 16:10:07.297 V/SQLiteCursor( 9150):       at java.lang.Thread.run(Thread.java:818)
```

The second part of the stacktrace repeats many times

**Comment by SaberAkiyama** [comment]
Update on v85.1.3: Same as a issue.
