### ISSUE TITLE
[Bug] Intermittent UI test failure - ContextMenusTest - verifyContextOpenLinkNewTab

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#17962]
• Master  2/10 :

► Flaky 1x verifyContextOpenLinkNewTab

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6056259136757101194/executions/bs.c2f701b59eab0052/testcases/3/test-cases

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifySnackBarText(BrowserRobot.kt:109)
at org.mozilla.fenix.ui.ContextMenusTest$verifyContextOpenLinkNewTab$2.invoke(ContextMenusTest.kt:68)
at org.mozilla.fenix.ui.ContextMenusTest$verifyContextOpenLinkNewTab$2.invoke(ContextMenusTest.kt:35)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:121)
at org.mozilla.fenix.ui.ContextMenusTest.verifyContextOpenLinkNewTab(ContextMenusTest.kt:63)

**Comment by sv-ohorvath** [comment]
Disabled and tracked now in https://github.com/mozilla-mobile/fenix/issues/18421
