### ISSUE TITLE
Intermittent UI test failure - HistoryTest.openHistoryInNewTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18003]
### Firebase Test Run:
Flaky, only failed 1 out of 2 runs: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7958247659561093789/executions/bs.e146aed402474d60/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openThreeDotMenu(HomeScreenRobot.kt:312)
at org.mozilla.fenix.ui.HistoryTest.openHistoryInNewTabTest(HistoryTest.kt:259)`
### Build: 
Master 2/12

From the video it appears that it failed to close the tab before trying to access the 3 dot menu from the homescreen. Similar to https://github.com/mozilla-mobile/fenix/issues/17484

**Comment by sv-ohorvath** [comment]
Potential fix landed in https://github.com/mozilla-mobile/fenix/commit/23cc3522aa1e5b4a85ae708ac5c4c2f79e7922b0. Closing the issue. If it fails again we can reopen it.
