### ISSUE TITLE
Intermittent UI test failure - StrictEnhancedTrackingProtectionTest.testStrictVisitProtectionSheet

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18012]
### Firebase Test Run:
Flaky, failed 1/2 tries:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7630516617979371856/executions/bs.213b607725305fb6/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:118)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitProtectionSheet(StrictEnhancedTrackingProtectionTest.kt:116)`
### Build: 
Debug 2/16

The session idling resources timed put waiting for the ETP onboarding pop-up.
Maybe related: https://github.com/mozilla-mobile/fenix/issues/14005

**Comment by sv-ohorvath** [comment]
Actually it has the same error as  #14005, closing as duplicate.
