### ISSUE TITLE
Intermittent UI test failure - BookmarksTest - openSelectionInNewTabTest

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#18051]
• Master 2/17 

► Flaky 1x openSelectionInNewTabTest

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7300464095579270765/executions/bs.b066062880ec1aa7/testcases/1/test-cases

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:103)
at org.mozilla.fenix.ui.robots.BrowserRobot.createBookmark(BrowserRobot.kt:309)
at org.mozilla.fenix.ui.BookmarksTest$openSelectionInNewTabTest$1.invoke(BookmarksTest.kt:327)
at org.mozilla.fenix.ui.BookmarksTest$openSelectionInNewTabTest$1.invoke(BookmarksTest.kt:34)
at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:487)
at org.mozilla.fenix.ui.BookmarksTest.openSelectionInNewTabTest(BookmarksTest.kt:326)
at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by sv-ohorvath** [comment]
From the video it looks like after clicking the homescreen nav bar, the keyboard wasn't triggered and the expected view (mozac_browser_toolbar_edit_url_view) didn't appear, causing the test to timeout. 
Found a bug that might be related: https://github.com/mozilla-mobile/fenix/issues/15526

**Comment by sv-ohorvath** [comment]
This was re-enabled/mistakenly labeled as disabled. Hasn't failed in 3 months and had unrelated issues, so closing it for now.
