### ISSUE TITLE
FNX-5256 ⁃ [Bug] History menu crashes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1811]
## Steps to reproduce
1. Go to the library>history menu.
    1. Expected behavior
History list is displayed.
    1. Actual behavior
App crashes.
    1. Device information

* Android device: HTC 10 (Android 8), HTC Desire 820 (Android 6.0.1)
* Fenix version: Debug build 4/19

**Comment by cadeyrn** [comment]
```
2019-04-19 18:42:50.308 17929-17950/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.mozilla.fenix.debug, PID: 17929
    java.lang.NoSuchMethodError: No virtual method getVisitInfos(JJ)Ljava/util/List; in class Lmozilla/appservices/places/PlacesReaderConnection; or its super classes (declaration of 'mozilla.appservices.places.PlacesReaderConnection' appears in /data/app/org.mozilla.fenix.debug-JpcSNAhq9_umR3vWKY08wA==/split_lib_dependencies_apk.apk:classes2.dex)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getDetailedVisits$2.invokeSuspend(PlacesHistoryStorage.kt:64)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage$getDetailedVisits$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getDetailedVisits$suspendImpl(PlacesHistoryStorage.kt:63)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getDetailedVisits(Unknown Source:0)
        at mozilla.components.concept.storage.HistoryStorage$DefaultImpls.getDetailedVisits$default(HistoryStorage.kt:46)
        at org.mozilla.fenix.library.history.HistoryFragment.reloadData(HistoryFragment.kt:148)
        at org.mozilla.fenix.library.history.HistoryFragment$onViewCreated$1.invokeSuspend(HistoryFragment.kt:86)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:234)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by colintheshots** [comment]
This regression was caused by a change to Application Services. A fix is coming in Android Components.

**Comment by bsurd** [comment]
This has been verified in the latest build on a Nexus 5 and Galaxy S8. Accessing history no longer crashes the app.
