### ISSUE TITLE
[Crash] java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 257902492 Other activity: HomeActivity hashcode 238238592

### ISSUE THREAD

**Issue by hkaancaliskan** [mozilla-mobile/fenix#18127]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=35999a4164e34b039042abe8d65bc398
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-96b8beda-69f7-4c9b-b8a6-b1dee0210223

```
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 257902492 Other activity: HomeActivity hashcode 238238592
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:9)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 15 more
```
## Steps to reproduce
1- Open a home screen shortcut (for me GitHub)
2- then quickly press back button to close firefox
3- then press another home screen shortcut (for me youtube)
4- crash :(

### Device information

* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 2/22 nightly

**Comment by Mugurell** [comment]
@hakkikaancaliskan Does this still reproduces for you in the current Nightly?
I tried now your STRs and for me everything works as expected.

**Comment by hakkikaancaliskan** [comment]
@Mugurell i think you should check crash stats because STR is not 100% reproducible.
This crash happened again 6 days ago on beta without this STR.

```
ce655f4a-82b6-4e47-9518-8527f8d63e16
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 146563967 Other activity: HomeActivity hashcode 36223629
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=97692d22c04845c8aa5194824fb0e175
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-b222536b-a7ab-4ce8-b868-752800210417
----
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 146563967 Other activity: HomeActivity hashcode 36223629
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:9)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 15 more

```

**Comment by hakkikaancaliskan** [comment]
@Mugurell I'm also able to reproduce on nightly with both cold and warm startup with same STR. And looks like it's %100 reproducible.
```
1df4b641-cadc-4d70-aa81-cafa3f716512
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 7723227 Other activity: HomeActivity hashcode 232903315
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=0c59dcfe3f7246ebae72f876141e700d
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-8ebf56a0-2a23-4a9c-bf58-765da0210428
----
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 7723227 Other activity: HomeActivity hashcode 232903315
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:9)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 15 more

```
