### ISSUE TITLE
Crash in [@ mozilla.appservices.places.UrlParseFailed: at mozilla.appservices.places.RustError.intoException(RustError.kt:13)]

### ISSUE THREAD

**Issue by test491** [mozilla-mobile/fenix#18147]
Crash report: https://crash-stats.mozilla.org/report/index/d9d584a5-d368-4ebd-9e76-629860210224

Java stack trace:
```
mozilla.appservices.places.UrlParseFailed
	at mozilla.appservices.places.RustError.intoException(RustError.kt:13)
	at mozilla.appservices.places.PlacesWriterConnection.doInsert(PlacesConnection.kt:18)
	at mozilla.appservices.places.PlacesWriterConnection.createBookmarkItem(PlacesConnection.kt:6)
	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$addItem$2.invokeSuspend(PlacesBookmarksStorage.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
version: 86.1.1

* version: 87.0.0-beta.1 (Build #2015795065) AC: 73.0.0, 69a800e47 GV: 87.0-20210222154334 AS: 71.0.0

crash report: https://crash-stats.mozilla.org/report/index/3b19f203-f3be-4caa-bb70-f9ae60210224

* version: Nightly 210224 (Build #2015795113) AC: 73.0.20210223143117, 05f3e3cc7 GV: 87.0a1-20210222084406 AS: 71.0.0

crash report: https://crash-stats.mozilla.org/report/index/bp-a554662d-6ff5-4a3b-977c-046bf0210224

trying to reproduce #14331 

str:
* Open https://1234.56.78.90 - as expected, Fenix will show a page saying it can't be loaded.
* Note that the "star" button is enabled - tap it to bookmark the page.
* Fenix crashes

**Comment by mariansima** [comment]
This issue still occurs on Samsung A8 SM-A530F Android 9 Nightly 93.0a1 2021-08-30

**Comment by SoftVision-LorandJanos** [comment]
This issue is reproducible on the latest Release (98.1.0RC).
However it is not reproducible with the:
- latest Beta (98.0.0-beta4).
- latest Nightly 99.0a1 (2022-03-02).
Device used: Oppo Reno 6 (Android 11).
Closing the ticket as fixed.
