### ISSUE TITLE
Crash in [@ java.lang.IllegalArgumentException: at mozilla.components.feature.prompts.PromptFeature$onConfirm$1.invoke(PromptFeature.kt:39)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#18155]
Crash report: https://crash-stats.mozilla.org/report/index/3bcca8f8-1b14-40c8-80e9-642070210224

Java stack trace:
```
java.lang.IllegalArgumentException
	at mozilla.components.feature.prompts.PromptFeature$onConfirm$1.invoke(PromptFeature.kt:39)
	at androidx.core.app.AppOpsManagerCompat.consumePromptFrom(AppOpsManagerCompat.java:5)
	at mozilla.components.feature.prompts.PromptFeature.onConfirm(PromptFeature.kt:1)
	at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment.access$onPositiveClickAction(SaveLoginDialogFragment.kt:10)
	at mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment$onViewCreated$1.onClick(SaveLoginDialogFragment.kt:1)
	at android.view.View.performClick(View.java:6724)
	at android.view.View.performClickInternal(View.java:6682)
	at android.view.View.access$3400(View.java:797)
	at android.view.View$PerformClick.run(View.java:26479)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:242)
	at android.app.ActivityThread.main(ActivityThread.java:7227)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
```

**Comment by kbrosnan** [comment]
This is showing up as a top crash in release. Looks to do with saving a new user name/password

Frame | Module | Function | Source | In app?
-- | -- | -- | -- | --
0 | mozilla.components.feature.prompts.PromptFeature$onConfirm$1 | invoke | PromptFeature.kt:39 | True
1 | androidx.core.app.AppOpsManagerCompat | consumePromptFrom | AppOpsManagerCompat.java:5 | True
2 | mozilla.components.feature.prompts.PromptFeature | onConfirm | PromptFeature.kt:1 | True
3 | mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment | access$onPositiveClickAction | SaveLoginDialogFragment.kt:10 | True
4 | mozilla.components.feature.prompts.dialog.SaveLoginDialogFragment$onViewCreated$1 | onClick | SaveLoginDialogFragment.kt:1 | True

**Comment by kbrosnan** [comment]
All but one of these crashes are Chinese users. Might be something with the China build?
