### ISSUE TITLE
Crash in [@ java.lang.SecurityException: at android.os.Parcel.createException(Parcel.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#18238]
Crash report: https://crash-stats.mozilla.org/report/index/a1035378-f563-4bce-bafa-8a7ff0210301

Java stack trace:
```
java.lang.SecurityException
	at android.os.Parcel.createException(Parcel.java:1966)
	at android.os.Parcel.readException(Parcel.java:1934)
	at android.os.Parcel.readException(Parcel.java:1884)
	at android.app.IActivityManager$Stub$Proxy.reportActivityFullyDrawn(IActivityManager.java:7318)
	at android.app.Activity.reportFullyDrawn(Activity.java:2092)
	at org.mozilla.fenix.perf.StartupReportFullyDrawn$attachReportFullyDrawn$$inlined$doOnPreDraw$1.run(View.kt:1)
	at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:2)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:991)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3019)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

This crash is an aggregation of several stacks with similar interactions with external apps.

**Comment by kbrosnan** [comment]
bz-1694983

This crash has some interesting raw Java stack traces.
```
java.lang.SecurityException: UID 10197 does not have permission to content://com.facebook.katana.securefileprovider/temp/.REMOVED.png [user 0] at 
android.os.Parcel.createException(Parcel.java:1966) at 
android.os.Parcel.readException(Parcel.java:1934) at
android.os.Parcel.readException(Parcel.java:1884) at 
android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:225) at 
android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:170) at 
org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2) at 
org.mozilla.fenix.search.SearchDialogFragment$onViewCreated$6.invoke(SearchDialogFragment.kt:12) at
mozilla.components.lib.state.ext.FragmentKt$consumeFrom$1.invokeSuspend(Fragment.kt:8)...
```

```
java.lang.SecurityException: Unsupported path /storage/emulated/999/Download/geph-android-4.1.7.apk at
android.os.Parcel.createException(Parcel.java:2074) at
android.os.Parcel.readException(Parcel.java:2042) at 
android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188) at 
android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140) at 
android.content.ContentProviderProxy.insert(ContentProviderNative.java:481) at 
android.content.ContentResolver.insert(ContentResolver.java:1844) at 
android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1904) at 
android.app.DownloadManager.addCompletedDownload(DownloadManager.java:1854) at...
```

```
java.lang.SecurityException: UID 10225 does not have permission to content://com.microsoft.office.onenote/clip [user 150] at
android.os.Parcel.createException(Parcel.java:1966) at android.os.Parcel.readException(Parcel.java:1934) at 
android.os.Parcel.readException(Parcel.java:1884) at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:225) at 
android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:170) at 
org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2) at
org.mozilla.fenix.search.SearchDialogFragment$onViewCreated$6.invoke(SearchDialogFragment.kt:12) at... 
```
are some examples. This might be AC/Fenix issue?

**Comment by Mugurell** [comment]
@kbrosnan There seem to be many different stacktraces and causes for these `SecurityException`s.
Should this ticket be a meta from which to branch out new tickets for individual, specific issues?
There seems to be quite a lot of situations that can lead to this so this would mean a lot of work.
But I can't find a way to get an ordered list of the most encountered stacktraces for the `SecurityException` signature to know which underlying issue to prioritize.

**Comment by rocketsroger** [comment]
For the crash  https://crash-stats.mozilla.org/report/index/a1035378-f563-4bce-bafa-8a7ff0210301  It was fixed last year July 20th 2021 (Assume merged in build on the 21st).  https://github.com/mozilla-mobile/android-components/commit/9f7ae0fe7a9b2515689ae0b6b753a7e14eaea0db.  Going through the crash reports, the build IDs are all before 2020 July 20th.  This issue has been resolved.

**Comment by rocketsroger** [comment]
Second issue https://bugzilla.mozilla.org/show_bug.cgi?id=1694983 is due to GV trying to start an activity with an intent that causes SecurityException.  Adding a try catch in A-C to make sure that it doesn't crash Fenix.

**Comment by kbrosnan** [comment]
@rocketsroger the Bugzilla bug is not being tracked by GV. If there is specific work for that team to do please open a new bug explaining the problem.

**Comment by rocketsroger** [comment]
Sure, I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1699723 to track it.  I'll close this issue since there's nothing else app side can do for the two SecurityException crash listed here.

**Comment by marta279** [comment]
ayuda para mi software
