### ISSUE TITLE
Crash: java.lang.IllegalThreadStateException: Must have a Handler

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#18399]
Nightly 
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10570831/

```
java.lang.IllegalThreadStateException: Must have a Handler
    at org.mozilla.geckoview.GeckoResult.then(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.map(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.map(GeckoResult.java:1)
    at org.mozilla.geckoview.WebExtensionController.updateTab(WebExtensionController.java:9)
    at org.mozilla.geckoview.WebExtensionController.lambda$handleMessage$1$WebExtensionController(WebExtensionController.java:4)
    at org.mozilla.geckoview.-$$Lambda$WebExtensionController$cy4tUfKhvCERfC7glVoFTwHAvqU.accept
    at org.mozilla.geckoview.GeckoResult.lambda$accept$2(GeckoResult.java:1)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$jOTMkpkhFSpBCw69vbWxDq7m7Tw.onValue
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4$GeckoResult(GeckoResult.java:2)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$-hYJKiV7OmgfRN8NZFvKg9ij7nk.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7562)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

org.mozilla.geckoview.UncaughtException: java.lang.IllegalThreadStateException: Must have a Handler
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4$GeckoResult(GeckoResult.java:10)
    at org.mozilla.geckoview.-$$Lambda$GeckoResult$-hYJKiV7OmgfRN8NZFvKg9ij7nk.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7562)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-9XJ](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10570831/?referrer=github_plugin)
