### ISSUE TITLE
RemoteServiceException: Bad notification posted from package org.mozilla.fenix: Couldn't inflate contentViewsjava.lang.Il...

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#18400]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6022536/?referrer=github_plugin

```
RemoteServiceException: Bad notification posted from package org.mozilla.fenix: Couldn't inflate contentViewsjava.lang.IllegalArgumentException: The given region must intersect with the Bitmap's dimensions.
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6673)
    at java.lang.reflect.Method.invoke(Method.java)
...
(2 additional frame(s) were not displayed)

Bad notification posted from package org.mozilla.fenix: Couldn't inflate contentViewsjava.lang.IllegalArgumentException: The given region must intersect with the Bitmap's dimensions.
```

**Comment by rocketsroger** [comment]
related GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1697255

**Comment by rocketsroger** [comment]
I will put in a workaround until GV have a chance to investigate the issue.

**Comment by rocketsroger** [comment]
Confirmed from my testing this is fixed in Nightly.  Please verify

**Comment by ebalazs-sv** [comment]
This issue is verified as fixed with the steps from https://github.com/mozilla-mobile/fenix/issues/18394.
The app does not crash when following the steps.
I will close this issue and remove the qa:needed label.
