### ISSUE TITLE
Crash - IllegalStateException: Display already acquired

### ISSUE THREAD

**Issue by Tothepablo** [mozilla-mobile/fenix#18670]
Crash report: https://crash-stats.mozilla.org/report/index/5e70c56c-6e17-4ec1-9bd4-2d59f0210204

Java stack trace:
```
java.lang.IllegalStateException
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:9)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
```

**Comment by Mugurell** [comment]
Thank you for the report @Tothepablo !

Will close this in favor of https://github.com/mozilla-mobile/android-components/issues/9081

But if you have any steps to reproduce, please post them here, it would us a lot!
