### ISSUE TITLE
Crash in [@ java.io.IOException: at com.jakewharton.disklrucache.Util.deleteContents(Util.java)]

### ISSUE THREAD

**Issue by Tothepablo** [mozilla-mobile/fenix#18671]
Crash report: https://crash-stats.mozilla.org/report/index/a31496b8-7b44-420c-ba74-e38920201114

Java stack trace:
```
java.io.IOException
	at com.jakewharton.disklrucache.Util.deleteContents(Util.java:7)
	at com.jakewharton.disklrucache.DiskLruCache.delete(DiskLruCache.java:2)
	at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.clear$browser_thumbnails_release(ThumbnailDiskCache.kt:2)
	at mozilla.components.browser.thumbnails.storage.ThumbnailStorage$clearThumbnails$1.invokeSuspend(ThumbnailStorage.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by kbrosnan** [comment]
This crash was recorded on v82. From the data in crash-stats it more or less does not happen on 86+. Is this happening on a current [release or nightly](https://github.com/mozilla-mobile/fenix/wiki#download)?

**Comment by mcarare** [comment]
This was fixed in https://github.com/mozilla-mobile/android-components/pull/9146.

**Comment by kbrosnan** [comment]
Thanks mcarare. Going to close this as works for me with current versions.
