### ISSUE TITLE
Permanent debug(screenshots-x86): org.mozilla.fenix.screenshots.DefaultHomeScreenTest - showDefaultHomeScreen androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with res-name that is "fxa_sign_in_button"

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#18680]
@Mugurell Could this be from #18594? The test only runs once per week and failed 2/2 runs today.

### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6835870086829229561/executions/bs.1172f9e174e51aea/testcases/1/errors
### Stacktrace:
```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with res-name that is "fxa_sign_in_button"

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14033f
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1080, height=1788, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@f345713, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-->ViewStub{id=16908682, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@7830d50, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@cbb3b49, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=66.0, child-count=1}
|
+--->FitWindowsLinearLayout{id=2131361869, res-name=action_bar_root, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@483516f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---->ViewStubCompat{id=2131361933, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@993ae7c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@2f34305, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+----->LinearLayout{id=2131362779, res-name=rootContainer, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@31d958b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+------>ViewStub{id=2131362630, res-name=navigationToolbarStub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@bab3668, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------>FragmentContainerView{id=2131362173, res-name=container, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eea0a81, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+------->CoordinatorLayout{id=2131362391, res-name=homeLayout, visibility=VISIBLE, width=1080, height=1722, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@99ff726, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+-------->AppBarLayout{id=2131362388, res-name=homeAppBar, visibility=VISIBLE, width=1080, height=248, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@3cdff67, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+--------->CollapsingToolbarLayout{id=-1, visibility=VISIBLE, width=1080, height=248, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.AppBarLayout$LayoutParams@3315114, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---------->AppCompatImageButton{id=2131362722, res-name=privateBrowsingButton, desc=Enable private browsing, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@c2bcdbd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=915.0, y=39.0}
|
+---------->AppCompatImageView{id=2131363111, res-name=wordmark, desc=Firefox Preview, visibility=VISIBLE, width=581, height=110, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=com.google.android.material.appbar.CollapsingToolbarLayout$LayoutParams@4845fb2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=50.0}
|
+-------->RecyclerView{id=2131362860, res-name=sessionControlRecyclerView, visibility=VISIBLE, width=1080, height=1590, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@7312b03, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=248.0, child-count=3}
|
+--------->FrameLayout{id=2131362666, res-name=onboarding_header, visibility=VISIBLE, width=992, height=78, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@25c6a80, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=44.0, child-count=1}
|
+---------->AppCompatTextView{id=2131362376, res-name=header_text, visibility=VISIBLE, width=992, height=78, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@8cc88b9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Welcome to Firefox Preview!, input-type=0, ime-target=false, has-links=false}
|
+--------->ConstraintLayout{id=2131362665, res-name=onboarding_card, visibility=VISIBLE, width=992, height=831, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@8d4c4fe, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=144.0, child-count=11}
|
+---------->AppCompatTextView{id=2131362376, res-name=header_text, visibility=VISIBLE, width=548, height=103, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@111745f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Choose your theme, input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatTextView{id=2131362238, res-name=description_text, visibility=VISIBLE, width=992, height=99, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@65daeac, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=147.0, text=Save some battery and your eyesight with dark mode., input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatTextView{id=2131362483, res-name=light_theme_description, visibility=VISIBLE, width=232, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@623f775, tag=null, root-is-layout-requested=false, has-input-connection=false, x=152.0, y=533.0, text=Light theme, input-type=0, ime-target=false, has-links=false}
|
+---------->OnboardingRadioButton{id=2131363011, res-name=theme_light_radio_button, desc=Light theme, visibility=VISIBLE, width=88, height=88, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@c34330a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=61.70625, y=267.95, text=, input-type=0, ime-target=true, has-links=false, is-checked=false}
|
+---------->AppCompatImageView{id=2131363010, res-name=theme_light_image, desc=Light theme, visibility=VISIBLE, width=375, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@d82f77b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=81.0, y=290.0}
|
+---------->OnboardingRadioButton{id=2131363009, res-name=theme_dark_radio_button, desc=Dark theme, visibility=VISIBLE, width=88, height=88, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@c4d0998, tag=null, root-is-layout-requested=false, has-input-connection=false, x=516.70624, y=267.95, text=, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---------->AppCompatImageView{id=2131363008, res-name=theme_dark_image, desc=Dark theme, visibility=VISIBLE, width=375, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@94995f1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=536.0, y=290.0}
|
+---------->AppCompatTextView{id=2131362210, res-name=dark_theme_title, visibility=VISIBLE, width=224, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@96a75d6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=612.0, y=533.0, text=Dark theme, input-type=0, ime-target=false, has-links=false}
|
+---------->View{id=2131362266, res-name=divider, visibility=VISIBLE, width=986, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@bbf9057, tag=null, root-is-layout-requested=false, has-input-connection=false, x=3.0, y=636.0}
|
+---------->View{id=2131362139, res-name=clickable_region_automatic, desc=Automatic Adapts to your device settings, visibility=VISIBLE, width=992, height=195, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@8d52744, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=636.0}
|
+---------->OnboardingRadioButton{id=2131363007, res-name=theme_automatic_radio_button, desc=Automatic, visibility=VISIBLE, width=617, height=104, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@df01962, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=683.0, text=Automatic
Adapts to your device settings, input-type=0, ime-target=false, has-links=false, is-checked=true}
|
+--------->ConstraintLayout{id=2131362665, res-name=onboarding_card, visibility=VISIBLE, width=992, height=636, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.recyclerview.widget.RecyclerView$LayoutParams@ac2daf3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=44.0, y=1019.0, child-count=8}
|
+---------->AppCompatTextView{id=2131362376, res-name=header_text, visibility=VISIBLE, width=753, height=103, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e9f73b0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=44.0, text=Pick your toolbar placement, input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatTextView{id=2131362238, res-name=description_text, visibility=VISIBLE, width=992, height=99, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9441229, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=147.0, text=Put the toolbar within easy reach. Keep it on the bottom, or move it to the top., input-type=0, ime-target=false, has-links=false}
|
+---------->OnboardingRadioButton{id=2131363030, res-name=toolbar_bottom_radio_button, desc=Bottom, visibility=VISIBLE, width=88, height=88, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@43a69ae, tag=null, root-is-layout-requested=false, has-input-connection=false, x=61.70625, y=267.95, text=, input-type=0, ime-target=false, has-links=false, is-checked=true}
|
+---------->AppCompatImageView{id=2131363029, res-name=toolbar_bottom_image, desc=Bottom, visibility=VISIBLE, width=375, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=true, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@3a6334f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=81.0, y=290.0}
|
+---------->AppCompatTextView{id=2131363031, res-name=toolbar_bottom_title, visibility=VISIBLE, width=144, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f801adc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=196.0, y=533.0, text=Bottom, input-type=0, ime-target=false, has-links=false}
|
+---------->AppCompatTextView{id=2131363037, res-name=toolbar_top_title, visibility=VISIBLE, width=74, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@3e2a7e5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=731.0, y=533.0, text=Top, input-type=0, ime-target=false, has-links=false}
|
+---------->OnboardingRadioButton{id=2131363036, res-name=toolbar_top_radio_button, desc=Top, visibility=VISIBLE, width=88, height=88, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@6c772ba, tag=null, root-is-layout-requested=false, has-input-connection=false, x=560.70624, y=267.95, text=, input-type=0, ime-target=false, has-links=false, is-checked=false}
|
+---------->AppCompatImageView{id=2131363035, res-name=toolbar_top_image, desc=Top, visibility=VISIBLE, width=375, height=221, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@dbcb56b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=580.0, y=290.0}
|
+-------->ConstraintLayout{id=2131363028, res-name=toolbarLayout, visibility=VISIBLE, width=1080, height=157, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams@46208c8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1565.0, child-count=6}
|
+--------->View{id=2131362078, res-name=bottom_bar, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f1add61, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=3.0}
|
+--------->FrameLayout{id=2131363038, res-name=toolbar_wrapper, desc=Search or enter address, visibility=VISIBLE, width=827, height=110, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@7ea0086, tag=null, root-is-layout-requested=false, has-input-connection=false, x=22.0, y=25.0, child-count=2}
|
+---------->AppCompatImageView{id=2131362824, res-name=search_engine_icon, visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@86f3d47, tag=null, root-is-layout-requested=false, has-input-connection=false, x=22.0, y=22.0}
|
+---------->AppCompatTextView{id=2131363027, res-name=toolbar, visibility=VISIBLE, width=433, height=56, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7f2e974, tag=null, root-is-layout-requested=false, has-input-connection=false, x=121.0, y=27.0, text=Search or enter address, input-type=0, ime-target=false, has-links=false}
|
+--------->Barrier{id=2131361853, res-name=accessory_button_barrier, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@946ee9d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=849.0, y=0.0}
|
+--------->TabCounter{id=2131362960, res-name=tab_button, visibility=VISIBLE, width=132, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@a559f12, tag=null, root-is-layout-requested=false, has-input-connection=false, x=849.0, y=14.0, child-count=1}
|
+---------->FrameLayout{id=2131362185, res-name=counter_root, desc=0 open tabs. Tap to switch tabs., visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@6d866e3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=33.0, y=33.0, child-count=2}
|
+----------->AppCompatImageView{id=2131362184, res-name=counter_box, desc=The tab counter toolbar button., visibility=VISIBLE, width=66, height=66, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@f28e0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+----------->AppCompatTextView{id=2131362186, res-name=counter_text, visibility=VISIBLE, width=19, height=44, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@228d799, tag=null, root-is-layout-requested=false, has-input-connection=false, x=23.0, y=11.0, text=0, input-type=0, ime-target=false, has-links=false}
|
+--------->MenuButton{id=2131362520, res-name=menuButton, visibility=VISIBLE, width=99, height=132, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@9208e3f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=981.0, y=14.0, child-count=3}
|
+---------->AppCompatImageView{id=2131362379, res-name=highlight, desc=Highlighted, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1edf30c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---------->AppCompatImageView{id=2131362403, res-name=icon, desc=Menu, visibility=VISIBLE, width=99, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9a65455, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---------->AppCompatImageView{id=2131362660, res-name=notification_dot, desc=Highlighted, visibility=VISIBLE, width=99, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@841fe6a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+--------->View{id=2131362077, res-name=bottomBarShadow, visibility=VISIBLE, width=1080, height=3, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@f99cf5b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1080, height=132, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@d0d33f8, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=1788.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertAccountsSignInButton(HomeScreenRobot.kt:556)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertAccountsSignInButton(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyAccountsSignInButton(HomeScreenRobot.kt:90)
at org.mozilla.fenix.screenshots.DefaultHomeScreenTest$showDefaultHomeScreen$1.invoke(DefaultHomeScreenTest.kt:34)
at org.mozilla.fenix.screenshots.DefaultHomeScreenTest$showDefaultHomeScreen$1.invoke(DefaultHomeScreenTest.kt:20)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:458)
at org.mozilla.fenix.screenshots.DefaultHomeScreenTest.showDefaultHomeScreen(DefaultHomeScreenTest.kt:33)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:32)
at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

**Comment by Mugurell** [comment]
Following #18594 we are instructing the system to highlight a certain option in system settings.
While here we don't find a certain view in the app's homescreen.

Not sure what changed lately (app's cold start could also be impacted) but based on the above logs I see that we are trying to find a button in HomeFragment while that is not yet? on the screen. The current layout is only that of HomeActivity.

A quick fix for this would probably be to use `waitNotNull` to wait a bit for the signIn button to appear on the screen. 

Bringing this to @mcomella 's attention since it seems the startup is a bit slower now.

**Comment by Mugurell** [comment]
mcomella wanted to followup on this based on my above comment.
Looking at the logs again now I'm seeing the structure of the HomeFragment so my above comment was in error.

It seems like the onboarding was shown but not the "Sign in" button, something that could be possible based on https://github.com/mozilla-mobile/fenix/blob/48460ce42cc57d033b3ad1746ad6ec63339fa393/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt#L85-L100
where there is a case for not adding a sign in item.

If this test is still failing / flaky there might be an issue that needs more investigations.
