### ISSUE TITLE
[Bug] closePrivateTabsNotificationTest intrumentation tests crashed on Firebase

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#18746]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open a private tab
2. Open the notifications tray
3. Tap the close private tabs notification
### Expected behavior
The private broswing homescreen is displayed
### Actual behavior
App crashed.
[closePrivateTabNotificationCrashLog.txt](https://github.com/mozilla-mobile/fenix/files/6242541/closePrivateTabNotificationCrash.txt)

[Firebase log](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5634021608517504804/executions/bs.5033d665074912d1/testcases/3/test-cases)

### Device information

* Device vendor / model and Android version: Pixel 2 virtual device, API 28
* Firefox for Android version: Debug 4/1

**Comment by sv-ohorvath** [comment]
Same crash on closePrivateTabTest: 
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7083322726591626257/executions/bs.4bc1180143686b70/testcases/3/logs
I see the same NullPointerExcception in the logs: 
[closePrivateTabTestLog.txt](https://github.com/mozilla-mobile/fenix/files/6256779/closePrivateTabTestLog.txt)
`04-04 17:45:09.251: W/System.err(13224): java.lang.NullPointerException: NullHandle
04-04 17:45:09.251: W/System.err(13224): 	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
04-04 17:45:09.251: W/System.err(13224): 	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:469)`

**Comment by sv-ohorvath** [comment]
bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1704067

**Comment by AndiAJ** [comment]
The same crash to occurred on Master 4/8 while the  `verifyAboutFirefoxPreview` test ran
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8321615644823376072/executions/bs.1221735652509b45/testcases/1/errors)

<details>
    <summary>Logcat (dropdown)</summary>
   04-08 12:39:53.913: D/LeakCanary(8256): Watching instance of androidx.coordinatorlayout.widget.CoordinatorLayout (org.mozilla.fenix.home.HomeFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key d6b56f81-2e87-4b9c-9688-978bd52e0649
04-08 12:39:53.913: D/LeakCanary(8256): Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 8cfba032-cdd3-4297-9c16-1732e0ec9fa2
04-08 12:39:53.913: D/LeakCanary(8256): Watching instance of org.mozilla.fenix.components.StoreProvider (org.mozilla.fenix.components.StoreProvider received ViewModel#onCleared() callback) with key c898f8ad-345e-4ad3-980d-d8ea170e5aa0
04-08 12:39:53.913: D/LeakCanary(8256): Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key dc9b1bd2-ad9d-4029-8a3f-04c835959683
04-08 12:39:53.914: D/LeakCanary(8256): Watching instance of org.mozilla.fenix.home.HomeFragment (org.mozilla.fenix.home.HomeFragment received Fragment#onDestroy() callback) with key a15352d3-1355-4085-9beb-3d17b44e37e0
04-08 12:39:53.929: I/GoogleInputMethod(2220): onFinishInput() : Dummy InputConnection bound
04-08 12:39:53.929: I/GoogleInputMethod(2220): onStartInput() : Dummy InputConnection bound
04-08 12:39:54.013: D/GeckoViewContent(8256): handleEvent: DOMWindowClose
04-08 12:39:54.016: D/GeckoViewSelectionActionDelegate[C](8557): handleEvent: visibilitychange
04-08 12:39:54.017: D/GeckoViewNavigation(8256): onDisable
04-08 12:39:54.018: D/GeckoViewProcessHangMonitor(8256): onDisable
04-08 12:39:54.019: D/GeckoViewModule(8256): unregisterListener
04-08 12:39:54.022: D/GeckoViewProcessHangMonitor(8256): onDestroy
04-08 12:39:54.022: D/GeckoViewProgress(8256): onDisable
04-08 12:39:54.022: D/GeckoViewModule(8256): unregisterListener
04-08 12:39:54.041: D/BrowserIcons(8256): Loaded icon (source = MEMORY): https://www.google.com/
04-08 12:39:54.052: D/BrowserIcons(8256): Loaded icon (source = MEMORY): https://www.wikipedia.org/
04-08 12:39:54.057: D/GeckoViewModule(8256): unregisterListener
04-08 12:39:54.059: D/GeckoViewMediaControl(8256): onDisable
04-08 12:39:54.066: D/GeckoViewModule(8256): unregisterListener
04-08 12:39:54.072: D/GeckoViewMediaControl[C](8557): onDisable
04-08 12:39:54.078: D/GeckoViewSelectionActionDelegate[C](8557): handleEvent: visibilitychange
04-08 12:39:54.078: D/GeckoViewAutofill[C](8557): handleEvent: pagehide
04-08 12:39:54.078: D/GeckoViewAutofill(8557): Clearing auto-fill
04-08 12:39:54.140: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:54.141: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:54.141: W/System.err(8256): java.lang.NullPointerException: NullHandle
04-08 12:39:54.141: W/System.err(8256): 	at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
04-08 12:39:54.141: W/System.err(8256): 	at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:469)
04-08 12:39:54.159: W/google-breakpad(8256): ExceptionHandler::GenerateDump cloned child 
04-08 12:39:54.159: W/google-breakpad(8256): 11706
04-08 12:39:54.159: W/google-breakpad(8256): ExceptionHandler::SendContinueSignalToChild sent continue signal to child
04-08 12:39:54.165: W/google-breakpad(11706): ExceptionHandler::WaitForContinueSignal waiting for continue signal...
04-08 12:39:54.285: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:54.285: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:54.385: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:54.385: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:54.419: I/Remoter(1922): Saved screenshot to '/data/screenshots/__pmv__-0183.jpg'
04-08 12:39:54.633: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:54.633: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:54.879: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:54.879: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:54.951: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:54.953: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:55.017: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:55.017: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:55.018: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:55.028: I/ActivityManager(2076): Start proc 11768:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashHandler/u0a95 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService
04-08 12:39:55.018: D/IdlingResourceRegistry(8256): All idling resources are idle.
04-08 12:39:55.030: I/Zygote(11768): seccomp disabled by setenforce 0
04-08 12:39:55.032: I/sh.CrashHandle(11768): Late-enabling -Xcheck:jni
04-08 12:39:55.067: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:55.067: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:55.074: W/sh.CrashHandle(11768): Unexpected CPU variant for X86 using defaults: x86
04-08 12:39:55.087: E/memtrack(2076): Couldn't load memtrack module
04-08 12:39:55.087: W/android.os.Debug(2076): failed to get memory consumption info: -1
04-08 12:39:55.121: I/sh.CrashHandle(11768): The ClassLoaderContext is a special shared library.
04-08 12:39:55.211: I/Gecko(8557): Exiting due to channel error.
04-08 12:39:55.211: W/InputDispatcher(2076): channel '31b4d53 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-08 12:39:55.211: E/InputDispatcher(2076): channel '31b4d53 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-08 12:39:55.212: I/Zygote(1919): Process 8256 exited cleanly (11)
04-08 12:39:55.216: I/ActivityManager(2076): Process org.mozilla.fenix.debug (pid 8256) has died: fore TOP 
04-08 12:39:55.217: E/lowmemorykiller(1936): Error writing /proc/8557/oom_score_adj; errno=22
04-08 12:39:55.217: W/libprocessgroup(2076): kill(-8256, 9) failed: No such process
04-08 12:39:55.217: I/libprocessgroup(2076): Successfully killed process cgroup uid 10095 pid 8256 in 0ms
04-08 12:39:55.217: W/WindowManager(2076): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@3456871
04-08 12:39:55.221: W/ActivityManager(2076): Force removing ActivityRecord{ef6fbc4 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t4}: app died, no saved state
04-08 12:39:55.221: I/WindowManager(2076): WIN DEATH: Window{31b4d53 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
04-08 12:39:55.221: W/InputDispatcher(2076): Attempted to unregister already unregistered input channel '31b4d53 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)'
04-08 12:39:55.225: W/BinderNative(2076): Uncaught exception from death notification
04-08 12:39:55.225: W/BinderNative(2076): java.lang.NullPointerException: Attempt to read from field 'android.accessibilityservice.IAccessibilityServiceClient com.android.server.accessibility.AbstractAccessibilityServiceConnection.mServiceInterface' on a null object reference
04-08 12:39:55.225: W/BinderNative(2076): 	at com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService(UiAutomationManager.java:179)
04-08 12:39:55.225: W/BinderNative(2076): 	at com.android.server.accessibility.UiAutomationManager.access$200(UiAutomationManager.java:41)
04-08 12:39:55.225: W/BinderNative(2076): 	at com.android.server.accessibility.UiAutomationManager$UiAutomationService.binderDied(UiAutomationManager.java:230)
04-08 12:39:55.225: W/BinderNative(2076): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:1193)
04-08 12:39:55.369: W/SurfaceFlinger(1939): Attempting to set client state on removed layer: org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity#0
04-08 12:39:55.369: I/ConfigStore(2076): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-08 12:39:55.369: W/SurfaceFlinger(1939): Attempting to destroy on removed layer: org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity#0
04-08 12:39:55.369: I/ConfigStore(2076): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
04-08 12:39:55.369: I/OpenGLRenderer(2076): Initialized EGL, version 1.4
04-08 12:39:55.369: D/OpenGLRenderer(2076): Swap behavior 1
04-08 12:39:55.391: W/ActivityManager(2076): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
04-08 12:39:55.391: I/ActivityManager(2076): Force stopping org.mozilla.fenix.debug appid=10095 user=0: finished inst
04-08 12:39:55.391: I/ActivityManager(2076): Killing 8557:org.mozilla.fenix.debug:tab34/u0a95 (adj 0): stop org.mozilla.fenix.debug
04-08 12:39:55.391: W/libprocessgroup(2076): kill(-8557, 9) failed: No such process
04-08 12:39:55.402: I/ActivityManager(2076): Killing 11768:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashHandler/u0a95 (adj 200): stop org.mozilla.fenix.debug
04-08 12:39:55.402: W/ActivityManager(2076): Scheduling restart of crashed service org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService in 1000ms
04-08 12:39:55.405: I/ActivityManager(2076):   Force stopping service ServiceRecord{dfcd990 u0 org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
04-08 12:39:55.405: W/ActivityManager(2076): Bringing down service while still waiting for start foreground: ServiceRecord{dfcd990 u0 org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
04-08 12:39:55.409: W/Looper(2076): Slow dispatch took 192ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=53
04-08 12:39:55.409: V/SettingsProvider(2076): Notifying for 0: content://settings/secure/accessibility_enabled
04-08 12:39:55.409: W/Looper(2076): Slow dispatch took 188ms main h=com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler c=null m=1
04-08 12:39:55.411: W/Binder(8163): Binder call failed.
04-08 12:39:55.411: W/Binder(8163): java.lang.SecurityException: Calling from not trusted UID!
04-08 12:39:55.411: W/Binder(8163): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:468)
04-08 12:39:55.411: W/Binder(8163): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:372)
04-08 12:39:55.411: W/Binder(8163): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:222)
04-08 12:39:55.411: W/Binder(8163): 	at android.os.Binder.execTransact(Binder.java:731)
04-08 12:39:55.412: W/ActivityManager(2076): setHasOverlayUi called on unknown pid: 8256
04-08 12:39:55.432: W/libprocessgroup(2076): kill(-8557, 9) failed: No such process
04-08 12:39:55.443: I/GoogleInputMethod(2220): onFinishInput() : Dummy InputConnection bound
04-08 12:39:55.443: I/GoogleInputMethod(2220): onStartInput() : Dummy InputConnection bound
04-08 12:39:55.454: W/Binder(2076): Outgoing transactions from this process must be FLAG_ONEWAY
04-08 12:39:55.454: W/Binder(2076): java.lang.Throwable
04-08 12:39:55.454: W/Binder(2076): 	at android.os.BinderProxy.transact(Binder.java:1114)
04-08 12:39:55.454: W/Binder(2076): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:164)
04-08 12:39:55.454: W/Binder(2076): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
04-08 12:39:55.455: D/AndroidRuntime(8163): Shutting down VM
04-08 12:39:55.470: W/libprocessgroup(2076): kill(-8557, 9) failed: No such process
04-08 12:39:55.477: I/Zygote(1919): Process 8557 exited cleanly (0)
04-08 12:39:55.501: I/Zygote(1919): Process 11768 exited due to signal (9)
04-08 12:39:55.513: W/libprocessgroup(2076): kill(-8557, 9) failed: No such process
04-08 12:39:55.513: I/libprocessgroup(2076): Successfully killed process cgroup uid 10095 pid 8557 in 121ms
04-08 12:39:55.513: W/libprocessgroup(2076): kill(-11768, 9) failed: No such process
04-08 12:39:55.513: I/libprocessgroup(2076): Successfully killed process cgroup uid 10095 pid 11768 in 0ms
04-08 12:39:55.516: I/system_server(2076): Background concurrent copying GC freed 79478(5MB) AllocSpace objects, 223(4MB) LOS objects, 42% free, 11MB/20MB, paused 110us total 499.050ms
04-08 12:39:55.577: I/Remoter(1922): Saved screenshot to '/data/screenshots/__pmv__-0184.jpg'
04-08 12:39:55.688: I/ndroid.systemu(2236): NativeAlloc concurrent copying GC freed 13138(565KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 198us total 271.094ms
04-08 12:39:55.805: I/ActivityManager(2076): Force stopping org.mozilla.fenix.debug appid=10095 user=0: clear data
04-08 12:39:55.806: I/ActivityManager(2076): Killing 7095:com.android.vending:instant_app_installer/u0a34 (adj 906): empty #17
04-08 12:39:55.806: W/libprocessgroup(2076): kill(-7095, 9) failed: No such process

</details>
