### ISSUE TITLE
DefaultToolbarMenuTest test failures: java.lang.ClassCastException:

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/fenix#18822]
`test-debug` failed from unrelated intermittent test failures: 

- `DefaultToolbarMenuTest. WHEN the bottom toolbar is set THEN the first item in the list is not the navigation`
- `DefaultToolbarMenuTest. WHEN the bottom toolbar is set THEN the nav menu should be the last item`
- `DefaultToolbarMenuTest. WHEN the top toolbar is set THEN settings should be the last item`
- `DefaultToolbarMenuTest. WHEN the top toolbar is set THEN the first item in the list is the navigation`

They all had the same stack trace:

<details>

```
java.lang.ClassCastException: android.content.Context$Subclass0 cannot be cast to org.mozilla.fenix.FenixApplication
	at org.mozilla.fenix.ext.ContextKt.getApplication(Context.kt:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:83)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:20)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$$inlined$stdFunctions$lambda$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:227)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at org.mozilla.fenix.ext.ContextKt.getApplication(Context.kt:29)
	at org.mozilla.fenix.ext.ContextKt.getComponents(Context.kt:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.mockk.proxy.jvm.advice.MethodCall.call(MethodCall.kt:14)
	at io.mockk.proxy.jvm.advice.SelfCallEliminatorCallable.call(SelfCallEliminatorCallable.kt:14)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.handleOriginalCall(JvmMockFactoryHelper.kt:83)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper.access$handleOriginalCall(JvmMockFactoryHelper.kt:20)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1$invocation$$inlined$stdFunctions$lambda$1.invoke(JvmMockFactoryHelper.kt:28)
	at io.mockk.impl.stub.MockKStub$handleInvocation$originalPlusToString$1.invoke(MockKStub.kt:227)
	at io.mockk.impl.stub.SpyKStub.defaultAnswer(SpyKStub.kt:15)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at org.mozilla.fenix.ext.ContextKt.getComponents(Context.kt:35)
	at org.mozilla.fenix.components.toolbar.DefaultToolbarMenu.<init>(DefaultToolbarMenu.kt:405)
	at org.mozilla.fenix.toolbar.DefaultToolbarMenuTest.createMenu(DefaultToolbarMenuTest.kt:73)
	at org.mozilla.fenix.toolbar.DefaultToolbarMenuTest.WHEN the top toolbar is set THEN the first item in the list is the navigation(DefaultToolbarMenuTest.kt:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

</details>

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/fenix/issues/18778#issuecomment-813909671_

**Comment by Apurwa96** [comment]
Hi @eliserichards, Can I work on this issue?

**Comment by SnexusG** [comment]
Could someone tell me how to reproduce these failures? When i ran them with an emulator they seemed  to work fine. Am i missing something here?

**Comment by eliserichards** [comment]
They are failing intermittently. This is a good guide on how to run the tests locally until they fail: https://medium.com/monsterculture/reproduce-flaky-tests-b8b42306d23f

**Comment by SnexusG** [comment]
Oh, got it. Thank you.
