### ISSUE TITLE
[Crash] NPE in QR feature

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#18824]
Crash report: https://crash-stats.mozilla.org/report/index/4957bd20-b828-423e-a431-80e050210406

Java stack trace:
```
java.lang.NullPointerException
	at org.mozilla.fenix.search.SearchDialogFragment$createQrFeature$2$$special$$inlined$let$lambda$1.onClick(SearchDialogFragment.kt:7)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:7080)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
```

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/18439
