### ISSUE TITLE
[Bug] Find a crash that affects usage very much

### ISSUE THREAD

**Issue by LvZW1895** [mozilla-mobile/fenix#18894]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Start the app, then a crash happened: 

Long Msg: java.lang.RuntimeException: StrictMode ThreadPolicy violation
	at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
	at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1719)
	at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$FxZGA9KtfTewqdcxlUwvIe5Nx9I.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
	at java.io.File.exists(File.java:815)
	at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2539)
	at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:719)
	at android.app.ContextImpl.getExternalCacheDir(ContextImpl.java:711)
	at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:279)
	at org.mozilla.JacocoUtils.getDiskCachePath(JacocoUtils.java:156)
	at org.mozilla.JacocoUtils.jacocoInit(JacocoUtils.java:51)
	at org.mozilla.JacocoUtils.uploadCoverageFileTask(JacocoUtils.java:87)
	at org.mozilla.fenix.HomeActivity$onCreate$1.invoke(HomeActivity.kt:263)
	at org.mozilla.fenix.HomeActivity$onCreate$1.invoke(HomeActivity.kt:127)
	at org.mozilla.fenix.ext.GleanKt.measureNoInline(Glean.kt:23)
	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:170)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Device information

* Device vendor / model and Android version:  Google Pixel 2,  AndroidOS 9.0
* Firefox for Android version: ? (go to Settings -> About Firefox) 1.0.2113

**Comment by Mugurell** [comment]
Seems like something @mcomella would be interested in.

**Comment by kbrosnan** [comment]
Our crash reporting data only shows this happening on truly ancient versions of Fenix. https://crash-stats.mozilla.org/signature/?java_stack_trace_raw=~ThreadPenaltyDeathWithIgnoresListener&product=Fenix

Please update to a [modern version of the app](https://github.com/mozilla-mobile/fenix/wiki#download)

**Comment by mcomella** [comment]
@LvZW1895 What commit was this debug build built from? Are you using stock Android?

I'm unable to reproduce on my Pixel 2 (which is using a newer version of Android).

Please note this crash will only happen in debug builds so you could work around this by using an official build or building your own release build.
