### ISSUE TITLE
[Bug] Constant Crashes / OutOfMemory Exception

### ISSUE THREAD

**Issue by nagelfargithub** [mozilla-mobile/fenix#19216]
Since the switch to Firefox Fenix I'm having constant troubles with Firefox freezing (most of the time) and crashing (sometimes). Mostly this happens on tab-switch or while changing from Private mode to normal mode or vice versa. Also opening a lot of tabs with videos can trigger this behaviour.
Currently I have 43 tabs open. Only addon is uBlock origin.
After a crash I can restart but if firefox hangs I have to kill it from the Settings -> Apps menu.
I'm seeing quite a few issues dealing with OutOfMemory Exceptions but not the stacktraces I'm seeing.
No other apps are exhibiting any kind of troubles.

## Steps to reproduce
Sometimes I can surf hours without problems, other times the freezes and crashes happen within  minutes. But it always happens on tab switch.

### Expected behavior
No crash on tab switch.

### Actual behavior
Firefox gets slower and starts to stutter. Tabs don't load anymore. Firefox gets unresponsive. 

### Device information

* Huawei BTV-W09 EMUI 5.0.4, Android 7.0
* Firefox DAylight 88.1.1 Build 2015804891
 
I have seen several stacktraces, most recents one are:

`
java.lang.OutOfMemoryError: Failed to allocate a 627124 byte allocation with 386808 free bytes and 377KB until OOM
	at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:77)
	at androidx.core.app.AppOpsManagerCompat.readBytes(AppOpsManagerCompat.java:1)
	at mozilla.components.browser.thumbnails.utils.ThumbnailDiskCache.getThumbnailData$browser_thumbnails_release(ThumbnailDiskCache.kt:3)
	at mozilla.components.browser.thumbnails.storage.ThumbnailStorage.access$loadThumbnailInternal(ThumbnailStorage.kt:5)
	at mozilla.components.browser.thumbnails.storage.ThumbnailStorage$loadThumbnail$1.invokeSuspend(ThumbnailStorage.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
`

and

`
e5084858-4f3f-4de6-b1eb-482f5919a816
java.lang.OutOfMemoryError: Failed to allocate a 1249932 byte allocation with 590096 free bytes and 576KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:508)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:930)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
	at android.content.res.Resources.getDrawable(Resources.java:834)
	at android.content.Context.getDrawable(Context.java:529)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:1)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:9)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:1)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:1)
	at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:7)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:8)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:37)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:13)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)
	at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:1)
	at androidx.core.app.AppOpsManagerCompat.measureNoInline(AppOpsManagerCompat.java:2)
	at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:1)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:25)
	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:5)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:53)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
`

But I'm also seeing native crashes in the crashreports like so

`
15e657aa-9a10-4417-8cf5-dcbcbd5684c1
<native crash>
`

One older exception I was seeing quite a bit was this one
`
77f68e27-0fa2-474e-b147-44487d092af8
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
	at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4$GeckoResult(GeckoResult.java:10)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$-hYJKiV7OmgfRN8NZFvKg9ij7nk.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
`

Happy to provide further information if necessary.

**Comment by sflorean** [comment]
@nagelfargithub this is still reproducible for you?
Tested on latest Nightly with Pixel 3 (Android 11), Xiaomi Redmi (Android 9.0) and the app didn't crash following the steps.

**Comment by nagelfargithub** [comment]
Yes, I'm still seeing OutOfMemory crashes with 88.1.4 Build 2015811035, e.g.
org.mozilla.geckoview.GeckoResult$UncaughtException: OutOfMemoryError thrown while trying to throw OutOfMemoryError; nostack trace available. Happened yesterday.

**Comment by scrp445** [comment]
I have the same problems, using it the same way (tab switching). Freezes occur randomly on any page, but it is more frequent on pages with a lot of images (e.g. Instagram)
