### ISSUE TITLE
[Bug] crash on fennec fdroid 88.1.1 org.mozilla.geckoview.GeckoResult$UncaughtException

### ISSUE THREAD

**Issue by zivian** [mozilla-mobile/fenix#19245]
`c77f1d2e-9180-41bd-8f8a-2ad5652ead14`
`org.mozilla.geckoview.GeckoResult$UncaughtException`
---
`org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: Fragment BrowserFragment{4e9eeba} (342157bd-3e40-40de-8b1f-091cb7f6fa1e)} not attached to a context.
	at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4$GeckoResult(GeckoResult.java:10)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$-hYJKiV7OmgfRN8NZFvKg9ij7nk.run(Unknown Source:8)
	at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$5(GeckoResult.java:2)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$itcI1hkT0606QBUv3dYAZ4ertbk.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.IllegalStateException: Fragment BrowserFragment{4e9eeba} (342157bd-3e40-40de-8b1f-091cb7f6fa1e)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
	at org.mozilla.fenix.browser.BaseBrowserFragment.getAppropriateLayoutGravity(BaseBrowserFragment.kt:1)
	at org.mozilla.fenix.browser.BrowserFragment$navToTrackingProtectionPanel$1.invoke(BrowserFragment.kt:5)
	at mozilla.components.browser.engine.gecko.-$$LambdaGroup$js$ajTXVcIBEzHqXHlGQzCQ0Zh2n6M.accept(java-style lambda group:2)
	at org.mozilla.geckoview.GeckoResult.lambda$accept$2(GeckoResult.java:1)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$jOTMkpkhFSpBCw69vbWxDq7m7Tw.onValue(Unknown Source:2)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4$GeckoResult(GeckoResult.java:2)
	... 10 more`

**Comment by sflorean** [comment]
@zivian this is still reproducible for you? Could you give us some details in order to reproduce the crash: device and Android versions, Fenix version? thank you!
