### ISSUE TITLE
java.lang.illegalArgumentException: vecx must be a finite, non-NaN value NaN

### ISSUE THREAD

**Issue by jawz101** [mozilla-mobile/fenix#19261]
## Steps to reproduce
Browse around, scroll up and down web pages enough to reach the bottom and top of a web page

### Expected behavior
Normal operation when reaching the bottom of a webpage

### Actual behavior
Screen flickers, Firefox eventually crashes

### Device information

* Device vendor / model and Android version: Google Pixel 4a / Android 12 DP3
* Firefox for Android version: ? (go to Settings -> About Firefox)
 Nightly 210425 17:01 (Build #2015806731)

d2cb894c-a4be-4603-99e9-5fd7f9fddcfe
java.lang.IllegalArgumentException: vecX must be a finite, non-NaN value NaN
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=4c11dfa885f04f1fa4afc1a39c38b782
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-602308aa-d83b-49ef-b4dc-b35ea0210427
----
java.lang.IllegalArgumentException: vecX must be a finite, non-NaN value NaN
	at android.graphics.RenderNode.stretch(RenderNode.java:725)
	at android.widget.EdgeEffect.draw(EdgeEffect.java:633)
	at org.mozilla.geckoview.OverscrollEdgeEffect.draw(OverscrollEdgeEffect.java:17)
	at org.mozilla.geckoview.OverscrollEdgeEffect.draw(OverscrollEdgeEffect.java:7)
	at org.mozilla.geckoview.GeckoView.dispatchDraw(GeckoView.java:3)
	at android.view.View.updateDisplayListIfDirty(View.java:21412)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4498)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4471)
	at android.view.View.updateDisplayListIfDirty(View.java:21377)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4334)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4062)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3223)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1005)
	at android.view.Choreographer.doCallbacks(Choreographer.java:826)
	at android.view.Choreographer.doFrame(Choreographer.java:761)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7695)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by jawz101** [comment]
I know this is Android 12 Developer Preview but it is happening so I figured someone might want to know if Android 12 will cause any problems.  It's frequent enough to reproduce within a few minutes of browsing and scrolling around on web pages.  I think the newer bounce animations in Android 12 mess with what Fenix expects to happen at the end of a web page.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1707959

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
