### ISSUE TITLE
FNX-5338 ⁃ NoSuchMethodError: No virtual method getVisitInfos(JJ)Ljava/util/List; in class Lmozilla/appservices/places/PlacesRe...

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1929]
https://sentry.prod.mozaws.net/operations/fenix/issues/5577506/

```
NoSuchMethodError: No virtual method getVisitInfos(JJ)Ljava/util/List; in class Lmozilla/appservices/places/PlacesReaderConnection; or its super classes (declaration of 'mozilla.appservices.places.PlacesReaderConnection' appears in base.apk)
    at org.mozilla.fenix.library.history.HistoryFragment.reloadData(HistoryFragment.kt:8)
    at org.mozilla.fenix.library.history.HistoryFragment$onViewCreated$1.invokeSuspend(HistoryFragment.kt:5)
...
(7 additional frame(s) were not displayed)

No virtual method getVisitInfos(JJ)Ljava/util/List; in class Lmozilla/appservices/places/PlacesReaderConnection; or its super classes (declaration of 'mozilla.appservices.places.PlacesReaderConnection' appears in base.apk)
```

This is a Fenix Nightly top crash from Sentry.

**Comment by ekager** [comment]
https://github.com/mozilla-mobile/fenix/issues/1811
