### ISSUE TITLE
FNX-5341 ⁃ IllegalStateException: Fragment DataChoicesFragment{4026896 (f8637977-4e4a-49fd-9c8c-223fd8dcb260)} not attached to a co...

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#1933]
https://sentry.prod.mozaws.net/operations/fenix/issues/5538700/

```
IllegalStateException: Fragment DataChoicesFragment{4026896 (f8637977-4e4a-49fd-9c8c-223fd8dcb260)} not attached to a context.
    at org.mozilla.fenix.settings.DataChoicesFragment$onCreate$1.onSharedPreferenceChanged(DataChoicesFragment.kt:1)
    at org.mozilla.fenix.settings.TrackingProtectionFragment.onCreatePreferences(TrackingProtectionFragment.kt:1)
    at org.mozilla.fenix.settings.TrackingProtectionFragment.onCreate(TrackingProtectionFragment.kt:1)
...
(20 additional frame(s) were not displayed)

Fragment DataChoicesFragment{4026896 (f8637977-4e4a-49fd-9c8c-223fd8dcb260)} not attached to a context.
```

This crash first started on April 13.

**Comment by colintheshots** [comment]
Duplicate of #1932.
