### ISSUE TITLE
Intermittent test failure - NimbusBranchesControllerTest.WHEN branch item is clicked THEN branch is opted into and selectedBranch state is updated

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#19459]
Test failure for an unrelated PR (https://github.com/mozilla-mobile/fenix/pull/19457).

<details>

<summary>Stacktrace:</summary>

```
[task 2021-05-10T21:02:29.948Z]   TEST: WHEN branch item is clicked THEN branch is opted into and selectedBranch state is updated
[task 2021-05-10T21:02:30.448Z]   FAILURE
[task 2021-05-10T21:02:30.549Z] 
[task 2021-05-10T21:02:30.550Z] org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
[task 2021-05-10T21:02:30.550Z] Misplaced or misused argument matcher detected here:
[task 2021-05-10T21:02:30.550Z] 
[task 2021-05-10T21:02:30.550Z] -> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)
[task 2021-05-10T21:02:30.551Z] -> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)
[task 2021-05-10T21:02:30.551Z] -> at mozilla.components.support.test.MatchersKt.any(Matchers.kt:17)
[task 2021-05-10T21:02:30.551Z] 
[task 2021-05-10T21:02:30.552Z] You cannot use argument matchers outside of verification or stubbing.
[task 2021-05-10T21:02:30.552Z] Examples of correct usage of argument matchers:
[task 2021-05-10T21:02:30.552Z]     when(mock.get(anyInt())).thenReturn(null);
[task 2021-05-10T21:02:30.552Z]     doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
[task 2021-05-10T21:02:30.552Z]     verify(mock).someMethod(contains("foo"))
[task 2021-05-10T21:02:30.553Z] 
[task 2021-05-10T21:02:30.553Z] This message may appear after an NullPointerException if the last matcher is returning an object 
[task 2021-05-10T21:02:30.553Z] like any() but the stubbed method signature expect a primitive argument, in this case,
[task 2021-05-10T21:02:30.553Z] use primitive alternatives.
[task 2021-05-10T21:02:30.553Z]     when(mock.get(any())); // bad use, will raise NPE
[task 2021-05-10T21:02:30.553Z]     when(mock.get(anyInt())); // correct usage use
[task 2021-05-10T21:02:30.553Z] 
[task 2021-05-10T21:02:30.554Z] Also, this error might show up because you use argument matchers with methods that cannot be mocked.
[task 2021-05-10T21:02:30.554Z] Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
[task 2021-05-10T21:02:30.555Z] Mocking methods declared on non-public parent classes is not supported.
[task 2021-05-10T21:02:30.555Z] 
[task 2021-05-10T21:02:30.555Z] 	at org.mozilla.fenix.nimbus.NimbusBranchesControllerTest.setup(NimbusBranchesControllerTest.kt:51)
[task 2021-05-10T21:02:30.555Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2021-05-10T21:02:30.555Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2021-05-10T21:02:30.556Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-05-10T21:02:30.556Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-05-10T21:02:30.556Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2021-05-10T21:02:30.556Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2021-05-10T21:02:30.556Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2021-05-10T21:02:30.556Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[task 2021-05-10T21:02:30.556Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2021-05-10T21:02:30.557Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2021-05-10T21:02:30.558Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2021-05-10T21:02:30.558Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2021-05-10T21:02:30.558Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2021-05-10T21:02:30.558Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2021-05-10T21:02:30.558Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2021-05-10T21:02:30.558Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2021-05-10T21:02:30.558Z] 	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
[task 2021-05-10T21:02:30.558Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-05-10T21:02:30.559Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-05-10T21:02:30.559Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-05-10T21:02:30.559Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-05-10T21:02:30.559Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2021-05-10T21:02:30.559Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2021-05-10T21:02:30.559Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2021-05-10T21:02:30.559Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
[task 2021-05-10T21:02:30.560Z] 	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
[task 2021-05-10T21:02:30.560Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-05-10T21:02:30.560Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-05-10T21:02:30.560Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2021-05-10T21:02:30.560Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2021-05-10T21:02:30.560Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2021-05-10T21:02:30.560Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2021-05-10T21:02:30.560Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2021-05-10T21:02:30.561Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2021-05-10T21:02:30.561Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2021-05-10T21:02:30.561Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-05-10T21:02:30.561Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-05-10T21:02:30.561Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2021-05-10T21:02:30.561Z] 	at java.lang.Thread.run(Thread.java:748)
```
</details>

### Build: 

- Task link: https://firefox-ci-tc.services.mozilla.com/tasks/X8BzMctjQS6o4TOPR6bE1A
- Logs link: https://firefoxci.taskcluster-artifacts.net/X8BzMctjQS6o4TOPR6bE1A/0/public/logs/live_backing.log

cc: @gabrielluong

**Comment by jonalmeida** [comment]
I'm going to try and pick this up next sprint. It looks like others have run into this issue as well. ☝️
