### ISSUE TITLE
Intermittent UI test failure - org.mozilla.fenix.browser.BrowserFragmentTest - WHEN in fullscreen THEN pull down refresh is disabled

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#19456]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=339195729&repo=fenix
### Stacktrace:
```
  TEST: WHEN in fullscreen THEN pull down refresh is disabled
    [Robolectric] org.mozilla.fenix.browser.BrowserFragmentTest.WHEN in fullscreen THEN pull down refresh is disabled: sdk=28; resources=BINARY
    I/MonitoringInstr: Instrumentation started!
    E/glean/Dispatchers: Exceeded maximum queue size, discarding task
    E/glean/Dispatchers: Exceeded maximum queue size, discarding task
  FAILURE

java.lang.AssertionError: Assertion failed
	at org.mozilla.fenix.browser.BrowserFragmentTest.WHEN in fullscreen THEN pull down refresh is disabled(BrowserFragmentTest.kt:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/07fd5ca9e65254b3094b34b1928f9e89ce339373

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10663)

**Comment by jonalmeida** [comment]
@bendk is seeing this test consistently fail when run with this docker image: https://github.com/bendk/application-services-builder

Curious why this pull-to-refresh test would fail here.

**Comment by bendk** [comment]
I'm also motivated to fix this one to make that build system work.  If anyone has any ideas to start checking, I'm happy to test them out and try to fix them.

**Comment by bendk** [comment]
On my side, I think this is because I was running `testBetaUnitTest` and AFAICT the test is never going to pass for that channel, since the [feature is only enabled for nightly/debug](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L19).

Does this seem correct?  Is there a chance that you were also running the beta unit tests in CI?  Is there a good way to disable or fix this test for the beta unit test run?
