### ISSUE TITLE
Intermittent UI test failure - SmokeTest.toggleSearchSuggestions

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#19478]
### Firebase Test Run:
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6648269585175269995/executions/bs.8b4c8b2226d29e72/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/toolbar_wrapper
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertNavigationToolbar(HomeScreenRobot.kt:481)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertNavigationToolbar(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openNavigationToolbar(HomeScreenRobot.kt:379)
at org.mozilla.fenix.ui.SmokeTest.toggleSearchSuggestions(SmokeTest.kt:499)`
### Build: 
Debug 5/11

**Comment by AndiAJ** [comment]
Closed in #19469
