### ISSUE TITLE
[Bug] Crash when editing an already saved credit card (or adding a new one overriding the old one)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#19492]
## Steps to reproduce
1. Launch Fenix and add a valid card.
2. On the credit cards section, select the newly added card and add another valid card.

### Expected behavior
The card number is changed correctly.
### Actual behavior
Crash when editing an already saved credit card (or adding a new one).
### Device information

* Device: **Google Pixel 4 XL (Android 11).**
* Firefox for Android version: **Nightly 5/13.**

```kotlin
c8dbb688-7eed-4c4e-b92f-34f9b11d3c7b
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
----
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: CHECK constraint failed: credit_cards_data
at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
at mozilla.appservices.autofill.Store.updateCreditCard(autofill.kt:6)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:25)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$updateCreditCard$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.updateCreditCard(AutofillCreditCardsAddressesStorage.kt:1)
at org.mozilla.fenix.settings.creditcards.controller.DefaultCreditCardEditorController$handleUpdateCreditCard$1.invokeSuspend(CreditCardEditorController.kt:5)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kaream671** [comment]
19492

**Comment by codrut-topliceanu** [comment]
I've logged https://github.com/mozilla/application-services/issues/4119 as this seems to stem from `mozilla.appservices.autofill.Store`.

**Comment by mhammond** [comment]
I suspect this is an old build of app-services, but I can't reproduce it. I can add exactly the same card multiple times (which the store component can't prevent as it only knows the encrypted values) and the "Edit Card" dialog shows the encrypted number instead of the CC number, which is (correctly) rejected as an invalid number

![image](https://user-images.githubusercontent.com/83924/118761461-cba44b00-b8b7-11eb-8f35-79333fd9d07e.png)

**Comment by codrut-topliceanu** [comment]
@mhammond Thx for taking a look at this.
You can delete the whole encrypted number and replace it with a non-encrypted value taken from an online random credit card [generator](https://www.getcreditcardnumbers.com/).
Maybe @gabrielluong can provide some further input here?

**Comment by mhammond** [comment]
> You can delete the whole encrypted number

Right, but the fact you need to do this is probably triggering one of the `CHECK` constraints we've added explicitly to try and avoid this kind of confusion (eg, trying to store a *real, unencrypted* CC number in the field where it's supposed to be encrypted will trigger this exact exception)

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly build 5/28** with **Google Pixel 4 XL (11).**
Please note that I edited more than 20 Credit Cards.
I went to the edit section even from the autofill option (from a website) but everything works as expected!
