### ISSUE TITLE
[Bug] Crash when initializing AutofillCreditCardsAddressesStorage

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#19508]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
After lastest update which added addresses and credit card sync, on clicking credit cards browser is crashing

### Expected behavior
Browser should show credit cards items

### Actual behavior
Crashing 

### Device information

* Device vendor / model and Android version: ? A11
* Firefox for Android version: ? (go to Settings -> About Firefox) latest nightly 

2e0b04e9-7885-4aff-a36a-ede30e8de1b4
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=89e739ee3ce34e279d1923c1907dd346
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-3877bde0-083a-451f-814e-955640210513
----
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
	at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
	at mozilla.appservices.autofill.Store.<init>(autofill.kt:7)
	at mozilla.components.service.sync.autofill.AutofillStorageConnection.init$service_sync_autofill_release(AutofillCreditCardsAddressesStorage.kt:3)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$conn$2.invoke(AutofillCreditCardsAddressesStorage.kt:1)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getConn(Unknown Source:2)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.access$getConn$p(AutofillCreditCardsAddressesStorage.kt:1)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:2)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
	at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getAllCreditCards(AutofillCreditCardsAddressesStorage.kt:1)
	at org.mozilla.fenix.settings.creditcards.CreditCardsSettingFragment$loadCreditCards$1.invokeSuspend(CreditCardsSettingFragment.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

**Comment by sheikh-azharuddin** [comment]
The issue seems critical... Browser is crashing even on opening some websites... Example reporting bugs github or the site (best example) https://www.igp.com/#search

**Comment by sheikh-azharuddin** [comment]
This is crashing even after disabling the credit card autofill   settings...

**Comment by csadilek** [comment]
Filed an upstream issue: https://github.com/mozilla/application-services/issues/4106

**Comment by sheikh-azharuddin** [comment]
I found one workaround: on clearing storage and cache and then signing again issue is fixed...

**Comment by Mugurell** [comment]
Waiting for the AS containing https://github.com/mozilla/application-services/issues/4106 to get to Fenix.

**Comment by csadilek** [comment]
This should be fixed now in latest Nightly. @sflorean Can you verify, please, based on https://github.com/mozilla-mobile/fenix/issues/19520. Thank you!

**Comment by madb1lly** [comment]
Hi @csadilek,
I confirm that this is now fixed for me,  Nokia 8 on android 9.
Cheers 🙂

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build (5/19) with the following devices:
- Pixel 3 (Android 11)
- Samsung Note 10 (Android 11)
Verified also the duplicated scenarios.
