### ISSUE TITLE
[Crash] Crash when clicked on website buttons

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#19513]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Go to https://github.com/mozilla-mobile/fenix/issues/new/choose and press "Get started" next to the bug report template.
I'm also able to reproduce on google via clicking "images, news etc" tab buttons but GitHub looks 100% reproducible.

### Expected behavior
No crash

### Actual behavior
Fenix crashes 

319490d7-79fa-4b1e-a2e5-ef15174583ea
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=198d6a98d61b4271a953a6f5bfb61372
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-798de63e-60f7-44fb-bf47-6564c0210514

```
mozilla.appservices.autofill.ErrorException$SqlError: Error executing SQL: no such trigger: credit_cards_tombstones_afterinsert_trigger
 at mozilla.appservices.autofill.Error.intoException(autofill.kt:14)
 at mozilla.appservices.autofill.Store.<init>(autofill.kt:7)
 at mozilla.components.service.sync.autofill.AutofillStorageConnection.init$service_sync_autofill_release(AutofillCreditCardsAddressesStorage.kt:3)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$conn$2.invoke(AutofillCreditCardsAddressesStorage.kt:1)
 at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getConn(Unknown Source:2)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.access$getConn$p(AutofillCreditCardsAddressesStorage.kt:1)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invokeSuspend(AutofillCreditCardsAddressesStorage.kt:2)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage$getAllCreditCards$2.invoke(AutofillCreditCardsAddressesStorage.kt:2)
 at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
 at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
 at mozilla.components.service.sync.autofill.AutofillCreditCardsAddressesStorage.getAllCreditCards(AutofillCreditCardsAddressesStorage.kt:1)
 at mozilla.components.service.sync.autofill.GeckoCreditCardsAddressesStorageDelegate$onCreditCardsFetch$1.invokeSuspend(GeckoCreditCardsAddressesStorageDelegate.kt:5)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

```

### Device information
* Device vendor / model and Android version: XZ1 Android 11
* Firefox for Android version: 5/14 nightly

**Comment by hakkikaancaliskan** [comment]
Oopsie, this seems duplicate of #19508. Sorry!
