### ISSUE TITLE
Intermittent UI test failure - <SmokeTest.restoreTabCrashedReporterTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19585]
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:98)
at org.mozilla.fenix.ui.SmokeTest$restoreTabCrashedReporterTest$5.invoke(SmokeTest.kt:1229)
at org.mozilla.fenix.ui.SmokeTest$restoreTabCrashedReporterTest$5.invoke(SmokeTest.kt:46)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.openTabCrashReporter(NavigationToolbarRobot.kt:175)
at org.mozilla.fenix.ui.SmokeTest.restoreTabCrashedReporterTest(SmokeTest.kt:1227)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

### Build: Master 5/19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-10748)

**Comment by AndiAJ** [comment]
Flaky on Master 5/27 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6514160188238217637/executions/bs.f0a1427a2034b399/testcases/1/test-cases)

**Comment by csadilek** [comment]
Hit this again in: https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4964865209988432393/executions/bs.1d07bd48939b9f5d/

**Comment by AndiAJ** [comment]
Flaky on Master 6/9: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5994022852718676571/executions/bs.73f0a5f2249df118/testcases/1/test-cases)

**Comment by AaronMT** [comment]
Failed in https://github.com/mozilla-mobile/fenix/pull/19941/checks?check_run_id=2794145508

I think we should disable this or put attention on fixing it.

**Comment by AndiAJ** [comment]
Flaky 2x on Master 6/10 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6268533671295772863/executions/bs.d2192f69f32f70ac/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5716753120940600641/executions/bs.6b1cf89582a0a62d/testcases/1/test-cases)

Failed 1x on Master 6/10 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6131596926491433173/executions/bs.2ce054fc788a390/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6131596926491433173/executions/bs.38fb8cf82c3a8e7a/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failures caused by #19964
Disabled in #19965 until the issue is fixed.

**Comment by sv-ohorvath** [comment]
Still happening. Let's keep it.

**Comment by sv-ohorvath** [comment]
Still reproducible.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807297

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
