### ISSUE TITLE
Intermittent UI test failure - SmokeTest.verifyReaderViewAppearanceUI

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#19644]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6406285822782981655/executions/bs.a9e252ee0112e41/testcases/1/test-cases
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:316)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:101)
at org.mozilla.fenix.ui.SmokeTest.verifyReaderViewAppearanceUI(SmokeTest.kt:1171)
### Build: 
Master 5/25

**Comment by sv-ohorvath** [comment]
Same failure as: https://github.com/mozilla-mobile/fenix/issues/20002

**Comment by sv-ohorvath** [comment]
This hasn't failed in a month, I'll close it for now. Can be reopened if it happens again.
