### ISSUE TITLE
AndroidRuntimeException Calling startActivity() from outside of an Activity  context

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#19648]
- [Sentry nightly ](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10876268/?query=is%3Aunresolved%20level%3Aerror%20level%3Afatal)
- [Sentry beta ](https://sentry.prod.mozaws.net/operations/firefox-beta/issues/8194436/?query=is%3Aunresolved%20Calling%20startActivity()%20from%20outside%20of%20an%20Activity)
- [Sentry release](https://sentry.prod.mozaws.net/operations/firefox/issues/9300753/?query=is%3Aunresolved%20Calling%20startActivity()%20from%20outside%20of%20an%20Activity)

```
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
    at android.app.ContextImpl.startActivity(ContextImpl.java:964)
    at android.app.ContextImpl.startActivity(ContextImpl.java:940)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:162)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
    at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0$FloatingActionMode(FloatingActionMode.java:123)
    at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick
    at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.lambda$createOverflowPanel$2$FloatingToolbar$FloatingToolbarPopup(FloatingToolbar.java:1475)
    at com.android.internal.widget.-$$Lambda$FloatingToolbar$FloatingToolbarPopup$E8FwnPCl7gZpcTlX_UaRPIBRnT0.onItemClick
    at android.widget.AdapterView.performItemClick(AdapterView.java:330)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3265)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-AAN](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10876268/?referrer=github_plugin)
