### ISSUE TITLE
Intermittent UI test failure - <SmokeTest.customTabMenuItemsTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19686]
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$1$1.invoke(SmokeTest.kt:1238)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$1$1.invoke(SmokeTest.kt:55)
at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:509)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$1.invoke(SmokeTest.kt:1237)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$1.invoke(SmokeTest.kt:55)
at org.mozilla.fenix.ui.robots.CustomTabRobotKt.customTabScreen(CustomTabRobot.kt:68)
at org.mozilla.fenix.ui.SmokeTest.customTabMenuItemsTest(SmokeTest.kt:1236)

### Build: Master 5/27

Same as https://github.com/mozilla-mobile/fenix/issues/19770, web content not visible to the test instrumentation.

**Comment by AndiAJ** [comment]
Flaky on Master 6/3 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8818903679497536667/executions/bs.dc58edaafc335a23/testcases/1/test-cases)
