### ISSUE TITLE
Intermittent UI test failure - <BookmarksTest.openSelectionInPrivateTabTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#19728]
### Stacktrace:
androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates: 798, 274 and precision: 16, 16' on view 'with text: is "Open in private tab"'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:18)
at org.mozilla.fenix.ui.robots.LibrarySubMenusMultipleSelectionToolbarRobot$Transition.clickOpenPrivateTab(LibrarySubMenusMultipleSelectionToolbarRobot.kt:112)
at org.mozilla.fenix.ui.BookmarksTest.openSelectionInPrivateTabTest(BookmarksTest.kt:362)

### Notes
❗ Different stack trace compared to in #16671

**Comment by sv-ohorvath** [comment]
In the video, the menu is opened and the "Open in private tab" option is clearly visible, but for some reason the test didn't "see" it. Since it didn't happen again in a month, I say we can close it and reopen if it happens again.
