### ISSUE TITLE
[Bug][Crash] IllegalStateException: Fragment TabsTrayFragment not attached to a context

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#19731]
Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11127448/ 

```
java.lang.IllegalStateException: Fragment TabsTrayFragment{32ba4368} (87482d02-32a2-4978-9986-df6a12758bb8)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
    at androidx.core.app.AppOpsManagerCompat.getRequireComponents(AppOpsManagerCompat.java:1)
    at org.mozilla.fenix.tabstray.TabsTrayFragment.dismissTabsTray(TabsTrayFragment.kt:2)
    at org.mozilla.fenix.tabstray.TabsTrayFragment.access$dismissTabsTray(TabsTrayFragment.kt:1)
    at org.mozilla.fenix.tabstray.TabsTrayFragment$onViewCreated$navigationInteractor$1.invoke(TabsTrayFragment.kt:2)
    at org.mozilla.fenix.tabstray.DefaultNavigationInteractor.onTabTrayDismissed(NavigationInteractor.kt:1)
    at org.mozilla.fenix.tabstray.TraySheetBehaviorCallback.onStateChanged(TraySheetBehaviorCallback.kt:1)
    at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:9)
    at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:3)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5660)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

**Comment by jonalmeida** [comment]
Thinking about it more, I think it would make sense to call the track event in [the navigation interactor](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/tabstray/NavigationInteractor.kt#L108) since that's really the real case where we want to track the user event. The other places are side-effects to other interactions (like clicking a synced tab).

This would also make that method a bit more testable without mocking the world for the `TabsTrayFragment`.
