### ISSUE TITLE
FNX-5372 ⁃ [Bug] Sign in on a fresh install crashes the app

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#1975]
## Steps to reproduce
1. Fresh install the app, or clear data.
1. Open the app, go to Settings>Sign in.
    1. Expected behavior
The sign in page is opened.
    1. Actual behavior
App crashes.
*Note: doesn't crash if you visit at least one website.
    1. Device information

* Android device: Pixel (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: 4/24

**Comment by cadeyrn** [comment]
Exception:

```
2019-04-24 21:35:24.194 23497-23497/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 23497
    java.lang.IllegalStateException: No selected session
        at mozilla.components.browser.session.LegacySessionManager.getSelectedSessionOrThrow(LegacySessionManager.kt:115)
        at mozilla.components.browser.session.SessionManager.getSelectedSessionOrThrow(SessionManager.kt:56)
        at org.mozilla.fenix.browser.BrowserFragment.getSessionByIdOrUseSelectedSession(BrowserFragment.kt:533)
        at org.mozilla.fenix.browser.BrowserFragment.onCreateView(BrowserFragment.kt:120)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2544)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:884)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2092)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1822)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1723)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:146)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-2C](https://sentry.prod.mozaws.net/operations/fenix/issues/5198794/)

**Comment by sblatz** [comment]
@bifleming I'm pulling this in before beta due to the severity of the crash for first time users.

**Comment by sv-ohorvath** [comment]
@sblatz Still reproducing on the 4/30 build.

**Comment by sv-ohorvath** [comment]
Now it crashes all the time, not just on first run.

**Comment by cadeyrn** [comment]
That's https://github.com/mozilla-mobile/android-components/issues/2935.

**Comment by sblatz** [comment]
I'm closing this as #2935 tracks the new crash.
