### ISSUE TITLE
Intermittent UI test failure - SmokeTest.openCustomTabInBrowserTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#19770]
### Firebase Test Run:
Flaky, failed 1/2 tries:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4692073155269381320/executions/bs.ff25770f09b959a5/testcases/1/test-cases

It just looks like another case of web content not visible to the test.

### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
at org.mozilla.fenix.ui.SmokeTest$openCustomTabInBrowserTest$1$1.invoke(SmokeTest.kt:1265)
at org.mozilla.fenix.ui.SmokeTest$openCustomTabInBrowserTest$1$1.invoke(SmokeTest.kt:55)
at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:509)
at org.mozilla.fenix.ui.SmokeTest$openCustomTabInBrowserTest$1.invoke(SmokeTest.kt:1264)
at org.mozilla.fenix.ui.SmokeTest$openCustomTabInBrowserTest$1.invoke(SmokeTest.kt:55)
at org.mozilla.fenix.ui.robots.CustomTabRobotKt.customTabScreen(CustomTabRobot.kt:68)
at org.mozilla.fenix.ui.SmokeTest.openCustomTabInBrowserTest(SmokeTest.kt:1263)`
### Build: 
Master 6/1

**Comment by AndiAJ** [comment]
Flaky on Debug 6/3 : [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8691601137300750163/executions/bs.3b8af1edc5b52a6/testcases/1/test-cases)
