### ISSUE TITLE
[Bug] [Crash] NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#19837]
We're seeing some new Nimbus crashes as a regression of https://github.com/mozilla-mobile/fenix/pull/19605/.

Low volume, but this affects Beta as well and we should plan to uplift a fix. `withExperiments` used to have a `catch-all`, which was removed in the PR above. This is now causing this exception to crash the app.

91 Nightly:
https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+DatabaseNotReady

90 Beta:
https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+DatabaseNotReady

```
org.mozilla.experiments.nimbus.internal.NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:5)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.getExperimentBranch(nimbus.kt:10)
    at org.mozilla.experiments.nimbus.Nimbus.getExperimentBranch(Nimbus.kt:1)
    at androidx.core.app.AppOpsManagerCompat.withExperiment(AppOpsManagerCompat.java:1)
    at org.mozilla.fenix.utils.Settings.shouldShowSetAsDefaultBrowserCard(Settings.kt:3)
    at org.mozilla.fenix.home.HomeFragment$onCreateView$1$2.invoke(HomeFragment.kt:9)
    at org.mozilla.fenix.components.StoreProviderFactory.create(StoreProvider.kt:1)
    at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:10)
    at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:2)
    at org.mozilla.fenix.home.HomeFragment$onCreateView$1.invoke(HomeFragment.kt:14)
    at androidx.core.app.AppOpsManagerCompat.measureNoInline(AppOpsManagerCompat.java:2)
    at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:1)
    at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:13)
```

**Comment by jhugman** [comment]
Hmm. I see. The `catchAll` should’ve made it in the `Nimbus` object when moving to Application Services, but didn't. We can fix this in fenix by re-instating the catchAll in `withExperiment` and then bring it in to Application Services.

Side notes:

1. experiments needing `getExperimentBranch` should be going away. This doesn't help this bug.
2. We should track the `DatabaseNotReady` exception closely. I'd like to get a feel of how close to startup the database is ready, and characteristics of devices where this is especially slow. This would help early start up and hold back experiment delivery.
