### ISSUE TITLE
Intermittent UI test failure - TopSitesTest.verifyRenameTopSite

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#19893]
### Firebase Test Run:
Flaky, failed 1 out of 2 tries
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7227752858928968526/executions/bs.a3a42bb404e8e395/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'has descendant: with text: is "Test_Page_2"' doesn't match the selected view.
Expected: has descendant: with text: is "Test_Page_2"
Got: "RecyclerView{id=2131363072, res-name=top_sites_list, visibility=VISIBLE, width=992, height=287, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@6a15d47, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertExistingTopSitesTabs(HomeScreenRobot.kt:652)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertExistingTopSitesTabs(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyExistingTopSitesTabs(HomeScreenRobot.kt:120)
at org.mozilla.fenix.ui.TopSitesTest$verifyRenameTopSite$9.invoke(TopSitesTest.kt:147)
at org.mozilla.fenix.ui.TopSitesTest$verifyRenameTopSite$9.invoke(TopSitesTest.kt:29)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.renameTopSite(HomeScreenRobot.kt:383)
at org.mozilla.fenix.ui.TopSitesTest.verifyRenameTopSite(TopSitesTest.kt:145)`
### Build: 
Master 6/7

**Comment by sv-ohorvath** [comment]
This hasn't failed in a month, I'll close it for now. Can be reopened if it happens again.

**Comment by AndiAJ** [comment]
Flaky 1 x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9154425991351969349/executions/bs.497797211817d6d1/testcases/1/test-cases)

```
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'has descendant: with text: is "Test_Page_2"' doesn't match the selected view.
Expected: has descendant: with text: is "Test_Page_2"
Got: "RecyclerView{id=2131363118, res-name=top_sites_list, visibility=VISIBLE, width=992, height=287, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@de55c4f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=4}"
```

**Comment by sv-ohorvath** [comment]
New error on Main 9/22:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id is <org.mozilla.fenix.debug:id/top_sites_list>)
`
Logs:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8278794498371878886/executions/bs.ed74fa26f9c61076/testcases/1/test-cases

**Comment by jonalmeida** [comment]
Happened again the in AC version bump PR: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4696752842999450519/executions/bs.76aa521916c279ea/test-cases
