### ISSUE TITLE
[Crash] java.util.ConcurrentModificationException at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:625)

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#20029]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Similar to https://github.com/mozilla-mobile/fenix/issues/20031. Both caught while running an automated test for switching locales. Can also be reproduced manually.

1. Fresh install
2. Go to Settings>Language
3. Select a language (e.g. Romanian)
4. Select French
5. Select "Use system language" or another language.
### Expected behavior
Languages get changed
### Actual behavior
App crashes.
### Device information

* Device vendor/model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Nightly 91.0a1, 6/14

6c45a4f0-97dc-4e95-a210-205d26fff631
java.util.ConcurrentModificationException
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=df5251e8ed674d918283beba6a1f7143
* Socorro: https://crash-stats.mozilla.org/report/index/bp-6fce0f57-7609-49f0-b607-f38e70210615
----
`java.util.ConcurrentModificationException
at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:625)
at androidx.navigation.NavController$1.onStateChanged(NavController.java:2)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:9)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:9)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:3)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:28)
at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:97)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3)
at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:1)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
at org.mozilla.fenix.HomeActivity.access$onStart$s-594849490(HomeActivity.kt:1)
at org.mozilla.fenix.HomeActivity$onStart$1.invoke(HomeActivity.kt:1)
at androidx.core.app.AppOpsManagerCompat.measureNoInline(AppOpsManagerCompat.java:2)
at org.mozilla.fenix.HomeActivity.onStart(HomeActivity.kt:1)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
at android.app.Activity.performStart(Activity.java:7165)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4782)
at android.app.ActivityThread.access$3200(ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by mcarare** [comment]
@sv-ohorvath Can you reproduce this consistently? I tried on different devices and I cannot reproduce it.

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath Can you reproduce this consistently? I tried on different devices and I cannot reproduce it.

No, not consistently, but after a few tries. I think it's important to clear the app profile if you don't get the crash after switching languages a few times. And also to keep switching languages fast, not just the two, maybe you get a crash after the 3rd-4th switch.

**Comment by mcarare** [comment]
@sv-ohorvath Thank you for your input, already tried that. Does the crash only happen when you select "Follow device language" or you can reproduce it without ever selecting that option?

**Comment by sv-ohorvath** [comment]
> @sv-ohorvath Thank you for your input, already tried that. Does the crash only happen when you select "Follow device language" or you can reproduce it without ever selecting that option?

Had to double-check that. It crashes when you select another language too.

**Comment by sflorean** [comment]
No issues found when testing on Nightly 7/9 and following the steps provided above.
Devices:
- Google Pixel 3 (Android 11)
- Google Pixel (Android 10)
- Google Pixel 3 XL (Android 9)
