### ISSUE TITLE
[Crash] android.util.AndroidRuntimeException: Animators may only be run on Looper threads

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#20031]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Caught the crash while trying to write an automated UI test for switching languages.
Similar to https://github.com/mozilla-mobile/fenix/issues/20029

1. Fresh install
2. Go to Settings>Language
3. Select French
5. Select "Use system language" or another language.
### Expected behavior
Languages get changed
### Actual behavior
App crashes.
Test logs:
[20031 crash log.txt](https://github.com/mozilla-mobile/fenix/files/6656363/20031.crash.log.txt)

### Device information

* Device vendor/model and Android version: Pixel 2 (Android 9)
* Firefox for Android version: Debug 6/14

Crash stacktrace: 
`android.util.AndroidRuntimeException: Animators may only be run on Looper threads
     FATAL EXCEPTION: DefaultDispatcher-worker-10
Process: org.mozilla.fenix.debug, PID: 7954
android.util.AndroidRuntimeException: Animators may only be run on Looper threads
	at android.animation.ValueAnimator.start(ValueAnimator.java:1034)
	at android.animation.ValueAnimator.start(ValueAnimator.java:1088)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
	at androidx.navigation.ui.AbstractAppBarOnDestinationChangedListener.setActionBarUpIndicator(AbstractAppBarOnDestinationChangedListener.java:132)
	at androidx.navigation.ui.AbstractAppBarOnDestinationChangedListener.onDestinationChanged(AbstractAppBarOnDestinationChangedListener.java:110)
	at androidx.navigation.ui.ToolbarOnDestinationChangedListener.onDestinationChanged(ToolbarOnDestinationChangedListener.java:58)
	at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.java:504)
	at androidx.navigation.NavController.onGraphCreated(NavController.java:642)
	at androidx.navigation.NavController.setGraph(NavController.java:592)
	at androidx.navigation.NavController.setGraph(NavController.java:572)
	at org.mozilla.fenix.perf.NavGraphProvider$inflateNavGraphAsync$inflationJob$1.invokeSuspend(NavGraphProvider.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

Firebase test log: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6741143898593996450/executions/bs.beed56982561a215/issues

**Comment by sflorean** [comment]
No issues found when testing on Nightly 7/9 and following the steps provided above.
Devices:
- Google Pixel 3 (Android 11)
- Google Pixel (Android 10)
- Google Pixel 3 XL (Android 9)
