### ISSUE TITLE
[Bug] [@ mozilla.appservices.places.PlacesException: at mozilla.appservices.places.RustError.intoException(RustError.kt:58) ]

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#20123]
### Steps to reproduce

No steps to reproduce, happened several times while browsing.

### Expected behavior

No crash.

### Actual behavior

mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_places_metadata
* Socorro: https://crash-stats.mozilla.org/report/index/bp-35e93fc3-2c2c-4ab4-ae4b-5eda60210622
----
```
mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_places_metadata
at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
at mozilla.appservices.places.PlacesWriterConnection.noteHistoryMetadataObservation(PlacesConnection.kt:1865)
at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation$suspendImpl(PlacesHistoryStorage.kt:263)
at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation(Unknown Source:0)
at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$createMetadata$1.invokeSuspend(HistoryMetadataService.kt:77)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

/cc @csadilek Seems to be related to your history metadata changes (#20013)? 

### Device information

* Device vendor / model and Android version: OnePlus 7T Pro McLaren / Oxygen OS 11 (Android 11)
* Firefox for Android version: master branch revision 15df06b294018103f7ca4179925d2ffa7695ee52

**Comment by pocmo** [comment]
CC @grigoryk

**Comment by sv-ohorvath** [comment]
One automation test crashed with the same signature: org.mozilla.fenix.ui.ReaderViewTest.verifyReaderViewToggle
[See the Firebase test report](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6800871074703049099/executions/bs.973caaf381d9dd27) (request access to Aaron Train if needed)

Not sure if related to the steps in this particular test, but from the logs, the steps taken were:
1. Load a page that supports reader mode.
2. Toggle reader mode on.
3. Open the main menu.

**Comment by csadilek** [comment]
@cadeyrn Thanks for filing! This feature is still under development and only active in debug builds (not in Nightly etc.) Can you confirm that you ran into this using a custom build?

@pocmo @sv-ohorvath ^^ If this is causing lots of problems on Firebase, we can deactivate until we're back and can fix it. Simply set this flag to `const` `false`:
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L45

**Comment by csadilek** [comment]
@cadeyrn Nevermind, just saw you're running custom build from `15df06b`. See above for how to deactivate the feature that's causing this problem.

**Comment by AndiAJ** [comment]
The following automation tests crashed on **Master 6/25**.

► Flaky 1x `verifyReaderViewAppearanceUI` 
Happened after:
• Switching to reader view
•  Verifying whether the page was properly loaded in reader mode
[Firebase log](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.6b9946c3442ac6d3/testcases/1/logs)

► Flaky 1x `verifyReaderViewAppearanceFontToggle`
Happened after:
• Switching to reader view
• Verifying whether the page was properly loaded in reader mode
• Click the 3 dot button
[Firebase log](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.2b8a18ef11493955/testcases/1/logs) 

• Failed 1x `verifyReaderViewToggle`
Happened after:
• Switching to reader view
[Firebase log 1st attempt](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.d7ef441933710614/testcases/1/logs)
[Firebase log 2nd attempt](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.d799e431f7aba4b0/testcases/1/logs)

• Failed 1x `verifyReaderViewAppearanceColorSchemeChange`
Happened after:
• Switching to reader view
[Firebase log 1st attempt](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.fcac43697c34174c/testcases/1/logs)
[Firebase log 2nd attempt](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5164963279827038499/executions/bs.deedd55f3abc592c/testcases/1/logs
)

```
06-24 15:59:29.774: I/ActivityManager(2070): --------- beginning of crash
06-24 15:59:29.814: E/AndroidRuntime(7396): FATAL EXCEPTION: DefaultDispatcher-worker-4
06-24 15:59:29.814: E/AndroidRuntime(7396): Process: org.mozilla.fenix.debug, PID: 7396
06-24 15:59:29.814: E/AndroidRuntime(7396): mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_places_metadata
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at mozilla.appservices.places.RustError.intoException(RustError.kt:58)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at mozilla.appservices.places.PlacesWriterConnection.noteHistoryMetadataObservation(PlacesConnection.kt:1865)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation$suspendImpl(PlacesHistoryStorage.kt:263)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.noteHistoryMetadataObservation(Unknown Source:0)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$createMetadata$1.invokeSuspend(HistoryMetadataService.kt:77)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
06-24 15:59:29.814: E/AndroidRuntime(7396): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
06-24 15:59:29.829: I/OpenGLRenderer(7396): Davey! duration=10967ms; Flags=0, IntendedVsync=329840245904, Vsync=340756912134, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=340760569924, AnimationStart=340760629300, PerformTraversalsStart=340760843872, DrawStart=340761091457, SyncQueued=340761116387, SyncStart=340774875087, IssueDrawCommandsStart=340775004351, SwapBuffers=340805391150, FrameCompleted=340821346099, DequeueBufferDuration=456000, QueueBufferDuration=118000, 
06-24 15:59:29.830: I/Process(7396): Sending signal. PID: 7396 SIG: 9
06-24 15:59:29.837: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-24 15:59:29.837: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-24 15:59:29.896: E/memtrack(2070): Couldn't load memtrack module
06-24 15:59:29.896: W/android.os.Debug(2070): failed to get memory consumption info: -1
06-24 15:59:29.958: W/InputDispatcher(2070): channel '416ae5e PopupWindow:92b7f5 (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-24 15:59:29.958: E/InputDispatcher(2070): channel '416ae5e PopupWindow:92b7f5 (server)' ~ Channel is unrecoverably broken and will be disposed!
06-24 15:59:29.959: I/Gecko(7694): Exiting due to channel error.
06-24 15:59:29.959: W/InputDispatcher(2070): channel 'bfdcb9d org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-24 15:59:29.959: E/InputDispatcher(2070): channel 'bfdcb9d org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-24 15:59:29.962: I/ActivityManager(2070): Process org.mozilla.fenix.debug (pid 7396) has died: fore TOP 
06-24 15:59:29.963: E/lowmemorykiller(1960): Error writing /proc/7694/oom_score_adj; errno=22
06-24 15:59:29.963: W/libprocessgroup(2070): kill(-7396, 9) failed: No such process
06-24 15:59:29.963: I/WindowManager(2070): WIN DEATH: Window{bfdcb9d u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
06-24 15:59:29.963: W/InputDispatcher(2070): Attempted to unregister already unregistered input channel 'bfdcb9d org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)'
06-24 15:59:29.969: I/WindowManager(2070): WIN DEATH: Window{416ae5e u0 PopupWindow:92b7f5}
06-24 15:59:29.969: W/InputDispatcher(2070): Attempted to unregister already unregistered input channel '416ae5e PopupWindow:92b7f5 (server)'
06-24 15:59:29.973: I/Zygote(1908): Process 7396 exited due to signal (9)
06-24 15:59:29.978: W/WindowManager(2070): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@a78b85a
06-24 15:59:29.980: W/SurfaceFlinger(1961): Attempting to set client state on removed layer: org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity#0
06-24 15:59:29.980: W/SurfaceFlinger(1961): Attempting to destroy on removed layer: org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity#0
06-24 15:59:29.983: W/ActivityManager(2070): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-24 15:59:29.983: I/ActivityManager(2070): Force stopping org.mozilla.fenix.debug appid=10095 user=0: finished inst
06-24 15:59:29.983: I/ActivityManager(2070): Killing 9072:org.mozilla.fenix.debug:crashReportingProcess/u0a95 (adj 900): stop org.mozilla.fenix.debug
```

**Comment by sv-ohorvath** [comment]
@csadilek I've disabled the feature flag to stop the UI tests failures which would block PRs.
