### ISSUE TITLE
Crash in [@ java.lang.NoClassDefFoundError: at o.DefaultImageHeaderParser$Reader$EndOfFileException.IconCompatParcelizer(Unknown Source:27)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#20159]
Crash report: https://crash-stats.mozilla.org/report/index/4bb7f0e7-a993-4d72-aa2d-0d7550210624

Java stack trace:
```
java.lang.NoClassDefFoundError
	at o.DefaultImageHeaderParser$Reader$EndOfFileException.IconCompatParcelizer(Unknown Source:27)
	at o.DownsampleStrategy$SampleSizeRounding.RemoteActionCompatParcelizer(Unknown Source:33)
	at o.TokenStreamFactory.write(Unknown Source:146)
	at o.TokenStreamFactory.run(Unknown Source:115)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by kbrosnan** [comment]
- https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.NoClassDefFoundError%3A%20at%20o.DefaultImageHeaderParser%24Reader%24EndOfFileException.IconCompatParcelizer%28Unknown%20Source%3A27%29

This only happens on ancient versions of Fenix 4.4. Users should upgrade to a current version.
