### ISSUE TITLE
Crash in [@ java.util.ServiceConfigurationError: at o.DownsampleStrategy$SampleSizeRounding.RemoteActionCompatParcelizer(Unknown Source)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#20157]
Crash report: https://crash-stats.mozilla.org/report/index/67b18964-0fa9-45b5-8d74-f34360210624

Java stack trace:
```
java.util.ServiceConfigurationError
	at o.DownsampleStrategy$SampleSizeRounding.RemoteActionCompatParcelizer(Unknown Source)
	at o.TokenStreamFactory.write(Unknown Source)
	at o.TokenStreamFactory.run(Unknown Source)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.read(Unknown Source)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$RemoteActionCompatParcelizer.run(Unknown Source)
```

**Comment by kbrosnan** [comment]
This is happening on Fenix 4.4.0 which is ancient. Users should upgrade to a current version.
