### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at android.database.CursorWindow.nativeGetString(Native Method)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/fenix#20160]
Crash report: https://crash-stats.mozilla.org/report/index/1de4433c-9fa5-4e2e-87e7-602880210624

Java stack trace:
```
java.lang.IllegalStateException
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:438)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
	at mozilla.components.feature.downloads.db.DownloadDao_Impl$10.call(DownloadDao_Impl.java:12)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by kbrosnan** [comment]
* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IllegalStateException%3A at android.database.CursorWindow.nativeGetString(Native Method)
* https://sentry.prod.mozaws.net/operations/firefox/issues/10951330/
* https://sentry.prod.mozaws.net/operations/firefox-beta/issues/11199671/

Might be resolved in 90.
