### ISSUE TITLE
NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20269]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11727998/?referrer=github_plugin

```
NimbusErrorException$DatabaseNotReady: Initialization of the database is not yet complete
    at org.mozilla.fenix.home.HomeMenu.<init>(HomeMenu.kt:64)
    at org.mozilla.fenix.home.HomeFragment$onViewCreated$1.invoke(HomeFragment.kt:10)
    at org.mozilla.fenix.home.HomeFragment.onViewCreated(HomeFragment.kt:1)
    at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:13)
    at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:2)
...
(47 additional frame(s) were not displayed)

[INFO] Initialization of the database is not yet complete
```

**Comment by jonalmeida** [comment]
These three issues (https://github.com/mozilla-mobile/fenix/issues/20267, https://github.com/mozilla-mobile/fenix/issues/20268, https://github.com/mozilla-mobile/fenix/issues/20269) all spiked on June 23rd in Sentry together because that was when we started to use the crash reporter in Nimbus. I don't believe they are new issues, but it is still something we need to address as clients are failing to register for an experiments.

**Comment by jonalmeida** [comment]
This looks like a legitimate case where we need Nimbus init'd for experiments in the three-dot menu.

cc: @jhugman @travis79

**Comment by jonalmeida** [comment]
Spoke offline to James, this is being worked on SDK-304 by the Nimbus team.
