### ISSUE TITLE
NimbusErrorException$RequestError: Network error: "fetch error: java.net.SocketTimeoutException"

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20267]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11722256/?referrer=github_plugin

```
NimbusErrorException$RequestError: Error sending request: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:14)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:13)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.fetchExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
...
(6 additional frame(s) were not displayed)

[INFO] Error sending request: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
```

**Comment by jonalmeida** [comment]
These three issues (https://github.com/mozilla-mobile/fenix/issues/20267, https://github.com/mozilla-mobile/fenix/issues/20268, https://github.com/mozilla-mobile/fenix/issues/20269) all spiked on June 23rd in Sentry together because that was when we started to use the crash reporter in Nimbus. I don't believe they are new issues, but it is still something we need to address as clients are failing to register for an experiments.

**Comment by jonalmeida** [comment]
SocketTimeout doesn't seem like something we can do anything about, but do we need to report this? For AutoPushFeature, we [filter out](https://github.com/mozilla-mobile/android-components/blob/ba029513b70fc15c771461c8d853f84b62a037bf/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L362-L377) the non-fatal exceptions that the native layers throw - this might be an option here.

cc: @jhugman @travis79

**Comment by jonalmeida** [comment]
Spoke offline to James, we can filter out this error since it's not useful.
