### ISSUE TITLE
NimbusErrorException$InternalError: Internal error: New experiment but enrollment already exists.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20268]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11763273/?referrer=github_plugin

```
NimbusErrorException$InternalError: Internal error: New experiment but enrollment already exists.
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:9)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.applyPendingExperiments(nimbus.kt:15)
    at org.mozilla.experiments.nimbus.-$$LambdaGroup$ks$FFGd6J-jWuYuF4BxN9FoSzJwXkw.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:4)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.applyPendingExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
...
(6 additional frame(s) were not displayed)

[INFO] Internal error: New experiment but enrollment already exists.
```

**Comment by jonalmeida** [comment]
These three issues (https://github.com/mozilla-mobile/fenix/issues/20267, https://github.com/mozilla-mobile/fenix/issues/20268, https://github.com/mozilla-mobile/fenix/issues/20269) all spiked on June 23rd in Sentry together because that was when we started to use the crash reporter in Nimbus. I don't believe they are new issues, but it is still something we need to address as clients are failing to register for an experiments.

**Comment by jonalmeida** [comment]
Another case of exceptions that we can ignore? See https://github.com/mozilla-mobile/fenix/issues/20267#issuecomment-874859298.

**Comment by jonalmeida** [comment]
Spoke offline to James, this is being investigated by the Nimbus team.
