### ISSUE TITLE
DiskWriteViolation in LocaleManager.getCurrentLocale during Application.attachBaseContext

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20314]
All Robolectric tests that need a `testContext` will instantiate an application class that performs a write on startup.

Does this have a major impact to non-test application starts as well?

```
[task 2021-07-09T16:21:13.464Z]     [Robolectric] org.mozilla.fenix.home.recenttabs.view.RecentTabViewHolderTest.WHEN a recent tab does not have a title THEN show the url: sdk=28; resources=BINARY
[task 2021-07-09T16:21:13.464Z]     D/StrictMode: onThreadPolicyViolation; policy=65597
[task 2021-07-09T16:21:13.464Z]     D/StrictMode: StrictMode policy violation; ~duration=0 ms: android.os.strictmode.DiskWriteViolation
[task 2021-07-09T16:21:13.464Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.$$robo$$android_os_StrictMode_AndroidBlockGuardPolicy$onWriteToDisk(StrictMode.java:1460)
[task 2021-07-09T16:21:13.464Z]     at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java)
[task 2021-07-09T16:21:13.464Z]     at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$mkdir(BlockGuardOs.java:196)
[task 2021-07-09T16:21:13.464Z]     at libcore.io.BlockGuardOs.mkdir(BlockGuardOs.java)
[task 2021-07-09T16:21:13.464Z]     at android.system.Os.$$robo$$android_system_Os$mkdir(Os.java:323)
[task 2021-07-09T16:21:13.464Z]     at android.system.Os.mkdir(Os.java)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:608)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$ensurePrivateDirExists(ContextImpl.java:596)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getPreferencesDir(ContextImpl.java:552)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.getPreferencesDir(ContextImpl.java)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferencesPath(ContextImpl.java:747)
[task 2021-07-09T16:21:13.464Z]     at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java)
[task 2021-07-09T16:21:13.465Z]     at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSharedPreferences(ContextImpl.java:400)
[task 2021-07-09T16:21:13.465Z]     at android.app.ContextImpl.getSharedPreferences(ContextImpl.java)
[task 2021-07-09T16:21:13.465Z]     at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:140)
[task 2021-07-09T16:21:13.465Z]     at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:116)
[task 2021-07-09T16:21:13.465Z]     at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:48)
[task 2021-07-09T16:21:13.465Z]     at mozilla.components.support.locale.LocaleManager.updateResources$support_locale_release(LocaleManager.kt:80)
[task 2021-07-09T16:21:13.465Z]     at mozilla.components.support.locale.LocaleAwareApplication.attachBaseContext(LocaleAwareApplication.kt:17)
[task 2021-07-09T16:21:13.465Z]     at android.app.Application.$$robo$$android_app_Application$attach(Application.java:212)
[task 2021-07-09T16:21:13.465Z]     at android.app.Application.attach(Application.java)
[task 2021-07-09T16:21:13.465Z]     at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
[task 2021-07-09T16:21:13.465Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2021-07-09T16:21:13.465Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.shadows.ShadowApplication.callAttach(ShadowApplication.java:79)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:250)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
[task 2021-07-09T16:21:13.465Z]     at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
[task 2021-07-09T16:21:13.466Z]     at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2021-07-09T16:21:13.466Z]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2021-07-09T16:21:13.466Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2021-07-09T16:21:13.466Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2021-07-09T16:21:13.466Z]     at java.lang.Thread.run(Thread.java:748)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17214)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813660

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
