### ISSUE TITLE
NimbusErrorException$ResponseError: Error in network response

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#20341]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11729364/?referrer=github_plugin

```
NimbusErrorException$ResponseError: Error in network response: 
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:13)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:13)
    at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.fetchExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
...
(6 additional frame(s) were not displayed)

[INFO] Error in network response: 
```

**Comment by jonalmeida** [comment]
Similar to https://github.com/mozilla-mobile/fenix/issues/20267, but leaving this up to @jhugman to confirm since it isn't nearly as noisy, so I'm unsure if it's a genuine error or not.
