### ISSUE TITLE
Intermittent test failure - PROCESS-CRASH | pid: None | application crashed [@ system@framework@boot-core-oj.art + 0x43cce]

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#20408]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=345535239&repo=fenix
### Stacktrace:
```
[task 2021-07-18T06:21:57.728Z] 06:21:57    ERROR -  raptor-browsertime Error: Browsertime failed to run
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime Info: b'    at Object.throwDecodedError (/builds/task_162658769693165/fetches/browsertime/node_modules/selenium-webdriver/lib/error.js:517:15)'
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime Info: b'    at parseHttpResponse (/builds/task_162658769693165/fetches/browsertime/node_modules/selenium-webdriver/lib/http.js:655:13)'
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime Info: b'    at Executor.execute (/builds/task_162658769693165/fetches/browsertime/node_modules/selenium-webdriver/lib/http.js:581:28)'
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime Info: b'    at process._tickCallback (internal/process/next_tick.js:68:7)'
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime Info: URL failed to load, trying 5 more time(s): Failed waiting on page https://www.youtube.com/watch?v=COU5T-Wafa4  to finished loading, timed out after 300000 ms
[task 2021-07-18T06:21:57.728Z] 06:21:57 CRITICAL -  raptor-browsertime Critical: Failed waiting on page https://www.youtube.com/watch?v=COU5T-Wafa4 to finished loading, timed out after 300000 ms WebDriverError: Failed to decode response from marionette
[task 2021-07-18T06:21:57.728Z] 06:21:57     INFO -  raptor-browsertime-android Info: removing reverse socket connections
[task 2021-07-18T06:22:07.750Z] 06:21:57     INFO -  adb command_output: adb -s ZY32259TSG wait-for-device reverse --remove-all, timeout: None, timedout: None, exitcode: 0, output:
[task 2021-07-18T06:22:07.750Z] 06:21:58     INFO -  adb shell_bool: adb -s ZY32259TSG wait-for-device shell su -c 'test -d /sdcard/Android/data/org.mozilla.fenix/files/test_root/org.mozilla.fenix-geckodriver-profile/minidumps', timeout: None, timedout: None, exitcode: 0, output:
[task 2021-07-18T06:22:07.750Z] 06:21:59     INFO -  adb shell_output: adb -s ZY32259TSG wait-for-device shell su -c sync, timeout: None, timedout: None, exitcode: 0, output:
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  adb shell_bool: adb -s ZY32259TSG wait-for-device shell su -c 'test -d /sdcard/Android/data/org.mozilla.fenix/files/test_root/org.mozilla.fenix-geckodriver-profile/minidumps', timeout: None, timedout: None, exitcode: 0, output:
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  adb chmod: path=/sdcard/Android/data/org.mozilla.fenix/files/test_root/org.mozilla.fenix-geckodriver-profile/minidumps, recursive=True, mask=777
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  adb shell_output: adb -s ZY32259TSG wait-for-device shell set, timeout: None, timedout: None, exitcode: 0, output: ANDROID_ASSETS=/system/app
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ANDROID_BOOTLOGO=1
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ANDROID_DATA=/data
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ANDROID_ROOT=/system
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ANDROID_SOCKET_adbd=9
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ANDROID_STORAGE=/storage
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  ASEC_MOUNTPOINT=/mnt/asec
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  BASHPID=18602
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  BOOTCLASSPATH=/system/framework/prcui-config.jar:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/qcom.fmradio.jar:/system/framework/oem-services.jar:/system/framework/tcmiface.jar:/system/framework/telephony-ext.jar
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  COLUMNS
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  EPOCHREALTIME=1626589321.174049
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  EXTERNAL_STORAGE=/sdcard
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  HOME=/
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  IFS=$' \t\n'
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  KSHEGID=2000
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  KSHGID=2000
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  KSHUID=2000
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  KSH_VERSION='@(#)MIRBSD KSH R52 2016/01/20'
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  LINES
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  LOGNAME=shell
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  OPTIND=1
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PGRP=18602
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PIPESTATUS=0
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PPID=5558
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PS1='$ '
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PS2='> '
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PS3='#? '
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PS4='+ '
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  PWD=/
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  RANDOM=8883
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  SECONDS=0
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  SHELL=/system/bin/sh
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  TERM=dumb
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  TMOUT=0
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  USER=shell
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  USER_ID=2000
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  adb Ignoring attempt to chmod external storage
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  adb command_output: adb -s ZY32259TSG wait-for-device pull /sdcard/Android/data/org.mozilla.fenix/files/test_root/org.mozilla.fenix-geckodriver-profile/minidumps /tmp/tmpz98uey7v/minidumps, timeout: None, timedout: None, exitcode: 0, output: /sdcard/Android/data/org.mozilla.fenix/files/test_root/org.mozilla.fenix-geckodriver-profile/minidumps/: 1 file pulled, 0 skipped. 9.6 MB/s (1079792 bytes in 0.108s)
[task 2021-07-18T06:22:07.750Z] 06:22:00     INFO -  mozcrash Downloading symbols from: https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/adGo5R1jTvSU_77OrUmTzw/artifacts/public/build/en-US/target.crashreporter-symbols.zip
[task 2021-07-18T06:22:07.750Z] 06:22:03     INFO -  mozcrash Copy/paste: /builds/task_162658769693165/fetches/minidump_stackwalk/minidump_stackwalk /tmp/tmpsu9uuges/095090d0-d6b9-6b88-5f56-b571e9e57828.dmp /tmp/tmpc2br0r7v
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  mozcrash Saved minidump as /builds/task_162658769693165/workspace/build/blobber_upload_dir/095090d0-d6b9-6b88-5f56-b571e9e57828.dmp
[task 2021-07-18T06:22:07.750Z] 06:22:07    ERROR -  PROCESS-CRASH | pid: None | application crashed [@ system@framework@boot-core-oj.art + 0x43cce]
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Crash dump filename: /tmp/tmpsu9uuges/095090d0-d6b9-6b88-5f56-b571e9e57828.dmp
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Operating system: Android
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -                    0.0.0 Linux 3.18.31-perf-g708ac5e #1 SMP PREEMPT Fri Jan 13 08:46:35 CST 2017 armv7l
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  CPU: arm
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       ARMv7 ARM part(0x4100d030) features: half,thumb,fastmult,vfpv2,edsp,neon,vfpv3,tls,vfpv4,idiva,idivt
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       8 CPUs
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  GPU: UNKNOWN
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Crash reason:  SIGSEGV /SEGV_MAPERR
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Crash address: 0x78380000
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Process uptime: not available
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  Thread 132 (crashed) 0  0xa68d10e4
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       r0 = 0x7837ff03    r1 = 0x00000080    r2 = 0x00000020    r3 = 0x88eb7be0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       r4 = 0x88eb7be0    r5 = 0x00000020    r6 = 0x88eb7bf0    r7 = 0x7837ffe3
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       r8 = 0x000000fc    r9 = 0x7837ff83   r10 = 0x00000020   r12 = 0x00000020
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       fp = 0x00000001    sp = 0x5e7de298    lr = 0x88eb7bc0    pc = 0xa68d10e4
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: given as instruction pointer in context
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   1  system@framework@boot-core-oj.art + 0x43cce
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de2d8    pc = 0x6f957cd0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   2  dalvik-main space (deleted) + 0x7433e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de2f0    pc = 0x12c74340
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   3  dalvik-main space (deleted) + 0x1ce11a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de300    pc = 0x12dce11c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   4  system@framework@boot-core-oj.art + 0x3e326a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de308    pc = 0x6fcf726c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   5  dalvik-main space (deleted) + 0x7bb45e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de30c    pc = 0x133bb460
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   6  dalvik-main space (deleted) + 0x7433e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de310    pc = 0x12c74340
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   7  system@framework@boot-core-oj.art + 0x3e308a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de318    pc = 0x6fcf708c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   8  libart.so + 0xaae63
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de320    pc = 0xa4a3ee65
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -   9  system@framework@boot.art + 0x8a2c6
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de324    pc = 0x6f9122c8
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  10  system@framework@boot-core-oj.art + 0x3e326a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de32c    pc = 0x6fcf726c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  11  dalvik-main space (deleted) + 0x7bb45e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de330    pc = 0x133bb460
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  12  dalvik-main space (deleted) + 0x7433e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de334    pc = 0x12c74340
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  13  system@framework@boot-core-oj.art + 0x3e308a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de338    pc = 0x6fcf708c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  14  boot-core-oj.oat + 0x5ee3c5
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de340    pc = 0x709753c7
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  15  system@framework@boot-core-oj.art + 0x362c22
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de344    pc = 0x6fc76c24
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  16  dalvik-main space (deleted) + 0xb1dbe
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de348    pc = 0x12cb1dc0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  17  dalvik-main space (deleted) + 0x1ce0ae
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de34c    pc = 0x12dce0b0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  18  boot-core-oj.oat + 0x5ebfc9
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de350    pc = 0x70972fcb
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  19  system@framework@boot-core-oj.art + 0x361fc2
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de354    pc = 0x6fc75fc4
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  20  dalvik-main space (deleted) + 0x1ce0ae
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de358    pc = 0x12dce0b0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  21  dalvik-main space (deleted) + 0x7bb46e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de35c    pc = 0x133bb470
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  22  dalvik-main space (deleted) + 0x7bb45e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de360    pc = 0x133bb460
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  23  dalvik-zygote space (deleted) + 0x2df36
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de364    pc = 0x7413af38
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  24  libart.so + 0x2715fb
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3c8    pc = 0xa4c055fd
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  25  system@framework@boot-core-oj.art + 0x351c86
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3cc    pc = 0x6fc65c88
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  26  libart.so + 0x23c6b3
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3d0    pc = 0xa4bd06b5
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  27  system@framework@boot-core-oj.art + 0x36a426
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3d4    pc = 0x6fc7e428
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  28  dalvik-main space (deleted) + 0x19a73e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3d8    pc = 0x12d9a740
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  29  dalvik-main space (deleted) + 0x9ff9fe
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3e8    pc = 0x135ffa00
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  30  system@framework@boot-core-oj.art + 0x3e120a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3ec    pc = 0x6fcf520c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  31  boot-core-oj.oat + 0x57e7e1
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3f0    pc = 0x709057e3
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  32  system@framework@boot-core-oj.art + 0x36a502
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de3f4    pc = 0x6fc7e504
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  33  libart.so + 0xa91c1
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de410    pc = 0xa4a3d1c3
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  34  dalvik-main space (deleted) + 0x7bb43e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de418    pc = 0x133bb440
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  35  dalvik-main space (deleted) + 0x9ff9fe
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de41c    pc = 0x135ffa00
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  36  boot-core-oj.oat + 0x312b29
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de428    pc = 0x70699b2b
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  37  libart.so + 0x40324b
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de448    pc = 0xa4d9724d
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  38  libc.so + 0x57947
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de470    pc = 0xa6057949
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  39  libc.so + 0x585f5
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de498    pc = 0xa60585f7
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  40  libc.so + 0x613d1
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de528    pc = 0xa60613d3
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  41  system@framework@boot-core-oj.art + 0x3cab9e
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de534    pc = 0x6fcdeba0
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  42  system@framework@boot-core-libart.art + 0x5bd6
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de538    pc = 0x6fd98bd8
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -  43  dalvik-non moving space (deleted) + 0x1882a
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -       sp = 0x5e7de550    pc = 0x7423c82c
[task 2021-07-18T06:22:07.750Z] 06:22:07     INFO -      Found by: stack scanning
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/41ba94b9517f9d61dcfc147c910de1ecc189f4fd

**Comment by Archaeopteryx** [comment]
Since this crash started, the [libskia.so](https://bugzilla.mozilla.org/show_bug.cgi?id=1717440) one is gone.
