### ISSUE TITLE
Crash in [@ android.app.RemoteServiceException: at android.app.ActivityThread$H.handleMessage(ActivityThread.java)]

### ISSUE THREAD

**Issue by DontTheyNeedYourhelp** [mozilla-mobile/fenix#20400]
Crash report: https://crash-stats.mozilla.org/report/index/5233fd1b-e505-409d-bb08-960e10210627

Java stack trace:
```
android.app.RemoteServiceException
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by kbrosnan** [comment]
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{94f2c84 u0 org.mozilla.firefox/org.mozilla.fenix.media.MediaSessionService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

**Comment by kbrosnan** [comment]
Previously https://github.com/mozilla-mobile/android-components/issues/7984

https://sentry.prod.mozaws.net/operations/firefox/issues/9264391/

https://crash-stats.mozilla.org/signature/?product=Fenix&signature=android.app.RemoteServiceException%3A%20at%20android.app.ActivityThread%24H.handleMessage%28ActivityThread.java%29
