### ISSUE TITLE
Intermittent UI test failure - <TopSitesTest.verifyRemoveTopSite>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20418]
### Stacktrace: 
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifySnackBarText(BrowserRobot.kt:114)
at org.mozilla.fenix.ui.TopSitesTest$verifyRemoveTopSite$4.invoke(TopSitesTest.kt:162)
at org.mozilla.fenix.ui.TopSitesTest$verifyRemoveTopSite$4.invoke(TopSitesTest.kt:29)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.addToFirefoxHome(ThreeDotMenuMainRobot.kt:295)
at org.mozilla.fenix.ui.TopSitesTest.verifyRemoveTopSite(TopSitesTest.kt:161)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7025931150273937114/executions/bs.e527200abd3ba86d/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.9f58e31281525b29/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 3/25 debug: 
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id is <org.mozilla.fenix.debug:id/top_sites_list>)
`
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6597984534487927757/executions/bs.d40719dd16856fac

**Comment by AndiAJ** [comment]
Flaky 1x on 3/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4795469606298877166/executions/bs.ceade64a321c5521/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5890873202605813445/executions/bs.fa91431cb6f05f44/testcases/1/test-cases)
