### ISSUE TITLE
Crash in [@ android.os.FileUriExposedException: file:/// exposed beyond app through Intent.getData()]

### ISSUE THREAD

**Issue by DavidCRicardo** [mozilla-mobile/fenix#20414]
### Steps to reproduce

Open a pdf file on my firefox desktop
Send tab to device. 
The firefox on the device always crashes with this process.

### Expected behaviour

I can see the tab on my device 

### Actual behaviour

A message box should open and say that you need to restart Firefox on your device

### Android version

Android 7

### Firefox release type

Firefox

### Firefox version

90.1.1

**Comment by Amejia481** [comment]
👋🏽 
Thanks for reporting @DavidCRicardo , if it's a public resource would you mind sharing the link?  :)

**Comment by kbrosnan** [comment]
The specific file/url does not matter.  Any file:/// URI will crash Firefox.

```
android.os.FileUriExposedException: file:///[REDACTED] exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2141)
	at android.net.Uri.checkFileUriExposed(Uri.java:2391)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11152)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11104)
	at android.app.PendingIntent.getActivity(PendingIntent.java:355)
	at android.app.PendingIntent.getActivity(PendingIntent.java:317)
	at org.mozilla.fenix.components.NotificationManager.showReceivedTabs(NotificationManager.kt:6)
	at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$$inlined$also$lambda$1.invoke(BackgroundServices.kt:3)
	at mozilla.components.feature.accounts.push.EventsObserver.onEvents(SendTabFeature.kt:7)
	at mozilla.components.service.fxa.-$$LambdaGroup$ks$ro7rEtSJwcc4uzMXErsGW2kmug8.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:8)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.AccountEventsIntegration.onEvents(AccountStorage.kt:2)
	at mozilla.components.service.fxa.-$$LambdaGroup$ks$ro7rEtSJwcc4uzMXErsGW2kmug8.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers(Unknown Source:7)
	at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2.invokeSuspend(FxaDeviceConstellation.kt:8)
	at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2.invoke(FxaDeviceConstellation.kt:2)
	at androidx.core.app.AppOpsManagerCompat.startUndispatchedOrReturn(AppOpsManagerCompat.java:2)
	at kotlinx.coroutines.AwaitKt.withContext(Await.kt:9)
	at mozilla.components.service.fxa.FxaDeviceConstellation.pollForCommands(FxaDeviceConstellation.kt:1)
	at mozilla.components.service.fxa.FxaDeviceConstellation$refreshDevices$2.invokeSuspend(FxaDeviceConstellation.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kbrosnan** [comment]
* https://sentry.prod.mozaws.net/operations/firefox/issues/10464684/
* https://sentry.prod.mozaws.net/operations/firefox-beta/issues/11181514/
* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=android.os.FileUriExposedException%3A%20at%20android.os.StrictMode.onFileUriExposed%28StrictMode.java%29

**Comment by DavidCRicardo** [comment]
Will you don't fix this issue? Don't forget that you are still having this bug.

**Comment by kbrosnan** [comment]
Sending the file URI won't do anything useful. The file will not be found, http error 404. This can be avoided by not sending file URIs.

**Comment by skhamis** [comment]
@kbrosnan I'm currently looking into this from the a-s side of things --> Is this still reproducible? I've been trying it on my emulator and with nightly I can't seem to get it to crash, instead it shows a nice: 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/436430/158489977-a9fd1f97-17fc-4175-b39a-0ecf0fd9a52a.png">

**Comment by kbrosnan** [comment]
Still crashed my nightly and beta on receiving the tab. https://crash-stats.mozilla.org/report/index/58dfac8d-c3fb-42cb-a3bc-8573f0220318
