### ISSUE TITLE
Intermittent UI test failure - closePrivateTabsNotificationTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#20433]
### Firebase Test Run:
https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8906963029425277909/executions/bs.c2f7edc2f22dc798/issues### Stacktrace:
`java.lang.IllegalArgumentException
	at androidx.core.text.TextDirectionHeuristicsCompat$TextDirectionHeuristicImpl.isRtl(TextDirectionHeuristicsCompat.java:131)
	at mozilla.components.support.utils.URLStringUtils.toDisplayUrl(URLStringUtils.kt:110)
	at mozilla.components.support.utils.URLStringUtils.toDisplayUrl$default(URLStringUtils.kt:104)
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView$2$1$2.invoke(BrowserToolbarView.kt:121)
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView$2$1$2.invoke(BrowserToolbarView.kt:121)
	at mozilla.components.browser.toolbar.display.DisplayToolbar.setUrl$browser_toolbar_release(DisplayToolbar.kt:485)
	at mozilla.components.browser.toolbar.BrowserToolbar.setUrl(BrowserToolbar.kt:110)
	at mozilla.components.feature.toolbar.internal.URLRenderer.updateUrl$feature_toolbar_release(URLRenderer.kt:67)
	at mozilla.components.feature.toolbar.internal.URLRenderer$start$1.invokeSuspend(URLRenderer.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`
### Build: 
7/19

Fixed when https://github.com/mozilla-mobile/android-components/pull/10640 is merged into Fenix

**Comment by sv-ohorvath** [comment]
The fix was merged, the test is no longer disbaled. We can close this.

**Comment by sv-ohorvath** [comment]
Waiting for the new AC version.

**Comment by sv-ohorvath** [comment]
Landed. closing.
