### ISSUE TITLE
[Bug] Fenix crashes after disabling "Show most visited sites" and returning to the homescreen

### ISSUE THREAD

**Issue by lobontiumira** [mozilla-mobile/fenix#20449]
### Steps to reproduce

1. Go to Settings - Customize - Show most visited sites, and disable it.
2. Tap back to reach the homescreen.

### Expected behaviour

The user is redirected to the homescreen without issues.

### Actual behaviour

Fenix crashes.

### Device name

Google Pixel, HTC 10

### Android version

Android 10, Android 8

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 from 7/21

### Device logs

754156d2-b1cf-41d6-9ebb-a3239739e44c
java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
* Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=60375c90e4ce48dcbdc5d77ccb8882b2
* Socorro: https://crash-stats.mozilla.org/report/index/bp-3e919f7a-0419-4e23-a6f0-9f1180210721
----
java.lang.IndexOutOfBoundsException: Index: 6, Size: 5
at java.util.ArrayList.remove(ArrayList.java:503)
at org.mozilla.fenix.home.sessioncontrol.viewholders.topsites.TopSitesPagerAdapter.onBindViewHolder(TopSitesPagerAdapter.kt:25)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:135)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
at android.view.View.measure(View.java:22072)
at android.view.ViewGroup.measureChild(ViewGroup.java:6580)
at androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:1)
at android.view.View.measure(View.java:22072)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6609)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:22072)
at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:16)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:11)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:22)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
at android.view.View.layout(View.java:19653)
at android.view.ViewGroup.layout(ViewGroup.java:6082)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2626)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2321)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1466)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6982)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
at android.view.Choreographer.doCallbacks(Choreographer.java:729)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:180)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

### Additional information

https://user-images.githubusercontent.com/40694158/126450165-15a14b71-fe88-4246-8f73-d466e87903a5.mp4

**Comment by csadilek** [comment]
Adding Nightly Sentry issue link: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11937189/

Spiking in the last 3 days.

**Comment by csadilek** [comment]
@codrut-topliceanu ^^ this looks to be a regression of https://github.com/mozilla-mobile/fenix/commit/bc723e0a9b377766861c188cb5c8cde6a6b48344. Can you take a look? It's spiking a bit too much. Could also back out if it needs more investigation and take time :).

**Comment by jonalmeida** [comment]
Sentry issue: [FIREFOX-NIGHTLY-BSY](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/11937189/?referrer=github_plugin)

**Comment by codrut-topliceanu** [comment]
> @codrut-topliceanu ^^ this looks to be a regression of [bc723e0](https://github.com/mozilla-mobile/fenix/commit/bc723e0a9b377766861c188cb5c8cde6a6b48344). Can you take a look? It's spiking a bit too much. Could also back out if it needs more investigation and take time :).

Confirmed 😞

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed in the latest Nightly (92.0a1 20210728T05:08:41.498400).

Devices used:

- Google Pixel 4 (Android 11)
- Samsung Galaxy Tab 3 (Android 9).
