### ISSUE TITLE
Crash in [@ org.json.JSONException: at org.json.JSON.typeMismatch(JSON.java)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#20472]
Crash report: https://crash-stats.mozilla.org/report/index/423c8b56-9fa0-4a05-94f0-51e670210719

Java stack trace:
```
org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.mozilla.geckoview.GeckoSession$SessionState.fromString(GeckoSession.java:1)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.tab(BrowserStateReader.kt:69)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReaderKt.access$browsingSession(BrowserStateReader.kt:11)
	at mozilla.components.browser.session.storage.serialize.BrowserStateReader.read(BrowserStateReader.kt:3)
	at mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:3)
	at mozilla.components.feature.tabs.TabsUseCases$RestoreUseCase$invoke$2.invokeSuspend(TabsUseCases.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

**Comment by kbrosnan** [comment]
Looks like this is a native crash so should be tracked in Bugzilla.  bz-1721861
