### ISSUE TITLE
[Bug]: Crash when some older versions of Chrome share links with Firefox

### ISSUE THREAD

**Issue by hokonch** [mozilla-mobile/fenix#20497]
### Steps to reproduce

1. Ensure the version of Chrome is between v80 to v84.
2. Open a website in Chrome and press and hold a link to share it to Firefox.
3. Firefox opens, but the icon in the Recents Screen is strangely Chrome.
4. Press and hold a link to share it to Firefox.
5. Crash

### Expected behaviour

Firefox will not crash under any circumstances.

### Actual behaviour

If you follow steps to reproduce, Firefox will crash every time. 

### Device name

Google Pixel 3a

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

90.1.2

### Device logs
09561911-de03-43c4-83e3-15af2c52e690
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 213732814 Other activity: HomeActivity hashcode 73457510
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=1cc2615d0d1744e78c10093e2fe9f595
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-0ec9a936-4f8e-46b9-8a88-fbcf00210725
----
```
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 213732814 Other activity: HomeActivity hashcode 73457510
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:18)
	at mozilla.components.feature.session.engine.EngineViewPresenter.access$onTabToRender(EngineViewPresenter.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:2)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:9)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 15 more
```

### Additional information

- I noticed this issue when I did a factory reset on my Pixel 3a, whose preinstalled version of Chrome is v83.
- I used Chrome Beta downloaded from APKmirror to identify the problematic Chrome version.
- I'm not sure if this issue is valid because it seems to be fixed in the current Chrome. If not, please feel free to close it.

https://user-images.githubusercontent.com/54430032/126887969-99c48f67-59bb-49c6-9c56-c486710357b7.mp4

**Comment by kbrosnan** [comment]
We made some changes to the intent handling in [Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) would you check if that version still reproduces this crash?

**Comment by hokonch** [comment]
Unfortunately it is still reproducible.

---

c6902e3e-c94a-44b5-b821-1126aca2c0f8
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 235566606 Other activity: HomeActivity hashcode 122768734
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=f3d1f2bedd834e2694e8fa3b1ee5f14e
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-b560dd85-aaa4-4605-8be3-e7a950210813
----
~~~
java.lang.IllegalStateException: SET SESSION: Current activity: HomeActivity hashcode 235566606 Other activity: HomeActivity hashcode 122768734
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:16)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:15)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:20)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: Display already acquired
	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:4)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:10)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	... 14 more
~~~
