### ISSUE TITLE
[Crash] NPE at DeleteBrowsingDataFragment deleteSelected

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/fenix#20543]
Crash report: https://crash-stats.mozilla.org/report/index/f5d52a02-ce5c-4960-bc66-28ea10210727

Java stack trace:
```
java.lang.NullPointerException
	at org.mozilla.fenix.settings.deletebrowsingdata.DeleteBrowsingDataFragment.access$deleteSelected(DeleteBrowsingDataFragment.kt:1)
	at org.mozilla.fenix.settings.deletebrowsingdata.DeleteBrowsingDataFragment$askToDelete$$inlined$let$lambda$1.onClick(DeleteBrowsingDataFragment.kt:2)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/18438
