### ISSUE TITLE
Intermittent debug(T) - 	java.lang.NullPointerException: Metric has no value

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#20616]
3 failures on fenix master so far, oldest for https://github.com/mozilla-mobile/fenix/commit/150a5a739e74ac6bf279b9472cede619fc41161c - one of them is for `WHEN reporting THEN the values from the storageStats are accumulated(StorageStatsMetricsTest.kt:51)`

### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=347091171&repo=fenix
### Stacktrace:
```
SUITE: org.mozilla.fenix.library.recentlyclosed.RecentlyClosedFragmentInteractorTest
  FAILURE

java.lang.NullPointerException: Metric has no value
	at mozilla.telemetry.glean.private.BooleanMetricType.testGetValue(BooleanMetricType.kt:120)
	at mozilla.telemetry.glean.private.BooleanMetricType.testGetValue$default(BooleanMetricType.kt:115)
	at org.mozilla.fenix.FenixApplicationTest.WHEN setStartupMetrics is called THEN sets some base metrics(FenixApplicationTest.kt:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/6f3d21b48dff0e1309d828e8eb97f97cc2c7e460

**Comment by Archaeopteryx** [comment]
This needs the probe renewal from #20520

**Comment by mcomella** [comment]
> This needs the probe renewal from #20520

It's https://github.com/mozilla-mobile/fenix/issues/20518 now – we had two issues and I resolved the duplicate.

**Comment by mcomella** [comment]
The failing line is `assertEquals(true, Metrics.defaultBrowser.testGetValue())`, which seems unrelated to the performance probes in the issues mentioned above.

**Comment by mcomella** [comment]
> wrt to the stack trace in the initial comment, the failing line is assertEquals(true, Metrics.defaultBrowser.testGetValue()), which seems unrelated to the performance probes in the issues mentioned above.

I think this is addressed by https://github.com/mozilla-mobile/fenix/pull/20517

**Comment by eliserichards** [comment]
This should be resolved now.
