### ISSUE TITLE
Intermittent UI test failure - <SmokeTest.customTabMenuItemsTest>

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#20644]
### Firebase Test Run:
Flaky
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9035031709302394425/executions/bs.fd4cb0aacfe59e68/testcases/1/test-cases
### Stacktrace:
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at org.mozilla.fenix.ui.robots.CustomTabRobot.verifyRefreshButtonExists(CustomTabRobot.kt:47)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$2.invoke(SmokeTest.kt:1269)
at org.mozilla.fenix.ui.SmokeTest$customTabMenuItemsTest$2.invoke(SmokeTest.kt:1261)
at org.mozilla.fenix.ui.robots.CustomTabRobot$Transition.openMainMenu(CustomTabRobot.kt:62)
at org.mozilla.fenix.ui.SmokeTest.customTabMenuItemsTest(SmokeTest.kt:1261)
### Build: 
Master 8/3

**Comment by sv-ohorvath** [comment]
The test opened the menu before the tab stopped loading, although the page content is shown, the progress bar is gone, so there is nothing to check if it has indeed done loading or not. The first solution that came to mind is to check the button is either a "Stop" or "Refresh" button. Will see if it keeps having problems, or it is too rare to care about.

**Comment by sv-ohorvath** [comment]
Hasn't failed in over a month, closing for now. Can be reopened if it fails again.
