### ISSUE TITLE
Fenix crashes when attempting to disconnect from Mozilla account

### ISSUE THREAD

**Issue by klint** [mozilla-mobile/fenix#20672]
### Steps to reproduce

Have Fenix connected to Mozilla/Firefox account
Wait for the email address being displayed in Fenix menu
Press on email address
Press on Disconnect

### Expected behaviour

Fenix should simply disconnect from account

### Actual behaviour

Firefox crashes

### Device name

Redmi Note 7

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1

**Comment by jonalmeida** [comment]
Logs would be helpful if this is reproducible.

**Comment by klint** [comment]
Hi. Yes, happens at each attempt. Is this the log you are expecting?
5c39f695-38a8-42c4-b5cc-43e4024c87fb

java.lang.NullPointerException: null cannot be cast to non-null type android.widget.FrameLayout

 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=b1d1802d37224edbb895e0ee6187cf1e

 * Socorro: https://crash-stats.mozilla.org/report/index/bp-cdf77c18-6471-417b-b03a-9aaa00210805

----

java.lang.NullPointerException: null cannot be cast to non-null type android.widget.FrameLayout

 at java.util.Objects.requireNonNull(Objects.java:228)

 at org.mozilla.fenix.settings.account.SignOutFragment$$ExternalSyntheticLambda0.onShow(Unknown Source:7)

 at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1399)

 at android.os.Handler.dispatchMessage(Handler.java:106)

 at android.os.Looper.loop(Looper.java:201)

 at android.app.ActivityThread.main(ActivityThread.java:6810)

 at java.lang.reflect.Method.invoke(Native Method)

 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)

 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by jonalmeida** [comment]
Brilliant thank you!

I believe the offending line is [here](https://github.com/mozilla-mobile/fenix/blob/2ac5a38120ed608d1121beea64e304e975fe595a/app/src/main/java/org/mozilla/fenix/settings/account/SignOutFragment.kt#L40) in the `SignOutFragment`, where we are assuming that an internal layout in the `BottomSheetDialog` will always be accessible.

I can see other [`BottomSheetBehavior`](https://searchfox.org/mozilla-mobile/search?q=BottomSheetBehavior&path=fenix&case=false&regexp=false)s that follow the pattern, but we don't have crashes from them so I suspect it's related to the dialog being destroyed when you hit sign out.

I have seen this issue with the tabs tray that is also a dialog with a `BottomSheetBehavior`. That might be another comparison to consider.

**Comment by Amejia481** [comment]
Sentry report https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12117877

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on Firefox Preview 92.0.0 Beta 1.
### Devices used:
- Huawei MediaPad M3 (Android 7.0)
- OnePlus 6T (Android 9)

**Comment by Amejia481** [comment]
We put a fix on nightly https://github.com/mozilla-mobile/fenix/pull/20791 and Beta https://github.com/mozilla-mobile/fenix/pull/20794, they should be available on the next updates.
