### ISSUE TITLE
Intermittent UI test failure - <StrictEnhancedTrackingProtectionTest.testStrictVisitSheetDetails>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20689]
### Stacktrace:
The last action was to open the "Tracking content" details (`openDetails`) and afterwards it crashed.

08-04 10:48:07.177: I/ViewInteraction(7249): Performing 'single click' action on view with id: org.mozilla.fenix.debug:id/tracking_content
08-04 10:48:07.183: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.221: I/chatty(7249): uid=10095(org.mozilla.fenix.debug) AndroidUI identical 12 lines
08-04 10:48:07.221: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.224: D/App(7249): DebugMetricController: track event: org.mozilla.fenix.components.metrics.Event$TrackingProtectionTrackerList@1955d85
08-04 10:48:07.363: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.514: I/chatty(7249): uid=10095(org.mozilla.fenix.debug) AndroidUI identical 2 lines
08-04 10:48:07.514: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.572: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:07.572: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:07.579: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.641: I/ActivityManager(2074): Killing 3595:com.google.android.calendar/u0a81 (adj 906): empty #17
08-04 10:48:07.579: D/IdlingResourceRegistry(7249): All idling resources are idle.
08-04 10:48:07.642: W/libprocessgroup(2074): kill(-3595, 9) failed: No such process
08-04 10:48:07.648: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:07.648: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:07.681: W/libprocessgroup(2074): kill(-3595, 9) failed: No such process
08-04 10:48:07.682: I/Zygote(1911): Process 3595 exited due to signal (9)
08-04 10:48:07.734: W/libprocessgroup(2074): kill(-3595, 9) failed: No such process
08-04 10:48:07.734: I/libprocessgroup(2074): Successfully killed process cgroup uid 10081 pid 3595 in 91ms
08-04 10:48:07.853: I/hwc.gce_x86(1939): Sent 3634 syncs in 60s
08-04 10:48:07.863: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:07.863: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:07.889: W/lla.fenix.debu(7249): Accessing hidden field Landroid/app/Activity;->mResultCode:I (light greylist, reflection)
08-04 10:48:07.889: D/StrictMode(7249): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultCode:I
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.lang.Class.getDeclaredField(Native Method)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:469)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule$1.run(ActivityTestRule.java:415)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Handler.handleCallback(Handler.java:873)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Looper.loop(Looper.java:193)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.lang.reflect.Method.invoke(Native Method)
08-04 10:48:07.889: D/StrictMode(7249): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-04 10:48:07.889: D/StrictMode(7249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-04 10:48:07.889: W/lla.fenix.debu(7249): Accessing hidden field Landroid/app/Activity;->mResultData:Landroid/content/Intent; (light greylist, reflection)
08-04 10:48:07.889: D/StrictMode(7249): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultData:Landroid/content/Intent;
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.lang.Class.getDeclaredField(Native Method)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:472)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
08-04 10:48:07.889: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule$1.run(ActivityTestRule.java:415)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Handler.handleCallback(Handler.java:873)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.os.Looper.loop(Looper.java:193)
08-04 10:48:07.889: D/StrictMode(7249): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-04 10:48:07.889: D/StrictMode(7249): 	at java.lang.reflect.Method.invoke(Native Method)
08-04 10:48:07.889: D/StrictMode(7249): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-04 10:48:07.889: D/StrictMode(7249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-04 10:48:07.893: D/places_ffi(7249): bookmarks_get_tree
08-04 10:48:07.894: D/LifecycleMonitor(7249): Lifecycle status change: org.mozilla.fenix.HomeActivity@5c579c5 in: PAUSED
08-04 10:48:07.894: D/LifecycleMonitor(7249): running callback: androidx.test.rule.ActivityTestRule$LifecycleCallback@2d75fe1
08-04 10:48:07.894: W/lla.fenix.debu(7249): Accessing hidden field Landroid/app/Activity;->mResultCode:I (light greylist, reflection)
08-04 10:48:07.895: D/StrictMode(7249): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultCode:I
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
08-04 10:48:07.895: D/StrictMode(7249): 	at java.lang.Class.getDeclaredField(Native Method)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:469)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule$LifecycleCallback.onActivityLifecycleChanged(ActivityTestRule.java:568)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.internal.runner.lifecycle.ActivityLifecycleMonitorImpl.signalLifecycleChange(ActivityLifecycleMonitorImpl.java:165)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnPause(MonitoringInstrumentation.java:750)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.Looper.loop(Looper.java:193)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-04 10:48:07.895: D/StrictMode(7249): 	at java.lang.reflect.Method.invoke(Native Method)
08-04 10:48:07.895: D/StrictMode(7249): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-04 10:48:07.895: D/StrictMode(7249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-04 10:48:07.895: W/lla.fenix.debu(7249): Accessing hidden field Landroid/app/Activity;->mResultData:Landroid/content/Intent; (light greylist, reflection)
08-04 10:48:07.895: D/StrictMode(7249): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/Activity;->mResultData:Landroid/content/Intent;
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
08-04 10:48:07.895: D/StrictMode(7249): 	at java.lang.Class.getDeclaredField(Native Method)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.setActivityResultForActivity(ActivityTestRule.java:472)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule.access$100(ActivityTestRule.java:71)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.rule.ActivityTestRule$LifecycleCallback.onActivityLifecycleChanged(ActivityTestRule.java:568)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.internal.runner.lifecycle.ActivityLifecycleMonitorImpl.signalLifecycleChange(ActivityLifecycleMonitorImpl.java:165)
08-04 10:48:07.895: D/StrictMode(7249): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnPause(MonitoringInstrumentation.java:750)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4021)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3986)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3938)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.os.Looper.loop(Looper.java:193)
08-04 10:48:07.895: D/StrictMode(7249): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-04 10:48:07.895: D/StrictMode(7249): 	at java.lang.reflect.Method.invoke(Native Method)
08-04 10:48:07.895: D/StrictMode(7249): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-04 10:48:07.895: D/StrictMode(7249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-04 10:48:07.895: D/LifecycleMonitor(7249): callback completes: androidx.test.rule.ActivityTestRule$LifecycleCallback@2d75fe1
08-04 10:48:07.904: I/BackdropActivity(6099): onResume()
08-04 10:48:07.905: I/ActivityManager(2074): Activity requesting to dismiss Keyguard: ActivityRecord{ee919f7 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t3}
08-04 10:48:07.965: I/GoogleInputMethod(2209): onFinishInput() : Dummy InputConnection bound
08-04 10:48:07.965: I/GoogleInputMethod(2209): onStartInput() : Dummy InputConnection bound
08-04 10:48:08.415: W/system_server(2074): Long monitor contention with owner android.anim (2134) at void com.android.server.wm.WindowSurfacePlacer.lambda$new$0(com.android.server.wm.WindowSurfacePlacer)(WindowSurfacePlacer.java:117) waiters=0 in void com.android.server.wm.WindowManagerService$H.handleMessage(android.os.Message) for 357ms
08-04 10:48:08.415: W/system_server(2074): Long monitor contention with owner android.anim (2134) at void com.android.server.wm.WindowSurfacePlacer.lambda$new$0(com.android.server.wm.WindowSurfacePlacer)(WindowSurfacePlacer.java:117) waiters=1 in boolean com.android.server.wm.WindowManagerService.containsShowWhenLockedWindow(android.os.IBinder) for 341ms
08-04 10:48:08.417: W/system_server(2074): Long monitor contention with owner Binder:2074_3 (2166) at void com.android.server.am.ActivityManagerService.activityIdle(android.os.IBinder, android.content.res.Configuration, boolean)(ActivityManagerService.java:7945) waiters=0 in java.util.ArrayList com.android.server.am.ActivityManagerService.collectProcesses(java.io.PrintWriter, int, boolean, java.lang.String[]) for 341ms
08-04 10:48:08.417: W/system_server(2074): Long monitor contention with owner Binder:2074_3 (2166) at void com.android.server.am.ActivityManagerService.activityIdle(android.os.IBinder, android.content.res.Configuration, boolean)(ActivityManagerService.java:7945) waiters=1 in android.app.ActivityManager$TaskSnapshot com.android.server.am.ActivityManagerService.getTaskSnapshot(int, boolean) for 331ms
08-04 10:48:08.417: W/system_server(2074): Long monitor contention with owner Binder:2074_3 (2166) at void com.android.server.am.ActivityManagerService.activityIdle(android.os.IBinder, android.content.res.Configuration, boolean)(ActivityManagerService.java:7945) waiters=3 in int com.android.server.am.ActivityManagerService.getLastResumedActivityUserId() for 294ms
08-04 10:48:08.420: W/system_server(2074): Long monitor contention with owner Binder:2074_3 (2166) at void com.android.server.am.ActivityManagerService.activityIdle(android.os.IBinder, android.content.res.Configuration, boolean)(ActivityManagerService.java:7945) waiters=2 in java.lang.String com.android.server.am.ActivityManagerService.checkContentProviderAccess(java.lang.String, int) for 302ms
08-04 10:48:08.420: V/SettingsProvider(2074): Notifying for 0: content://settings/secure/long_press_timeout
08-04 10:48:08.420: W/Looper(2074): Slow dispatch took 302ms main h=com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler c=null m=1
08-04 10:48:08.420: W/Looper(2074): Slow delivery took 302ms main h=com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler c=null m=2
08-04 10:48:08.421: W/Looper(2074): Drained
08-04 10:48:08.432: I/ConfigStore(2074): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-04 10:48:08.432: I/ConfigStore(2074): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-04 10:48:08.432: I/OpenGLRenderer(2074): Initialized EGL, version 1.4
08-04 10:48:08.432: D/OpenGLRenderer(2074): Swap behavior 1
08-04 10:48:08.442: D/GeckoViewModule(7249): dispatch GeckoView:SetFocused, data={"focused":false}
08-04 10:48:08.443: D/GeckoViewContent(7249): onEvent: event=GeckoView:SetFocused, data={"focused":false}
08-04 10:48:08.460: D/places_ffi(7249): bookmarks_get_tree
08-04 10:48:08.486: I/Remoter(1915): Saved screenshot to '/data/screenshots/__pmv__-0160.jpg'
08-04 10:48:08.570: D/NuPlayerDriver(1979): NuPlayerDriver(0xf1019280) created, clientPid(2387)
08-04 10:48:08.571: W/hwservicemanager(1843): getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
08-04 10:48:08.604: D/GenericSource(1979): FileSource remote
08-04 10:48:08.614: D/NuPlayerDriver(1979): notifyListener_l(0xf1019280), (1, 0, 0, -1), loop setting(0, 0)
08-04 10:48:08.654: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:08.654: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:08.663: I/MediaFocusControl(2074): requestAudioFocus() from uid/pid 10019/2387 clientId=android.media.AudioManager@78a20ab callingPack=com.android.systemui req=3 flags=0x0 sdk=28
08-04 10:48:08.677: I/droid.launcher(2855): NativeAlloc concurrent copying GC freed 23386(1091KB) AllocSpace objects, 3(264KB) LOS objects, 49% free, 2MB/4MB, paused 101us total 251.065ms
08-04 10:48:08.712: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:08.712: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:08.783: I/ndroid.systemu(2387): NativeAlloc concurrent copying GC freed 32317(1667KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 18.007ms total 251.353ms
08-04 10:48:08.798: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:08.798: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:08.879: I/OpenGLRenderer(7249): Davey! duration=973ms; Flags=0, IntendedVsync=283053445922, Vsync=283103445920, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=283116505648, AnimationStart=283116547818, PerformTraversalsStart=283116877070, DrawStart=283117116663, SyncQueued=283117382047, SyncStart=283119077443, IssueDrawCommandsStart=283119160870, SwapBuffers=283192648603, FrameCompleted=284028241527, DequeueBufferDuration=74000, QueueBufferDuration=804000, 
08-04 10:48:08.948: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:08.948: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:09.001: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:09.001: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:09.165: V/MediaRouter(2387): onRestoreRoute() : route=RouteInfo{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‏‏‎‏‎‏‏‎‏‎‏‎‎‏‏‏‏‏‏‎‎‏‏‏‏‎‎‏‏‏‏‎‏‎‎‏‏‏‎‎‏‏‏‏‎‏‏‏‎‏‏‏‎‎‏‎‏‏‎‏‏‎Phone‎‏‎‎‏‎, description=null, status=null, category=RouteCategory{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‏‎‎‏‏‏‎‏‎‏‎‏‎‎‎‎‏‎‏‎‏‎‎‎‎‏‎‎‏‏‏‎‏‏‎‎‎‎‏‎‏‏‎‏‏‎‏‎‎‏‎‏‏‎‏‏‎‎‎‏‎‎System‎‏‎‎‏‎ types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
08-04 10:48:09.165: V/MediaRouter(2387): Selecting route: RouteInfo{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‏‏‎‏‎‏‏‎‏‎‏‎‎‏‏‏‏‏‏‎‎‏‏‏‏‎‎‏‏‏‏‎‏‎‎‏‏‏‎‎‏‏‏‏‎‏‏‏‎‏‏‏‎‎‏‎‏‏‎‏‏‎Phone‎‏‎‎‏‎, description=null, status=null, category=RouteCategory{ name=‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‏‎‎‏‎‎‎‎‏‏‏‏‏‏‎‏‏‎‎‏‏‏‎‏‎‏‎‏‎‎‎‎‏‎‏‎‏‎‎‎‎‏‎‎‏‏‏‎‏‏‎‎‎‎‏‎‏‏‎‏‏‎‏‎‎‏‎‏‏‎‏‏‎‎‎‏‎‎System‎‏‎‎‏‎ types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
08-04 10:48:09.166: D/NuPlayerDriver(1979): start(0xf1019280), state is 4, eos is 0
08-04 10:48:09.166: I/GenericSource(1979): start
08-04 10:48:09.168: V/MediaPlayer(2387): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
08-04 10:48:09.168: V/MediaPlayer(2387): cleanDrmObj: mDrmObj=null mDrmSessionId=null
08-04 10:48:09.168: D/NuPlayerDriver(1979): reset(0xf2999600) at state 6
08-04 10:48:09.168: I/AddressedMediaPlayer(2204): null queue from com.android.bluetooth, constructing single-item list
08-04 10:48:09.168: W/AddressedMediaPlayer(2204): Controller has no metadata!? Making an empty one
08-04 10:48:09.168: E/bt_btif(2204): register_notification_rsp: Avrcp device is not connected, handle: 0x0
08-04 10:48:09.168: I/chatty(2204): uid=1002(bluetooth) BluetoothAvrcpH identical 4 lines
08-04 10:48:09.168: E/bt_btif(2204): register_notification_rsp: Avrcp device is not connected, handle: 0x0
08-04 10:48:09.168: D/NuPlayerDriver(1979): notifyListener_l(0xf2999600), (8, 0, 0, -1), loop setting(0, 0)
08-04 10:48:09.169: D/NuPlayerDriver(1979): notifyListener_l(0xf2999600), (211, 0, 0, 20), loop setting(0, 0)
08-04 10:48:09.171: D/NuPlayerDriver(1979): notifyResetComplete(0xf2999600)
08-04 10:48:09.171: W/AMessage(1979): failed to post message as target looper for handler 0 is gone.
08-04 10:48:09.172: W/RingtonePlayer(2387): Notification sound delayed by 1051msecs
08-04 10:48:09.181: W/hwservicemanager(1843): getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
08-04 10:48:09.182: I/OMXClient(1979): IOmx service obtained
08-04 10:48:09.182: I/OMXMaster(1983): makeComponentInstance(OMX.google.vorbis.decoder) in omx@1.0-service process
08-04 10:48:09.183: E/OMXNodeInstance(1983): setConfig(0xe7eac960:google.vorbis.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
08-04 10:48:09.183: I/ACodec(1979): codec does not support config priority (err -2147483648)
08-04 10:48:09.183: E/OMXNodeInstance(1983): getConfig(0xe7eac960:google.vorbis.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
08-04 10:48:09.184: I/MediaCodec(1979): MediaCodec will operate in async mode
08-04 10:48:09.185: W/AshmemAllocator(1916): ashmem_create_region(32768) returning hidl_memory(0xe879c180, 32768)
08-04 10:48:09.186: I/chatty(1916): uid=1000(system) allocator@1.0-s identical 6 lines
08-04 10:48:09.187: W/AshmemAllocator(1916): ashmem_create_region(32768) returning hidl_memory(0xe879c180, 32768)
08-04 10:48:09.189: D/AudioFlinger(1936): Client defaulted notificationFrames to 12000 for frameCount 24000
08-04 10:48:09.190: D/NuPlayerDriver(1979): notifyListener_l(0xf1019280), (6, 0, 0, -1), loop setting(0, 0)
08-04 10:48:09.193: D/AudioTrack(1979): correcting timestamp time for pause, currentTimeNanos: 284331304690 < limitNs: 284336995275 < mStartNs: 284338995275
08-04 10:48:09.211: I/chatty(1979): uid=1013(media) NuPlayerRendere identical 33 lines
08-04 10:48:09.211: D/AudioTrack(1979): correcting timestamp time for pause, currentTimeNanos: 284331304690 < limitNs: 284336995275 < mStartNs: 284338995275
08-04 10:48:09.212: D/AudioFlinger(1936): mixer(0xe4083380) throttle end: throttle time(10)
08-04 10:48:09.289: E/memtrack(2074): Couldn't load memtrack module
08-04 10:48:09.290: W/android.os.Debug(2074): failed to get memory consumption info: -1
08-04 10:48:09.358: I/MetadataService(1915): Processed 0 update/creates for instance/attributes/
08-04 10:48:09.358: I/MetadataService(1915): Processed 0 update/creates for project/attributes/
08-04 10:48:09.358: I/MetadataService(1915): Processed 0 update/creates for testing/attributes/
08-04 10:48:09.462: D/NuPlayerDriver(1979): notifyListener_l(0xf1019280), (211, 0, 0, 20), loop setting(0, 0)
08-04 10:48:09.514: I/TestRunner(7249): finished: testStrictVisitSheetDetails(org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest)

**Comment by AndiAJ** [comment]
Closing in favor of #20247
