### ISSUE TITLE
[Bug]: "Share All Tabs" option can cause TransactionTooLargeException

### ISSUE THREAD

**Issue by Ruin0x11** [mozilla-mobile/fenix#20683]
### Steps to reproduce

1. Open a large number of tabs.
2. Select "Share All Tabs" from the tab context menu and pick an intent.

### Expected behaviour

The share intent should open.

### Actual behaviour

The app crashes with a `TransactionTooLargeException`.

### Device name

OnePlus 7 Pro

### Android version

9

### Firefox release type

Firefox Nightly

### Firefox version

92.0a1 (Build #2015825971) AC: 92.0.20210803143316, 2347602c39 GV: 92.0a1-20210802093840 AS: 81.0.1

### Device logs

```
FATAL EXCEPTION: main
Process: org.mozilla.fenix, PID: 19865
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
	at android.app.Activity.startActivityForResult(Activity.java:4587)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:2)
	at android.app.Activity.startActivityForResult(Activity.java:4545)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:1)
	at android.app.Activity.startActivity(Activity.java:4906)
	at android.app.Activity.startActivity(Activity.java:4874)
	at org.mozilla.fenix.share.DefaultShareController.handleShareToApp(ShareController.kt:14)
	at org.mozilla.fenix.share.ShareInteractor.onShareToApp(ShareInteractor.kt:1)
	at org.mozilla.fenix.share.viewholders.AppViewHolder.$r8$lambda$DIv2WiPjc6KEKFi6s4G6j-Fuc8M(AppViewHolder.kt:4)
	at org.mozilla.fenix.share.ShareCloseView$$ExternalSyntheticLambda0.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 1247272 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:1129)
	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3755)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
	... 21 more
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17470)

**Comment by jonalmeida** [comment]
We're going over the Binder transaction size limit set by Android.

**Comment by Ruin0x11** [comment]
This is still an ongoing issue.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1810782

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
