### ISSUE TITLE
Intermittent failure in `SelectTabUseCaseWrapperTest. WHEN invoked THEN metrics, use case and callback are triggered `

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#20700]
We need to replace the mocked lambda with non-mocked code.

It failed in my PR https://github.com/mozilla-mobile/fenix/pull/20698 https://firefoxci.taskcluster-artifacts.net/K_GeFrtPQYSLkC1_6Of4gg/0/public/reports/test/testDebugUnitTest/index.html:
```
io.mockk.MockKException: Can't instantiate proxy for class kotlin.Function1
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at org.mozilla.fenix.tabstray.browser.SelectTabUseCaseWrapperTest.WHEN invoked THEN metrics, use case and callback are triggered(SelectTabUseCaseWrapperTest.kt:98)
```

**Comment by csadilek** [comment]
Dupe and fixed in: https://github.com/mozilla-mobile/fenix/issues/21910
