### ISSUE TITLE
Intermittent UI test failure - <SmokeTest.mainMenuInstallPWATest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20716]
### Firebase Test Run:
[Firebae link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7333463789825505757/executions/bs.4c5a5095d1b07a82/testcases/1/test-cases)
[Firebae link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7333463789825505757/executions/bs.2756ade9e54f84dc/testcases/1/test-cases)

### Stacktrace:
```
08-05 18:24:39.664: I/QueryController(7590): Matched selector: UiSelector[TEXT=Install] <<==>> [android.view.accessibility.AccessibilityNodeInfo@2dbee; boundsInParent: Rect(0, 0 - 229, 59); boundsInScreen: Rect(498, 1364 - 727, 1423); packageName: org.mozilla.fenix.debug; className: android.widget.TextView; text: Install; error: null; maxTextLength: -1; contentDescription: null; tooltipText: null; viewIdResName: org.mozilla.fenix.debug:id/highlight_text; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: true; visible: true; actions: [AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_SET_SELECTION - null]]
08-05 18:24:39.666: D/InteractionController(7590): clickAndSync(612, 1393)
08-05 18:24:39.802: D/LazyMonitored(7590): Init component #63: mozilla.components.feature.tabs.CustomTabsUseCases
08-05 18:24:39.802: D/App(7590): DebugMetricController: track event: BrowserMenuItemTapped(item=ADD_TO_HOMESCREEN)
08-05 18:24:39.850: W/SurfaceFlinger(1948): Attempting to set client state on removed layer: PopupWindow:1472b3b#0
08-05 18:24:39.850: W/SurfaceFlinger(1948): Attempting to destroy on removed layer: PopupWindow:1472b3b#0
08-05 18:24:39.882: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:39.882: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:39.888: I/GoogleInputMethod(2212): onFinishInput() : Dummy InputConnection bound
08-05 18:24:39.888: I/GoogleInputMethod(2212): onStartInput() : Dummy InputConnection bound
08-05 18:24:40.069: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:40.069: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:40.183: D/BrowserIcons(7590): Loaded icon (source = DOWNLOAD): https://rpappalax.github.io/testapp/
08-05 18:24:40.191: I/ActivityManager(2070): START u0 {act=android.content.pm.action.CONFIRM_PIN_SHORTCUT flg=0x10008000 cmp=com.android.launcher3/.dragndrop.AddItemActivity (has extras)} from uid 1000
08-05 18:24:40.202: D/places_ffi(7590): bookmarks_get_tree
08-05 18:24:40.203: D/LifecycleMonitor(7590): Lifecycle status change: org.mozilla.fenix.HomeActivity@5df5df in: PAUSED
08-05 18:24:40.204: D/LifecycleMonitor(7590): running callback: androidx.test.rule.ActivityTestRule$LifecycleCallback@f09b633
08-05 18:24:40.204: D/LifecycleMonitor(7590): callback completes: androidx.test.rule.ActivityTestRule$LifecycleCallback@f09b633
08-05 18:24:40.204: W/ActivityThread(2853): handleWindowVisibility: no activity for token android.os.BinderProxy@3decc19
08-05 18:24:40.252: I/GoogleInputMethod(2212): onFinishInput() : Dummy InputConnection bound
08-05 18:24:40.252: I/GoogleInputMethod(2212): onStartInput() : Dummy InputConnection bound
08-05 18:24:40.307: D/places_ffi(7590): bookmarks_get_tree
08-05 18:24:40.639: I/Remoter(1911): Saved screenshot to '/data/screenshots/__pmv__-0155.jpg'
08-05 18:24:40.708: W/system_server(2070): Long monitor contention with owner Binder:2070_20 (4759) at void com.android.server.am.ActivityManagerService.activityIdle(android.os.IBinder, android.content.res.Configuration, boolean)(ActivityManagerService.java:7945) waiters=0 in int com.android.server.am.ActivityManagerService.getLastResumedActivityUserId() for 244ms
08-05 18:24:40.711: I/ActivityManager(2070): Displayed com.android.launcher3/.dragndrop.AddItemActivity: +252ms
08-05 18:24:40.726: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:40.726: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:40.899: D/GeckoRuntime(7590): Lifecycle: onPause
08-05 18:24:40.900: D/GeckoNetworkManager(7590): Incoming event stop for state OnWithListeners -> OffWithListeners
08-05 18:24:40.913: W/droid.launcher(2853): Long monitor contention with owner pool-1-thread-1 (2914) at boolean android.os.MessageQueue.enqueueMessage(android.os.Message, long)(MessageQueue.java:544) waiters=0 in android.os.Message android.os.MessageQueue.next() for 453ms
08-05 18:24:41.184: I/Finsky:download_service(6491): [349] nmi.run(36): Stats for Executor: bgExecutor non@7ee4789[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
08-05 18:24:41.332: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:41.332: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:41.504: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:41.504: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:41.794: I/Remoter(1911): Saved screenshot to '/data/screenshots/__pmv__-0156.jpg'
08-05 18:24:42.312: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:42.312: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:42.598: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:42.598: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:42.818: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:42.818: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:42.894: I/Remoter(1911): Saved screenshot to '/data/screenshots/__pmv__-0157.jpg'
08-05 18:24:43.050: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.050: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.233: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.233: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.360: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.360: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.482: I//system/bin/tombstoned(1968): received crash request for pid 7590
08-05 18:24:43.485: I/lla.fenix.debu(7590): Wrote stack traces to '[tombstoned]'
08-05 18:24:43.485: E//system/bin/tombstoned(1968): Traces for pid 7590 written to: /data/anr/trace_00
08-05 18:24:43.485: E//system/bin/tombstoned(1968): --------- beginning of crash
08-05 18:24:43.538: E/AndroidRuntime(7590): FATAL EXCEPTION: FinalizerWatchdogDaemon
08-05 18:24:43.538: E/AndroidRuntime(7590): Process: org.mozilla.fenix.debug, PID: 7590
08-05 18:24:43.538: E/AndroidRuntime(7590): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
08-05 18:24:43.538: E/AndroidRuntime(7590): 	at java.lang.Thread.run(Thread.java:764)
08-05 18:24:43.538: E/ExceptionHandler(7590): Uncaught exception handled: 
08-05 18:24:43.538: E/ExceptionHandler(7590): java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at android.view.ThreadedRenderer.nDeleteProxy(Native Method)
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at android.view.ThreadedRenderer.finalize(ThreadedRenderer.java:967)
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
08-05 18:24:43.538: E/ExceptionHandler(7590): 	at java.lang.Thread.run(Thread.java:764)
08-05 18:24:43.560: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.560: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.594: I/mozac/CrashReporter(7590): Received crash: UncaughtExceptionCrash(timestamp=1628213083539, throwable=java.util.concurrent.TimeoutException: android.view.ThreadedRenderer.finalize() timed out after 10 seconds, breadcrumbs=[Breadcrumb(message=onCreate(), data={recreated=false, intent=android.intent.action.MAIN, instance=6157791}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:13 PDT 2021), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:14 PDT 2021), Breadcrumb(message=onStart(), data={instance=6157791}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:14 PDT 2021), Breadcrumb(message=onResume(), data={instance=6157791}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:14 PDT 2021), Breadcrumb(message=Changing to fragment searchDialogFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:19 PDT 2021), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:22 PDT 2021), Breadcrumb(message=onAttach(), data={instance=170614316, activityInstance=6157791, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:22 PDT 2021), Breadcrumb(message=onCreateView(), data={customTabSessionId=null, instance=170614316, activityInstance=6157791, activityName=HomeActivity}, category=BrowserFragment, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:22 PDT 2021), Breadcrumb(message=onPause(), data={finishing=false, instance=6157791}, category=HomeActivity, level=INFO, type=DEFAULT, date=Thu Aug 05 18:24:40 PDT 2021)], uuid=a1e630cb-29eb-47cf-8548-113d81dab721)
08-05 18:24:43.624: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.624: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.735: I/Zygote(10101): seccomp disabled by setenforce 0
08-05 18:24:43.736: I/eportingProces(10101): Late-enabling -Xcheck:jni
08-05 18:24:43.737: I/ActivityManager(2070): Start proc 10101:org.mozilla.fenix.debug:crashReportingProcess/u0a95 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.service.SendCrashTelemetryService
08-05 18:24:43.764: I/mozac/CrashReporter(7590): Showing prompt
08-05 18:24:43.800: W/eportingProces(10101): Unexpected CPU variant for X86 using defaults: x86
08-05 18:24:43.861: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:43.861: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:43.872: I/ActivityManager(2070): START u0 {flg=0x10018000 cmp=org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10095
08-05 18:24:43.887: I/Process(7590): Sending signal. PID: 7590 SIG: 9
08-05 18:24:43.931: I/ActivityManager(2070): Start proc 10126:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashReporter/u0a95 for activity org.mozilla.fenix.debug/mozilla.components.lib.crash.prompt.CrashReporterActivity
08-05 18:24:43.939: I/BackdropActivity(6386): onResume()
08-05 18:24:43.952: I/ActivityManager(2070): Activity requesting to dismiss Keyguard: ActivityRecord{bb06d8a u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t3}
08-05 18:24:43.953: I/Zygote(10126): seccomp disabled by setenforce 0
08-05 18:24:43.954: I/h.CrashReporte(10126): Late-enabling -Xcheck:jni
08-05 18:24:43.974: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-05 18:24:43.974: W/BroadcastQueue(2070): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-05 18:24:44.114: D/NuPlayerDriver(1960): NuPlayerDriver(0xee899300) created, clientPid(2234)
08-05 18:24:44.116: W/hwservicemanager(1839): getTransport: Cannot find entry android.hardware.media.omx@1.0::IOmx/default in either framework or device manifest.
08-05 18:24:44.128: D/GenericSource(1960): FileSource remote
08-05 18:24:44.139: D/NuPlayerDriver(1960): notifyListener_l(0xee899300), (1, 0, 0, -1), loop setting(0, 0)
08-05 18:24:44.183: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:44.183: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:44.184: I/MediaFocusControl(2070): requestAudioFocus() from uid/pid 10019/2234 clientId=android.media.AudioManager@8114d47 callingPack=com.android.systemui req=3 flags=0x0 sdk=28
08-05 18:24:44.303: W/h.CrashReporte(10126): Unexpected CPU variant for X86 using defaults: x86
08-05 18:24:44.325: I/Remoter(1911): Saved screenshot to '/data/screenshots/__pmv__-0158.jpg'
08-05 18:24:44.328: E/memtrack(2070): Couldn't load memtrack module
08-05 18:24:44.328: W/android.os.Debug(2070): failed to get memory consumption info: -1
08-05 18:24:44.377: I/Gecko(7909): Exiting due to channel error.
08-05 18:24:44.377: W/InputDispatcher(2070): channel '3b8778e org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-05 18:24:44.377: E/InputDispatcher(2070): channel '3b8778e org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

### Notes
❗ Based on the logs and videos the last action was to click the "Install" button

**Comment by Mugurell** [comment]
@AndiAJ I see test this failing for most of the recent PRs. Should this be ignored?

**Comment by sv-ohorvath** [comment]
The test needs an update to the test page used.

**Comment by AndiAJ** [comment]
Flaky 1x on 9/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9190559462828656854/executions/bs.87e32407510eb455/testcases/1/logs)

**Comment by AndiAJ** [comment]
Flaky 1x on 1/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8222779888113457088/executions/bs.d0018877c0815554/testcases/1/logs)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of months
