### ISSUE TITLE
Intermittent UI test failure - <SettingsAboutTest.verifyAboutFirefoxPreview>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20754]
### Stacktrace:
androidx.test.espresso.PerformException: Error performing 'single click' on view 'with text: is "Know your rights"'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertKnowYourRights(SettingsSubMenuAboutRobot.kt:188)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertKnowYourRights(SettingsSubMenuAboutRobot.kt:1)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$verifyListElements$3.invoke(SettingsSubMenuAboutRobot.kt:85)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$verifyListElements$3.invoke(SettingsSubMenuAboutRobot.kt:85)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$navigateBackToAboutPage$6.invoke(SettingsSubMenuAboutRobot.kt:77)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$navigateBackToAboutPage$6.invoke(SettingsSubMenuAboutRobot.kt:76)
at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:118)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.navigateBackToAboutPage(SettingsSubMenuAboutRobot.kt:76)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:85)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:64)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:46)
at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:82)
at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:81)
at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:118)
at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:81)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user.
Target view: "AppCompatTextView{id=2131361811, res-name=about_item_title, visibility=VISIBLE, width=1080, height=154, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@26b2f89, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Know your rights, input-type=0, ime-target=false, has-links=false}"
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:63)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:15)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6777693062739191218/executions/bs.7ec92d8697417bf8/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Also flaky on 10/5, with a different error: [logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4929027764776248982/executions/bs.6e2af4e94e1caf67/testcases/1/test-cases)
`androidx.test.espresso.AmbiguousViewMatcherException: 'with id is <org.mozilla.fenix.debug:id/mozac_browser_tabstray_close>' matches multiple views in the hierarchy.

at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:18)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.closeTab(TabDrawerRobot.kt:97)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$navigateBackToAboutPage$2.invoke(SettingsSubMenuAboutRobot.kt:72)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt$navigateBackToAboutPage$2.invoke(SettingsSubMenuAboutRobot.kt:71)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:504)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.navigateBackToAboutPage(SettingsSubMenuAboutRobot.kt:71)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:91)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:66)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:48)
`

**Comment by sv-ohorvath** [comment]
Flaky on 10/6: [AmbiguousViewMatcherException](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4929027764776248982/executions/bs.6e2af4e94e1caf67/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7886336653752882262/executions/bs.4fc38fe8df814c16/testcases/1/test-cases)

`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id is <org.mozilla.fenix.debug:id/recycler_view>`

**Comment by AndiAJ** [comment]
Flaky 1x on 12/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8638506024975453775/executions/bs.3385fd6db6644a13/testcases/1/test-cases)

androidx.test.espresso.PerformException: Error performing 'single click' on view 'with text: is "Licensing information"'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)

**Comment by AndiAJ** [comment]
Flaky 1x on 1/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5927605682662587086/executions/bs.72de0934e68b29b/testcases/1/test-cases)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatTextView{id=2131362661, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@59c4ffd, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9000572215713279418/executions/bs.30f43890fdd8f703/testcases/1/test-cases)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatTextView{id=2131362665, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@38bc300, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/9 Main [Firebase link](url)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/26 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7977495052116291019/executions/bs.87e8fb7e9b0a83a5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7907259869959067326/executions/bs.6ff32552a74edff7/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7734882724186563675/executions/bs.243a3af9677aae78/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6980551312252686855/executions/bs.2ccd7de309ad6709/testcases/1/test-cases)
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@e20eca5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertCrashes(SettingsSubMenuAboutRobot.kt:174)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:82)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:66)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:48)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:85)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:84)
	at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:136)
	at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:84)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@e20eca5, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5960961912975782918/executions/bs.48c7d48c597bb317/testcases/1/test-cases)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@117e0fc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertCrashes(SettingsSubMenuAboutRobot.kt:174)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:82)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:66)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:48)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:85)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:84)
	at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:136)
	at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:84)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@117e0fc, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5596205753103991488/executions/bs.b197216c6562a75c/testcases/1/test-cases)

androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2cdb922, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertCrashes(SettingsSubMenuAboutRobot.kt:174)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.verifyListElements(SettingsSubMenuAboutRobot.kt:82)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:66)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:48)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:85)
	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:84)
	at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:136)
	at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:84)
	... 33 trimmed
Caused by: junit.framework.AssertionFailedError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: view.getVisibility() was <GONE>
View Details: AppCompatTextView{id=2131362680, res-name=mozac_lib_crash_empty, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2cdb922, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=No crash reports have been submitted., input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Disabled in #25128
