### ISSUE TITLE
Intermittent UI test failure - <SmokeTest.tabMediaControlButtonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20814]
### Stacktrace:
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.verifyTabMediaControlButtonState(TabDrawerRobot.kt:151)
at org.mozilla.fenix.ui.SmokeTest$tabMediaControlButtonTest$3.invoke(SmokeTest.kt:1339)
at org.mozilla.fenix.ui.SmokeTest$tabMediaControlButtonTest$3.invoke(SmokeTest.kt:1336)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:517)
at org.mozilla.fenix.ui.SmokeTest.tabMediaControlButtonTest(SmokeTest.kt:1336)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Flaky 2x on 8/31 Main
 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5969217960440391884/executions/bs.936d5567889cab8/testcases/1/test-cases)
[Firebase link](tabMediaControlButtonTest)

**Comment by AndiAJ** [comment]
Flaky 2x on 8/31 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5969217960440391884/executions/bs.936d5567889cab8/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7614208652612001427/executions/bs.e7dc92ed0926b3ad/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/11Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7311411295032462992/executions/bs.21058fe7ccb7d14c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6591285157398681319/executions/bs.e11e2f08dd983a6b/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
From the video, it looks like somehow UIAutomator fails to click the "Pause" button on the tab.

**Comment by AndiAJ** [comment]
Flaky 1x on 9/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5478741837066733989/executions/bs.d97786561cb4a998/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7335337014568034226/executions/bs.3b048b855714b02e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closed with #21685

**Comment by AndiAJ** [comment]
Flaky 1x on 11/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5426906074085329245/executions/bs.685b92584194d1f6/testcases/1/test-cases)

java.lang.AssertionError: Playback did not moved to state: PLAYING
at org.junit.Assert.fail(Assert.java:89)
at org.mozilla.fenix.ui.robots.BrowserRobot.assertPlaybackState(BrowserRobot.kt:506)
at org.mozilla.fenix.ui.SmokeTest$tabMediaControlButtonTest$2.invoke(SmokeTest.kt:1266)
at org.mozilla.fenix.ui.SmokeTest$tabMediaControlButtonTest$2.invoke(SmokeTest.kt:1263)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
at org.mozilla.fenix.ui.SmokeTest.tabMediaControlButtonTest(SmokeTest.kt:1263)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.9bfca696864e54d1/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.5b647957231fc103/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7681397052728475747/executions/bs.d6e8aae726f53d1a/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7681397052728475747/executions/bs.b138c75e5c9ac69c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing for now, as it didn't fail for approx. a month
