### ISSUE TITLE
mozilla.appservices.places.PlacesException: Error executing SQL: Integer 2321879344 out of range at index 5

### ISSUE THREAD

**Issue by willdurand** [mozilla-mobile/fenix#20856]
On Fenix Nightly with History Metadata enabled, the app crashes on startup with the following error:

```
mozilla.appservices.places.PlacesException: Error executing SQL: Integer 2321879344 out of range at index 5
	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince$suspendImpl(PlacesConnection.kt:13)
	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince(Unknown Source:0)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince$suspendImpl(PlacesHistoryStorage.kt:4)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince(Unknown Source:0)
	at org.mozilla.fenix.historymetadata.HistoryMetadataFeature$start$1.invokeSuspend(HistoryMetadataFeature.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

I was able to open Fenix without an immediate crash by opening a link from another app. I disabled History Metadata, no more crashes since then.

### Links

 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=833e0ec780d44883b1a855836a0b41b9
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-afcd374b-4817-4e59-bd8c-6cd0c0210815

### Other information

- 93.0a1 (Build #2015828043)
- AC: 93.0.20210813143343, 9fa4750cc7
- GV: 93.0a1-20210813092746
- AS: 82.1.0
- OnePlus2 with Android 10

**Comment by csadilek** [comment]
Thanks for trying out this feature and reporting! This was fixed in https://github.com/mozilla-mobile/fenix/issues/20901. However, this problem caused invalid data to be persisted which will continue to trigger the crash. Luckily, we fixed before enabling it publicly, but unfortunately that means you will have to either clear your application data or delete the incorrect history entry or metadata record, see https://github.com/mozilla-mobile/fenix/issues/20901#issuecomment-901554070.
