### ISSUE TITLE
Intermittent UI test failure - <SearchTest.shortcutButtonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#20973]
### Stacktrace:
java.lang.AssertionError: Assertion failed
at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineResults(SearchRobot.kt:231)
at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineResults(SearchRobot.kt:1)
at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineResults(SearchRobot.kt:56)
at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:64)
at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:60)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:185)
at org.mozilla.fenix.ui.SearchTest.shortcutButtonTest(SearchTest.kt:60)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

### Build: 8/23 Main

**Comment by AndiAJ** [comment]
Flaky 1x on 1/27 Main [Firebase](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8399056902814531345/executions/bs.32056c409ec2ae96/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 1/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5003774744227135626/executions/bs.4bc69de6eb800cc9/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5100799137262457576/executions/bs.daf6410974b18ba1/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Looks like the number of search suggestions doesn't always match the expected number, it could be only a network issue, but I think it can be avoided with a small change to the test.

**Comment by AndiAJ** [comment]
Flaky 1x on 2/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5678571608136217424/executions/bs.941a4c47f3dd0206/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7416112078635174647/executions/bs.3c2b141117704193/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 2x on 2/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7471522327065362314/executions/bs.eae417449d6713bc/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4969700827430697250/executions/bs.b03fd7feefa5b1a4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8609805091409708981/executions/bs.fddc759dabecb5fc/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8692563289701035661/executions/bs.721c7efc1b276aa8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4868799456652171052/executions/bs.5c89853653dd8913/testcases/1/test-cases)

Flaky 1x on 2/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6213407336353355300/executions/bs.29888e609a5d467c/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 2/24 Main: [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5748349958798985235/executions/bs.eb8ee57b458cda60/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8869833438789736084/executions/bs.6e749cdc683048cb/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7990348231970079023/executions/bs.a2ff7ce128609cd/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5930931022056030865/executions/bs.3e8eb7b867903c8a/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5927840737094122777/executions/bs.e8545776151a0a13/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/12 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7875192870428056923/executions/bs.81a287d6fa913a4a/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7875192870428056923/executions/bs.c7810e774b81b89e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6560896464354313903/executions/bs.d6a872a471a715b3/testcases/1/test-cases)

**Comment by Mugurell** [comment]
Failing again https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5986358079757616327

**Comment by Mugurell** [comment]
Disabled the test in https://github.com/mozilla-mobile/fenix/pull/24796 as it was blocking merging.

**Comment by AndiAJ** [comment]
Fixed and re-enabled in #24903
