### ISSUE TITLE
Crash in [@ java.lang.ExceptionInInitializerError: at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)]

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#20991]
Crash report: https://crash-stats.mozilla.org/report/index/d8b3378b-8095-469b-955f-ec4db0210824

Java stack trace:
```
java.lang.ExceptionInInitializerError
	at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:5)
	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:7)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(PlacesStorage.kt:1)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan$suspendImpl(PlacesHistoryStorage.kt:4)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.deleteHistoryMetadataOlderThan(Unknown Source:0)
	at org.mozilla.fenix.historymetadata.DefaultHistoryMetadataService$cleanup$1.invokeSuspend(HistoryMetadataService.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.ExceptionInInitializerError%3A%20at%20mozilla.appservices.places.LibPlacesFFI.%3Cclinit%3E%28Unknown%20Source%3A0%29
* can't find this crash in Sentry

**Comment by Amejia481** [comment]
cc @grigoryk
