### ISSUE TITLE
Intermittent UI test failure - StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21005]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7703657670252405383/executions/bs.f80e057f100d2902/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/protection_settings
If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:androidx.appcompat.widget.AppCompatSpinner{a3d89f4 GFED..CL. ......I. 0,0-0,0 #7f0a00fe app:id/autoplayStatus}`
more in the link above.
### Build: 
Main 8/25

**Comment by AndiAJ** [comment]
Flaky 1x on 8/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8293397968990327046/executions/bs.a5dc134a53862e2/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
There are 3 different issues here:
1. The tracking test page content didn't load, so the generic page is still loaded when the test opens the ETP sheet.
2. The test accidentally clicks the ETP toggle instead of the "Details" button and turns ETP off.
3. The first page in the test (the generic web page) didn't open, the browser layout is not visible.

**Comment by sv-ohorvath** [comment]
New error, flaky on 10/5 debug (starting with https://github.com/mozilla-mobile/fenix/pull/21689):
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull$default(WaitNotNull.kt:17)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertEnhancedTrackingProtectionSheetStatus(EnhancedTrackingProtectionRobot.kt:117)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertEnhancedTrackingProtectionSheetStatus(EnhancedTrackingProtectionRobot.kt:1)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot.verifyEnhancedTrackingProtectionSheetStatus(EnhancedTrackingProtectionRobot.kt:37)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitDisableExceptionToggle$7.invoke(StrictEnhancedTrackingProtectionTest.kt:105)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest$testStrictVisitDisableExceptionToggle$7.invoke(StrictEnhancedTrackingProtectionTest.kt:104)
at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot$Transition.disableEnhancedTrackingProtectionFromSheet(EnhancedTrackingProtectionRobot.kt:88)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle(StrictEnhancedTrackingProtectionTest.kt:104)`
