### ISSUE TITLE
IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#21090]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/12712238/?referrer=github_plugin

```
IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.Collections$SingletonList.get(Collections.java:4863)
    at org.mozilla.fenix.settings.DataChoicesFragment.access$getQuittingAppString(DataChoicesFragment.kt:2)
    at org.mozilla.fenix.settings.DataChoicesFragment$onCreatePreferences$$inlined$apply$lambda$1.onPreferenceChange(Extensions.kt:8)
    at androidx.preference.Preference.callChangeListener(Preference.java:1)
    at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:2)
...
(14 additional frame(s) were not displayed)

Index: 1, Size: 1
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17744)

**Comment by hokonch** [comment]
I overlooked this issue before reporting about it. Detailed STR and cause are here https://github.com/mozilla-mobile/fenix/issues/21148.

**Comment by hokonch** [comment]
@kbrosnan  Why not close this issue? It looks like this crash no longer occurs in the supported version (Release, Beta, Nightly).
