### ISSUE TITLE
The app crashes when returning to the edit bookmarks menu after changing device settings

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#21162]
### Steps to reproduce

1. Open any website and add it to bookmarks
2. Open the Edit menu for that bookmark (either snackbar or 3-dot menu)
3. Open the device settings and toggle night mode
4. Wait for changes to take effect and return to Firefox

### Expected behaviour

The application is stable at all times 

### Actual behaviour

The application crashes when returning to the edit menu after the changes take effect

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

92.1.1 2021-09-04

### Device logs

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class fragment
----
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5046)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4955)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class fragment
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
	at org.mozilla.fenix.HomeActivity.getSupportActionBarAndInflateIfNecessary(HomeActivity.kt:16)
	at org.mozilla.fenix.library.bookmarks.edit.EditBookmarkFragment.onViewCreated(EditBookmarkFragment.kt:3)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:30)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:12)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:48)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:4)
	at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:14)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:819)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:902)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:554)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
	at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:4)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:11)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)
	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:18)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5046)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4955)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

### Additional information

Occurs on Firefox Nightly 93.0a1 2021-09-06 

Also triggers when changing other device settings such as navigation bar or font size.

![241604448_1091138191292718_2529875722498434456_n](https://user-images.githubusercontent.com/89511597/132234755-8f05bb3e-34af-41d8-8a01-da3952616fcf.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17790)

**Comment by kbrosnan** [comment]
* https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+Binary+XML+file+line+%2327
* https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+Binary+XML+file+line+%2327
* https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+Binary+XML+file+line+%2327
* https://crash-stats.mozilla.org/signature/?java_stack_trace_raw=~Binary XML file line %2327&product=Fenix&_sort=-date&signature=java.lang.RuntimeException%3A at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)

**Comment by AndiAJ** [comment]
Reproducible on 93.0.0-beta.1 using a Google Pixel 3a (Android 11)

92bfae12-4f37-4e62-a135-af12dad06611
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Error inflating class fragment
* Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=897da9161cdf4cf0ae630297e8f2d13d
* Socorro: https://crash-stats.mozilla.org/report/index/bp-82550c0d-1e0f-411d-95eb-08b5b0210908
----
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.firefox_beta/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #27 in org.mozilla.firefox_beta:layout/activity_home: Error inflating class fragment
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized
at org.mozilla.fenix.HomeActivity.getSupportActionBarAndInflateIfNecessary(HomeActivity.kt:16)
at org.mozilla.fenix.library.bookmarks.edit.EditBookmarkFragment.onViewCreated(EditBookmarkFragment.kt:3)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:30)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:24)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:73)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:12)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:48)
at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:4)
at org.mozilla.fenix.HomeActivity.onCreateView(HomeActivity.kt:14)
at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
at org.mozilla.fenix.perf.PerformanceInflater.inflate(PerformanceInflater.kt:4)
at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:11)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)
at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:18)
at android.app.Activity.performCreate(Activity.java:8000)
at android.app.Activity.performCreate(Activity.java:7984)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5451)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5357)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7660)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by cpeterso** [comment]
Reopening because this crash still seems to be happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1646397, though a RuntimeException from `ActivityThread.performLaunchActivity()` might be a pretty generic crash signature.

**Comment by nemamayank** [comment]
**Hello guys can you help me out**

_Below is my trace and reported in play store as well_

```
java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4035)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4201)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2438)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8669)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by: androidx.fragment.app.Fragment$InstantiationException:
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:628)
  at androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:483)
  at androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:85)
  at androidx.fragment.app.FragmentManager.restoreSaveState (FragmentManager.java:2728)
  at androidx.fragment.app.FragmentController.restoreSaveState (FragmentController.java:198)
  at androidx.fragment.app.FragmentActivity$2.onContextAvailable (FragmentActivity.java:149)
  at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.java:99)
  at androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:313)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:273)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java:115)
  at dagger.android.support.DaggerAppCompatActivity.onCreate (DaggerAppCompatActivity.java:53)
  at nl.ockto.mobile.presentation.ui.common.BaseActivity.onCreate (BaseActivity.kt:20)
  at nl.ockto.mobile.presentation.ui.main.MainActivity.onCreate (MainActivity.kt:142)
  at android.app.Activity.performCreate (Activity.java:8290)
  at android.app.Activity.performCreate (Activity.java:8270)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1329)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4009)
Caused by: java.lang.NoSuchMethodException:
  at java.lang.Class.getConstructor0 (Class.java:2363)
  at java.lang.Class.getConstructor (Class.java:1759)
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:613)


////// Code Snip //////

`abstract class BaseActivity<VM : BaseViewModel?>(
private val viewModelClass: Class? = null
) : DaggerAppCompatActivity() {

@Inject
lateinit var viewModelProviderFactory: ViewModelProviderFactory

private var _viewModel: VM? = null
val viewModel get() = _viewModel!!

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    if (viewModelClass != null)
        _viewModel = ViewModelProvider(this, viewModelProviderFactory).get(viewModelClass)
}
}`
```

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812703

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
