### ISSUE TITLE
[Bug]: Crashes for Chinese but not for English on turning off studies

### ISSUE THREAD

**Issue by nvxarm** [mozilla-mobile/fenix#21222]
### Steps to reproduce

1. Select Chinese in Android settings
2. Turn off studies in Firefox
3. It crashes

4. Select English in Android settings
5. Turn off studies in Firefox
6. It works

### Expected behaviour

Do not crash when using Chinese

### Actual behaviour

It crashed

### Device name

ASUS ROG Phone 5s

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1.1 (Build #2015832083)

### Device logs

https://crash-stats.mozilla.org/report/index/03f710cf-5ea4-4b95-b5fe-c603f0210910

### Additional information

[Chinese-Crashing.mp4](https://user-images.githubusercontent.com/16894061/132785178-ae8dac79-6121-4031-bfaf-e96e65888c65.mp4)

[English-Not-Crashing.mp4](https://user-images.githubusercontent.com/16894061/132785142-43f6546e-cb23-44e1-99b2-7b232930987e.mp4)

**Comment by nvxarm** [comment]
https://crash-stats.mozilla.org/report/index/03f710cf-5ea4-4b95-b5fe-c603f0210910


```
java.lang.IndexOutOfBoundsException
	at java.util.Collections$SingletonList.get(Collections.java:4872)
	at org.mozilla.fenix.settings.DataChoicesFragment$onCreatePreferences$lambda-3$$inlined$setOnPreferenceChangeListener$1.onPreferenceChange(Extensions.kt:12)
	at androidx.preference.Preference.callChangeListener(Preference.java:1)
	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:2)
	at androidx.preference.Preference.performClick(Preference.java:3)
	at androidx.preference.SwitchPreference.performClick(SwitchPreference.java:1)
	at androidx.preference.Preference$1.onClick(Preference.java:1)
	at android.view.View.performClick(View.java:7466)
	at android.view.View.performClickInternal(View.java:7443)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28327)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by nvxarm** [comment]
https://github.com/mozilla-mobile/fenix/issues/21148
