### ISSUE TITLE
[Crash] NPE in AddonsManagementFragment

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#21418]
Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13014158/

Add-on installs successfully but the app crashes when updating the UI in the success callback. 

Looks like `binding` is null when the async operation finishes and invokes the callback. @codrut-topliceanu Can you take a quick look? I can't reproduce and the only change that landed recently was: https://github.com/mozilla-mobile/fenix/commit/7070bb5607f5ac9fd0825ab21e7abba675f98bdc.

We have seen cases like this before where the context is still not null, but the view got destroyed when the async operation returns. Then `binding` would be null causing the crash. Let's handle that, and potentially uplift.

```
java.lang.NullPointerException: null
    at org.mozilla.fenix.addons.AddonsManagementFragment$onPositiveButtonClicked$1$installOperation$1.invoke(AddonsManagementFragment.kt:8)
    at mozilla.components.feature.addons.AddonManager$installAddon$4.invoke(AddonManager.kt:9)
    at mozilla.components.browser.engine.gecko.GeckoEngine$installWebExtension$onInstallSuccess$1.invoke(GeckoEngine.kt:16)
    at mozilla.components.browser.engine.gecko.GeckoEngine$$ExternalSyntheticLambda9.onValue
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4(GeckoResult.java:2)
    at org.mozilla.geckoview.GeckoResult.$r8$lambda$AFxsnIxghFV7ZhrvgIHpdLryPVU
    at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda0.run
    at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$5(GeckoResult.java:2)
    at org.mozilla.geckoview.GeckoResult.$r8$lambda$PbNUepeldwERMEcQ_iVWEzy-zTE
    at org.mozilla.geckoview.GeckoView$$ExternalSyntheticLambda0.run
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

org.mozilla.geckoview.UncaughtException: java.lang.NullPointerException
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$4(GeckoResult.java:10)
```

**Comment by csadilek** [comment]
This also hit the latest beta which lines up with timing: https://sentry.prod.mozaws.net/operations/firefox-beta/issues/13100734/

**Comment by codrut-topliceanu** [comment]
**Steps to reproduce:**

1. 3 dot menu -> Add-ons / Add-ons Manager
2. Click + to install an add-on, press "Add" button
3. As soon as the bottom dialog appears informing the user that the add-on is being installed **navigate away** from the fragment by clicking on one of the other add-ons in the list

**Expected:** 
 - the clicked add-on details page is opened

**Actual:**
 - crash

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Firefox Preview Nightly 2021-10-05.

### Devices used:
- Oppo Find X3 (Android 11)
- OnePlus 6T (Android 9)
