### ISSUE TITLE
Intermittent UI test failure - HistoryTest.deleteMultipleSelectionTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21442]
### Firebase Test Run:
Flaky test
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8278794498371878886/executions/bs.30079b4d12d754f5/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.IdlingResourceTimeoutException: Wait for [org.mozilla.fenix.helpers.RecyclerViewIdlingResource:2131362435] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.helpers.TestHelper.longTapSelectItem(TestHelper.kt:69)
at org.mozilla.fenix.ui.HistoryTest$deleteMultipleSelectionTest$7.invoke(HistoryTest.kt:235)
at org.mozilla.fenix.ui.HistoryTest$deleteMultipleSelectionTest$7.invoke(HistoryTest.kt:230)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openHistory(ThreeDotMenuMainRobot.kt:178)
at org.mozilla.fenix.ui.HistoryTest.deleteMultipleSelectionTest(HistoryTest.kt:230)`
### Build: 
Started with this commit 87e4a25

**Comment by AndiAJ** [comment]
Flaky 1x on 9/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5478741837066733989/executions/bs.ae96105b8e9d7e2b/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 9/27: [test report](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8861787374425386959/executions/bs.25d3daf4fea7a76b/test-cases)

**Comment by AndiAJ** [comment]
Fixed with #21563
