### ISSUE TITLE
[Crash]: App is crashing on new tab open, at address bar and home page button

### ISSUE THREAD

**Issue by gelirhil** [mozilla-mobile/fenix#21506]
### Steps to reproduce

Any of this actions:
1. Tap the new tab button.
2. Tap address bar.
3. Tap home page button.

### Expected behaviour

App is stable all the time.

### Actual behaviour

App crashes with crash report sending.

### Device name

Google Pixel 4a

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

94.0a1 (Build #2015836107)

### Device logs

2e857b1c-ab1a-4be6-bd4b-db4ecf937c6f
mozilla.appservices.places.PlacesException: Error executing SQL: Integer 3163514776 out of range at index 6
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=6e38f89d0b3b4137bcb535de3540cf67
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-6f1caa88-8a43-44fd-98ba-6026f0210925
----
mozilla.appservices.places.PlacesException: Error executing SQL: Integer 3163514776 out of range at index 6
	at mozilla.appservices.places.RustError$Companion.makeException(RustError.kt:1)
	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince$suspendImpl(PlacesConnection.kt:7)
	at mozilla.appservices.places.PlacesReaderConnection.getHistoryMetadataSince(Unknown Source:0)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince$suspendImpl(PlacesHistoryStorage.kt:4)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHistoryMetadataSince(Unknown Source:0)
	at org.mozilla.fenix.historymetadata.HistoryMetadataFeature$start$1.invokeSuspend(HistoryMetadataFeature.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

### Additional information

Tested with all extensions disabled and app cash cleared with system tools.

**Comment by gelirhil** [comment]
No signs of the bug in build #2015836299.

**Comment by csadilek** [comment]
Thanks for reporting @gelirhil! Yes, there's a new Nightly rolling out with a fix:

94.0a1 (Build #2015836299)
AC: 94.0.20210926133629, cafbf98276
