### ISSUE TITLE
Intermittent UI test failure - BookmarksTest.openSelectionInNewTabTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21539]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5478183495229699525/executions/bs.f00fd86aeeb5a1ea/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.AmbiguousViewMatcherException: 'with id is <org.mozilla.fenix.debug:id/mozac_browser_tabstray_close>' matches multiple views in the hierarchy.
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:18)
at org.mozilla.fenix.ui.robots.TabDrawerRobot.closeTab(TabDrawerRobot.kt:97)
at org.mozilla.fenix.ui.BookmarksTest$openSelectionInNewTabTest$2.invoke(BookmarksTest.kt:352)
at org.mozilla.fenix.ui.BookmarksTest$openSelectionInNewTabTest$2.invoke(BookmarksTest.kt:351)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:512)
at org.mozilla.fenix.ui.BookmarksTest.openSelectionInNewTabTest(BookmarksTest.kt:351)`
### Build: 
Main 9/27

**Comment by sv-ohorvath** [comment]
This issue appears to be related to multiple tests (duplicate tabs title, close button or tab item):
https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+is%3Aopen+androidx.test.espresso.AmbiguousViewMatcherException%3A
