### ISSUE TITLE
Intermittent UI test failure - SmokeTest.openRecentlyClosedTabsInNewTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21631]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8600167687374339475/executions/bs.fd8b1144bb1faece/testcases/1/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:271)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:97)
at org.mozilla.fenix.ui.SmokeTest.openRecentlyClosedTabsInNewTabTest(SmokeTest.kt:746)`
### Build: 
main 10/1 https://github.com/mozilla-mobile/fenix/pull/21594

**Comment by sv-ohorvath** [comment]
See https://github.com/mozilla-mobile/fenix/issues/21684 also for the same error

**Comment by sv-ohorvath** [comment]
Closing for now since it hasn't failed in a month. Please reopen if it has the same issue, if not, open a new issue.
