### ISSUE TITLE
[Crash] IndexOutOfBoundsException in TabsAdapter

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#21686]
Sentry: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13492817/

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.get(ArrayList.java:437)
    at org.mozilla.fenix.tabstray.browser.TabsAdapter.onBindViewHolder(TabsAdapter.kt:4)
    at org.mozilla.fenix.tabstray.browser.BrowserTabsAdapter.onBindViewHolder(BrowserTabsAdapter.kt:27)
    at org.mozilla.fenix.tabstray.browser.BrowserTabsAdapter.onBindViewHolder(BrowserTabsAdapter.kt:8)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
    at androidx.recyclerview.widget.ConcatAdapter.onBindViewHolder(ConcatAdapter.java:5)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:143)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
    at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
    at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
    at android.view.View.layout(View.java:22085)
```

**Comment by jonalmeida** [comment]
We found some consistent STR for the bug:

1. Ensure the app is completely stopped; swipe away from the app switcher.
2. Open Fenix and enable the Secret Settings.
3. Open the tabs tray and make a tab inactive.
4. :boom: 

This is happening because when the TabsFeature calls our TabsTray.updateTabs, we are changing the reference to the list for it under the hood, so all calls to the DiffUtils will fail because the size of the list is wrong.
