### ISSUE TITLE
Debug build startup crash due to deploy instrumentation: (False positive?) StrictMode ThreadPolicy violation: DiskReadViolation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21695]
I keep getting this on my Pixel 4a, Android 12 on app startup. Sometimes it works. Often it just crashes. It doesn't seem like our code is in the stacktrace. Do we just need to add an exception?

```
      ExceptionHandler  E  Uncaught exception handled:
                         E  java.lang.RuntimeException: StrictMode ThreadPolicy violation
                         E      at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
                         E      at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1890)
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda1.run(Unknown Source:4)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:920)
                         E  Caused by: android.os.strictmode.DiskReadViolation
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
                         E      at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                         E      at libcore.io.ForwardingOs.access(ForwardingOs.java:131)
                         E      at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7719)
                         E      at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
                         E      at java.io.File.exists(File.java:813)
                         E      at com.android.tools.deploy.instrument.ResourceOverlays.updateLoader(ResourceOverlays.java:73)
                         E      at com.android.tools.deploy.instrument.ResourceOverlays.addResourceOverlays(ResourceOverlays.java:36)
                         E      at com.android.tools.deploy.instrument.InstrumentationHooks.addResourceOverlays(InstrumentationHooks.java:102)
                         E      at android.app.LoadedApk.getResources(LoadedApk.java:1312)
                         E      at android.app.ContextImpl.createAppContext(ContextImpl.java:3011)
                         E      at android.app.ContextImpl.createAppContext(ContextImpl.java:3003)
                         E      at android.app.Service.createServiceBaseContext(Service.java:904)
                         E      at android.app.ActivityThread.handleCreateService(ActivityThread.java:4475)
                         E      at android.app.ActivityThread.access$1700(ActivityThread.java:247)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7842)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                         E  Uncaught exception handled:
                         E  java.lang.RuntimeException: StrictMode ThreadPolicy violation
                         E      at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:44)
                         E      at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:38)
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1890)
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda1.run(Unknown Source:4)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:920)
                         E  Caused by: android.os.strictmode.DiskReadViolation
                         E      at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
                         E      at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                         E      at libcore.io.ForwardingOs.access(ForwardingOs.java:131)
                         E      at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7719)
                         E      at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
                         E      at java.io.File.exists(File.java:813)
                         E      at com.android.tools.deploy.instrument.ResourceOverlays.updateLoader(ResourceOverlays.java:73)
                         E      at com.android.tools.deploy.instrument.ResourceOverlays.addResourceOverlays(ResourceOverlays.java:36)
                         E      at com.android.tools.deploy.instrument.InstrumentationHooks.addResourceOverlays(InstrumentationHooks.java:102)
                         E      at android.app.LoadedApk.getResources(LoadedApk.java:1312)
                         E      at android.app.ContextImpl.createAppContext(ContextImpl.java:3011)
                         E      at android.app.ContextImpl.createAppContext(ContextImpl.java:3003)
                         E      at android.app.Service.createServiceBaseContext(Service.java:904)
                         E      at android.app.ActivityThread.handleCreateService(ActivityThread.java:4475)
                         E      at android.app.ActivityThread.access$1700(ActivityThread.java:247)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loopOnce(Looper.java:201)
                         E      at android.os.Looper.loop(Looper.java:288)
                         E      at android.app.ActivityThread.main(ActivityThread.java:7842)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by pocmo** [comment]
> Did this happen after the app crashed on usage, and then following starts turned into a startup-crash?

This did happen too, I think. But it also happens quite often when I deploy from Android Studio. I then have to launch the app manually again.

**Comment by jonalmeida** [comment]
I have a suspicion that it might be partly related to the crash reporter writing some files to disk in a service, but somehow along the way, the violation has a stack that doesn't include our own calls.

Just a hunch.

**Comment by mcomella** [comment]
```
                         E      at com.android.tools.deploy.instrument.InstrumentationHooks.addResourceOverlays(InstrumentationHooks.java:102)
```

The `InstrumentationHooks` file [is in the `com.android.tools.deploy.instrument` package](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:deploy/agent/runtime/src/main/java/com/android/tools/deploy/instrument/InstrumentationHooks.java;l=17;drc=ab812198a673136c28f3b90050c083d665c2be97) which implies this would not occur in production, only when deploying with some kind of instrumentation. As such, I think it can be safely ignored.

That being said, the code that actually causes the violation is suppressed internally, on the latest version of upstream:

https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:deploy/agent/runtime/src/main/java/com/android/tools/deploy/instrument/ResourceOverlays.java;l=69-82;drc=abbbe67087626460e0127d3f5377f9cf896e9941

So I'm wondering if this is fine on the Android 12 release version but was broken in the beta.

@pocmo Are you on the latest version of Android 12? Can you still reproduce?

**Comment by mcomella** [comment]
> I think it can be safely ignored because it doesn't impact users and it's not really within our control.

fwiw, in this case, I think we would ignore violations with the `InstrumentHooks` class.

**Comment by pocmo** [comment]
> @pocmo Are you on the latest version of Android 12? Can you still reproduce?

Yeah, I am on the latest Android 12 build - release now.

**Comment by pocmo** [comment]
I'll put up a patch. Seems like the fix is in Android Studio code, so may get fixed in a later revision (I am on the stable track).
