### ISSUE TITLE
Intermittent UI test failure - SmokeTest.openMainMenuFindInPageTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21711]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9081089006430601399/executions/bs.30af526b9d01988f/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with res-name that is "browserLayout" or with res-name that is "download_button")

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:108)
at org.mozilla.fenix.ui.SmokeTest.openMainMenuFindInPageTest(SmokeTest.kt:304)
`
### Build: 
10/5 https://github.com/mozilla-mobile/fenix/pull/21698

**Comment by sv-ohorvath** [comment]
From the video it looks like the page is not displayed after entering the URL in the navbar, the app still shows the home screen.
I can't reproduce this manually yet.

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month
