### ISSUE TITLE
Intermittent test failure:       PocketUpdatesMiddlewareTest. WHEN SelectPocketStoriesCategory is dispatched THEN persist details in DataStore

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#21733]
> PocketUpdatesMiddlewareTest. WHEN SelectPocketStoriesCategory is dispatched THEN persist details in DataStore

```
java.lang.InstantiationError: kotlin.jvm.functions.Function2
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor256.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
	at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
	at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
	at io.mockk.impl.instantiation.JvmInstantiator.instantiate(JvmInstantiator.kt:15)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1$1.invoke(RecordingState.kt:49)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$2.invoke(JvmAnyValueGenerator.kt:35)
	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:34)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:31)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1.invoke(RecordingState.kt:48)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:20)
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:47)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
	at org.mozilla.fenix.home.PocketUpdatesMiddlewareTest$WHEN SelectPocketStoriesCategory is dispatched THEN persist details in DataStore$1.invokeSuspend(PocketUpdatesMiddlewareTest.kt:188)
	at org.mozilla.fenix.home.PocketUpdatesMiddlewareTest$WHEN SelectPocketStoriesCategory is dispatched THEN persist details in DataStore$1.invoke(PocketUpdatesMiddlewareTest.kt)
	at org.mozilla.fenix.home.PocketUpdatesMiddlewareTest$WHEN SelectPocketStoriesCategory is dispatched THEN persist details in DataStore$1.invoke(PocketUpdatesMiddlewareTest.kt)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invokeSuspend(RecordedBlockEvaluator.kt:28)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$2$1.invoke(RecordedBlockEvaluator.kt)
	at io.mockk.InternalPlatformDsl$runCoroutine$1.invokeSuspend(InternalPlatformDsl.kt:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

https://firefoxci.taskcluster-artifacts.net/Io3wpEBLTDyjqaGjcHRjEQ/0/public/reports/test/testDebugUnitTest/index.html

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18191)

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v94.0.0
