### ISSUE TITLE
[Bug]: Typing address manually crashes

### ISSUE THREAD

**Issue by yarons** [mozilla-mobile/fenix#21829]
### Steps to reproduce

Tap the address bar.
Start typing a URL.

### Expected behaviour

The relevant URL should autocomplete and some relevant suggestions should appear, the address autocompletes but then it's time for suggestions it crashes.

### Actual behaviour

Crash.

### Device name

Pocophone F1

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 (Build #2015838699)

### Device logs

java.lang.IllegalArgumentException: Can't represent a size of 330609 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:3)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit_release(Constraints.kt:2)
	at androidx.compose.ui.unit.Constraints$Companion.fixedWidth-OenEA2s(Constraints.kt:1)
	at androidx.compose.foundation.layout.MaxIntrinsicWidthModifier.calculateContentConstraints-l58MMJ0(Intrinsic.kt:2)
	at androidx.compose.foundation.layout.IntrinsicSizeModifier$DefaultImpls.measure-3p2s80s(Intrinsic.kt:1)
	at androidx.compose.foundation.layout.MaxIntrinsicWidthModifier.measure-3p2s80s(Intrinsic.kt:1)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:71)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:34)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:19)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:71)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:34)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:45)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
	at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:9)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.foundation.layout.UnspecifiedConstraintsModifier.measure-3p2s80s(Size.kt:14)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:71)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:34)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:13)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1)
	at androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:7)
	at androidx.compose.foundation.lazy.LazyListKt$LazyList$1.invoke(LazyList.kt:76)
	at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:19)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:7)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:13)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$3.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:61)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:34)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:8)
	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:11)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:27)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:1)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:3)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:1)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$measure$1$1.placeChildren(DelegatingLayoutNodeWrapper.kt:4)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:12)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:1)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:3)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:1)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper$measure$1$1.placeChildren(DelegatingLayoutNodeWrapper.kt:4)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:12)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:14)
	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:3)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.placeAt-f8xVGno(DelegatingLayoutNodeWrapper.kt:12)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:15)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:38)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:1)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:3)
	at android.view.View.draw(View.java:21550)
	at android.view.View.updateDisplayListIfDirty(View.java:20416)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20376)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20376)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20376)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20376)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4401)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4374)
	at android.view.View.updateDisplayListIfDirty(View.java:20376)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3736)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3531)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2868)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:865)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### Additional information

Looks like a regression from the past couple of days.

**Comment by yarons** [comment]
I don't have access to the Sentry.

Regarding the first link, my report doesn't match the description, it doesn't happen after less than a minute, it happens in a very specific case when I'm trying to type a URL manually.

Thank you :)

**Comment by Mugurell** [comment]
Still seeing crashes for this, even in a build from yesterday - https://crash-stats.mozilla.org/report/index/c0da1432-2906-40dd-833e-3d5380211012

**Comment by kbrosnan** [comment]
I was thinking that we might be recording glean events for address bar interactions and overflowing the buffer. Though the compose rewrite is a good theory.

**Comment by csadilek** [comment]
OK, fix landed in Nightly and was uplifted to beta:
https://github.com/mozilla-mobile/android-components/pull/11125
https://github.com/mozilla-mobile/android-components/pull/11129

I am not seeing crashes in the latest version, but let's double-check in a few days.

**Comment by kbrosnan** [comment]
@yarons did this stop on recent nightly builds?
