### ISSUE TITLE
Intermittent UI test failure - Wait for [SessionLoadedIdlingResource] to become idle timed out

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#21925]
### Firebase Test Run:

[StrictEnhancedTrackingProtectionTest.testStrictVisitSheetDetails](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5364583050534126802/executions/bs.f73229d790680373/testcases/1/test-cases)

### Stacktrace:
```
androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:108)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitSheetDetails(StrictEnhancedTrackingProtectionTest.kt:142)
at java.lang.reflect.Method.invoke(Native Method)
```

### Build: 
Flaky 1x on 10/14 Main 

Same error on https://github.com/mozilla-mobile/fenix/issues/21324 while loading the TP test page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18309)

**Comment by sv-ohorvath** [comment]
Same error on customTrackingProtectionSettingsTest: [logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7177696035154217166/executions/bs.ad1c377da14280c9/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Not reproducing anymore.
