### ISSUE TITLE
[Crash]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22070]
### Steps to reproduce

Prerequisites: Clean install

1. Launch Firefox and dismiss the onboarding screen
2. Sign in with an account
3. Disable network connection
4. Open the homepage 
5. Tap on a button from "Stories by topic" (e.g. Technology)

### Expected behaviour

The application is stable at all times

### Actual behaviour

The application will crash

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

95.0a1 2021-10-21

### Device logs

5587a4de-1579-4c7a-a815-53753a34df56
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix/?query=6ffca18d370441078fba667c2d84dd1e
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-3e5d2f8f-a4d1-4722-8949-ac51f0211021
----
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	... 3 more
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at org.mozilla.fenix.ext.HomeFragmentStateKt.getFilteredStories(HomeFragmentState.kt:22)
	at org.mozilla.fenix.home.HomeFragmentStore$1.invoke(HomeFragmentStore.kt:86)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$chain$1.invoke(ReducerChainBuilder.kt:7)
	at org.mozilla.fenix.home.PocketUpdatesMiddleware.invoke(PocketUpdatesMiddleware.kt:11)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:10)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### Additional information

Before doing the clean install, the account used had previously opened articles from pocket in history, if this might be relevant information.

**Comment by Mugurell** [comment]
No occurences after October 22nd - https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13662710/
Closing the ticket.
