### ISSUE TITLE
Crash when opening opening a history group

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#22226]
We show the the same menu options for individual history items and for the new history groups.
When selecting the option to "Option in new tab" for a history group the app will crash with the following stacktrace
```
java.lang.ClassCastException: org.mozilla.fenix.library.history.History$Group cannot be cast to org.mozilla.fenix.library.history.History$Regular
    at org.mozilla.fenix.library.history.HistoryFragment$onOptionsItemSelected$2.invoke(HistoryFragment.kt:212)
    at org.mozilla.fenix.library.history.HistoryFragment$onOptionsItemSelected$2.invoke(HistoryFragment.kt:211)
    at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
    at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
    at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
    at org.mozilla.fenix.library.LibraryPageFragment.openItemsInNewTab(LibraryPageFragment.kt:1290)
    at org.mozilla.fenix.library.LibraryPageFragment.openItemsInNewTab$default(LibraryPageFragment.kt:27)
    at org.mozilla.fenix.library.history.HistoryFragment.onOptionsItemSelected(HistoryFragment.kt:211)
```

&nbsp;

Sentry issue - https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/13630000/events/79218836/

&nbsp;

https://user-images.githubusercontent.com/11428869/139440576-9f7445b8-1d63-4011-8cc6-1eba7f3360e5.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18510)

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly 96.0a1 (2021-11-03T05:10:24.120708) and on the latest Beta (95.0.0-beta.1).

Device used: Xiaomi Mi11 (Android 11).

Closing the ticket as fixed.
