### ISSUE TITLE
Intermittent debug(T) org.mozilla.fenix.push.WebPushEngineIntegrationTest - delegate calls unsubscribe

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#22240]
WebPushEngineIntegrationTest. delegate calls unsubscribe

```
java.lang.InstantiationError: kotlin.jvm.functions.Function1
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor165.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instanceViaObjenesis(ObjenesisInstantiator.kt:75)
	at io.mockk.proxy.jvm.ObjenesisInstantiator.instance(ObjenesisInstantiator.kt:42)
	at io.mockk.impl.instantiation.JvmInstantiator$instantiate$2.invoke(JvmInstantiator.kt:16)
	at io.mockk.impl.instantiation.AbstractInstantiator.instantiateViaInstanceFactoryRegistry(AbstractInstantiator.kt:17)
	at io.mockk.impl.instantiation.JvmInstantiator.instantiate(JvmInstantiator.kt:15)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1$1.invoke(RecordingState.kt:49)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator$anyValue$2.invoke(JvmAnyValueGenerator.kt:35)
	at io.mockk.impl.instantiation.AnyValueGenerator.anyValue(AnyValueGenerator.kt:34)
	at io.mockk.impl.instantiation.JvmAnyValueGenerator.anyValue(JvmAnyValueGenerator.kt:31)
	at io.mockk.impl.recording.states.RecordingState$matcher$signatureValue$1.invoke(RecordingState.kt:48)
	at io.mockk.impl.recording.JvmSignatureValueGenerator.signatureValue(JvmSignatureValueGenerator.kt:20)
	at io.mockk.impl.recording.states.RecordingState.matcher(RecordingState.kt:47)
	at io.mockk.impl.recording.CommonCallRecorder.matcher(CommonCallRecorder.kt:52)
	at org.mozilla.fenix.push.WebPushEngineIntegrationTest$delegate calls unsubscribe$1.invoke(WebPushEngineIntegrationTest.kt:223)
	at org.mozilla.fenix.push.WebPushEngineIntegrationTest$delegate calls unsubscribe$1.invoke(WebPushEngineIntegrationTest.kt:189)
	at io.mockk.impl.eval.RecordedBlockEvaluator$record$block$1.invoke(RecordedBlockEvaluator.kt:25)
	at io.mockk.impl.eval.RecordedBlockEvaluator$enhanceWithRethrow$1.invoke(RecordedBlockEvaluator.kt:78)
	at io.mockk.impl.recording.JvmAutoHinter.autoHint(JvmAutoHinter.kt:23)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:40)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalEvery(API.kt:92)
	at io.mockk.MockKKt.every(MockK.kt:98)
	at org.mozilla.fenix.push.WebPushEngineIntegrationTest.delegate calls unsubscribe(WebPushEngineIntegrationTest.kt:189)
```

**Comment by jonalmeida** [comment]
Holding back on fixing this with https://github.com/mozilla-mobile/fenix/pull/22246 landing. If we see this happen again, we should fix it.

**Comment by csadilek** [comment]
OK, we haven't seen this in 30+ consecutive builds after https://github.com/mozilla-mobile/fenix/pull/22246 landed. We also see builds where this failure is detected and successfully retried. So the workaround seems to do the trick for now. Closing, let's re-open if we see again.
