### ISSUE TITLE
[Bug] (crash) java.lang.IllegalStateException: at mozilla.components.service.sync.logins.SyncableLoginsStorage$add$2.invokeSuspend(SyncableLoginsStorage.kt:7)

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#22279]
### Steps to reproduce

_I report this bug on behalf of an user in the Firefox support, I am not the affected user._

1. The user just upgraded from Firefox 68 to Firefox 93.2.0
2. Then the user entered his master password to get the saved login data on the new Firefox version.

### Expected behaviour

No crash. :)

### Actual behaviour

```
java.lang.IllegalStateException
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$add$2.invokeSuspend(SyncableLoginsStorage.kt:7)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$add$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.add(SyncableLoginsStorage.kt:1)
	at org.mozilla.fenix.components.tips.providers.MasterPasswordTipProvider$saveLogins$1.invokeSuspend(MasterPasswordTipProvider.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

Socorro link: https://crash-stats.mozilla.org/report/index/141ef2e4-8825-4898-a845-4503e0211028

### Device name

Xiaomi Redmi Note 4

### Android version

Android 7

### Firefox release type

Firefox

### Firefox version

93.2.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18541)

**Comment by pocmo** [comment]
> The user just upgraded from Firefox 68 to Firefox 93.2.0

Do you happen to know why/how that happened? We still see some late migrations, but it's not clear if those are all regular users. But this one obviously is and I wonder how/why the made this huge jump. :)

**Comment by cadeyrn** [comment]
> Do you happen to know why/how that happened? 

@pocmo Unfortunately not. I asked the user but he was not in the forum since then.
