### ISSUE TITLE
[Bug]: Crash after scrolling down suggestions and sending the app to background

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22382]
### Steps to reproduce

Prerequisites: Have search suggestions enabled

1. Sign in with an account that has lots of history items
2. Tap the search bar and input one character
3. Scroll down through the suggestions (closer to the end preferably)
4. Send the application to background

### Expected behaviour

The application is stable

### Actual behaviour

The application crashes

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Beta

### Firefox version

95.0.0-beta.2 2021-11-08

### Device logs

7a6d9c28-4b19-4415-8a9c-4931b41a343a
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1115060 bytes
----
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1115060 bytes
at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7078)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: android.os.TransactionTooLargeException: data parcel size 1115060 bytes
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:1145)
at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3891)
at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
... 7 more

### Additional information

This issue also occurs on Nightly and might be related to this issue https://github.com/mozilla-mobile/fenix/issues/20683 that has different steps to reproduce

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible with the latest Nightly 102.0a1 (2022-05-18T17:12:12.001240).
Devices used:
- Samsung Galaxy Tab S3 (Android 9).
- Google Pixel 4 (Android 12).

Closing the issue as fixed.
