### ISSUE TITLE
IllegalArgumentException: surfaceTexture must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22381]
Nightly:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14730037/?referrer=github_plugin

```
IllegalArgumentException: surfaceTexture must not be null
    at android.view.Surface.<init>(Surface.java:140)
    at mozilla.components.feature.qr.QrFragment$stateCallback$1.onOpened(QrFragment.kt:9)
    at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
...
(5 additional frame(s) were not displayed)

surfaceTexture must not be null
```

**Comment by pocmo** [comment]
Release audience:
https://sentry.prod.mozaws.net/operations/firefox/issues/13075990

Fairly low volume (but that's probably true for QR code scanning in general).
