### ISSUE TITLE
IllegalArgumentException: com.android.providers.settings: Targeting S+ (version 31 and above) requires that one of FLAG_IMM...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22405]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14809263/?referrer=github_plugin

```
IllegalArgumentException: com.android.providers.settings: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
    at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
    at android.content.ContentResolver.call(ContentResolver.java:2450)
    at android.content.ContentResolver.call(ContentResolver.java:2430)
...
(3 additional frame(s) were not displayed)

com.android.providers.settings: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**Comment by pocmo** [comment]
This just showed up in Nightly. I am a bit surprised about this since we are NOT targeting 31+ (and I hope we are not really accidentally somehow).

**Comment by pocmo** [comment]
(This one user has rooted=yes, so maybe we can ignore it, unless it shows up for more users)
