### ISSUE TITLE
LoginStore.getByBaseDomain: InternalException: called `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22443]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/14011601/?referrer=github_plugin

```
InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
    at mozilla.appservices.logins.LoginStore.getByBaseDomain(logins.kt:14)
    at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:3)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
    at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
...
(7 additional frame(s) were not displayed)

called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by bendk** [comment]
Couple A-S PRs that should address this one:
  - https://github.com/mozilla/application-services/pull/4669 fixes one cause of this issue (I think it's the most likely)
  - https://github.com/mozilla/application-services/pull/4669 would stop all the `PoisonErrors` after a panic.  We could still get panics, but panics wouldn't make it so calling any `LoginStore` method throws an error.

**Comment by boppreh** [comment]
I'm getting these on ~50% of the pages I try to load since about a month ago, making the browser unusable. OnePlus 6 with only uBlock Origin and HTTPS Everywhere installed. Disabling sync didn't help.

**Comment by kbrosnan** [comment]
Not seeing this crash on 98 in Sentry and [Crash Stats](https://crash-stats.mozilla.org/signature/?java_stack_trace_raw=~mozilla.appservices.logins.InternalException&product=Fenix&signature=mozilla.appservices.logins.InternalException%3A%20at%20mozilla.appservices.logins.LoginStore.getByBaseDomain%28logins.kt%3A14%29).
