### ISSUE TITLE
Update leakcanary version to 2.7 or above be able to targe Android 12

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22559]
Related https://github.com/square/leakcanary/issues/2076 and https://github.com/mozilla-mobile/fenix/issues/22539
```
/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1056481257.tmp/base.apk (at Binary XML file line #978): leakcanary.internal.activity.LeakLauncherActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
        at com.android.ddmlib.internal.DeviceImpl.installRemotePackage(DeviceImpl.java:1310)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1136)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1112)
        at com.android.ddmlib.internal.DeviceImpl.installPackage(DeviceImpl.java:1101)
        at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:127)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.install(InstallVariantTask.java:159)
        at com.android.build.gradle.internal.tasks.InstallVariantTask.lambda$doTaskAction$1(InstallVariantTask.java:96)
        at com.android.builder.testing.api.DeviceProvider.use(DeviceProvider.java:53)

```

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/23082.
