### ISSUE TITLE
[Bug]: Sending local PDF tab from Windows PC to Android causes Android app to crash

### ISSUE THREAD

**Issue by KnightsWhoSayNi0** [mozilla-mobile/fenix#22566]
### Steps to reproduce

1. Open a local PDF file in firefox on Windows
2. Right click tab and choose "Send tab to device"
3. Choose an android phone
4. Android phone will crash when trying to open firefox

### Expected behaviour

Should Refuse to send local file.

### Actual behaviour

Tries to send local file and crashes android app.

### Device name

Google Pixel 4a

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

94.1.2

### Device logs

6de5e61e-a292-4296-86d2-30c015e765ea
android.os.FileUriExposedException: file:///C:/Users/John/Desktop/Random%20Things/Philips-DCP-750-Service-Manual.pdf exposed beyond app through Intent.getData()
----
android.os.FileUriExposedException: file:///C:/Users/John/Desktop/Random%20Things/Philips-DCP-750-Service-Manual.pdf exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2209)
	at android.net.Uri.checkFileUriExposed(Uri.java:2402)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11400)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11352)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:461)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$1$3.invoke(BackgroundServices.kt:16)
	at mozilla.components.feature.accounts.push.EventsObserver.onEvents(SendTabFeature.kt:17)
	at mozilla.components.service.fxa.AccountEventsIntegration$onEvents$1.invoke(AccountStorage.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.AccountEventsIntegration.onEvents(AccountStorage.kt:2)
	at mozilla.components.service.fxa.FxaDeviceConstellation$processEvents$1.invoke(FxaDeviceConstellation.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers(Unknown Source:7)
	at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2.invokeSuspend(FxaDeviceConstellation.kt:10)
	at mozilla.components.service.fxa.FxaDeviceConstellation$pollForCommands$2.invoke(FxaDeviceConstellation.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.fxa.FxaDeviceConstellation$refreshDevices$2.invokeSuspend(FxaDeviceConstellation.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

**Comment by LaurentiuApahideanSV** [comment]
This is known issue, any file:///URL will crash Firefox as can be seen here: https://github.com/mozilla-mobile/fenix/issues/20414#issuecomment-882763693. I will mark this issue as closed as it will be handled there.

**Comment by KnightsWhoSayNi0** [comment]
Ah, I apologize. I forgot to check if it was a known bug or not.
