### ISSUE TITLE
Update work-manager verstion to 2.7.0-alpha02 or above to able to use it on Android 12

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#22577]
On Android 12 we are unable to run the app, as work-manager is not indicating the correct mutability flag for `PendingIntent`, it looks [2.7.0-alpha02](https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha03) they are addressing the issue.

```
 java.lang.IllegalArgumentException: org.mozilla.fenix.debug: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/fenix/pull/23080.
