### ISSUE TITLE
CreditCardUtils: NumberFormatException: For input string: "[..]"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22607]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/15404388/?referrer=github_plugin

```
NumberFormatException: For input string: "[see bug report]"
    at java.lang.Integer.parseInt(Integer.java:615)
    at java.lang.Integer.parseInt(Integer.java:650)
    at mozilla.components.support.utils.CreditCardUtilsKt.creditCardIIN(CreditCardUtils.kt:17)
    at com.google.android.material.internal.ContextUtils.toCreditCard(ContextUtils.java:7)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onCreditCardSave$1.invoke(GeckoPromptDelegate.kt:4)
...
(16 additional frame(s) were not displayed)

For input string: "[see bug report]"
```

**Comment by pocmo** [comment]
CC @gabrielluong

**Comment by julienw** [comment]
There's a STR in #22651.

**Comment by Amejia481** [comment]
Addressed on https://github.com/mozilla-mobile/android-components/issues/
