### ISSUE TITLE
UncaughtException: java.lang.NullPointerException: nativeExtension.id must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22608]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/15333408/?referrer=github_plugin

```
NullPointerException: nativeExtension.id must not be null
    at mozilla.components.browser.engine.gecko.webextension.GeckoWebExtension.<init>(GeckoWebExtension.kt:1)
    at mozilla.components.browser.engine.gecko.GeckoEngine$$ExternalSyntheticLambda12.onValue
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$6(GeckoResult.java:2)
    at org.mozilla.geckoview.GeckoResult.$r8$lambda$CtmBkNQN_okuE2MBIfsimJFUi6Q(GeckoResult.java)
    at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda1.run
...
(11 additional frame(s) were not displayed)

UncaughtException: java.lang.NullPointerException: nativeExtension.id must not be null
    at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
    at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$6(GeckoResult.java:10)
    at org.mozilla.geckoview.GeckoResult.$r8$lambda$CtmBkNQN_okuE2MBIfsimJFUi6Q(GeckoResult.java)
    at org.mozilla.geckoview.GeckoResult$$ExternalSyntheticLambda1.run
...
(11 additional frame(s) were not displayed)

java.lang.NullPointerException: nativeExtension.id must not be null
```

**Comment by pocmo** [comment]
This crash started to show up in Nightly 96. The crash is in A-C code, but it looks like we get a null extension ID? File as GeckoView bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1743169

**Comment by kbrosnan** [comment]
Looks to be tracked by the GV bug.
