### ISSUE TITLE
[Bug]: Crash after restoring from miui local backup 

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#22613]
### Steps to reproduce

restoring from miui local backup 

### Expected behaviour

no crash

### Actual behaviour

Crash after opening fenix two or three seconds 

### Android version

android 11

### Firefox release type

Firefox

### Firefox version

94.1.2

### Device logs

mozilla.appservices.logins.LoginsStorageException$InvalidKey: InvalidKey error: SqlError
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.read(logins.kt:5)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler$lift$1.invoke(logins.kt:1)
	at mozilla.appservices.logins.LoginsKt.liftFromRustBuffer(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:2)
	at mozilla.appservices.logins.LoginsStorageException$ErrorHandler.lift(logins.kt:1)
	at mozilla.appservices.logins.LoginStore.<init>(logins.kt:13)
	at mozilla.appservices.logins.DatabaseLoginsStorage.unlock(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$conn$2.invoke(SyncableLoginsStorage.kt:9)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getConn(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invokeSuspend(SyncableLoginsStorage.kt:6)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$warmUp$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at org.mozilla.fenix.FenixApplication$initVisualCompletenessQueueAndQueueTasks$queueInitStorageAndServices$1$1.invokeSuspend(FenixApplication.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

**Comment by lindongbin** [comment]
delete some file from backup and it work
