### ISSUE TITLE
InvalidParameterException: Not valid prompt request type

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#22619]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/15411783/?referrer=github_plugin

```
InvalidParameterException: Not valid prompt request type
    at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:285)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Collect.kt:19)
    at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:7)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
...
(9 additional frame(s) were not displayed)

Not valid prompt request type
```

**Comment by pocmo** [comment]
Looks like this is new in 96 and just started happening.

**Comment by pocmo** [comment]
Last change in `feature-prompts` happened recently by @gabrielluong. Maybe a regression?

https://github.com/mozilla-mobile/android-components/commit/bd5ad084ee2bff1ae1c84619a6ba3fd2d8572dc8#diff-b42db5f12716ca0e467afb8d368c19419b6bd7d21db89f4ee33b3d253d572180

**Comment by kbrosnan** [comment]
This appears to be fixed.
