### ISSUE TITLE
Crash in [@ java.lang.NumberFormatException: at java.lang.Integer.parseInt(Integer.java)]

### ISSUE THREAD

**Issue by julienw** [mozilla-mobile/fenix#22651]
I got this when paying on mesepices.com after entering my credit card information.

Crash report: https://crash-stats.mozilla.org/report/index/a77d722a-6473-4316-a90d-fd23c0211201

Java stack trace:
```
java.lang.NumberFormatException
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at mozilla.components.support.utils.CreditCardUtilsKt.creditCardIIN(CreditCardUtils.kt:17)
	at com.google.android.material.color.MaterialColors.toCreditCard(MaterialColors.java:7)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onCreditCardSave$1.invoke(GeckoPromptDelegate.kt:4)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onCreditCardSave(GeckoPromptDelegate.kt:4)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.callDelegate(PromptController.java:2)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.callDelegate(PromptController.java:1)
	at org.mozilla.geckoview.PromptController.getResponse(PromptController.java:6)
	at org.mozilla.geckoview.PromptController.handleEvent(PromptController.java:6)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:6)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/22607
