### ISSUE TITLE
Intermittent UI test failure - verifyContextCopyImageLocation 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#22684]
### Firebase Test Run:
Flaky, 1/2 tries:
[Firebase test run report link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7028219816686620007/executions/bs.737a7bea286d81cd/testcases/1/test-cases)
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:263)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
at org.mozilla.fenix.ui.ContextMenusTest.verifyContextCopyImageLocation(ContextMenusTest.kt:168)`
### Build: 
Debug 12/2

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of months
