### ISSUE TITLE
Intermittent UI test failure - < TabbedBrowsingTest.closeTabTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#22749]
## 1.
```
Fatal exception
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
       FATAL EXCEPTION: main
Process: com.android.systemui, PID: 2220
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:61)
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
	at com.android.systemui.statusbar.phone.ShadowKeyDrawable.draw(ShadowKeyDrawable.java:88)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:1011)
	at android.widget.ImageView.onDraw(ImageView.java:1360)
	at android.view.View.draw(View.java:20207)
	at android.view.View.updateDisplayListIfDirty(View.java:19082)
	at android.view.View.draw(View.java:19935)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.updateDisplayListIfDirty(View.java:19073)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.View.draw(View.java:19935)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw(View.java:20210)
	at android.view.View.updateDisplayListIfDirty(View.java:19082)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3312)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2485)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7184)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

## 2.
```
Native crash of /vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim
A native crash was detected.
       *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'generic/gce_x86_phone/gce_x86:9/PGR1.190916.001/5877764:userdebug/test-keys'
Revision: '0'
ABI: 'x86'
pid: 1919, tid: 2520, name: bluetooth@1.0-s  >>> /vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Status.cpp:149] Failed HIDL return status not checked: Status(EX_TRANSACTION_FAILED): 'DEAD_OBJECT: ''
    eax 00000000  ebx 0000077f  ecx 000009d8  edx 00000006
    edi 0000077f  esi e7df6048
    ebp e74d7498  esp e74d7418  eip e7feebe9
backtrace:
    #00 pc 00000be9  [vdso:e7fee000] (__kernel_vsyscall+9)
    #01 pc 0001fdf8  /system/lib/libc.so (syscall+40)
    #02 pc 00022e73  /system/lib/libc.so (abort+115)
    #03 pc 00006f85  /system/lib/libbase.so (android::base::DefaultAborter(char const*)+37)
    #04 pc 00008433  /system/lib/libbase.so (_ZNSt3__110__function6__funcIPFvPKcENS_9allocatorIS5_EES4_EclEOS3_+35)
    #05 pc 00007ccc  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+828)
    #06 pc 0001bbf2  /system/lib/libhidlbase.so (android::hardware::details::return_status::~return_status()+290)
    #07 pc 000073ca  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (_ZNSt3__110__function6__funcIZN7android8hardware9bluetooth4V1_03sim12BluetoothHci10initializeERKNS2_2spINS5_22IBluetoothHciCallbacksEEEE3$_1NS_9allocatorISD_EEFvNS_10unique_ptrIN15test_vendor_lib11EventPacketENS_14default_deleteISI_EEEEEEclEOSL_+234)
    #08 pc 000108ff  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (test_vendor_lib::DualModeController::LeScan()+2239)
    #09 pc 0000fbd5  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (test_vendor_lib::DualModeController::HandleTimerTick()+85)
    #10 pc 00018de3  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (_ZNSt3__110__function6__funcIZN15test_vendor_lib18DualModeController10StartTimerEvE4$_54NS_9allocatorIS4_EEFvvEEclEv+35)
    #11 pc 0000c3a6  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (test_vendor_lib::AsyncManager::AsyncTaskManager::ThreadRoutine()+918)
    #12 pc 0000bfd0  /system/vendor/bin/hw/android.hardware.bluetooth@1.0-service.sim (_ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN15test_vendor_lib12AsyncManager16AsyncTaskManager14tryStartThreadEvEUlvE_EEEEEPvSC_+64)
    #13 pc 0008f005  /system/lib/libc.so (__pthread_start(void*)+53)
    #14 pc 000247fb  /system/lib/libc.so (__start_thread+75)
```
  

### Build: 12/7
❗ Tracking the bluetooth related crash in #22618

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a couple of months
