### ISSUE TITLE
Crash in [@ java.lang.ClassCastException: at org.mozilla.fenix.tabstray.browser.AbstractBrowserTabViewHolder$$ExternalSyntheticLambda3.onTouch(Unknown Source:3)]

### ISSUE THREAD

**Issue by K900** [mozilla-mobile/fenix#22756]
Crash report: https://crash-stats.mozilla.org/report/index/a61623d9-27f1-430e-ac94-ea6b50211208

Java stack trace:
```
java.lang.ClassCastException
	at org.mozilla.fenix.tabstray.browser.AbstractBrowserTabViewHolder$$ExternalSyntheticLambda3.onTouch(Unknown Source:3)
	at android.view.View.dispatchTouchEvent(View.java:14536)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
	at android.view.View.dispatchPointerEvent(View.java:14799)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6347)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6148)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5814)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5871)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8562)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8513)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8482)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8685)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:239)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8642)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8771)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Can't find a reliable way to trigger it, but opening a bunch of tabs, then opening the tab tray seems to do it.

**Comment by csadilek** [comment]
Thank you! Duping this to https://github.com/mozilla-mobile/fenix/issues/22757 which has a fix landed. Will go out in next Nightly.
