### ISSUE TITLE
[Crash] ClassCastException: RecyclerView cannot be cast to AbstractBrowserTrayList

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#22757]
Recent regression. Based on timing, likely caused by: https://github.com/mozilla-mobile/fenix/commit/6637f610884bf4c6826886b4a413a23f3400622e

Sentry isn't grouping this correctly, but I merged the ones I saw into:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/15849763/

```
java.lang.ClassCastException: androidx.recyclerview.widget.RecyclerView cannot be cast to org.mozilla.fenix.tabstray.browser.AbstractBrowserTrayList
    at org.mozilla.fenix.tabstray.browser.AbstractBrowserTabViewHolder$$ExternalSyntheticLambda3.onTouch
    at android.view.View.dispatchTouchEvent(View.java:14536)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
    ....
```

**Comment by csadilek** [comment]
Crash only happened in this one version of Nightly and volume is trending down. Closing as fixed.
