### ISSUE TITLE
[Bug]: Application crashes if quickly tapping the OK button on the "Add new collection" prompt

### ISSUE THREAD

**Issue by mariansima** [mozilla-mobile/fenix#22784]
### Steps to reproduce

1. Select a tab from the tab tray
2. Tap the collection button
3. Select the "Add new collection" option
4. Quickly tap the OK button

### Expected behaviour

The application is stable at all times

### Actual behaviour

The application crashes

https://user-images.githubusercontent.com/89511597/145558485-ff3d2320-7e92-407a-ab52-80c7aca1c398.mp4

### Device name

Samsung Galaxy A8

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

97.0a1 2021-12-10

### Device logs

85d903dd-92de-49a6-b3c3-83d8c2db55f9
java.lang.IllegalStateException: Fragment TabsTrayFragment{bcd2f58} (a0f90cba-79c2-4b47-97ed-afe9790ece8d) did not return a View from onCreateView() or this was called before onCreateView().
 * Sentry: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=33e16fc853b540138d83f552f63f1ec5
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-696880e8-00d9-446e-b5d5-c6ef20211210
----
java.lang.IllegalStateException: Fragment TabsTrayFragment{bcd2f58} (a0f90cba-79c2-4b47-97ed-afe9790ece8d) did not return a View from onCreateView() or this was called before onCreateView().
	at androidx.fragment.app.Fragment.requireView(Fragment.java:2)
	at org.mozilla.fenix.tabstray.TabsTrayFragment$onViewCreated$navigationInteractor$3.invoke(TabsTrayFragment.kt:4)
	at org.mozilla.fenix.tabstray.DefaultNavigationInteractor$onSaveToCollections$1.invoke(NavigationInteractor.kt:12)
	at org.mozilla.fenix.collections.CollectionsDialogKt$showAddNewDialog$1$1.invokeSuspend(CollectionsDialog.kt:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

### Additional information

Also occurs on 96.0.0-beta. 1 and RC 95.1.0 2021-11-30

**Comment by SoftVision-LorandJanos** [comment]
Reproduced on the Nightly it was logged with (2021-12-10).
Verified as fixed on the latest Nightly (2021-12-15).
Device used: Xiaomi Mi11 Lite (Android 11).
Closing the ticket as fixed.
