### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.manageDownloadsInDownloadsMenuTest >

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#22867]
### Stacktrace:

```Kotlin
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.DownloadRobot.waitForDownloadsListToExist(DownloadRobot.kt:63)
at org.mozilla.fenix.ui.SmokeTest$manageDownloadsInDownloadsMenuTest$7.invoke(SmokeTest.kt:754)
at org.mozilla.fenix.ui.SmokeTest$manageDownloadsInDownloadsMenuTest$7.invoke(SmokeTest.kt:753)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:137)
at org.mozilla.fenix.ui.SmokeTest.manageDownloadsInDownloadsMenuTest(SmokeTest.kt:753)
```

**Comment by AaronMT** [comment]
First occurrence in https://github.com/mozilla-mobile/fenix/pull/22822 ([log](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/AzP5e6c0Ra293KnyNmcbhA/runs/0/artifacts/public/logs/live_backing.log))

**Comment by AndiAJ** [comment]
Closing in favor of #17485
