### ISSUE TITLE
FNX3-16206 ⁃ [Bug] Crash when clicking a link in an external app

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2288]
### Steps to reproduce
1. make sure Fenix is your default browser
1. close Fenix via the Android recent apps view
1. click a link in an external app _without_ Custom Tabs support in Fenix (I used Twitter); clicking on a link in an external app _with_ Custom Tabs support in Fenix (like Gmail) does _not_ crash.

### Expected behavior
Fenix opens the website.

### Actual behavior
Fenix crashes.

```
2019-05-06 07:26:38.169 20385-20385/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 20385
    java.lang.NullPointerException: NullHandle
        at org.mozilla.geckoview.GeckoSession$Compositor.setFixedBottomOffset(Native Method)
        at org.mozilla.geckoview.GeckoDisplay.setVerticalClipping(GeckoDisplay.java:122)
        at org.mozilla.geckoview.GeckoView$Display.setVerticalClipping(GeckoView.java:180)
        at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:114)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:390)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:353)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:84)
        at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:51)
        at mozilla.components.feature.session.EngineViewPresenter.onSessionSelected(EngineViewPresenter.kt:47)
        at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:459)
        at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:20)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:99)
        at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:7)
        at mozilla.components.browser.session.LegacySessionManager.select(LegacySessionManager.kt:459)
        at mozilla.components.browser.session.LegacySessionManager.restore(LegacySessionManager.kt:215)
        at mozilla.components.browser.session.SessionManager.restore(SessionManager.kt:92)
        at org.mozilla.fenix.components.Core$sessionManager$2$$special$$inlined$also$lambda$1.invokeSuspend(Core.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
```

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision e04d7837b352fbdea45cfb58e30ce8027043f241

**Comment by cadeyrn** [comment]
Fixed by #2348.
