### ISSUE TITLE
Firefox for Android crashes on login screens

### ISSUE THREAD

**Issue by gyrofrog** [mozilla-mobile/fenix#22910]
When I reach a webpage with a login screen, Firefox crashes. This started on December 12.  

The instructions said to come here and log a new issue ... whereupon Firefox crashed again at the Github login screen.

Here's the crash report, from when I tried to login via Github (I'm doing this via Firefox on Windows)

f0b53d4e-9433-472b-8e91-1d71ad462c7b
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
----
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
	at mozilla.appservices.logins.LoginStore.getByBaseDomain(logins.kt:14)
	at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by gyrofrog** [comment]
Here's what the "About" screen says:

95.2.0 (Build #2015851755)
AC: 95.0.14, 4f3b0461e7
GV: 95.0.1-20211215221728
AS: 86.0.1

I'm using the uBlock Origin and NoScript Security Suite add-ons.

**Comment by gyrofrog** [comment]
Seems to occur on any website where I'm not already logged in, whether it's the login page or not. Sometimes the page will load after repeated attempts/crashes.

Here's another one, while trying to access this particular webpage (https://github.com/mozilla-mobile/fenix/issues/22910)
```
48e9b9dc-0453-435b-b20d-62090ee0e98e
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
----
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
	at mozilla.appservices.logins.LoginStore.getByBaseDomain(logins.kt:14)
	at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

```

**Comment by Amejia481** [comment]
@gyrofrog  could you share your device info (Brand, model, and Android Version)?

**Comment by gyrofrog** [comment]
Sure!
The phone is a Samsung Galaxy S20 FE 5G (SM-G781U)
Android 10

**Comment by Amejia481** [comment]
Thanks @abodea for testing

**Comment by gyrofrog** [comment]
Well since yesterday, I can't reproduce the crash.  I haven't (knowingly) changed anything on my phone; Firefox and Android are still the same versions.  However, it does look like uBlock Origin had a new update on Dec. 19th (though I am unsure when that was pushed to my phone).

**Comment by gyrofrog** [comment]
P.S. Yes I'm logged into the Firefox sync account, although it does not seem that everything syncs since then (which might be unrelated).

**Comment by parcelcat** [comment]
I think this is related: #22877

**Comment by gyrofrog** [comment]
Well now it started doing it again. I did notice that uBlock Origin was updated again, after I left my last note (when it was working).  But other than that I still haven't changed anything on my phone.

**Comment by gyrofrog** [comment]
Also crashes if I try to view a saved login.

```

3e1e99b5-cbcf-4e8d-910a-193219d54da2
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
----
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
	at mozilla.appservices.logins.LoginStore.list(logins.kt:14)
	at mozilla.appservices.logins.DatabaseLoginsStorage.list(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invokeSuspend(SyncableLoginsStorage.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$list$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at org.mozilla.fenix.settings.logins.controller.SavedLoginsStorageController$handleLoadAndMapLogins$fetchLoginsJob$1$1.invokeSuspend(SavedLoginsStorageController.kt:7)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)


```

**Comment by tkhyn** [comment]
Same issue here, has been happening for a few weeks. I have the same crashes each time I access a page with a login form or when I try to retrieve existing saved login / password info. I do not recall it stopped between Dec 19 and 23, and it still happens with uBlock Origin disabled so it does not look like it's due to the ad blocker, but rather the login manager

**Comment by boppreh** [comment]
Same here, on OnePlus 6, Android 11, with uBlock Origin and HTTPS Everywhere. Disabling sync didn't help either. I'd say it happens about 50-70% of the time, and in some non-login pages too. Makes the browser virtually unusable.

**Comment by grigoryk** [comment]
Just speculating for now, but so far this is the only new issue I found that aligns in terms of its uptick and when ya'll started to have problems (mid-December): https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/16150050/

**Comment by Amejia481** [comment]
@gyrofrog ,@boppreh, @tkhyn and @parcelcat would you mind trying on Firefox [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ?

**Comment by boppreh** [comment]
> @gyrofrog ,@boppreh, @tkhyn and @parcelcat would you mind trying on Firefox [nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix) ?

I actually haven't had any crashes in the past two days, even though Android says the Firefox app has not been updated. Since the original error was lock-related, I assume whatever race was crashing the browser before is now completing in a benign way.

**Comment by gyrofrog** [comment]
Yeah, it (the regular browser app) is working for me now, too.  But I recall that happening before, where it worked again one day and then crashed again later.

**Comment by gyrofrog** [comment]
Well I spoke too soon: the following link crashes in the regular app, but _not_ in the nightly:
`https://wtop.com/virginia/2022/01/republican-concedes-special-election-in-virginia-house/
`
I did add Noscript and uBlock Origin to the nightly app.

Here's the crash info

```
347ef5fc-8b89-4f77-a045-f760f253ca27
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
----
mozilla.appservices.logins.InternalException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
	at mozilla.appservices.logins.LoginStore.getByBaseDomain(logins.kt:14)
	at mozilla.appservices.logins.DatabaseLoginsStorage.getByBaseDomain(DatabaseLoginsStorage.kt:3)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)


```

**Comment by Amejia481** [comment]
We put a patch for issue that should be in the nightly version, we would like to verify if you are able to reproduce the issue there?

**Comment by gyrofrog** [comment]
I couldn't reproduce it in the nightly build, but the thing is, some sites that didn't work before work now (in the regular app).  The post I made about 10 minutes before yours was a crash in the regular app, but it worked OK in the nightly build. It was a website I hadn't visited in a while so I guess that's "fresh" information

**Comment by tkhyn** [comment]
@Amejia481 some of the pages that were (and still are) crashing work in the nightly for me, and the same is true for the link @gyrofrog provided. So it looks like the patch fixes that issue, thanks a lot! 
I signed in to ff sync in the nightly. There was no difference (i.e. it still worked in nightly, not in the official app) when enabling / disabling the only 2 extensions I have: uBlock origin and Google Search Fixer.

**Comment by gyrofrog** [comment]
I noticed Firefox had updated in the meantime but wasn't sure it included a fix:

96.1.1 (Build #2015855931), 8711f4f20+
AC: 96.0.11, 64c90c98b3
GV: 96.0-20220106144528
AS: 86.2.1


Saw crash again with the following URL: <https://cooking.nytimes.com/recipes/1015053-kimchi-omelet-with-sriracha-syrup>

It works anyway after 3rd try or so. Works fine in Nightly.

**Comment by kbrosnan** [comment]
This looks fixed. It was a common crash on 95 and rare crash on 96. There have been no crashes in 97 beta or release.
