### ISSUE TITLE
[Crash] RuntimeException: android.os.DeadSystemException at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:136)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#22958]
Originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1747117

There are some crash reports from Fenix 94, but the volume spiked in 95.

https://crash-stats.mozilla.org/report/index/f6131fef-4a13-44b8-8135-f3c450211221

```
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:136)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:9)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:14)
	at mozilla.components.lib.state.ext.FragmentKt$consumeFlow$1$invokeSuspend$$inlined$filter$1$2.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:232)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by mcarare** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/22262. Only occurs for SDK > 29.

**Comment by 674Y3r** [comment]
### Description
I can reproduce this crash by having really long text (~300 000 characters) in clipboard. In most cases it crashes instantly after selecting url bar, but sometimes it freezes. I managed to crash it during freeze by changing from private to normal tab using button at the top of home screen (selecting options in first startup screen seems to crash it too [24ae2564-fe77-4bb6-afbe-340890220116](https://crash-stats.mozilla.org/report/index/24ae2564-fe77-4bb6-afbe-340890220116)).

It seems like this only applies to url bar, because I couldn't reproduce it by opening search boxes on pages or by going through various browser options that require keyboard input.

Links to few random crash reports (in no particular order and with browser update in between).
- [74605dae-b323-4029-b01d-2f5e40220116](https://crash-stats.mozilla.org/report/index/74605dae-b323-4029-b01d-2f5e40220116)
- [dddb9bc0-4cf7-4e40-9020-7f04c0220116](https://crash-stats.mozilla.org/report/index/dddb9bc0-4cf7-4e40-9020-7f04c0220116)
- [f734aff2-108b-41e5-8355-d176d0220116](https://crash-stats.mozilla.org/report/index/f734aff2-108b-41e5-8355-d176d0220116)
- [5f11ff52-797f-4fd1-9b34-6f00d0220116](https://crash-stats.mozilla.org/report/index/5f11ff52-797f-4fd1-9b34-6f00d0220116)
- [06e8d84d-5fa0-4223-9aed-780b00220116](https://crash-stats.mozilla.org/report/index/06e8d84d-5fa0-4223-9aed-780b00220116)
- [54dbabd8-713f-4824-9bf4-154530220116](https://crash-stats.mozilla.org/report/index/54dbabd8-713f-4824-9bf4-154530220116)
- [e2dd3362-a48c-49bf-9274-b93060220116](https://crash-stats.mozilla.org/report/index/e2dd3362-a48c-49bf-9274-b93060220116)

### Additional notes:
- I'm using AnySoftKeyboard,
  - Note: when leaving and closing frozen Firefox, keyboard didn't wanted to open until I stopped both apps in settings,
- Clipboard was populated using pc through KDE Connect,
  - Although going to e.g. `reddit.com/r/rust.json` selecting and copying everything and then opening url bar seems to crash it too [40db9960-c361-4428-82b4-1d2810220116](https://crash-stats.mozilla.org/report/index/40db9960-c361-4428-82b4-1d2810220116).

**Comment by delia-pop** [comment]
We were not able to reproduce the issue in the latest Firefox 98.1.0 RC build.
