### ISSUE TITLE
[Crash] IllegalStateException: You must either set a text or a view at com.android.internal.util.Preconditions.checkState(Preconditions.java:173)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#22960]
Reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1739035

Crash report: https://crash-stats.mozilla.org/report/index/dd3c7a4d-2261-457a-987c-df9bf0211103

Very high crash volume. Looks like a regression in Fenix 93.

```
java.lang.IllegalStateException: You must either set a text or a view
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:173)
	at android.widget.Toast.show(Toast.java:188)
	at org.mozilla.fenix.HomeActivity$$ExternalSyntheticLambda2.onErrorResponse(Unknown Source:2)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:9)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by mcarare** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/22262. Only occurs for SDK > 29.

**Comment by kbrosnan** [comment]
Looks like a slight change in line numbers otherwise the stacks are the same. Looks like a duplicate.
