### ISSUE TITLE
Crash in [@ java.lang.IllegalStateException: at kotlinx.coroutines.sync.MutexImpl.lock(Mutex.kt:23)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#23011]
Crash report: https://crash-stats.mozilla.org/report/index/24468697-dc2f-40c4-a953-8bb0b0211229

This parent process crash looks like a regression in Nightly 97.0a1. We have 7941 crash reports from 2646 installations of Nightly 97.0a1.

Java stack trace:
```
java.lang.IllegalStateException
	at kotlinx.coroutines.sync.MutexImpl.lock(Mutex.kt:23)
	at mozilla.components.concept.storage.KeyManager.getOrGenerateKey$suspendImpl(KeyManager.kt:4)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invokeSuspend(SyncableLoginsStorage.kt:5)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage$getByBaseDomain$2.invoke(SyncableLoginsStorage.kt:2)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:1)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:9)
	at mozilla.components.service.sync.logins.SyncableLoginsStorage.getByBaseDomain(SyncableLoginsStorage.kt:1)
	at mozilla.components.service.sync.logins.GeckoLoginStorageDelegate$onLoginFetch$1.invokeSuspend(GeckoLoginStorageDelegate.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by cpeterso** [comment]
Fenix::Stability bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1747920

**Comment by cpeterso** [comment]
This crash regression spiked around 2021-12-16, but quickly tapered off. Has this crash already been fixed?

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/22877
