### ISSUE TITLE
FNX-5586 ⁃ RuntimeException: Unable to resume activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeEx...

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2314]
https://sentry.prod.mozaws.net/operations/fenix/issues/5319054/

```
IllegalStateException: Display already acquired
    at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:7)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:19)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:5)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
    at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
...
(41 additional frame(s) were not displayed)

RuntimeException: Failed to call observer method
    at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
    at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
    at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:39)
...
(31 additional frame(s) were not displayed)

RuntimeException: Unable to resume activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3823)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3855)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
...
(7 additional frame(s) were not displayed)

Unable to resume activity {org.mozilla.fenix/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
```

**Comment by agi90** [comment]
I get this from time to time, seems to be happening when Fenix has been on the background for a while and I open a custom tab link. Note: this was previously linked to a resolved issue, but according to Sentry and my testing this is definitely not fixed yet.

**Comment by softvision-miralobontiu** [comment]
Verified the scenario from agi90, I've opened some pages with custom tabs, left the app in the background for a few hours, reopened, everything worked fine. No crashes.
Tested with Sony Xperia Z5 Premium (Android 7.1.1), with the latest build 1.0.1923 (#11550608).
