### ISSUE TITLE
[Crash reporter] ArrayIndexOutOfBoundsException: length=320; index=331

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23160]
Top 10 in Socorro https://crash-stats.mozilla.org/report/index/136df7a3-1584-43d9-a988-60c440220111

Sentry nightly https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+ArrayIndexOutOfBoundsException
Sentry Beta
https://sentry.prod.mozaws.net/operations/firefox-beta/?query=is%3Aunresolved+ArrayIndexOutOfBoundsException
Sentry Stable
https://sentry.prod.mozaws.net/operations/firefox/?query=is%3Aunresolved+ArrayIndexOutOfBoundsException

```
java.lang.ArrayIndexOutOfBoundsException: length=320; index=331
    at androidx.compose.runtime.SlotTableKt.access$updateNodeCount(SlotTable.kt:1)
    at androidx.compose.runtime.SlotWriter.endGroup(SlotTable.kt:9)
    at androidx.compose.runtime.ComposerImpl.end(Composer.kt:97)
    at androidx.compose.runtime.ComposerImpl.endReplaceableGroup(Composer.kt:1)
    at androidx.compose.runtime.StaticProvidableCompositionLocal.provided$runtime_release(CompositionLocal.kt:1)
    at androidx.compose.runtime.ComposerImpl$startProviders$currentProviders$1.invoke(Composer.kt:18)
    at androidx.compose.runtime.ComposerImpl.startProviders(Composer.kt:7)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:2)
    at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:17)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:66)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:5)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:24)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:7)
    at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:8)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:21)
    at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:6)
    at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
    at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:1)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
    at android.view.View.dispatchAttachedToWindow(View.java:13532)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1299)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5888)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
    at android.view.Choreographer.doCallbacks(Choreographer.java:611)
    at android.view.Choreographer.doFrame(Choreographer.java:581)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19121)

**Comment by kbrosnan** [comment]
Looks to be a single OEM device running Android 5.1. Some sort of education tablet in Japan and also sold as a Verizon tablet. 

* STS-TOTTORI	TAB-A03-BR2
* STS-TOTTORI	TAB-A03-BR
* Quanta	QTAQZ3
