### ISSUE TITLE
Intermittent UI test failure - SitePermissionsTest: all audio & video permissions tests

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#23298]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6758542498543968589/executions/bs.8dc79fb5d6862c0a/test-cases
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowMicrophonePermissionChoiceTest$4.invoke(SitePermissionsTest.kt:77)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowMicrophonePermissionChoiceTest$4.invoke(SitePermissionsTest.kt:76)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:90)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowMicrophonePermissionChoiceTest(SitePermissionsTest.kt:76)`
### Build: 
debug 1/19

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19206)

**Comment by sv-ohorvath** [comment]
not certain, might be related to https://github.com/mozilla-mobile/fenix/issues/19237

**Comment by sv-ohorvath** [comment]
Moved here the rememberAllowAudioVideoPermissionChoiceTest report and I'll close the other issue as duplicate: https://github.com/mozilla-mobile/fenix/issues/23358

**Comment by sv-ohorvath** [comment]
As Aaron discovered, some AVDs on Firebase don't have a camera or microphone installed, which is the cause of these failures.

**Comment by sv-ohorvath** [comment]
More tests disabled in https://github.com/mozilla-mobile/fenix/pull/23904:
audioVideoPermissionChoiceOnEachRequestTest
rememberBlockAudioVideoPermissionChoiceTest
rememberAllowAudioVideoPermissionChoiceTest
microphonePermissionChoiceOnEachRequestTest
rememberBlockMicrophonePermissionChoiceTest
cameraPermissionChoiceOnEachRequestTest
rememberBlockCameraPermissionChoiceTest
rememberAllowCameraPermissionChoiceTest

**Comment by sv-ohorvath** [comment]
As it looks from these reports, the issues on API28 were (I assume) only audio-related tests:
rememberAllowAudioVideoPermissionChoiceTest 
rememberAllowMicrophonePermissionChoiceTest
and after the API30 upgrade, all tests started to fail.

**Comment by sv-ohorvath** [comment]
These tests are now running on a cron job on an API 28 device, separated from the other tests on API 30: https://github.com/mozilla-mobile/fenix/pull/25890#issuecomment-1177396742
