### ISSUE TITLE
Intermittent UI test failure - org.mozilla.fenix.ui.SitePermissionsTest - rememberAllowAudioVideoPermissionChoiceTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#23358]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7450399435631885158/executions/bs.d5eae80e09e3176/testcases/1/test-cases
### Stacktrace:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
	at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/59549169936095a29a2f6a45bf6cb6d8e540c693

**Comment by AaronMT** [comment]
@sv-ohorvath Can this new test benefit from `RetryTestRule`? I know that `verifyPageContent` is using a `SessionIdlingResource` what else can be used here?

**Comment by sv-ohorvath** [comment]
@AaronMT I tried the RetryTestRule but if the test fails after you have already given the app/page permissions, you can't reset the app while retrying, it will crash the test. Maybe there's a solution here, but I didn't see it.
I'm not sure what we can use, but I'll have to investigate deeper if it isn't an actual bug.

**Comment by sv-ohorvath** [comment]
Flaky on 1/24/22: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5736220999583984224/executions/bs.f84ab5da584b3f9e/test-cases

**Comment by sv-ohorvath** [comment]
Locally the test works perfectly, only seen intermittents on Firebase so far.
I did some debugging, trying to get the actual permission result if it was different than expected, and it looks like the element doesn't exist = no result from the javascript function. 
[report link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6901690375461483915/executions/bs.817f20ac7b6ec110/testcases/1/test-cases)

It is weird that only this test and https://github.com/mozilla-mobile/fenix/issues/23298 (caught while doing some preliminary check runs of these tests) are hitting this issue and the video permission test is working fine so far.

**Comment by AndiAJ** [comment]
Flaky 1x on 1/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8783789934447651333/executions/bs.e962ff07bc3b0d07/testcases/1/test-cases)


java.lang.AssertionError: Page didn't load or doesn't contain the expected text
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 2x on 1/29 Main

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6987449431947187152/executions/bs.f2eb2f5f1cadfee6/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5003774744227135626/executions/bs.76061176fabbf01c/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6754973813092881501/executions/bs.f062a5071af6b4c2/testcases/1/test-cases)

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:95)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5352387207535353876/executions/bs.6e0c3c18fd155711/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7471522327065362314/executions/bs.39082f6c94c741f2/testcases/1/test-cases)

Failed 1x on 2/9 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5756742239488704678/executions/bs.640daac933d9029c/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5756742239488704678/executions/bs.b0eec5839a20a7e1/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8545743945382462890/executions/bs.a296702db614f61e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 2/17 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7799721081276003014/executions/bs.de9ac555dfb27fe9/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7799721081276003014/executions/bs.4508921151a178b8/testcases/1/test-cases)

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:95)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Failed 1x on 2/18 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7661198875906469136/executions/bs.c0fcc0140bd91f85/testcases/1/test-cases)

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7661198875906469136/executions/bs.a9e66cfab1bab629/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 2/24: [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8861921527204184146/executions/bs.6ec5d86f06c0d1b0/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 2/25 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8852187052922880495/executions/bs.21d04694ba9309b8/testcases/1/test-cases)


java.lang.AssertionError: Page didn't load or doesn't contain the expected text
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8852187052922880495/executions/bs.f1e3a01819ad7416/testcases/1/test-cases)

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:95)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Failed 2x on 2/28 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7149394154176089021/executions/bs.5d598917d25fd2c6/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7149394154176089021/executions/bs.d0e43bbd713453c/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8526272505276262223/executions/bs.a2a66032fdc62c75/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8526272505276262223/executions/bs.9f79f66884121ce3/testcases/1/test-cases)
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:86)
at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$4.invoke(SitePermissionsTest.kt:85)
at org.mozilla.fenix.ui.robots.SitePermissionsRobot$Transition.clickPagePermissionButton(SitePermissionsRobot.kt:109)
at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:85)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
Since both tests are disabled for the same cause, I'll close this as duplicate to https://github.com/mozilla-mobile/fenix/issues/23298 (issue updated to include #23358 as well)
