### ISSUE TITLE
Intermittent UI test failure - < DownloadTest.pauseResumeCancelDownloadTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23434]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Resume, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickSystemNotificationControlButton(NotificationRobot.kt:56)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:129)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:126)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:83)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:126)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:38)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 1/26 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19285)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8345234132924003710/executions/bs.7cc6c2427a21ba16/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Resume, RESOURCE_ID=android:id/action0]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.NotificationRobot.clickSystemNotificationControlButton(NotificationRobot.kt:56)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:129)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:126)
at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:83)
at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:126)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7083929490654417210/executions/bs.3735a9822531e22/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Resume, RESOURCE_ID=android:id/action0]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.NotificationRobot.clickSystemNotificationControlButton(NotificationRobot.kt:56)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:129)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:126)
at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:83)
at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:126)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8112883617846183996/executions/bs.3a308768088b1291/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Resume, RESOURCE_ID=android:id/action0]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.NotificationRobot.clickSystemNotificationControlButton(NotificationRobot.kt:56)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:129)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:126)
at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:83)
at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:126)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7675341231802008307/executions/bs.1e80e86476eb3e84/testcases/1/test-cases)


androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_DESCRIPTION=Resume, RESOURCE_ID=android:id/action0]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.NotificationRobot.clickSystemNotificationControlButton(NotificationRobot.kt:56)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:129)
at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:126)
at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:83)
at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:126)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7857800586791855907/executions/bs.a23db3dbe7d38bef/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7758694448932467848/executions/bs.43a9f1beeed4e339/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6274715200932093927/executions/bs.3ed5b87bfa25ab24/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7231238784808241170/executions/bs.961b063c5e7987ac/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/22 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.ac88e8638690782e/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.2648ef763bab6c6d/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.d98ff0d16325af67/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.b4ea3a4ef1473e1b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8119555734501379986/executions/bs.46ef17c53af4cc11/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/22 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7388158075623210626/executions/bs.4b4ef54ce9531cd7/testcases/1/test-cases)

**Comment by AaronMT** [comment]
Failure on 4/27 after API30 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8311006727993183179/details?stepId=bs.e0e4d08537215a74&testCaseId=1)

**Comment by sv-ohorvath** [comment]
On the new target device with API30, the notification stack behavior is hard to predict, and harder to write a method for checking the download notification which will appear under the silent notifications, it could be expanded, collapsed, hidden, can show up for one second and gone the other. I'll leave this test disabled as it's too unstable to run for now.

**Comment by sv-ohorvath** [comment]
Re-enabled and running on the new API 28 cron-job:  https://github.com/mozilla-mobile/fenix/pull/25890
