### ISSUE TITLE
[Bug]: Sending a local file tab to a device crashes Firefox on that device.

### ISSUE THREAD

**Issue by SwanX1** [mozilla-mobile/fenix#23462]
### Steps to reproduce

1. Open any file in a tab on a computer (or any other device) (the URL should be something like `file:///path/to/file`)
2. Right-click on the tab > Send tab to device
3. Observe the app crashes on the device receiving the tab

### Expected behaviour

The tab should not be able to be sent, if it is sent, it should not be able to be received by the device. It should be treated as unsafe, and any errors (see crash report) should be caught when thrown.

### Actual behaviour

Firefox app on the receiving device crashes.

### Device name

Samsung Galaxy A52s 5G (SM-A528B/DS)

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.2.0

### Device logs
<details>

```
53a1bb50-9799-465c-9676-9b01abad2b10
android.os.FileUriExposedException: file:///mnt/sda1/Downloads/test_file.pdf exposed beyond app through Intent.getData()
----
android.os.FileUriExposedException: file:///mnt/sda1/Downloads/test_file.pdf exposed beyond app through Intent.getData()
at android.os.StrictMode.onFileUriExposed(StrictMode.java:2141)
at android.net.Uri.checkFileUriExposed(Uri.java:2391)
at android.content.Intent.prepareToLeaveProcess(Intent.java:11848)
at android.content.Intent.prepareToLeaveProcess(Intent.java:11797)
at android.app.PendingIntent.getActivity(PendingIntent.java:362)
at android.app.PendingIntent.getActivity(PendingIntent.java:324)
at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$1$3.invoke(BackgroundServices.kt:16)
at mozilla.components.feature.accounts.push.EventsObserver.onEvents(SendTabFeature.kt:17)
at mozilla.components.service.fxa.AccountEventsIntegration$onEvents$1.invoke(AccountStorage.kt:3)
at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
at mozilla.components.service.fxa.AccountEventsIntegration.onEvents(AccountStorage.kt:2)
at mozilla.components.service.fxa.FxaDeviceConstellation$processEvents$1.invoke(FxaDeviceConstellation.kt:3)
at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers(Unknown Source:7)
at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2$1.invoke(FxaDeviceConstellation.kt:24)
at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt:4)
at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:17)
at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:18)
at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2.invokeSuspend(FxaDeviceConstellation.kt:6)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```
</details>

### Additional information

Device the tab was sent from:
 - Linux, Ubuntu 20.04
 - Firefox 96.0 (64-bit)

I am able to provide any other information if requested.

**Comment by mcarare** [comment]
Closing in favor of https://github.com/mozilla-mobile/fenix/issues/23462 that also contains logs. Progress can be followed on that issue.

**Comment by SwanX1** [comment]
> Closing in favor of #23462 that also contains logs. Progress can be followed on that issue.

@mcarare, It seems you've linked this issue in your message, I assume it should be #20414.
