### ISSUE TITLE
 Sending a local file tab to a device crashes Firefox on that device.

### ISSUE THREAD

**Issue by oserlab** [mozilla-mobile/fenix#23543]
Steps to reproduce
Open any file in a tab on a computer (or any other device) (the URL should be something like file:///path/to/file)
Right-click on the tab > Send tab to device
Observe the app crashes on the device receiving the tab
Expected behaviour
The tab should not be able to be sent, if it is sent, it should not be able to be received by the device. It should be treated as unsafe, and any errors (see crash report) should be caught when thrown.

Actual behaviour
Firefox app on the receiving device crashes.

Device name
Samsung Galaxy A52s 5G (SM-A528B/DS)

Android version
Android 11

Firefox release type
Firefox

Firefox version
96[.](https://modprince.com/)2.0

Device logs
Details
Additional information
Device the tab was sent from:

Linux, Ubuntu 20.04
Firefox 96.0 (64-bit)
I am able to provide any other information if requested.

**Comment by grigoryk** [comment]
Tried this out locally, and yup, we crash with something like this:
```
02-02 19:42:11.655 13582 13582 E AndroidRuntime: FATAL EXCEPTION: main
02-02 19:42:11.655 13582 13582 E AndroidRuntime: Process: org.mozilla.fenix, PID: 13582
02-02 19:42:11.655 13582 13582 E AndroidRuntime: android.os.FileUriExposedException: file:///Users/grisha/Downloads/books/intuitive-python_P1.0.pdf exposed beyond app through Intent.getData()
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2356)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9881)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9835)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:342)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:304)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$1$3.invoke(BackgroundServices.kt:17)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.feature.accounts.push.EventsObserver.onEvents(SendTabFeature.kt:17)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.AccountEventsIntegration$onEvents$1.invoke(AccountStorage.kt:3)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.AccountEventsIntegration.onEvents(AccountStorage.kt:2)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.FxaDeviceConstellation$processEvents$1.invoke(FxaDeviceConstellation.kt:3)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers(Unknown Source:7)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2$1.invoke(FxaDeviceConstellation.kt:24)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt:4)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:17)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:18)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2.invokeSuspend(FxaDeviceConstellation.kt:6)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-02 19:42:11.655 13582 13582 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by kbrosnan** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/issues/20414
