### ISSUE TITLE
Crash IOException: Timed out when downloading wallpapers 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#23563]
Sentry https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/17697998/
```
java.io.IOException: Timed out
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:11)
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:6)
    at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:4)
    at org.mozilla.fenix.wallpapers.WallpaperDownloader$downloadWallpaper$2$2$1.invoke(WallpaperDownloader.kt:3)
    at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
    at org.mozilla.fenix.wallpapers.WallpaperDownloader$downloadWallpaper$2.invokeSuspend(WallpaperDownloader.kt:53)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Comment by Amejia481** [comment]
Sentry issue: [FIREFOX-NIGHTLY-EYN](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/17697998/?referrer=github_plugin)

**Comment by Amejia481** [comment]
Addressed on https://github.com/mozilla-mobile/fenix/commit/e290bc1bd6c4a9e3185e8f0bf9ffb433d378620d
