### ISSUE TITLE
Intermittent UI test failure - <SettingsPrivacyTest.saveLoginsInPWATest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23600]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, INDEX=0, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=username]
	at androidx.test.uiautomator.UiObject.getText(UiObject.java:564)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPrefilledLoginCredentials(BrowserRobot.kt:596)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5$7.invoke(SettingsPrivacyTest.kt:577)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5$7.invoke(SettingsPrivacyTest.kt:576)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:80)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:576)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:558)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:66)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:558)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 2/5 Main

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19403)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/3 Main[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7935899350925589962/executions/bs.79a4f71bbdafb8ff/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x 3/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5834214743541741101/executions/bs.60ba7eb0259f4f50/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/22 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.29642fcfbf301479/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.a7da8ac3b46b83c5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.be3bdc42aff4ed35/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.ca6e361ac19f2489/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7503015965810385104/executions/bs.52ef61c0b540c591/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on Debug 4/14: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7503015965810385104/executions/bs.52ef61c0b540c591/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.dee1d7fd36a30443/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5556923081587262800/executions/bs.51f72685c9471382/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:196)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:594)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:593)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:593)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8284089589761317682/executions/bs.c0a04cdb51308119/testcases/1/test-cases)

java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity } within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1651512972829 and now the last time the queue went idle was: 1651513020110. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:548)
	at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:547)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5788891211849078919/executions/bs.ed938328c719d0d0/testcases/1/test-cases)

java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity } within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1651583940108 and now the last time the queue went idle was: 1651583963335. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:548)
	at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:547)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5788891211849078919/executions/bs.ed938328c719d0d0/testcases/1/test-cases)

java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity } within 45000 milliseconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1651583940108 and now the last time the queue went idle was: 1651583963335. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:548)
	at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:376)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:547)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5596205753103991488/executions/bs.2e6bee2f20f8cf2/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:196)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:595)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:594)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:594)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5460873252149528487/executions/bs.66f7f17151f35598/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=username]
	at androidx.test.uiautomator.UiObject.setText(UiObject.java:666)
	at org.mozilla.fenix.ui.robots.BrowserRobot.fillAndSubmitLoginCredentials(BrowserRobot.kt:583)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:598)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:596)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:596)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7338317756672302018/executions/bs.8d4805d1dea37ed7/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=username]
	at androidx.test.uiautomator.UiObject.setText(UiObject.java:666)
	at org.mozilla.fenix.ui.robots.BrowserRobot.fillAndSubmitLoginCredentials(BrowserRobot.kt:583)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:598)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:596)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:596)

**Comment by sv-ohorvath** [comment]
Flaky on 5/12: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6325109800017567775/details?stepId=bs.7f25f905e80d2797&testCaseId=1&query=et.291f5ce14e1ada2f&deeplink=true)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6205589146968146110/executions/bs.870c8d85ee7f0dff/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8018778787200624400/executions/bs.e1dcf14f80014f41/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=username]
	at androidx.test.uiautomator.UiObject.setText(UiObject.java:666)
	at org.mozilla.fenix.ui.robots.BrowserRobot.fillAndSubmitLoginCredentials(BrowserRobot.kt:583)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:598)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:596)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:596)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8878394947742265741/executions/bs.d1aa571636195c8e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8599150317556569257/executions/bs.3ed10ca0827ed1f9/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Fixed with #25298
