### ISSUE TITLE
Intermittent UI test failure - < MediaNotificationTest.mediaSystemNotificationInPrivateModeTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23716]
### Stacktrace:
java.lang.AssertionError: Playback did not moved to state: PLAYING
	at org.junit.Assert.fail(Assert.java:89)
	at org.mozilla.fenix.ui.robots.BrowserRobot.assertPlaybackState(BrowserRobot.kt:538)
	at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:101)
	at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:98)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.MediaNotificationTest.mediaSystemNotificationInPrivateModeTest(MediaNotificationTest.kt:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6505466398412881049/executions/bs.d57a80556c7c1234/testcases/1/test-cases)

java.lang.AssertionError: Playback did not moved to state: PLAYING
at org.junit.Assert.fail(Assert.java:89)
at org.mozilla.fenix.ui.robots.BrowserRobot.assertPlaybackState(BrowserRobot.kt:538)
at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:101)
at org.mozilla.fenix.ui.MediaNotificationTest$mediaSystemNotificationInPrivateModeTest$3.invoke(MediaNotificationTest.kt:98)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
at org.mozilla.fenix.ui.MediaNotificationTest.mediaSystemNotificationInPrivateModeTest(MediaNotificationTest.kt:98)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
Flaky on 3/11: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8110454151101644654/executions/bs.9d74a3ba307bc60b/test-cases)

**Comment by AndiAJ** [comment]
Flaky 3/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7705189685308218709/executions/bs.2590404121e572c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7797596527594866708/executions/bs.87b769e6ff362b53/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7656546548319699377/executions/bs.d252ef1c67b32bfd/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/15 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8501391564667539794/executions/bs.8707d3a99ebe868f/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8501391564667539794/executions/bs.5813fa2fc62262a5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Fixed and re-enabled in #24763
