### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. openAllTabsInCollectionTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23739]
### Stacktrace:
androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:248)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection(TabDrawerRobot.kt:267)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection$default(TabDrawerRobot.kt:261)
	at org.mozilla.fenix.ui.SmokeTest$openAllTabsInCollectionTest$3.invoke(SmokeTest.kt:734)
	at org.mozilla.fenix.ui.SmokeTest$openAllTabsInCollectionTest$3.invoke(SmokeTest.kt:733)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.SmokeTest.openAllTabsInCollectionTest(SmokeTest.kt:733)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluateInner(AndroidComposeTestRule.android.kt:357)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:346)
	at androidx.compose.ui.test.junit4.android.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:63)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.android.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:150)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:38)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 2/14 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19496)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8196810256642212733/executions/bs.d92f2182dfceeb68/testcases/1/test-cases)

androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id is <org.mozilla.fenix.debug:id/collection_overflow_button>'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:5)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:25)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:18)
at org.mozilla.fenix.ui.robots.CollectionRobot.clickCollectionThreeDotButton(CollectionRobot.kt:122)
at org.mozilla.fenix.ui.SmokeTest$openAllTabsInCollectionTest$5.invoke(SmokeTest.kt:741)
at org.mozilla.fenix.ui.SmokeTest$openAllTabsInCollectionTest$5.invoke(SmokeTest.kt:740)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.expandCollection(HomeScreenRobot.kt:344)
at org.mozilla.fenix.ui.SmokeTest.openAllTabsInCollectionTest(SmokeTest.kt:740)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6588991798016413409/executions/bs.4a90def009aef4bd/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 2/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8692563289701035661/executions/bs.cddc987c39567687/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9027701154686361338/executions/bs.8d5e255ee984a0e4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8636223036716578004/executions/bs.8515b89f5c1cfa44/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8737018614605436173/executions/bs.44aa9a407a6c9db2/testcases/1)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7571716381124233523/executions/bs.30732521e17d1a6e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 2x on 3/31 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4931052203467081828/executions/bs.834adfe2caadbda2/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5783725821879837838/executions/bs.d1eea6cb7316d0c4/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4718751470234203031/executions/bs.961d894d901ba3b1/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.45471349b6bd5f4b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5556923081587262800/executions/bs.a4db36c944e9d2de/testcases/1/test-cases)

androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131362215/org.mozilla.fenix.debug:id/collection_name>
View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1023, height=692, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(wrapxwrap) gr=CENTER sim={adjust=pan} ty=APPLICATION fmt=TRANSLUCENT wanim=0x7f140005
fl=DIM_BEHIND ALT_FOCUSABLE_IM HARDWARE_ACCELERATED
fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
