### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23816]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySuggestedUserName(BrowserRobot.kt:628)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:299)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:292)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:292)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)

**Comment by AndiAJ** [comment]
Flaky1x on 2/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7886522204485771903/executions/bs.c2682556a7ca39c5/testcases/1/test-cases)

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPrefilledLoginCredentials(BrowserRobot.kt:635)
at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:302)
at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:292)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:292)
at java.lang.reflect.Method.invoke(Native Method)

**Comment by sv-ohorvath** [comment]
Flaky on 2/25 Main: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9013547153922251071/executions/bs.379fd92d8f6a918c)

`ava.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:464)
at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:294)
at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:292)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:292)`

**Comment by AndiAJ** [comment]
Flaky 1x on 3/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6893015053930923782/executions/bs.397000669472fe3b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7961619469912603677/executions/bs.f65868613817318/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4917488087587961829/executions/bs.fe016281edbd2ce8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/22 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.4296ab2c49517e49/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.bc44a1ed1d61f340/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.37cfc249c705a901/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7772509306765377746/executions/bs.f7521dc8637e5fbb/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4615233822896028987/executions/bs.640bfd2e99738813/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on debug 14/4: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5999639850219991053/executions/bs.442d20fb69b98250/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8692955215529957507/executions/bs.c9efe08fd41c33d8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5195192927831800455/executions/bs.4ece6e140f25d7f9/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:464)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:312)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:310)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:310)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/1 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7886110399420620651/executions/bs.e929677971aa7242/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:464)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:312)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:310)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:310)

**Comment by Mugurell** [comment]
This was also seen in https://github.com/mozilla-mobile/fenix/pull/25051.

**Comment by AndiAJ** [comment]
Failed on #24903
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9032329152035585449/executions/bs.4b662650aa635f6a/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9032329152035585449/executions/bs.98064a04794b6713/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:464)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:312)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:310)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:310)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7855219871393933100/executions/bs.b272b6405790b957/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8489326607428587927/executions/bs.31e7ec2a211d1a5c/testcases/1/test-cases)
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:464)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:312)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$verifyMultipleLoginsSelectionsTest$2.invoke(SettingsPrivacyTest.kt:310)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.verifyMultipleLoginsSelectionsTest(SettingsPrivacyTest.kt:310)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8961363929250737495/executions/bs.94215fdb6d7c71c9/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Disabled in #25060

**Comment by AndiAJ** [comment]
Fixed in  #25105
