### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest. toggleSearchSuggestionsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23817]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineSuggestionResults(SearchRobot.kt:310)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineSuggestionResults(SearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineSuggestionResults(SearchRobot.kt:83)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchSuggestionsTest$2.invoke(SettingsSearchTest.kt:190)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchSuggestionsTest$2.invoke(SettingsSearchTest.kt:188)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:200)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleSearchSuggestionsTest(SettingsSearchTest.kt:188)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluateInner(AndroidComposeTestRule.android.kt:357)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:346)
	at androidx.compose.ui.test.junit4.android.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:63)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.android.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:150)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 2/18 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19551)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for months.

**Comment by AndiAJ** [comment]
Failed 1x on 4/19 Nightly [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/6482124854380882696/executions/bs.404a353918080d7f/testcases/1)

**Comment by AndiAJ** [comment]
Failed 3x on Nightly
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/5935343914657235135/executions/bs.fb134dc298e1f012/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/5018284864117130005/executions/bs.d7ce6dddf6bb38f8/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/5207162383241090454/executions/bs.66019aefcdc8fab5/testcases/1/test-cases)

Seems like a regression from https://github.com/mozilla-mobile/android-components/pull/12000

**Comment by AndiAJ** [comment]
#23864 needs to be fixed for the test to work properly.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807295

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
