### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest.toggleVoiceSearchTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#23858]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SearchRobot.startVoiceSearch(SearchRobot.kt:72)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:210)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:208)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:200)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleVoiceSearchTest(SettingsSearchTest.kt:208)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluateInner(AndroidComposeTestRule.android.kt:357)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:346)
	at androidx.compose.ui.test.junit4.android.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:63)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.android.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:150)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 2/20 Main

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-19578)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7681397052728475747/executions/bs.f53e4455f686b6d5/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing for now, as it didn't fail for approx. a month

**Comment by sv-ohorvath** [comment]
Failed 2/2 runs on my PR: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7282540253963958874/details?stepId=bs.3089db422cf60923&testCaseId=1

**Comment by sv-ohorvath** [comment]
From the logs it appears that the intent was sent:
`Transition from ACTIVITY_FINISHED to INTENT_STARTED
06-02 08:34:24.086: I/ActivityTaskManager(477): START u0 {act=android.speech.action.RECOGNIZE_SPEECH cmp=com.google.android.googlequicksearchbox/com.google.android.voicesearch.intentapi.IntentApiActivity (has extras)} from uid 10152`
 but the voice recognition app didn't launch in the given amount of time. I'll try an intent validation instead.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5802194637017098129/executions/bs.f846e174a8937c8a/testcases/1/test-cases)

androidx.test.espresso.IdlingResourceTimeoutException: Wait for [Compose-Espresso link] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.ui.robots.SearchRobot.startVoiceSearch(SearchRobot.kt:96)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:216)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:214)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:259)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleVoiceSearchTest(SettingsSearchTest.kt:214)

**Comment by sv-ohorvath** [comment]
Not yet confirmed, but this could be caused by a bug in Compose when a compose view is hidden, as observed by other people in the FTL slack channel: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1649717690963949
A potential fix could be in 1.2.0-alpha07.
@AndiAJ will run the tests with the 1.2.0-alpha07 version to confirm.

**Comment by AndiAJ** [comment]
Thanks @sv-ohorvath , based on the results the next compose release could fix the inconsistency.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5831402259488321526/executions/bs.f7822c922a6c8ac5/testcases/1/test-cases)

androidx.test.espresso.IdlingResourceTimeoutException: Wait for [Compose-Espresso link] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.ui.robots.SearchRobot.startVoiceSearch(SearchRobot.kt:95)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:216)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:214)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:259)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleVoiceSearchTest(SettingsSearchTest.kt:214)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6004124826316730576/executions/bs.b9f324204debaba1/testcases/1/test-cases)

androidx.test.espresso.IdlingResourceTimeoutException: Wait for [Compose-Espresso link] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.ui.robots.SearchRobot.startVoiceSearch(SearchRobot.kt:91)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:216)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:214)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:256)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleVoiceSearchTest(SettingsSearchTest.kt:214)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flak 1x on 8/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8257035239687653875/executions/bs.32ef62ef82108f88/testcases/1/test-cases)

androidx.test.espresso.IdlingResourceTimeoutException: Wait for [Compose-Espresso link] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.ui.robots.SearchRobot.startVoiceSearch(SearchRobot.kt:91)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:217)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleVoiceSearchTest$2.invoke(SettingsSearchTest.kt:215)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:260)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleVoiceSearchTest(SettingsSearchTest.kt:215)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
