### ISSUE TITLE
Intermittent test failure debug(T) - org.mozilla.fenix.library.history.HistoryItemTimeGroupTest- WHEN grouping history item with 25 hours before midnight date THEN item is grouped to this week (failure at midnight)

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#23929]
Test fails if executed at midnight.

### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=368851855&repo=fenix
### Stacktrace:
```
[task 2022-02-23T00:00:00.538Z]   TEST: WHEN grouping history item with 25 hours before midnight date THEN item is grouped to this week
[task 2022-02-23T00:00:00.738Z]   FAILURE
[task 2022-02-23T00:00:00.738Z] 
[task 2022-02-23T00:00:00.743Z] java.lang.AssertionError: expected:<ThisWeek> but was:<Yesterday>
[task 2022-02-23T00:00:00.744Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2022-02-23T00:00:00.744Z] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[task 2022-02-23T00:00:00.744Z] 	at org.junit.Assert.assertEquals(Assert.java:118)
[task 2022-02-23T00:00:00.744Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2022-02-23T00:00:00.744Z] 	at org.mozilla.fenix.library.history.HistoryItemTimeGroupTest.WHEN grouping history item with 25 hours before midnight date THEN item is grouped to this week(HistoryItemTimeGroupTest.kt:119)
[task 2022-02-23T00:00:00.744Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2022-02-23T00:00:00.744Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2022-02-23T00:00:00.745Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-02-23T00:00:00.745Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-02-23T00:00:00.745Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2022-02-23T00:00:00.745Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2022-02-23T00:00:00.745Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2022-02-23T00:00:00.745Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2022-02-23T00:00:00.746Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2022-02-23T00:00:00.747Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2022-02-23T00:00:00.747Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2022-02-23T00:00:00.747Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2022-02-23T00:00:00.747Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2022-02-23T00:00:00.747Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2022-02-23T00:00:00.748Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2022-02-23T00:00:00.748Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2022-02-23T00:00:00.748Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2022-02-23T00:00:00.748Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2022-02-23T00:00:00.748Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2022-02-23T00:00:00.749Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-02-23T00:00:00.749Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-02-23T00:00:00.749Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2022-02-23T00:00:00.749Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2022-02-23T00:00:00.749Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2022-02-23T00:00:00.749Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2022-02-23T00:00:00.750Z] 	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
[task 2022-02-23T00:00:00.750Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
[task 2022-02-23T00:00:00.750Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2022-02-23T00:00:00.750Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2022-02-23T00:00:00.750Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-02-23T00:00:00.751Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-02-23T00:00:00.751Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2022-02-23T00:00:00.751Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2022-02-23T00:00:00.751Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2022-02-23T00:00:00.751Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2022-02-23T00:00:00.752Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2022-02-23T00:00:00.752Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2022-02-23T00:00:00.752Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2022-02-23T00:00:00.752Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2022-02-23T00:00:00.752Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2022-02-23T00:00:00.753Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2022-02-23T00:00:00.753Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/4e8615326e415104eca2985db2f95e886a070a2c

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19619)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813735

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
