### ISSUE TITLE
Instrumentation doesn't start on a Pixel 6 (physical) (Android 12)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#23943]
```Kotlin
2022-02-23 13:45:50.629 9757-9757/? E/appproc: ERROR: could not find class 'androidx.test.services.shellexecutor.ShellMain'
2022-02-23 13:45:50.629 9757-9757/? A/app_process: thread.cc:2365] No pending exception expected: java.lang.ClassNotFoundException: androidx.test.services.shellexecutor.ShellMain
```

```2022-02-23 13:40:41.059 7013-7013/? E/AndroidRuntime: FATAL EXCEPTION: main
    PID: 7013
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at androidx.test.services.speakeasy.client.ToolConnection$ToolConnectionPostIcs.doCall(ToolConnection.java:66)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:6)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:1)
        at androidx.test.services.shellexecutor.BlockingPublish.getResult(BlockingPublish.java:2)
        at androidx.test.services.shellexecutor.ShellCommandExecutorServer.start(ShellCommandExecutorServer.java:6)
        at androidx.test.services.shellexecutor.ShellMain.main(ShellMain.java:2)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.test.services.speakeasy.client.ToolConnection$ToolConnectionPostIcs.doCall(ToolConnection.java:50)
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:6) 
        at androidx.test.services.speakeasy.client.ToolConnection.publish(ToolConnection.java:1) 
        at androidx.test.services.shellexecutor.BlockingPublish.getResult(BlockingPublish.java:2) 
        at androidx.test.services.shellexecutor.ShellCommandExecutorServer.start(ShellCommandExecutorServer.java:6) 
        at androidx.test.services.shellexecutor.ShellMain.main(ShellMain.java:2) 
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) 
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355) 
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19629)

**Comment by AaronMT** [comment]
Possibly fixed in 1.4.1

https://www.higithub.com/android/issue/android-test/1042
