### ISSUE TITLE
[Crash] IndexOutOfBoundsException calling SafeIntentKt.intervalIndexForItemIndex

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#23989]
Started occurring 2 days ago:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/18474953/

Likely related to compose upgrade? (https://github.com/mozilla-mobile/fenix/commit/23f41c9c68d0def372f613cc2137b6e5474885c4.) No Fenix or A-C code in stack.

```
java.lang.IndexOutOfBoundsException: Index 0, size 0
    at mozilla.components.support.utils.SafeIntentKt.intervalIndexForItemIndex(SafeIntent.kt:9)
    at androidx.compose.foundation.lazy.list.LazyListItemsProviderImpl.getKey(LazyListItemsProviderImpl.kt:3)
    at androidx.transition.TransitionValuesMaps.getAndMeasure-0kLqBqw(TransitionValuesMaps.java:2)
    at androidx.compose.foundation.lazy.list.LazyListKt$rememberLazyListMeasurePolicy$1$1.measure-3p2s80s(LazyList.kt:82)
    at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$2.invoke(LazyLayout.kt:16)
    at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:19)
    at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:13)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
    at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:8)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.measure-BRTryo0(DelegatingLayoutNodeWrapper.kt:5)
    at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:3)
    at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:61)
    at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:31)
    at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:8)
    at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:12)
    at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:13)
    at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:2)
    at androidx.compose.ui.node.Owner$DefaultImpls.measureAndLayout$default(Owner.kt:1)
    at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:3)
    at android.view.View.draw(View.java:20264)
    at android.view.View.updateDisplayListIfDirty(View.java:19136)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4331)
```

**Comment by Mugurell** [comment]
Probably the same as https://github.com/mozilla-mobile/fenix/issues/23961 which offers more insights.

**Comment by csadilek** [comment]
Crashes went away after reverting the compose 1.1.0 upgrade, but let's keep this ticket around as a blocker for the upgrade.

**Comment by grigoryk** [comment]
A lot of these crashes in Socorro have `org.mozilla.fenix.perf.SearchDialogFragmentConstraintLayout.onMeasure` in their stacktraces, e.g. https://crash-stats.mozilla.org/report/index/43b9740f-9eb8-4cd3-9997-52e8f0220309

... but that seems unrelated to the issue at hand, e.g. something's going wrong while layout constraints are being resolved, and in case of `SearchDialogFragmentConstraintLayout` we override `onMeasure` to insert perf probes.

**Comment by Mugurell** [comment]
The updates were re-landed for a while now and it seems like https://github.com/Mugurell/android-components/commit/806f97413755ad7390a3f4165e87688dae2b8c05 helped fixthe crash. Things look good in Sentry.
