### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest.addPredefinedSearchEngineTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24024]
### Stacktrace:
java.lang.IllegalArgumentException: Can't scroll to index 5, it is out of bounds [0, 0)
	at androidx.compose.foundation.lazy.list.LazySemanticsKt$lazyListSemantics$1$3.invoke(LazySemantics.kt:90)
	at androidx.compose.foundation.lazy.list.LazySemanticsKt$lazyListSemantics$1$3.invoke(LazySemantics.kt:89)
	at androidx.compose.ui.test.ActionsKt$scrollToIndex$2.invoke(Actions.kt:146)
	at androidx.compose.ui.test.ActionsKt$scrollToIndex$2.invoke(Actions.kt:145)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread$lambda-0(AndroidSynchronization.android.kt:37)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.$r8$lambda$JHfZTn-RG8lrYeP9BZG_AgROyug(Unknown Source:0)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$$ExternalSyntheticLambda0.call(Unknown Source:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2163)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month
