### ISSUE TITLE
Intermittent UI test failure - < PwaTest.externalLinkPWATest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24074]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, INDEX=0, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=mib]
	at androidx.test.uiautomator.UiObject.setText(UiObject.java:666)
	at org.mozilla.fenix.ui.robots.BrowserRobot.fillAndSubmitGoogleSearchQuery(BrowserRobot.kt:577)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:49)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:47)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:66)
	at org.mozilla.fenix.ui.PwaTest.externalLinkPWATest(PwaTest.kt:47)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 3/2 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19704)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month

**Comment by AndiAJ** [comment]
Flaky 1x on 4/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5335208578285343305/executions/bs.3ab7fa955c17b933/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8340803670320999655/executions/bs.6256e10b1bdc112b/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.cf2531db50ff1d00/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5525004325908631939/executions/bs.8f8149a3ff5fea0c/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8843059143129947351/executions/bs.6a1a2ee2cc5fe578/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5559144539534571350/executions/bs.6678f2eff993db04/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.EditText, INDEX=0, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=mib]
	at androidx.test.uiautomator.UiObject.setText(UiObject.java:666)
	at org.mozilla.fenix.ui.robots.BrowserRobot.fillAndSubmitGoogleSearchQuery(BrowserRobot.kt:577)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:49)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:47)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.PwaTest.externalLinkPWATest(PwaTest.kt:47)

**Comment by AndiAJ** [comment]
Fixed with #25173
