### ISSUE TITLE
Intermittent UI test failure - < PwaTest. emailLinkPWATest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24092]
### Stacktrace:
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: Wanted to match 1 intents. Actually matched 0 intents.

IntentMatcher: resolvesTo: com.google.android.gm

Matched intents:[]

Recorded intents:
-Intent { act=mozilla.components.feature.pwa.VIEW_PWA dat=https://mozilla-mobile.github.io/... pkg=org.mozilla.fenix.debug } handling packages:[[org.mozilla.fenix.debug]])
-Intent { act=mozilla.components.feature.pwa.VIEW_PWA dat=https://mozilla-mobile.github.io/... flg=0x80000 pkg=org.mozilla.fenix.debug cmp=org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity (has extras) } handling packages:[[org.mozilla.fenix.debug]], extras:[Bundle[{activity_referrer_package=org.mozilla.fenix.debug, activity_referrer_category=-1, mozilla.components.feature.pwa.EXTRA_WEB_APP_MANIFEST={"name":"Yay an app with a super long name","short_name":"TEST_APP","start_url":"https:\/\/mozilla-mobile.github.io\/testapp\/externalLinks.html","display":"standalone","icons":[{"src":"https:\/\/mozilla-mobile.github.io\/testapp\/web_icon.png","sizes":"300x300","type":"image\/png","purpose":"any"}],"scope":"https:\/\/mozilla-mobile.github.io\/testapp\/","theme_color":"#FF69B4","dir":"auto","orientation":"any","related_applications":[],"prefer_related_applications":false}, open_to_browser=true, private_browsing_mode=false, activeSessionId=8d0300c1-5e40-4bdb-8e8a-bb06b7ff28e1}]])
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1538)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:190)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:170)
	at org.mozilla.fenix.helpers.TestHelper.assertNativeAppOpens(TestHelper.kt:224)
	at org.mozilla.fenix.ui.PwaTest$emailLinkPWATest$5.invoke(PwaTest.kt:68)
	at org.mozilla.fenix.ui.PwaTest$emailLinkPWATest$5.invoke(PwaTest.kt:66)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:66)
	at org.mozilla.fenix.ui.PwaTest.emailLinkPWATest(PwaTest.kt:66)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: junit.framework.AssertionFailedError: Wanted to match 1 intents. Actually matched 0 intents.

IntentMatcher: resolvesTo: com.google.android.gm

Matched intents:[]

Recorded intents:
-Intent { act=mozilla.components.feature.pwa.VIEW_PWA dat=https://mozilla-mobile.github.io/... pkg=org.mozilla.fenix.debug } handling packages:[[org.mozilla.fenix.debug]])
-Intent { act=mozilla.components.feature.pwa.VIEW_PWA dat=https://mozilla-mobile.github.io/... flg=0x80000 pkg=org.mozilla.fenix.debug cmp=org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity (has extras) } handling packages:[[org.mozilla.fenix.debug]], extras:[Bundle[{activity_referrer_package=org.mozilla.fenix.debug, activity_referrer_category=-1, mozilla.components.feature.pwa.EXTRA_WEB_APP_MANIFEST={"name":"Yay an app with a super long name","short_name":"TEST_APP","start_url":"https:\/\/mozilla-mobile.github.io\/testapp\/externalLinks.html","display":"standalone","icons":[{"src":"https:\/\/mozilla-mobile.github.io\/testapp\/web_icon.png","sizes":"300x300","type":"image\/png","purpose":"any"}],"scope":"https:\/\/mozilla-mobile.github.io\/testapp\/","theme_color":"#FF69B4","dir":"auto","orientation":"any","related_applications":[],"prefer_related_applications":false}, open_to_browser=true, private_browsing_mode=false, activeSessionId=8d0300c1-5e40-4bdb-8e8a-bb06b7ff28e1}]])
	at junit.framework.Assert.fail(Assert.java:50)
	at androidx.test.espresso.intent.VerificationModes$Times.verify(VerificationModes.java:80)
	at androidx.test.espresso.intent.Intents.internalIntended(Intents.java:346)
	at androidx.test.espresso.intent.Intents$2.check(Intents.java:194)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:10)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    
### Build: 3/3 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19719)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8737737946875135846/executions/bs.e888306f7d8613a2/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/22 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.98c0ac93d550e62/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6481699293202036185/executions/bs.8df0fec2ebecb3c7/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Failed 1x on 3/23 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7681397052728475747/executions/bs.12bd2ea0901af5da/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7681397052728475747/executions/bs.78880daefe0e3a47/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Flaky on 3/24 debug: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7188803470867051978/executions/bs.b817cc4c1ba6764

**Comment by AndiAJ** [comment]
Flaky 1x on 3/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6629411483903246862/executions/bs.5a0807b40ad09291/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 5/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6376239380738150855/executions/bs.5d9ac9131639e3c5/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Install]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.clickInstall(ThreeDotMenuMainRobot.kt:324)
	at org.mozilla.fenix.ui.PwaTest.emailLinkPWATest(PwaTest.kt:64)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8599499133086905800/executions/bs.ec1f0b863c0a65fb/testcases/1/test-cases)

androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.helpers.TestHelper.assertNativeAppOpens(TestHelper.kt:232)
	at org.mozilla.fenix.ui.PwaTest$emailLinkPWATest$5.invoke(PwaTest.kt:70)
	at org.mozilla.fenix.ui.PwaTest$emailLinkPWATest$5.invoke(PwaTest.kt:68)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.PwaTest.emailLinkPWATest(PwaTest.kt:68)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5013732482803529560/executions/bs.5fc148da67ad9cd0/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Install]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.clickInstall(ThreeDotMenuMainRobot.kt:324)
	at org.mozilla.fenix.ui.PwaTest.emailLinkPWATest(PwaTest.kt:66)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5176727413160994718/executions/bs.f1454d4ede0811bc/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Fixed with #25512
