### ISSUE TITLE
[Bug]: Firefox crashing for no apparent reason 

### ISSUE THREAD

**Issue by Jisreallycool** [mozilla-mobile/fenix#24090]
### Steps to reproduce

1. Open Firefox
2. open webpage
3. mess around on the page for a bit
4. crash

### Expected behaviour

The web page should function correctly.

### Actual behaviour

The app closes unexpectedly.

### Device name

LG Wing

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

96.2.0

### Device logs

fc0c56e0-abcc-4345-99b3-21a0e1dddf81
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$WEx@5a2adc1 is not valid; is your activity running?
----
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$WEx@5a2adc1 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:977)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:416)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:102)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1599)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1355)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1321)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup.show(FloatingToolbar.java:614)
	at com.android.internal.widget.FloatingToolbar.doShow(FloatingToolbar.java:302)
	at com.android.internal.widget.FloatingToolbar.show(FloatingToolbar.java:232)
	at com.android.internal.view.FloatingActionMode$FloatingToolbarVisibilityHelper.updateToolbarVisibility(FloatingActionMode.java:391)
	at com.android.internal.view.FloatingActionMode$1.run(FloatingActionMode.java:67)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7631)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19718)

**Comment by LaviniaL99** [comment]
Hello @Jisreallycool 

Thanks for you report! I verified the issue on the latest Nightly build (99.0a1 from 03/08) and latest RC build (98.1.1) and i was not able to reproduce the issue. 

**Device used:**
- Samsung S10E-> Android 10

Can you please verify if you are still able to reproduce the issue on the latest builds and if so, please let me know if there is a **specific webpage** where the problem occurs and please attach a video of the interest flow.

Thanks!
