### ISSUE TITLE
Intermittent debug(T) - org.mozilla.fenix.settings.creditcards.DefaultCreditCardEditorControllerTest - handleSaveCreditCard

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#24143]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=370019258&repo=fenix
### Stacktrace:
```
[task 2022-03-04T20:16:42.489Z] SUITE: org.mozilla.fenix.settings.creditcards.DefaultCreditCardEditorControllerTest
[task 2022-03-04T20:16:43.589Z]   TEST: handleSaveCreditCard
[task 2022-03-04T20:16:43.889Z]   FAILURE
[task 2022-03-04T20:16:43.889Z] 
[task 2022-03-04T20:16:43.891Z] io.mockk.MockKException: Can't instantiate proxy for class kotlin.Function1
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
[task 2022-03-04T20:16:43.891Z] 	at org.mozilla.fenix.settings.creditcards.DefaultCreditCardEditorControllerTest.<init>(DefaultCreditCardEditorControllerTest.kt:225)
[task 2022-03-04T20:16:43.891Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[task 2022-03-04T20:16:43.891Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[task 2022-03-04T20:16:43.891Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2022-03-04T20:16:43.891Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2022-03-04T20:16:43.891Z] 	at jdk.internal.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
[task 2022-03-04T20:16:43.891Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2022-03-04T20:16:43.891Z] 	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
[task 2022-03-04T20:16:43.891Z] 	at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
[task 2022-03-04T20:16:43.891Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[task 2022-03-04T20:16:43.891Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2022-03-04T20:16:43.891Z] 	at java.base/java.lang.Thread.run(Thread.java:829)
[task 2022-03-04T20:16:43.891Z] Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass interface kotlin.jvm.functions.Function1
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:38)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:34)
[task 2022-03-04T20:16:43.891Z] 	... 47 more
[task 2022-03-04T20:16:43.891Z] Caused by: java.lang.IllegalArgumentException: Could not create type
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:155)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.subclass(SubclassInstrumentation.kt:51)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.ProxyMaker.subclass(ProxyMaker.kt:113)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.ProxyMaker.proxy(ProxyMaker.kt:35)
[task 2022-03-04T20:16:43.891Z] 	... 48 more
[task 2022-03-04T20:16:43.891Z] Caused by: java.lang.IllegalStateException: Failed to invoke proxy for public abstract java.lang.Class net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup$MethodHandles$Lookup.defineClass(java.lang.Object,byte[]) throws java.lang.IllegalAccessException
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1123)
[task 2022-03-04T20:16:43.891Z] 	at com.sun.proxy.$Proxy48.defineClass(Unknown Source)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1621)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:113)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:492)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
[task 2022-03-04T20:16:43.891Z] 	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6147)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.doInterceptedSubclassing(SubclassInstrumentation.kt:98)
[task 2022-03-04T20:16:43.891Z] 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation.access$doInterceptedSubclassing(SubclassInstrumentation.kt:21)
[task 2022-03-04T20:16:43.892Z] 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:54)
[task 2022-03-04T20:16:43.892Z] 	at io.mockk.proxy.jvm.transformation.SubclassInstrumentation$subclass$1.call(SubclassInstrumentation.kt:21)
[task 2022-03-04T20:16:43.892Z] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
[task 2022-03-04T20:16:43.892Z] 	... 52 more
[task 2022-03-04T20:16:43.892Z] Caused by: java.lang.LinkageError: loader 'app' attempted duplicate class definition for kotlin.jvm.functions.Function1$Subclass23. (kotlin.jvm.functions.Function1$Subclass23 is in unnamed module of loader 'app')
[task 2022-03-04T20:16:43.892Z] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[task 2022-03-04T20:16:43.892Z] 	at java.base/java.lang.System$2.defineClass(System.java:2131)
[task 2022-03-04T20:16:43.892Z] 	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
[task 2022-03-04T20:16:43.892Z] 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[task 2022-03-04T20:16:43.892Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2022-03-04T20:16:43.892Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[task 2022-03-04T20:16:43.892Z] 	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$Dispatcher.invoke(Unknown Source)
[task 2022-03-04T20:16:43.892Z] 	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:986)
[task 2022-03-04T20:16:43.892Z] 	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1110)
[task 2022-03-04T20:16:43.892Z] 	... 63 more
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/2fba91ea791cd4cbe0af824e201c6fddbe1a248a

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19760)

**Comment by Archaeopteryx** [comment]
Similar for org.mozilla.fenix.settings.quicksettings.DefaultQuickSettingsControllerTest: https://treeherder.mozilla.org/logviewer?job_id=370930368&repo=fenix

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813738

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
