### ISSUE TITLE
Addresss StrictMode crash on debug for isThemedWallpapersFeatureEnabled

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#24175]
This issue is only reproducible on debug

```
2022-03-09 15:54:13.758 17307-17425/? E/ExceptionHandler: Uncaught exception handled:
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:45)
        at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:39)
        at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1890)
        at android.os.StrictMode$AndroidBlockGuardPolicy$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
        at [libcore.io](http://libcore.io/).BlockGuardOs.access(BlockGuardOs.java:74)
        at [libcore.io](http://libcore.io/).ForwardingOs.access(ForwardingOs.java:131)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7747)
        at [java.io](http://java.io/).UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at [java.io](http://java.io/).File.exists(File.java:813)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:751)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:742)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:698)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:923)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:545)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
        at mozilla.components.support.locale.LocaleManager$Storage.getSharedPreferences(LocaleManager.kt:140)
        at mozilla.components.support.locale.LocaleManager$Storage.getLocale(LocaleManager.kt:116)
        at mozilla.components.support.locale.LocaleManager.getCurrentLocale(LocaleManager.kt:48)
        at org.mozilla.fenix.FeatureFlags.isThemedWallpapersFeatureEnabled(FeatureFlags.kt:94)
        at org.mozilla.fenix.home.HomeFragment.shouldAnimateLogoForWallpaper(HomeFragment.kt:1170)
        at org.mozilla.fenix.home.HomeFragment.onResume(HomeFragment.kt:754)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3048)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
        at android.app.Activity.performResume(Activity.java:8219)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4814)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19782)

**Comment by Amejia481** [comment]
For ignoring the issue we could use `context.components.strictMode.resetAfter`

**Comment by Archaeopteryx** [comment]
Does this also explain [this screenshot test run](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6161996319292934086) (which runs once per week) which had all tests failing?

**Comment by Amejia481** [comment]
It's related to wallpaper but it's not the same issue, this one is related to `WallpaperFileManager.clean`. I filed this ticket https://github.com/mozilla-mobile/fenix/issues/24194
