### ISSUE TITLE
Crash in [@ java.lang.RuntimeException: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java)] in java.lang.IllegalArgumentException: Tab with same ID already exists

### ISSUE THREAD

**Issue by caniblaze420** [mozilla-mobile/fenix#24393]
d7f66cbe-4126-4bc1-80cb-4e70ea1a4a37
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
----
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:1)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7156)
... 3 more
Caused by: java.lang.IllegalArgumentException: Tab with same ID already exists
at mozilla.components.browser.state.reducer.TabListReducerKt.access$requireUniqueTab(TabListReducer.kt:4)
at mozilla.components.browser.state.reducer.TabListReducer.reduce(TabListReducer.kt:156)
at mozilla.components.browser.state.store.BrowserStore$1.invoke(BrowserStore.kt:356)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$chain$1.invoke(ReducerChainBuilder.kt:7)
at mozilla.components.browser.state.engine.middleware.TrimMemoryMiddleware.invoke(TrimMemoryMiddleware.kt:3)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.CrashMiddleware.invoke(CrashMiddleware.kt:3)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.WebExtensionMiddleware.invoke(WebExtensionMiddleware.kt:15)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.SuspendMiddleware.invoke(SuspendMiddleware.kt:9)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.TabsRemovedMiddleware.invoke(TabsRemovedMiddleware.kt:24)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.LinkingMiddleware.invoke(LinkingMiddleware.kt:21)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.CreateEngineSessionMiddleware.invoke(CreateEngineSessionMiddleware.kt:18)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.state.engine.middleware.EngineDelegateMiddleware.invoke(EngineDelegateMiddleware.kt:23)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at org.mozilla.fenix.historymetadata.HistoryMetadataMiddleware.invoke(HistoryMetadataMiddleware.kt:50)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.media.middleware.LastMediaAccessMiddleware.invoke(LastMediaAccessMiddleware.kt:3)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.search.middleware.AdsTelemetryMiddleware.invoke(AdsTelemetryMiddleware.kt:51)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.prompts.PromptMiddleware.invoke(PromptMiddleware.kt:18)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.media.middleware.RecordingDevicesMiddleware.invoke(RecordingDevicesMiddleware.kt:3)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.search.middleware.SearchMiddleware.invoke(SearchMiddleware.kt:12)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.search.region.RegionMiddleware.invoke(RegionMiddleware.kt:7)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.session.middleware.undo.UndoMiddleware.invoke(UndoMiddleware.kt:36)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.browser.thumbnails.ThumbnailsMiddleware.invoke(ThumbnailsMiddleware.kt:46)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at org.mozilla.fenix.telemetry.TelemetryMiddleware.invoke(TelemetryMiddleware.kt:29)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.readerview.ReaderViewMiddleware.invoke(ReaderViewMiddleware.kt:43)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.downloads.DownloadMiddleware.invoke(DownloadMiddleware.kt:66)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.recentlyclosed.RecentlyClosedMiddleware.invoke(RecentlyClosedMiddleware.kt:47)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.feature.session.middleware.LastAccessMiddleware.invoke(LastAccessMiddleware.kt:8)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:10)
at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19926)

**Comment by csadilek** [comment]
@caniblaze420 Do you have steps to reproduce this i.e., what are you doing right before this crash happens? 

We have not seen any other reports of this. Also, can you share what version of Firefox you're using?

**Comment by sunilk9211** [comment]
In which version was this found? This issue was reported and fixed for version 98.0. https://github.com/mozilla-mobile/fenix/issues/23583

**Comment by lobontiumira** [comment]
I've encountered this crash on the Focus Nightly 101.0a1 (build 361030509 with GV 101.0a1-20220412094307) with Samsung Galaxy note 8 (Android 9), and found the STR:

1. Have fingerprint set and enabled on your device.
2. On Focus, go to Settings - Privacy & Security - Switching Apps, and enable the use of fingerprint.
3. On Focus open a page.
4. Put Focus in background, without closing it.
5. From the device's settings, delete the fingerprint set on step 1.
6. Open Focus -> crash.

Reproducible 2/2

b2c27e0c-9158-4f11-b97f-9b3755aad3a8
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
* New Sentry Instance: <No URL>
* Socorro: https://crash-stats.mozilla.org/report/index/bp-65b3d67e-2eda-4e83-8bbb-24cd30220414

**Comment by mcarare** [comment]
STR could be helpful to further investigate this. Maybe @caniblaze420 can help with that.

Also, regarding to this being a Focus isssue, the stacktrace contains calls from the fenix code base:

`at org.mozilla.fenix.historymetadata.HistoryMetadataMiddleware.invoke(HistoryMetadataMiddleware.kt:50)
`
