### ISSUE TITLE
Intermittent UI test failure - SmokeTest.openMainMenuAddTopSiteTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24458]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7188803470867051978/executions/bs.876f07e3607501da
### Stacktrace:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id is <org.mozilla.fenix.debug:id/top_sites_list>)
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertExistingTopSitesTabs(HomeScreenRobot.kt:650)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertExistingTopSitesTabs(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyExistingTopSitesTabs(HomeScreenRobot.kt:137)
at org.mozilla.fenix.ui.SmokeTest$openMainMenuAddTopSiteTest$5.invoke(SmokeTest.kt:338)
at org.mozilla.fenix.ui.SmokeTest$openMainMenuAddTopSiteTest$5.invoke(SmokeTest.kt:337)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.goToHomescreen(BrowserRobot.kt:73
### Build: 
debug 3/24

**Comment by AndiAJ** [comment]
Flaky 1x on 3/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4795469606298877166/executions/bs.25338223783adc73/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8289600709456727063/executions/bs.ec490577aff50477/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Removed in favour of verifyAddToFirefoxHome
