### ISSUE TITLE
Intermittent UI test failure - selectAndSearchTextTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24457]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6442021535674591773/executions/bs.d463739e690d99e3/test-cases
### Stacktrace:
Intrumentation Crash
[Logs](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6442021535674591773/executions/bs.d463739e690d99e3/testcases/1/logs)
### Build: 
debug 3/24

**Comment by sv-ohorvath** [comment]
Same crash occurs on https://github.com/mozilla-mobile/fenix/issues/24281

**Comment by AndiAJ** [comment]
Checked the status of this test today.
Ran the test 50x on Firebase and was Flaky 4x in all cases due to this crash.

[Logcat](https://00f74ba44b076e4d384f1a63f2d09bc2d2d3e338b4-apidata.googleusercontent.com/download/storage/v1/b/fenix_test_artifacts/o/2022-04-19_12-43-46.170997_tSAl%2Fmatrix_0_31%2FPixel2-28-en_US-portrait%2Flogcat?jk=AFshE3WrHFDUeUiMiPHkInDfi5cB4aWd_rMxV_HyiEbXGRaYA9lM_2mBltVZVoTJM4jfB19I0W8oY8u_P5MlEaf8Uh3ZTkJ1X2KrBOQTWDsUDIoXUzP5GB4ca5l5RLlGMYaTRodCWS26ibFfhecuP6PSuwXOGQFQCeOhMduCKWx7F4ddz0K2Sw5M0ShbxP7LdHcIqpX6n5-TN24oKYK7FQDLcmXhIrLYvkj_ENXAyC459SJ-r6IvWkcvYRn4BBHuRZriTzzUHXUg2vyLRZW4pdkCVSVgvisGMJoyDSKhp5xgCtisIP0tw7euIHT9EaoYOyxcH7uO5XX3g2GS5GQ7FMQKC3GHE2ff6NiJdGXjQRb2PSgxKAyo8u13a_NoGPvPPAuFd10XYGWiNzR9BdapMFuLXte61pP8vbdwISxjcqO37EGUXi1kPo4Vjs4MhneAlIzZS_CJLyUrh09tvJlNo9x1B0Z4MOFOqR8VNGJnKyIjOmbS55zOkhTsM_hWnTdZWoovdL3xGGBBTbU9BNygNw4AZ6Qhf_VtQClJIE2NHNK1qESCZ5s611Y0_HRoCM-yrmmpifYBvbcZ6aJcPQK1l6ZoG_-aXcrVbm6Fy1OyAhK7oCNddok7q956uwZMlhcnhV0PMgw2Pek2no3OJOOvVKZbfpE41BUEhkxdMrvM3OpGeXPBlKtp2UgddjOsmGGh2wh84HjCqatWRP6U595yfJkuMILYYK1wK2mWFgpBQSXpkxPpcoGZfvp_xkXNjGJbG-G-aF22Et-RMvvjeCaoV3o3XpEx0uor3JzicZf43Oeiweu2xKknzCFoTJIRs3gwXDNcnds4Ds12ffecjT_4lNCwYLmwGE9ZnVoY4xA16mh9VX19RBdYKszXv5oV8lwMlvsukzgOzS_CzBXxFN9Qxk6jYopK3dyq1DClCzbW2GROkJ86EFFxFsZw-G3D4YIt6sGudPxvXyhkjys-Ad6PayQxiSfNyZfbFqUv8Stp7WtaOR4sxgmL32zBuLauzl_Sk9r7TrHvvkSGWvSudPwLyWGjDM47X-3jIkewmH-fgbWWUn7iOas1-61YWFLAnFaRtYwN86gbZEXG1UMQkXeC74218XEq2nXnv54w4MokH4x4paJOl01f2uo&isca=1)
[Logcat](https://00f74ba44b1dbdcb278b8d0047b10b77ef1ee4f706-apidata.googleusercontent.com/download/storage/v1/b/fenix_test_artifacts/o/2022-04-19_12-43-46.170997_tSAl%2Fmatrix_0_41%2FPixel2-28-en_US-portrait%2Flogcat?jk=AFshE3XWzGXBmcWBB51vC2Cd3LyanTJbx2YNjetRqxwQlJVSDaKtMo_vrMoV0BRB8Sm2Mrb0T1XLObbq7THrhIjR7o6W5W49CuRQBqgfLShx80tzl60p77IXZEzhRA0ZMdk8MpX8ZAh8Wpp-o6Mmnel7dzQWcty86ypcQLp7TIv1XbfDfVIrtedm-7wzsJKtQ4AIMHCZ1m8L1pPYHq1XgZKm7L9dNqOymrPD0PX4MBpwPhkS3H6OKMmkHnU0mbJGrsTG1Bhm5ceH0YSm6xPnsW58pJUG_OXmSyyyBSh2rxA2Ux3NMWdF9O30JPXq_DhsXdVsOuhEVuuW2XiXfZNstcRv0PSMTY-tKriHEhAuOmH_mZGv6OnblTOI9DoH1zbM8ktDvWDiNGC6Vbb4dcRYM5IF9Dww8ETCrjGVQLIpsSmckuNr0kqnjbqaAhj2Yy22O-t9GnDUsBh6JTF_0EKS2Lo2KRTN5imR4TdI-gaAVZgWhR7REqlo4noBzItPWJsU0qq7ISt-NbkPlKaNIHEx-mwb_cFwF-VMJGVm5XmAWYLV7TCe2G9A1LvHtYXSJQwULX9TlIK2G1xBG5MMTSSMEO-yn7i6m4dceaVJNGYyNcVOTgEJQX1342dgFzcZo0QGfNHJm2S4VGpSqEFZNAMS5CtoGkd49TBaLQZp5uhGscuhkWSz5TMtGbBUUSlZOMh5vKWqvVn33t47B_J2HYySnibCeKN1CXP23QQBq5VIKzZG3qU6l2-dMrpZ2jaPSL9VLIZl8iEHLz9OPyJ6bd6MaZXszp3T260FGIzCo_SPfzNi-cMOhiRRVy4MGrw6g_6dTXBcSU_EZ8aOvEpoAjAI_9w_JwRVI3Srcx7UAV4LpFyUBxa2abrYvrZDycXCbCa0NRRmNjjrqHIpzxQL31vQH8h6ilfaJNjVItA6et4uLFkwNiGuw0cm89y7p9KHZErfqjuMqBwIFC1ZPGRDVzxDZSIcxGbD8OkdN4qGkFrAgu_UhYFKVmnCzEQlMp4sgP-0RW-zQuza2_r92Il8ve8tbkZ0KOdOllSWyIZQTKIxbCSCbjvOP7ppksKioMCwO7LJ4aiKhZxF_0aLsJlfT1IISHiu1zAtOnJCU3oXpK9w4KSEXYfYCYQLIWo&isca=1)
[Logcat](https://00f74ba44b24f8ba9a072cc1c7ba121f1f22dc2046-apidata.googleusercontent.com/download/storage/v1/b/fenix_test_artifacts/o/2022-04-19_12-43-46.170997_tSAl%2Fmatrix_0_42%2FPixel2-28-en_US-portrait%2Flogcat?jk=AFshE3WcFe5EW1kBCzjx_60Z1nJdMP35JcCb36vSfrgDfNFFogrJ_fbhfdPmNxspmmVNC5ucslj8-iNeqdkpCT_ur_s9Unkj8y22ySmsFGy92PX0gaIvy0q08LG61ZVFtEIYtLp79yxLQ5ZU0LgGWy8-RprY-fD2eHpl9kxTdwcBZgd8JcN8S4oJB3CMMMaydTUYcPc82qBb0DETRaXcPvhjsq1tSmNANqn3dkyFk3uEYgCZGgKe09-Kagfv1xEsU05tXuq1a7CnnsAWZE-qcM-4qTxfUbU6rgjGoIY9DbepaRsYFeDb0jUlnxWbOx8-M0egzVYeRBgM8F3aIBCdIWq_J9cLgxqSFo1XVnrQLv2Whv4isVzBTyjBt4REQfdTZC2bmAF6mlYD8qND52rJuv0sTOuS7PYF0ScT5Ya35_27LVvSTa5cSBuN3kq-0TA42lfGvaMTSiedj24y9qTCHu8lIgA00FpAgpSmR9Ue3WAa35KhJCsnhe3J3W-Qiit6iDTs9pSV_xOekCuYvWb5uocnZbU7NENTOpp3XaZHFCqmMrO2NCe1s1xP9AuO9AX1pn3DS4f3qNPKPRQmRdMXhfB7yUJCGT7GBXq1bYzFk1L1GE4F8cpcYcuqkKJHnZwZnaXipyYGCqMGLpN6eCEeAZC2k5Z4FxpF-m-4dxcJk1x4F3SK0PKYrbM0W0ijfCqtsIdg06zFirapeqwYdgChwLRmdEGuvtEvJkYi-5tjsU0yA2498RJQWjoxJM_ItIn98SpFDo5sK9hj9ZP0kEMtcAAf4jtoy8XL1qODj9sO4N07VAAEq0S1z3yHk5qW3fG4f6_KJVTS3IJjiRQo4CfeGYMnCZb2OdYrofr62hiOxcusstoc_pG-6jEtq9zqh0tdgzS-gjlG1X8PfW6IiDKDyzdOqdRBQx0QwDJ76hn_rkxginkV3cNkTtHNPdvM_2ERwUh_TNJuCBPfSkoZQAtT6h7zY4mWFO1UTYuuTDX9c8mBQK6veCxnLYNy2nX762DYCOS2z33E5gXGkZ2xqyjrt3lSKiPKRwkmMRo3V4wb-BIqpYQQBMEeW_ixATd_OlpBk5gPpZjYESdh3PLA0SQpPVuikeImPCo8Zeqy5wi16jkCVB_oBBdcDAQ&isca=1)
[Logcat](https://00f74ba44b24f8ba9a072cc1c7ba121f1f22dc2046-apidata.googleusercontent.com/download/storage/v1/b/fenix_test_artifacts/o/2022-04-19_12-43-46.170997_tSAl%2Fmatrix_0_42%2FPixel2-28-en_US-portrait%2Flogcat?jk=AFshE3WcFe5EW1kBCzjx_60Z1nJdMP35JcCb36vSfrgDfNFFogrJ_fbhfdPmNxspmmVNC5ucslj8-iNeqdkpCT_ur_s9Unkj8y22ySmsFGy92PX0gaIvy0q08LG61ZVFtEIYtLp79yxLQ5ZU0LgGWy8-RprY-fD2eHpl9kxTdwcBZgd8JcN8S4oJB3CMMMaydTUYcPc82qBb0DETRaXcPvhjsq1tSmNANqn3dkyFk3uEYgCZGgKe09-Kagfv1xEsU05tXuq1a7CnnsAWZE-qcM-4qTxfUbU6rgjGoIY9DbepaRsYFeDb0jUlnxWbOx8-M0egzVYeRBgM8F3aIBCdIWq_J9cLgxqSFo1XVnrQLv2Whv4isVzBTyjBt4REQfdTZC2bmAF6mlYD8qND52rJuv0sTOuS7PYF0ScT5Ya35_27LVvSTa5cSBuN3kq-0TA42lfGvaMTSiedj24y9qTCHu8lIgA00FpAgpSmR9Ue3WAa35KhJCsnhe3J3W-Qiit6iDTs9pSV_xOekCuYvWb5uocnZbU7NENTOpp3XaZHFCqmMrO2NCe1s1xP9AuO9AX1pn3DS4f3qNPKPRQmRdMXhfB7yUJCGT7GBXq1bYzFk1L1GE4F8cpcYcuqkKJHnZwZnaXipyYGCqMGLpN6eCEeAZC2k5Z4FxpF-m-4dxcJk1x4F3SK0PKYrbM0W0ijfCqtsIdg06zFirapeqwYdgChwLRmdEGuvtEvJkYi-5tjsU0yA2498RJQWjoxJM_ItIn98SpFDo5sK9hj9ZP0kEMtcAAf4jtoy8XL1qODj9sO4N07VAAEq0S1z3yHk5qW3fG4f6_KJVTS3IJjiRQo4CfeGYMnCZb2OdYrofr62hiOxcusstoc_pG-6jEtq9zqh0tdgzS-gjlG1X8PfW6IiDKDyzdOqdRBQx0QwDJ76hn_rkxginkV3cNkTtHNPdvM_2ERwUh_TNJuCBPfSkoZQAtT6h7zY4mWFO1UTYuuTDX9c8mBQK6veCxnLYNy2nX762DYCOS2z33E5gXGkZ2xqyjrt3lSKiPKRwkmMRo3V4wb-BIqpYQQBMEeW_ixATd_OlpBk5gPpZjYESdh3PLA0SQpPVuikeImPCo8Zeqy5wi16jkCVB_oBBdcDAQ&isca=1)

04-19 05:47:50.721: I/ActivityManager(2070): Start proc 11125:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashHandler/u0a92 for service org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService
04-19 05:47:50.724: I/Zygote(11125): seccomp disabled by setenforce 0
04-19 05:47:50.725: I/sh.CrashHandle(11125): Late-enabling -Xcheck:jni
04-19 05:47:50.732: I/Gecko(6811): Exiting due to channel error.
04-19 05:47:50.732: W/InputDispatcher(2070): channel 'a2cc2b3 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-19 05:47:50.732: E/InputDispatcher(2070): channel 'a2cc2b3 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-19 05:47:50.737: I/ActivityManager(2070): Process org.mozilla.fenix.debug (pid 6499) has died: fore FGS 
04-19 05:47:50.738: W/libprocessgroup(2070): kill(-6499, 9) failed: No such process
04-19 05:47:50.738: I/libprocessgroup(2070): Successfully killed process cgroup uid 10092 pid 6499 in 0ms
04-19 05:47:50.740: W/WindowManager(2070): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@8765f5b
04-19 05:47:50.740: I/WindowManager(2070): WIN DEATH: Window{a2cc2b3 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
04-19 05:47:50.740: W/InputDispatcher(2070): Attempted to unregister already unregistered input channel 'a2cc2b3 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)'
04-19 05:47:50.742: I/Zygote(1909): Process 6499 exited cleanly (11)
04-19 05:47:50.746: W/BinderNative(2070): Uncaught exception from death notification
04-19 05:47:50.746: W/BinderNative(2070): java.lang.NullPointerException: Attempt to read from field 'android.accessibilityservice.IAccessibilityServiceClient com.android.server.accessibility.AbstractAccessibilityServiceConnection.mServiceInterface' on a null object reference
04-19 05:47:50.746: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.destroyUiAutomationService(UiAutomationManager.java:179)
04-19 05:47:50.746: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager.access$200(UiAutomationManager.java:41)
04-19 05:47:50.746: W/BinderNative(2070): 	at com.android.server.accessibility.UiAutomationManager$UiAutomationService.binderDied(UiAutomationManager.java:230)
04-19 05:47:50.746: W/BinderNative(2070): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:1193)
04-19 05:47:50.748: W/SurfaceFlinger(1923): Attempting to destroy on removed layer: AppWindowToken{debe7a4 token=Token{5b19637 ActivityRecord{2b6736 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t4}}}#0
04-19 05:47:50.749: W/ActivityManager(2070): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
04-19 05:47:50.749: I/ActivityManager(2070): Force stopping org.mozilla.fenix.debug appid=10092 user=0: finished inst
04-19 05:47:50.749: I/ActivityManager(2070): Killing 10916:org.mozilla.fenix.debug:tab25/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-19 05:47:50.750: W/Binder(2070): Outgoing transactions from this process must be FLAG_ONEWAY
04-19 05:47:50.750: W/Binder(2070): java.lang.Throwable
04-19 05:47:50.750: W/Binder(2070): 	at android.os.BinderProxy.transact(Binder.java:1114)
04-19 05:47:50.750: W/Binder(2070): 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:164)
04-19 05:47:50.750: W/Binder(2070): 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
04-19 05:47:50.750: W/libprocessgroup(2070): kill(-10916, 9) failed: No such process
04-19 05:47:50.751: D/AndroidRuntime(6354): Shutting down VM
04-19 05:47:50.764: I/ActivityManager(2070): Killing 6811:org.mozilla.fenix.debug:tab33/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-19 05:47:50.766: I/ActivityManager(2070): Killing 11125:org.mozilla.fenix.debug:mozilla.components.lib.crash.CrashHandler/u0a92 (adj -10000): stop org.mozilla.fenix.debug
04-19 05:47:50.767: I/ActivityManager(2070): Killing 6933:org.mozilla.fenix.debug:gpu/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-19 05:47:50.768: I/ActivityManager(2070):   Force stopping service ServiceRecord{a04ad3f u0 org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
04-19 05:47:50.768: W/ActivityManager(2070): Bringing down service while still waiting for start foreground: ServiceRecord{a04ad3f u0 org.mozilla.fenix.debug/mozilla.components.lib.crash.handler.CrashHandlerService}
04-19 05:47:50.769: W/ActivityManager(2070): setHasOverlayUi called on unknown pid: 6499
04-19 05:47:50.782: I/Zygote(1909): Process 6933 exited cleanly (0)
04-19 05:47:50.791: W/libprocessgroup(2070): kill(-10916, 9) failed: No such process
04-19 05:47:50.791: I/libprocessgroup(2070): Successfully killed process cgroup uid 10092 pid 10916 in 41ms
04-19 05:47:50.791: W/libprocessgroup(2070): kill(-6811, 9) failed: No such process
04-19 05:47:50.791: I/Zygote(1909): Process 10916 exited due to signal (9)
04-19 05:47:50.801: I/Zygote(1909): Process 6811 exited cleanly (0)
04-19 05:47:50.802: I/Zygote(1909): Process 11125 exited due to signal (9)
04-19 05:47:50.831: W/libprocessgroup(2070): kill(-6811, 9) failed: No such process
04-19 05:47:50.831: I/libprocessgroup(2070): Successfully killed process cgroup uid 10092 pid 6811 in 39ms
04-19 05:47:50.831: W/libprocessgroup(2070): kill(-11125, 9) failed: No such process
04-19 05:47:50.831: I/libprocessgroup(2070): Successfully killed process cgroup uid 10092 pid 11125 in 0ms
04-19 05:47:50.831: W/libprocessgroup(2070): kill(-6933, 9) failed: No such process
04-19 05:47:50.831: I/libprocessgroup(2070): Successfully killed process cgroup uid 10092 pid 6933 in 0ms
04-19 05:47:51.046: I/ActivityManager(2070): Force stopping androidx.test.orchestrator appid=10087 user=0: finished inst
