### ISSUE TITLE
Intermittent UI test failure - TopSitesTest.verifyAddToFirefoxHome

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24462]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8213581011812053008/executions/bs.440c648fc04b56fa
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id is <org.mozilla.fenix.debug:id/top_sites_list>)
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertExistingTopSitesList(HomeScreenRobot.kt:640)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertExistingTopSitesList(HomeScreenRobot.kt:1)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyExistingTopSitesList(HomeScreenRobot.kt:135)
at org.mozilla.fenix.ui.TopSitesTest$verifyAddToFirefoxHome$5.invoke(TopSitesTest.kt:70)
at org.mozilla.fenix.ui.TopSitesTest$verifyAddToFirefoxHome$5.invoke(TopSitesTest.kt:69)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.goToHomescreen(BrowserRobot.kt:733)
at org.mozilla.fenix.ui.TopSitesTest.verifyAddToFirefoxHome(TopSitesTest.kt:69)`
### Build: 
debug 3/25

**Comment by sv-ohorvath** [comment]
same issue: https://github.com/mozilla-mobile/fenix/issues/24376

**Comment by AaronMT** [comment]
![Screen Shot 2022-03-25 at 4 10 23 PM](https://user-images.githubusercontent.com/102331/160194315-9a6ddb72-e2f4-4987-a1a1-8b723fb9584d.png)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6119952028663171131/executions/bs.ba895a8d626edc75/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 3/28 Main [Firebase link](verifyAddToFirefoxHome)
