### ISSUE TITLE
Intermittent UI test failure - < CollectionTest.swipeToRemoveTabFromCollectionTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24629]
### Stacktrace:
androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:250)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection(TabDrawerRobot.kt:269)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection$default(TabDrawerRobot.kt:263)
	at org.mozilla.fenix.ui.CollectionTest$swipeToRemoveTabFromCollectionTest$3.invoke(CollectionTest.kt:189)
	at org.mozilla.fenix.ui.CollectionTest$swipeToRemoveTabFromCollectionTest$3.invoke(CollectionTest.kt:188)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.CollectionTest.swipeToRemoveTabFromCollectionTest(CollectionTest.kt:188)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
    
### Build: 4/5 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20075)

**Comment by AndiAJ** [comment]
Flaky 1x on 4/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8317148807931007638/executions/bs.7aaab7a7f66589c6/testcases/1/test-cases)

**Comment by sv-ohorvath** [comment]
Fixed and re-enabled in https://github.com/mozilla-mobile/fenix/pull/25439
