### ISSUE TITLE
[Bug] Crash when sharing to What's App

### ISSUE THREAD

**Issue by mozillamarcia** [mozilla-mobile/fenix#2465]
## Steps to reproduce
* Launch Fenix
* Press the share button at the bottom of the page
* Press What's App in the list of apps
* Crash 

### Expected behavior
* No crash

### Actual behavior
* Crash

### Device information
* Android device: Pixel 3
* Fenix version: 1.0.1919 (Build #11310607) 
[logcatshare.txt](https://github.com/mozilla-mobile/fenix/files/3175476/logcatshare.txt)

**Comment by bifleming** [comment]
@jonalmeida checking crashes to see if this is still happening.

**Comment by jonalmeida** [comment]
```
--------- beginning of crash\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: FATAL EXCEPTION: main\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: Process: org.mozilla.fenix, PID: 27003\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void org.mozilla.geckoview.GeckoSession$Compositor.setFixedBottomOffset(int) (tried Java_org_mozilla_geckoview_GeckoSession_00024Compositor_setFixedBottomOffset and Java_org_mozilla_geckoview_GeckoSession_00024Compositor_setFixedBottomOffset__I)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession$Compositor.setFixedBottomOffset(Native Method)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoDisplay.setVerticalClipping(GeckoDisplay.java:5)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView$Display.setVerticalClipping(GeckoView.java:3)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:3)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:19)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:5)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.feature.session.EngineViewPresenter.onSessionSelected(EngineViewPresenter.kt:1)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.session.LegacySessionManager$select$$inlined$synchronized$lambda$1.invoke(LegacySessionManager.kt:2)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:5)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.session.LegacySessionManager.notifyObservers(Unknown Source:4)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.session.LegacySessionManager.select(LegacySessionManager.kt:4)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.session.LegacySessionManager.restore(LegacySessionManager.kt:13)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at mozilla.components.browser.session.SessionManager.restore(SessionManager.kt:1)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at org.mozilla.fenix.components.Core$sessionManager$2$$special$$inlined$also$lambda$1.invokeSuspend(Core.kt:10)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)\
05-05 11:52:55.677 27003 27003 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)\
```

This was a crash from adding setVerticalClipping in GV that is resolved.
