### ISSUE TITLE
Intermittent UI test failure - testStrictVisitDisableExceptionToggle

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24794]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5999639850219991053/executions/bs.609496768cd8ba09/testcases/1/test-cases
### Stacktrace:
`androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitDisableExceptionToggle(StrictEnhancedTrackingProtectionTest.kt:142)`
### Build: 
Debug 4/14

First failure found on https://github.com/mozilla-mobile/fenix/pull/24764

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
