### ISSUE TITLE
Crash in [@ java.lang.ArrayIndexOutOfBoundsException: at androidx.compose.runtime.SlotTableKt.access$updateNodeCount(SlotTable.kt:1)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#24801]
Crash report: https://crash-stats.mozilla.org/report/index/f2c778f4-83a7-44f9-8045-055280220413

Java stack trace:
```
java.lang.ArrayIndexOutOfBoundsException
	at androidx.compose.runtime.SlotTableKt.access$updateNodeCount(SlotTable.kt:1)
	at androidx.compose.runtime.SlotWriter.endGroup(SlotTable.kt:9)
	at androidx.compose.runtime.ComposerImpl.end(Composer.kt:97)
	at androidx.compose.runtime.ComposerImpl.endReplaceableGroup(Composer.kt:1)
	at androidx.compose.runtime.StaticProvidableCompositionLocal.provided$runtime_release(CompositionLocal.kt:1)
	at androidx.compose.runtime.ComposerImpl$startProviders$currentProviders$1.invoke(Composer.kt:18)
	at androidx.compose.runtime.ComposerImpl.startProviders(Composer.kt:7)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:2)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:17)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:8)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:66)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:5)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:24)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:7)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotState.kt:8)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:21)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:6)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:1)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
	at android.view.View.dispatchAttachedToWindow(View.java:13525)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1299)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5888)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
	at android.view.Choreographer.doCallbacks(Choreographer.java:611)
	at android.view.Choreographer.doFrame(Choreographer.java:581)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

https://bugzilla.mozilla.org/show_bug.cgi?id=1764803

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20175)

**Comment by Amejia481** [comment]
Similar trace on: 
https://sentry.io/organizations/mozilla/issues/3252741073/?project=6295546&sort=freq&statsPeriod=14d

```
java.lang.ArrayIndexOutOfBoundsException: length=160; index=163
    at androidx.compose.runtime.SlotTableKt.access$updateNodeCount(SlotTable.kt:1)
    at androidx.compose.runtime.SlotWriter.endGroup(SlotTable.kt:9)
    at androidx.compose.runtime.ComposerImpl.end(Composer.kt:97)
    at androidx.compose.runtime.ComposerImpl.endReplaceableGroup(Composer.kt:1)
    at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:65)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:5)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
    at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:3)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:24)
    at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:6)
    at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:8)
    at org.mozilla.fenix.addons.ExtensionsKt.observeDerivedStateRecalculations(Extensions.kt:9)
    at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:21)
    at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:10)
    at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:6)
    at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:3)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:15)
    at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:2)
    at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:1)
    at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:5)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:13)
    at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:11)
    at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:17)
    at android.view.View.dispatchAttachedToWindow(View.java:13525)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:3975)
    at android.view.ViewGroup.addView(ViewGroup.java:3786)
    at android.view.ViewGroup.addView(ViewGroup.java:3727)
    at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:6)
    at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:19)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:6)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:22)
    at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
    at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at org.mozilla.fenix.perf.HomeActivityRootLinearLayout.onLayout(HomeActivityRootLinearLayout.kt:2)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15671)
    at android.view.ViewGroup.layout(ViewGroup.java:5038)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2089)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1846)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5888)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:798)
    at android.view.Choreographer.doCallbacks(Choreographer.java:611)
    at android.view.Choreographer.doFrame(Choreographer.java:581)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:784)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5254)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by rvandermeulen** [comment]
This is showing up in the Focus 101 topcrash list as well.

**Comment by cpeterso** [comment]
We can close this GitHub issue because we're tracking it in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1764803
