### ISSUE TITLE
Intermittent UI test failure - installAddonTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24815]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5922064655051906308/executions/bs.62cb9788baaa1f11
### Stacktrace:
`androidx.test.espresso.IdlingResourceTimeoutException: Wait for [javaClass] to become idle timed out
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:106)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.assertAddonIsInstalled(SettingsSubMenuAddonsManagerRobot.kt:191)
at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonIsInstalled(SettingsSubMenuAddonsManagerRobot.kt:67)
at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:95)
at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:82)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:344)
at org.mozilla.fenix.ui.SettingsAddonsTest.installAddonTest(SettingsAddonsTest.kt:82)`
### Build: 
4/15 debug

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20182)

**Comment by sv-ohorvath** [comment]
The video shows a "Failed to install ublock origin" snackbar, maybe we should catch that.

**Comment by sv-ohorvath** [comment]
Similar failure on https://github.com/mozilla-mobile/reference-browser/issues/1710 - timed-out waiting for the confirmation dialog

**Comment by AndiAJ** [comment]
Flaky 1x on 4/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5111322198882531715/executions/bs.b8986c65682c0636/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{cd87d03} (7657088d-dd36-4521-a3b3-068acdaf241f) has not been attached yet.
at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
at android.os.Handler.dispatchMessage(Handler.java:102)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Mugurell** [comment]
Also seen in https://github.com/mozilla-mobile/fenix/pull/25051

**Comment by AndiAJ** [comment]
Flaky 1x on 5/9 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5559144539534571350/executions/bs.7e3456a9271d3c8c/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{26c6c08} (cff1a1ec-3605-4969-ae93-8619004f7cf1) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6225128909323920146/executions/bs.9a1a7b441867c7c2/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8423526193624416052/executions/bs.f8348b5dfb9071d7/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{66798cf} (bf862769-036c-47f5-a816-4930843bed08) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6028563573824745721/executions/bs.d51560d131ba2ed7/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{b14fbf8} (718d0492-0172-400b-93d3-a45006251277) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5601265167547199173/executions/bs.560a21b7f36d5839/testcases/1/test-cases)
java.lang.IllegalStateException: Fragment NavHostFragment{acbf5d7} (7fed7921-a1a1-4a42-8252-7e01c52fe250) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6706268940943461866/executions/bs.601516786064f53e/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{6ad6d53} (9fa08458-3a44-404a-879f-fea5e8e6f016) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7799698211980821407/executions/bs.a1f5eca78deae01e/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{c5a3569} (3816789a-8118-48d9-9b27-875872073851) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7174263684429934902/executions/bs.f2dc304936f2fb7b/testcases/1/test-cases)

java.lang.IllegalStateException: Fragment NavHostFragment{7c809c8} (a65bfa30-c182-495e-9dbd-89a38a6aa203) has not been attached yet.
	at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:1075)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isInstalledAddonDialogShown(AddonsInstallingIdlingResource.kt:35)
	at org.mozilla.fenix.helpers.idlingresource.AddonsInstallingIdlingResource.isIdleNow(AddonsInstallingIdlingResource.kt:24)
	at androidx.test.espresso.base.IdlingResourceRegistry.getBusyResources(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry.access$700(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeoutWarning(IdlingResourceRegistry.java:1)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:4)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:3)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by sv-ohorvath** [comment]
Same failure again, 1x on main 6/9: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6696243506005561227/executions/bs.402c1eca2d54e96f

**Comment by sv-ohorvath** [comment]
Hopefully fixed in https://github.com/mozilla-mobile/fenix/pull/25613
