### ISSUE TITLE
Intermittent UI test failure - SmokeTest.openMainMenuAddonsTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#24816]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7614964483086490746/executions/bs.1f9214697d3b82a1/testcases/1/test-cases
### Stacktrace:
`java.lang.NullPointerException: activityTestRule.activit…ewById(R.id.add_ons_list) must not be null
at org.mozilla.fenix.ui.SmokeTest$openMainMenuAddonsTest$4.invoke(SmokeTest.kt:275)
at org.mozilla.fenix.ui.SmokeTest$openMainMenuAddonsTest$4.invoke(SmokeTest.kt:272)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:344)
at org.mozilla.fenix.ui.SmokeTest.openMainMenuAddonsTest(SmokeTest.kt:272)`
### Build: 
4/15 debug

**Comment by sv-ohorvath** [comment]
Probably similar connection issues on: https://github.com/mozilla-mobile/fenix/issues/24815, timed-out waiting for the addons list to load.

**Comment by sv-ohorvath** [comment]
Hasn't failed in more than a month, closing
