### ISSUE TITLE
[Bug]: Fenix crashes when sending local file tab from a desktop to mobile device

### ISSUE THREAD

**Issue by shivrm** [mozilla-mobile/fenix#24822]
### Steps to reproduce

1. Log in to Firefox Sync on two devices - a desktop and a mobile device
2. On the desktop open a local file (such as a PDF) in Firefox
3. Use the 'Send Tab to Device' button to send the tab to the mobile device
4. Click on the notification informing you that a tab has been sent

### Expected behaviour

Fenix says the file does not exist on the mobile device.

### Actual behaviour

The app crashes unexpectedly.

### Device name

Motorola moto e⁷ power

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

99.2.0

### Device logs

```
29b2a2c7-a786-4532-8b06-2b9ebcf259d3
android.os.FileUriExposedException: file:///s:/file.pdf exposed beyond app through Intent.getData()
----
android.os.FileUriExposedException: file:///s:/file.pdf exposed beyond app through Intent.getData()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2083)
	at android.net.Uri.checkFileUriExposed(Uri.java:2388)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10791)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10744)
	at android.app.PendingIntent.getActivity(PendingIntent.java:349)
	at android.app.PendingIntent.getActivity(PendingIntent.java:311)
	at org.mozilla.fenix.components.BackgroundServices$makeAccountManager$1$3.invoke(BackgroundServices.kt:17)
	at mozilla.components.feature.accounts.push.EventsObserver.onEvents(SendTabFeature.kt:17)
	at mozilla.components.service.fxa.AccountEventsIntegration$onEvents$1.invoke(AccountStorage.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.AccountEventsIntegration.onEvents(AccountStorage.kt:2)
	at mozilla.components.service.fxa.FxaDeviceConstellation$processEvents$1.invoke(FxaDeviceConstellation.kt:3)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.service.fxa.FxaDeviceConstellation.notifyObservers(Unknown Source:7)
	at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2$1.invoke(FxaDeviceConstellation.kt:24)
	at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$7.invoke(Utils.kt:4)
	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:17)
	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:18)
	at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEvent$2.invokeSuspend(FxaDeviceConstellation.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

```

### Additional information

The desktop in this case was an Windows 10 PC running Firefox 99.0.1 (64-bit).
I haven't tested for cases where the file exists in the target device.

**Comment by kbrosnan** [comment]
This is fixed in an upcoming version of Firefox. https://github.com/mozilla-mobile/fenix/issues/20414
