### ISSUE TITLE
crash on entering credit card details

### ISSUE THREAD

**Issue by afidel1978** [mozilla-mobile/fenix#24880]
This has been happening since April 11th, both in main browser window and when using embedded engine from other Android apps. Enter CC details and hit submit and boom crash. Android 12 with April security updates,
Firefox beta 
100.0.0-beta.6 (Build #2015875331), 9666640e9+
AC: 100.0.6, 3d0dd01527
GV: 100.0-20220417185951
AS: 91.1.1

a18fcf1d-d945-450a-8657-a96e8f5fbb7c
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
 * New Sentry Instance: https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/?query=0024e6d9e89a44118561626c2a043546
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-035398c4-cd21-4ea6-ba70-6e0100220419
----
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:3)
	at org.mozilla.geckoview.Autocomplete$CreditCard.<init>(Autocomplete.java:12)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.newPrompt(PromptController.java:4)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.newPrompt(PromptController.java:8)
	at org.mozilla.geckoview.PromptController.getResponse(PromptController.java:1)
	at org.mozilla.geckoview.PromptController.handleEvent(PromptController.java:6)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:6)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by kbrosnan** [comment]
Duplicate bz-1763805
