### ISSUE TITLE
Crash in [@ java.lang.NullPointerException: at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda0.onClick(Unknown Source:9)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#24910]
Crash report: https://crash-stats.mozilla.org/report/index/a8de1b73-8e1c-4001-9158-b46530220421

Crash regression in Fenix 99.2.0

Java stack trace:
```
java.lang.NullPointerException
	at org.mozilla.fenix.utils.ToolbarPopupWindow$$ExternalSyntheticLambda0.onClick(Unknown Source:9)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29133)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by cpeterso** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1765830

**Comment by kbrosnan** [comment]
* https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.NullPointerException%3A at org.mozilla.fenix.utils.ToolbarPopupWindow%24%24ExternalSyntheticLambda0.onClick(Unknown Source%3A9)
* https://sentry.prod.mozaws.net/operations/firefox/issues/17521062/?query=is%3Aunresolved%20org.mozilla.fenix.utils.ToolbarPopupWindow
* Not showing up in Beta/Nightly on crash-stats or Sentry. Fixed?

**Comment by cpeterso** [comment]
I see a few crash reports from Nightly 100, but none from Beta 100 or Nightly 101. We can probably close this bug as fixed in 100 based on your queries.
