### ISSUE TITLE
FNX3-16363 ⁃ [Bug] regression: Fenix crashes when trying to open a custom tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#2494]
### Steps to reproduce
1. press on a link in an external app with custom tab support

### Expected behavior
Fenix opens the website as custom tab.

### Actual behavior
Fenix crashes. It's a regression from #2485. /cc @sblatz 

```
2019-05-15 00:01:35.130 17359-17359/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 17359
    java.lang.RuntimeException: Unable to stop activity {org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4737)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6950)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
     Caused by: java.lang.IllegalArgumentException: Required value was null.
        at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:687)
        at org.mozilla.fenix.browser.BrowserFragment.onStop(BrowserFragment.kt:508)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2836)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:933)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStop(FragmentManagerImpl.java:2621)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:2832)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:933)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStop(FragmentManagerImpl.java:2621)
        at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:290)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:564)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1454)
        at android.app.Activity.performStop(Activity.java:7161)
```

### Device information
* Android device: HTC U11 / Android 8.0
* Fenix version: Fenix revision 573e21557729241a19e32f364f6bb8419ccd56ce

**Comment by sblatz** [comment]
This is almost certainly due to our [ViewModel changes](https://github.com/mozilla-mobile/fenix/pull/2457).

@boek is investigating.

**Comment by bsurd** [comment]
The issue is no longer reproducible with the latest build (5/16). Custom tabs can now be used successfully, tested on a Galaxy S8, OnePlus 5T and Nexus 5.
