### ISSUE TITLE
Crash in [@ android.database.sqlite.SQLiteFullException: at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)]

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla-mobile/fenix#24947]
Crash report: https://crash-stats.mozilla.org/report/index/0eeff7df-67e9-4e5d-b605-b4d1e0220424

Superficially this crash appears like a device problem: the storage is full and sqlite is throwing out an error because of that. However there's something very suspicious going on: all crash reports come from Samsung devices. This makes me suspect that something could be different in the storage layer, how the device is partitioned or something like that, and we're accidentally filling up a specific part of the filesystem which shouldn't be holding large amounts of data.

Java stack trace:
```
android.database.sqlite.SQLiteFullException
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1096)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:800)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:449)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:420)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:272)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:649)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:255)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:222)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:1191)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:1146)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:861)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:729)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:310)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:2)
	at mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabDao_Impl$4.call(RecentlyClosedTabDao_Impl.java:4)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1.invokeSuspend(CoroutinesRoom.kt:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by kbrosnan** [comment]
Looking at crash-stats aggregations on java stacktrace raw the 44 of the 50 signatures are `SQLITE_IOERR_SHMSIZE_FULL` which reports that the device is out of storage space. This is pretty common on older Android where the application partition was small. I have a device where there is about 300 MB for user apps. With updates for core apps there is barely enough space to extract Fenix. 

The remaining are a little more generic but still suggest that the partition is full.

This does not seem actionable. If a user encounters this they would need to free up disk space by uninstalling apps.
