### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest. verifyContextOpenLinkPrivateTab >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24974]
### Stacktrace:
04-26 12:38:26.695: I/Finsky(2964): --------- beginning of crash
04-26 12:38:26.695: E/AndroidRuntime(9211): FATAL EXCEPTION: main
04-26 12:38:26.695: E/AndroidRuntime(9211): Process: org.mozilla.fenix.debug, PID: 9211
04-26 12:38:26.695: E/AndroidRuntime(9211): java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5897)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.os.Looper.loop(Looper.java:193)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-26 12:38:26.695: E/AndroidRuntime(9211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-26 12:38:26.696: E/ExceptionHandler(9211): Uncaught exception handled: 
04-26 12:38:26.696: E/ExceptionHandler(9211): java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5897)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.os.Looper.loop(Looper.java:193)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-26 12:38:26.696: E/ExceptionHandler(9211): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-26 12:38:26.697: I/Finsky(2964): [2] qlq.s(2): Installer: package org.mozilla.fenix.debug.test was removed. replacing: false
04-26 12:38:26.701: I/Finsky(2964): [2] qmo.L(12): Installer: Notifying status update. package=org.mozilla.fenix.debug.test, status=UNINSTALLED
04-26 12:38:26.708: I/Finsky(2964): [2] alxk.a(3): Do not start WearSupportService due to Wear service optimization
04-26 12:38:26.708: I/Finsky(2964): [2] alxk.a(3): Do not start WearSupportService due to Wear service optimization
04-26 12:38:26.709: E/WallpaperDownloader(9211): Unsupported URI scheme: /high/land
04-26 12:38:26.709: E/WallpaperDownloader(9211): java.lang.IllegalArgumentException: Unsupported URI scheme: /high/land
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:131)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:56)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at org.mozilla.fenix.wallpapers.WallpaperDownloader$downloadWallpaper$2.invokeSuspend(WallpaperDownloader.kt:45)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-26 12:38:26.709: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
04-26 12:38:26.710: E/WallpaperDownloader(9211): Unsupported URI scheme: /high/port
04-26 12:38:26.710: E/WallpaperDownloader(9211): java.lang.IllegalArgumentException: Unsupported URI scheme: /high/port
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:131)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:56)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at org.mozilla.fenix.wallpapers.WallpaperDownloader$downloadWallpaper$2.invokeSuspend(WallpaperDownloader.kt:45)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-26 12:38:26.710: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
04-26 12:38:26.713: E/WallpaperDownloader(9211): Unsupported URI scheme: /high/port
04-26 12:38:26.713: E/WallpaperDownloader(9211): java.lang.IllegalArgumentException: Unsupported URI scheme: /high/port
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at org.mozilla.geckoview.GeckoWebExecutor.fetch(GeckoWebExecutor.java:131)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:56)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at org.mozilla.fenix.wallpapers.WallpaperDownloader$downloadWallpaper$2.invokeSuspend(WallpaperDownloader.kt:45)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
04-26 12:38:26.713: E/WallpaperDownloader(9211): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
04-26 12:38:26.714: D/CarrierSvcBindHelper(2368): No carrier app for: 0
04-26 12:38:26.716: I/ActivityManager(2071): Force stopping org.mozilla.fenix.debug appid=10092 user=-1: deletePackageX
04-26 12:38:26.716: I/ActivityManager(2071): Killing 9211:org.mozilla.fenix.debug/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-26 12:38:26.717: W/ActivityManager(2071): Scheduling restart of crashed service org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService in 1000ms
04-26 12:38:26.717: W/libprocessgroup(2071): kill(-9211, 9) failed: No such process

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
