### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. deleteTabsDataWithNoOpenTabsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24975]
### Stacktrace:
04-26 18:15:03.296: D/AndroidRuntime(8943): --------- beginning of crash
04-26 18:15:03.298: E/AndroidRuntime(8943): FATAL EXCEPTION: main
04-26 18:15:03.298: E/AndroidRuntime(8943): Process: org.mozilla.fenix.debug:tab6, PID: 8943
04-26 18:15:03.298: E/AndroidRuntime(8943): java.lang.RuntimeException: Unable to create application org.mozilla.fenix.DebugFenixApplication: java.lang.SecurityException: Permission Denial: getIntentSender() from pid=8943, uid=10092, (need uid=-1) is not allowed to send as package org.mozilla.fenix.debug
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Looper.loop(Looper.java:193)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-26 18:15:03.298: E/AndroidRuntime(8943): Caused by: java.lang.SecurityException: Permission Denial: getIntentSender() from pid=8943, uid=10092, (need uid=-1) is not allowed to send as package org.mozilla.fenix.debug
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Parcel.createException(Parcel.java:1942)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Parcel.readException(Parcel.java:1910)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Parcel.readException(Parcel.java:1860)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.IActivityManager$Stub$Proxy.getIntentSender(IActivityManager.java:4938)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.PendingIntent.getActivity(PendingIntent.java:349)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.PendingIntent.getActivity(PendingIntent.java:309)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.components.Analytics$crashReporter$2.invoke(Analytics.kt:93)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.components.Analytics$crashReporter$2.invoke(Analytics.kt:45)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.components.Analytics.getCrashReporter(Analytics.kt:45)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.FenixApplication.setupCrashReporting(FenixApplication.kt:378)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.FenixApplication.setupInAllProcesses(FenixApplication.kt:162)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:115)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	... 8 more
04-26 18:15:03.298: E/AndroidRuntime(8943): Caused by: android.os.RemoteException: Remote stack trace:
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at com.android.server.am.ActivityManagerService.getIntentSender(ActivityManagerService.java:8350)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.IActivityManager$Stub.onTransact$getIntentSender$(IActivityManager.java:10394)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:792)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3288)
04-26 18:15:03.298: E/AndroidRuntime(8943): 	at android.os.Binder.execTransact(Binder.java:731)
04-26 18:15:03.305: I/Finsky(2937): [2] ProfileStateService.onCreate(5): creating profileStateService
04-26 18:15:03.309: I/ActivityManager(2071): Killing 8943:org.mozilla.fenix.debug:tab6/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-26 18:15:03.311: I/ActivityManager(2071): Killing 8990:org.mozilla.fenix.debug:gpu/u0a92 (adj 0): stop org.mozilla.fenix.debug
04-26 18:15:03.315: W/Looper(2071): Drained
04-26 18:15:03.319: I/Finsky(2937): [243] jmd.a(15): [ContentSync] finished, scheduled=true
04-26 18:15:03.319: W/ActivityManager(2071): Can't find mystery application for Crash from pid=8943 uid=10092: android.os.BinderProxy@5c14d9c
04-26 18:15:03.319: I/Finsky(2937): [2] ycb.d(13): PackageMonitorReceiverImpl - Received: android.intent.action.PACKAGE_FULLY_REMOVED, [Y5XVmSslptZcbABy9EBG9nkXaw44h8Sk7-R-OrPlqt4]
04-26 18:15:03.320: I/Finsky(2937): [2] ydc.g(1): Invalidating cached PackageState for org.mozilla.fenix.debug.test
04-26 18:15:03.321: I/Finsky(2937): [2] ydc.p(3): Package no longer installed: org.mozilla.fenix.debug.test
04-26 18:15:03.321: I/Finsky(2937): [242] otz.run(16): Frosting DB delete succeeded: false
04-26 18:15:03.321: I/Finsky(2937): [2] ycb.d(16): PackageMonitorReceiverImpl - Deduping intent android.intent.action.PACKAGE_FULLY_REMOVED
04-26 18:15:03.322: I/Finsky(2937): [2] jpr.a(3): Registering listener 163000904 for user UserHandle{0}.
04-26 18:15:03.322: I/Finsky(2937): [2] jpr.g(8): User UserHandle{0} finished enterprise setup, removing profile.
04-26 18:15:03.322: I/Finsky(2937): [2] abwt.b(5): SCH: Jobs in database: 1-1337 2-48879 3-5 3-6 3-7 10-78 12-1 24-77777777 26-1414141414 31-305419896 
04-26 18:15:03.336: W/libprocessgroup(2071): kill(-8893, 9) failed: No such process

### Build: 4/27 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20290)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
