### ISSUE TITLE
Intermittent UI test failure - < StrictEnhancedTrackingProtectionTest. testStrictVisitProtectionSheet >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24993]
### Stacktrace:
androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@d65c7a6, window-token=android.view.ViewRootImpl$W@d65c7a6, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034d
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034d
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertSecuritySheetIsCompletelyDisplayed(EnhancedTrackingProtectionRobot.kt:198)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertSecuritySheetIsCompletelyDisplayed(EnhancedTrackingProtectionRobot.kt:1)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot$Transition.openEnhancedTrackingProtectionSheet(EnhancedTrackingProtectionRobot.kt:78)
	at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitProtectionSheet(StrictEnhancedTrackingProtectionTest.kt:124)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8961363929250737495/executions/bs.867f496e4202c889/testcases/1/test-cases)

androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@fbddf85, window-token=android.view.ViewRootImpl$W@fbddf85, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034d
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034d
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.assertSecuritySheetIsCompletelyDisplayed(EnhancedTrackingProtectionRobot.kt:198)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobotKt.access$assertSecuritySheetIsCompletelyDisplayed(EnhancedTrackingProtectionRobot.kt:1)
	at org.mozilla.fenix.ui.robots.EnhancedTrackingProtectionRobot$Transition.openEnhancedTrackingProtectionSheet(EnhancedTrackingProtectionRobot.kt:78)
	at org.mozilla.fenix.ui.StrictEnhancedTrackingProtectionTest.testStrictVisitProtectionSheet(StrictEnhancedTrackingProtectionTest.kt:124)

**Comment by AndiAJ** [comment]
Fixed with #25143
