### ISSUE TITLE
Intermittent UI test failure - < CollectionTest. selectTabOnLongTapTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24997]
### Stacktrace:
androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:231)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:228)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.CollectionTest.selectTabOnLongTapTest(CollectionTest.kt:228)
    
### Build: 4/27 Main

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20305)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5113777915146555380/executions/bs.db4c8102b921c574/testcases/1/test-cases)

androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:231)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:228)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.CollectionTest.selectTabOnLongTapTest(CollectionTest.kt:228)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6143236903472697287/executions/bs.f28e06e1b9c0dfc3/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:231)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:228)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:718)
	at org.mozilla.fenix.ui.CollectionTest.selectTabOnLongTapTest(CollectionTest.kt:228)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5659912606256936879/executions/bs.2d36653fa890b84e/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7574897098872181062/executions/bs.ff5aaeb656631126/testcases/1/test-cases)

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.verifyTabsMultiSelectionCounter(TabDrawerRobot.kt:282)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:227)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:223)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:718)
	at org.mozilla.fenix.ui.CollectionTest.selectTabOnLongTapTest(CollectionTest.kt:223)

**Comment by AndiAJ** [comment]
Failed 1x on 5/18 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4805081705038778996/executions/bs.986a90bdb32e1c0e/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4805081705038778996/executions/bs.5cd1b61f1cb485fa/testcases/1/test-cases)

androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:226)
	at org.mozilla.fenix.ui.CollectionTest$selectTabOnLongTapTest$6.invoke(CollectionTest.kt:223)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:718)
	at org.mozilla.fenix.ui.CollectionTest.selectTabOnLongTapTest(CollectionTest.kt:223)

**Comment by AndiAJ** [comment]
Disabled in #25276
