### ISSUE TITLE
Intermittent UI test failure - < NoNetworkAccessStartupTests.testSignInPageWithNoNetworkConnection>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#24995]
### Firebase Test Run: ❗ Failed 1x on 4/27 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.9ec8e01ab78ad744/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7426066978220056767/executions/bs.60efcec79a68347a/test-cases)
### Stacktrace:
04-27 08:14:01.430: I/WindowManager(484): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 12fd224 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true)
04-27 08:14:01.515: I/ActivityManager(484): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
04-27 08:14:01.515: I/ActivityManager(484): Killing 12261:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-27 08:14:01.521: I/ServiceChildProcess(12869): Destroying GeckoServiceChildProcess
04-27 08:14:01.523: D/AndroidRuntime(12217): Shutting down VM
04-27 08:14:01.524: I/ServiceChildProcess(13000): Destroying GeckoServiceChildProcess
04-27 08:14:01.525: W/ActivityTaskManager(484): Force removing ActivityRecord{ba00947 u0 org.mozilla.fenix.debug/org.mozilla.fenix.settings.account.AuthCustomTabActivity t9 f}}: app died, no saved state
04-27 08:14:01.532: W/ActivityTaskManager(484): Force removing ActivityRecord{6a13b85 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
04-27 08:14:01.551: I/nix.debug:tab2(12869): System.exit called, status: 0
04-27 08:14:01.551: I/AndroidRuntime(12869): VM exiting with result code 0, cleanup skipped.
04-27 08:14:01.555: I/fenix.debug:gp(13000): System.exit called, status: 0
04-27 08:14:01.555: I/AndroidRuntime(13000): VM exiting with result code 0, cleanup skipped.
04-27 08:14:01.578: W/Binder(12217): Caught a RuntimeException from the binder stub implementation.
04-27 08:14:01.578: W/Binder(12217): java.lang.SecurityException: Calling from not trusted UID!
04-27 08:14:01.578: W/Binder(12217): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-27 08:14:01.578: W/Binder(12217): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-27 08:14:01.578: W/Binder(12217): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-27 08:14:01.578: W/Binder(12217): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-27 08:14:01.578: W/Binder(12217): 	at android.os.Binder.execTransact(Binder.java:1123)
04-27 08:14:01.605: I/ActivityManager(484): Killing 12869:org.mozilla.fenix.debug:tab28/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-27 08:14:01.606: I/ActivityManager(484): Killing 13000:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-27 08:14:01.608: I/ActivityManager(484): Killing 9157:com.google.android.contacts/u0a101 (adj 985): empty #17
04-27 08:14:01.609: I/WindowManager(484):   Force finishing activity ActivityRecord{6a13b85 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f} isExiting}
04-27 08:14:01.609: W/ActivityTaskManager(484): Duplicate finish request for r=ActivityRecord{6a13b85 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f} isExiting}
04-27 08:14:01.620: D/WindowManager(484): notifyANR took 225ms

### Build: 4/27 Main

Caused by #24047

**Comment by AndiAJ** [comment]
Closing in favour of #24978
