### ISSUE TITLE
Crash: IllegalStateException Too many receivers, total of 1000, registered for pid: 21899, callerPackage: org.mozilla.fenix

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#25011]
Sentry nightly https://sentry.io/organizations/mozilla/issues/3182273882/?project=6295546
```
java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 21899, callerPackage: org.mozilla.fenix
    at android.os.Parcel.createException(Parcel.java:1958)
    at android.os.Parcel.readException(Parcel.java:1918)
    at android.os.Parcel.readException(Parcel.java:1868)
    at android.app.IActivityManager$Stub$Proxy.registerReceiver(IActivityManager.java:3826)
    at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1488)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1449)
    at android.app.ContextImpl.registerReceiver(ContextImpl.java:1437)
    at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
    at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:29)
    at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:9)
    at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$invokeSuspend$$inlined$map$1$2.emit(Collect.kt:5)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
    at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6735)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by rocketsroger** [comment]
Fix https://github.com/mozilla-mobile/android-components/pull/12073

**Comment by rocketsroger** [comment]
Fix https://github.com/mozilla-mobile/android-components/pull/12113

**Comment by rocketsroger** [comment]
Number of crashes seems to be dropping.  I'll continue to monitor.

**Comment by rocketsroger** [comment]
Confirmed that looking at recent Sentry (or lack of) reports, this crash has been fixed.  Closing.
