### ISSUE TITLE
java.lang.IllegalStateException: Method setCurrentState must be called on the main thread

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/fenix#25014]
Sentry nightly : https://sentry.io/organizations/mozilla/issues/3229757609/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&statsPeriod=14d

java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
    at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:1)
    at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.java:3)
    at androidx.navigation.NavController.popBackStackInternal(NavController.java:22)
    at androidx.navigation.NavController.popBackStack(NavController.java:5)
    at androidx.navigation.NavController.popBackStack(NavController.java:4)
    at org.mozilla.fenix.library.historymetadata.controller.DefaultHistoryMetadataGroupController$deleteAll$1.invokeSuspend(HistoryMetadataGroupController.kt:29)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

**Comment by csadilek** [comment]
👍 This is caused by https://github.com/mozilla-mobile/fenix/issues/25003 so duping to this ticket. Looks like @mcarare has a PR up with a fix: https://github.com/mozilla-mobile/fenix/pull/25004
