### ISSUE TITLE
Intermittent UI test failure - < CustomTabsTest.customTabsOpenExternalLinkTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25028]
### Stacktrace:
04-28 10:15:23.912: I/WindowManager(466): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: fdce7d9 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true)
04-28 10:15:24.023: D/GeckoViewProgressDelegate[C](11959): handleEvent: MozAfterPaint
04-28 10:15:24.023: D/GeckoViewModule(11225): dispatch GeckoView:SetActive, data={"active":false}
04-28 10:15:24.024: D/GeckoViewProgressDelegate[C](11959): handleEvent: MozAfterPaint
04-28 10:15:24.031: D/GeckoViewContent(11225): onEvent: event=GeckoView:SetActive, data={"active":false}
04-28 10:15:24.074: D/GeckoViewModule(11225): dispatch GeckoView:FlushSessionState, data=null
04-28 10:15:24.084: D/GeckoViewProgress(11225): onEvent: event=GeckoView:FlushSessionState, data=null
04-28 10:15:24.085: D/GeckoViewProgress(11225): receiveMessage: MozAfterPaint
04-28 10:15:24.085: D/GeckoViewProgress(11225): receiveMessage: MozAfterPaint
04-28 10:15:24.087: D/GeckoViewSessionStateAggregator[C](11959): receiveMessage: GeckoView:FlushSessionState
04-28 10:15:24.138: I/Choreographer(11225): Skipped 315 frames!  The application may be doing too much work on its main thread.
04-28 10:15:24.139: D/GeckoSession(11225): handleMessage GeckoView:StateUpdated uri=null
04-28 10:15:24.186: E/MmTelFeatureConnection [0](1791): ImsRegistrationCallbackAdapter: ImsRegistration is null
04-28 10:15:24.247: I/ActivityManager(466): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
04-28 10:15:24.247: I/ActivityManager(466): Killing 11225:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-28 10:15:24.248: W/Binder(11174): Caught a RuntimeException from the binder stub implementation.
04-28 10:15:24.248: W/Binder(11174): java.lang.SecurityException: Calling from not trusted UID!
04-28 10:15:24.248: W/Binder(11174): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-28 10:15:24.248: W/Binder(11174): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-28 10:15:24.248: W/Binder(11174): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-28 10:15:24.248: W/Binder(11174): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-28 10:15:24.248: W/Binder(11174): 	at android.os.Binder.execTransact(Binder.java:1123)
04-28 10:15:24.249: W/ActivityTaskManager(466): Force removing ActivityRecord{893b3b9 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
04-28 10:15:24.252: I/ServiceChildProcess(11959): Destroying GeckoServiceChildProcess
04-28 10:15:24.252: W/ActivityTaskManager(466): Force removing ActivityRecord{23bbfe4 u0 org.mozilla.fenix.debug/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity t10 f}}: app died, no saved state
04-28 10:15:24.258: I/ServiceChildProcess(12103): Destroying GeckoServiceChildProcess
04-28 10:15:24.276: I/BackdropActivity(10446): onResume()
04-28 10:15:24.280: I/ActivityManager(466): Killing 11959:org.mozilla.fenix.debug:tab19/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-28 10:15:24.283: I/ActivityTaskManager(466): Activity requesting to dismiss Keyguard: ActivityRecord{5394d41 u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
04-28 10:15:24.285: I/ActivityManager(466): Killing 12103:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-28 10:15:24.290: D/WindowManager(466): notifyANR took 401ms

### Notes
❗ Similar with #24047

**Comment by sv-ohorvath** [comment]
Now flaky with the following error:
`java.lang.ExceptionInInitializerError
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.getMDevice(HomeScreenRobot.kt:438)
at org.mozilla.fenix.ui.robots.CustomTabRobotKt.<clinit>(CustomTabRobot.kt:179)
at org.mozilla.fenix.ui.robots.CustomTabRobotKt.customTabScreen(Unknown Source:0)
at org.mozilla.fenix.ui.CustomTabsTest.customTabsOpenExternalLinkTest(CustomTabsTest.kt:69)
... 34 trimmed
Caused by: java.lang.IllegalStateException: UiAutomation not connected, UiAutomation@9e3a4ea[id=-1, flags=0]
at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1239)
at android.app.UiAutomation.getServiceInfo(UiAutomation.java:497)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.<clinit>(HomeScreenRobot.kt:438)`
same as https://github.com/mozilla-mobile/fenix/issues/25132
