### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. redirectToAppPermissionsSystemSettingsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25034]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5525004325908631939/executions/bs.21ffb32e29f93531/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5525004325908631939/executions/bs.69494aecd8a0f29c/testcases/1/test-cases)

### Stacktrace:
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: ancestor <android.widget.LinearLayout{c581529 G.E..V... ......I. 0,0-0,0 #7f0a03ea app:id/permissions_blocked_container}>'s getVisibility() was <GONE>
View Details: AppCompatTextView{id=-1, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ea9b0ae, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Blocked by Android, input-type=0, ime-target=false, has-links=false}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSitePermissionsCommonRobotKt.assertBlockedByAndroid(SettingsSubMenuSitePermissionsCommonRobot.kt:167)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSitePermissionsCommonRobotKt.access$assertBlockedByAndroid(SettingsSubMenuSitePermissionsCommonRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSitePermissionsCommonRobot.verifyBlockedByAndroid(SettingsSubMenuSitePermissionsCommonRobot.kt:46)
	at org.mozilla.fenix.ui.SmokeTest$redirectToAppPermissionsSystemSettingsTest$5.invoke(SmokeTest.kt:545)
	at org.mozilla.fenix.ui.SmokeTest$redirectToAppPermissionsSystemSettingsTest$5.invoke(SmokeTest.kt:544)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSitePermissionsRobot$Transition.openCamera(SettingsSubMenuSitePermissionsRobot.kt:69)
	at org.mozilla.fenix.ui.SmokeTest.redirectToAppPermissionsSystemSettingsTest(SmokeTest.kt:544)
	... 45 trimmed
Caused by: junit.framework.AssertionFailedError: 'view has effective visibility <VISIBLE>' doesn't match the selected view.
Expected: view has effective visibility <VISIBLE>
     Got: ancestor <android.widget.LinearLayout{c581529 G.E..V... ......I. 0,0-0,0 #7f0a03ea app:id/permissions_blocked_container}>'s getVisibility() was <GONE>
View Details: AppCompatTextView{id=-1, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@ea9b0ae, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Blocked by Android, input-type=0, ime-target=false, has-links=false}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:12)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
### Build: 4/29 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20327)

**Comment by AndiAJ** [comment]
Disabled in #25035

**Comment by AndiAJ** [comment]
Fixed with #25803
