### ISSUE TITLE
Intermittent UI test failure - < TabbedBrowsingTest. verifyContextMenuShortcuts >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25056]
### Stacktrace: 
04-29 18:10:27.703: I/WindowManager(482): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: de83af0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (915.0, 1711.0)]), policyFlags=0x6b000000
04-29 18:10:27.845: I/ActivityManager(482): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
04-29 18:10:27.846: W/Binder(11961): Caught a RuntimeException from the binder stub implementation.
04-29 18:10:27.846: W/Binder(11961): java.lang.SecurityException: Calling from not trusted UID!
04-29 18:10:27.846: W/Binder(11961): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
04-29 18:10:27.846: W/Binder(11961): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
04-29 18:10:27.846: W/Binder(11961): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
04-29 18:10:27.846: W/Binder(11961): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
04-29 18:10:27.846: W/Binder(11961): 	at android.os.Binder.execTransact(Binder.java:1123)
04-29 18:10:27.846: I/ActivityManager(482): Killing 12003:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:27.850: W/ActivityTaskManager(482): Force removing ActivityRecord{610a26e u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
04-29 18:10:27.855: D/AndroidRuntime(11961): Shutting down VM
04-29 18:10:27.855: I/ServiceChildProcess(12831): Destroying GeckoServiceChildProcess
04-29 18:10:27.856: E/JavaBinder(11961): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
04-29 18:10:27.856: E/JavaBinder(11961): java.lang.RuntimeException: Bad file descriptor
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.os.BinderProxy.transactNative(Native Method)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
04-29 18:10:27.856: E/JavaBinder(11961): 	at android.os.Binder.execTransact(Binder.java:1123)
04-29 18:10:27.903: I/ServiceChildProcess(12689): Destroying GeckoServiceChildProcess
04-29 18:10:27.908: I/ActivityManager(482): Killing 12689:org.mozilla.fenix.debug:tab12/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:27.921: I/ActivityManager(482): Killing 12831:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
04-29 18:10:27.926: D/WindowManager(482): notifyANR took 223ms
### Notes: Similar with https://github.com/mozilla-mobile/fenix/issues/24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20339)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8599499133086905800/executions/bs.cf5b696998507043/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5063369851374032949/executions/bs.e12883d1ce2e612/test-cases)

06-14 18:08:27.090: I/WindowManager(478): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 52d3c34 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (915.0, 1711.0)]), policyFlags=0x6b000000
06-14 18:08:27.229: I/ActivityManager(478): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-14 18:08:27.229: I/ActivityManager(478): Killing 12979:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-14 18:08:27.231: W/ActivityTaskManager(478): Force removing ActivityRecord{3f19dac u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-14 18:08:27.234: W/Binder(12943): Caught a RuntimeException from the binder stub implementation.
06-14 18:08:27.234: W/Binder(12943): java.lang.SecurityException: Calling from not trusted UID!
06-14 18:08:27.234: W/Binder(12943): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-14 18:08:27.234: W/Binder(12943): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-14 18:08:27.234: W/Binder(12943): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-14 18:08:27.234: W/Binder(12943): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-14 18:08:27.234: W/Binder(12943): 	at android.os.Binder.execTransact(Binder.java:1123)
06-14 18:08:27.234: I/ServiceChildProcess(13567): Destroying GeckoServiceChildProcess
06-14 18:08:27.242: D/AndroidRuntime(12943): Shutting down VM
06-14 18:08:27.263: I/BackdropActivity(12164): onResume()
06-14 18:08:27.264: I/ActivityTaskManager(478): Activity requesting to dismiss Keyguard: ActivityRecord{6c9e8cb u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
06-14 18:08:27.264: I/ActivityManager(478): Killing 13567:org.mozilla.fenix.debug:tab22/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-14 18:08:27.271: I/ActivityManager(478): Killing 13746:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-14 18:08:27.274: D/WindowManager(478): notifyANR took 186ms

**Comment by AndiAJ** [comment]
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6547038931035715046/executions/bs.60a109aaedf86fd3/test-cases)

06-28 16:43:31.655: I/WindowManager(476): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 1508c21 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (915.0, 1711.0)]), policyFlags=0x6b000000
06-28 16:43:31.787: I/ActivityManager(476): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-28 16:43:31.788: I/ActivityManager(476): Killing 11138:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-28 16:43:31.790: W/ActivityTaskManager(476): Force removing ActivityRecord{884f3b1 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-28 16:43:31.792: D/AndroidRuntime(11073): Shutting down VM
06-28 16:43:31.795: I/ServiceChildProcess(11903): Destroying GeckoServiceChildProcess
06-28 16:43:31.800: I/ServiceChildProcess(13842): Destroying GeckoServiceChildProcess
06-28 16:43:31.801: I/ServiceChildProcess(11709): Destroying GeckoServiceChildProcess
06-28 16:43:31.850: I/nix.debug:tab2(13842): System.exit called, status: 0
06-28 16:43:31.850: I/AndroidRuntime(13842): VM exiting with result code 0, cleanup skipped.
06-28 16:43:31.869: I/nix.debug:tab2(11709): System.exit called, status: 0
06-28 16:43:31.869: I/AndroidRuntime(11709): VM exiting with result code 0, cleanup skipped.
06-28 16:43:31.871: I/fenix.debug:gp(11903): System.exit called, status: 0
06-28 16:43:31.872: I/AndroidRuntime(11903): VM exiting with result code 0, cleanup skipped.
06-28 16:43:31.928: E/JavaBinder(11073): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
06-28 16:43:31.928: E/JavaBinder(11073): java.lang.RuntimeException: Bad file descriptor
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.os.BinderProxy.transactNative(Native Method)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
06-28 16:43:31.928: E/JavaBinder(11073): 	at android.os.Binder.execTransact(Binder.java:1123)
06-28 16:43:31.996: I/Zygote(290): Process 11903 exited cleanly (0)
06-28 16:43:32.001: E/MmTelFeatureConnection [0](1783): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-28 16:43:32.026: I/Zygote(290): Process 11709 exited cleanly (0)
06-28 16:43:32.029: I/Zygote(290): Process 13842 exited cleanly (0)
06-28 16:43:32.165: I/binder(0): release 11138:11824 transaction 774087 out, still active
06-28 16:43:32.166: I/binder(0): undelivered TRANSACTION_COMPLETE
06-28 16:43:32.167: I/binder(0): undelivered transaction 775705, process died.
06-28 16:43:32.168: I/binder(0): undelivered transaction 775706, process died.
06-28 16:43:32.170: I/binder(0): undelivered transaction 775817, process died.
06-28 16:43:32.131: I/Zygote(290): Process 11138 exited due to signal 9 (Killed)
06-28 16:43:32.185: I/binder(0): undelivered transaction 775700, process died.
06-28 16:43:32.186: I/binder(0): undelivered transaction 775701, process died.
06-28 16:43:32.187: I/binder(0): undelivered transaction 775732, process died.
06-28 16:43:32.167: I/libprocessgroup(476): Successfully killed process cgroup uid 10152 pid 11138 in 374ms
06-28 16:43:32.123: I/RenderThread(476): type=1400 audit(0.0:172): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=1 b/65201432
06-28 16:43:32.403: E/FrameEvents(476): updateAcquireFence: Did not find frame.
06-28 16:43:32.412: I/ActivityManager(476): Killing 13842:org.mozilla.fenix.debug:tab23/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-28 16:43:32.412: W/system_server(476): Long monitor contention with owner InputDispatcher (1484) at void com.android.server.wm.ActivityTaskManagerService$LocalService.onProcessUnMapped(int)(ActivityTaskManagerService.java:6519) waiters=3 in void com.android.server.wm.WindowState$DeathRecipient.binderDied() for 288ms
06-28 16:43:32.412: I/WindowManager(476): WIN DEATH: Window{1508c21 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
06-28 16:43:32.413: I/libprocessgroup(476): Successfully killed process cgroup uid 10152 pid 13842 in 0ms
06-28 16:43:32.420: W/system_server(476): Long monitor contention with owner InputDispatcher (1484) at void com.android.server.wm.ActivityTaskManagerService$LocalService.onProcessUnMapped(int)(ActivityTaskManagerService.java:6519) waiters=4 in void com.android.server.wm.Session.binderDied() for 282ms
06-28 16:43:32.420: W/system_server(476): Long monitor contention with owner InputDispatcher (1484) at void com.android.server.wm.ActivityTaskManagerService$LocalService.onProcessUnMapped(int)(ActivityTaskManagerService.java:6519) waiters=0 in void com.android.server.wm.InputMonitor$UpdateInputWindows.run() for 595ms
06-28 16:43:32.421: I/Choreographer(476): Skipped 35 frames!  The application may be doing too much work on its main thread.
06-28 16:43:32.423: W/system_server(476): Long monitor contention with owner InputDispatcher (1484) at void com.android.server.wm.ActivityTaskManagerService$LocalService.onProcessUnMapped(int)(ActivityTaskManagerService.java:6519) waiters=1 in void com.android.server.wm.WindowManagerService$LocalService.setAccessibilityIdToSurfaceMetadata(android.os.IBinder, int) for 301ms
06-28 16:43:32.423: W/WindowManager(476): Cannot find window which accessibility connection is added to
06-28 16:43:32.424: I/BackdropActivity(10179): onResume()
06-28 16:43:32.425: W/WindowManager(476): Failed looking up window session=Session{5310f14 11138:u0a10152} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5425 com.android.server.wm.WindowState$DeathRecipient.binderDied:2809 android.os.IBinder$DeathRecipient.binderDied:305 
06-28 16:43:32.425: I/WindowManager(476): WIN DEATH: null
06-28 16:43:32.425: I/ActivityManager(476): Killing 11709:org.mozilla.fenix.debug:tab26/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-28 16:43:32.425: I/libprocessgroup(476): Successfully killed process cgroup uid 10152 pid 11709 in 0ms
06-28 16:43:32.426: I/ActivityManager(476): Killing 11903:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-28 16:43:32.434: W/system_server(476): Long monitor contention with owner Binder:476_18 (2827) at void com.android.server.accessibility.AccessibilityWindowManager$RemoteAccessibilityConnection.binderDied()(AccessibilityWindowManager.java:830) waiters=0 in void com.android.server.accessibility.AccessibilityWindowManager$RemoteAccessibilityConnection.binderDied() for 310ms
06-28 16:43:32.436: D/WindowManager(476): notifyANR took 788ms

**Comment by AndiAJ** [comment]
Closing in favour of #25926
