### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest. verifyContextOpenImageNewTab >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25054]
### Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6130204499935979422/executions/bs.e2f84e6a84f4e35d/testcases/1/test-cases)
Provide a Firebase test run report link here showcasing the problem
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@adcbde2[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.ContextMenusTest.<init>(ContextMenusTest.kt:40)
    
### Notes 
Similar with #25076 and #25075

**Comment by AndiAJ** [comment]
#25133 landed yesterday.
We'll keep an eye on it, closing for now.
