### ISSUE TITLE
Intermittent UI test failure - < CollectionTest. renameCollectionTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25059]
### Stacktrace:
androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection(TabDrawerRobot.kt:272)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection$default(TabDrawerRobot.kt:266)
	at org.mozilla.fenix.ui.CollectionTest$renameCollectionTest$3.invoke(CollectionTest.kt:124)
	at org.mozilla.fenix.ui.CollectionTest$renameCollectionTest$3.invoke(CollectionTest.kt:123)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.CollectionTest.renameCollectionTest(CollectionTest.kt:123)
    
### Build: 5/2 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20343)

**Comment by AaronMT** [comment]
Flaky 1x [Firebase](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8541816937527319761/details?stepId=bs.98f3bff0b28abfa3&testCaseId=1&tabId=logs)

**Comment by AndiAJ** [comment]
Flaky 1 x on 5/9 Main [Firebase link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7359284100500311315/executions/bs.99d7e40b9669e706/testcases/1/test-cases)

androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection(TabDrawerRobot.kt:272)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection$default(TabDrawerRobot.kt:266)
	at org.mozilla.fenix.ui.CollectionTest$renameCollectionTest$3.invoke(CollectionTest.kt:124)
	at org.mozilla.fenix.ui.CollectionTest$renameCollectionTest$3.invoke(CollectionTest.kt:123)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:699)
	at org.mozilla.fenix.ui.CollectionTest.renameCollectionTest(CollectionTest.kt:123)

**Comment by sv-ohorvath** [comment]
Fixed and re-enabled in https://github.com/mozilla-mobile/fenix/pull/25439
