### ISSUE TITLE
Intermittent UI test failure - < PwaTest. telephoneLinkPWATest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25077]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=Telephone link]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:318)
	at org.mozilla.fenix.ui.PwaTest$telephoneLinkPWATest$5.invoke(PwaTest.kt:82)
	at org.mozilla.fenix.ui.PwaTest$telephoneLinkPWATest$5.invoke(PwaTest.kt:81)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:73)
	at org.mozilla.fenix.ui.PwaTest.telephoneLinkPWATest(PwaTest.kt:81)
    
### Build: 5/3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20352)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8277032657026226760/executions/bs.720da0cd31737c12/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Install]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.clickInstall(ThreeDotMenuMainRobot.kt:324)
	at org.mozilla.fenix.ui.PwaTest.telephoneLinkPWATest(PwaTest.kt:81)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4943242860213616898/executions/bs.fa960353818af79b/testcases/1/test-cases)

androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:194)
	at androidx.test.espresso.intent.Intents.intended(Intents.java:173)
	at org.mozilla.fenix.helpers.TestHelper.assertNativeAppOpens(TestHelper.kt:232)
	at org.mozilla.fenix.ui.PwaTest$telephoneLinkPWATest$5.invoke(PwaTest.kt:85)
	at org.mozilla.fenix.ui.PwaTest$telephoneLinkPWATest$5.invoke(PwaTest.kt:83)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:81)
	at org.mozilla.fenix.ui.PwaTest.telephoneLinkPWATest(PwaTest.kt:83)

**Comment by AndiAJ** [comment]
Fixed with #25512
