### ISSUE TITLE
Intermittent UI test failure - < CrashReportingTest. privateBrowsingUseAppWhileTabIsCrashedTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25076]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@d48b450[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.helpers.HomeActivityTestRuleKt.setLongTapTimeout(HomeActivityTestRule.kt:78)
	at org.mozilla.fenix.helpers.HomeActivityIntentTestRule.beforeActivityLaunched(HomeActivityTestRule.kt:65)
	at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:373)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:547)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:337)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$TextInputServiceStatement.evaluate(AndroidComposeTestRule.android.kt:417)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$ComposeIdlingResourceStatement.evaluate(AndroidComposeTestRule.android.kt:402)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$RecomposerStatement.evaluateWithWindowRecomposer(AndroidComposeTestRule.android.kt:374)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$RecomposerStatement.evaluate(AndroidComposeTestRule.android.kt:364)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$CleanupCoroutinesStatement.evaluate(AndroidComposeTestRule.android.kt:388)
	at androidx.compose.ui.test.junit4.EspressoLink$getStatementFor$1.evaluate(EspressoLink.android.kt:69)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:149)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
    
### Notes
Similar with #25054 and #25075

**Comment by AndiAJ** [comment]
#25133 landed yesterday.
We'll keep an eye on it, closing for now.
