### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. verifyExpandedCollectionItemsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25075]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@dac7cb6[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.SmokeTest.<init>(SmokeTest.kt:66)
    
### Notes
Similar with #25054 and #25076

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20350)

**Comment by AndiAJ** [comment]
#25133 landed yesterday.
We'll keep an eye on it, closing for now.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6547038931035715046/executions/bs.d98bf9437e177010/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@cfacd19[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.CollectionTest.<init>(CollectionTest.kt:32)
