### ISSUE TITLE
[Bug]: Firefox Beta for Android crashes when using payment processors

### ISSUE THREAD

**Issue by lif9er** [mozilla-mobile/fenix#25120]
### Steps to reproduce

1. Attempt to purchase something (previous instances: buying a movie ticket through Veezi and paying a parking ticket on njcourts.gov)

### Expected behaviour

You should be able to proceed through the checkout process.

### Actual behaviour

If it's a website where it occurs, Firefox Beta for Android crashes every time. Persists through reboot.

### Device name

Google Pixel 3XL

### Android version

Android 12

### Firefox release type

Firefox Beta

### Firefox version

100.0.0-beta.7

### Device logs

f178fa3a-b466-49c8-9825-a3945f8b7a04
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
----
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.mozilla.gecko.util.GeckoBundle.getString(GeckoBundle.java:3)
	at org.mozilla.geckoview.Autocomplete$CreditCard.<init>(Autocomplete.java:12)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.newPrompt(PromptController.java:4)
	at org.mozilla.geckoview.PromptController$CreditCardSaveHandler.newPrompt(PromptController.java:8)
	at org.mozilla.geckoview.PromptController.getResponse(PromptController.java:1)
	at org.mozilla.geckoview.PromptController.handleEvent(PromptController.java:6)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:6)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by gabrielluong** [comment]
Hi @lif9er, This should be fixed in Beta 100.0rc1. See https://bugzilla.mozilla.org/show_bug.cgi?id=1763805. I believe the reason you are hitting this is because the fix is approved for a later version than 100-beta.7. So, maybe give it a couple of days for the update to roll out to unless you can manually update beta. I see from https://github.com/mozilla-mobile/fenix/releases/tag/v100.1.1 that 100.1.1 is out, but I am unsure how rapidly it gets rolled to everybody. I would imagine the fix would be in there.
