### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. mainMenuInstallPWATest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25124]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.SmokeTest.mainMenuInstallPWATest(SmokeTest.kt:952)
    
### Build: 5/4 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20384)

**Comment by AndiAJ** [comment]
Similar with #25125

**Comment by AndiAJ** [comment]
Ran it 100x on Firebase and passed in all cases, I'll go ahead and close it.
