### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTypesTest. downloadMultipleFileTypesTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25125]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8961363929250737495/executions/bs.1d5e4983eba059f/testcases/6/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8961363929250737495/executions/bs.1d5e4983eba059f/testcases/8/test-cases)
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7066995971673540368/executions/bs.9920a58c2ff47bfd/testcases/2/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5642381861846779718/executions/bs.303de22953e7bb14/testcases/3/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)

**Comment by AndiAJ** [comment]
Similar with https://github.com/mozilla-mobile/fenix/issues/25124

**Comment by AndiAJ** [comment]
Flaky 1x on 5/16 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5659912606256936879/executions/bs.6d5b192f5311ef5e/testcases/5/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8599150317556569257/executions/bs.83b53ed6e13d4e1c/testcases/3/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8423526193624416052/executions/bs.be93e5788d41fa07/testcases/3/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)

**Comment by sv-ohorvath** [comment]
Also flaky on 5/26: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6757722942743332020/details?stepId=bs.bf0c2e2a73c17e3c&testCaseId=3

**Comment by AndiAJ** [comment]
Flaky 1x on 5/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7551035073070944308/executions/bs.4da2ff8c3749b3f9/testcases/7/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73)
