### ISSUE TITLE
Intermittent UI test failure - < CollectionTest.undoDeleteCollectionTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25203]
### Stacktrace:
androidx.test.uiautomator.StaleObjectException
	at androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:647)
	at androidx.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:213)
	at androidx.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:264)
	at androidx.test.uiautomator.UiObject2.click(UiObject2.java:356)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.selectTab(TabDrawerRobot.kt:253)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection(TabDrawerRobot.kt:272)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.createCollection$default(TabDrawerRobot.kt:266)
	at org.mozilla.fenix.ui.CollectionTest$undoDeleteCollectionTest$3.invoke(CollectionTest.kt:287)
	at org.mozilla.fenix.ui.CollectionTest$undoDeleteCollectionTest$3.invoke(CollectionTest.kt:286)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:718)
	at org.mozilla.fenix.ui.CollectionTest.undoDeleteCollectionTest(CollectionTest.kt:286)
    
### Build: 5/10 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20438)

**Comment by sv-ohorvath** [comment]
Fixed and re-enabled in https://github.com/mozilla-mobile/fenix/pull/25439
