### ISSUE TITLE
Intermittent UI test failure - < SearchTest.noCurrentSearchGroupFromPrivateBrowsingTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25275]
### Stacktrace:
05-17 09:19:24.600: I/WindowManager(463): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 5f5ad73 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5004ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (80.0, 218.0)]), policyFlags=0x6b000000
05-17 09:19:24.664: W/FenixPerf(12361): StrictMode violation suppressed: #50
05-17 09:19:24.718: D/ThumbnailStorage(12361): Saved thumbnail to disk (id = 34c2b3b1-5d63-4be6-b68b-2347b5f0d0c8, generationId = 110)
05-17 09:19:24.883: I/ActivityManager(463): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
05-17 09:19:24.883: I/ActivityManager(463): Killing 12361:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-17 09:19:24.883: W/Binder(12307): Caught a RuntimeException from the binder stub implementation.
05-17 09:19:24.883: W/Binder(12307): java.lang.SecurityException: Calling from not trusted UID!
05-17 09:19:24.883: W/Binder(12307): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-17 09:19:24.883: W/Binder(12307): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-17 09:19:24.883: W/Binder(12307): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-17 09:19:24.883: W/Binder(12307): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-17 09:19:24.883: W/Binder(12307): 	at android.os.Binder.execTransact(Binder.java:1123)
05-17 09:19:24.886: I/ServiceChildProcess(12984): Destroying GeckoServiceChildProcess
05-17 09:19:24.888: I/ServiceChildProcess(13184): Destroying GeckoServiceChildProcess
05-17 09:19:24.890: W/ActivityTaskManager(463): Force removing ActivityRecord{40bb855 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-17 09:19:24.960: D/AndroidRuntime(12307): Shutting down VM
05-17 09:19:24.963: E/JavaBinder(12307): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
05-17 09:19:24.963: E/JavaBinder(12307): java.lang.RuntimeException: Bad file descriptor
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.os.BinderProxy.transactNative(Native Method)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
05-17 09:19:24.963: E/JavaBinder(12307): 	at android.os.Binder.execTransact(Binder.java:1123)
05-17 09:19:24.975: I/fenix.debug:gp(13184): System.exit called, status: 0
05-17 09:19:24.975: I/AndroidRuntime(13184): VM exiting with result code 0, cleanup skipped.
05-17 09:19:24.989: I/enix.debug:tab(12984): System.exit called, status: 0
05-17 09:19:24.989: I/AndroidRuntime(12984): VM exiting with result code 0, cleanup skipped.
05-17 09:19:24.991: I/ActivityManager(463): Killing 12984:org.mozilla.fenix.debug:tab4/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-17 09:19:25.014: I/ActivityManager(463): Killing 13184:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-17 09:19:25.015: I/BackdropActivity(11499): onResume()
05-17 09:19:25.018: D/WindowManager(463): notifyANR took 486ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20499)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5776357103126378758/executions/bs.583118f1d411321d/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
