### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.updateSavedLoginTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25294]
### Stacktrace:
05-18 10:51:41.805: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 4844ccd org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false)
05-18 10:51:42.002: I/OpenGLRenderer(12036): Davey! duration=7489ms; Flags=1, IntendedVsync=790807397415, Vsync=793074063991, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=793087053215, AnimationStart=793087055024, PerformTraversalsStart=793087531890, DrawStart=794945689082, SyncQueued=794978954671, SyncStart=794979166796, IssueDrawCommandsStart=794989304101, SwapBuffers=798193013467, FrameCompleted=798297154823, DequeueBufferDuration=816370, QueueBufferDuration=387815, GpuCompleted=72057628414510440, 
05-18 10:51:42.195: I/ActivityManager(479): Force stopping org.mozilla.fenix.debug appid=10151 user=0: finished inst
05-18 10:51:42.195: I/ActivityManager(479): Killing 12036:org.mozilla.fenix.debug/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-18 10:51:42.199: W/Binder(11978): Caught a RuntimeException from the binder stub implementation.
05-18 10:51:42.199: W/Binder(11978): java.lang.SecurityException: Calling from not trusted UID!
05-18 10:51:42.199: W/Binder(11978): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-18 10:51:42.199: W/Binder(11978): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-18 10:51:42.199: W/Binder(11978): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-18 10:51:42.199: W/Binder(11978): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-18 10:51:42.199: W/Binder(11978): 	at android.os.Binder.execTransact(Binder.java:1123)
05-18 10:51:42.201: W/ActivityTaskManager(479): Force removing ActivityRecord{b7c9a7b u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-18 10:51:42.202: I/ServiceChildProcess(15152): Destroying GeckoServiceChildProcess
05-18 10:51:42.206: D/AndroidRuntime(11978): Shutting down VM
05-18 10:51:42.207: I/ServiceChildProcess(12944): Destroying GeckoServiceChildProcess
05-18 10:51:42.235: I/ServiceChildProcess(13144): Destroying GeckoServiceChildProcess
05-18 10:51:42.252: I/nix.debug:tab2(15152): System.exit called, status: 0
05-18 10:51:42.252: I/AndroidRuntime(15152): VM exiting with result code 0, cleanup skipped.
05-18 10:51:42.253: I/nix.debug:tab3(12944): System.exit called, status: 0
05-18 10:51:42.253: I/AndroidRuntime(12944): VM exiting with result code 0, cleanup skipped.
05-18 10:51:42.358: I/fenix.debug:gp(13144): System.exit called, status: 0
05-18 10:51:42.358: I/AndroidRuntime(13144): VM exiting with result code 0, cleanup skipped.
05-18 10:51:42.360: I/ActivityManager(479): Killing 15152:org.mozilla.fenix.debug:tab26/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-18 10:51:42.361: I/ActivityManager(479): Killing 12944:org.mozilla.fenix.debug:tab30/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-18 10:51:42.365: I/ActivityManager(479): Killing 13144:org.mozilla.fenix.debug:gpu/u0a151 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-18 10:51:42.369: W/Looper(479): Slow dispatch took 170ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=31
05-18 10:51:42.377: D/WindowManager(479): notifyANR took 575ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20508)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7056756895064680931/executions/bs.d45245fd278f4b60/test-cases)

06-29 17:36:02.523: I/WindowManager(476): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 923884e org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5001ms for FocusEvent(hasFocus=false)
06-29 17:36:02.654: I/OpenGLRenderer(10533): Davey! duration=7419ms; Flags=1, IntendedVsync=572417568643, Vsync=574650901887, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=574656999037, AnimationStart=574657003612, PerformTraversalsStart=574658164205, DrawStart=579326998418, SyncQueued=579329114879, SyncStart=579372949057, IssueDrawCommandsStart=579373047807, SwapBuffers=579706821636, FrameCompleted=579880948130, DequeueBufferDuration=138629, QueueBufferDuration=320878, GpuCompleted=0, 
06-29 17:36:02.817: D/GeckoSession(10533): handleMessage GeckoView:StateUpdated uri=null
06-29 17:36:02.907: W/system_server(476): Long monitor contention with owner InputDispatcher (1492) at void com.android.server.wm.ActivityTaskManagerService$LocalService.saveANRState(java.lang.String)(ActivityTaskManagerService.java:6971) waiters=0 in void com.android.server.wm.WindowAnimator.lambda$new$1$WindowAnimator(long) for 114ms
06-29 17:36:02.933: I/ActivityManager(476): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-29 17:36:02.933: I/ActivityManager(476): Killing 10533:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-29 17:36:02.950: W/Binder(10482): Caught a RuntimeException from the binder stub implementation.
06-29 17:36:02.950: W/Binder(10482): java.lang.SecurityException: Calling from not trusted UID!
06-29 17:36:02.950: W/Binder(10482): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-29 17:36:02.950: W/Binder(10482): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-29 17:36:02.950: W/Binder(10482): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-29 17:36:02.950: W/Binder(10482): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-29 17:36:02.950: W/Binder(10482): 	at android.os.Binder.execTransact(Binder.java:1123)
06-29 17:36:02.958: W/ActivityTaskManager(476): Force removing ActivityRecord{7e64bbd u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-29 17:36:02.959: I/ServiceChildProcess(13357): Destroying GeckoServiceChildProcess
06-29 17:36:02.962: I/ServiceChildProcess(11376): Destroying GeckoServiceChildProcess
06-29 17:36:02.977: I/fenix.debug:gp(11376): System.exit called, status: 0
06-29 17:36:02.977: I/AndroidRuntime(11376): VM exiting with result code 0, cleanup skipped.
06-29 17:36:02.978: I/nix.debug:tab2(13357): System.exit called, status: 0
06-29 17:36:02.978: I/AndroidRuntime(13357): VM exiting with result code 0, cleanup skipped.
06-29 17:36:02.997: I/ServiceChildProcess(11255): Destroying GeckoServiceChildProcess
06-29 17:36:03.020: I/enix.debug:tab(11255): System.exit called, status: 0
06-29 17:36:03.020: I/AndroidRuntime(11255): VM exiting with result code 0, cleanup skipped.
06-29 17:36:03.087: D/AndroidRuntime(10482): Shutting down VM
06-29 17:36:03.138: I/ActivityManager(476): Killing 11255:org.mozilla.fenix.debug:tab4/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-29 17:36:03.139: I/Zygote(290): Process 10533 exited due to signal 9 (Killed)
06-29 17:36:03.140: I/ActivityManager(476): Killing 13357:org.mozilla.fenix.debug:tab23/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-29 17:36:03.142: I/ActivityManager(476): Killing 11376:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-29 17:36:03.144: D/WindowManager(476): notifyANR took 650ms
