### ISSUE TITLE
[Bug]: Crash on opening keyboard

### ISSUE THREAD

**Issue by diohi** [mozilla-mobile/fenix#25313]
### Steps to reproduce

As soon as I try to open the keyboard FF crashes with a Java runtime exception
I had a large document saved to my clipboard (744310 characters) 

### Expected behaviour

Keyboard should open

### Actual behaviour

App crashes 

### Device name

Galaxy A50

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

100.2.0 (Build #2015880363)

### Device logs

0f29eb00-53e3-4627-b148-9ece3ecf03b8
java.lang.RuntimeException: android.os.DeadSystemException
 * New Sentry Instance: https://sentry.prod.mozaws.net/operations/fenix-fennec/?query=571e590945514d4da0d9aa4926d48b47
 * Socorro: https://crash-stats.mozilla.org/report/index/bp-c306bd64-19bb-448b-878a-ad00d0220520
----
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:171)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.utils.ClipboardHandler.containsURL$app_release(ClipboardHandler.kt:4)
	at org.mozilla.fenix.search.SearchDialogFragment$onResume$1$1.invokeSuspend(SearchDialogFragment.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.DeadSystemException
	... 10 more

### Additional information

#22958 looks similar

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20516)

**Comment by kbrosnan** [comment]
@mcarare to have a look

**Comment by gabrielluong** [comment]
@mcarare should this be closed or set for qa-needed?

**Comment by mcarare** [comment]
@diohi If possible, can you also re-test this on the next Nightly? Thank you!

**Comment by diohi** [comment]
> @diohi If possible, can you also re-test this on the next Nightly? Thank you!

Just tested it. It still crashes on 102.0a1 (Build #2015882859). I used the same document to verify.

I´m trying to figure out why the nightly won´t upload the crash reports, i can just copy a part of it and paste it in a document right now. This is what i get:

59cc3f42-a32a-42ef-9478-b9030eed1302
java.lang.RuntimeException: android.os.DeadSystemExceptionjava.lang.RuntimeException: android.os.DeadSystemException
at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:171)
at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
at org.mozilla.fenix.utils.ClipboardHandler.containsURL$app_nightly(ClipboardHandler.kt:4)
at org.mozilla.fenix.search.SearchDialogFragment$onResume$1$1.invokeSuspend(SearchDialogFragment.kt:2)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eabd8a5, java.util.concurrent.ThreadPoolExecutor@fcbb47a[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]]
Caused by: android.os.DeadSystemException
... 10 more


Should i file a new bug report for the nightly?

**Comment by mcarare** [comment]
@diohi Do you perhaps have another device (preferably not a Samsung device) to test the same scenario? Thank you!

**Comment by diohi** [comment]
@mcarare No but i will test it with the phone of a friend. It´s probably gonna take until tomorrow.

**Comment by sflorean** [comment]
Tested on the following builds (RC, Beta 102, and latest Nightly), and we couldn't reproduce the issue:
- Samsung A32 (Android 11)
- Motorola Moto G30 (Android 11)
- Realme GT (Android 11) 
- Oppo Find X3 (Android 11)
