### ISSUE TITLE
YouTube crashing when playing through firefox nightly on android 

### ISSUE THREAD

**Issue by beardedwunda** [mozilla-mobile/fenix#25325]
bd9440b5-ea08-4a74-af86-a80f76d46682
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b1f4674 u0 org.mozilla.fenix/.media.MediaSessionService}
----
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b1f4674 u0 org.mozilla.fenix/.media.MediaSessionService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20521)

**Comment by LaurentiuApahideanSV** [comment]
I tried to reproduce the issue on Firefox Nightly 102.0a1 2020-05-25 by watching youtube videos, pausing them an resuming them but was unable to. The issue seems to be related to https://github.com/mozilla-mobile/fenix/issues/17714.

### Device used:
- OnePlus 6T (Android 9)
- Google Pixel 6 (Android 13)
