### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. selectSearchEnginesShortcutTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25344]
### Stacktrace:
java.lang.AssertionError: Failed: assertExists.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'Google' (ignoreCase: false))

	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:162)
	at androidx.compose.ui.test.SemanticsNodeInteraction.assertExists(SemanticsNodeInteraction.kt:137)
	at androidx.compose.ui.test.SemanticsNodeInteraction.assertExists$default(SemanticsNodeInteraction.kt:136)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineList(SearchRobot.kt:409)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineList(SearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineList(SearchRobot.kt:111)
	at org.mozilla.fenix.ui.SmokeTest$selectSearchEnginesShortcutTest$2.invoke(SmokeTest.kt:475)
	at org.mozilla.fenix.ui.SmokeTest$selectSearchEnginesShortcutTest$2.invoke(SmokeTest.kt:472)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:263)
	at org.mozilla.fenix.ui.SmokeTest.selectSearchEnginesShortcutTest(SmokeTest.kt:472)
    
### Build: 5/23

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20537)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
