### ISSUE TITLE
Intermittent UI test failure - < TabbedBrowsingTest.closeAllTabsTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25341]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@ca9b6ef[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)
    
### Build: 5/20

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20535)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Closing in favour of #25925
