### ISSUE TITLE
Intermittent UI test failure - < BrowsingErrorPagesTest.blockPhishingPageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25356]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:67)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:66)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockPhishingPageTest(BrowsingErrorPagesTest.kt:66)
    
### Build: 5/24

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20542)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8423526193624416052/executions/bs.dfa2a350c2b140af/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:67)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:66)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockPhishingPageTest(BrowsingErrorPagesTest.kt:66)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9179209236495218719/executions/bs.20646e6d706b2711/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:67)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:66)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockPhishingPageTest(BrowsingErrorPagesTest.kt:66)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6061257219661177659/executions/bs.e4c2316f4e34b1a5/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:67)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockPhishingPageTest$2.invoke(BrowsingErrorPagesTest.kt:66)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockPhishingPageTest(BrowsingErrorPagesTest.kt:66)

**Comment by Mugurell** [comment]
Seen as failing in https://github.com/mozilla-mobile/fenix/pull/25441 - [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4715183642184833831).

**Comment by AndiAJ** [comment]
Flaky 1x on 6/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4871672654926793429/executions/bs.6e52accf6a0546c2/testcases/1/test-cases)

java.lang.IllegalStateException: UiAutomation not connected, UiAutomation@fac4023[id=-1, flags=0]
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1239)
	at android.app.UiAutomation.getServiceInfo(UiAutomation.java:497)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.helpers.HomeActivityTestRuleKt.closeNotificationShade(HomeActivityTestRule.kt:98)
	at org.mozilla.fenix.helpers.HomeActivityTestRuleKt.access$closeNotificationShade(HomeActivityTestRule.kt:1)
	at org.mozilla.fenix.helpers.HomeActivityTestRule.afterActivityFinished(HomeActivityTestRule.kt:43)
	at androidx.test.rule.ActivityTestRule.finishActivity(ActivityTestRule.java:415)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:557)
	at org.mozilla.fenix.helpers.RetryTestRule$apply$$inlined$statement$1.evaluate(RetryTestRule.kt:67)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
