### ISSUE TITLE
Intermittent UI test failure - < BrowsingErrorPagesTest. blockHarmfulPageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25380]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:101)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockHarmfulPageTest$2.invoke(BrowsingErrorPagesTest.kt:89)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockHarmfulPageTest$2.invoke(BrowsingErrorPagesTest.kt:88)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockHarmfulPageTest(BrowsingErrorPagesTest.kt:88)

**Comment by sv-ohorvath** [comment]
Failed 2/2 on 5/27 debug, will disable the test:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6757722942743332020/details?stepId=bs.ca62d83ee188e1ee&testCaseId=1

**Comment by AndiAJ** [comment]
Re-enabled in #25496
