### ISSUE TITLE
Intermittent UI test failure - < BrowsingErrorPagesTest.blockUnwantedSoftwarePageTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25394]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:78)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:77)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockUnwantedSoftwarePageTest(BrowsingErrorPagesTest.kt:77)
    
### Build: 5/25 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20569)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7691826298831162127/executions/bs.f9ee8e32bf57e3ea/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:79)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:78)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockUnwantedSoftwarePageTest(BrowsingErrorPagesTest.kt:78)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6195018821396380857/executions/bs.19337cdd8e7b7a7f/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:79)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:78)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockUnwantedSoftwarePageTest(BrowsingErrorPagesTest.kt:78)

**Comment by AndiAJ** [comment]
Flaky 1x on 5/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8042436885610407364/executions/bs.dd696c21de113833/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:79)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockUnwantedSoftwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:78)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockUnwantedSoftwarePageTest(BrowsingErrorPagesTest.kt:78)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 5/31 Main 

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6140603320738910622/executions/bs.bd6dc7c59cab8485/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6140603320738910622/executions/bs.1259ca4e56a1857f/test-cases)

**Comment by Mugurell** [comment]
Also see on https://github.com/mozilla-mobile/fenix/pull/25473. [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6197403962574911939/executions/bs.7e5c585281ce8314/testcases/1/test-cases).

**Comment by AndiAJ** [comment]
Re-enabled in #25496

**Comment by Mugurell** [comment]
Test was seen again as failing in https://github.com/mozilla-mobile/fenix/pull/25549. [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7517444027210077227/executions/bs.c9117d04ce11edc0/testcases/1/test-cases).
Checked with Andi who recommended re-opening this.
