### ISSUE TITLE
Intermittent UI test failure - addPrivateBrowsingShortcut

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25416]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6757722942743332020/details?stepId=bs.b56daa08737b9896&testCaseId=1
### Stacktrace:
`java.lang.RuntimeException: Error while connecting UiAutomation@d43e7ad[id=-1, flags=0]
at android.app.UiAutomation.connect(UiAutomation.java:259)
at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.ui.SettingsPrivacyTest.<init>(SettingsPrivacyTest.kt:42)`
### Build: 
Main branch 5/27

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20581)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5344484766244397594/executions/bs.dd15117f2f5127f8/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
