### ISSUE TITLE
Intermittent UI test failure - saveLoginFromPromptTest 

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25414]
### Firebase Test Run:
Flaky, 1/2 tries:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7616133251038543920/executions/bs.9a12466acf02a131
### Stacktrace:
`java.lang.RuntimeException: Error while connecting UiAutomation@3410079[id=-1, flags=0]
at android.app.UiAutomation.connect(UiAutomation.java:259)
at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.ui.SettingsPrivacyTest.<init>(SettingsPrivacyTest.kt:42)`
### Build: 
Main branch 5/27

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20579)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
