### ISSUE TITLE
Intermittent UI test failure - < TopSitesTest. verifyDefaultTopSitesLocale_EN >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25468]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@b65cad5[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TopSitesTest.<init>(TopSitesTest.kt:35)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20617)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
