### ISSUE TITLE
Intermittent UI test failure - < TabbedBrowsingTest.verifyUndoSnackBarTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25467]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyTabCounter(BrowserRobot.kt:116)
	at org.mozilla.fenix.ui.TabbedBrowsingTest$verifyUndoSnackBarTest$4.invoke(TabbedBrowsingTest.kt:197)
	at org.mozilla.fenix.ui.TabbedBrowsingTest$verifyUndoSnackBarTest$4.invoke(TabbedBrowsingTest.kt:196)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:848)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.verifyUndoSnackBarTest(TabbedBrowsingTest.kt:196)
    
### Build: 5/31 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20614)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
