### ISSUE TITLE
Intermittent UI test failure - < BrowsingErrorPagesTest. blockMalwarePageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25471]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockMalwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:57)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest$blockMalwarePageTest$2.invoke(BrowsingErrorPagesTest.kt:56)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.BrowsingErrorPagesTest.blockMalwarePageTest(BrowsingErrorPagesTest.kt:56)
    
### Build: 5/31 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20618)

**Comment by Mugurell** [comment]
Seen again in https://github.com/mozilla-mobile/fenix/pull/25540. [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5693231821252186319/executions/bs.c3ee327f4f01ab18/test-cases)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
