### ISSUE TITLE
Intermittent UI test failure - < SettingsBasicsTest.changeAccessibiltySettings>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25497]
### Stacktrace:
05-31 15:00:04.467: I/WindowManager(478): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 779ceae org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true)
05-31 15:00:04.676: D/BoundBrokerSvc(10001): onUnbind: Intent { act=com.google.firebase.dynamiclinks.service.START pkg=com.google.android.gms }
05-31 15:00:04.781: I/ActivityManager(478): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
05-31 15:00:04.782: I/ActivityManager(478): Killing 12238:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-31 15:00:04.788: I/ServiceChildProcess(12821): Destroying GeckoServiceChildProcess
05-31 15:00:04.789: W/Binder(12194): Caught a RuntimeException from the binder stub implementation.
05-31 15:00:04.789: W/Binder(12194): java.lang.SecurityException: Calling from not trusted UID!
05-31 15:00:04.789: W/Binder(12194): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
05-31 15:00:04.789: W/Binder(12194): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
05-31 15:00:04.789: W/Binder(12194): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
05-31 15:00:04.789: W/Binder(12194): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
05-31 15:00:04.789: W/Binder(12194): 	at android.os.Binder.execTransact(Binder.java:1123)
05-31 15:00:04.790: I/ServiceChildProcess(12955): Destroying GeckoServiceChildProcess
05-31 15:00:04.791: W/ActivityTaskManager(478): Force removing ActivityRecord{1a22861 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
05-31 15:00:04.803: I/enix.debug:tab(12821): System.exit called, status: 0
05-31 15:00:04.803: I/AndroidRuntime(12821): VM exiting with result code 0, cleanup skipped.
05-31 15:00:04.812: I/fenix.debug:gp(12955): System.exit called, status: 0
05-31 15:00:04.812: I/AndroidRuntime(12955): VM exiting with result code 0, cleanup skipped.
05-31 15:00:04.820: D/AndroidRuntime(12194): Shutting down VM
05-31 15:00:04.828: I/ActivityManager(478): Killing 12821:org.mozilla.fenix.debug:tab5/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-31 15:00:04.829: I/ActivityManager(478): Killing 12955:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
05-31 15:00:04.830: I/BackdropActivity(11422): onResume()
05-31 15:00:04.831: I/WindowManager(478):   Force finishing activity ActivityRecord{1a22861 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f} isExiting}
05-31 15:00:04.831: W/ActivityTaskManager(478): Duplicate finish request for r=ActivityRecord{1a22861 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f} isExiting}
05-31 15:00:04.838: I/ActivityTaskManager(478): Activity requesting to dismiss Keyguard: ActivityRecord{7106d9b u0 com.google.android.apps.mtaas.backdrop/.BackdropActivity t8}
05-31 15:00:04.839: D/WindowManager(478): notifyANR took 377ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20635)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
