### ISSUE TITLE
Intermittent UI test failure - assertion failure - DownloadFileTypesTest.downloadMultipleFileTypesTest

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#25500]
Seen in https://github.com/mozilla-mobile/fenix/pull/25473 -  https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8856446557927701424/executions/bs.51405ca90cd5280/testcases/2/test-cases

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:258)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:73) 
```

This seems different than the existing issues from https://github.com/mozilla-mobile/fenix/issues/25295 and https://github.com/mozilla-mobile/fenix/issues/25296 here the test runs but does not get the expected result.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20637)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4949564092567111435/executions/bs.b8d64d9319f33058/testcases/4/test-cases)

java.lang.AssertionError: Download notification Open button not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.assertDownloadNotificationPopup(DownloadRobot.kt:161)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.access$assertDownloadNotificationPopup(DownloadRobot.kt:1)
	at org.mozilla.fenix.ui.robots.DownloadRobot.verifyDownloadNotificationPopup(DownloadRobot.kt:44)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$4.invoke(DownloadFileTypesTest.kt:72)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$4.invoke(DownloadFileTypesTest.kt:71)
	at org.mozilla.fenix.ui.robots.DownloadRobot$Transition.clickDownload(DownloadRobot.kt:81)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:71)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9179370985506286963/executions/bs.bf9b2263bdf1513d/testcases/1/test-cases)

java.lang.AssertionError: Download notification Open button not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.assertDownloadNotificationPopup(DownloadRobot.kt:161)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.access$assertDownloadNotificationPopup(DownloadRobot.kt:1)
	at org.mozilla.fenix.ui.robots.DownloadRobot.verifyDownloadNotificationPopup(DownloadRobot.kt:44)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$4.invoke(DownloadFileTypesTest.kt:72)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$4.invoke(DownloadFileTypesTest.kt:71)
	at org.mozilla.fenix.ui.robots.DownloadRobot$Transition.clickDownload(DownloadRobot.kt:81)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:71)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
