### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. openWebsiteForSavedLoginTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25510]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:465)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$openWebsiteForSavedLoginTest$2.invoke(SettingsPrivacyTest.kt:288)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$openWebsiteForSavedLoginTest$2.invoke(SettingsPrivacyTest.kt:286)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:112)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.openWebsiteForSavedLoginTest(SettingsPrivacyTest.kt:286)
    
### Build: 6/2 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20641)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
