### ISSUE TITLE
Intermittent UI test failure - < SearchTest. shortcutButtonTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25511]
### Stacktrace:
java.lang.AssertionError: Failed to assertAny((Text + EditableText contains 'mozilla firefox' (ignoreCase: false)) && (Text + EditableText contains 'DuckDuckGo' (ignoreCase: false)))
None of the following nodes match:
Node #41 at (l=0.0, t=66.0, r=1080.0, b=220.0)px, Tag: 'mozac.awesomebar.suggestion'
Focused = 'false'
Text = '[mozilla, DuckDuckGo]'
Actions = [OnClick, GetTextLayoutResult]
MergeDescendants = 'true'
Selector used: 'TestTag = 'mozac.awesomebar.suggestion''

	at androidx.compose.ui.test.AssertionsKt.assertAny(Assertions.kt:319)
	at org.mozilla.fenix.ui.robots.SearchRobotKt$waitForSearchSuggestions$1.invoke(SearchRobot.kt:321)
	at org.mozilla.fenix.ui.robots.SearchRobotKt$waitForSearchSuggestions$1.invoke(SearchRobot.kt:318)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitUntil(AndroidComposeTestRule.android.kt:312)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineResults(SearchRobot.kt:313)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineResults(SearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineResults(SearchRobot.kt:100)
	at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:103)
	at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:99)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:263)
	at org.mozilla.fenix.ui.SearchTest.shortcutButtonTest(SearchTest.kt:99)
    
### Build: 6/2 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20642)

**Comment by sv-ohorvath** [comment]
Flaky on main 6/9: 
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6931479551860094543/executions/bs.3bb46f02f730d29e

**Comment by AndiAJ** [comment]
Flaky 1x on 6/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6682481508963703719/executions/bs.68a5ebbcf649f740/testcases/1/test-cases)

java.lang.AssertionError: Failed to assertAny((Text + EditableText contains 'mozilla firefox' (ignoreCase: false)) && (Text + EditableText contains 'DuckDuckGo' (ignoreCase: false)))
None of the following nodes match:
Node #33 at (l=0.0, t=66.0, r=1080.0, b=220.0)px, Tag: 'mozac.awesomebar.suggestion'
Focused = 'false'
Text = '[mozilla, DuckDuckGo]'
Actions = [OnClick, GetTextLayoutResult]
MergeDescendants = 'true'
Selector used: 'TestTag = 'mozac.awesomebar.suggestion''

	at androidx.compose.ui.test.AssertionsKt.assertAny(Assertions.kt:319)
	at org.mozilla.fenix.ui.robots.SearchRobotKt$waitForSearchSuggestions$1.invoke(SearchRobot.kt:325)
	at org.mozilla.fenix.ui.robots.SearchRobotKt$waitForSearchSuggestions$1.invoke(SearchRobot.kt:322)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitUntil(AndroidComposeTestRule.android.kt:312)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineResults(SearchRobot.kt:317)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineResults(SearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineResults(SearchRobot.kt:104)
	at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:103)
	at org.mozilla.fenix.ui.SearchTest$shortcutButtonTest$7.invoke(SearchTest.kt:99)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:259)
	at org.mozilla.fenix.ui.SearchTest.shortcutButtonTest(SearchTest.kt:99)

**Comment by AndiAJ** [comment]
Fixed with #25632
