### ISSUE TITLE
Intermittent UI test failure - < SettingsHomepageTest. setWallpaperTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25537]
### Stacktrace:
06-03 18:11:16.292: E/ExceptionHandler(13069): Uncaught exception handled: 
06-03 18:11:16.292: E/ExceptionHandler(13069): java.util.NoSuchElementException
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:759)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1313)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at org.mozilla.fenix.gleanplumb.OnDiskMessageMetadataStorage.writeToDisk$app_debug(OnDiskMessageMetadataStorage.kt:58)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at org.mozilla.fenix.gleanplumb.OnDiskMessageMetadataStorage.addMetadata(OnDiskMessageMetadataStorage.kt:38)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at org.mozilla.fenix.gleanplumb.NimbusMessagingStorage.addMetadata(NimbusMessagingStorage.kt:225)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at org.mozilla.fenix.gleanplumb.NimbusMessagingStorage.getMessages(NimbusMessagingStorage.kt:73)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at org.mozilla.fenix.gleanplumb.state.MessagingMiddleware$invoke$1.invokeSuspend(MessagingMiddleware.kt:41)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
06-03 18:11:16.292: E/ExceptionHandler(13069): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c014c8d, Dispatchers.IO]
06-03 18:11:16.292: D/TestExecutor(13069): Adding listener androidx.test.internal.events.client.OrchestratedInstrumentationListener
06-03 18:11:16.292: D/TestExecutor(13069): Adding listener androidx.test.internal.runner.listener.ActivityFinisherRunListener
06-03 18:11:16.295: I/mozac/CrashReporter(13069): Received crash: UncaughtExceptionCrash(timestamp=1654305076293, throwable=java.util.NoSuchElementException, breadcrumbs=[], uuid=ec699ee0-3828-4c3c-b7dd-f7580e702eac)
06-03 18:11:16.296: I/TestRunner(13069): run started: 1 tests
06-03 18:11:16.301: I/TestRunner(13069): started: setWallpaperTest(org.mozilla.fenix.ui.SettingsHomepageTest)
06-03 18:11:16.313: W/ActivityTestRule(13069): getActivityIntent() returned null using default: Intent(Intent.ACTION_MAIN)
06-03 18:11:16.422: D/GeckoViewConsole(13069): onEvent GeckoView:WebExtension:EnsureBuiltIn {"locationUri":"resource://android/assets/extensions/webcompat-reporter/","webExtensionId":"webcompat-reporter@mozilla.org"}
06-03 18:11:16.426: D/GeckoViewConsole(13069): onEvent GeckoView:WebExtension:EnsureBuiltIn {"locationUri":"resource://android/assets/extensions/browser-icons/","webExtensionId":"icons@mozac.org"}
06-03 18:11:16.446: D/GeckoViewConsole(13069): onEvent GeckoView:WebExtension:EnsureBuiltIn {"locationUri":"resource://android/assets/extensions/ads/","webExtensionId":"ads@mozac.org"}
06-03 18:11:16.454: D/GeckoViewConsole(13069): onEvent GeckoView:WebExtension:EnsureBuiltIn {"locationUri":"resource://android/assets/extensions/search/","webExtensionId":"cookies@mozac.org"}
06-03 18:11:16.455: D/GeckoViewConsole(13069): onEvent GeckoView:WebExtension:List null
06-03 18:11:16.455: E/GeckoConsole(13069): [JavaScript Error: "Error: File resource://default-theme/ does not contain a valid manifest" {file: "resource://gre/modules/addons/XPIInstall.jsm" line: 693}]
06-03 18:11:16.455: E/GeckoConsole(13069): [JavaScript Error: "Error: File resource://default-theme/ does not contain a valid manifest" {file: "resource://gre/modules/addons/XPIInstall.jsm" line: 693}]
06-03 18:11:16.518: V/UiAutomation(13069): Init UiAutomation@eb698bc[id=1, flags=0]
06-03 18:11:16.532: I/hwservicemanager(167): getTransport: Cannot find entry android.hardware.configstore@1.0::ISurfaceFlingerConfigs/default in either framework or device manifest.
06-03 18:11:16.739: I/InputManager(478): Disabling motion classifier because timeout changed: feature enabled, long press timeout = 3000
06-03 18:11:16.739: I/InputClassifier(478): Disabling motion classifier
06-03 18:11:16.740: I/hw-BpHwBinder(478): onLastStrongRef automatically unlinking death recipients
06-03 18:11:16.747: I/cmd(13914): oneway function results will be dropped but finished with status OK and parcel size 4
06-03 18:11:16.768: W/FenixPerf(13069): StrictMode violation suppressed: #8
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f08013d.
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f1301bf.
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f1301bf.
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f08013b.
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f1301be.
06-03 18:11:16.798: E/system_server(478): No package ID 7f found for ID 0x7f1301be.
06-03 18:11:16.804: V/AvrcpMediaPlayerList(1599): mPackageChangedBroadcastReceiver: action: android.intent.action.PACKAGE_CHANGED
06-03 18:11:16.804: D/AvrcpMediaPlayerList(1599): Name of package changed: org.mozilla.fenix.debug
06-03 18:11:16.820: I/RoleManagerService(478): Granting default roles...
06-03 18:11:16.821: I/PermissionControllerServiceImpl(11367): Updating user sensitive for uid 10152
06-03 18:11:16.845: D/CompatibilityChangeReporter(478): Compat change id reported: 135634846; UID 10152; state: DISABLED
06-03 18:11:16.845: D/CompatibilityChangeReporter(478): Compat change id reported: 143937733; UID 10152; state: ENABLED
06-03 18:11:16.854: D/Zygote(290): Forked child process 13923
06-03 18:11:16.883: W/Icing(10640): No valid account for uploading user actions
06-03 18:11:16.915: I/fenix.debug:gp(13923): Late-enabling -Xcheck:jni
06-03 18:11:16.921: I/ActivityTaskManager(478): START u0 {act=android.intent.action.MAIN flg=0x14000000 cmp=org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity} from uid 10152
06-03 18:11:16.962: I/fenix.debug:gp(13923): Unquickening 12 vdex files!
06-03 18:11:16.964: W/fenix.debug:gp(13923): Unexpected CPU variant for X86 using defaults: x86
06-03 18:11:16.989: D/EventSequenceValidator(478): Transition from ACTIVITY_FINISHED to INTENT_STARTED
06-03 18:11:16.991: I/InputReader(478): Reconfiguring input devices, changes=KEYBOARD_LAYOUTS | 
06-03 18:11:17.007: W/ActivityManager(478): Slow operation: 162ms so far, now at startProcess: done updating battery stats
06-03 18:11:17.008: W/ActivityManager(478): Slow operation: 162ms so far, now at startProcess: building log message
06-03 18:11:17.008: I/ActivityManager(478): Start proc 13923:org.mozilla.fenix.debug:gpu/u0a152 for service {org.mozilla.fenix.debug/org.mozilla.gecko.process.GeckoChildProcessServices$gpu}
06-03 18:11:17.008: W/ActivityManager(478): Slow operation: 162ms so far, now at startProcess: starting to update pids map
06-03 18:11:17.010: W/ActivityManager(478): Slow operation: 165ms so far, now at startProcess: done updating pids map
06-03 18:11:17.012: I/adbd(382): jdwp connection from 13923
06-03 18:11:17.014: D/EventSequenceValidator(478): Transition from INTENT_STARTED to ACTIVITY_LAUNCHED
06-03 18:11:17.029: W/Looper(478): Slow dispatch took 218ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@858f2d7 m=0
06-03 18:11:17.030: I/Telecom(478): DefaultDialerCache: Refreshing default dialer for user 0: now null: DDC.oR@APs
06-03 18:11:17.031: W/Looper(478): Slow delivery took 242ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@12717c4 m=0
06-03 18:11:17.032: W/Looper(478): Drained
06-03 18:11:17.138: D/ServiceAllocator(13069): org.mozilla.gecko.process.GeckoChildProcessServices$gpu updateBindings: FOREGROUND priority, 0 importance, 3 successful binds, 0 failed binds, 0 successful unbinds
06-03 18:11:17.139: I/Fitness(9486): OnPackageChangedOperation got intent: Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:org.mozilla.fenix.debug flg=0x45000010 pkg=com.google.android.gms cmp=com.google.android.gms/.chimera.PersistentIntentOperationService (has extras) } [CONTEXT service_id=17 ]
06-03 18:11:17.151: D/CarrierSvcBindHelper(1786): No carrier app for: 0
06-03 18:11:17.151: D/ImsResolver(1786): maybeAddedImsService, packageName: org.mozilla.fenix.debug
06-03 18:11:17.247: D/PermissionCache(336): checking android.permission.READ_FRAME_BUFFER for uid=1000 => granted (103 us)
06-03 18:11:17.391: W/Role(11367): Cannot get ApplicationInfo for default holder: com.google.android.dialer
06-03 18:11:17.569: W/system_server(478): Long monitor contention with owner Binder:478_14 (2827) at void com.android.server.wm.ActivityTaskManagerService.activityPaused(android.os.IBinder)(ActivityTaskManagerService.java:1848) waiters=0 in void com.android.server.wm.ActivityStackSupervisor$ActivityStackSupervisorHandler.handleMessage(android.os.Message) for 388ms
06-03 18:11:17.584: W/system_server(478): Long monitor contention with owner Binder:478_C (2462) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=2 in boolean com.android.server.am.ActivityManagerService.refContentProvider(android.os.IBinder, int, int) for 361ms
06-03 18:11:17.586: W/system_server(478): Long monitor contention with owner Binder:478_C (2462) at int com.android.server.am.ActivityManagerService.bindIsolatedService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, java.lang.String, int)(ActivityManagerService.java:15184) waiters=3 in void com.android.server.am.ActivityManagerService.monitor() for 109ms
06-03 18:11:17.590: W/Looper(478): Slow dispatch took 114ms android.fg h=android.os.Handler c=com.android.server.Watchdog$HandlerChecker@c35ef88 m=0
06-03 18:11:17.591: W/.gms.persisten(9486): Long monitor contention with owner GoogleApiHandler (9610) at boolean vws.e(vwr, android.content.ServiceConnection, java.lang.String, java.util.concurrent.Executor)(:com.google.android.gms@221514040@22.15.14 (150700-441847897):10) waiters=0 in void vwt.onServiceConnected(android.content.ComponentName, android.os.IBinder) for 385ms
06-03 18:11:17.591: I/ProvidersCache(13099): Provider returned no roots. Possibly naughty: com.google.android.apps.docs.storage
06-03 18:11:17.594: D/CompatibilityChangeReporter(478): Compat change id reported: 136274596; UID 10152; state: ENABLED
06-03 18:11:17.636: I/Fitness(9486): FitCleanupIntentOperation received Intent android.intent.action.PACKAGE_CHANGED [CONTEXT service_id=17 ]
06-03 18:11:17.655: W/FenixPerf(13069): StrictMode violation suppressed: #9
06-03 18:11:17.661: V/DisplayPowerController(478): Brightness [0.05] reason changing to: 'manual [ dim ]', previous reason: 'manual'.
06-03 18:11:17.678: D/EglHelper(1616): createEglContext start
06-03 18:11:17.758: D/EglHelper(1616): createEglContext done
06-03 18:11:17.758: D/EglHelper(1616): createEglSurface start
06-03 18:11:17.795: D/LifecycleMonitor(13069): Lifecycle status change: org.mozilla.fenix.HomeActivity@48af656 in: PRE_ON_CREATE
06-03 18:11:17.796: W/FenixPerf(13069): StrictMode violation suppressed: #10
06-03 18:11:17.819: I/Icing(10640): Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
06-03 18:11:17.822: D/EglHelper(1616): createEglSurface done
06-03 18:11:17.899: I/ProvidersCache(13099): Provider returned no roots. Possibly naughty: com.google.android.apps.docs.storage
06-03 18:11:18.095: W/lla.fenix.debu(13069): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
06-03 18:11:18.096: D/StrictMode(13069): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z
06-03 18:11:18.096: D/StrictMode(13069): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
06-03 18:11:18.096: D/StrictMode(13069): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
06-03 18:11:18.096: D/StrictMode(13069): 	at java.lang.Class.getMethod(Class.java:2067)
06-03 18:11:18.096: D/StrictMode(13069): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.widget.ViewUtils.<clinit>(ViewUtils.java:44)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java:80)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:976)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
06-03 18:11:18.096: D/StrictMode(13069): 	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:225)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.Activity.performCreate(Activity.java:8000)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.Activity.performCreate(Activity.java:7984)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
06-03 18:11:18.096: D/StrictMode(13069): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:769)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.os.Looper.loop(Looper.java:223)
06-03 18:11:18.096: D/StrictMode(13069): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-03 18:11:18.096: D/StrictMode(13069): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 18:11:18.096: D/StrictMode(13069): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-03 18:11:18.096: D/StrictMode(13069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-03 18:11:18.097: W/lla.fenix.debu(13069): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
06-03 18:11:18.098: D/StrictMode(13069): StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
06-03 18:11:18.098: D/StrictMode(13069): 	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
06-03 18:11:18.098: D/StrictMode(13069): 	at java.lang.Class.getDeclaredMethodInternal(Native Method)
06-03 18:11:18.098: D/StrictMode(13069): 	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
06-03 18:11:18.098: D/StrictMode(13069): 	at java.lang.Class.getMethod(Class.java:2066)
06-03 18:11:18.098: D/StrictMode(13069): 	at java.lang.Class.getMethod(Class.java:1693)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java:84)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:976)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
06-03 18:11:18.098: D/StrictMode(13069): 	at org.mozilla.fenix.HomeActivity.onCreate(HomeActivity.kt:225)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.Activity.performCreate(Activity.java:8000)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.Activity.performCreate(Activity.java:7984)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
06-03 18:11:18.098: D/StrictMode(13069): 	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:769)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.os.Looper.loop(Looper.java:223)
06-03 18:11:18.098: D/StrictMode(13069): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-03 18:11:18.098: D/StrictMode(13069): 	at java.lang.reflect.Method.invoke(Native Method)
06-03 18:11:18.098: D/StrictMode(13069): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-03 18:11:18.098: D/StrictMode(13069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-03 18:11:18.110: E/MmTelFeatureConnection [0](1786): ImsRegistrationCallbackAdapter: ImsRegistration is null
06-03 18:11:18.128: W/FenixPerf(13069): StrictMode violation suppressed: #11
06-03 18:11:18.143: I/Process(13069): Sending signal. PID: 13069 SIG: 9
06-03 18:11:18.271: I/Icing(10640): IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=null serviceId=30
06-03 18:11:18.274: I/gle.android.gm(10640): Background young concurrent copying GC freed 24893(1498KB) AllocSpace objects, 16(768KB) LOS objects, 43% free, 8765KB/15MB, paused 32us total 1.087s
06-03 18:11:18.348: D/SharedPreferencesImpl(10640): Time required to fsync /data/user/0/com.google.android.gms/shared_prefs/proxy-apps-corpus.xml: [<1: 0, <2: 0, <4: 0, <8: 1, <16: 0, <32: 1, <64: 0, <128: 2, <256: 1, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
06-03 18:11:18.483: I/ActivityManager(478): Process org.mozilla.fenix.debug (pid 13069) has died: fg  TOP 
06-03 18:11:18.484: I/Zygote(290): Process 13069 exited due to signal 9 (Killed)
06-03 18:11:18.494: D/ConnectivityService(478): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=70, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10152 AdministratorUids: [] RequestorUid: 10152 RequestorPackageName: org.mozilla.fenix.debug] ], android.os.BinderProxy@fed91fc)
06-03 18:11:18.496: D/ConnectivityService(478): releasing NetworkRequest [ TRACK_DEFAULT id=70, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10152 AdministratorUids: [] RequestorUid: 10152 RequestorPackageName: org.mozilla.fenix.debug] ] (release request)
06-03 18:11:18.520: W/WindowManager(478): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@acc7137
06-03 18:11:18.527: W/ActivityManager(478): Scheduling restart of crashed service org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService in 1000ms for connection
06-03 18:11:18.528: W/ActivityManager(478): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-03 18:11:18.540: I/libprocessgroup(478): Successfully killed process cgroup uid 10152 pid 13069 in 0ms
06-03 18:11:18.543: I/ActivityManager(478): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-03 18:11:18.544: I/ActivityManager(478): Killing 13753:org.mozilla.fenix.debug:tab24/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-03 18:11:18.544: W/Binder(13044): Caught a RuntimeException from the binder stub implementation.
06-03 18:11:18.544: W/Binder(13044): java.lang.SecurityException: Calling from not trusted UID!
06-03 18:11:18.544: W/Binder(13044): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-03 18:11:18.544: W/Binder(13044): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-03 18:11:18.544: W/Binder(13044): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-03 18:11:18.544: W/Binder(13044): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-03 18:11:18.544: W/Binder(13044): 	at android.os.Binder.execTransact(Binder.java:1123)
06-03 18:11:18.546: I/ActivityManager(478): Killing 13923:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-03 18:11:18.552: I/WindowManager(478):   Force finishing activity ActivityRecord{871acf7 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9}
06-03 18:11:18.554: D/AndroidRuntime(13044): Shutting down VM
06-03 18:11:18.579: I/Zygote(290): Process 13923 exited due to signal 9 (Killed)
06-03 18:11:18.590: I/ActivityManager(478):   Force stopping service ServiceRecord{738f917 u0 org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService}
### Build: 6/4 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20653)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx month.
