### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest.launchPageShortcutInPrivateModeTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25541]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:398)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:270)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:213)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:94)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:95)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:387)
    
### Build: 6/6 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20656)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7623785673034699146/executions/bs.f5253a48e7ebc3da/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: for text= "TestShortcut"
	at androidx.test.uiautomator.UiCollection.getChildByText(UiCollection.java:126)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:215)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:94)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:95)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:387)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7661261350667918991/executions/bs.dfcf063b39583e1d/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.assertSearchEngineSuggestionResults(SearchRobot.kt:320)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.access$assertSearchEngineSuggestionResults(SearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineSuggestionResults(SearchRobot.kt:105)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchBookmarksAndHistoryTest$12.invoke(SettingsSearchTest.kt:101)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchBookmarksAndHistoryTest$12.invoke(SettingsSearchTest.kt:98)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:259)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleSearchBookmarksAndHistoryTest(SettingsSearchTest.kt:98)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7056756895064680931/executions/bs.2c4b0c3431029022/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:398)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:270)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:213)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:94)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:95)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:387)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6529665076382642417/executions/bs.e600458c0d407f53/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:398)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:270)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:213)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:95)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:96)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:390)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7999977842162768897/executions/bs.ed10fa178a04e56f/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:398)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:270)
	at androidx.test.uiautomator.UiScrollable.getChildByText(UiScrollable.java:213)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut$shortcut(AddToHomeScreenRobot.kt:95)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.searchAndOpenHomeScreenShortcut(AddToHomeScreenRobot.kt:96)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.launchPageShortcutInPrivateModeTest(SettingsPrivacyTest.kt:390)

**Comment by AndiAJ** [comment]
Closing as it didn't fail recently.
