### ISSUE TITLE
Intermittent UI test failure - < ContextMenusTest.verifyContextShareLink>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25560]
### Stacktrace:
06-07 18:16:44.232: I/WindowManager(479): Input event dispatching timed out sending to org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity.  Reason: 674ff2b org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server) is not responding. Waited 5002ms for MotionEvent(deviceId=-1, source=0x00001002, displayId=0, action=MOVE, actionButton=0x00000000, flags=0x00000000, metaState=0x00000000, buttonState=0x00000000, classification=NONE, edgeFlags=0x00000000, xPrecision=1.0, yPrecision=1.0, xCursorPosition=nan, yCursorPosition=nan, pointers=[0: (80.0, 218.0)]), policyFlags=0x6b000000
06-07 18:16:44.359: D/GeckoIdleService(12929): Get idle time: time since reset 5010 msec
06-07 18:16:44.359: D/GeckoIdleService(12929): Idle timer callback: current idle time 5010 msec
06-07 18:16:44.359: D/GeckoIdleService(12929): next timeout 174990 msec from now
06-07 18:16:44.359: D/GeckoIdleService(12929): SetTimerExpiryIfBefore: next timeout 174990 msec from now
06-07 18:16:44.359: D/GeckoIdleService(12929): reset timer expiry to 175000 msec from now
06-07 18:16:44.359: D/GeckoIdleService(12929): Idle timer callback: tell observer 0x95a27144 user is idle
06-07 18:16:44.462: I/ActivityManager(479): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-07 18:16:44.462: I/ActivityManager(479): Killing 12929:org.mozilla.fenix.debug/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-07 18:16:44.465: W/Binder(12906): Caught a RuntimeException from the binder stub implementation.
06-07 18:16:44.465: W/Binder(12906): java.lang.SecurityException: Calling from not trusted UID!
06-07 18:16:44.465: W/Binder(12906): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-07 18:16:44.465: W/Binder(12906): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-07 18:16:44.465: W/Binder(12906): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-07 18:16:44.465: W/Binder(12906): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-07 18:16:44.465: W/Binder(12906): 	at android.os.Binder.execTransact(Binder.java:1123)
06-07 18:16:44.466: W/ActivityTaskManager(479): Force removing ActivityRecord{97e7a0a u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9 f}}: app died, no saved state
06-07 18:16:44.482: D/AndroidRuntime(12906): Shutting down VM
06-07 18:16:44.515: E/JavaBinder(12906): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
06-07 18:16:44.515: E/JavaBinder(12906): java.lang.RuntimeException: Bad file descriptor
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.os.BinderProxy.transactNative(Native Method)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.os.BinderProxy.transact(BinderProxy.java:540)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5262)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:136)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:228)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
06-07 18:16:44.515: E/JavaBinder(12906): 	at android.os.Binder.execTransact(Binder.java:1123)
06-07 18:16:44.530: I/ServiceChildProcess(13692): Destroying GeckoServiceChildProcess
06-07 18:16:44.533: I/ActivityManager(479): Killing 13692:org.mozilla.fenix.debug:tab9/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-07 18:16:44.536: I/ActivityManager(479): Killing 13852:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-07 18:16:44.549: D/WindowManager(479): notifyANR took 321ms
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20668)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx a month.
