### ISSUE TITLE
 Crash in [@ java.lang.IllegalStateException: at androidx.fragment.app.Fragment.requireView(Fragment.java)]

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#25563]
https://bugzilla.mozilla.org/show_bug.cgi?id=1773347

The crash rate looks much higher in Release than in Nightly and Beta. This crash signature is #5 in Release, but doesn't appear in the top 50 of Nightly or Beta.

Crash report: https://crash-stats.mozilla.org/report/index/45c9e008-514a-40ed-a213-f2a2c0220608

Java stack trace:
```
java.lang.IllegalStateException
	at androidx.fragment.app.Fragment.requireView(Fragment.java:2)
	at org.mozilla.fenix.library.historymetadata.HistoryMetadataGroupFragment$onCreateView$4.invoke(HistoryMetadataGroupFragment.kt:2)
	at org.mozilla.fenix.library.historymetadata.controller.DefaultHistoryMetadataGroupController$deleteAll$1.invokeSuspend(HistoryMetadataGroupController.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20672)

**Comment by mcarare** [comment]
Note for QA:

Initial STR:
 - Open a history group
 - Tap on the delete all button (from the top right of the screen) fast (at least twice)
 - On the confirmation dialog tap the delete button twice fast.
 - App crashes

After the fix, it should not be possible to have two dialogues.

**Comment by sflorean** [comment]
Tested with the following devices on latest Nightly and the crash/ 2 dialogues were not displayed.
- OnePlus 9 (Android 12)
- Pixel 6 (Android 12)
- Samsung A32 (Android 11).

**Comment by cpeterso** [comment]
@mcarare - Can we uplift your fix to Fenix Beta 102? Even though the crash rate in Beta is low, the crash rate on Release is very high.

**Comment by rvandermeulen** [comment]
@Mergifyio backport releases_v102.0.0

**Comment by rvandermeulen** [comment]
Uplifted to the v102 branch in #25720. Unfortunately, this missed the 102.1.1 build, but it'll be in any subsequent 102.x release after that.

**Comment by delia-pop** [comment]
Tested on RC 102.2.0 with Google Pixel 6 (Android 12). The issue was not encountered.
