### ISSUE TITLE
Intermittent UI test failure - HomeScreenTest.dismissOnboardingUsingBookmarksTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25579]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6696243506005561227/executions/bs.2c09bc2d25aae673
### Stacktrace:
`java.lang.RuntimeException: Error while connecting UiAutomation@bac5c5e[id=-1, flags=0]
at android.app.UiAutomation.connect(UiAutomation.java:259)
at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.ui.HomeScreenTest.<init>(HomeScreenTest.kt:31)`
### Build: 
on main 6/9

Known issue: https://github.com/mozilla-mobile/fenix/issues/25132

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20679)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6532940061125001073/executions/bs.99023af114e5ba82/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@3e9108d[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.HomeScreenTest.<init>(HomeScreenTest.kt:31)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6476279798326038196/executions/bs.743705e5329c6b0/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4624027911031954850/executions/bs.d4b2c564a3f9096/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@86b62da[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.HomeScreenTest.<init>(HomeScreenTest.kt:31)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
