### ISSUE TITLE
Intermittent UI test failure - TabbedBrowsingTest.closeTabTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25578]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6696243506005561227/executions/bs.6f49200709fbc39c
### Stacktrace:
`java.lang.RuntimeException: Error while connecting UiAutomation@3740472[id=-1, flags=0]
at android.app.UiAutomation.connect(UiAutomation.java:259)
at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)`
### Build: 
on main 6/9

Known issue: https://github.com/mozilla-mobile/fenix/issues/25132

**Comment by AndiAJ** [comment]
Flaky 1x 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7056756895064680931/executions/bs.d96e5034132df28f/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@97a1acd[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
