### ISSUE TITLE
Intermittent UI test failure - DownloadTest.testCloseDownloadPrompt

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25582]
### Firebase Test Run:
Flaky 1x, different cause: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6696243506005561227/executions/bs.6efb3b6fc14939e7
### Stacktrace:
`androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (view.getContentDescription() is "Menu")`
### Build: 
main 6/9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20684)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6145772402386505934/executions/bs.21394a6993e76b75/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:263)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:98)
	at org.mozilla.fenix.ui.DownloadTest.testCloseDownloadPrompt(DownloadTest.kt:86)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7875874550238599349/executions/bs.289abdde9b636947/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:260)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.DownloadTest.testCloseDownloadPrompt(DownloadTest.kt:109)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
