### ISSUE TITLE
Intermittent UI test failure - CustomTabsTest.customTabShareTextTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#25583]
### Firebase Test Run:
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8550465586738230344/executions/bs.860288759431a177
### Stacktrace:
`java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.clickShareSelectedText(BrowserRobot.kt:781)
at org.mozilla.fenix.ui.CustomTabsTest.customTabShareTextTest(CustomTabsTest.kt:159)`
### Build: 
on main 6/9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20685)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6152182392285553804/executions/bs.daf3a535b18d440e/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.clickShareSelectedText(BrowserRobot.kt:795)
	at org.mozilla.fenix.ui.CustomTabsTest.customTabShareTextTest(CustomTabsTest.kt:162)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7380004979876198760/executions/bs.294f2f3095b7c7a3/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.clickShareSelectedText(BrowserRobot.kt:795)
	at org.mozilla.fenix.ui.CustomTabsTest.customTabShareTextTest(CustomTabsTest.kt:162)

**Comment by Mugurell** [comment]
Also failing in https://github.com/mozilla-mobile/fenix/pull/26431

**Comment by sv-ohorvath** [comment]
No new reports since Aug. Closing
