### ISSUE TITLE
Android 12 Foreground Service restriction

### ISSUE THREAD

**Issue by SalarIonck** [mozilla-mobile/fenix#25608]
### Steps to reproduce

Launch Firefox. return to the home screen start a new app

### Expected behaviour

Firefox should not crash.

### Actual behaviour

Firefox crashes

### Device name

Xiaomi Redmi note 9s

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

103.0a1

### Device logs

`android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service org.mozilla.fenix/.media.MediaSessionService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelable(Parcel.java:3333)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2420)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7212)
	at android.app.Service.startForeground(Service.java:736)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate.startForegroundNotificationIfNeeded(MediaSessionServiceDelegate.kt:8)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$3.emit(MediaSessionServiceDelegate.kt:35)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Emitters.kt:9)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate$onCreate$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:5)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7866)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8b03557, Dispatchers.Main]`

### Additional information

Due to a restriction in Android 12's `Foreground Service`. It is no longer possible to use `Service` to do background operations.

This means that `Service` can only be used when Firefox is running in the foreground.

If Firefox is closed or went to the background, invoking  `Service`. Using `startForegroundService` will cause  `ForegroundServiceStartNotAllowedException`.
Causing Firefox to crash.

To perform background task you need to use `Worker` instead of `Service` other way Firefox will crash.
This issue effects all android devices running android 12.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20700)

**Comment by Amejia481** [comment]
https://sentry.io/organizations/mozilla/issues/3338690729/?project=6295546&query=is%3Aunresolved+level%3Afatal+ForegroundServiceStartNotAllowedException&sort=freq&statsPeriod=14d

**Comment by mcarare** [comment]
I cannot see crashes with this signature in sentry after the 107 version. I do see a few in crash-stats.
Is it safe to assume the recent changes to `MediaSessionService` have decreased the number of crashes?

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1814305

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by delia-pop** [comment]
Removing the QA Needed label since the ticket was moved to Bugzilla.
