### ISSUE TITLE
Intermittent UI test failure - < TopSitesTest. verifyOpenTopSitePrivateTab >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25626]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySnackBarText(BrowserRobot.kt:122)
	at org.mozilla.fenix.ui.TopSitesTest$verifyOpenTopSitePrivateTab$4.invoke(TopSitesTest.kt:116)
	at org.mozilla.fenix.ui.TopSitesTest$verifyOpenTopSitePrivateTab$4.invoke(TopSitesTest.kt:115)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.addToFirefoxHome(ThreeDotMenuMainRobot.kt:309)
	at org.mozilla.fenix.ui.TopSitesTest.verifyOpenTopSitePrivateTab(TopSitesTest.kt:115)
    
### Build: 6/15 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20713)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
