### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest. homeScreenItemsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25630]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@4e4e822[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.HomeScreenTest.<init>(HomeScreenTest.kt:31)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20717)

**Comment by AndiAJ** [comment]
Closing as it didn't fail lately.
