### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. tabMediaControlButtonTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25643]
### Stacktrace:
java.lang.IllegalStateException: Resource Compose-Espresso link isIdleNow() is returning true, but a message indicating that the resource has transitioned from busy to idle was never sent.
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleRaceCondition(IdlingResourceRegistry.java:5)
	at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:2)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
### Notes: Similar with #25345

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20725)

**Comment by sv-ohorvath** [comment]
Not yet confirmed, but this could be caused by a bug in Compose when a compose view is hidden, as observed by other people in the FTL slack channel: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1654692960684439
A potential fix could be in 1.2.0-alpha07.
@AndiAJ will run the tests with the Compose 1.2.0-alpha07 version to confirm.

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
