### ISSUE TITLE
Intermittent UI test failure - <Classname.verifyBasicNavigationToolbarFunctionality>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25656]
### Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6777631117620506800/executions/bs.a8477e68ee7e18c/testcases/1/test-cases)
Provide a Firebase test run report link here showcasing the problem
### Stacktrace: java.lang.RuntimeException: Error while connecting UiAutomation@ae61940[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.SmokeTest.<init>(SmokeTest.kt:64)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20731)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7149532798817018611/executions/bs.a8feb73d45d818c8/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@9fad30f[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.SmokeTest.<init>(SmokeTest.kt:64)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
