### ISSUE TITLE
Intermittent UI test failure - < TopSitesTest.verifyRemoveTopSite>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25655]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@acafbef[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TopSitesTest.<init>(TopSitesTest.kt:35)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20732)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5246040111437170003/executions/bs.a3c604f88140cff3/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@b45ee9c[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TopSitesTest.<init>(TopSitesTest.kt:35)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
