### ISSUE TITLE
Intermittent UI test failure - < BookmarksTest. cantSelectDesktopFoldersTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25698]
### Stacktrace:
java.lang.NoClassDefFoundError: org.mozilla.fenix.ui.robots.HomeScreenRobotKt
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(Unknown Source:0)
	at org.mozilla.fenix.ui.BookmarksTest.cantSelectDesktopFoldersTest(BookmarksTest.kt:591)
	... 34 trimmed
Caused by: java.lang.ExceptionInInitializerError
	... 37 more
Caused by: java.lang.IllegalStateException: UiAutomation not connected, UiAutomation@359e517[id=-1, flags=0]
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1239)
	at android.app.UiAutomation.getServiceInfo(UiAutomation.java:497)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.<clinit>(HomeScreenRobot.kt:424)
	... 37 more
    
### Notes: Same as #25340 #25339 #25339 #25296 #25498 #25542 #25566 #25629 #25631

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20763)

**Comment by AndiAJ** [comment]
Closing in favour of #25924
