### ISSUE TITLE
Fennec Mobile crashes on selecting credit card number input field

### ISSUE THREAD

**Issue by almightyyoda2012** [mozilla-mobile/fenix#25706]
Fennec Mobile consistently crashes upon selecting any credit card input field

e61c821d-9f71-4331-aee8-f5b192b698a0
java.lang.NumberFormatException: For input string: "******"
----
java.lang.NumberFormatException: For input string: "******"
	at java.lang.Integer.parseInt(Integer.java:604)
	at java.lang.Integer.parseInt(Integer.java:650)
	at mozilla.components.support.utils.CreditCardUtilsKt.creditCardIIN(CreditCardUtils.kt:17)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onCreditCardSelect$1.invoke(GeckoPromptDelegate.kt:15)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onCreditCardSelect(GeckoPromptDelegate.kt:4)
	at org.mozilla.geckoview.PromptController$CreditCardSelectHandler.callDelegate(PromptController.java:2)
	at org.mozilla.geckoview.PromptController$CreditCardSelectHandler.callDelegate(PromptController.java:1)
	at org.mozilla.geckoview.PromptController.getResponse(PromptController.java:6)
	at org.mozilla.geckoview.PromptController.handleEvent(PromptController.java:6)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:6)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20768)

**Comment by amedyne** [comment]
@almightyyoda2012 Can you share what build version you are using and encountering this issue with?

**Comment by kbrosnan** [comment]
Can you reproduce this crash on Firefox? We don't build the Fennec F-Droid APK. https://forum.f-droid.org/

**Comment by almightyyoda2012** [comment]
Not reproducible on firefox

**Comment by almightyyoda2012** [comment]
Build #931020

**Comment by csadilek** [comment]
> Build #931020

Yes, that makes sense. This bug was fixed in Fenix 96, so a build based on 93 would have this crash:
- https://github.com/mozilla-mobile/fenix/issues/22607
- https://github.com/mozilla-mobile/android-components/commit/09eb7d13b1392a5dcb09c97b82d35a5a820141a2
