### ISSUE TITLE
Intermittent UI test failure - < CollectionTest.mainMenuSaveToExistingCollection>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25714]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@f510cf5[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.CollectionTest.<init>(CollectionTest.kt:32)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655 #25656 #25657 #25700 #25711 #25713

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20774)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6547038931035715046/executions/bs.4b4b935c1f97ee62/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@2686618[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.CollectionTest.<init>(CollectionTest.kt:32)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
