### ISSUE TITLE
Intermittent UI test failure - < TopSitesTest. verifyOpenTopSiteNormalTab >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25715]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@8dd15d2[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TopSitesTest.<init>(TopSitesTest.kt:35)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655 #25656 #25657 #25700 #25711 #25713 #25714

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20777)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
