### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. mainMenuRefreshButtonTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25712]
### Stacktrace:
androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SmokeTest.mainMenuRefreshButtonTest(SmokeTest.kt:424)
    
### Build: 6/21 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20773)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
