### ISSUE TITLE
Intermittent UI test failure - < SitePermissionsTest. blockNotificationsPermissionPromptTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25713]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@14f9329[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2133)
	at androidx.test.runner.permission.UiAutomationShellCommand.<init>(UiAutomationShellCommand.java:65)
	at androidx.test.runner.permission.PermissionRequester.addPermissions(PermissionRequester.java:92)
	at androidx.test.rule.GrantPermissionRule.grantPermissions(GrantPermissionRule.java:100)
	at androidx.test.rule.GrantPermissionRule.grant(GrantPermissionRule.java:94)
	at org.mozilla.fenix.ui.SitePermissionsTest.<init>(SitePermissionsTest.kt:38)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655 #25656 #25657 #25700 #25711

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20775)

**Comment by AndiAJ** [comment]
Closing in favour of #25925
