### ISSUE TITLE
Intermittent UI test failure - < TabbedBrowsingTest.closePrivateTabTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25727]
### Stacktrace:
java.lang.RuntimeException: Error while connecting UiAutomation@9d53b0c[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655 #25656 #25657 #25700 #25711 #25713 #25714 #25715 #25716

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20785)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/22 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6677883741225399590/executions/bs.9def0c6d36ed78d6/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@9d53b0c[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)

**Comment by AndiAJ** [comment]
Flaky 1x on 6/30 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8888487749410625343/executions/bs.8a2d7a34ac41840f/testcases/1/test-cases)

java.lang.RuntimeException: Error while connecting UiAutomation@1e131e6[id=-1, flags=0]
	at android.app.UiAutomation.connect(UiAutomation.java:259)
	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2176)
	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
	at androidx.test.uiautomator.QueryController.<init>(QueryController.java:95)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:109)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.TabbedBrowsingTest.<init>(TabbedBrowsingTest.kt:43)
