### ISSUE TITLE
Intermittent UI test failure - < BookmarksTest.navigateBookmarksFoldersTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25728]
### Stacktrace:
06-22 09:05:34.202: I/WindowManager(479): WIN DEATH: Window{8c5ae31 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}
06-22 09:05:34.212: W/InputDispatcher(479): Attempted to unregister already unregistered input channel '8c5ae31 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity (server)'
06-22 09:05:34.218: I/ActivityManager(479):   Force stopping service ServiceRecord{11688b7 u0 com.google.android.gms/.cast.media.CastMediaRouteProviderService}
06-22 09:05:34.219: W/ActivityManager(479): Unable to launch app com.google.android.gms/10097 for service Intent { act=android.media.MediaRoute2ProviderService cmp=com.google.android.gms/.cast.media.CastMediaRouteProviderService }: process is bad
06-22 09:05:34.220: E/ActivityManager(479): Failure starting process com.google.android.gms
06-22 09:05:34.220: E/ActivityManager(479): java.lang.SecurityException: Package com.google.android.gms is currently frozen!
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.pm.PackageManagerService.checkPackageStartable(PackageManagerService.java:4463)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:1757)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2319)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ProcessList.startProcessLocked(ProcessList.java:2441)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3170)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2946)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:2062)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.am.ActivityManagerService.bindIsolatedService(ActivityManagerService.java:15184)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1833)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1773)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.bind(MediaRoute2ProviderServiceProxy.java:224)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.media.MediaRoute2ProviderServiceProxy.onBindingDied(MediaRoute2ProviderServiceProxy.java:290)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1950)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1986)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.os.Handler.handleCallback(Handler.java:938)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 09:05:34.220: E/ActivityManager(479): 	at android.os.Looper.loop(Looper.java:223)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.SystemServer.run(SystemServer.java:622)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.server.SystemServer.main(SystemServer.java:408)
06-22 09:05:34.220: E/ActivityManager(479): 	at java.lang.reflect.Method.invoke(Native Method)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-22 09:05:34.220: E/ActivityManager(479): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
06-22 09:05:34.220: I/ActivityManager(479): Force stopping com.google.android.gms appid=10097 user=0: start failure
06-22 09:05:34.221: I/ActivityManager(479):   Force stopping service ServiceRecord{d00f953 u0 com.google.android.gms/.cast.media.CastMediaRouteProviderService}
06-22 09:05:34.221: W/ActivityManager(479): Unable to launch app com.google.android.gms/10097 for service Intent { act=android.media.MediaRoute2ProviderService cmp=com.google.android.gms/.cast.media.CastMediaRouteProviderService }: process is bad
06-22 09:05:34.222: I/ActivityManager(479): Process org.mozilla.fenix.debug (pid 11579) has died: fg  TOP 
06-22 09:05:34.222: I/libprocessgroup(479): Successfully killed process cgroup uid 10152 pid 11579 in 0ms
06-22 09:05:34.225: I/ServiceChildProcess(12427): Destroying GeckoServiceChildProcess
06-22 09:05:34.232: W/ActivityManager(479): Scheduling restart of crashed service org.mozilla.fenix.debug/androidx.work.impl.background.systemjob.SystemJobService in 1000ms for connection
06-22 09:05:34.235: W/ActivityTaskManager(479): Force removing ActivityRecord{443a342 u0 org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity t9}: app died, no saved state
06-22 09:05:34.239: W/ActivityManager(479): Crash of app org.mozilla.fenix.debug running instrumentation ComponentInfo{org.mozilla.fenix.debug.test/androidx.test.runner.AndroidJUnitRunner}
06-22 09:05:34.243: I/ActivityManager(479): Force stopping org.mozilla.fenix.debug appid=10152 user=0: finished inst
06-22 09:05:34.244: I/ActivityManager(479): Killing 12427:org.mozilla.fenix.debug:tab9/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-22 09:05:34.246: W/Binder(11519): Caught a RuntimeException from the binder stub implementation.
06-22 09:05:34.246: W/Binder(11519): java.lang.SecurityException: Calling from not trusted UID!
06-22 09:05:34.246: W/Binder(11519): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-22 09:05:34.246: W/Binder(11519): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-22 09:05:34.246: W/Binder(11519): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-22 09:05:34.246: W/Binder(11519): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-22 09:05:34.246: W/Binder(11519): 	at android.os.Binder.execTransact(Binder.java:1123)
06-22 09:05:34.250: I/ActivityManager(479): Killing 12572:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to finished inst
06-22 09:05:34.251: D/AndroidRuntime(11519): Shutting down VM
### Notes: Similar with #24047

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20786)

**Comment by AndiAJ** [comment]
Closing in favour of #25926
