### ISSUE TITLE
[Bug]: address autofill crash

### ISSUE THREAD

**Issue by sheikh-azharuddin** [mozilla-mobile/fenix#25735]
### Steps to reproduce

Enable address autofill
Click on some fields
Firefox Crashing 

### Expected behaviour

Should not crash

### Actual behaviour

Crashing 

### Device name

rog 3

### Android version

android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest

### Device logs

74d73b8c-2861-45f4-a540-b2fa15be3c0f
java.lang.NullPointerException: additionalName must not be null
----
java.lang.NullPointerException: additionalName must not be null
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onAddressSelect$1.invoke(GeckoPromptDelegate.kt:12)
	at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
	at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onAddressSelect(GeckoPromptDelegate.kt:4)
	at org.mozilla.geckoview.PromptController$AddressSelectHandler.callDelegate(PromptController.java:2)
	at org.mozilla.geckoview.PromptController$AddressSelectHandler.callDelegate(PromptController.java:1)
	at org.mozilla.geckoview.PromptController.getResponse(PromptController.java:6)
	at org.mozilla.geckoview.PromptController.handleEvent(PromptController.java:7)
	at org.mozilla.geckoview.GeckoSession$Listener.handleMessage(GeckoSession.java:10)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:359)
	at android.app.ActivityThread.main(ActivityThread.java:8046)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

### Additional information

![Screenshot_20220623-212747200](https://user-images.githubusercontent.com/58127841/175343093-1461d16b-73df-4a3c-b632-0beab043f34a.jpg)

**Comment by kbrosnan** [comment]
Please provide the New Sentry Instance and/or Socorro links

**Comment by sheikh-azharuddin** [comment]
Here is the socorro link
https://crash-stats.mozilla.org/report/index/7291f7a5-aeb5-4c04-a090-077410220623

New sentry instance , I am getting error after signin

**Comment by kbrosnan** [comment]
@gabrielluong would you have a look at this. It seems like fallout from address autofill.

**Comment by gabrielluong** [comment]
This should be fixed in GV https://bugzilla.mozilla.org/show_bug.cgi?id=1774481. I am guessing we're waiting for this to make it from GV into AC into Fenix.

**Comment by kbrosnan** [comment]
We expect this to be fixed by bz-1774481.
