### ISSUE TITLE
Screengrab currently does not work on 2.206.2

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#25773]
Trying on an API 30 AVD, I get a `RuntimeException` with `screengrab 2.206.2`.

```Kotlin
java.lang.RuntimeException: java.lang.ClassNotFoundException: $Proxy9
[14:28:08]: ▸ 	at tools.fastlane.screengrab.locale.LocaleUtil.changeDeviceLocaleTo(LocaleUtil.java:52)
[14:28:08]: ▸ 	at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:30)
[14:28:08]: ▸ 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
[14:28:08]: ▸ 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[14:28:08]: ▸ 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[14:28:08]: ▸ 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[14:28:08]: ▸ 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[14:28:08]: ▸ 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
[14:28:08]: ▸ 	at org.junit.runners.Suite.runChild(Suite.java:128)
[14:28:08]: ▸ 	at org.junit.runners.Suite.runChild(Suite.java:27)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[14:28:08]: ▸ 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[14:28:08]: ▸ 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[14:28:08]: ▸ 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[14:28:08]: ▸ 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[14:28:08]: ▸ 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
[14:28:08]: ▸ 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
```

Not a Fenix issue, but I want somewhere to track this (Fastlane https://github.com/fastlane/fastlane/issues/19521).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20815)

**Comment by AaronMT** [comment]
This is due to LeakCanary on debug

https://github.com/fastlane/fastlane/issues/19521#issuecomment-1170017435

> We have the same issue, and after investigating, we found out that this is not a bug of screengrab, but instead it was a conflict with LeakCanary.
LeakCanary replaces the default IActivityManager with with a proxy instance [here](https://github.com/square/leakcanary/blob/013c7fdd9069e0895a676b0a16a1737691b324a7/leakcanary-object-watcher-android-core/src/main/java/leakcanary/ServiceWatcher.kt#L80-L103), which causes the ClassNotFoundException when screengrab tries to [access](https://github.com/fastlane/fastlane/blob/019bad7f9ded480c41ae6d36320aa940f90ec108/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/locale/LocaleUtil.java#L39) it using reflection.
 

> So check if you are using LeakCanary or check for other libraries that may be doing the same thing.

> For LeakCanary, the fix is to avoid installing it on test builds, for now, we are doing it by using leakcanary-android-core artifact, and handling the initialization manually on non-test builds, but I believe there are other ways to handle this by using a specific testBuildType.
