### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. startBrowsingButtonTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25781]
### Firebase Test Run: 💥 Failed 1x 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6944795685142319592/executions/bs.eb79d43b236d01c1/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6944795685142319592/executions/bs.6ce963896a9e95f8/testcases/1/test-cases)
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.fenix.debug:id/finish_button]
	at androidx.test.uiautomator.UiObject.getBounds(UiObject.java:911)
	at androidx.test.uiautomator.UiScrollable.ensureFullyVisible(UiScrollable.java:294)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.startBrowsingButton(HomeScreenRobot.kt:716)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertStartBrowsingButton(HomeScreenRobot.kt:617)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertStartBrowsingButton(HomeScreenRobot.kt:1)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyStartBrowsingButton(HomeScreenRobot.kt:135)
	at org.mozilla.fenix.ui.SmokeTest$startBrowsingButtonTest$1.invoke(SmokeTest.kt:184)
	at org.mozilla.fenix.ui.SmokeTest$startBrowsingButtonTest$1.invoke(SmokeTest.kt:183)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:420)
	at org.mozilla.fenix.ui.SmokeTest.startBrowsingButtonTest(SmokeTest.kt:183)
    
### Build: 6/28 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20821)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month
