### ISSUE TITLE
Intermittent UI test failure - < SitePermissionsTest. allowNotificationsPermissionPromptTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25796]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SitePermissionsRobot.verifyNotificationsPermissionPrompt(SitePermissionsRobot.kt:68)
	at org.mozilla.fenix.ui.robots.SitePermissionsRobot.verifyNotificationsPermissionPrompt$default(SitePermissionsRobot.kt:66)
	at org.mozilla.fenix.ui.SitePermissionsTest$allowNotificationsPermissionPromptTest$3.invoke(SitePermissionsTest.kt:253)
	at org.mozilla.fenix.ui.SitePermissionsTest$allowNotificationsPermissionPromptTest$3.invoke(SitePermissionsTest.kt:252)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.clickOpenNotificationButton(BrowserRobot.kt:859)
	at org.mozilla.fenix.ui.SitePermissionsTest.allowNotificationsPermissionPromptTest(SitePermissionsTest.kt:252)
    
### Build: 6/28 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20836)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/5 Main 

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SitePermissionsRobot.verifyNotificationsPermissionPrompt(SitePermissionsRobot.kt:68)
	at org.mozilla.fenix.ui.robots.SitePermissionsRobot.verifyNotificationsPermissionPrompt$default(SitePermissionsRobot.kt:66)
	at org.mozilla.fenix.ui.SitePermissionsTest$allowNotificationsPermissionPromptTest$3.invoke(SitePermissionsTest.kt:281)
	at org.mozilla.fenix.ui.SitePermissionsTest$allowNotificationsPermissionPromptTest$3.invoke(SitePermissionsTest.kt:280)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.clickOpenNotificationButton(BrowserRobot.kt:859)
	at org.mozilla.fenix.ui.SitePermissionsTest.allowNotificationsPermissionPromptTest(SitePermissionsTest.kt:280)
