### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. openMainMenuSettingsItemTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25800]
### Stacktrace:
06-28 18:23:14.055: W/ActivityManager(478): Crash of app org.mozilla.fenix running instrumentation ComponentInfo{org.mozilla.fenix.test/androidx.test.runner.AndroidJUnitRunner}
06-28 18:23:14.076: I/ActivityManager(478): Force stopping org.mozilla.fenix appid=10152 user=0: finished inst
06-28 18:23:14.076: I/ActivityManager(478): Killing 13386:org.mozilla.fenix:tab14/u0a152 (adj 0): stop org.mozilla.fenix due to finished inst
06-28 18:23:14.077: W/Binder(12860): Caught a RuntimeException from the binder stub implementation.
06-28 18:23:14.077: W/Binder(12860): java.lang.SecurityException: Calling from not trusted UID!
06-28 18:23:14.077: W/Binder(12860): 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525)
06-28 18:23:14.077: W/Binder(12860): 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
06-28 18:23:14.077: W/Binder(12860): 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390)
06-28 18:23:14.077: W/Binder(12860): 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-28 18:23:14.077: W/Binder(12860): 	at android.os.Binder.execTransact(Binder.java:1123)
06-28 18:23:14.077: I/ActivityManager(478): Killing 13484:org.mozilla.fenix:gpu/u0a152 (adj 0): stop org.mozilla.fenix due to finished inst
06-28 18:23:14.078: I/Zygote(291): Process 13386 exited cleanly (0)
06-28 18:23:14.078: I/WindowManager(478):   Force finishing activity ActivityRecord{7b7bfcd u0 org.mozilla.fenix/.HomeActivity t9 f} isExiting}
06-28 18:23:14.078: W/ActivityTaskManager(478): Duplicate finish request for r=ActivityRecord{7b7bfcd u0 org.mozilla.fenix/.HomeActivity t9 f} isExiting}
06-28 18:23:14.086: D/AndroidRuntime(12860): Shutting down VM
### Notes: Similar with #24047

**Comment by AndiAJ** [comment]
Closing in favour of #25926
