### ISSUE TITLE
Intermittent UI test failure - < BookmarksTest. multipleBookmarkDeletionsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25907]
### Stacktrace:
java.lang.NoClassDefFoundError: org.mozilla.fenix.ui.robots.HomeScreenRobotKt
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(Unknown Source:0)
	at org.mozilla.fenix.ui.BookmarksTest.multipleBookmarkDeletionsTest(BookmarksTest.kt:503)
	... 34 trimmed
Caused by: java.lang.ExceptionInInitializerError
	... 37 more
Caused by: java.lang.IllegalStateException: UiAutomation not connected, UiAutomation@f0a4fc3[id=-1, flags=0]
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1239)
	at android.app.UiAutomation.getServiceInfo(UiAutomation.java:497)
	at androidx.test.uiautomator.UiDevice.<init>(UiDevice.java:115)
	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.<clinit>(HomeScreenRobot.kt:424)
	... 37 more
    
### Notes: Similar with: #25416 #25414 #25342 #25341 #25453 #25468 #25579 #25578 #25624 #25625 #25628 #25630 #25642 #25655 #25656 #25657 #25700 #25711 #25713 #25714 #25715 #25716 #25727 #25742 #25747 #25762 #25763 #25779 #25798 #25830 #25853 #25903

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20920)

**Comment by AndiAJ** [comment]
Closing in favour of #25924
