### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest.saveLoginsInPWATest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25921]
### Stacktrace:
androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@ab41e9f, window-token=android.view.ViewRootImpl$W@ab41e9f, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=INVISIBLE, width=1080, height=1920, has-focus=true, has-focusable=false, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f14034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:710)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:606)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:598)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:598)
    
### Build: 7/7 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20937)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 8/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8418839253415243456/executions/bs.7dd7ea689f62e3ae/testcases/1/test-cases)

androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@d40051a, window-token=android.view.ViewRootImpl$W@d40051a, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f13034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=INVISIBLE, width=1080, height=1920, has-focus=true, has-focusable=false, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f13034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:710)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:647)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:639)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:639)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5488632995933379087/executions/bs.6786e3377bcdacda/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsDisplayed(BrowserRobot.kt:666)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:643)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:640)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:640)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6334610519521053713/executions/bs.839efc32ca242c74/testcases/1/test-cases)

androidx.test.espresso.PerformException: Error performing 'single click' on view '(view.getContentDescription() is "Menu")'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:710)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:648)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:640)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:640)
	... 33 trimmed
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)
Target view: "AppCompatImageView{id=2131296965, res-name=icon, desc=Menu, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@a3f7b73, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}"
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:20)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5102202898759840953/executions/bs.8ff34d45c3e225fe/testcases/1/test-cases)

androidx.test.espresso.PerformException: Error performing 'single click' on view '(view.getContentDescription() is "Menu")'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:710)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:648)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:640)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:640)
	... 33 trimmed
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)
Target view: "AppCompatImageView{id=2131296965, res-name=icon, desc=Menu, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@5a97b70, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}"
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:20)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8442961684888781781/executions/bs.1a0755c9e9e6cb03/testcases/1/test-cases)

androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@5c3bca8, window-token=android.view.ViewRootImpl$W@5c3bca8, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f13034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=INVISIBLE, width=1080, height=1920, has-focus=true, has-focusable=false, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f13034f
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_STATUS_BAR LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:750)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:648)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:640)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:640)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8268278885395658076/executions/bs.edf75f329f5f5c98/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:232)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:703)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:702)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:702)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6027500735658614405/executions/bs.e3ae535e95c319ed/testcases/2/test-cases)

androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
Root{application-window-token=android.view.ViewRootImpl$W@24b3181, window-token=android.view.ViewRootImpl$W@24b3181, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f130350
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_NAVIGATION_BAR
  fitSides=}, decor-view-string=DecorView{id=-1, visibility=INVISIBLE, width=1080, height=1920, has-focus=true, has-focusable=false, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(0,0)(fillxfill) sim={state=always_hidden adjust=resize} ty=BASE_APPLICATION wanim=0x7f130350
  fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
  pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
  vsysui=LIGHT_NAVIGATION_BAR
  fitSides=}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:799)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:699)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:691)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:691)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5516308132556840495/executions/bs.5c5316e97226b197/testcases/3/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:238)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:677)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$2.invoke(SettingsPrivacyTest.kt:676)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:676)

**Comment by AndiAJ** [comment]
Closing, it didn't fail for more than a month.
