### ISSUE TITLE
Intermittent UI test failure - legacy-x86 - rememberBlockAudioVideoPermissionChoiceTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25972]
See also #25971 

### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8616102722980811149/executions/bs.726f5b576808efe2/testcases/1/test-cases
### Stacktrace:
```
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:107)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:862)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:107)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/3a8ad63850913b5882ffab6bb28195a4f9dd73af

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20965)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7055228040257761939/executions/bs.8ba15eacbecc021f/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:107)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:107)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/25 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5452196243614052552/executions/bs.a8dcea66de94c17f/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:108)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/27 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8703931938252808631/executions/bs.fa7b36bb0ba76491/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8703931938252808631/executions/bs.7bac61775493edc4/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:108)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8976479091284768305/executions/bs.6e23aa17605c2034/testcases/1/test-cases)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/19 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6571573194005314602/executions/bs.1c8ba2a12ee9a1d6/testcases/1)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6571573194005314602/executions/bs.4ce7146f1452c48d/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:108)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7488465860309332299/executions/bs.b136e61a2f14ec8a/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:108)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:108)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8587098337730470729/executions/bs.cc4f561985d4c533/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:110)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:947)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:109)
    
Flaky 1x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8661649586292534263/executions/bs.f195283d4a2ba245/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:110)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:109)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:947)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:109)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/26 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5896318238990645730/executions/bs.8cfc0ee3299e4c84/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:103)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberBlockAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:102)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:977)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberBlockAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:102)

**Comment by sv-ohorvath** [comment]
I switched the test to run again on API 30 with ARM, I'll close this as fixed, but can be reopened again if it still fails.
