### ISSUE TITLE
Intermittent UI test failure - < SettingsAddonsTest.installAddonTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25973]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonInstallCompleted(SettingsSubMenuAddonsManagerRobot.kt:67)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:96)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:83)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:361)
	at org.mozilla.fenix.ui.SettingsAddonsTest.installAddonTest(SettingsAddonsTest.kt:83)
    
### Build: 7/8 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20968)

**Comment by sv-ohorvath** [comment]
closed in favor of https://github.com/mozilla-mobile/fenix/issues/26105
