### ISSUE TITLE
Intermittent UI test failure - deleteCollectionTest - androidx.test.uiautomator.UiObjectNotFoundException 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25970]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/5379394058481151477/executions/bs.1dbb94fa785585b/testcases/1
### Stacktrace:
```
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=VIEW, RESOURCE_ID=org.mozilla.fenix:id/snackbar_btn]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.TabDrawerRobot.snackBarButtonClick(TabDrawerRobot.kt:144)
	at org.mozilla.fenix.ui.CollectionTest$deleteCollectionTest$3.invoke(CollectionTest.kt:219)
	at org.mozilla.fenix.ui.CollectionTest$deleteCollectionTest$3.invoke(CollectionTest.kt:217)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openTabDrawer(BrowserRobot.kt:733)
	at org.mozilla.fenix.ui.CollectionTest.deleteCollectionTest(CollectionTest.kt:217)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/14ee00303b495f152f43cd7d7cea5cc2f1329ee5

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20963)

**Comment by AndiAJ** [comment]
Failed 1x on 7/19 **Nightly** [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/8230139520200612143/executions/bs.89f6d09989422a43/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true, RESOURCE_ID=org.mozilla.fenix:id/sessionControlRecyclerView]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollToEnd(UiScrollable.java:595)
	at androidx.test.uiautomator.UiScrollable.scrollToEnd(UiScrollable.java:614)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.expandCollection(HomeScreenRobot.kt:396)
	at org.mozilla.fenix.ui.CollectionTest.deleteCollectionTest(CollectionTest.kt:223)

**Comment by sv-ohorvath** [comment]
Did a new trial run to see the state of the test: https://github.com/mozilla-mobile/fenix/runs/7428221077
Nothing outstanding, I think we can ignore the failure, for now, and see if it comes up again.

**Comment by AndiAJ** [comment]
Failed 1x on 7/22 Nightly [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.80a1a071cfb2770e/matrices/5342964478331277333/executions/bs.6ea276b6485dddd1/testcases/1)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true, RESOURCE_ID=org.mozilla.fenix:id/sessionControlRecyclerView]
	at androidx.test.uiautomator.UiScrollable.scrollForward(UiScrollable.java:417)
	at androidx.test.uiautomator.UiScrollable.scrollToEnd(UiScrollable.java:595)
	at androidx.test.uiautomator.UiScrollable.scrollToEnd(UiScrollable.java:614)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.expandCollection(HomeScreenRobot.kt:396)
	at org.mozilla.fenix.ui.CollectionTest.deleteCollectionTest(CollectionTest.kt:223)

**Comment by sv-ohorvath** [comment]
I landed a potential fix, we'll see how it goes, this issue can be reopened if it fails again.
