### ISSUE TITLE
Intermittent UI Test failure - legacy-x86 - rememberAllowAudioVideoPermissionChoiceTest

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#25971]
### Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8026323383195407621/executions/bs.f4841ba8f5a4ada/testcases/1/test-cases
### Stacktrace:
```
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:131)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:862)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:131)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/279efffd9b7ab642bd3afd15887a579f1bd8da23

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20964)

**Comment by AndiAJ** [comment]
Failed 1x on 7/15 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7055228040257761939/executions/bs.9f6f64c640fbbd14/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:131)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:131)
    

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7055228040257761939/executions/bs.3b7cd8977e7369f7/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:131)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:131)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7774601605074933781/executions/bs.ab3bd0270a1ad217/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:132)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6402441778388697976/executions/bs.df26a2283bc13636/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:132)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6546754286172828085/executions/bs.d5ecbbacd2ab3f8b/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:132)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:863)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:132)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6923361566729279423/executions/bs.2e6e889c8a46fcca/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:134)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:947)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:133)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6602131390530195638/executions/bs.e9c43e06b3a3e6b/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:134)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:947)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:133)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6391180727540463565/executions/bs.81c43ebe879e7a4d/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:134)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:133)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:960)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:133)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6959470602703678757/executions/bs.8720bdbde5694834/testcases/1/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:127)
	at org.mozilla.fenix.ui.SitePermissionsTest$rememberAllowAudioVideoPermissionChoiceTest$8.invoke(SitePermissionsTest.kt:126)
	at org.mozilla.fenix.ui.robots.BrowserRobotKt.browserScreen(BrowserRobot.kt:991)
	at org.mozilla.fenix.ui.SitePermissionsTest.rememberAllowAudioVideoPermissionChoiceTest(SitePermissionsTest.kt:126)
