### ISSUE TITLE
Intermittent UI test failure - < NavigationToolbarTest. goBackTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#25990]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:66)
	at org.mozilla.fenix.ui.NavigationToolbarTest$goBackTest$6.invoke(NavigationToolbarTest.kt:68)
	at org.mozilla.fenix.ui.NavigationToolbarTest$goBackTest$6.invoke(NavigationToolbarTest.kt:66)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.goBack(ThreeDotMenuMainRobot.kt:242)
	at org.mozilla.fenix.ui.NavigationToolbarTest.goBackTest(NavigationToolbarTest.kt:66)
    
### Build: 7/11 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20982)

**Comment by AndiAJ** [comment]
Closing, didn't fail for approx. a month.
