### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest.selectNewDefaultSearchEngine>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26042]
### Stacktrace:
07-14 18:20:16.577: D/AndroidRuntime(13969): Shutting down VM
07-14 18:20:16.577: I/Finsky(9762): [2] qmo.O(7): Installer: found apps to install. isMultiUserMode=false, apps=[]
07-14 18:20:16.577: I/Finsky(9762): --------- beginning of crash
07-14 18:20:16.578: E/AndroidRuntime(13969): FATAL EXCEPTION: main
07-14 18:20:16.578: E/AndroidRuntime(13969): Process: org.mozilla.fenix.debug:tab4, PID: 13969
07-14 18:20:16.578: E/AndroidRuntime(13969): java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6738)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.os.Looper.loop(Looper.java:223)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at java.lang.reflect.Method.invoke(Native Method)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-14 18:20:16.578: E/AndroidRuntime(13969): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-14 18:20:16.579: I/InputReader(476): Reconfiguring input devices, changes=KEYBOARD_LAYOUTS | 
07-14 18:20:16.581: V/AvrcpMediaPlayerList(1589): mPackageChangedBroadcastReceiver: action: android.intent.action.PACKAGE_REMOVED
07-14 18:20:16.588: I/GsaVoiceInteractionSrv(3167): O received Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.google.android.gms flg=0x4000010 (has extras) }
07-14 18:20:16.590: I/ActivityManager(476): Force stopping org.mozilla.fenix.debug appid=10152 user=-1: deletePackageX
07-14 18:20:16.590: I/ActivityManager(476): Killing 13907:org.mozilla.fenix.debug/u0a152 (adj 250): stop org.mozilla.fenix.debug due to deletePackageX
07-14 18:20:16.593: I/ActivityManager(476): Killing 13969:org.mozilla.fenix.debug:tab4/u0a152 (adj 0): stop org.mozilla.fenix.debug due to deletePackageX
07-14 18:20:16.610: I/ActivityManager(476): Killing 14016:org.mozilla.fenix.debug:gpu/u0a152 (adj 0): stop org.mozilla.fenix.debug due to deletePackageX
07-14 18:20:16.629: W/Finsky(9762): [861] qxt.call(45): Cannot find installStatus. Using status from installer: status=# qqo@edf6361a
07-14 18:20:16.629: I/Finsky(9762): [861] rab.C(2): IQ: Notifying installation update. package=org.mozilla.fenix.debug.test, status=UNINSTALLED
07-14 18:20:16.644: I/Zygote(288): Process 14052 exited due to signal 9 (Killed)
07-14 18:20:16.662: I/Zygote(288): Process 14016 exited due to signal 9 (Killed)
07-14 18:20:16.608: I/chatty(0): uid=0(root) logd identical 31917 lines
07-14 18:20:16.609: D/logd(0): Skipping 256 entries from slow reader, pid 13904, from LogBuffer::kickMe()
07-14 18:20:16.708: I/binder(0): release 14016:14016 transaction 1003501 out, still active
07-14 18:20:16.709: I/binder(0): undelivered TRANSACTION_COMPLETE
07-14 18:20:16.709: D/logd(0): Skipping 256 entries from slow reader, pid 13904, from LogBuffer::kickMe()
07-14 18:20:16.683: I/Zygote(288): Process 13907 exited due to signal 9 (Killed)
07-14 18:20:16.685: I/libprocessgroup(476): Successfully killed process cgroup uid 10097 pid 14052 in 187ms
07-14 18:20:16.699: I/Zygote(288): Process 13969 exited due to signal 9 (Killed)
07-14 18:20:16.710: I/chatty(0): uid=0(root) logd identical 5 lines
07-14 18:20:16.710: D/logd(0): Skipping 256 entries from slow reader, pid 13904, from LogBuffer::kickMe()
07-14 18:20:16.744: I/binder(0): undelivered transaction 1003426, process died.
07-14 18:20:16.745: I/binder(0): undelivered transaction 1003427, process died.
07-14 18:20:16.746: I/binder(0): undelivered transaction 1003428, process died.

### Build: 7/14 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21023)

**Comment by AndiAJ** [comment]
Closing, didn't fail for approx. a month.
