### ISSUE TITLE
[Bug]: The connection has timed out

### ISSUE THREAD

**Issue by rettichschnidi** [mozilla-mobile/fenix#26086]
### Steps to reproduce

1. Open Firefox
2. Try to open wikipedia.org (or literally any other page)
3. "The connection has timed out" gets displayed

### Expected behaviour

Firefox can load web pages

### Actual behaviour

Pages does not load, and after a while, "The connection has timed out" gets displayed

### Device name

Xiaomi Mi A1

### Android version

Android 10 (Lineage OS 17.1-20210810-NIGHLY-tissot)

### Firefox release type

Firefox

### Firefox version

102.1.1 (Build #2015887771)

### Device logs
```
$ grep 15274 2022-06-18-Firefox-fail-2.txt
06-18 12:22:26.926  2231  2231 D Zygote  : Forked child process 15274
06-18 12:22:26.929  2713  2856 I ActivityManager: Start proc 15274:org.mozilla.firefox/u0a132 for pre-top-activity {org.mozilla.firefox/org.mozilla.firefox.App}
06-18 12:22:27.029 15274 15274 I FirebaseInitProvider: FirebaseApp initialization successful
06-18 12:22:27.029 15274 15300 E FirebaseInstanceId: Google Play services missing or without correct permission.
06-18 12:22:27.131 15274 15305 I libglean_ffi: glean_core: Creating new Glean v44.1.1
06-18 12:22:27.132 15274 15305 I libglean_ffi: glean_core::database: Database initialized
06-18 12:22:27.134 15274 15305 I libglean_ffi: glean_ffi: Glean initialized
06-18 12:22:27.137 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/b7d69189-41f7-4e6b-9afa-4387aa56b2c9
06-18 12:22:27.137 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/a4ffb6f7-b4c3-429b-adb3-0f0aad5d85ff
06-18 12:22:27.137 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/68ea4d6f-3a9f-4b19-a2a0-71f13acd4f58
06-18 12:22:27.137 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/ae229d0a-cea0-4c14-bb9f-0de69c81da4c
06-18 12:22:27.138 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/48ff9812-b756-4c81-9273-1cc6ea58cfd3
06-18 12:22:27.138 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/2cf8dfe3-971b-444d-af97-8ddccbac5b17
06-18 12:22:27.138 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/4d4c0631-6c95-4c23-a651-45c7ef7b6145
06-18 12:22:27.138 15274 15306 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/4435870c-ac0b-44c3-abde-65b3ed6334ec
06-18 12:22:27.138 15274 15305 I glean/Dispatchers: Task queued for execution and delayed until flushed
06-18 12:22:27.140 15274 15305 I chatty  : uid=10132(org.mozilla.firefox) GleanAPIPool identical 2 lines
06-18 12:22:27.141 15274 15305 I glean/Dispatchers: Task queued for execution and delayed until flushed
06-18 12:22:27.145 15274 15305 I glean/MetricsPingSched: The 'metrics' ping was already sent today, 1655547747142.
06-18 12:22:27.154 15274 15309 I GeckoThread: preparing to run Gecko
06-18 12:22:27.166 15274 15309 I GeckoLoader: Library base=/data/app/org.mozilla.firefox-tit5xOenondO-ouVurSo3g==/lib/arm64
06-18 12:22:27.168 15274 15309 W Settings: Setting animator_duration_scale has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only global URI.
06-18 12:22:27.170 15274 15309 I GeckoLoader: Library base=/data/app/org.mozilla.firefox-tit5xOenondO-ouVurSo3g==/lib/arm64
06-18 12:22:27.171 15274 15309 E GeckoLibLoad: Load sqlite start
06-18 12:22:27.172 15274 15309 E GeckoLibLoad: Load sqlite done
06-18 12:22:27.172 15274 15309 I GeckoLoader: Library base=/data/app/org.mozilla.firefox-tit5xOenondO-ouVurSo3g==/lib/arm64
06-18 12:22:27.172 15274 15309 E GeckoLibLoad: Load nss start
06-18 12:22:27.172 15274 15309 E GeckoLibLoad: Load nss done
06-18 12:22:27.172 15274 15309 I GeckoLoader: Library base=/data/app/org.mozilla.firefox-tit5xOenondO-ouVurSo3g==/lib/arm64
06-18 12:22:27.173 15274 15309 E GeckoLibLoad: Loaded libs in 0.629271ms total, 0ms(3ms) user, 0ms(0ms) system, 0(0) faults
06-18 12:22:27.175 15274 15309 W GeckoThread: zerdatime 942043 - runGecko
06-18 12:22:27.240 15274 15309 I Gecko:DumpUtils: Fifo watcher disabled via pref.
06-18 12:22:27.269 15274 15326 I rc_log_ffi::ios: rc_log adapter initialized!
06-18 12:22:27.280 15274 15309 W mozilla.firefo: Accessing hidden field Ljava/lang/Boolean;->value:Z (greylist-max-p, JNI, denied)
06-18 12:22:27.280 15274 15309 W mozilla.firefo: Accessing hidden field Ljava/lang/Integer;->value:I (greylist-max-p, JNI, denied)
06-18 12:22:27.280 15274 15309 W mozilla.firefo: Accessing hidden field Ljava/lang/Double;->value:D (greylist-max-p, JNI, denied)
06-18 12:22:27.309 15274 15349 I nimbus  : fetching experiments
06-18 12:22:27.309 15274 15348 I nimbus::persistence: Already at version 2, no upgrade needed
06-18 12:22:27.309 15274 15349 I viaduct::backend: Using HTTP backend FFI (trusted)
06-18 12:22:27.309 15274 15348 I nimbus  : [Nimbus] Retrieved date from Context: 2022-06-18 10:15:20 UTC
06-18 12:22:27.310 15274 15348 I nimbus  : [Nimbus] Installation Date: 2022-06-18 10:15:20 UTC
06-18 12:22:27.310 15274 15348 I nimbus  : [Nimbus] Update Date: 2022-06-18 10:16:52.515325129 UTC
06-18 12:22:27.310 15274 15348 I nimbus  : [Nimbus] Days since install: 0
06-18 12:22:27.310 15274 15348 I nimbus  : [Nimbus] Days since update: 0
06-18 12:22:27.311 15274 15305 I libglean_ffi: glean_core: Upload enabled: true
06-18 12:22:27.320 15274 15348 I nimbus  : updating experiment list
06-18 12:22:27.326 15274 15274 I App     : AutoPushFeature is configured, initializing it...
06-18 12:22:27.328 15274 15274 I AbstractFirebasePushService: start
06-18 12:22:27.365 15274 15348 I nimbus  : [Nimbus] Retrieved date from Context: 2022-06-18 10:15:20 UTC
06-18 12:22:27.365 15274 15348 I nimbus  : [Nimbus] Installation Date: 2022-06-18 10:15:20 UTC
06-18 12:22:27.366 15274 15348 I nimbus  : [Nimbus] Update Date: 2022-06-18 10:16:52.515325129 UTC
06-18 12:22:27.366 15274 15348 I nimbus  : [Nimbus] Days since install: 0
06-18 12:22:27.366 15274 15348 I nimbus  : [Nimbus] Days since update: 0
06-18 12:22:27.480 15274 15274 I NavController: Ignoring popBackStack to destination org.mozilla.firefox:id/browserFragment as it was not found on the current back stack
06-18 12:22:27.491 15274 15274 I service-pocket: Scheduling pocket recommendations background refresh
06-18 12:22:27.567 15274 15309 I AdrenoGLES: QUALCOMM build                   : 7331a27, Ieeb4a86f7b
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Build Date                       : 11/13/19
06-18 12:22:27.567 15274 15309 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Local Branch                     : 
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Remote Branch                    : 
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Remote Branch                    : 
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Reconstruct Branch               : 
06-18 12:22:27.567 15274 15309 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
06-18 12:22:27.572 15274 15309 I AdrenoGLES: PFP: 0x005ff087, ME: 0x005ff063
06-18 12:22:27.575 15274 15309 W AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
06-18 12:22:27.576 15274 15309 W AdrenoUtils: <ReadGpuID:218>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
06-18 12:22:27.573 15274 15274 W Gecko   : type=1400 audit(0.0:546): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=30572 scontext=u:r:untrusted_app:s0:c132,c256,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0 app=org.mozilla.firefox
06-18 12:22:27.600 15274 15405 I AdrenoGLES: QUALCOMM build                   : 7331a27, Ieeb4a86f7b
06-18 12:22:27.600 15274 15405 I AdrenoGLES: Build Date                       : 11/13/19
06-18 12:22:27.600 15274 15405 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
06-18 12:22:27.600 15274 15405 I AdrenoGLES: Local Branch                     : 
06-18 12:22:27.600 15274 15405 I AdrenoGLES: Remote Branch                    : 
06-18 12:22:27.600 15274 15405 I AdrenoGLES: Remote Branch                    : 
06-18 12:22:27.600 15274 15405 I AdrenoGLES: Reconstruct Branch               : 
06-18 12:22:27.601 15274 15405 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
06-18 12:22:27.610 15274 15405 I AdrenoGLES: PFP: 0x005ff087, ME: 0x005ff063
06-18 12:22:27.648 15274 15423 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-18 12:22:27.648 15274 15274 I StartupTypeTelemetry: Recorded start up: cold_main
06-18 12:22:27.646 15274 15274 W Adjust-pool-27-: type=1400 audit(0.0:547): avc: denied { search } for name="net" dev="sysfs" ino=23313 scontext=u:r:untrusted_app:s0:c132,c256,c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0 app=org.mozilla.firefox
06-18 12:22:27.662 15274 15274 I Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
06-18 12:22:27.701 15274 15375 W Gralloc3: mapper 3.x is not supported
06-18 12:22:27.711 15274 15305 I libglean_ffi: glean_core::ping: Collecting baseline
06-18 12:22:27.716 15274 15305 I libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.firefox/glean_data/pending_pings/6a708cff-2949-49c3-a64c-f2493e24b9db
06-18 12:22:27.717 15274 15305 I libglean_ffi: glean_core: The ping 'baseline' was submitted and will be sent as soon as possible
06-18 12:22:27.754  2713  4448 W ActivityManager: Receiver with filter android.content.IntentFilter@750686d already registered for pid 15274, callerPackage is org.mozilla.firefox
06-18 12:22:27.864 15274 15274 I BgSyncManager: Periodic syncing enabled: PeriodicSyncConfig(periodMinutes=240, initialDelayMinutes=5)
06-18 12:22:27.864 15274 15274 I FirefoxAccountStateMachine: Sync is enabled
06-18 12:22:27.971 15274 15463 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Account$Start@8be481' for state Idle(accountState=NotAuthenticated). Next state is Active(progressState=Initializing)
06-18 12:22:27.997 15274 15463 I FirefoxAccount: Registering persistence callback
06-18 12:22:27.997 15274 15463 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Account$Start@8be481' side-effects for state Active(progressState=Initializing), got successive event mozilla.components.service.fxa.manager.Event$Progress$AccountNotFound@d7d7f6b
06-18 12:22:27.998 15274 15463 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$AccountNotFound@d7d7f6b' for state Active(progressState=Initializing). Next state is Idle(accountState=NotAuthenticated)
06-18 12:22:28.028 15274 15274 I DefaultSupportedAddonsChecker: Unregister check for new supported add-ons
06-18 12:22:28.037  2713  4448 D ConnectivityService: requestNetwork for uid/pid:10132/15274 NetworkRequest [ TRACK_DEFAULT id=79, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10132] ]
06-18 12:22:28.091 15274 15274 I WebExtension: releasePendingMessages: extension=fxa@mozac.org nativeApp=mozacWebchannelBackground session=null
06-18 12:22:28.094 15274 15274 I WebExtension: releasePendingMessages: extension=readerview@mozac.org nativeApp=mozacReaderviewActive session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.094 15274 15274 I WebExtension: releasePendingMessages: extension=readerview@mozac.org nativeApp=mozacReaderview session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.096 15274 15274 I WebExtension: releasePendingMessages: extension=fxa@mozac.org nativeApp=mozacWebchannel session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.126 15274 15274 I WebExtension: releasePendingMessages: extension=readerview@mozac.org nativeApp=mozacReaderviewActive session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.126 15274 15274 I WebExtension: releasePendingMessages: extension=readerview@mozac.org nativeApp=mozacReaderview session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.171 15274 15274 I WebExtension: releasePendingMessages: extension=icons@mozac.org nativeApp=MozacBrowserIcons session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.172 15274 15274 I WebExtension: releasePendingMessages: extension=ads@mozac.org nativeApp=MozacBrowserAdsMessage session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.173 15274 15274 I WebExtension: releasePendingMessages: extension=cookies@mozac.org nativeApp=MozacBrowserSearchMessage session=org.mozilla.geckoview.GeckoSession@1053a96
06-18 12:22:28.216 15274 15309 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
06-18 12:22:28.218 15274 15309 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
06-18 12:22:28.226 15274 15309 W Utils   : could not parse long range '175-174'
06-18 12:22:28.273 15274 15309 I GeckoSession: zerdatime 943140 - chrome startup finished
06-18 12:22:28.282 15274 15274 I GeckoSession: handleMessage GeckoView:PageStart uri=
06-18 12:22:28.284 15274 15274 I GeckoSession: handleMessage GeckoView:PageStop uri=null
06-18 12:22:28.331 15274 15309 D GeckoIdleService: Registering Idle observer callback
06-18 12:22:28.331 15274 15309 D GeckoIdleService: Register idle observer 0x7120337f20 for 180 seconds
06-18 12:22:28.331 15274 15309 D GeckoIdleService: Register: adjusting next switch from -1 to 180 seconds
06-18 12:22:28.331 15274 15309 D GeckoIdleService: next timeout 180000 msec from now
06-18 12:22:28.331 15274 15309 D GeckoIdleService: SetTimerExpiryIfBefore: next timeout 180000 msec from now
06-18 12:22:28.332 15274 15309 D GeckoIdleService: reset timer expiry to 180010 msec from now
06-18 12:22:28.332 15274 15309 D GeckoIdleService: Register idle observer 0x712032d1a8 for 5 seconds
06-18 12:22:28.332 15274 15309 D GeckoIdleService: Register: adjusting next switch from 180 to 5 seconds
06-18 12:22:28.332 15274 15309 D GeckoIdleService: next timeout 5000 msec from now
06-18 12:22:28.332 15274 15309 D GeckoIdleService: SetTimerExpiryIfBefore: next timeout 5000 msec from now
06-18 12:22:28.332 15274 15309 D GeckoIdleService: reset timer expiry to 5010 msec from now
06-18 12:22:28.430 15274 15274 I GeckoSession: handleMessage GeckoView:PageStart uri=
06-18 12:22:29.393 15274 15274 W GeckoSession: No history entries found.
06-18 12:22:32.696 15274 15274 I glean/Glean: Registering pings for org.mozilla.fenix.GleanMetrics.Pings
06-18 12:22:32.705 15274 15333 I FenixApplication: Running post-visual completeness tasks...
06-18 12:22:32.705 15274 15333 I FenixApplication: Storage initialization...
06-18 12:22:32.705 15274 15333 I PlacesHistoryStorage: Warming up places storage...
06-18 12:22:32.708 15274 15274 I ColdStartupDuration: COLD MAIN Application.<init> to first frame: 689 ms
06-18 12:22:32.708 15274 15274 I FenixApplication: Kicking-off account manager...
06-18 12:22:32.708 15274 15274 I FenixApplication: 'Kicking-off account manager' took 0 ms
06-18 12:22:32.724 15274 15333 I PlacesHistoryStorage: 'Warming up places storage' took 17 ms
06-18 12:22:32.724 15274 15333 I PlacesBookmarksStorage: Warming up places storage...
06-18 12:22:32.724 15274 15333 I PlacesBookmarksStorage: 'Warming up places storage' took 0 ms
06-18 12:22:32.725 15274 15333 I SyncableLoginsStorage: Warming up storage...
06-18 12:22:32.745 15274 15333 W logins::schema: user_version: 1
06-18 12:22:32.746 15274 15333 I SyncableLoginsStorage: 'Warming up storage' took 20 ms
06-18 12:22:32.747 15274 15333 I AutofillCCAddressesStorage: Warming up storage...
06-18 12:22:32.776 15274 15333 I AutofillCCAddressesStorage: 'Warming up storage' took 28 ms
06-18 12:22:32.785 15274 15333 I FenixApplication: 'Storage initialization' took 79 ms
06-18 12:22:33.342 15274 15309 D GeckoIdleService: Get idle time: time since reset 5010 msec
06-18 12:22:33.342 15274 15309 D GeckoIdleService: Idle timer callback: current idle time 5010 msec
06-18 12:22:33.342 15274 15309 D GeckoIdleService: next timeout 174989 msec from now
06-18 12:22:33.342 15274 15309 D GeckoIdleService: SetTimerExpiryIfBefore: next timeout 174989 msec from now
06-18 12:22:33.342 15274 15309 D GeckoIdleService: reset timer expiry to 174999 msec from now
06-18 12:22:33.342 15274 15309 D GeckoIdleService: Idle timer callback: tell observer 0x712032d1a8 user is idle
06-18 12:22:37.365 15274 15349 E App     : Nimbus error: Error fetching experiments from endpoint
06-18 12:22:37.365 15274 15349 E App     : org.mozilla.experiments.nimbus.internal.NimbusException$RequestException: Error sending request: [no-sentry] Network error: Java error: "fetch error: java.net.SocketTimeoutException"
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.internal.FfiConverterTypeNimbusError$lift$1.invoke(nimbus.kt:82)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.internal.NimbusKt.liftFromRustBuffer(nimbus.kt:2)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.internal.NimbusException$ErrorHandler.lift(nimbus.kt:3)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.internal.NimbusClient.fetchExperiments(nimbus.kt:26)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.Nimbus$fetchExperimentsOnThisThread$1.invoke(Nimbus.kt:1)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.Nimbus.fetchExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
06-18 12:22:37.365 15274 15349 E App     : 	at org.mozilla.experiments.nimbus.Nimbus$fetchExperiments$1.invokeSuspend(Nimbus.kt:2)
06-18 12:22:37.365 15274 15349 E App     : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
06-18 12:22:37.365 15274 15349 E App     : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
06-18 12:22:37.365 15274 15349 E App     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 12:22:37.365 15274 15349 E App     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 12:22:37.365 15274 15349 E App     : 	at java.lang.Thread.run(Thread.java:919)
06-18 12:22:57.785 15274 15456 I SessionStorage/AutoSave: Save: Periodic
06-18 12:23:00.599 15274 15274 I GeckoSession: handleMessage GeckoView:PageStop uri=null
06-18 12:23:00.612 15274 15333 I SessionStorage/AutoSave: Save: Load finished
06-18 12:23:00.933 15274 15274 W mozilla.firefo: Core platform API violation: Ljava/nio/Buffer;->position:I from Landroid/graphics/Bitmap; using JNI
06-18 12:23:00.933 15274 15274 W mozilla.firefo: Core platform API violation: Ljava/nio/Buffer;->_elementSizeShift:I from Landroid/graphics/Bitmap; using JNI
u0_a132      15274  2231 9548188 289408 SyS_epoll_wait      0 S org.mozilla.firefox
```

### Additional information

- Firefox Beta does also not work, but nightly works (is now my daily driver, currently 104.0a1)
- Reinstalling did not help
- Issue happens on Wi-Fi as well as when connected only via mobile connection
- Every single other app in the devices has no trouble connecting to the internet

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21050)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 104.0a1 2022-07-22 but was unable to reproduce it.

### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by rettichschnidi** [comment]
> I tested the issue on Firefox Nightly 104.0a1 2022-07-22 but was unable to reproduce it.

As described in the issue, it does not happen with Firefox nightly. I will update my report to make it more clear.

This said: I in tend to upgrade my phone to a more modern, supported version of LineageOS. Would be totally OK if you'd rather investigating this issue for now and wait for my feedback once I have actually updated LineageOS.

**Comment by rettichschnidi** [comment]
This is actually no longer an issue with Firefox 109.1.1 running on my Xiaomi Mi A1/LineageOS 19-20230103-NIGHTLY-tissot.
