### ISSUE TITLE
Intermittent UI test failure - < ReaderViewTest. verifyNonReaderViewPageMenuNoDetection >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26108]
### Stacktrace:
androidx.test.espresso.IdlingResourceTimeoutException: Wait for [SessionLoadedIdlingResource] to become idle timed out
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:106)
	at org.mozilla.fenix.ui.ReaderViewTest.verifyNonReaderViewPageMenuNoDetection(ReaderViewTest.kt:102)
    
### Notes: Similar with #25881 and #25712

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21068)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
