### ISSUE TITLE
Intermittent UI test failure - SettingsAddonsTest - verifyAddonInstallCompleted fails

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26105]
Issue for keeping track of flaky tests that involve installing an add-on that fails on API30 frequently for unknown reasons and couldn't be fixed yet.

### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonInstallCompleted(SettingsSubMenuAddonsManagerRobot.kt:67)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$1.invoke(SettingsAddonsTest.kt:154)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$1.invoke(SettingsAddonsTest.kt:152)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobotKt.addonsMenu(SettingsSubMenuAddonsManagerRobot.kt:283)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:152)
    
### Build: 7/19 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21066)

**Comment by sv-ohorvath** [comment]
### Firebase Test Run: [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7537936359652306464/executions/bs.ef6b1adab79d1e78/testcases/1/test-cases)
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonInstallCompleted(SettingsSubMenuAddonsManagerRobot.kt:67)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:96)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:83)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:361)
	at org.mozilla.fenix.ui.SettingsAddonsTest.installAddonTest(SettingsAddonsTest.kt:83)
    
### Build: 7/8 Main

moved from https://github.com/mozilla-mobile/fenix/issues/25973 - closed as a duplicate.

**Comment by AndiAJ** [comment]
`installAddonTest`  flaky 1x on 7/26 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7192468813204361000/executions/bs.635983c0945b14d9/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonInstallCompleted(SettingsSubMenuAddonsManagerRobot.kt:67)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:96)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:83)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:361)
	at org.mozilla.fenix.ui.SettingsAddonsTest.installAddonTest(SettingsAddonsTest.kt:83)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8131879852987698440/executions/bs.2f0ff419148bfdc7/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.verifyAddonInstallCompleted(SettingsSubMenuAddonsManagerRobot.kt:67)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:96)
	at org.mozilla.fenix.ui.SettingsAddonsTest$installAddonTest$3.invoke(SettingsAddonsTest.kt:83)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:369)
	at org.mozilla.fenix.ui.SettingsAddonsTest.installAddonTest(SettingsAddonsTest.kt:83)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.
