### ISSUE TITLE
Intermittent UI test failure - < CollectionTest. mainMenuSaveToExistingCollection >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26129]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySnackBarText(BrowserRobot.kt:122)
	at org.mozilla.fenix.ui.CollectionTest$mainMenuSaveToExistingCollection$9.invoke(CollectionTest.kt:253)
	at org.mozilla.fenix.ui.CollectionTest$mainMenuSaveToExistingCollection$9.invoke(CollectionTest.kt:252)
	at org.mozilla.fenix.ui.robots.CollectionRobot$Transition.selectExistingCollection(CollectionRobot.kt:229)
	at org.mozilla.fenix.ui.CollectionTest.mainMenuSaveToExistingCollection(CollectionTest.kt:252)
    
### Build: 7/21 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21080)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
