### ISSUE TITLE
Intermittent UI test failure - < DownloadTest. manageDownloadsInDownloadsMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26128]
### Stacktrace:
java.lang.AssertionError: Download notification Open button not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.assertDownloadNotificationPopup(DownloadRobot.kt:161)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.access$assertDownloadNotificationPopup(DownloadRobot.kt:1)
	at org.mozilla.fenix.ui.robots.DownloadRobot.verifyDownloadNotificationPopup(DownloadRobot.kt:44)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$4.invoke(DownloadTest.kt:181)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$4.invoke(DownloadTest.kt:180)
	at org.mozilla.fenix.ui.robots.DownloadRobot$Transition.clickDownload(DownloadRobot.kt:81)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:180)
    
### Build: 7/21 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21078)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.

**Comment by AndiAJ** [comment]
Flaky 1x on 8/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8684811494654675077/executions/bs.4f086018c36ad355/testcases/1/test-cases)

java.lang.AssertionError: Download notification Open button not found
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.assertDownloadNotificationPopup(DownloadRobot.kt:161)
	at org.mozilla.fenix.ui.robots.DownloadRobotKt.access$assertDownloadNotificationPopup(DownloadRobot.kt:1)
	at org.mozilla.fenix.ui.robots.DownloadRobot.verifyDownloadNotificationPopup(DownloadRobot.kt:44)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$4.invoke(DownloadTest.kt:183)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$4.invoke(DownloadTest.kt:182)
	at org.mozilla.fenix.ui.robots.DownloadRobot$Transition.clickDownload(DownloadRobot.kt:81)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:182)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
