### ISSUE TITLE
[Bug] Launching local build of ArmNightly build config crashes upon startup

### ISSUE THREAD

**Issue by nojunpark** [mozilla-mobile/fenix#2612]
## Steps to reproduce
Locally build ArmNightly built variant (Used `./gradlew clean -PversionName=startup assembleArmNightly`) on commit `9e50b553408dc1ccfb858b83790acdbc90ad0892`
Sign the apk and install on Moto G5
Start the app

### Expected behavior
App starts

### Actual behavior
Crashes, with stack trace

```
05-17 14:20:45.641 17622 17640 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
05-17 14:20:45.641 17622 17640 E AndroidRuntime: Process: org.mozilla.fenix, PID: 17622
05-17 14:20:45.641 17622 17640 E AndroidRuntime: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:4)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:1)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:4)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:1)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:15)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:10)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at org.mozilla.fenix.home.HomeFragment$onViewCreated$1.invokeSuspend(HomeFragment.kt:11)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
05-17 14:20:45.641 17622 17640 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: FATAL EXCEPTION: main
05-17 14:20:45.642 17622 17622 E AndroidRuntime: Process: org.mozilla.fenix, PID: 17622
05-17 14:20:45.642 17622 17622 E AndroidRuntime: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:4)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:1)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:4)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:1)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:15)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:7)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at org.mozilla.fenix.components.Core$sessionManager$2.invoke(Core.kt:2)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at org.mozilla.fenix.components.Core.getSessionManager(Unknown Source:7)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at org.mozilla.fenix.home.HomeFragment.emitSessionChanges(HomeFragment.kt:1)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at org.mozilla.fenix.home.HomeFragment.onStart(HomeFragment.kt:8)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:6)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:209)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:3)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:9)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:209)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStart(FragmentManagerImpl.java:3)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:13)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1356)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7052)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6626)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-17 14:20:45.642 17622 17622 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
05-17 14:20:45.642 17622 17640 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android')
```

### Device information
* Android device: moto g5
* Fenix version: commit 9e50b553408dc1ccfb858b83790acdbc90ad0892

**Comment by yoasif** [comment]
Also reported on the fenix google group: 

Pixel 3 XL force close on open.

Crash report: Main Dispatcher Error
Log: https://del.dog/zaxujiqeda.cs

**Comment by kbrosnan** [comment]
Does this work if you update to current master? https://github.com/mozilla-mobile/fenix/pull/2617 reverts the GV update which caused a startup crash.

**Comment by hawkinsw** [comment]
Can anyone with permission assign this to me?

**Comment by sarentz** [comment]
This looks like the build that had the new GeckoView? The timing is correct for that, we landed that last Friday at noon.
