### ISSUE TITLE
Firefox Android crashed when open https://atmos.leeroy.ca/ and  click explore

### ISSUE THREAD

**Issue by Murmurl912** [mozilla-mobile/fenix#26126]
Firefox Android crashed when open https://atmos.leeroy.ca/ and  click explore

104.0a1 (Build #2015892459), 51715c27b+
AC: 104.0.20220715193302, 25b1068e5a
GV: 104.0a1-20220715095545
AS: 93.6.0

crash info
3e87598c-fa81-402c-a1b3-722638d9caab
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
----
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.resolveTypeIfNeeded(android.content.ContentResolver)' on a null object reference
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:460)
	at android.app.PendingIntent.getActivity(PendingIntent.java:447)
	at android.app.PendingIntent.getActivity(PendingIntent.java:411)
	at mozilla.components.feature.media.notification.MediaNotificationKt.access$toNotificationData(MediaNotification.kt:71)
	at mozilla.components.feature.media.notification.MediaNotification.create(MediaNotification.kt:4)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate.access$updateNotification(MediaSessionServiceDelegate.kt:7)
	at mozilla.components.feature.media.service.MediaSessionServiceDelegate$processMediaSessionState$1.invokeSuspend(MediaSessionServiceDelegate.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7890)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6a05f12, Dispatchers.Main]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21077)

**Comment by mcarare** [comment]
@Murmurl912 Can you please specify the device and Android version? Thank you!

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Nightly 104.0a1 2022-07-21 but was unable to reproduce it.
### Devices used:
- Google Pixel 6 (Android 13)
- OnePlus 6T (Android 9)

**Comment by kbrosnan** [comment]
Do you have open in app enabled?

**Comment by Murmurl912** [comment]
My device is sony xperia 1 iv xq-ct72

**Comment by Murmurl912** [comment]
My devices is Xperia 1 iv XQ-CT72, Os is android 12, build version 64.0.F.10.25. It could be a device isucce, this are a lot of bugs with this phone.

**Comment by Murmurl912** [comment]
I found what cause the crash. I deny read pacakge list permission.  Which cause the pacakge manager crashed when call getLaunchIntentForPackage.

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813798

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
