### ISSUE TITLE
Intermittent UI test failure -  legacy-x86 - < DownloadTest. pauseResumeCancelDownloadTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26132]
### Firebase Test Run: 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6804635958579395733/executions/bs.b3af1bee47d1b04e/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6804635958579395733/executions/bs.7cca211969d5d434/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6804635958579395733/executions/bs.167c9787eca4c2b1/testcases/1/test-cases)

### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:150)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:150)
    
### Build: Failed on 7/21 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21084)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6340380616251551049/executions/bs.fbfde7353934a664/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:150)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:150)

**Comment by AndiAJ** [comment]
Flaky 1x on 7/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8703931938252808631/executions/bs.c5aa2d63fcb4952/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:150)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:150)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6214816321318224797/executions/bs.b617055b63630ed1/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:150)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:150)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6832107525042132963/executions/bs.8c60b6c7515f1572/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:155)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:152)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:152)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/12 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9140386269948453965/executions/bs.1de528fd289d6445/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9140386269948453965/executions/bs.f64b9737e36a3e2/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=PAUSE, RESOURCE_ID=android:id/action0]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.NotificationRobot.clickDownloadNotificationControlButton(NotificationRobot.kt:84)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:158)
	at org.mozilla.fenix.ui.DownloadTest$pauseResumeCancelDownloadTest$5.invoke(DownloadTest.kt:155)
	at org.mozilla.fenix.ui.robots.NotificationRobotKt.notificationShade(NotificationRobot.kt:135)
	at org.mozilla.fenix.ui.DownloadTest.pauseResumeCancelDownloadTest(DownloadTest.kt:155)

**Comment by sv-ohorvath** [comment]
I think the problem might be solved after switching to ARM. I'll close the issue but feel free to reopen if it occurs again.
