### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. copyTextTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26188]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.SearchRobot.clickPasteText(SearchRobot.kt:225)
	at org.mozilla.fenix.ui.SmokeTest$copyTextTest$4.invoke(SmokeTest.kt:921)
	at org.mozilla.fenix.ui.SmokeTest$copyTextTest$4.invoke(SmokeTest.kt:918)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.searchScreen(SearchRobot.kt:378)
	at org.mozilla.fenix.ui.SmokeTest.copyTextTest(SmokeTest.kt:918)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6350317156142166997/executions/bs.aaaa9a0e038977ef/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.SearchRobot.clickPasteText(SearchRobot.kt:225)
	at org.mozilla.fenix.ui.SmokeTest$copyTextTest$4.invoke(SmokeTest.kt:928)
	at org.mozilla.fenix.ui.SmokeTest$copyTextTest$4.invoke(SmokeTest.kt:925)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.searchScreen(SearchRobot.kt:378)
	at org.mozilla.fenix.ui.SmokeTest.copyTextTest(SmokeTest.kt:925)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7337334365503288726/executions/bs.5069bd67f8a82d2d/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.copyTextTest(SmokeTest.kt:923)

**Comment by AndiAJ** [comment]
Failed 1x on 9/15 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7450824176595990323/executions/bs.c85b110d8d63cad6/testcases/4/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7450824176595990323/executions/bs.52de51080a92bc4e/testcases/4/test-cases)

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.mozilla.fenix.compose.cfr.CFRPopupFullscreenLayout.show(CFRPopupFullscreenLayout.kt:121)
	at org.mozilla.fenix.compose.cfr.CFRPopup.show$lambda-1(CFRPopup.kt:76)
	at org.mozilla.fenix.compose.cfr.CFRPopup.$r8$lambda$TXBcbC1ZJIfV_BS4FJxo1uw7w5M(Unknown Source:0)
	at org.mozilla.fenix.compose.cfr.CFRPopup$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
