### ISSUE TITLE
Firefox Android crash

### ISSUE THREAD

**Issue by skycaptnkragg** [mozilla-mobile/fenix#26237]
13c0a4d8-6cd7-451f-96e5-e475ae772f97
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
----
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
	at org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(Native Method)
	at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:10)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:10)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$3.emit(EngineViewPresenter.kt:16)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@493f55b, Dispatchers.Main]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21144)

**Comment by kbrosnan** [comment]
Please provide more information. A crash ID URL would be helpful. https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

I don't see this crash signature on any of our crash tracking tools.

**Comment by kbrosnan** [comment]
Closing this in favor of #26259 which has better information.
