### ISSUE TITLE
Firefox crashes when opening link from external app

### ISSUE THREAD

**Issue by DodoLeDev** [mozilla-mobile/fenix#26259]
### Steps to reproduce

1. Open firefox normally
2. Close firefox and clear it from recents
3. Open an app with external link
4. Click the link, it'll open with firefox
5. Firefox opens, then suddently crashes 😞

### Expected behaviour

Firefox should start normally, without any crash, and load the requested webpage

### Actual behaviour

Firefox crashes. Nothing more.

### Device name

Xiaomi Redmi note 9

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

105.0a1

### Device logs

```
4cc303fc-f2c4-4887-bcab-5072a9f0e2e0
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
----
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
	at org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(Native Method)
	at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:10)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:10)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$3.emit(EngineViewPresenter.kt:16)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7c5ff41, Dispatchers.Main]
```

### Additional information

This bug seems to appear when Firefox wants to fully initialize itself while we ask it to load a webpage

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21159)

**Comment by cadeyrn** [comment]
Same crash signature as in #26237.

**Comment by kbrosnan** [comment]
Talked to GV engineers and this seems to be a platform bug.

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1783244

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
@DodoLeDev, does this crash happen you open an external link from any app or one specific app? Did opening an external link used to work and only started crashing recently?

**Comment by DarkFlame57** [comment]
I am having the same issue on fennec (f-droid firefox build)

**Comment by DarkFlame57** [comment]
> @DodoLeDev, does this crash happen you open an external link from any app or one specific app? Did opening an external link used to work and only started crashing recently?

In my case when opening from telegram

**Comment by ubergeek77** [comment]
This is a critical bug, but the Bugzilla tracker indicates this isn't going to be fixed until Firefox 104. That's not scheduled to be released until nearly the end of the month.

Can this please be pushed up in priority so that the appropriate fix is available sooner as a stable release?

It does not seem appropriate to leave such a critical crash bug unaddressed for three more weeks.

**Comment by DodoLeDev** [comment]
Wow! Seems that **this bug has been fixed in the latest Nightly release**!  
_Thanks for all your answers!_

**Comment by LaurentiuApahideanSV** [comment]
@DodoLeDev We've uplifted the fix on Firefox Beta 104.0b6 and plan on releasing later today. Once the new build is available could you please install it and see if the issue is fixed on that build as well?

**Comment by DodoLeDev** [comment]
The bug no longer appears on Nightly builds! 🥳

**Comment by BDPeterV** [comment]
De bug appears on Firefox 108.0.2, running in KDE Neon.
