### ISSUE TITLE
[@ java.lang.RuntimeException: Failure delivering result ResultInfo...] when uploading files 

### ISSUE THREAD

**Issue by themukeshmahiya** [mozilla-mobile/fenix#26275]
### Steps to reproduce

1. Open any website, then open ublock origin settings & tap restore from file

### Expected behaviour

it should import backup without any errors

### Actual behaviour

it crashes 

### Device name

redmi note 10 pro (sweeetin)

### Android version

12

### Firefox release type

Firefox

### Firefox version

103.1.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21175)

**Comment by kbrosnan** [comment]
Please provide crash ID URLs, https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by themukeshmahiya** [comment]
1.https://crash-stats.mozilla.org/report/index/da1c679c-911c-4939-bb10-293740220802

2.https://crash-stats.mozilla.org/report/index/4c98e9a6-644d-43ef-9a6c-3a0320220802

**Comment by kbrosnan** [comment]
https://crash-stats.mozilla.org/search/?java_stack_trace_raw=~java.lang.RuntimeException%3A%20Failure%20delivering%20result%20ResultInfo&product=Fenix&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature - requires raw java stacktrace access to return results.

https://sentry.io/organizations/mozilla/issues/?project=6295551&project=6295546&project=6375561&query=is%3Aunresolved+Failure+delivering+result+ResultInfo&statsPeriod=14d

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7113, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/EXACT_FILE_REDACTED.TXT flg=0x1 }} to activity {org.mozilla.firefox/org.mozilla.firefox.App}: java.lang.SecurityException: com.android.providers.downloads has no access to content://media/external_primary/file/1619
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5423)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5462)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2260)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
Caused by: java.lang.SecurityException: com.android.providers.downloads has no access to content://media/external_primary/file/1619
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2029)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toFileUri(GeckoPromptDelegate.kt:22)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onFilePrompt$onSelectSingle$1.invoke(GeckoPromptDelegate.kt:4)
	at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:25)
	at mozilla.components.feature.prompts.PromptFeatureKt.consumePromptFrom(PromptFeature.kt:9)
	at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:18)
	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.onActivityResult(ViewBoundFeatureWrapper.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:6)
	at org.mozilla.fenix.HomeActivity.onActivityResult(HomeActivity.kt:5)
	at android.app.Activity.dispatchActivityResult(Activity.java:8566)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5416)
	... 13 more
```

**Comment by thornySoap** [comment]
This is sort of annoying, because I have to switch to another browser everytime I want to upload PDFs to Moodle. And that is often

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1805342

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by cpeterso** [comment]
I moved this bug to Bugzilla so we can prioritize it there.

The exception is `java.lang.SecurityException: com.android.providers.downloads has no access to content://media/external_primary/file/1619`
