### ISSUE TITLE
crashes when i start it up

### ISSUE THREAD

**Issue by errorCam** [mozilla-mobile/fenix#26321]
bd5ef7e2-4b93-4196-9cd5-8bc53799d166
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
----
java.lang.UnsatisfiedLinkError: No implementation found for boolean org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(android.view.Surface) (tried Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned and Java_org_mozilla_gecko_SurfaceViewWrapper_isSurfaceAbandoned__Landroid_view_Surface_2)
	at org.mozilla.gecko.SurfaceViewWrapper.isSurfaceAbandoned(Native Method)
	at org.mozilla.geckoview.GeckoView$Display.acquire(GeckoView.java:10)
	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:10)
	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$3.emit(EngineViewPresenter.kt:16)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at mozilla.components.feature.session.engine.EngineViewPresenter$start$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4378328, Dispatchers.Main]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21201)

**Comment by kbrosnan** [comment]
Duplicate https://github.com/mozilla-mobile/fenix/issues/26259
