### ISSUE TITLE
Frequent browsertime java.lang.SecurityException: Package org.mozilla.fenix has not requested permission android.permission.WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#26359]
### Test Run:
https://treeherder.mozilla.org/logviewer?job_id=386636915&repo=fenix
### Stacktrace:
```
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  adb Unable to grant runtime permission android.permission.WRITE_EXTERNAL_STORAGE to org.mozilla.fenix due to args: adb wait-for-device shell su -c 'pm grant org.mozilla.fenix android.permission.WRITE_EXTERNAL_STORAGE', exitcode: 255, stdout:
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  Exception occurred while executing 'grant':
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  java.lang.SecurityException: Package org.mozilla.fenix has not requested permission android.permission.WRITE_EXTERNAL_STORAGE
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:453)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1538)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermissionInternal(PermissionManagerService.java:1492)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1484)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:2325)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:259)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.ShellCommand.exec(ShellCommand.java:44)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26546)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.Binder.shellCommand(Binder.java:965)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.Binder.onTransact(Binder.java:839)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5247)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.Binder.execTransactInternal(Binder.java:1195)
[task 2022-08-08T06:33:58.337Z] 06:33:55     INFO -  	at android.os.Binder.execTransact(Binder.java:1159)
```
### Build: 
https://github.com/mozilla-mobile/fenix/commit/9255d351fde9ce858753f37c4641b299ef563dc7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21218)

**Comment by Archaeopteryx** [comment]
This is a regression from the migration to the a51 machines in [Bug 1780858](https://bugzilla.mozilla.org/show_bug.cgi?id=1780858). cc @92kns

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813821

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
