### ISSUE TITLE
[Crash]  NullPointerException SearchDialogController

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#26366]
Low volume 
[Sentry Nightly ](https://sentry.io/organizations/mozilla/issues/3471134095/?project=6295546)
[Sentry Beta ](https://sentry.io/organizations/mozilla/issues/?project=6295551&query=is%3Aunresolved+level%3Afatal+SearchDialogController&sort=freq)

```

java.lang.NullPointerException: null
    at org.mozilla.fenix.search.SearchDialogController$$ExternalSyntheticLambda0.onClick
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:3)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7050)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21222)

**Comment by cpeterso** [comment]
This bug must have been fixed in 106. We have ~2000 crash reports from 105 and only one from 106.

https://bugzilla.mozilla.org/show_bug.cgi?id=1782760
