### ISSUE TITLE
Intermittent Unit Test failure - StartupTypeTelemetryTest.WHEN record is called THEN telemetry is recorded with the appropriate label

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/fenix#26380]
### Test Run:
Test failed in https://github.com/mozilla-mobile/fenix/pull/26378 - https://firefoxci.taskcluster-artifacts.net/OIThuwo1TRSMqXOucAYXqg/0/public/reports/test/testDebugUnitTest/index.html 

### Stacktrace:
> java.lang.AssertionError: expected:<1> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.mozilla.fenix.perf.StartupTypeTelemetryTest.WHEN record is called THEN telemetry is recorded with the appropriate label(StartupTypeTelemetryTest.kt:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.

### Build: 105

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21233)

**Comment by jonalmeida** [comment]
Happened again in an unrelated PR: [logs link](https://pipelines.actions.githubusercontent.com/serviceHosts/76ef84e6-2541-41e9-85c1-758085b4811e/_apis/pipelines/1/runs/77230/signedlogcontent/8?urlExpires=2022-08-11T02%3A51%3A37.8968811Z&urlSigningMethod=HMACV1&urlSignature=Fx%2FD7x0CJ7rvm0Pno4fCioHleO1gy1orJhcVJVOfAwk%3D)

**Comment by Mugurell** [comment]
Also failing in https://github.com/mozilla-mobile/fenix/pull/26415

**Comment by Mugurell** [comment]
And here https://github.com/mozilla-mobile/fenix/pull/26431

**Comment by Mugurell** [comment]
Failed again in https://github.com/mozilla-mobile/fenix/pull/26436
Seems like something regressed.

**Comment by jonalmeida** [comment]
We updated to a new Glean version recently, that might be related.

**Comment by rvandermeulen** [comment]
Can we disable this test for now? This is causing a lot of pain for getting PRs merged lately.

**Comment by Mugurell** [comment]
Will look into fixing or disabling.
