### ISSUE TITLE
Intermittent UI test failure - < PwaTest. externalLinkPWATest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26383]
### Stacktrace:

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=External link]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickLinkMatchingText(BrowserRobot.kt:309)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:54)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$5.invoke(PwaTest.kt:53)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:82)
	at org.mozilla.fenix.ui.PwaTest.externalLinkPWATest(PwaTest.kt:53)
    
### Build: 8/8 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21235)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6022596981284277251/executions/bs.4628156049d835fa/testcases/1/test-cases)

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at org.mozilla.fenix.ui.robots.CustomTabRobot.verifyCustomTabToolbarTitle(CustomTabRobot.kt:77)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$6.invoke(PwaTest.kt:58)
	at org.mozilla.fenix.ui.PwaTest$externalLinkPWATest$6.invoke(PwaTest.kt:57)
	at org.mozilla.fenix.ui.robots.CustomTabRobotKt.customTabScreen(CustomTabRobot.kt:157)
	at org.mozilla.fenix.ui.PwaTest.externalLinkPWATest(PwaTest.kt:57)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
