### ISSUE TITLE
Intermittent UI test failure - < CustomTabsTest. customTabCopyToolbarUrlTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26405]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.SearchRobot.clickPasteText(SearchRobot.kt:225)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:139)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:136)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.searchScreen(SearchRobot.kt:378)
	at org.mozilla.fenix.ui.CustomTabsTest.customTabCopyToolbarUrlTest(CustomTabsTest.kt:136)
    
### Build: 8/10

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21250)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7377266042136343430/executions/bs.f4a0177d00ce0f27/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.SearchRobot.clickPasteText(SearchRobot.kt:225)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:139)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:136)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.searchScreen(SearchRobot.kt:378)
	at org.mozilla.fenix.ui.CustomTabsTest.customTabCopyToolbarUrlTest(CustomTabsTest.kt:136)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9066000715543028307/executions/bs.6bbde80eee74d8f1/testcases/1/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.SearchRobot.clickPasteText(SearchRobot.kt:225)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:145)
	at org.mozilla.fenix.ui.CustomTabsTest$customTabCopyToolbarUrlTest$3.invoke(CustomTabsTest.kt:142)
	at org.mozilla.fenix.ui.robots.SearchRobotKt.searchScreen(SearchRobot.kt:378)
	at org.mozilla.fenix.ui.CustomTabsTest.customTabCopyToolbarUrlTest(CustomTabsTest.kt:142)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
