### ISSUE TITLE
[Top Crash #2] Crash when closing CustomTab

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#2645]
https://sentry.prod.mozaws.net/operations/fenix/issues/5713056/

```
IllegalArgumentException: Required value was null.
    at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:5)
    at org.mozilla.fenix.browser.BrowserFragment.onStop(BrowserFragment.kt:3)
...
(26 additional frame(s) were not displayed)

RuntimeException: Unable to stop activity {org.mozilla.fenix/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null.
    at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4380)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4350)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4425)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:192)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
...
(9 additional frame(s) were not displayed)

Unable to stop activity {org.mozilla.fenix/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null.
```

**Comment by agi90** [comment]
I see this when I press "back" after opening any link in CustomTab

**Comment by cadeyrn** [comment]
There are already a few issues about a crash when closing a custom tab: #2414, #2447, #2615.

**Comment by agi90** [comment]
Ah thanks, there was no bug linked in Sentry so I opened a new one, I'll dupe this.
