### ISSUE TITLE
Crash: NoSuchElementException: List is empty

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#26472]
Low volume.
 
[Nightly](https://sentry.io/organizations/mozilla/issues/3500174340/?project=6295546) 

```
java.util.NoSuchElementException: List is empty.
    at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:8)
    at org.mozilla.fenix.home.HomeFragment$$ExternalSyntheticLambda1.onClick
    at android.view.View.performClick(View.java:7792)
    at android.view.View.performClickInternal(View.java:7769)
    at android.view.View.access$3800(View.java:910)
    at android.view.View$PerformClick.run(View.java:30218)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21303)

**Comment by Amejia481** [comment]
This is our [top 3 crash on Socorro](https://crash-stats.mozilla.org/signature/?product=Fenix&version=105.0a1&signature=java.util.NoSuchElementException%3A%20at%20kotlin.collections.CollectionsKt___CollectionsKt.first%28_Collections.kt%3A8%29&date=%3E%3D2022-08-12T13%3A41%3A00.000Z&date=%3C2022-08-15T13%3A41%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1)

**Comment by cpeterso** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1805351
