### ISSUE TITLE
Intermittent UI test failure - < SitePermissionsTest. blockLocationPermissionsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26504]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SitePermissionsTest.blockLocationPermissionsTest(SitePermissionsTest.kt:305)
    
### Build: 8/16 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21316)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/1 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5777872327041094756/executions/bs.34301fb934974e1/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SitePermissionsTest.blockLocationPermissionsTest(SitePermissionsTest.kt:306)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.
