### ISSUE TITLE
Intermittent UI test failure - selectAllAndCopyTextTest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26663]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5675668473229135495/executions/bs.8a87d572c8c3fc08
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
at org.mozilla.fenix.ui.SmokeTest.selectAllAndCopyTextTest(SmokeTest.kt:942)`
### Build: 
8/25 main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21401)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8981396227333621246/executions/bs.9bd751b32274ea6b/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.selectAllAndCopyTextTest(SmokeTest.kt:935)

**Comment by AndiAJ** [comment]
Failed 1x on 9/14 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8486829012504663760/executions/bs.3f54c26b30bd0871/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8486829012504663760/executions/bs.d70872348e7b90d7/testcases/2/test-cases)

Crash reported in #26884

**Comment by AndiAJ** [comment]
Failed 1x on 9/15 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7450824176595990323/executions/bs.bf883a275a2837ac/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7450824176595990323/executions/bs.a084d4be62f0ef33/testcases/2/test-cases)

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.mozilla.fenix.compose.cfr.CFRPopupFullscreenLayout.show(CFRPopupFullscreenLayout.kt:121)
	at org.mozilla.fenix.compose.cfr.CFRPopup.show$lambda-1(CFRPopup.kt:76)
	at org.mozilla.fenix.compose.cfr.CFRPopup.$r8$lambda$TXBcbC1ZJIfV_BS4FJxo1uw7w5M(Unknown Source:0)
	at org.mozilla.fenix.compose.cfr.CFRPopup$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
