### ISSUE TITLE
Intermittent UI test failure - appLikeExperiencePWATest

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/fenix#26662]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5796381612557137068/executions/bs.b020121266b4e3dd
### Stacktrace:
`java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:194)
at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$2.invoke(PwaTest.kt:104)
at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$2.invoke(PwaTest.kt:102)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
at org.mozilla.fenix.ui.PwaTest.appLikeExperiencePWATest(PwaTest.kt:102)`
### Build: 
8/25 main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21400)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6379734460118068652/executions/bs.2617ee3c0899ded4/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.PwaRobot.verifyPwaActivityInCurrentTask(PwaRobot.kt:17)
	at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$6.invoke(PwaTest.kt:113)
	at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$6.invoke(PwaTest.kt:111)
	at org.mozilla.fenix.ui.robots.PwaRobotKt.pwaScreen(PwaRobot.kt:24)
	at org.mozilla.fenix.ui.PwaTest.appLikeExperiencePWATest(PwaTest.kt:111)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/8 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8268278885395658076/executions/bs.9ddc0694d0aecdbb/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyNotificationDotOnMainMenu(BrowserRobot.kt:232)
	at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$2.invoke(PwaTest.kt:104)
	at org.mozilla.fenix.ui.PwaTest$appLikeExperiencePWATest$2.invoke(PwaTest.kt:102)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.PwaTest.appLikeExperiencePWATest(PwaTest.kt:102)

**Comment by sv-ohorvath** [comment]
I think the problem might be solved after switching to ARM. I'll close the issue but feel free to reopen if it occurs again.
