### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. verifyPageMainMenuItemsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26711]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.verifyPageMainMenuItemsTest(SmokeTest.kt:226)
    
### Build: 8/29 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21422)

**Comment by AndiAJ** [comment]
Flaky 1x on 8/30 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7805410178466872505/executions/bs.556a92578e492520/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.verifyPageMainMenuItemsTest(SmokeTest.kt:226)
    
Flaky 1x on 8/31 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7805410178466872505/executions/bs.556a92578e492520/testcases/1/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:255)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:95)
	at org.mozilla.fenix.ui.SmokeTest.verifyPageMainMenuItemsTest(SmokeTest.kt:226)

**Comment by sv-ohorvath** [comment]
From the video, it looks like the Report site issue button is missing at times. Because the button comes from GeckoView, it takes a while sometimes to appear.
