### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. deleteCookiesTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26710]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:648)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:645)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:645)
    
### Build: 8/29 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21423)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/15 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6985779698123776295/executions/bs.e90b81d75c489cf7/testcases/4/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:636)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:635)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:635)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6550454271955666676/executions/bs.166961bb33c7550d/testcases/4/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:631)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:630)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:630)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6483019716651296844/executions/bs.86a9ad5905becab6/testcases/4/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:631)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:630)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:630)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9014064053191835540/executions/bs.582caa367d4e0e19/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:630)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:629)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:629)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9064761894909151206/executions/bs.34bba8c58e59655b/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:630)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:629)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:629)

**Comment by AaronMT** [comment]
Flaky 1x on 9/22  Main [Firebase link](https://console.firebase.google.com/u/1/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8011096836086217428/details?stepId=bs.34bbbfb91b0b07c0&testCaseId=3)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6522167868642259159/executions/bs.aedd0aaff8fe26b1/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:630)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:629)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:629)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7328893946622616140/executions/bs.f15366bcda590b5f/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/5 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4852264580427468483/executions/bs.664e173f9af97cc4/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/11 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8545463452083292429/executions/bs.2de9ad47cab85aba/testcases/3/test-cases)

https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8545463452083292429/executions/bs.2de9ad47cab85aba/testcases/3/test-cases

**Comment by AndiAJ** [comment]
Flaky 1x on 10/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8806923033038695971/executions/bs.453c9a1aa52bcc49/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9185893564535102230/executions/bs.b54f193f8314fe6a/testcases/2/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:103)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/19 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6549306435882635547/executions/bs.8b7c1b3f88719890/testcases/9/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:103)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 2x on 10/20 Main
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9190284581396348801/executions/bs.535941523004e7f8/testcases/9/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6457281863668362211/executions/bs.db8d21735d808590/testcases/9/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:103)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)

**Comment by AndiAJ** [comment]
Flaky 1x on 29/10 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6349335510177509653/executions/bs.2334796b3766240e/testcases/6/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:108)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:138)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)
    

Flaky 1x on 30/10 [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6516688432053508384/executions/bs.ed521319e49fd21a/testcases/6/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:108)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:620)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$deleteCookiesTest$2.invoke(SettingsPrivacyTest.kt:619)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:138)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.deleteCookiesTest(SettingsPrivacyTest.kt:619)
