### ISSUE TITLE
[Bug]: Firefox Nightly crashes when opening a new tab after accessing about:config

### ISSUE THREAD

**Issue by ClintNase** [mozilla-mobile/fenix#26759]
### Steps to reproduce

1. Open the Firefox Nightly browser
2. Type "about:config" in the address bar
3. Press "Enter"
4. Open a new tab
5. Observe the behaviour

### Expected behaviour

New tab is opened.

### Actual behaviour

The browser crashes.

### Device name

ONEPLUS A6000

### Android version

OxygenOS version 11.1.2.2

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1-20220831093258

### Device logs

4a9be630-bb09-44dd-808c-af4183081797
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
----
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:641)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	... 3 more
Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	at android.net.Uri.getQueryParameterNames(Uri.java:1605)
	at org.mozilla.fenix.ext.UriKt.containsQueryParameters(Uri.kt:4)
	at org.mozilla.fenix.home.blocklist.BlocklistHandler.filterContileRecentTab(BlocklistHandler.kt:8)
	at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.invoke(BlocklistMiddleware.kt:20)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:10)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:3)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Additional information

Notes:
- Video provided: https://gifyu.com/image/SwmMO
- Reproducible regardless of what words are typed as long as it is in the same format (eg. "hello:world" )
- Unable to access the browser until Storage & Cache is cleared

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21444)

**Comment by MozillaNoah** [comment]
This is also trending in [Sentry](https://sentry.io/organizations/mozilla/issues/3550188284/?project=6295546&query=is%3Aunresolved+level%3Afatal+firstSeen%3A-1w&sort=freq&statsPeriod=14d)

**Comment by delia-pop** [comment]
Verified as fixed on the latest Nightly 106.0a1 from [Index Browser](https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.nightly.2022.09.02.latest/arm64-v8a)  09/02 with Google Pixel 6 (Android 13) and Lenovo Yoga Tab 11 (Android 11). 
The application no longer crashes when attempting to open a new tab after visiting about:config. 

https://user-images.githubusercontent.com/89388888/188172734-2de1624d-3520-46cf-ba7b-973e311e9c86.mp4

**Comment by kbrosnan** [comment]
Regressed by https://github.com/mozilla-mobile/fenix/issues/26706

**Comment by sv-calin** [comment]
I can confirm it's no longer reproducible.

**Environment:**
Operating system: Android 11 (ONEPLUS A6000)
Firefox version: 106.0a1-20220911091736
