### ISSUE TITLE
Intermittent Unit Test failure - WHEN the wallpaper is updated to a new one THEN show the wallpaper

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/fenix#26760]
### Test Run:
https://treeherder.mozilla.org/logviewer?job_id=389050096&repo=fenix
### Stacktrace:
```
  TEST: WHEN the wallpaper is updated to a new one THEN show the wallpaper
    W/PackageParser: Unknown element under <manifest>: queries at /builds/worker/checkouts/vcs/app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ Binary XML file line #40
  FAILURE

java.lang.AssertionError: Verification failed: call 1 of 1: WallpapersObserver(#2340).showWallpaper$app_debug(eq(Wallpaper(#2343)), any())). Only one matching call to WallpapersObserver(#2340)/showWallpaper$app_debug(Wallpaper, Continuation) happened, but arguments are not matching:
[0]: argument: Wallpaper(name=default, collection=Collection(name=default, heading=null, description=null, learnMoreUrl=null, availableLocales=null, startDate=null, endDate=null), textColor=null, cardColor=null), matcher: eq(Wallpaper(#2343)), result: -
[1]: argument: continuation {}, matcher: any(), result: +

Stack trace:
                                                                                    io.mockk.impl.InternalPlatform.captureStackTrace                                                  (InternalPlatform.kt:124)             
                                                                                      io.mockk.impl.stub.MockKStub.handleInvocation                                                   (MockKStub.kt:250)                    
                                                    io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation                                                         (JvmMockFactoryHelper.kt:23)          
                                                                             io.mockk.proxy.jvm.advice.Interceptor.call                                                               (Interceptor.kt:21)                   
                                                                         org.mozilla.fenix.home.WallpapersObserver.observeWallpaperUpdates$app_debug                                  (WallpapersObserver.kt:77)            
org.mozilla.fenix.home.WallpapersObserverTest$WHEN the wallpaper is updated to a new one THEN show the wallpaper$1.invokeSuspend                                                      (WallpapersObserverTest.kt:104)       
org.mozilla.fenix.home.WallpapersObserverTest$WHEN the wallpaper is updated to a new one THEN show the wallpaper$1.invoke                                                             (WallpapersObserverTest.kt:-1)        
org.mozilla.fenix.home.WallpapersObserverTest$WHEN the wallpaper is updated to a new one THEN show the wallpaper$1.invoke                                                             (WallpapersObserverTest.kt:-1)        
                                         kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invokeSuspend                                                      (TestBuilders.kt:208)                 
                                         kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke                                                             (TestBuilders.kt:-1)                  
                                         kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke                                                             (TestBuilders.kt:-1)                  
                                                                      kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched                                         (Undispatched.kt:55)                  
                                                                                 kotlinx.coroutines.CoroutineStart.invoke                                                             (CoroutineStart.kt:112)               
                                                                              kotlinx.coroutines.AbstractCoroutine.start                                                              (AbstractCoroutine.kt:126)            
                                                            kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine                                                   (TestBuilders.kt:207)                 
                                                                            kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine                                                   (-:1)                                 
                                                kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend                                                      (TestBuilders.kt:167)                 
                                                kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke                                                             (TestBuilders.kt:-1)                  
                                                kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke                                                             (TestBuilders.kt:-1)                  
                                                      kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend                                                      (TestBuildersJvm.kt:13)               
                                                               kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith                                                         (ContinuationImpl.kt:33)              
                                                                                 kotlinx.coroutines.DispatchedTask.run                                                                (DispatchedTask.kt:106)               
                                                                              kotlinx.coroutines.EventLoopImplBase.processNextEvent                                                   (EventLoop.common.kt:279)             
                                                                              kotlinx.coroutines.BlockingCoroutine.joinBlocking                                                       (Builders.kt:85)                      
                                                                         kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking                                                        (Builders.kt:59)                      
                                                                                     kotlinx.coroutines.BuildersKt.runBlocking                                                        (-:1)                                 
                                                                         kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default                                                (Builders.kt:38)                      
                                                                                     kotlinx.coroutines.BuildersKt.runBlocking$default                                                (-:1)                                 
                                                                         kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult                                                   (TestBuildersJvm.kt:12)               
                                                            kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest                                                            (TestBuilders.kt:166)                 
                                                                            kotlinx.coroutines.test.TestBuildersKt.runTest                                                            (-:1)                                 
                                                            kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest                                                            (TestBuilders.kt:154)                 
                                                                            kotlinx.coroutines.test.TestBuildersKt.runTest                                                            (-:1)                                 
                                                                    mozilla.components.support.test.rule.HelpersKt.runTestOnMain                                                      (Helpers.kt:56)                       
                                                                    mozilla.components.support.test.rule.HelpersKt.runTestOnMain$default                                              (Helpers.kt:41)                       
                                                                     org.mozilla.fenix.home.WallpapersObserverTest.WHEN the wallpaper is updated to a new one THEN show the wallpaper (WallpapersObserverTest.kt:93)        
                                                                     jdk.internal.reflect.NativeMethodAccessorImpl.invoke0                                                            (NativeMethodAccessorImpl.java:-2)N   
                                                                     jdk.internal.reflect.NativeMethodAccessorImpl.invoke                                                             (NativeMethodAccessorImpl.java:62)    
                                                                 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke                                                             (DelegatingMethodAccessorImpl.java:43)
                                                                                          java.lang.reflect.Method.invoke                                                             (Method.java:566)                     
                                                                         org.junit.runners.model.FrameworkMethod$1.runReflectiveCall                                                  (FrameworkMethod.java:50)             
                                                               org.junit.internal.runners.model.ReflectiveCallable.run                                                                (ReflectiveCallable.java:12)          
                                                                           org.junit.runners.model.FrameworkMethod.invokeExplosively                                                  (FrameworkMethod.java:47)             
                                                                org.junit.internal.runners.statements.InvokeMethod.evaluate                                                           (InvokeMethod.java:17)                
                                                                                     org.junit.rules.TestWatcher$1.evaluate                                                           (TestWatcher.java:55)                 
                                                                                          org.junit.rules.RunRules.evaluate                                                           (RunRules.java:20)                    
                                                          org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate                                                           (RobolectricTestRunner.java:591)      
                                                                      org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0                                                  (SandboxTestRunner.java:274)          
                                                                         org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0                                           (Sandbox.java:88)                     
                                                                                   java.util.concurrent.FutureTask.run                                                                (FutureTask.java:264)                 
                                                                           java.util.concurrent.ThreadPoolExecutor.runWorker                                                          (ThreadPoolExecutor.java:1128)        
                                                                    java.util.concurrent.ThreadPoolExecutor$Worker.run                                                                (ThreadPoolExecutor.java:628)         
                                                                                                  java.lang.Thread.run                                                                (Thread.java:829)                     
	at io.mockk.impl.recording.states.VerifyingState.failIfNotPassed(VerifyingState.kt:66)
	at io.mockk.impl.recording.states.VerifyingState.recordingDone(VerifyingState.kt:42)
	at io.mockk.impl.recording.CommonCallRecorder.done(CommonCallRecorder.kt:47)
```
### Build: 
https://treeherder.mozilla.org/logviewer?job_id=389050096&repo=fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21445)

**Comment by boek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1813836

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
