### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. deleteCachedFilesTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26786]
### Stacktrace:

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: mozilla.components.lib.state.StoreException: Exception while reducing state
	at mozilla.components.lib.state.Store$exceptionHandler$1$1.run(Store.kt:51)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	... 3 more
Caused by: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	at android.net.Uri.getQueryParameterNames(Uri.java:1605)
	at org.mozilla.fenix.ext.UriKt.containsQueryParameters(Uri.kt:29)
	at org.mozilla.fenix.home.blocklist.BlocklistHandler.filterContileRecentTab(BlocklistHandler.kt:65)
	at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.getUpdatedAction(BlocklistMiddleware.kt:51)
	at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.invoke(BlocklistMiddleware.kt:32)
	at org.mozilla.fenix.home.blocklist.BlocklistMiddleware.invoke(BlocklistMiddleware.kt:19)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:62)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:62)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:57)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$threadCheck$1.invoke(ReducerChainBuilder.kt:55)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:62)
	at mozilla.components.lib.state.internal.ReducerChainBuilder$build$1$1.invoke(ReducerChainBuilder.kt:62)
	at mozilla.components.lib.state.Store$dispatch$1.invokeSuspend(Store.kt:94)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
    
### Build: 9/1 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21458)

**Comment by AndiAJ** [comment]
Closing as it didn't fail for approx. a month.
