### ISSUE TITLE
[Bug]: Crashes when trying to upload files

### ISSUE THREAD

**Issue by CathyKMeow** [mozilla-mobile/fenix#26785]
### Steps to reproduce

1. Open a file upload demo site (e.g. [this one](https://blueimp.github.io/jQuery-File-Upload/))
2. Select a file which is not a media file (picture / video / audio)

### Expected behaviour

The file had been selected for upload.

### Actual behaviour

Fenix crashes.

### Device name

Samsung Galaxy Tab S8 Ultra

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 2022-09-02T05:11:28.035473

### Device logs
```
ca6d4d99-be83-4af2-8620-62dc702da493
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7113, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:a.zip flg=0x1 }} to activity {org.mozilla.fenix/org.mozilla.fenix.App}: java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/850
----
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7113, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:a.zip flg=0x1 }} to activity {org.mozilla.fenix/org.mozilla.fenix.App}: java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/850
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8646)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/850
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.access$toFileUri(GeckoPromptDelegate.kt:22)
	at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate$onFilePrompt$onSelectSingle$1.invoke(GeckoPromptDelegate.kt:4)
	at mozilla.components.feature.prompts.file.FilePicker$onActivityResult$1.invoke(FilePicker.kt:25)
	at mozilla.components.feature.prompts.PromptFeatureKt.consumePromptFrom(PromptFeature.kt:9)
	at mozilla.components.feature.prompts.PromptFeature.onActivityResult(PromptFeature.kt:18)
	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.onActivityResult(ViewBoundFeatureWrapper.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onActivityResult(BaseBrowserFragment.kt:6)
	at org.mozilla.fenix.HomeActivity.onActivityResult(HomeActivity.kt:5)
	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
	... 13 more
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21457)

**Comment by marcel263** [comment]
Returns "filetype not allowed" on the page. No crash Android 11 Nightlh

**Comment by amocirean** [comment]
Hello @CathyKMeow, thank you for submitting the issue.
I was not able to reproduce it on Nightly 107.0a1 nor Release 105.2.0. As the previous comment states, a "File Type not allowed" message is shown under the file name. No crash is generated.
Could you tell us if the issue is still occuring on the latest RC or Nightly on your device?

Devices Used: Huawei P40 Lite (Android 10), Google Pixel 6 (Android 13).

**Comment by csadilek** [comment]
Closing, as there's no activity and the crash is no longer reproducible. Please file again if you're still experiencing problems.
