### ISSUE TITLE
FNX3-16512 ⁃ [Bug] java.lang.IllegalStateException: homeLayout must not be null

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/fenix#2685]
Getting this on 2a099ca7140b84e398975534801520b35f62a420

I don't have STR, but what I logged into Firefox Sync 

> 2019-05-21 11:36:48.112 22536-22536/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 22536
    java.lang.IllegalStateException: homeLayout must not be null
        at org.mozilla.fenix.home.HomeFragment.onSaveInstanceState(HomeFragment.kt:205)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2829)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2276)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2335)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2832)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2276)
        at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2335)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
        at android.app.Activity.performSaveInstanceState(Activity.java:1549)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1443)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:4848)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4195)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4159)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4234)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by sblatz** [comment]
Should be fixed by #2691

**Comment by sv-ohorvath** [comment]
@sblatz Do you have any details for QA?

**Comment by sblatz** [comment]
STR were:
1. Go to home view
2. Open a webpage
3. Go home
4. Background the app (go to home screen)

App would crash after doing these steps.

@sv-ohorvath

**Comment by sv-ohorvath** [comment]
Didn't see any crashes following the STR above. Considering this as fixed.

**Comment by vladikoff** [comment]
Awesome! thanks for fixing this!
