### ISSUE TITLE
Android crash whenever I open gboard

### ISSUE THREAD

**Issue by clueless15** [mozilla-mobile/fenix#26919]
a5cb1e30-a431-4f35-9dad-03b463edc308
java.lang.RuntimeException: android.os.DeadSystemException
----
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:151)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$2.emit(SearchDialogFragment.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Emitters.kt:9)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:14)
	at mozilla.components.lib.state.ext.FragmentKt$consumeFlow$1$invokeSuspend$$inlined$filter$1$2.emit(Emitters.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1c143cd, Dispatchers.Main]
Caused by: android.os.DeadSystemException
	... 18 more
I have no idea what I am doing 😅.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21532)

**Comment by kbrosnan** [comment]
What build are you using? Any updates for that version?

**Comment by clueless15** [comment]
104.2.0 (Build #2015902899)

**Comment by clueless15** [comment]
I'm still using Firefox though I have to use a 'certain' method to avoid getting Firefox crash. Basically I open any website from my homepage for ex. https://www.wikipedia.com then I click on url and edit (I have to delete the url one by one, if I delete everything it then crashes). That's how I am avoiding it rn 😅.

**Comment by mcarare** [comment]
@clueless15 This is caused by large text or object saved in your clipboard.
