### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest. verifyCustomizeHomepageTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26932]
### Firebase Test Run: 
Failed 4x 💥 

[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8268278885395658076/executions/bs.e88a878436847026/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8268278885395658076/executions/bs.ef9cfb62a48b7d64/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7941182983455665512/executions/bs.6257cb1666df8536/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7941182983455665512/executions/bs.ab569a3a0642de4/testcases/1/test-cases)
[Fireabse link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8359051018120093902/executions/bs.10258e1234f91680/testcases/1/test-cases)
[Fireabse link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8359051018120093902/executions/bs.e5aebda639f06bb9/testcases/1/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6894419708819635171/executions/bs.21aad156be1a5b58/testcases/1/test-cases)

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.mozilla.fenix.compose.cfr.CFRPopupFullScreenLayout.show(CFRPopupFullscreenLayout.kt:121)
	at org.mozilla.fenix.compose.cfr.CFRPopup.show$lambda-1(CFRPopup.kt:76)
	at org.mozilla.fenix.compose.cfr.CFRPopup.$r8$lambda$TXBcbC1ZJIfV_BS4FJxo1uw7w5M(Unknown Source:0)
	at org.mozilla.fenix.compose.cfr.CFRPopup$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
        
### Build: 9/8 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21539)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/12 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8008032084191005980/executions/bs.f13c8dd790b50e91/testcases/1/test-cases)

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1068)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.mozilla.fenix.compose.cfr.CFRPopupFullscreenLayout.show(CFRPopupFullscreenLayout.kt:121)
	at org.mozilla.fenix.compose.cfr.CFRPopup.show$lambda-1(CFRPopup.kt:76)
	at org.mozilla.fenix.compose.cfr.CFRPopup.$r8$lambda$TXBcbC1ZJIfV_BS4FJxo1uw7w5M(Unknown Source:0)
	at org.mozilla.fenix.compose.cfr.CFRPopup$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by AndiAJ** [comment]
Fixed with #26962
