### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. saveLoginFromPromptTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26936]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.test.uiautomator.UiObject2.clickAndWait(androidx.test.uiautomator.EventCondition, long)' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsShown(BrowserRobot.kt:480)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:220)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:219)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:219)
    
### Build: 9/12 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21543)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8142601911874790038/executions/bs.a3d4d6c98e9d907f/testcases/3/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.test.uiautomator.UiObject2.clickAndWait(androidx.test.uiautomator.EventCondition, long)' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsShown(BrowserRobot.kt:480)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:221)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:220)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:220)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/20 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7993691461117043120/executions/bs.c0a77416283bbfca/testcases/2/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.test.uiautomator.UiObject2.clickAndWait(androidx.test.uiautomator.EventCondition, long)' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsShown(BrowserRobot.kt:488)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:220)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:219)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:219)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4709057851805465678/executions/bs.d74d49c875445994/testcases/2/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.test.uiautomator.UiObject2.clickAndWait(androidx.test.uiautomator.EventCondition, long)' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsShown(BrowserRobot.kt:488)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:220)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:219)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:219)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 9/22 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8464498623874392497/executions/bs.f8502c86b09459cd/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8464498623874392497/executions/bs.8f9e67cf1e1834d6/testcases/2/test-cases)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object androidx.test.uiautomator.UiObject2.clickAndWait(androidx.test.uiautomator.EventCondition, long)' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifySaveLoginPromptIsShown(BrowserRobot.kt:480)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:220)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginFromPromptTest$2.invoke(SettingsPrivacyTest.kt:219)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginFromPromptTest(SettingsPrivacyTest.kt:219)
