### ISSUE TITLE
NumberFormatException: empty String

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/fenix#26943]
Sentry Issue: [FENIX-NIGHTLY-22G](https://sentry.io/organizations/mozilla/issues/3579319906/?referrer=github_integration)

NumberFormatException: empty String
    at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
    at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.lang.Float.parseFloat(Float.java:455)
    at mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate.onDateTimePrompt(GeckoPromptDelegate.kt:8)
    at org.mozilla.geckoview.PromptController$DateTimeHandler.callDelegate(PromptController.java:2)
...
(13 additional frame(s) were not displayed)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21545)

**Comment by Amejia481** [comment]
Looks like it could be related to https://github.com/mozilla-mobile/android-components/pull/12632
cc @Alexandru2909.

**Comment by cpeterso** [comment]
Corresponding Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1790425
