### ISSUE TITLE
Intermittent UI test failure - < NavigationToolbarTest. verifyClearCookiesFromQuickSettingsTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26955]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.assertClearSiteDataPrompt(SiteSecurityRobot.kt:52)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.access$assertClearSiteDataPrompt(SiteSecurityRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobot.verifyClearSiteDataPrompt(SiteSecurityRobot.kt:29)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyClearCookiesFromQuickSettingsTest$4.invoke(NavigationToolbarTest.kt:181)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyClearCookiesFromQuickSettingsTest$4.invoke(NavigationToolbarTest.kt:179)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openSiteSecuritySheet(BrowserRobot.kt:953)
	at org.mozilla.fenix.ui.NavigationToolbarTest.verifyClearCookiesFromQuickSettingsTest(NavigationToolbarTest.kt:179)
    
### Build: 9/13 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21551)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8681501143901288292/executions/bs.34142a571f4df8f1/testcases/5/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.assertClearSiteDataPrompt(SiteSecurityRobot.kt:52)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.access$assertClearSiteDataPrompt(SiteSecurityRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobot.verifyClearSiteDataPrompt(SiteSecurityRobot.kt:29)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyClearCookiesFromQuickSettingsTest$4.invoke(NavigationToolbarTest.kt:175)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyClearCookiesFromQuickSettingsTest$4.invoke(NavigationToolbarTest.kt:173)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openSiteSecuritySheet(BrowserRobot.kt:999)
	at org.mozilla.fenix.ui.NavigationToolbarTest.verifyClearCookiesFromQuickSettingsTest(NavigationToolbarTest.kt:173)

**Comment by AndiAJ** [comment]
Closing, it didn't fail for more than a month.
