### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest. editCustomSearchEngineTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#26976]
### Stacktrace:
java.lang.IllegalArgumentException: Can't scroll to index 5, it is out of bounds [0, 0)
	at androidx.compose.foundation.lazy.LazySemanticsKt$lazyListSemantics$1$scrollToIndexAction$1.invoke(LazySemantics.kt:106)
	at androidx.compose.foundation.lazy.LazySemanticsKt$lazyListSemantics$1$scrollToIndexAction$1.invoke(LazySemantics.kt:104)
	at androidx.compose.ui.test.ActionsKt$scrollToIndex$2.invoke(Actions.kt:147)
	at androidx.compose.ui.test.ActionsKt$scrollToIndex$2.invoke(Actions.kt:146)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread$lambda-0(AndroidSynchronization.android.kt:37)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.$r8$lambda$JHfZTn-RG8lrYeP9BZG_AgROyug(Unknown Source:0)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$$ExternalSyntheticLambda0.call(Unknown Source:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
### Build: 9/14 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21711)

**Comment by sv-ohorvath** [comment]
Probably similar to https://github.com/mozilla-mobile/focus-android/issues/7282?

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for a month.
