### ISSUE TITLE
Intermittent UI test failure - java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27006]
### Stacktrace:
09-14 19:06:18.883: D/AndroidRuntime(10677): Shutting down VM
09-14 19:06:18.883: D/AndroidRuntime(10677): --------- beginning of crash
09-14 19:06:18.883: E/AndroidRuntime(10677): FATAL EXCEPTION: main
09-14 19:06:18.883: E/AndroidRuntime(10677): Process: org.mozilla.fenix.debug:tab5, PID: 10677
09-14 19:06:18.883: E/AndroidRuntime(10677): java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6738)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.os.Looper.loop(Looper.java:223)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at java.lang.reflect.Method.invoke(Native Method)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-14 19:06:18.883: E/AndroidRuntime(10677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-14 19:06:18.883: E/ExceptionHandler(10677): Uncaught exception handled: 
09-14 19:06:18.883: E/ExceptionHandler(10677): java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6738)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.os.Looper.loop(Looper.java:223)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at java.lang.reflect.Method.invoke(Native Method)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-14 19:06:18.883: E/ExceptionHandler(10677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-14 19:06:18.883: I/mozac/CrashReporter(10677): Received crash: UncaughtExceptionCrash(timestamp=1663207578883, throwable=java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.content.pm.PackageItemInfo.metaData' on a null object reference, breadcrumbs=[], uuid=b3a06576-19ec-4124-8966-154f3a70fc00)
09-14 19:06:18.886: I/ActivityManager(545): Killing 10677:org.mozilla.fenix.debug:tab5/u0a177 (adj 0): stop org.mozilla.fenix.debug due to deletePackageX
09-14 19:06:18.886: I/ActivityManager(545): Killing 10740:org.mozilla.fenix.debug:gpu/u0a177 (adj 0): stop org.mozilla.fenix.debug due to deletePackageX
### Build: 9/15 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21583)

**Comment by AndiAJ** [comment]
Closing, as it didn't happen for approx. a month.
