### ISSUE TITLE
Intermittent UI test failure - < SettingsBasicsTest. verifyCreditCardAutofillTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27040]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:657)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:243)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:242)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:242)
    
### Build: 9/16 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21600)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/16 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8955130765938238467/executions/bs.f6b5d3d5d894818d/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:657)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:243)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:242)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:242)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6504631387575185492/executions/bs.31e92b4d01bdc994/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:665)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:243)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:242)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:242)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/24 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5198011754103439780/executions/bs.bc9fd777faa2047/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:674)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:243)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:242)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:242)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 10/1 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7474140829602720948/executions/bs.e66644e498d8bd53/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7474140829602720948/executions/bs.1bd5e0addd43d19/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:688)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:243)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:242)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:242)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/7 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6043409114477636485/executions/bs.6d1450389f887e88/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:688)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:234)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:233)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:233)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/13 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8951299737265088260/executions/bs.3c74289a16185149/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:689)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:234)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:233)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:233)

Flaky 1x on 10/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5516308132556840495/executions/bs.19ae8fbd0cef3289/testcases/1/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:689)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:234)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:233)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:233)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/14 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7997505555263112703/executions/bs.bc20c61ffb82491e/testcases/1/test-cases

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=cardNumber]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickCardNumberTextBox(BrowserRobot.kt:689)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:234)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyCreditCardAutofillTest$9.invoke(SettingsBasicsTest.kt:233)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyCreditCardAutofillTest(SettingsBasicsTest.kt:233)

**Comment by AndiAJ** [comment]
Fixed with #27408
