### ISSUE TITLE
Intermittent UI test failure - < SettingsAddonsTest. useAddonsInPrivateModeTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27041]
### Stacktrace:
java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:158)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:157)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:157)
    
### Build: 9/15 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21601)

**Comment by AndiAJ** [comment]
💥 Failed 1x on 9/16 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6483019716651296844/executions/bs.d13c2a8ad038a17/testcases/2/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6483019716651296844/executions/bs.c34120334ebe387d/testcases/2/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:158)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:157)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:157)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/22 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/4779628286591460806/executions/bs.8a46bfc785fc6f45/testcases/2/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:158)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:157)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:157)

**Comment by sv-ohorvath** [comment]
Flaky 1x on 10/5 [link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7916146661260272919/executions/bs.75ef17e20a014646)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/10 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6325338160219950647/executions/bs.39ba76df71065dcc/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:102)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:152)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:151)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:151)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/18 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8243641693347147231/executions/bs.30b7fe91cb8de983/testcases/2/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:103)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:152)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:151)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:151)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/31 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8065683749686407874/executions/bs.8780f16890f4b81c/testcases/3/test-cases)

java.lang.AssertionError: Page didn't load or doesn't contain the expected text
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyPageContent(BrowserRobot.kt:108)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:152)
	at org.mozilla.fenix.ui.SettingsAddonsTest$useAddonsInPrivateModeTest$4.invoke(SettingsAddonsTest.kt:151)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:138)
	at org.mozilla.fenix.ui.SettingsAddonsTest.useAddonsInPrivateModeTest(SettingsAddonsTest.kt:151)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
