### ISSUE TITLE
[Bug] TransactionTooLargeException from "Open links in apps"

### ISSUE THREAD

**Issue by tihovekna** [mozilla-mobile/fenix#27042]
Firefox App for Android is crashing constantly last few days. Hier is crash report: 
9765d04d-8254-4d1d-a50f-c43d6a9fc965
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1573584 bytes
----
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1573584 bytes
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1271)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1234)
	at mozilla.components.feature.app.links.AppLinksUseCases$GetAppLinkRedirect.invoke(AppLinksUseCases.kt:33)
	at org.mozilla.fenix.components.toolbar.DefaultToolbarMenu$coreMenuItems$2$menuItems$2$1.invoke(DefaultToolbarMenu.kt:6)
	at mozilla.components.browser.menu.ext.BrowserMenuItemKt$getHighlight$1.invoke(BrowserMenuItem.kt:3)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:5)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:1)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:1)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:1)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:1)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:1)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
	at mozilla.components.browser.menu.ext.BrowserMenuItemKt.getHighlight(BrowserMenuItem.kt:9)
	at mozilla.components.browser.toolbar.BrowserToolbar.invalidateActions(BrowserToolbar.kt:15)
	at org.mozilla.fenix.components.toolbar.MenuPresenter$start$1$3.emit(MenuPresenter.kt:3)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at org.mozilla.fenix.components.toolbar.MenuPresenter$start$1$invokeSuspend$$inlined$mapNotNull$1$2.emit(Emitters.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b332557, Dispatchers.Main]
Caused by: android.os.TransactionTooLargeException: data parcel size 1573584 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:575)
	at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:6768)
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1243)
	... 30 more

Can someone fix that problem? 
Thanks. 
Tiho

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21602)

**Comment by Mugurell** [comment]
This seems related to the "Open links in apps functionality" and dependent on the accessed webpage and installed apps.
Can you share an example of the webpage on which you observe this issue and maybe the installed app which could open that link?

**Comment by tihovekna** [comment]
I can't open the App. When I try to open it, it crashes. It's not related
to any specific websites.

pet, 16. ruj 2022. 16:16 Mugurell ***@***.***> je napisao:

**Comment by Mugurell** [comment]
Should be fixed in the next Nightly.
