### ISSUE TITLE
Intermittent UI test failure - < SettingsBasicsTest. verifyAddressAutofillTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27057]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=streetAddress]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickStreetAddressTextBox(BrowserRobot.kt:647)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:186)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:185)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyAddressAutofillTest(SettingsBasicsTest.kt:185)
    
### Build: 9/16 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21611)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/21 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9064761894909151206/executions/bs.db0d822fd24e0267/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=streetAddress]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickStreetAddressTextBox(BrowserRobot.kt:655)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:186)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:185)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyAddressAutofillTest(SettingsBasicsTest.kt:185)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/27 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7462231284517954448/executions/bs.58c970a0a1815f57/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=streetAddress]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickStreetAddressTextBox(BrowserRobot.kt:664)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:186)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:185)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyAddressAutofillTest(SettingsBasicsTest.kt:185)

**Comment by AndiAJ** [comment]
Flaky 1x on 9/29 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8882881882594236366/executions/bs.f30f4d49d6b62dd4/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=streetAddress]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickStreetAddressTextBox(BrowserRobot.kt:678)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:186)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:185)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyAddressAutofillTest(SettingsBasicsTest.kt:185)

**Comment by AndiAJ** [comment]
Flaky 1x on 10/4 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7258768135041453474/executions/bs.288a5b50d9680485/testcases/2/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[CONTAINS_TEXT=, CLASS=android.widget.EditText, PACKAGE NAME=org.mozilla.fenix.debug, RESOURCE_ID=streetAddress]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.ui.robots.BrowserRobot.clickStreetAddressTextBox(BrowserRobot.kt:678)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:177)
	at org.mozilla.fenix.ui.SettingsBasicsTest$verifyAddressAutofillTest$8.invoke(SettingsBasicsTest.kt:176)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:109)
	at org.mozilla.fenix.ui.SettingsBasicsTest.verifyAddressAutofillTest(SettingsBasicsTest.kt:176)

**Comment by AndiAJ** [comment]
Fixed with #27408
