### ISSUE TITLE
FNX3-16525 ⁃ IOException: org.mozilla.geckoview.WebRequestError: Request failed, error=0x11, category=0x1

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2711]
https://sentry.prod.mozaws.net/operations/fenix/issues/5785285/

```
WebRequestError: Request failed, error=0x11, category=0x1
    at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(GeckoLoader.java)
    at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:91)

IOException: org.mozilla.geckoview.WebRequestError: Request failed, error=0x11, category=0x1
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:24)
    at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:12)
    at mozilla.components.browser.icons.BrowserIconsKt.access$load(BrowserIcons.kt:5)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(4 additional frame(s) were not displayed)

org.mozilla.geckoview.WebRequestError: Request failed, error=0x11, category=0x1
```

Similar to #520

**Comment by kbrosnan** [comment]
New crash in release 1.0.1921. Looks like an A-C crash?

**Comment by sarentz** [comment]
@pocmo this looks like a favicon exception?

**Comment by pocmo** [comment]
Fixed by:
https://github.com/mozilla-mobile/android-components/issues/3104

I marked this as "Resolved in the next release" in Sentry.
