### ISSUE TITLE
FNX3-16526 ⁃ SocketTimeoutException

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2712]
https://sentry.prod.mozaws.net/operations/fenix/issues/5785200/

```
SocketTimeoutException: None
    at mozilla.components.browser.engine.gecko.fetch.GeckoViewFetchClient.fetch(GeckoViewFetchClient.kt:25)
    at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:12)
    at mozilla.components.browser.icons.BrowserIconsKt.access$load(BrowserIcons.kt:5)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(4 additional frame(s) were not displayed)
```

New crash in 1.0.1921

**Comment by pocmo** [comment]
Fix required in AC:
https://github.com/mozilla-mobile/android-components/issues/3104

**Comment by pocmo** [comment]
The fix landed in AC and I marked the Sentry issue as "fixed in the next release".
