### ISSUE TITLE
FNX3-16530 ⁃ [Bug] IllegalStateException: HomeFragment not attached to a context.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#2719]
## Steps to reproduce
Switch between tabs quickly and the app crashes.

```
2019-05-21 22:50:02.973 12778-12778/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 12778
    java.lang.IllegalStateException: Fragment HomeFragment{16666fd (6bea78fd-cc33-4402-b6b5-a772ecf78052)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:763)
        at org.mozilla.fenix.ext.FragmentKt.getRequireComponents(Fragment.kt:13)
        at org.mozilla.fenix.home.HomeFragment.emitSessionChanges(HomeFragment.kt:568)
        at org.mozilla.fenix.home.HomeFragment.access$emitSessionChanges(HomeFragment.kt:69)
        at org.mozilla.fenix.home.HomeFragment$singleSessionObserver$1.onTitleChanged(HomeFragment.kt:77)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$2$lambda$1.invoke(Session.kt:159)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$2$lambda$1.invoke(Session.kt:26)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:99)
        at mozilla.components.browser.session.Session.notifyObservers(Unknown Source:7)
        at mozilla.components.browser.session.Session.notifyObservers(Session.kt:400)
        at mozilla.components.browser.session.Session.access$notifyObservers(Session.kt:26)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$2.afterChange(Delegates.kt:71)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
```

Seems to be caused from this addition.

* Android device: Pixel 2
* Fenix version: master (21-05-2019)

**Comment by softvision-miralobontiu** [comment]
Verified as fixed, on the latest build 1.0.1922 (#11530616), with Nokia 6 (Android 7.1.1), and Google Pixel (Android 9).
