### ISSUE TITLE
Crash navigating back

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#272]
## Steps to reproduce
1. Navigate to https://www.wikipdeia.org
1. Navigate to https://www.mozilla.org
1. Tap back on the Android navigation toolbar several times until the app crashes
1. The exact URLs used do not matter

### Expected behavior
Does not crash

### Actual behavior
```
Process: org.mozilla.fenix, PID: 25938
java.lang.RuntimeException: Failed to call observer method
    at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
    at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
    at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
    at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
    at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:333)
    at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:138)
    at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:124)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:2485)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1494)
    at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646)
    at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416)
    at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372)
    at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:884)
    at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:827)
    at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:874)
    at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:827)
    at androidx.fragment.app.FragmentActivity.onBackPressed(FragmentActivity.java:190)
    at android.app.Activity.onKeyUp(Activity.java:3114)
    at android.view.KeyEvent.dispatch(KeyEvent.java:3416)
    at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
    at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
    at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
    at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
    at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:486)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5715)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5578)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5075)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5128)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5094)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5231)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5102)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5288)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5075)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5128)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5094)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5102)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5075)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5128)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5094)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5264)
    at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5433)
```

### Device information
* Android device: Galaxy Note 9 and Google Pixel 3
* Fenix version: Unclear. Up to date according to distribution methods as of 2019-01-28 14:30 Pacific time

**Comment by boek** [comment]
This is now fixed. Though we now have to implement the correct back behavior
