### ISSUE TITLE
Intermittent UI test failure - < DownloadTest. manageDownloadsInDownloadsMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27220]
### Stacktrace:
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/trash]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadFromStorage(TestHelper.kt:151)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:194)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:188)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:170)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:188)
    
### Build: 9/28 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21693)

**Comment by sv-ohorvath** [comment]
Flank 1x on 10/5 Main
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/trash]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.helpers.TestHelper.deleteDownloadFromStorage(TestHelper.kt:152)
at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:182)
at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:176)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:170)
at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:176)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/2 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6909327565510047739/executions/bs.faf8a92470003323/testcases/3/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/trash]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadFromStorage(TestHelper.kt:154)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:182)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:176)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:176)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/3 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7056909787559757833/executions/bs.4c32c5c75d2c413b/testcases/3/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/trash]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadFromStorage(TestHelper.kt:154)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:182)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:176)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:176)

**Comment by AaronMT** [comment]
Failed in https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6188064547525830878/executions/bs.24fa67674002278d/videos

https://treeherder.mozilla.org/jobs?repo=fenix&selectedTaskRun=fiXuoR65RKybar_tnmWkqg.0

We should disable this one

**Comment by AndiAJ** [comment]
Failed 1x on 11/3 Main 
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6188064547525830878/executions/bs.42d76bb395e03916/testcases/3/test-cases)
[Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6188064547525830878/executions/bs.24fa67674002278d/testcases/3/test-cases)

androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=com.google.android.apps.photos:id/trash]
	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadFromStorage(TestHelper.kt:154)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:182)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:176)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:176)

**Comment by AaronMT** [comment]
In the video, when Google Photos opens I just see a spinner

https://storage.cloud.google.com/fenix_test_artifacts/2022-11-03_14-16-58.791168_Krfv/matrix_0/Pixel2.arm-30-en_US-portrait-shard_42/video.mp4?authuser=0

**Comment by sv-ohorvath** [comment]
@AaronMT I've already started a few days ago looking for a different solution to delete a file from storage, but I'm still getting different results on firebase. It will take a little more time since I'm working on it in between the search suite.
