### ISSUE TITLE
[Bug]: Fatal Exception when opening external link in private tab with no tabs open (strictmode violation)

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/fenix#27293]
### Steps to reproduce

0. Use a Debug version of Fenix, which enables the strictmode manager.
1. Go to Settings -> Private Browsing and enable `Open links in a private tab`.
2. Close browser so that there are no tabs open.
3. Open an app that opens non-custom tabs in a browser (e.g. Google Maps)
4. Try to open a link.

### Expected behaviour

The link should open in Fenix just as in the non-private tab case except of course in a private tab.

### Actual behaviour

The browser momentarily appears and then disappears. Android then navigates back to the calling app.

### Device name

Google Pixel 3 XL (emulator w/ Google APIs)

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1-20221003094838

### Device logs

```
FATAL EXCEPTION: pool-8-thread-1
    Process: org.mozilla.fenix.debug, PID: 16675
    java.lang.RuntimeException: StrictMode ThreadPolicy violation
   	at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.penaltyDeath(ThreadPenaltyDeathWithIgnoresListener.kt:45)
   	at org.mozilla.fenix.perf.ThreadPenaltyDeathWithIgnoresListener.onThreadViolation(ThreadPenaltyDeathWithIgnoresListener.kt:39)
   	at android.os.StrictMode$AndroidBlockGuardPolicy.lambda$onThreadPolicyViolation$1(StrictMode.java:1827)
   	at android.os.-$$Lambda$StrictMode$AndroidBlockGuardPolicy$FxZGA9KtfTewqdcxlUwvIe5Nx9I.run(Unknown Source:4)
   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
   	at java.lang.Thread.run(Thread.java:923)
    Caused by: android.os.strictmode.DiskReadViolation
   	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1596)
   	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:71)
   	at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
   	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7533)
   	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
   	at java.io.File.exists(File.java:815)
   	at android.app.ContextImpl.getDataDir(ContextImpl.java:2539)
   	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:626)
   	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:853)
   	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:475)
   	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
   	at mozilla.components.support.base.ids.SharedIds.preferences(SharedIds.kt:88)
   	at mozilla.components.support.base.ids.SharedIds.getIdForTag(SharedIds.kt:31)
   	at mozilla.components.support.base.ids.SharedIdsHelper.getIdForTag(SharedIdsHelper.kt:30)
   	at mozilla.components.feature.privatemode.notification.AbstractPrivateNotificationService.getNotificationId(AbstractPrivateNotificationService.kt:78)
   	at mozilla.components.feature.privatemode.notification.AbstractPrivateNotificationService.onCreate(AbstractPrivateNotificationService.kt:116)
   	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192)
   	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
   	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
   	at android.os.Handler.dispatchMessage(Handler.java:106)
   	at android.os.Looper.loop(Looper.java:223)
   	at android.app.ActivityThread.main(ActivityThread.java:7656)
   	at java.lang.reflect.Method.invoke(Native Method)
   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Additional information

P.S. when observing logs during normal operation, I see a good few non-fatal strictmode violation warnings. Is that expected? Should I file issues for them when I see them?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21730)

**Comment by sum20156** [comment]
@Mugurell I checked the issue, it is because we are doing sharedprefs operation on UI thread, and on debug mode strict mode is configured to flag IO operation on UI thread. We have to move the code to a different thread.

**Comment by cpeterso** [comment]
Closing this GitHub issue because we're tracking the fix in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795459
