### ISSUE TITLE
Intermittent UI test failure - < SmokeTest.firstRunScreenTest>

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27328]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.assertWelcomeHeader(HomeScreenRobot.kt:686)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.access$assertWelcomeHeader(HomeScreenRobot.kt:1)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyWelcomeHeader(HomeScreenRobot.kt:108)
	at org.mozilla.fenix.ui.SmokeTest$firstRunScreenTest$1.invoke(SmokeTest.kt:122)
	at org.mozilla.fenix.ui.SmokeTest$firstRunScreenTest$1.invoke(SmokeTest.kt:115)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:597)
	at org.mozilla.fenix.ui.SmokeTest.firstRunScreenTest(SmokeTest.kt:115)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month
