### ISSUE TITLE
[Bug]: FIDO2 is not working in Firefox apk

### ISSUE THREAD

**Issue by Ramvarn** [mozilla-mobile/fenix#27367]
### Steps to reproduce

Generate an apk through debug, release and nightly and generate the apk.

Type the url: try-webauthn.appspot.com. Click Register a credential button, 

### Expected behaviour

Registration should be successful

### Actual behaviour

But registration not happened and biometric authentication not happened. Instead it displays an error as

"The operation was aborted"

### Device name

Vivo X70 Pro Plus, Nexus 

### Android version

Android 12, Android 11, Android 10

### Firefox release type

Firefox Nightly

### Firefox version

107.0a1 (Build#2015909251)

### Device logs

It throws an error as:

2022-10-11 18:02:15.313 11913-11913/? W/WebAuthnTokenManager: Failed to launch activity: 
    java.lang.IllegalStateException: No delegate attached
        at org.mozilla.geckoview.GeckoRuntime.startActivityForResult(GeckoRuntime.java:46)
        at org.mozilla.geckoview.WebAuthnTokenManager.lambda$makeCredential$2(WebAuthnTokenManager.java:5)
        at org.mozilla.geckoview.WebAuthnTokenManager.$r8$lambda$lxV1Gw97OXmWk5F1S1TWNMYm1hg(Unknown Source:0)
        at org.mozilla.geckoview.WebAuthnTokenManager$$ExternalSyntheticLambda0.onSuccess(Unknown Source:4)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:18)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8278)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

Similarly when clicked Authenticate,

2022-10-11 15:30:35.036 13439-13439/? W/WebAuthnTokenManager: Failed to get FIDO intent
    java.lang.IllegalStateException: No delegate attached
        at org.mozilla.geckoview.GeckoRuntime.startActivityForResult(GeckoRuntime.java:46)
        at org.mozilla.geckoview.WebAuthnTokenManager.lambda$getAssertion$6(WebAuthnTokenManager.java:5)
        at org.mozilla.geckoview.WebAuthnTokenManager.$r8$lambda$UTHifykiJMrgE92X3BsFw0xcqnE(Unknown Source:0)
        at org.mozilla.geckoview.WebAuthnTokenManager$$ExternalSyntheticLambda2.onSuccess(Unknown Source:4)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:18)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8278)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by kbrosnan** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794616

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
