### ISSUE TITLE
Firefox crashes when I press the address bar

### ISSUE THREAD

**Issue by Potaot** [mozilla-mobile/fenix#27384]
4f70a33e-3a94-47c6-b087-f1478af6f4a4
java.lang.RuntimeException: android.os.DeadSystemException
----
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:189)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$2.emit(SearchDialogFragment.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Emitters.kt:9)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:14)
	at mozilla.components.lib.state.ext.FragmentKt$consumeFlow$1$invokeSuspend$$inlined$filter$1$2.emit(Emitters.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:14)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2de9a97, Dispatchers.Main]
Caused by: android.os.DeadSystemException
	... 18 more

**Comment by Potaot** [comment]
My phone just needed a restart

**Comment by Mugurell** [comment]
This is a valid issue, also reported in https://github.com/mozilla-mobile/fenix/issues/27042.
To be fixed in the next Nightly.
