### ISSUE TITLE
[Bug]: IllegalStateException when returning to Firefox while a <select> is open

### ISSUE THREAD

**Issue by opekope2** [mozilla-mobile/fenix#27433]
### Steps to reproduce

1. Open https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
2. Open the select dropdown
3. Go to Android home screen or last apps overview
4. Return to Firefox

### Expected behaviour

Firefox continues to run and the \<select\> is still open

### Actual behaviour

Firefox closes down and/or crashes (Huawei doesn't show the Firefox stopped dialog)

### Device name

Honor 20 Lite

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

106.1.0

### Device logs

```
635e82e9-424a-45a4-a6d8-0d58cc4508e8
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{1f6e4bb} (d4aa4473-3c9c-4178-b170-6ac5f91cb7f3) not associated with a fragment manager.
----
java.lang.IllegalStateException: Fragment ChoiceDialogFragment{1f6e4bb} (d4aa4473-3c9c-4178-b170-6ac5f91cb7f3) not associated with a fragment manager.
	at androidx.fragment.app.Fragment.getParentFragmentManager(Fragment.java:2)
	at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:16)
	at androidx.fragment.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:1)
	at mozilla.components.feature.prompts.PromptFeature$start$1$3.emit(PromptFeature.kt:29)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifAnyChanged$$inlined$filter$1$2.emit(Emitters.kt:19)
	at mozilla.components.feature.prompts.PromptFeature$start$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:7)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@43c600, Dispatchers.Main]
```

### Additional information

This happened to me on a different website, so I tried another, and it seems like an issue on all websites.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21815)

**Comment by kbrosnan** [comment]
Does not crash in Geckoview example. Crashes Focus and Firefox.

**Comment by Alexandru2909** [comment]
The fix has been merged on AC, this issue can be tested by QA.
