### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. openWebsiteForSavedLoginTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27464]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:516)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$openWebsiteForSavedLoginTest$2.invoke(SettingsPrivacyTest.kt:276)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$openWebsiteForSavedLoginTest$2.invoke(SettingsPrivacyTest.kt:274)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:111)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.openWebsiteForSavedLoginTest(SettingsPrivacyTest.kt:274)
    
### Build: 10/19 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21829)

**Comment by AndiAJ** [comment]
Closing, it didn't fail for more than a month.
