### ISSUE TITLE
Crash on searchbar focus

### ISSUE THREAD

**Issue by Anfeket** [mozilla-mobile/fenix#27499]
### Steps to reproduce

1. Focus on the search bar

### Expected behaviour

I should be able to type into the search bar 

### Actual behaviour

Firefox crashes 

### Device name

Honor Play 

### Android version

Android 9

### Firefox release type

Firefox

### Firefox version

106.1.0

### Device logs

739af53d-c30e-431c-870d-c3e2ccd847e1
java.lang.RuntimeException: android.os.DeadSystemException
----
java.lang.RuntimeException: android.os.DeadSystemException
	at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:151)
	at org.mozilla.fenix.utils.ClipboardHandler.getText(ClipboardHandler.kt:2)
	at org.mozilla.fenix.utils.ClipboardHandler.extractURL(ClipboardHandler.kt:1)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$2.emit(SearchDialogFragment.kt:25)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Emitters.kt:9)
	at org.mozilla.fenix.search.SearchDialogFragment$observeClipboardState$1$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:14)
	at mozilla.components.lib.state.ext.FragmentKt$consumeFlow$1$invokeSuspend$$inlined$filter$1$2.emit(Emitters.kt:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e11eff6, Dispatchers.Main]
Caused by: android.os.DeadSystemException
	... 18 more

### Additional information

Crashes after focusing on the top bar, I have also reinstalled the app but the issue persists.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21847)

**Comment by Anfeket** [comment]
Nevermind, fixed after cleaning my clipboard
