### ISSUE TITLE
FNX3-16559 ⁃ [Bug] crash when running raptor twice - java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.raptor/org.mozilla.fenix.HomeActivity}

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#2756]
## Steps to reproduce
Install Fenix (Raptor release build) from https://index.taskcluster.net/v1/task/project.mobile.fenix.v2.branch.master.latest.raptor.arm/artifacts/public/target.apk.  Version is `package: name='org.mozilla.fenix.raptor' versionCode='1' versionName='1.0.1921' platformBuildVersionName=''`

Invoke this twice:

`adb shell am start -W -n org.mozilla.fenix.raptor/org.mozilla.fenix.IntentReceiverActivity -a android.intent.action.VIEW -d 'https://mozilla.github.io/tracking-test/'`

### Expected behavior
Page loads twice.

### Actual behavior
First time: page loads.  Second time: crash,

```
05-22 14:22:54.420   864  1585 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://mozilla.github.io/... flg=0x10000000 cmp=org.mozilla.fenix.raptor/org.mozilla.fenix.HomeActivity (has extras)} from uid 10213 on display 0
05-22 14:22:54.427  8572  9805 D SessionStorage/AutoSave: Saved state to disk [28ms]
05-22 14:22:54.514  8572  8603 D places_ffi: bookmarks_get_all_with_url
05-22 14:22:54.516   864   873 I art     : Background partial concurrent mark sweep GC freed 87698(3MB) AllocSpace objects, 5(116KB) LOS objects, 33% free, 20MB/30MB, paused 1.319ms total 143.222ms
05-22 14:22:54.528  8572  8572 W GeckoView: No GeckoSession attached to this GeckoView instance. Call setSession to attach a GeckoSession to this instance.
05-22 14:22:54.536  8572  8572 D AndroidRuntime: Shutting down VM
05-22 14:22:54.540  8572  8589 D places_ffi: bookmarks_get_all_with_url
05-22 14:22:54.542  8572  8572 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.raptor/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method)
05-22 14:22:54.543  8572  8572 I mozac/CrashReporter: Showing prompt
05-22 14:22:54.555  8572  8596 I GeckoSession: zerdatime 2151012 - chrome startup finished
05-22 14:22:54.565   864  1585 I ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.raptor/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10213 on display 0
--------- beginning of crash
05-22 14:22:54.569  8572  8572 E AndroidRuntime: FATAL EXCEPTION: main
05-22 14:22:54.569  8572  8572 E AndroidRuntime: Process: org.mozilla.fenix.raptor, PID: 8572
05-22 14:22:54.569  8572  8572 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.mozilla.fenix.raptor/org.mozilla.fenix.HomeActivity}: java.lang.RuntimeException: Failed to call observer method
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3429)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:2827)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2833)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.-wrap15(ActivityThread.java)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to call observer method
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:48)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:10)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:108)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:209)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:3)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:3)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:2)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:1)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6807)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	... 10 more
05-22 14:22:54.569  8572  8572 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Display already acquired
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:7)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:19)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:5)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:7)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:1)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:1)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:4)
05-22 14:22:54.569  8572  8572 E AndroidRuntime: 	... 33 more
05-22 14:22:54.625   864  8451 I OpenGLRenderer: Initialized EGL, version 1.4
05-22 14:22:54.625   864  8451 D OpenGLRenderer: Swap behavior 1
05-22 14:22:54.663  8572  8596 D GeckoScreenOrientation: unlocking
```

### Device information
* Android device: Motorola Nexus 6.
* Fenix version: see above.

**Comment by kbrosnan** [comment]
See similar #2314

**Comment by colintheshots** [comment]
This should be fixed by the other fixes to Display Already Acquired crashes. These steps don't happen in the app, but similar STRs existed which had created two BrowserFragments briefly and crashed GeckoView.
