### ISSUE TITLE
Save as PDF does not work in Reader View

### ISSUE THREAD

**Issue by jarifuri** [mozilla-mobile/fenix#27641]
### Steps to reproduce

1. Open the url `https://en.m.wikipedia.org/wiki/Firefox`
2. Click on the icon to toogle into the Reader View
3. Click on the menu (three dots ...) and share icon
4. Click on the Save as PDF
5. The dialog for the file download appears, click on the Download

### Expected behaviour

The pdf file is downloaded

### Actual behaviour

The message `Firefox Nigthly can't dowload this file type` appears.

### Device name

motorola moto g 7 power

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

108.0a1

### Additional information

It happens on all sites I have tried. In the normal mode (without the switching to the Reader View) it works, i.e. I can save these sites as the pdf file.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21908)

**Comment by jonalmeida** [comment]
Just ran into this as well.

Sometimes I receive the "Unable to generate PDF" with this trace:
```
 E  failed to add asset path '/data/app/~~Fq1khztNhGf5Rp6S9B6fCg==/org.mozilla.fenix.debug-AqrYf5sZPd0q9OdoK_Y7sg==/base.apk'
    java.io.IOException: Failed to load asset path /data/app/~~Fq1khztNhGf5Rp6S9B6fCg==/org.mozilla.fenix.debug-AqrYf5sZPd0q9OdoK_Y7sg==/base.apk
    	at android.content.res.ApkAssets.nativeLoad(Native Method)
    	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
    	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
    	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
    	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
    	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
    	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
    	at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
    	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
    	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2376)
    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
    	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
    	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
    	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
    	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
    	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
    	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
    	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
    	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
    	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
    	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
    	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
    	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
    	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at android.app.ActivityThread.main(ActivityThread.java:7842)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Sometimes I receive the same error as OP:
```
 E  failed to add asset path '/data/app/~~Fq1khztNhGf5Rp6S9B6fCg==/org.mozilla.fenix.debug-AqrYf5sZPd0q9OdoK_Y7sg==/base.apk'
    java.io.IOException: Failed to load asset path /data/app/~~Fq1khztNhGf5Rp6S9B6fCg==/org.mozilla.fenix.debug-AqrYf5sZPd0q9OdoK_Y7sg==/base.apk
    	at android.content.res.ApkAssets.nativeLoad(Native Method)
    	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
    	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
    	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
    	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
    	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
    	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
    	at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
    	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
    	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2376)
    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
    	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
    	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
    	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
    	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
    	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
    	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
    	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
    	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
    	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
    	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
    	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
    	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
    	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
    	at android.os.Handler.dispatchMessage(Handler.java:106)
    	at android.os.Looper.loopOnce(Looper.java:201)
    	at android.os.Looper.loop(Looper.java:288)
    	at android.app.ActivityThread.main(ActivityThread.java:7842)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by AdinaPetridean** [comment]
@jarifuri thank you for your report! The issue is still reproducible on: Firefox Nightly 108.0a1- 14/11 with Motorola Moto G9 plus (Android 11).

**Comment by shtstorm** [comment]
In the latest nightly, this shows up as an error while saving page as PDF: **Firefox Nightly can't download this file type**.

![Screenshot_20221209-144236](https://user-images.githubusercontent.com/79124442/206793318-65c17862-9d4c-4f67-a4ba-b575676ef583.png)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812124

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
