### ISSUE TITLE
[crash] UninitializedPropertyAccessException: lateinit property menu has not been initialized

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#27669]
Sentry nightly  low volume 
https://sentry.io/organizations/mozilla/issues/3709698449/?project=6295546

```
kotlin.UninitializedPropertyAccessException: lateinit property menu has not been initialized
    at org.mozilla.fenix.settings.logins.fragment.LoginDetailFragment.onPause(LoginDetailFragment.kt:77)
    at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:45)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:148)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1146)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:92)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:74)
    at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:4)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6759)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21918)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21918

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1805345

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
