### ISSUE TITLE
[Bug] Crash on close Mozilla preview in IM app

### ISSUE THREAD

**Issue by mishazawa** [mozilla-mobile/fenix#2767]
## Steps to reproduce
Open link in instant messaging app (f.e. telegram)

Press close button

### Expected behavior
Mozilla closes without crash report

### Actual behavior
Mozilla Preview open crash report popup

### Device information
* Android device: Xiaomi Redmi 4, Android 6.0.1 MMB29M
* Fenix version: 1.0.1921

**Comment by mishazawa** [comment]
Log cat debug log
```05-23 10:42:11.254 30562-30562/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix, PID: 30562
    java.lang.RuntimeException: Unable to stop activity {org.mozilla.fenix/org.mozilla.fenix.customtabs.CustomTabActivity}: java.lang.IllegalArgumentException: Required value was null.
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3802)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856)
        at android.app.ActivityThread.access$1500(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
     Caused by: java.lang.IllegalArgumentException: Required value was null.
        at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:5)
        at org.mozilla.fenix.browser.BrowserFragment.onStop(BrowserFragment.kt:3)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:10)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:110)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:200)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.Fragment.performStop(Fragment.java:7)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:110)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:200)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.FragmentController.dispatchStop(FragmentController.java:3)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:4)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1279)
        at android.app.Activity.performStop(Activity.java:6447)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3797)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3856) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5441) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) ```

**Comment by AaronMT** [comment]
Signature looks like one posted in https://github.com/mozilla-mobile/fenix/issues/2616
