### ISSUE TITLE
Intermittent UI test failure - < NavigationToolbarTest. verifyInsecurePageSecuritySubMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27752]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.assertSecureConnectionSubMenu(SiteSecurityRobot.kt:44)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobotKt.access$assertSecureConnectionSubMenu(SiteSecurityRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SiteSecurityRobot.verifySecureConnectionSubMenu(SiteSecurityRobot.kt:27)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyInsecurePageSecuritySubMenuTest$3.invoke(NavigationToolbarTest.kt:162)
	at org.mozilla.fenix.ui.NavigationToolbarTest$verifyInsecurePageSecuritySubMenuTest$3.invoke(NavigationToolbarTest.kt:159)
	at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openSiteSecuritySheet(BrowserRobot.kt:1068)
	at org.mozilla.fenix.ui.NavigationToolbarTest.verifyInsecurePageSecuritySubMenuTest(NavigationToolbarTest.kt:159)
    
### Build: 11/7 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21949)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21949

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
