### ISSUE TITLE
Intermittent UI test failure - < WebControlsTest. externalLinkTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27790]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:72)
	at org.mozilla.fenix.ui.WebControlsTest$externalLinkTest$2.invoke(WebControlsTest.kt:162)
	at org.mozilla.fenix.ui.WebControlsTest$externalLinkTest$2.invoke(WebControlsTest.kt:160)
	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:138)
	at org.mozilla.fenix.ui.WebControlsTest.externalLinkTest(WebControlsTest.kt:160)
    
### Build: 11/9 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21966)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-21966

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for more than a month.
