### ISSUE TITLE
Intermittent UI test failure - < SearchTest. deleteSearchGroupFromHistoryTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27845]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyRecentlyVisitedSearchGroupDisplayed(HomeScreenRobot.kt:202)
	at org.mozilla.fenix.ui.SearchTest$deleteSearchGroupFromHistoryTest$9.invoke(SearchTest.kt:402)
	at org.mozilla.fenix.ui.SearchTest$deleteSearchGroupFromHistoryTest$9.invoke(SearchTest.kt:401)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:589)
	at org.mozilla.fenix.ui.SearchTest.deleteSearchGroupFromHistoryTest(SearchTest.kt:401)
    
### Build: 11/15 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21990)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/17 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5231687764776446739/executions/bs.294501d7cd522a17/testcases/4/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyRecentlyVisitedSearchGroupDisplayed(HomeScreenRobot.kt:202)
	at org.mozilla.fenix.ui.SearchTest$deleteSearchGroupFromHistoryTest$9.invoke(SearchTest.kt:402)
	at org.mozilla.fenix.ui.SearchTest$deleteSearchGroupFromHistoryTest$9.invoke(SearchTest.kt:401)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:589)
	at org.mozilla.fenix.ui.SearchTest.deleteSearchGroupFromHistoryTest(SearchTest.kt:401)

**Comment by AndiAJ** [comment]
Closing, as it didn't fail for approx. a month.
