### ISSUE TITLE
Firefox for Android crashes submitting form

### ISSUE THREAD

**Issue by Aimhere2k** [mozilla-mobile/fenix#27863]
On myprevea.com, attempting to make a payment. I enter my payment details, tap Submit, and Firefox crashes to Android home screen. 

8567fb38-eb0c-4efe-b38b-d27163e88f5d
java.lang.IllegalStateException: Fragment CreditCardSaveDialogFragment{ecfb7a6} (359434e7-2c87-4af5-9f08-26406a3d393c) not attached to a context.
----
java.lang.IllegalStateException: Fragment CreditCardSaveDialogFragment{ecfb7a6} (359434e7-2c87-4af5-9f08-26406a3d393c) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:2)
	at mozilla.components.feature.prompts.creditcard.CreditCardSaveDialogFragment$updateUI$1$1.invokeSuspend(CreditCardSaveDialogFragment.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b7de1f5, Dispatchers.IO]

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21996)

**Comment by kbrosnan** [comment]
It would be helpful to get the crash ID URL as shown in https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information. I believe this crash stack is redacted.

**Comment by csadilek** [comment]
This needs a check to see if the fragment is still attached when the IO operation completes.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812181

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
