### ISSUE TITLE
Intermittent UI test failure - < manageDownloadsInDownloadsMenuTest. manageDownloadsInDownloadsMenuTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#27894]
### Stacktrace:
java.lang.AssertionError: The file was not deleted
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadedFileOnStorage(TestHelper.kt:167)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:157)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:153)
    
### Build: 11/17 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22010)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/23 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5588685322309942415/executions/bs.9b160b7fcbd88d5a/testcases/3/test-cases)

java.lang.AssertionError: The file was not deleted
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadedFileOnStorage(TestHelper.kt:167)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:157)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:153)

**Comment by sv-ohorvath** [comment]
Flaky 2x on 11/24: [link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8568330469005949241/executions/bs.74d4a5243cb7142a)

**Comment by AndiAJ** [comment]
Flaky 1x on 11/28 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5810295065460200808/executions/bs.46305913bd6e872a/testcases/3/test-cases)

java.lang.AssertionError: The file was not deleted
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.mozilla.fenix.helpers.TestHelper.deleteDownloadedFileOnStorage(TestHelper.kt:167)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:157)
	at org.mozilla.fenix.ui.DownloadTest$manageDownloadsInDownloadsMenuTest$7.invoke(DownloadTest.kt:153)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:169)
	at org.mozilla.fenix.ui.DownloadTest.manageDownloadsInDownloadsMenuTest(DownloadTest.kt:153)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807286

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
