### ISSUE TITLE
Repeatable Crash in Firefox beta on given website 

### ISSUE THREAD

**Issue by thebp2** [mozilla-mobile/fenix#27912]
Crash info:
d476f335-f597-4218-adb8-12c42ce4dd17
mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error executing SQL: Integer -1 out of range at index 12
----
mozilla.appservices.places.uniffi.PlacesApiException$UnexpectedPlacesException: reason=Error executing SQL: Integer -1 out of range at index 12
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:21)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.read(places.kt:1)
	at mozilla.appservices.places.uniffi.FfiConverter$DefaultImpls.liftFromRustBuffer(places.kt:13)
	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(places.kt:6)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:2)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.liftFromRustBuffer(places.kt:1)
	at mozilla.appservices.places.uniffi.FfiConverterRustBuffer$DefaultImpls.lift(places.kt:7)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:3)
	at mozilla.appservices.places.uniffi.FfiConverterTypePlacesApiError.lift(places.kt:2)
	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:2)
	at mozilla.appservices.places.uniffi.PlacesApiException$ErrorHandler.lift(places.kt:1)
	at mozilla.appservices.places.uniffi.PlacesConnection.applyObservation(places.kt:163)
	at mozilla.appservices.places.PlacesWriterConnection.noteObservation(PlacesConnection.kt:24)
	at mozilla.components.browser.storage.sync.PlacesHistoryStorage$recordObservation$2.invokeSuspend(PlacesHistoryStorage.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@eac78ac, Dispatchers.IO]

Url: https://www.smbc-comics.com/comic/emotional-stripper

Version info: 
108.0b2 (Build #2015916427), 211d3465f+
AC: 108.0.1, ad80021 b41
GV: 108.0-20221117185908
AS: 95.0.1

2022-11-18T01:50:14.009992

Every time I try to go to that URL Firefox beta crashes. I've also observed this on some other websites today but none I can share links for.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22017)

**Comment by thebp2** [comment]
Same crash on https://www.smbc-comics.com/comic/parrot

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1812414

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
