### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest. openPocketDiscoverMoreTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28000]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:72)
	at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:276)
	at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:275)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.clickPocketDiscoverMoreButton(HomeScreenRobot.kt:711)
	at org.mozilla.fenix.ui.HomeScreenTest.openPocketDiscoverMoreTest(HomeScreenTest.kt:275)
    
### Build: 11/28 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22065)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807285

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
