### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest. undoDeleteSearchEngineTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28014]
### Stacktrace:
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: '(view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing")' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing")
     Got: no descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing" was found
View Details: RadioGroup{id=2131297433, res-name=search_engine_group, visibility=VISIBLE, width=1080, height=651, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}

	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:12)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobotKt.assertEngineListContains(SettingsSubMenuSearchRobot.kt:372)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobotKt.access$assertEngineListContains(SettingsSubMenuSearchRobot.kt:1)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuSearchRobot.verifyEngineListContains(SettingsSubMenuSearchRobot.kt:173)
	at org.mozilla.fenix.ui.SettingsSearchTest$undoDeleteSearchEngineTest$4.invoke(SettingsSearchTest.kt:331)
	at org.mozilla.fenix.ui.SettingsSearchTest$undoDeleteSearchEngineTest$4.invoke(SettingsSearchTest.kt:326)
	at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openSearchSubMenu(SettingsRobot.kt:146)
	at org.mozilla.fenix.ui.SettingsSearchTest.undoDeleteSearchEngineTest(SettingsSearchTest.kt:326)
	... 57 trimmed
Caused by: junit.framework.AssertionFailedError: '(view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing")' doesn't match the selected view.
Expected: (view is an instance of android.view.ViewGroup and has descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing")
     Got: no descendant matching an instance of android.widget.TextView and view.getText() with or without transformation to match: is "Bing" was found
View Details: RadioGroup{id=2131297433, res-name=search_engine_group, visibility=VISIBLE, width=1080, height=651, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@YYYYYY, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:16)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:7)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:14)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    
### Build: 11/29 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22074)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807284

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
