### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest#openPocketDiscoverMoreTest >

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#28098]
`openPocketDiscoverMoreTest`

https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8898325441069935240

```Kotlin
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:72)
at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:297)
at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:296)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.clickPocketDiscoverMoreButton(HomeScreenRobot.kt:711)
at org.mozilla.fenix.ui.HomeScreenTest.openPocketDiscoverMoreTest(HomeScreenTest.kt:296)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22107)

**Comment by AndiAJ** [comment]
Flaky 1x on 12/6 Main [Firebase link](https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8728299300571178214/executions/bs.4e08ca591242994d/testcases/4/test-cases)

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.ui.robots.BrowserRobot.verifyUrl(BrowserRobot.kt:72)
	at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:297)
	at org.mozilla.fenix.ui.HomeScreenTest$openPocketDiscoverMoreTest$4.invoke(HomeScreenTest.kt:296)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.clickPocketDiscoverMoreButton(HomeScreenRobot.kt:711)
	at org.mozilla.fenix.ui.HomeScreenTest.openPocketDiscoverMoreTest(HomeScreenTest.kt:296)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807282

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
