### ISSUE TITLE
Intermittent UI test failure - < SettingsSearchTest. toggleSearchEnginesShortcutListTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28109]
### Stacktrace:
java.lang.AssertionError: Failed to perform isDisplayed check.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'Google' (ignoreCase: false))
However, the unmerged tree contains '1' node that matches. Are you missing `useUnmergedNode = true` in your finder?

	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
	at androidx.compose.ui.test.AndroidAssertions_androidKt.checkIsDisplayed(AndroidAssertions.android.kt:29)
	at androidx.compose.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:33)
	at org.mozilla.fenix.ui.robots.SearchRobot.verifySearchEngineShortcuts(SearchRobot.kt:292)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchEnginesShortcutListTest$9.invoke(SettingsSearchTest.kt:472)
	at org.mozilla.fenix.ui.SettingsSearchTest$toggleSearchEnginesShortcutListTest$9.invoke(SettingsSearchTest.kt:461)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openSearch(HomeScreenRobot.kt:451)
	at org.mozilla.fenix.ui.SettingsSearchTest.toggleSearchEnginesShortcutListTest(SettingsSearchTest.kt:461)
    
### Build: 12/6 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22110)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807281

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
