### ISSUE TITLE
Intermittent UI test failure - < SettingsAddonsTest. verifyAddonsCanBeUninstalled >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28145]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.clickInstallAddon(SettingsSubMenuAddonsManagerRobot.kt:54)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot$installAddon$3.invoke(SettingsSubMenuAddonsManagerRobot.kt:134)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot$installAddon$3.invoke(SettingsSubMenuAddonsManagerRobot.kt:133)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openAddonsManagerMenu(ThreeDotMenuMainRobot.kt:381)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobot.installAddon(SettingsSubMenuAddonsManagerRobot.kt:133)
	at org.mozilla.fenix.ui.SettingsAddonsTest$verifyAddonsCanBeUninstalled$1.invoke(SettingsAddonsTest.kt:101)
	at org.mozilla.fenix.ui.SettingsAddonsTest$verifyAddonsCanBeUninstalled$1.invoke(SettingsAddonsTest.kt:100)
	at org.mozilla.fenix.ui.robots.SettingsSubMenuAddonsManagerRobotKt.addonsMenu(SettingsSubMenuAddonsManagerRobot.kt:283)
	at org.mozilla.fenix.ui.SettingsAddonsTest.verifyAddonsCanBeUninstalled(SettingsAddonsTest.kt:100)
    
### Build: 12/8 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22126)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807280

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
