### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest. verifyPocketLearnMoreLinkTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28209]
### Stacktrace:
java.lang.AssertionError: Assert failed: The component is not displayed!
	at androidx.compose.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:35)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyPoweredByPocket(HomeScreenRobot.kt:417)
	at org.mozilla.fenix.ui.HomeScreenTest$verifyPocketLearnMoreLinkTest$3.invoke(HomeScreenTest.kt:330)
	at org.mozilla.fenix.ui.HomeScreenTest$verifyPocketLearnMoreLinkTest$3.invoke(HomeScreenTest.kt:329)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:796)
	at org.mozilla.fenix.ui.HomeScreenTest.verifyPocketLearnMoreLinkTest(HomeScreenTest.kt:329)
    
### Build: 12/13 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22151)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807277

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
