### ISSUE TITLE
Intermittent UI test failure - < SmokeTest. firstRunScreenTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28210]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.helpers.MatcherHelper.assertItemWithResIdExists(MatcherHelper.kt:46)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyHomeScreenAppBarItems(HomeScreenRobot.kt:93)
	at org.mozilla.fenix.ui.SmokeTest$firstRunScreenTest$1.invoke(SmokeTest.kt:113)
	at org.mozilla.fenix.ui.SmokeTest$firstRunScreenTest$1.invoke(SmokeTest.kt:112)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:792)
	at org.mozilla.fenix.ui.SmokeTest.firstRunScreenTest(SmokeTest.kt:112)
    
### Build: 12/14 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22152)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807276

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
