### ISSUE TITLE
Intermittent UI test failure - < SettingsPrivacyTest. saveLoginsInPWATest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28246]
### Stacktrace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.test.uiautomator.UiObject2.click()' on a null object reference
	at org.mozilla.fenix.ui.robots.BrowserRobot.saveLoginFromPrompt(BrowserRobot.kt:416)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:689)
	at org.mozilla.fenix.ui.SettingsPrivacyTest$saveLoginsInPWATest$5.invoke(SettingsPrivacyTest.kt:685)
	at org.mozilla.fenix.ui.robots.AddToHomeScreenRobot$Transition.openHomeScreenShortcut(AddToHomeScreenRobot.kt:77)
	at org.mozilla.fenix.ui.SettingsPrivacyTest.saveLoginsInPWATest(SettingsPrivacyTest.kt:685)

    
### Build: 12/16 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22164)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807273

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
