### ISSUE TITLE
Intermittent UI test failure - < HomeScreenTest. dismissOnboardingWithPageLoadTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28247]
### Stacktrace:
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.mozilla.fenix.helpers.MatcherHelper.assertItemContainingTextExists(MatcherHelper.kt:52)
	at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyWelcomeHeader(HomeScreenRobot.kt:196)
	at org.mozilla.fenix.ui.HomeScreenTest$dismissOnboardingWithPageLoadTest$2.invoke(HomeScreenTest.kt:214)
	at org.mozilla.fenix.ui.HomeScreenTest$dismissOnboardingWithPageLoadTest$2.invoke(HomeScreenTest.kt:213)
	at org.mozilla.fenix.ui.robots.HomeScreenRobotKt.homeScreen(HomeScreenRobot.kt:792)
	at org.mozilla.fenix.ui.HomeScreenTest.dismissOnboardingWithPageLoadTest(HomeScreenTest.kt:213)

    
### Build: 12/16 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22165)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807272

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
