### ISSUE TITLE
Intermittent UI test failure - < DownloadFileTypesTest. downloadMultipleFileTypesTest >

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#28296]
### Stacktrace:
java.lang.AssertionError: Downloads list either empty or not displayed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.mozilla.fenix.ui.robots.DownloadRobot.waitForDownloadsListToExist(DownloadRobot.kt:65)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$7.invoke(DownloadFileTypesTest.kt:59)
	at org.mozilla.fenix.ui.DownloadFileTypesTest$downloadMultipleFileTypesTest$7.invoke(DownloadFileTypesTest.kt:58)
	at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openDownloadsManager(ThreeDotMenuMainRobot.kt:178)
	at org.mozilla.fenix.ui.DownloadFileTypesTest.downloadMultipleFileTypesTest(DownloadFileTypesTest.kt:58)

    
### Build:  12/22 Main

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22188)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807269

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
