### ISSUE TITLE
FNX3-16666 ⁃ [Bug] Crash when trying to rate the app on a devices without the play store app

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/fenix#2903]
## Steps to reproduce
1. Go to settings
1. Tap "Rate on Google Play"

### Expected behavior
The app takes you to the play store website listing.

### Actual behavior
The app crashes.

### Crash
[Sentry](https://sentry.prod.mozaws.net/operations/fenix/issues/5841685/)

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=org.mozilla.fenix }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
    at android.app.Activity.startActivityForResult(Activity.java:4586)
    at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:6)
    at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:2)
    at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:2)
    at androidx.fragment.app.Fragment.startActivity(Fragment.java:3)
    at androidx.fragment.app.Fragment.startActivity(Fragment.java:1)
    at org.mozilla.fenix.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:27)
    at androidx.preference.Preference.performClick(Preference.java:7)
    at androidx.preference.Preference.performClick(Preference.java:1)
    at androidx.preference.Preference$1.onClick(Preference.java:1)
    at android.view.View.performClick(View.java:6614)
    at android.view.View.performClickInternal(View.java:6587)
    at android.view.View.access$3100(View.java:784)
    at android.view.View$PerformClick.run(View.java:26125)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6715)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by abodea** [comment]
Verified as fixed on the latest **`build 1.0.1922 (#11490609) 5/29 with Samsung Galaxy Note 9(Android 8.1.0), OnePlus 6 (Android 9).`**
