### ISSUE TITLE
IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and ...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#2932]
https://sentry.prod.mozaws.net/operations/fenix/issues/5340635/

```
IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{7cec73c position=6 id=4, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{eb82fe8 position=3 id=4, oldPos=-1, pLpos:-1} mozilla.components.browser.awesomebar.BrowserAwesomeBar{8c2445f VFED..... ......ID 0,148-1080,1172 #7f08009b app:id/awesomeBar}, adapter:mozilla.components.browser.awesomebar.SuggestionsAdapter@913cea1, layout:androidx.recyclerview.widget.LinearLayoutManager@7ea38c6, context:org.mozilla.fenix.HomeActivity@6a7d8dc
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:48)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
    at android.view.View.layout(View.java:20831)
    at android.view.ViewGroup.layout(ViewGroup.java:6203)
    at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
...
(49 additional frame(s) were not displayed)

Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{7cec73c position=6 id=4, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{eb82fe8 position=3 id=4, oldPos=-1, pLpos:-1} mozilla.components.browser.awesomebar.BrowserAwesomeBar{8c2445f VFED..... ......ID 0,148-1080,1172 #7f08009b app:id/awesomeBar}, adapter:mozilla.components.browser.awesomebar.SuggestionsAdapter@913cea1, layout:androidx.recyclerview.widget.LinearLayoutManager@7ea38c6, context:org.mozilla.fenix.HomeActivity@6a7d8dc
```

**Comment by pocmo** [comment]
We fixed sth. like that in AC some time ago. I am surprised that this is happening in Fenix.

**Comment by csadilek** [comment]
Landed one fix and additional error handling. If this still happens with ac.version 0.55.0, we should have more insights.

**Comment by csadilek** [comment]
We're no longer seeing this crash in Sentry since 0.56. Closing.
