### ISSUE TITLE
FNX3-16698 ⁃ [Bug] launches to blank screen and hangs on Nexus 10

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#2945]
## Steps to reproduce
* Install a fresh version of Firefox Preview
* Launch it

### Expected behavior
* App runs

### Actual behavior
* App hangs
* [traces.txt](https://gist.github.com/kbrosnan/6e408ba39dd4dee93bd2c1f4a94b53b6)

```
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x72fc7000 self=0xb70292e8
  | sysTid=9986 nice=0 cgrp=default sched=0/0 handle=0xb6f26bec
  | state=S schedstat=( 465968241 229220866 1575 ) utm=35 stm=11 core=0 HZ=100
  | stack=0xbe4ef000-0xbe4f1000 stackSize=8MB
  | held mutexes=
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:3)
  - waiting to lock <0x125805c2> (a kotlin.SynchronizedLazyImpl) held by thread 15
  at org.mozilla.fenix.components.Search.getSearchEngineManager(Search.kt:-1)
  at org.mozilla.fenix.components.Components$useCases$2.invoke(Components.kt:3)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  - locked <@addr=0x12e353c0> (a kotlin.SynchronizedLazyImpl)
  at org.mozilla.fenix.components.Components.getUseCases(Components.kt:-1)
  at org.mozilla.fenix.components.Components$utils$2.invoke(Components.kt:1)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  - locked <@addr=0x12e353e0> (a kotlin.SynchronizedLazyImpl)
  at org.mozilla.fenix.components.Components.getUtils(Components.kt:-1)
  at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:1)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  - locked <@addr=0x12e35340> (a kotlin.SynchronizedLazyImpl)
  at org.mozilla.fenix.components.Components.getBackgroundServices(Components.kt:-1)
  at org.mozilla.fenix.home.HomeFragment.currentMode(HomeFragment.kt:2)
  at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:3)
  at androidx.fragment.app.Fragment.performCreateView(Fragment.java:5)
  at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:88)
  at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
  at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
  at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
  at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:4)
  at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:3)
  at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:8)
  at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:99)
  at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
  at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:209)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
  at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:3)
  at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:6)
  at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
  at android.app.Activity.performStart(Activity.java:6006)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
  at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

### Device information
* Android device:  Nexus 10 Running Android 5.1
* Fenix version: May 28th build

**Comment by kbrosnan** [comment]
Nexus 9 is also affected. We should block these devices if we are not going to fix this before MVP.

**Comment by colintheshots** [comment]
Lesson learned: Always make sure you or the library method you're using specifies a dispatcher when using Kotlin Coroutines. The default dispatcher is almost always the wrong answer. I believe the default thread pool size still equals # of CPUs plus one. Using the default dispatcher when the IO dispatcher is needed will result in deadlocks, livelocks, and ANRs which only appear on cheaper devices with fewer CPUs. It's very common that these issues do not become noticeable until an app is deployed to production.

**Comment by colintheshots** [comment]
This probably should have been an MVP blocker. I didn't realize this wasn't a single device issue.

**Comment by sv-ohorvath** [comment]
I only have a Nexus 9 tablet on which this was happening. It looks like it's fixed for me on the 7/3 nightly build. @kbrosnan could you confirm this too on your Nexus?
