### ISSUE TITLE
FNX3-16856 ⁃ [Bug] Pre-launch report: IllegalStateException: CameraDevice was already closed

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3208]
When uploading APKs Google runs automated tests on devices and generates a "Pre-launch report". During those tests the following crash happened.

Stacktrace:

```
FATAL EXCEPTION: CameraBackground
Process: org.mozilla.fenix, PID: 14708
java.lang.IllegalStateException: CameraDevice was already closed
	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2217)
	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:932)
	at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:979)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:239)
	at mozilla.components.feature.qr.QrFragment$createCameraPreviewSession$$inlined$let$lambda$1.onConfigured(QrFragment.kt:11)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
	at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:251)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

Device:

```
Screen Size
720 × 1280
Test Duration
300 seconds
Screen Density (dpi)
320
Model Name
Xperia XZ1 Compact
RAM
4096 MB
Manufacturer
Sony
OpenGL ES Version
3.2
Android Version
Android 8.0
Native Platform
armeabi-v7a
Locale
en_US
CPU Make
Qualcomm
CPU Model
MSM8998
```

**Comment by csadilek** [comment]
Assigning this to me to land a fix in A-C.
