### ISSUE TITLE
FNX3-16857 ⁃ [Bug] Pre-launch report: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Collection.contains(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3209]
Sentry issue: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5910805/

When uploading APKs Google runs automated tests on devices and generates a "Pre-launch report". During those tests the following crash happened.

Stacktrace

```
FATAL EXCEPTION: ControllerMessenger
Process: org.mozilla.fenix, PID: 9843
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Collection.contains(java.lang.Object)' on a null object reference
	at androidx.collection.MapCollections.retainAllHelper(MapCollections.java:4)
	at androidx.fragment.app.FragmentTransition.captureOutSharedElements(FragmentTransition.java:11)
	at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:51)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:81)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:1)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:77)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
	at androidx.test.espresso.action.Tap.c(Tap.java:8)
	at androidx.test.espresso.action.Tap.b(Tap.java:18)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:3)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

Device

```
Screen Size
1440 × 2560
Test Duration
300 seconds
Screen Density (dpi)
640
Model Name
Moto Z
RAM
3072 MB
Manufacturer
Motorola
OpenGL ES Version
3.2
Android Version
Android 7.0
Native Platform
armeabi-v7a
Locale
es_ES
CPU Make
Qualcomm
CPU Model
MSM8996
```

**Comment by sarentz** [comment]
This one went up a lot around May 30th and then went down but is still happening at a volume that probably should be addressed ...

<img width="253" alt="Screen Shot 2019-06-06 at 9 45 21 AM" src="https://user-images.githubusercontent.com/22330190/59037765-e9e61d00-883f-11e9-9d86-fb3ac85ff786.png">

**Comment by colintheshots** [comment]
I haven't been able to reproduce this in master with any of my devices and the rate of crashes appears to be abating in Sentry. This could have been correlated with another crash we resolved.

**Comment by colintheshots** [comment]
This bug report is closely related to the cause of the crash. We need to be careful with popping fragments when used with shared element transitions. https://issuetracker.google.com/issues/120507394

**Comment by vesta0** [comment]
We haven't been reliably able to reproduce this. Please re-open if it happens again.
