### ISSUE TITLE
FNX3-16876 ⁃ IllegalArgumentException: navigation destination org.mozilla.fenix:id/action_browserFragment_to_homeFragment is unknown to ...

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#3238]
STR:

1. Open the browser to the browser screen.
1. Press the lock icon and the tab counter at the same time. Or press the toolbar and the tab counter at the same time.

Expected: One of the two events will trigger.

Actual: Crash with the following stack trace.

https://sentry.prod.mozaws.net/operations/fenix/issues/5503452/

```
IllegalArgumentException: navigation destination org.mozilla.fenix:id/action_browserFragment_to_homeFragment is unknown to this NavController
    at org.mozilla.fenix.components.toolbar.ToolbarIntegration$$special$$inlined$run$lambda$1.invoke(ToolbarIntegration.kt:15)
    at org.mozilla.fenix.components.toolbar.TabCounterToolbarButton$createView$$inlined$apply$lambda$1.onClick(TabCounterToolbarButton.kt:3)
...
(9 additional frame(s) were not displayed)

navigation destination org.mozilla.fenix:id/action_browserFragment_to_homeFragment is unknown to this NavController
```

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest build 1.0.1923 (#11580610), with Samsung Galaxy S8 (Android 9), and Huawei P9 Lite (Android 6).
