### ISSUE TITLE
SessionSuggestionProvider returned duplicate suggestion IDs

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#3313]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5919435/

Looks like one of the guards we built in is now throwing. However, this can only happen if we have a duplicate session ID in `SessionManager`, as this error indicates that a single `onInputChanged` on a single provider instance returned duplicates:

```
java.lang.IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs
    at mozilla.components.browser.awesomebar.BrowserAwesomeBar.processProviderSuggestions$browser_awesomebar_release(BrowserAwesomeBar.kt:6)
    at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(BrowserAwesomeBar.kt:7)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6744)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

**Comment by csadilek** [comment]
Fixed by: https://github.com/mozilla-mobile/fenix/pull/3320/commits/88b7c4f5e3a65583074a981c578f65b126290c57
