### ISSUE TITLE
FNX3-16992 ⁃ [Bug] crash when second webrtc tab is opened

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#3406]
## Steps to reproduce
* Visit https://appr.tc
* Click join room
* Open a second https://appr.tc link from email or other external source

### Expected behavior
does not crash

### Actual behavior
Crash

```
2019-06-12 16:20:22.387 951-951/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix, PID: 951
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:48)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:19)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:7)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:19)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:5)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
        at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
        at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:7)
        at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:1)
        at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:1)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:4)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:48) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:105) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:19) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 
        at android.app.Activity.performStart(Activity.java:7165) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

### Device information
* Android device: Pixel 3
* Fenix version: June 12th build

**Comment by AaronMT** [comment]
Similar stack, probably similar issue from https://github.com/mozilla-mobile/fenix/issues/2314 (CC @colintheshots)

**Comment by colintheshots** [comment]
"Display already acquired" usually happens when you get two GeckoViews, most likely with the same session ID.

**Comment by ekager** [comment]
Are you still seeing this crash?

**Comment by softvision-miralobontiu** [comment]
I was not able to reproduce the crash on the latest Nightly build 8/7 (#12191937) with OnePlus (Android 9), and Xiaomi Mi 8 Lite (Android 9).
