### ISSUE TITLE
FNX3-17131 ⁃ [Bug][Once] Fenix crashes after opening camera from "scan pairing code in desktop Firefox" menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#3580]
## Prerequisites
You have Talkback option enabled from your Android settings.

## Steps to reproduce
1. Launch Fenix.
1. Login with valid credentials.
1. Logout.
1. Select and access `Turn on Sync`.
1. Select and access `Scan pairing code in desktop Firefox`.
1. Tap on `Open Camera`.

### Expected behavior
The camera is opened and no issues are displayed.

### Actual behavior
Fenix crashes after tapping on the `Open Camera`.

* Android device: **`Samsung Galaxy Note 9(Android 8.1.0).`**
* Fenix version: **`6/19 1.0.0-rc.2`** 
    1. Notes
* [Log_long.txt](https://github.com/mozilla-mobile/fenix/files/3309914/Log_long.txt)
* [Log_short.txt](https://github.com/mozilla-mobile/fenix/files/3309915/Log_short.txt)

**Please note that I was able to reproduce this issue only once out of 10 tries.**

**Comment by sblatz** [comment]
This will impact onboarding of new users to FxA. We should consider fixing ASAP.

**Comment by kbrosnan** [comment]
Crash looks to be 
```
2019-06-20 13:07:31.607 9678-9678/? E/KeyFrames: unable to load
    java.lang.NoSuchMethodException: androidx.constraintlayout.motion.widget.KeyAttributes.<init> []
        at java.lang.Class.getConstructor0(Class.java:2321)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.constraintlayout.motion.widget.KeyFrames.<clinit>(KeyFrames.java:2)
        at androidx.constraintlayout.motion.widget.MotionScene.<init>(MotionScene.java:18)
        at androidx.constraintlayout.motion.widget.MotionLayout.init(MotionLayout.java:6)
        at androidx.constraintlayout.motion.widget.MotionLayout.<init>(MotionLayout.java:64)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at org.mozilla.fenix.home.HomeFragment.onCreateView(HomeFragment.kt:2)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:88)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:6)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:54)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:11)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:4)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:4)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:99)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:210)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1341)
        at android.app.Activity.performStart(Activity.java:7278)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

Do not see any matching stacks in Sentry.

**Comment by kbrosnan** [comment]
This breaks the pair function on a couple devices I tried. 

```
09-06 16:07:01.161 E/AndroidRuntime(24955): FATAL EXCEPTION: main
09-06 16:07:01.161 E/AndroidRuntime(24955): Process: org.mozilla.fenix, PID: 24955
09-06 16:07:01.161 E/AndroidRuntime(24955): kotlin.KotlinNullPointerException
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at io.reactivex.plugins.RxJavaPlugins.throwNpe(RxJavaPlugins.java:1)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at mozilla.components.feature.accounts.FirefoxAccountsAuthFeature$interceptor$1.onLoadRequest(FirefoxAccountsAuthFeature.kt:15)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at org.mozilla.fenix.AppRequestInterceptor.onLoadRequest(AppRequestInterceptor.kt:16)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:8)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:40)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:1)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at android.os.Handler.handleCallback(Handler.java:883)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at android.os.Looper.loop(Looper.java:214)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at java.lang.reflect.Method.invoke(Native Method)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-06 16:07:01.161 E/AndroidRuntime(24955): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
09-06 16:07:01.232 I/DropBoxManagerService( 1507): add tag=data_app_crash isTagEnabled=true flags=0x2
09-06 16:07:01.233 W/ActivityTaskManager( 1507):   Force finishing activity org.mozilla.fenix/.customtabs.AuthCustomTabActivity
09-06 16:07:01.245 W/BroadcastQueue( 1507): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-06 16:07:01.245 W/BroadcastQueue( 1507): Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-06 16:07:01.313 I/ActivityManager( 1507): Process org.mozilla.fenix:tab (pid 25044) has died: fore BTOP
09-06 16:07:01.314 W/ActivityManager( 1507): Scheduling restart of crashed service org.mozilla.fenix/org.mozilla.gecko.process.GeckoServiceChildProcess$tab in 1000ms
09-06 16:07:01.350 I/WindowManager( 1507): WIN DEATH: Window{2c161b1 u0 org.mozilla.fenix/org.mozilla.fenix.customtabs.AuthCustomTabActivity}
09-06 16:07:01.351 I/ActivityManager( 1507): Process org.mozilla.fenix (pid 24955) has died: fore TOP 
```

**Comment by boek** [comment]
This was reported to have been fixed in A-C. Can we verify it's fixed?

**Comment by kbrosnan** [comment]
Verified this on a Pixel 3 which was crashing before.
