### ISSUE TITLE
publicsuffixlist: ArrayIndexOutOfBoundsException: length=0; index=0

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3625]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5974641/

```
ArrayIndexOutOfBoundsException: length=0; index=0
    at mozilla.components.lib.publicsuffixlist.ext.ByteArrayKt.binarySearch(ByteArray.kt:5)
    at mozilla.components.lib.publicsuffixlist.PublicSuffixListData.getPublicSuffixOffset(PublicSuffixListData.kt:8)
    at mozilla.components.lib.publicsuffixlist.PublicSuffixList$stripPublicSuffix$1.invokeSuspend(PublicSuffixList.kt:3)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
...
(3 additional frame(s) were not displayed)

length=0; index=0
```

**Comment by pocmo** [comment]
A fix for this landed in Android Components and is scheduled to be released with 2.0.0 (~July 2nd). If it's more urgent we can create a 0.56.x or 1.0.x release including this fix.

**Comment by sblatz** [comment]
@pocmo We're now on the 2.0.0-SNAPSHOT. Is this ready for QA?

**Comment by liuche** [comment]
Ready for QA.
