### ISSUE TITLE
IllegalStateException: Unable to create directory: /storage/sdcard0/Download

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3626]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5981647/

```
IllegalStateException: Unable to create directory: /storage/sdcard0/Download
    at android.app.DownloadManager$Request.setDestinationInExternalPublicDir(DownloadManager.java:595)
    at mozilla.components.feature.downloads.manager.AndroidDownloadManager.download(AndroidDownloadManager.kt:32)
    at mozilla.components.feature.downloads.manager.DownloadManager$DefaultImpls.download$default(DownloadManager.kt:1)
    at -$$LambdaGroup$ks$xGifb9OOCCPDQOsrm8Dw9Qw6JaI.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:3)
    at mozilla.components.feature.downloads.SimpleDownloadDialogFragment$onCreateDialog$$inlined$with$lambda$1.onClick(SimpleDownloadDialogFragment.kt:3)
...
(8 additional frame(s) were not displayed)

Unable to create directory: /storage/sdcard0/Download
```

**Comment by ekager** [comment]
I guess we could probably close this since we switched to the new download manager @pocmo ?

**Comment by boek** [comment]
Decided in the A-C triage meeting that we can close this as Fenix doesn't use this code anymore (No crashes on Sentry in the last 30 days as well)
