### ISSUE TITLE
[Bug] Save to collection in browser fragment crashes

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3711]
## Steps to reproduce
1. Open a website
2. Press Save to Collection

### Expected behavior
1. Tab is saved to collection

### Actual behavior
1. Fenix crashes

Latest nightly (6/27/19)

    java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:316)
        at org.mozilla.fenix.home.HomeFragment.scrollAndAnimateCollection(HomeFragment.kt:726)
        at org.mozilla.fenix.home.HomeFragment.access$scrollAndAnimateCollection(HomeFragment.kt:84)
        at org.mozilla.fenix.home.HomeFragment$collectionStorageObserver$1.onTabsAdded(HomeFragment.kt:796)
        at org.mozilla.fenix.components.TabCollectionStorage$addTabsToCollection$1.invoke(TabCollectionStorage.kt:61)
        at org.mozilla.fenix.components.TabCollectionStorage$addTabsToCollection$1.invoke(TabCollectionStorage.kt:22)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:131)
        at org.mozilla.fenix.components.TabCollectionStorage.notifyObservers(Unknown Source:26)
        at org.mozilla.fenix.components.TabCollectionStorage.addTabsToCollection(TabCollectionStorage.kt:61)
        at org.mozilla.fenix.collections.CreateCollectionFragment$subscribeToActions$1$$special$$inlined$let$lambda$2.invokeSuspend(CreateCollectionFragment.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by AndiAJ** [comment]
Hi, **verified as fixed**  on the latest Fenix build (#11790617 from 28/6) using the following devices:

• Google Pixel 3XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7.0)
