### ISSUE TITLE
[Bug] Firefox Preview crashes when typing in awesome bar

### ISSUE THREAD

**Issue by stonebanks** [mozilla-mobile/fenix#3759]
## Steps to reproduce
1- Open Firefox Preview
2- start typing something in the awesome bar

### Expected behavior
 should let you type

### Actual behavior

Crashes

#### log from adb:

> 06-28 06:15:52.877 18514 18514 E AndroidRuntime: FATAL EXCEPTION: main
06-28 06:15:52.877 18514 18514 E AndroidRuntime: Process: org.mozilla.fenix, PID: 18514
06-28 06:15:52.877 18514 18514 E AndroidRuntime: java.lang.IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at mozilla.components.browser.awesomebar.BrowserAwesomeBar.processProviderSuggestions$browser_awesomebar_release(BrowserAwesomeBar.kt:6)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend$$inlined$forEach$lambda$1.invokeSuspend(BrowserAwesomeBar.kt:7)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-28 06:15:52.877 18514 18514 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-28 06:15:52.883 18514 18514 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: SessionSuggestionProvider returned duplicate suggestion IDs)

### Device information

* Android device: Nexus 5x on lineage OS 15.1
* Fenix version: 1.0.1.1926 (Build #11790618 68.0-20190612114833) AC: 2.0.0

**Comment by stonebanks** [comment]
Never mind I remove the app then installed it again, sync'ed my account and all and it seems to work
