### ISSUE TITLE
[Bug] Firefox closes itself

### ISSUE THREAD

**Issue by ARZUMATA** [mozilla-mobile/fenix#3761]
## Steps to reproduce

Launch Firefox Preview.

### Expected behavior

Firefox stays open.

### Actual behavior
Firefox closes to launcher.

[2019-06-28_14.35.zip](https://github.com/mozilla-mobile/fenix/files/3338992/2019-06-28_14.35.zip)

![photo_2019-06-28_14-38-36](https://user-images.githubusercontent.com/19918315/60339814-7f457e80-99b2-11e9-9bc7-985106aa27b8.jpg)
![photo_2019-06-28_14-38-33](https://user-images.githubusercontent.com/19918315/60339815-7fde1500-99b2-11e9-9784-81d87408a37d.jpg)
### Device information

* Android device: Zenfone 2 ZE551ML latest stock firmware
* Fenix version: 1.0.0

### Notes

Will do my best to help pinpoint the issue.

**Comment by julKali** [comment]
This seems to be the relevant passage:
```
06-28 14:35:17.290 D/houdini (14205): [14317] Unsupported feature (ID:0x20e000b2).
06-28 14:35:17.307 I/KERNEL  (  319): [96331.798492] [DISP] brightness level = 15
06-28 14:35:17.350 W/InputDispatcher(  677): channel 'fb93394 org.mozilla.fenix/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-28 14:35:17.350 E/InputDispatcher(  677): channel 'fb93394 org.mozilla.fenix/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-28 14:35:17.350 D/GraphicsStats(  677): Buffer count: 10
06-28 14:35:17.350 W/InputDispatcher(  677): Attempted to unregister already unregistered input channel 'fb93394 org.mozilla.fenix/org.mozilla.fenix.HomeActivity (server)'
06-28 14:35:17.350 I/WindowState(  677): WIN DEATH: Window{fb93394 u0 org.mozilla.fenix/org.mozilla.fenix.HomeActivity}
06-28 14:35:17.358 I/KERNEL  (  319): [96331.848947] [DISP] brightness level = 15
06-28 14:35:17.366 I/KERNEL  (  305): [96331.856769] mmc2: set SDHCI_TUNE_FOR_CMD52.
06-28 14:35:17.370 W/WindowAnimator(  677): Failed to dispatch window animation state change.
06-28 14:35:17.370 W/WindowAnimator(  677): android.os.DeadObjectException
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.BinderProxy.transactNative(Native Method)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.BinderProxy.transact(Binder.java:503)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.view.IWindow$Stub$Proxy.onAnimationStarted(IWindow.java:520)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:282)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:683)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.view.Choreographer.doFrame(Choreographer.java:603)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.Handler.handleCallback(Handler.java:739)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.Looper.loop(Looper.java:148)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-28 14:35:17.370 W/WindowAnimator(  677): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
06-28 14:35:17.380 D/hwcomposer(  274): void android::intel::DisplayAnalyzer::handleIdleExitEvent(): handling idle exit event
06-28 14:35:17.390 D/NetworkController.WifiSignalController(  906): Change in state from: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=true,activityOut=true,rssi=-32,lastModified=06-28 02:35:09,ssid="CCTV"
06-28 14:35:17.390 D/NetworkController.WifiSignalController(  906): 	to: connected=true,enabled=true,level=4,inetCondition=1,iconGroup=IconGroup(Wi-Fi Icons),activityIn=false,activityOut=true,rssi=-32,lastModified=06-28 02:35:09,ssid="CCTV"
06-28 14:35:17.390 D/SignalClusterView(  906): vpn: GONE
06-28 14:35:17.390 D/SignalClusterView(  906): ethernet: GONE
06-28 14:35:17.390 D/SignalClusterView(  906): wifi: VISIBLE sig=2130838688 inout=2130838674
06-28 14:35:17.390 D/SignalClusterView(  906): mobile: VISIBLE sig=2130838652 typ=0 inout=0 simoff=false
06-28 14:35:17.390 D/SignalClusterView(  906): mobile: VISIBLE sig=2130838665 typ=0 inout=0 simoff=false
06-28 14:35:17.390 D/SignalClusterView(  906): vpn: GONE
06-28 14:35:17.390 D/SignalClusterView(  906): ethernet: GONE
06-28 14:35:17.390 D/SignalClusterView(  906): wifi: VISIBLE sig=2130838688 inout=2130838674
06-28 14:35:17.390 D/SignalClusterView(  906): mobile: VISIBLE sig=2130838652 typ=0 inout=0 simoff=false
06-28 14:35:17.390 D/SignalClusterView(  906): mobile: VISIBLE sig=2130838665 typ=0 inout=0 simoff=false
06-28 14:35:17.408 I/KERNEL  (  319): [96331.899295] [DISP] brightness level = 15
06-28 14:35:17.410 I/ActivityManager(  677): Process org.mozilla.fenix (pid 14205) has died
```

It looks like this is an issue with native code execution. Have you tried building the APK yourself and running it in debug mode?

**Comment by ARZUMATA** [comment]
No I didn't I just got it from Google Play.
I'll try to build and see how it behaves.

The Beta 1.0.1926 runs well though.
