### ISSUE TITLE
[Bug] Bookmarks not syncing in Firefox Preview

### ISSUE THREAD

**Issue by panpiotrs** [mozilla-mobile/fenix#3774]
## Steps to reproduce
Install / reinstall Firefox Preview, connect it with Firefox account.

### Expected behavior
Both history and bookmarks are synced.

### Actual behavior
Only history is synced, I can see history from desktop on mobile and mobile history on desktop.
I don't see bookmarks from my desktop Firefox on FP and I don't see bookmarks created on FP on my desktop Firefox.
Actually I don't even see the FP on the list of devices on https://accounts.firefox.com/settings.
I can't also see from my desktop browser which tabs are open on FP, not sure if it's currently implemented or not.

Here's the screenshot of what I see in "Desktop Bookmarks" folder, all of those folders are empty https://imgur.com/q1W7GgZ

I have "original" Firefox installed on my phone and it's syncing history and bookmarks without any trouble in both ways.

I also tried manually sync Firefox Preview by clicking on "Sync Now" - it looks like it's working ("Last synced: 0 minutes ago"), but bookmarks are still not there.

I tried reinstalling it, after that I tried to pair it by QR Code - again, it looks like it works perfectly, but bookmarks are missing.

### Device information

* Android device: Galaxy S9+, Android 9
* Fenix version: 1.0.0 (Build #11721515 🦎 68.0-20190611143747)

**Comment by panpiotrs** [comment]
Btw. I'm not using Firefox, I was using it years ago and now I'm testing it only from time to time to check if it's getting better (problems with high CPU usage on Mac). I can just remove those old bookmarks and import new ones from Opera to check how this will go then. Let me know if you want me to wait and check this collection of bookmarks in next releases or should I just remove them and test it now with different collection.

**Comment by ekager** [comment]
fyi @grigoryk

**Comment by grigoryk** [comment]
@panpiotrs is it possible for you to attach device logs while sync is running? (e.g. run `adb logcat`, press `Sync Now`, and copy-paste logs into this issue; there shouldn't be any personal information in those logs). That will help quite a bit with the investigation.

And to double-check, you mentioned you also have regular Firefox for Android installed, and its bookmark sync is working both ways for you. That means you see your desktop bookmarks on there, and you can add new mobile bookmarks/make edits, and they are reflected in your Firefox Desktop after you sync both clients?

**Comment by panpiotrs** [comment]
@grigoryk If only you could give me some hints how to do that (where to run this adb command) or some links with description of that. I don't have Android Studio, it looks to be related to that, is it possible to do that without installing AStudio?

Yes, syncing between Firefox and Firefox for Android works perfectly, any change I can think of doing there is reflected after sync, no matter if done in one browser or another. I installed Firefox for Android couple of weeks ago after changing my device and sync it then for the first time so those old bookmarks from my desktop Firefox are old, but shouldn't be 'corrupted' or something.

**Comment by grigoryk** [comment]
@panpiotrs this page has instructions on how to get to the logs: https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information - you don't need to install Android Studio, but you will need to at least install "android platform tools". Refer to the page for links.

Those instructions talks about a "crash", but in your case you just want to copy-paste the logs that are displayed while you're syncing on Fenix.

**Comment by grigoryk** [comment]
@panpiotrs if you need further help with the logs, feel free to ask here or also in #mobile on our IRC (https://wiki.mozilla.org/IRC). My nickname is "grisha" there, happy to help out.

**Comment by panpiotrs** [comment]
I think this is all what is related to Firefox from that log.

And there it is: `06-28 23:00:13.640 W/sync15::sync_multiple(12587): Store error: Error executing SQL: Invalid column type Null at index: 3)`
If you want some other tests, no problem, let me know what to do.

```
06-28 23:00:12.692 I/sync15::sync_multiple(12587): Syncing history engine!
06-28 23:00:12.693 I/sync15::sync(12587): Syncing collection history
06-28 23:00:12.701 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587
06-28 23:00:12.702 D/DnsProxyListener( 4598): DNSDBG::dns addrinfo af 2
06-28 23:00:12.702 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
06-28 23:00:12.711 D/WifiTrafficPoller( 4925): TrafficStats TxPkts=1102144 RxPkts=2132018 TxBytes=228911860 RxBytes=2750050854 , Foreground uid=10325 pkgName=org.mozilla.fenix TxPackets=10312 RxPackets=16615 TxBytes=1254197 RxBytes=18719004
06-28 23:00:12.907 I/sync15::sync(12587): Downloaded 0 remote changes
06-28 23:00:12.923 D/sql_support::conn_ext(12587): Transaction commited after 11.464308ms
06-28 23:00:12.936 D/sql_support::conn_ext(12587): Transaction commited after 12.67527ms
06-28 23:00:12.937 I/places::history_sync::plan(12587): incoming: {}
06-28 23:00:12.937 I/sync15::sync(12587): Uploading 0 outgoing changes
06-28 23:00:12.937 I/sync15::sync(12587): Upload success (0 records success, 0 records failed)
06-28 23:00:12.937 I/places::history_sync::store(12587): sync completed after uploading 0 records
06-28 23:00:12.938 D/places::storage::history::history_sync(12587): Updating all synced rows
06-28 23:00:12.938 D/places::storage::history::history_sync(12587): Updating all non-synced rows
06-28 23:00:12.951 D/places::storage::history::history_sync(12587): Removing local tombstones
06-28 23:00:12.965 D/sql_support::conn_ext(12587): Transaction commited after 27.513461ms
06-28 23:00:12.973 I/sync15::sync(12587): Sync finished!
06-28 23:00:12.973 I/sync15::sync_multiple(12587): Sync of history was successful!
06-28 23:00:12.973 I/sync15::sync_multiple(12587): Updating persisted global state
06-28 23:00:12.974 D/sync15::sync_multiple(12587): sync was successful, final status=Ok
06-28 23:00:12.995 D/PlacesHistoryStorage(12587): Successfully synced.
06-28 23:00:12.997 I/StorageSync(12587): Synchronized history store.
06-28 23:00:12.998 D/PlacesBookmarksStorage(12587): Syncing...
06-28 23:00:12.999 D/glean/PingMaker(12587): Collecting history_sync
06-28 23:00:13.023 D/places_ffi(12587): sync15_bookmarks_sync
06-28 23:00:13.044 D/glean/PingStorageEngine(12587): Storing ping 1e95c615-4858-4bd6-9872-e5f00b55874b at /data/user/0/org.mozilla.fenix/glean_data/pending_pings/1e95c615-4858-4bd6-9872-e5f00b55874b
06-28 23:00:13.081 D/PackageManager( 4925): setEnabledSetting : userId = 0 packageName = org.mozilla.fenix cmp = androidx.work.impl.background.systemalarm.RescheduleReceiver newState = 1 callingPackage = 10325/org.mozilla.fenix
06-28 23:00:13.086 D/sql_support::conn_ext(12587): Transaction commited after 34.390231ms
06-28 23:00:13.089 I/sync15::sync_multiple(12587): Advancing state machine to ready (full)
06-28 23:00:13.096 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587
06-28 23:00:13.096 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
06-28 23:00:13.096 D/DnsProxyListener( 4598): DNSDBG::dns addrinfo af 2
06-28 23:00:13.113 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 4925
06-28 23:00:13.113 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 4925, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
06-28 23:00:13.145 D/glean/PingStorageEngine(12587): Processing persisted pings at /data/user/0/org.mozilla.fenix/glean_data/pending_pings
06-28 23:00:13.147 D/glean/PingStorageEngine(12587): Processing ping: 1e95c615-4858-4bd6-9872-e5f00b55874b
06-28 23:00:13.160 D/glean/HttpPingUploader(12587): Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fenix/history_sync/1/1e95c615-4858-4bd6-9872-e5f00b55874b
06-28 23:00:13.162 I/System.out(12587): (HTTPLog)-Static: isSBSettingEnabled false
06-28 23:00:13.163 I/System.out(12587): (HTTPLog)-Static: isSBSettingEnabled false
06-28 23:00:13.178 D/DnsProxyListener( 4598): DNSDBG::dns addrinfo af 2
06-28 23:00:13.292 D/io_stats(14541): !@   8,0 r 1360322 68172196 w 2315740 43212284 d 166066 50456844 f 681037 685439 iot 1702052 1145269 th 102400 0 0 pt 0 inp 0 0 110351.635
06-28 23:00:13.304 I/sync15::sync_multiple(12587): Syncing bookmarks engine!
06-28 23:00:13.304 I/sync15::sync(12587): Syncing collection bookmarks
06-28 23:00:13.317 D/DnsProxyListener( 4598): DNSDBG::dns addrinfo af 2
06-28 23:00:13.318 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587
06-28 23:00:13.318 D/ConnectivityService( 4925): filterNetworkStateForUid() uid: 10325, pid: 12587, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
06-28 23:00:13.377 I/WifiStateMachine( 4925): checkScoreBasedQuality -  mPreviousScore[0]:92 mPreviousScore[1]:92 mPreviousScore[2]:91 s2Score:89mPrevoiusScoreAverage:91
06-28 23:00:13.526 I/sync15::sync(12587): Downloaded 0 remote changes
06-28 23:00:13.527 D/sql_support::conn_ext(12587): Transaction commited after 126.73µs
06-28 23:00:13.544 D/dogear::store(12587): Built local tree from mirror
06-28 23:00:13.544 D/dogear::store(12587): 📂 root________ (Folder; Age = 28198563ms; Unmerged)
06-28 23:00:13.544 D/dogear::store(12587): | 📂 menu________ (Folder; Age = 28198563ms; Unmerged)
06-28 23:00:13.544 D/dogear::store(12587): | 📂 toolbar_____ (Folder; Age = 28198563ms; Unmerged)
06-28 23:00:13.544 D/dogear::store(12587): | 📂 unfiled_____ (Folder; Age = 28198563ms; Unmerged)
06-28 23:00:13.544 D/dogear::store(12587): | 📂 mobile______ (Folder; Age = 28198563ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): Built remote tree from mirror
06-28 23:00:13.637 D/dogear::store(12587): 📂 root________ (Folder; Age = 1561748040180ms)
06-28 23:00:13.637 D/dogear::store(12587): | ❗️📂 menu________ (Folder; Age = 1060297150ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 CDmhVfYFrSm- (Query; Age = 49892689540ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 inrybk6LJ9wX (Separator; Age = 48682163440ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 BZYAvPqfqCPv (Query; Age = 1060317180ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 e1eGQW6kHFzS (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 XhfjZGAPOXa4 (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 qQHav0Y-bJuz (Query; Age = 23764408070ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 zh7GW2Zh0KDH (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 TzAuVhOq5Tay (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 PiMSIFJtGYNv (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 XoYGEiuL3n92 (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 📂 8_67LBp8Qke8 (Folder; Age = 50914958550ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | 🔖 g7rd_AUc9_qw (Bookmark; Age = 49892689540ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | 🔖 037A2vXiO8oz (Bookmark; Age = 49892689540ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | 🔖 NIzw63-86n1n (Bookmark; Age = 49892689540ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | 🔖 hkjix53m4xLh (Bookmark; Age = 49892689540ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 CP6WKBhGlrJG (Query; Age = 23764408070ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | 🔖 TEJHnnbfuocK (Query; Age = 23764408070ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | ❗️📂 xGE-Lx3snISV (Folder; Age = 1060317180ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️🔖 6KC7NAE7I6My (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️🔖 6Hpg-4SyHcNp (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️🔖 xZ167J8j3L4f (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️🔖 fxm-dnJYQqxP (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️🔖 _25cldjM5Cxe (Query; Age = 8918322660ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️📂 CBoh680fLoJQ (Folder; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 NlAD_OePyDl_ (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 _zl5R3DTQ7hT (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 57xVzQG4QnHJ (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 SWp6B75WG55k (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 isU73ja1ECka (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 7ydxH0NkiJpc (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 Tx9xTnolEGHX (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 kGrri6kv8ZLj (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 KjxuIOO3YFzU (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 exyVXDitfwfY (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 DFYFGpuB6IN7 (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 QjuHk6nd0HgL (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 LB7W-BtLGROX (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 🔖 24vTj9e_ANEu (Bookmark; Age = 54724192320ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | ❗️📂 0mKSsJOW1Rz- (Folder; Age = 41539354760ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 📂 z2ababQCcF7t (Folder; Age = 50916291620ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 rB917f2IxVcF (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 0vAPKh9tRkhA (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 fFwgvcN7SjJn (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 c1rPWY69-3RY (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 -PmkyVZm3-P2 (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 NV7TmxzAE79d (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 tPm39o4lSLIq (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 wcol8oXS-KkB (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 IS3vcj_8oU5s (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 📂 _3K3T-f7GGMY (Folder; Age = 54702210460ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 f9ZoIoGW4K-t (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 Y9U1dr24_Com (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | 📂 9IvGC8WqtYxG (Folder; Age = 50916291620ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 CX70_pok6m8T (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 0sEK0XVtPoBg (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 lvjEP56ctzXa (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 _ne_b8QN9Ftl (Bookmark; Age = 54702203480ms; Unmerged)
06-28 23:00:13.637 D/dogear::store(12587): | | | | | 🔖 BKboeHRiyx4Z (Bookmark; Age = 54702203480ms; Unmer
06-28 23:00:13.640 D/places::bookmark_sync::store(12587): merge completed
06-28 23:00:13.640 W/sync15::sync_multiple(12587): Sync of bookmarks failed! Error(
06-28 23:00:13.640 W/sync15::sync_multiple(12587):
06-28 23:00:13.640 W/sync15::sync_multiple(12587): Store error: Error executing SQL: Invalid column type Null at index: 3)
06-28 23:00:13.640 D/sync15::sync_multiple(12587): sync was successful, final status=Ok
06-28 23:00:13.644 I/places::ffi(12587): Recursing to resolve places error
06-28 23:00:13.644 E/places::ffi(12587): Unexpected error: SqlError(InvalidColumnType(3, Null))
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): Places exception while syncing
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): mozilla.appservices.places.PlacesException: Error synchronizing: Store error: Error executing SQL: Invalid column type Null at index: 3
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:17)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:2)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:6)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.645 E/PlacesBookmarksStorage(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
06-28 23:00:13.646 E/StorageSync(12587): Error synchronizing a bookmarks store
06-28 23:00:13.646 E/StorageSync(12587): mozilla.appservices.places.PlacesException: Error synchronizing: Store error: Error executing SQL: Invalid column type Null at index: 3
06-28 23:00:13.646 E/StorageSync(12587): 	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
06-28 23:00:13.646 E/StorageSync(12587): 	at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:17)
06-28 23:00:13.646 E/StorageSync(12587): 	at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:2)
06-28 23:00:13.646 E/StorageSync(12587): 	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:6)
06-28 23:00:13.646 E/StorageSync(12587): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
06-28 23:00:13.646 E/StorageSync(12587): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
06-28 23:00:13.646 E/StorageSync(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.646 E/StorageSync(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.646 E/StorageSync(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
06-28 23:00:13.647 I/SyncWorker(12587): Synchronized store history
06-28 23:00:13.647 E/SyncWorker(12587): Failed to synchronize store bookmarks
06-28 23:00:13.647 E/SyncWorker(12587): mozilla.appservices.places.PlacesException: Error synchronizing: Store error: Error executing SQL: Invalid column type Null at index: 3
06-28 23:00:13.647 E/SyncWorker(12587): 	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
06-28 23:00:13.647 E/SyncWorker(12587): 	at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:17)
06-28 23:00:13.647 E/SyncWorker(12587): 	at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:2)
06-28 23:00:13.647 E/SyncWorker(12587): 	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:6)
06-28 23:00:13.647 E/SyncWorker(12587): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
06-28 23:00:13.647 E/SyncWorker(12587): 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
06-28 23:00:13.647 E/SyncWorker(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.647 E/SyncWorker(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
06-28 23:00:13.647 E/SyncWorker(12587): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
06-28 23:00:13.655 I/WM-WorkerWrapper(12587): Worker result SUCCESS for Work [ id=5c1db9cc-c731-4fe4-9cef-8816f9160b23, tags={ Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker, Common } ]
06-28 23:00:13.988 I/g.mozilla.feni(12587): Background concurrent copying GC freed 148070(7MB) AllocSpace objects, 162(7MB) LOS objects, 50% free, 19MB/38MB, paused 436us total 238.463ms
06-28 23:00:14.033 D/glean/HttpPingUploader(12587): Ping successfully sent (200)
06-28 23:00:14.034 D/glean/PingStorageEngine(12587): 1e95c615-4858-4bd6-9872-e5f00b55874b was deleted: true
06-28 23:00:14.041 I/WM-WorkerWrapper(12587): Worker result SUCCESS for Work [ id=97dc1d75-518d-43ba-9be4-3e08589730fd, tags={ mozac_service_glean_ping_upload_worker, mozilla.components.service.glean.scheduler.PingUploadWorker } ]
```

**Comment by grigoryk** [comment]
That's very helpful, thank you @panpiotrs ! Seems like we've seen this issue before, it's being tracked in https://github.com/mozilla/application-services/issues/1325.

**Comment by panpiotrs** [comment]
All right, good luck with that, Fenix looks really nice and fresh even with this bug and without extensions, I think I will just start using it anyway 👍

**Comment by grigoryk** [comment]
@panpiotrs the bug appears to be caused by bookmarks with invalid URLs. Those URLs aren't being handled correctly by the underlying bookmark sync mechanism. Fenix uses an entirely new syncing stack underneath, which is why you don't see a similar issue in Firefox for Android.

A possible workaround for you could be to look through your bookmarks (in Firefox Desktop), and remove any with suspicious looking URLs. A proper fix should be out in one of the upcoming releases.

**Comment by panpiotrs** [comment]
You're right. I found what is the problem by removing everything except the one unremovable and two others to let you see what's going on:

![](https://i.imgur.com/CMZMfyA.jpg)

This is how backup in json looks like:
```
{"guid":"root________","title":"","index":0,"dateAdded":1510832161194000,"lastModified":1561761130265000,"id":1,"typeCode":2,"type":"text/x-moz-place-container","root":"placesRoot","children":[{"guid":"menu________","title":"Menu Zakładki","index":0,"dateAdded":1403881025958000,"lastModified":1561761130265000,"id":2,"typeCode":2,"type":"text/x-moz-place-container","root":"bookmarksMenuFolder","children":[{"guid":"gTkWpWBljK-L","title":"Pasek zakładek","index":0,"dateAdded":1506955593000000,"lastModified":1561761130265000,"id":94,"typeCode":2,"type":"text/x-moz-place-container","children":[{"guid":"gy7nAD4EIH8O","title":"Nauka","index":1,"dateAdded":1490817106000000,"lastModified":1561761050906000,"id":96,"typeCode":2,"type":"text/x-moz-place-container","children":[{"guid":"1DIZLAwjuKfb","title":"Fizyka","index":0,"dateAdded":1458547141000000,"lastModified":1561761050906000,"id":20,"typeCode":2,"type":"text/x-moz-place-container","children":[{"guid":"fgXzSmygf1RQ","title":"https://profmattstrassler.com/","index":7,"dateAdded":1490817108000000,"lastModified":1490817108000000,"id":556,"typeCode":1,"type":"text/x-moz-place","uri":"https://profmattstrassler.com/"},{"guid":"pIdvDoVHjHgx","title":"http://fizykwyjasnia.pl/","index":8,"dateAdded":1490817108000000,"lastModified":1490817108000000,"id":651,"typeCode":1,"type":"text/x-moz-place","uri":"http://fizykwyjasnia.pl/"}]}]}]}]},{"guid":"toolbar_____","title":"Pasek zakładek","index":1,"dateAdded":1460573492000000,"lastModified":1561759668338000,"id":3,"typeCode":2,"annos":[{"name":"bookmarkProperties/description","value":"Zakładki umieszczone w tym folderze będą widoczne na pasku zakładek.","expires":4,"flags":0}],"type":"text/x-moz-place-container","root":"toolbarFolder"},{"guid":"unfiled_____","title":"Pozostałe zakładki","index":3,"dateAdded":1510832161194000,"lastModified":1561759808193000,"id":5,"typeCode":2,"type":"text/x-moz-place-container","root":"unfiledBookmarksFolder"},{"guid":"mobile______","title":"Zakładki z urządzeń przenośnych","index":4,"dateAdded":1510832161195000,"lastModified":1561761119234000,"id":6,"typeCode":2,"annos":[{"name":"mobile/bookmarksRoot","value":"1","expires":4,"flags":0}],"type":"text/x-moz-place-container","root":"mobileFolder"}]}
```

As you can see there is no `Blog - nie od razu naukę zbudowano` in the backup, only those two correct bookmarks. And I can't remove it in the bookmark manager, I can click on it, and that's everything, can't edit, can't remove, can't move to other folder. When I try to restore this backup file without this item there is an error saying that it can't process this backup file. But it's rather because of this thing staying partially invisible in database.

Do you want to link it somewhere else in Mozilla bug tracker or should I just wipe out my profile entirely and start again with completely new Firefox (if it's possible)? I used Xmarks looong time ago, I guess it was corrupted by this sync manager, maybe I'm the only one with that kind of thing.

**Comment by thomcc** [comment]
You mentioned importing bookmarks from Opera, is that where these came from? Perhaps desktop Firefox is mishandling that import, causing these URLs.

**Comment by panpiotrs** [comment]
Or maybe it wasn't Xmarks that messed it, because I removed Firefox for Android after our conversation before, I installed it now again and I can't see those two/three bookmarks. It syncs all folders, but they're empty. The same on Firefox Preview, more folders than before (this simple tree you're seeing), all empty. Maybe it was messed up by syncing between my Firefoxes after I installed it couple of weeks ago on Android.

@thomcc I don't think so, but we will see how it will behave when I will be able to somehow remove all of this, I will then try to import my current bookmarks from Opera and sync :)

**Comment by panpiotrs** [comment]
I was able to remove bookmark folders by Firefox for Android. It wasn't removed from my default profile on Firefox Desktop, but I created new profile, sync it, and there was no bookmarks. I imported my current collection of bookmarks and everything is syncing now correctly with both Firefox for Android and Firefox Preview. 🎉
