### ISSUE TITLE
IllegalStateException: Fragment BrowserFragment{7d22609 (0ea908f2-edc6-4f66-9aea-3a649a8a491b)} not attached to a context.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3816]
https://sentry.prod.mozaws.net/operations/fenix/issues/5617779/

```
IllegalStateException: Fragment BrowserFragment{7d22609 (0ea908f2-edc6-4f66-9aea-3a649a8a491b)} not attached to a context.
    at org.mozilla.fenix.browser.BrowserFragment.getSessionById(BrowserFragment.kt:2)
    at org.mozilla.fenix.browser.BrowserFragment.setToolbarBehavior(BrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment.access$setToolbarBehavior(BrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment$subscribeToSession$observer$1.onLoadingStateChanged(BrowserFragment.kt:2)
...
(24 additional frame(s) were not displayed)

Fragment BrowserFragment{7d22609 (0ea908f2-edc6-4f66-9aea-3a649a8a491b)} not attached to a context.
```

**Comment by ekager** [comment]
This method does not exist anymore with the static toolbar :) Closing!
