### ISSUE TITLE
IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period ...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#3817]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5990425/

```
IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
    at org.mozilla.fenix.components.PermissionStorage.findSitePermissionsBy(PermissionStorage.kt:1)
    at org.mozilla.fenix.settings.quicksettings.QuickSettingsSheetDialogFragment$sessionObserver$1$onUrlChanged$1.invokeSuspend(QuickSettingsSheetDialogFragment.kt:6)
...
(10 additional frame(s) were not displayed)

Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
```

**Comment by ekager** [comment]
Closed by https://github.com/mozilla-mobile/fenix/pull/3795
