### ISSUE TITLE
[Bug] Crash when Sharing (anywhere)

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/fenix#3834]
This also just happens any time I try to share anywhere in the app (Home fragment -> share tabs is the easiest way to reproduce).

## Steps to reproduce
1. Open "Your Library"
2. Open "History"
3. Long press to share
4. Press share icon

### Expected behavior
Able to share my link

### Actual behavior
App crashes.

Perhaps something to do with https://github.com/mozilla-mobile/fenix/commit/8cd1a0cb384e23de6a41d19302e46f409e495121

cc: @NotWoods 

### Stacktrace

```
2019-07-01 14:57:11.349 4861-4861/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 4861
    kotlin.UninitializedPropertyAccessException: lateinit property adapterJob has not been initialized
        at org.mozilla.fenix.utils.AdapterWithJob.getAdapterJob(AdapterWithJob.kt:17)
        at org.mozilla.fenix.share.AppShareAdapter.getCoroutineContext(AppShareView.kt:46)
        at kotlinx.coroutines.CoroutineContextKt.newCoroutineContext(CoroutineContext.kt:57)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:50)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at org.mozilla.fenix.share.AppShareAdapter.<init>(AppShareView.kt:56)
        at org.mozilla.fenix.share.AppShareAdapter.<init>(AppShareView.kt:42)
        at org.mozilla.fenix.share.ShareUIView.<init>(ShareUIView.kt:33)
        at org.mozilla.fenix.share.ShareComponent.initView(ShareComponent.kt:40)
        at org.mozilla.fenix.share.ShareComponent.initView(ShareComponent.kt:31)
        at org.mozilla.fenix.mvi.UIComponent$uiView$2.invoke(UIComponent.kt:31)
        at org.mozilla.fenix.mvi.UIComponent$uiView$2.invoke(UIComponent.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.mvi.UIComponent.getUiView(Unknown Source:25)
        at org.mozilla.fenix.mvi.UIComponent.bind(UIComponent.kt:46)
        at org.mozilla.fenix.share.ShareComponent.<init>(ShareComponent.kt:43)
        at org.mozilla.fenix.share.ShareFragment.onCreateView(ShareFragment.kt:50)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2595)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:880)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1237)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1302)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2075)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1865)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1820)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1726)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by softvision-miralobontiu** [comment]
Verified that the app doesn't crash when share-ing from History.
Tested with the latest build 1.0.1926 (#11790618) with HTC Desire 820 (Android 6.0.1), Google Pixel (Android Q), and Motorola Moto G6 (Android 8).
