### ISSUE TITLE
crash when clicking on address bar

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#384]
## Steps to reproduce

1. Open Fenix
2. Enter an url and open the website => (there is no website, but that's #383)
3. click on the adress bar
4. press back button on your device => the keyboard will be hidden
5. press back button again => you see the same as in step 2
6. repeat step 3 => Fenix crashes

### Expected behavior

No Crash.

### Actual behavior

Crash.

### Device information

* Android device: HTC U 11 w/ Android 8.0.0
* Fenix version: 10495657c5ea95f3eb2bfbb575b64972fdd5e632

**Comment by pocmo** [comment]
Ah, I see that too when I tried to reproduce the issue in #360.

Here's a stacktrace:

```
E  FATAL EXCEPTION: main
E  Process: org.mozilla.fenix.debug, PID: 15449
E  io.reactivex.exceptions.OnErrorNotImplementedException: navigation destination org.mozilla.fenix.debug:id/action_browserFragment_to_searchF
   ragment is unknown to this NavController
E      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
E      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
E      at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
E      at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
E      at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
E      at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
E      at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:105)
E      at org.mozilla.fenix.search.toolbar.ToolbarUIView$$special$$inlined$apply$lambda$2.invoke(ToolbarUIView.kt:41)
E      at org.mozilla.fenix.search.toolbar.ToolbarUIView$$special$$inlined$apply$lambda$2.invoke(ToolbarUIView.kt:21)
E      at mozilla.components.browser.toolbar.display.DisplayToolbar$$special$$inlined$apply$lambda$1.onClick(DisplayToolbar.kt:98)
E      at android.view.View.performClick(View.java:6597)
E      at android.view.View.performClickInternal(View.java:6574)
E      at android.view.View.access$3100(View.java:778)
E      at android.view.View$PerformClick.run(View.java:25885)
E      at android.os.Handler.handleCallback(Handler.java:873)
E      at android.os.Handler.dispatchMessage(Handler.java:99)
E      at android.os.Looper.loop(Looper.java:193)
E      at android.app.ActivityThread.main(ActivityThread.java:6718)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E  Caused by: java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.debug:id/action_browserFragment_to_searchFragment i
   s unknown to this NavController
E      at androidx.navigation.NavController.navigate(NavController.java:778)
E      at androidx.navigation.NavController.navigate(NavController.java:719)
E      at org.mozilla.fenix.browser.BrowserFragment.navigateToSearch(BrowserFragment.kt:190)
E      at org.mozilla.fenix.browser.BrowserFragment.access$navigateToSearch(BrowserFragment.kt:43)
E      at org.mozilla.fenix.browser.BrowserFragment$onViewCreated$4.accept(BrowserFragment.kt:155)
E      at org.mozilla.fenix.browser.BrowserFragment$onViewCreated$4.accept(BrowserFragment.kt:43)
E      at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
E      ... 17 more
```
