### ISSUE TITLE
SecurityException: Lacking privileges to access camera service

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4074]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6055762/

```
SecurityException: Lacking privileges to access camera service
    at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:108)
    at android.hardware.camera2.legacy.CameraDeviceUserShim.connectBinderShim(CameraDeviceUserShim.java:331)
    at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:267)
    at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:383)
    at mozilla.components.feature.qr.QrFragment.openCamera$feature_qr_release(QrFragment.kt:7)
...
(78 additional frame(s) were not displayed)

Lacking privileges to access camera service
```

**Comment by pocmo** [comment]
Very low volume.

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-2KJ](https://sentry.prod.mozaws.net/operations/fenix/issues/6248506/?referrer=github_plugin)

Still seeing some instances of this crash. There are some [suggestions on SO and other sites for how to add some defensive code](https://www.google.com/search?q=SecurityException%3A+Lacking+privileges+to+access+camera+service) to avoid this crash.

**Comment by kbrosnan** [comment]
This crash mostly happens on a Redmi 3 running Android 5.1.1

**Comment by mcarare** [comment]
This is fixed by https://github.com/mozilla-mobile/android-components/pull/7912
