### ISSUE TITLE
[Bug] java.lang.IllegalStateException: search_shortcuts_button must not be null

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4119]
This just came up in a `monkey` session (`** System appears to have crashed at event 115 of 500 using seed 1563418424054`):

```
// java.lang.IllegalStateException: search_shortcuts_button must not be null
// 	at io.reactivex.plugins.RxJavaPlugins.checkExpressionValueIsNotNull(RxJavaPlugins.java:1)
// 	at org.mozilla.fenix.search.SearchFragment.access$updateSearchShortuctsIcon(SearchFragment.kt:4)
// 	at org.mozilla.fenix.search.SearchFragment$onViewCreated$5$1.invokeSuspend(SearchFragment.kt:43)
// 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
// 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
// 	at android.os.Handler.handleCallback(Handler.java:883)
// 	at android.os.Handler.dispatchMessage(Handler.java:100)
// 	at android.os.Looper.loop(Looper.java:214)
// 	at android.app.ActivityThread.main(ActivityThread.java:7343)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
```

**Comment by ekager** [comment]
We should check if this is still happening since we fixed some lifecycle issues in #4131

**Comment by sblatz** [comment]
p5 since it's likely fixed and only came up with a monkey run.

**Comment by ekager** [comment]
I think we should just close it then, and we can open a new issue if we see this again on Sentry
