### ISSUE TITLE
IllegalStateException: JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tr...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4248]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6078067/

```
IllegalStateException: Apps may not schedule more than 100 distinct jobs
    at android.os.Parcel.readException(Parcel.java:1975)
    at android.os.Parcel.readException(Parcel.java:1913)
    at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
    at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
    at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:5)
...
(6 additional frame(s) were not displayed)

IllegalStateException: JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tracked jobs in our DB; our Configuration limit is 20.
    at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:17)
    at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:31)
    at androidx.work.impl.Schedulers.schedule(Schedulers.java:15)
    at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
...
(2 additional frame(s) were not displayed)

JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tracked jobs in our DB; our Configuration limit is 20.
```

**Comment by pocmo** [comment]
The only things I know that are using work manager currently are Glean and Fretboard.

**Comment by pocmo** [comment]
Sentry issue: [FENIX-1XS](https://sentry.prod.mozaws.net/operations/fenix/issues/6034999/)

**Comment by ekager** [comment]
This has very few events but is still happening rarely as of 8 days ago

**Comment by ekager** [comment]
I don't see this in Sentry anymore? We can probably close

**Comment by pocmo** [comment]
👍
