### ISSUE TITLE
Recent builds insta crash on ChromeOS

### ISSUE THREAD

**Issue by BaronKrause** [mozilla-mobile/fenix#4338]
As of around 2 weeks ago Firefox Preview (google play store version) insta crashes on ChromeOS (stable branch running on a Pixel Slate) and will continue to crash in the background even when not open until removed. Reinstall after removal provides the same results.

While not a priority I'm sure (there is no tablet/desktop interface yet), just wanted to report it since it DID actually work fine on ChromeOS since Preview's "official" release up till that point.

**Comment by NotWoods** [comment]
Stack trace from running on Pixelbook:
```shell
2019-07-28 14:03:51.980 2327-2327/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix, PID: 2327
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6135)
        at android.app.ActivityThread.access$1100(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:27)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1167)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130)
        at android.app.ActivityThread.access$1100(ActivityThread.java:201) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6971) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865) 
     Caused by: java.lang.RuntimeException: LibViaduct not available
        at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:1)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy0.viaduct_initialize(Unknown Source)
        at mozilla.appservices.httpconfig.RustHttpConfig.setClient(HttpConfig.kt:5)
        at mozilla.appservices.FenixMegazord$Companion.init(FenixMegazord.kt:6)
        at mozilla.appservices.FenixMegazord.init(Unknown Source:2)
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:27) 
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1167) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6130) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:201) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6971) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865) 
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'fenix':
    dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
    dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
    dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
    Native library (android-x86-64/libfenix.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:69)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:12)
        at com.sun.jna.Library$Handler.<init>(Library.java:13)
        at com.sun.jna.Native.load(Native.java:5)
        at com.sun.jna.Native.load(Native.java:3)
        at mozilla.appservices.httpconfig.LibViaduct$Companion.<clinit>(LibViaduct.kt:5)
        at mozilla.appservices.httpconfig.LibViaduct.<clinit>(Unknown Source:0)
        	... 16 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:17)
        		... 22 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:24)
        		... 22 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "intel_aes_encrypt_cbc_128" referenced by "/data/app/org.mozilla.fenix-uaNGPqlOSzoDZAGQd1KOEw==/lib/x86_64/libfenix.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:30)
        		... 22 more
    	Suppressed: java.io.IOException: Native library (android-x86-64/libfenix.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:17)
2019-07-28 14:03:51.980 2327-2327/? E/AndroidRuntime:     at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:55)
        		... 22 more
```

**Comment by eoger** [comment]
I've got this.

**Comment by eoger** [comment]
Should get fixed by https://github.com/mozilla-mobile/fenix/pull/4391 which will include application-services@0.36.0 containing the fix.

**Comment by sv-ohorvath** [comment]
Verified the x86_64 build runs on a Xiaomi Mi Pad 2 (Android 5.1, x86-64 processor). The reporter of #4142 confirmed that it's fixed for him too.
