### ISSUE TITLE
Task :app:Bootstrap_CONDA_'Miniconda3' failed while using android studio "build" button

### ISSUE THREAD

**Issue by rxumoz** [mozilla-mobile/fenix#4349]
**Steps to reproduce**
    1. Press build button in Android studio

**Expected behavior**
    Build successfully

**Actual behavior**
    Build failed

It seems that it's releated to python path, but I've tried "unset PYTHONPATH" and delete the pythonpath set before, it still fails.**However,  using command line  "./gradlew clean app:assembleArmDebug" can build the project successfully**

Here is the log:

> Task :app:Bootstrap_CONDA_'Miniconda3'
Fatal Python error: initsite: Failed to import the site module
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth:
Traceback (most recent call last):
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/contextlib.py", line 5, in <module>
    from collections import deque
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/collections/__init__.py", line 27, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/site.py", line 47, in __boot
    addsitedir(item)
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 178, in addpackage
    import traceback
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/traceback.py", line 3, in <module>
    import collections
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/collections/__init__.py", line 27, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Bootstraping to /Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3
PREFIX=/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3
installing: python-3.7.0-hc167b69_0 ...
Python 3.7.0
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libcxxabi-4.0.1-hebd6815_0 ...
installing: xz-5.2.4-h1de35cc_4 ...
installing: yaml-0.1.7-hc338f04_2 ...
installing: zlib-1.2.11-hf3cbc9b_2 ...
installing: libcxx-4.0.1-h579ed51_0 ...
installing: openssl-1.0.2p-h1de35cc_0 ...
installing: tk-8.6.8-ha441bb4_0 ...
installing: libffi-3.2.1-h475c297_4 ...
installing: ncurses-6.1-h0a44026_0 ...
installing: libedit-3.1.20170329-hb402a30_2 ...
installing: readline-7.0-h1de35cc_5 ...
installing: sqlite-3.24.0-ha441bb4_0 ...
installing: asn1crypto-0.24.0-py37_0 ...
installing: certifi-2018.8.24-py37_1 ...
installing: chardet-3.0.4-py37_1 ...
installing: idna-2.7-py37_0 ...
installing: pycosat-0.6.3-py37h1de35cc_0 ...
installing: pycparser-2.18-py37_1 ...
installing: pysocks-1.6.8-py37_0 ...
installing: python.app-2-py37_8 ...
installing: ruamel_yaml-0.15.46-py37h1de35cc_0 ...
installing: six-1.11.0-py37_1 ...
installing: cffi-1.11.5-py37h6174b99_1 ...
installing: setuptools-40.2.0-py37_0 ...
installing: cryptography-2.3.1-py37hdbc3d79_0 ...
installing: wheel-0.31.1-py37_0 ...
installing: pip-10.0.1-py37_0 ...
installing: pyopenssl-18.0.0-py37_0 ...
installing: urllib3-1.23-py37_0 ...
installing: requests-2.19.1-py37_0 ...
installing: conda-4.5.11-py37_0 ...
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3
Installing packages via pip: [glean_parser==0.29.0]
Executing '/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/bin/pip install --trusted-host pypi.python.org --no-cache-dir glean_parser==0.29.0'
Fatal Python error: initsite: Failed to import the site module
Error processing line 1 of /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/configparser-3.5.0-py2.7-nspkg.pth:
Traceback (most recent call last):
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/contextlib.py", line 5, in <module>
    from collections import deque
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/collections/__init__.py", line 27, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/site.py", line 47, in __boot
    addsitedir(item)
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site.py", line 178, in addpackage
    import traceback
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/traceback.py", line 3, in <module>
    import collections
  File "/Users/mozillabeijing/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/collections/__init__.py", line 27, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
> Task :app:Bootstrap_CONDA_'Miniconda3' FAILED

**Comment by sanemat** [comment]
> :app:Bootstrap_CONDA_'Miniconda3'

Why we need miniconda3????
We are android project :sweat:
