### ISSUE TITLE
[Bug] Fenix crashes when opening any URL from URL bar w/ longpress

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#4438]
## Steps to reproduce
1. Launch Fenix.
2. Open any website example(any search on google.com).
3. Tap on the URL.
4. Tap again on the URL and hold.
5. Tap on the `Open` button from the floating menu.
### Expected behavior
A new tab is opened in Fenix.
### Actual behavior
Fenix crashes when opening another tab.
### Device information

| Device | Fenix Version | Status    |
| :---         |     :---:    |     ---: |
| **Samsung Galaxy S10+(Android 9)**   | **1.2.0-rc.1 (Build #12130445)**   | ⛔crash   |
| **Samsung Galaxy S10+(Android 9)**   | **Nightly 8/1 (Build #12130632)**   | ⛔crash   |
| **Google Pixel 3a XL(Android 9)**   | **1.2.0-rc.1 (Build #12130445)**   | ⛔crash   |
| **Google Pixel 3a XL(Android 9)**   | **Nightly 8/1 (Build #12130632)**  | ⛔crash  |
| **Huawei Mate 20Lite(Android 8)**   | **1.2.0-rc.1 (Build #12130445)**   | ⛔crash   |
| **Huawei Mate 20Lite(Android 8)**   | **Nightly 8/1 (Build #12130632)**  | ⛔crash  |
| **Google Pixel 3a (Android 9)**   | **1.2.0-rc.1 (Build #12130445)**   | ⛔crash   |
| **Google Pixel 3a (Android 9)**   | **Nightly 8/1 (Build #12130632)**  | ⛔crash   |
| **Samsung Galaxy S7(Android 7)**   | **Nightly 8/1 (Build #12130632)**  | OK ✅   |
| **Samsung Galaxy S7(Android 7)**    | **1.2.0-rc.1 (Build #12130445)** | OK ✅   |
| **OnePLus A3000(Android 6.0.1)**   | **1.2.0-rc.1 (Build #12130445)** | OK ✅   |
| **OnePLus A3000(Android 6.0.1)**   | **Nightly 8/1 (Build #12130632)**  | OK ✅   |

### Notes
Please note that for the devices running android below 8, the share menu was used but fenix didn't crashes.
[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3456300/logcat.txt) [Video](https://drive.google.com/file/d/1V5x0A8HQPn6reLduU8FuIrzQVcI1dLS4/view?usp=sharing)

**Comment by abodea** [comment]
```css
--------- beginning of crash
2019-08-01 13:53:50.080 26735-26735/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix, PID: 26735
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:46)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:106)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:211)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:106)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:211)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:18)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7348)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3131)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.IllegalStateException: Display already acquired
        at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:5)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:15)
        at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:3)
        at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:9)
        at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
        at mozilla.components.feature.session.SessionFeature.start(SessionFeature.kt:6)
        at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.start$support_base_release(ViewBoundFeatureWrapper.kt:1)
        at mozilla.components.support.base.feature.LifecycleBinding.start(ViewBoundFeatureWrapper.kt:1)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:4)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:46) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:5) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:2) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:7) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:106) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:211) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2) 
        at androidx.fragment.app.Fragment.performStart(Fragment.java:14) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:106) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:9) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:211) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:18) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 
        at android.app.Activity.performStart(Activity.java:7348) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3131) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7032) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) ```

**Comment by boek** [comment]
This is also a crash in 1.1

**Comment by csadilek** [comment]
This is (or is related to) a top crash we have in Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/5917855/

**Comment by csadilek** [comment]
This doesn't crash in R-B so I took a quick look. The problem is that Fenix starts two BrowserFragments. This causes the selected session (and its GeckoSession) to be attached to two different views which explains the error.

The first fragment is created/started via `HomeActivity.handleNewIntent`, the second via `HomeActivity.onCreate`.

**Comment by csadilek** [comment]
The problem goes away when using `android:launchMode="singleInstance"`, but we recently switched to "singleTask" which explains why we see the additional `onCreate` call. See: https://github.com/mozilla-mobile/fenix/commit/336ec84a52b24aaa58e3e3de97123b11170f6875

**Comment by liuche** [comment]
Also look for other entry points that might cause this same crash.

**Comment by softvision-miralobontiu** [comment]
Verified that the app doesn't crash anymore following the steps on the latest Nightly build 8/7 (#12191937) with Samsung Galaxy Note 8 (Android 9), Xiaomi Mi 8 Lite (Android 9), OnePlus 5T (Android 9), and Nexus 6P (Android 8.1).
