### ISSUE TITLE
[Bug] GeckoView configuration file causes crashes

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/fenix#4471]
## Steps to reproduce

Create `/data/local/tmp/org.mozilla.fenix-geckoview-config.yaml` (even empty, with no content), following https://mozilla.github.io/geckoview/consumer/docs/automation.  Start Fenix.  Witness crash.

### Expected behavior

No crash; configuration is respected.

### Actual behavior

```
08-01 23:15:09.896  9778  9778 I GeckoRuntime: Adding debug configuration from: /data/local/tmp/org.mozilla.fenix-geckoview-config.yaml
08-01 23:15:09.897  9778  9778 D AndroidRuntime: Shutting down VM
08-01 23:15:09.897  9778  9778 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.gecko.util.DebugConfig.mergeIntoInitInfo(org.mozilla.gecko.GeckoThread$InitInfo)' on a null object reference)
08-01 23:15:09.898  9778  9778 I mozac/CrashReporter: Showing prompt
08-01 23:15:09.902  1623  1831 I ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10067 on display 0
--------- beginning of crash
08-01 23:15:09.908  9778  9778 E AndroidRuntime: FATAL EXCEPTION: main
08-01 23:15:09.908  9778  9778 E AndroidRuntime: Process: org.mozilla.fenix, PID: 9778
08-01 23:15:09.908  9778  9778 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.gecko.util.DebugConfig.mergeIntoInitInfo(org.mozilla.gecko.GeckoThread$InitInfo)' on a null object reference
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6077)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
08-01 23:15:09.908  9778  9778 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.gecko.util.DebugConfig.mergeIntoInitInfo(org.mozilla.gecko.GeckoThread$InitInfo)' on a null object reference
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.geckoview.GeckoRuntime.init(GeckoRuntime.java:34)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.geckoview.GeckoRuntime.create(GeckoRuntime.java:8)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.components.Core$runtime$2.invoke(Core.kt:14)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.components.Core.getRuntime(Core.kt)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.components.Core$engine$2.invoke(Core.kt:10)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.components.Core.getEngine(Core.kt)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:34)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
08-01 23:15:09.908  9778  9778 E AndroidRuntime:        ... 8 more
```

This makes very little sense.  The `DebugConfig.fromFile` function is marked as returning an `@NonNull` value.  I wonder if https://github.com/mozilla-mobile/fenix/pull/3911 and [Bug 1563844](https://bugzilla.mozilla.org/show_bug.cgi?id=1563844) aren't enough here?

### Device information

* Android device: `mach android-emulator --version x86-7.0`
* Fenix version:
```
curl https://index.taskcluster.net/v1/task/project.mobile.fenix.v2.nightly.latest/artifacts/public/build/x86/target.apk
See Other. Redirecting to https://queue.taskcluster.net/v1/task/cKnKU0WtTm-24pWPNBmKJg/artifacts/public%2Fbuild%2Fx86%2Ftarget.apk⏎                                                                                                                            
```

**Comment by ncalexan** [comment]
@csadilek can you investigate?  This has reached the limit of my ability.  I will note that the GV 69 source JAR appears to disagree with the compiled `.class` file, which I don't understand (and may be relevant).

**Comment by csadilek** [comment]
@ncalexan this only fails for me for empty config files. The raptor config or just 

```
env:
  MOZ_LOG: nsHttp:5
```

work fine for me! Tested on latest master and X86 emulator as well. Looks like an empty file gets deserialized into a null `DebugInfo`?

**Comment by csadilek** [comment]
This works fine for non-empty config files. There's a follow-up for GV to return a default config rather than null for empty files, but not a Fenix issue.
