### ISSUE TITLE
[Bug] Widget voice search icon should be hidden if applications not installed to handle voice search

### ISSUE THREAD

**Issue by hakkikaancaliskan** [mozilla-mobile/fenix#4589]
If voice search application not found, voice search is crashing because it's not catched.
https://github.com/mozilla-mobile/fenix/blob/8194e0778e38ed95b769c13d91b89919fa5b4b38/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt#L103

From RecognizerIntent.java:
> NOTE: There may not be any applications installed to handle this action, so you should
> make sure to catch {@link ActivityNotFoundException}.

```
2019-08-07 16:00:43.451 7014-7014/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 7014
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.speech.action.RECOGNIZE_SPEECH (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at android.app.Activity.startActivityForResult(Activity.java:4544)
        at org.mozilla.fenix.IntentReceiverActivity.displaySpeechRecognizer(IntentReceiverActivity.kt:107)
        at org.mozilla.fenix.IntentReceiverActivity.access$displaySpeechRecognizer(IntentReceiverActivity.kt:19)
        at org.mozilla.fenix.IntentReceiverActivity$onCreate$1.invokeSuspend(IntentReceiverActivity.kt:49)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by sblatz** [comment]
Hey @hakkikaancaliskan, thanks for filing! This is a known issue, but the strack trace is helpful! Please follow https://github.com/mozilla-mobile/fenix/issues/4384
