### ISSUE TITLE
[Bug] Intermittent crash on UI tests API 25,28 due to "Error inflating class"

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/fenix#4598]
Firebase logs:

- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8808375598462826676/executions/bs.c6402a3eac1c12cb
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9146913364902185569/executions/bs.d28b6c1b3a7326ab/test-cases
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5980646345217812309/executions/bs.f0151fdaf603d61a/test-cases
- https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7752406400094525448/executions/bs.fb01164acc578f4/test-cases

```
 Fatal exception
java.lang.RuntimeException: Unable to pause activity {org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class <unknown>
FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 14272
java.lang.RuntimeException: Unable to pause activity {org.mozilla.fenix.debug/org.mozilla.fenix.HomeActivity}: android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class <unknown>
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4069)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4024)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3976)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at org.mozilla.fenix.components.toolbar.BrowserToolbarView.<init>(BrowserToolbarView.kt:36)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:150)
	at org.mozilla.fenix.browser.BrowserFragment.onViewCreated(BrowserFragment.kt:89)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:894)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1240)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1305)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2658)
	at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2628)
	at androidx.fragment.app.Fragment.performPause(Fragment.java:2780)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:935)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1240)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1305)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2658)
	at androidx.fragment.app.FragmentManagerImpl.dispatchPause(FragmentManagerImpl.java:2628)
	at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:279)
	at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:420)
	at android.app.Activity.performPause(Activity.java:7337)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnPause(MonitoringInstrumentation.java:712)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4059)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4024)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3976)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int mozilla.components.concept.toolbar.Toolbar$SiteTrackingProtection.ordinal()' on a null object reference
	at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.onCreateDrawableState(TrackingProtectionIconView.kt:63)
	at android.view.View.getDrawableState(View.java:21287)
	at android.view.View.initializeScrollbarsInternal(View.java:6005)
	at android.view.View.<init>(View.java:5569)
	at android.widget.ImageView.<init>(ImageView.java:177)
	at android.widget.ImageView.<init>(ImageView.java:172)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
	at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.<init>(TrackingProtectionIconView.kt:32)
	at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.<init>(TrackingProtectionIconView.kt:31)
	at mozilla.components.browser.toolbar.display.DisplayToolbar.<init>(DisplayToolbar.kt:92)
	at mozilla.components.browser.toolbar.BrowserToolbar.<init>(BrowserToolbar.kt:78)
	at mozilla.components.browser.toolbar.BrowserToolbar.<init>(BrowserToolbar.kt:72)
	at mozilla.components.browser.toolbar.BrowserToolbar.<init>(Unknown Source:6)
	... 39 more
 Non-SDK interfaces usage
Your app uses 16 non-SDK interfaces, which are incompatible with Android P+. Take a look at the logs to see detailed stack traces. Sample of used non-SDK interfaces: 
Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z
Landroid/os/MessageQueue;->mMessages:Landroid/os/Message;
Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface;
Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z
Ljava/lang/Boolean;->value:Z
Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z
Landroid/os/MessageQueue;->next()Landroid/os/Message;
Landroid/graphics/FontFamily;-><init>()V
Landroid/app/Activity;->mResultCode:I
Landroid/graphics/FontFamily;->freeze()Z
Landroid/app/Activity;->mResultData:Landroid/content/Intent;
Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
Ljava/lang/Integer;->value:I
Ljava/lang/Double;->value:D
Landroid/graphics/FontFamily;->abortCreation()V
Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate;
```

**Comment by Amejia481** [comment]
This should be fixed after using the latest snapshot

**Comment by sblatz** [comment]
From https://github.com/mozilla-mobile/android-components/commit/c000217b565cf7f96996de04c8da27ea41874a25

**Comment by rpappalax** [comment]
Fixed, thanks!
