### ISSUE TITLE
[Bug] Crash opening search bar after clearing data

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#4604]
## Steps to reproduce
1. Install the current master Fenix build
2. Open a tab or tabs.
3. Delete all tabs from Settings.
4. Return to home.
5. Press the search bar.

### Expected behavior
The search fragment should open.

### Actual behavior
The app crashes with this stack trace:
2019-08-07 16:00:42.690 org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 30351
    android.view.InflateException: Binary XML file line #5: Binary XML file line #5: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at org.mozilla.fenix.search.toolbar.ToolbarView.<init>(ToolbarView.kt:60)
        at org.mozilla.fenix.search.SearchFragment.onCreateView(SearchFragment.kt:95)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2605)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:882)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2099)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1873)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1829)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1729)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:151)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int mozilla.components.concept.toolbar.Toolbar$SiteTrackingProtection.ordinal()' on a null object reference
        at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.onCreateDrawableState(TrackingProtectionIconView.kt:63)
        at android.view.View.getDrawableState(View.java:20212)
        at android.view.View.initializeScrollbarsInternal(View.java:5745)
        at android.view.View.<init>(View.java:5309)
        at android.widget.ImageView.<init>(ImageView.java:176)
        at android.widget.ImageView.<init>(ImageView.java:171)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:72)
        at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.<init>(TrackingProtectionIconView.kt:32)
        at mozilla.components.browser.toolbar.display.TrackingProtectionIconView.<init>(TrackingProtectionIconView.kt:31)
        at mozilla.components.browser.toolbar.display.DisplayToolbar.<init>(DisplayToolbar.kt:92)
        at mozilla.components.browser.toolbar.BrowserToolbar.<init>(BrowserToolbar.kt:78)
        at mozilla.components.browser.toolbar.BrowserToolbar.<init>(BrowserToolbar.kt:72)
        at mozilla.components.browser.toolbar.BrowserToolbar.<init>(Unknown Source:6)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at org.mozilla.fenix.search.toolbar.ToolbarView.<init>(ToolbarView.kt:60) 
        at org.mozilla.fenix.search.SearchFragment.onCreateView(SearchFragment.kt:95) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2605) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:882) 
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2099) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1873) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1829) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1729) 
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:151) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

### Device information

* Android device: Pixel 5X
* Fenix version: master

**Comment by ekager** [comment]
Seems to be an issue with the new `TrackingProtectionIconView`. CC @Amejia481

**Comment by Amejia481** [comment]
I'm on it, thanks @ekager!

**Comment by Amejia481** [comment]
This will be fix as soon a the new snapshot kicks in https://github.com/mozilla-mobile/android-components/commit/c000217b565cf7f96996de04c8da27ea41874a25

**Comment by ekager** [comment]
Closing as we should have the new snapshot now
