### ISSUE TITLE
[Bug] Send Tab (push) is broken on latest nightly

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4635]
Send tab works when polling, but push support seems to no longer work. Seems to be fine on a local debug version 

**Not working:**
Nightly 190808 19:19 (Build #12201930)
📦: 8.0.0, c000217b5
🦎: 69.0-20190808090046
Thursday 8/8 @ 7:29 PM

**Working:**
1.0.1932 (Build #1)
📦: 8.0.0, c000217b5
🦎: 69.0-20190808090046
Thursday 8/8 @ 5:38 PM

**Comment by jonalmeida** [comment]
I guess I should look into it.

**Comment by jonalmeida** [comment]
Seems like something is failing silently:
```
2019-08-09 14:27:06.657 org.mozilla.fenix.debug D/fxaclient_ffi: fxa_handle_push_message
2019-08-09 14:27:06.663 org.mozilla.fenix.debug E/FxaDeviceConstellation: Error while running: processing raw events
    mozilla.appservices.fxaclient.FxaException$Unspecified: JSON error: unknown variant `fxaccounts:device_connected`, expected `fxaccounts:command_received` at line 1 column 52
        at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:48)
        at mozilla.appservices.fxaclient.FirefoxAccount.handlePushMessage(FirefoxAccount.kt:751)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:80)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1$1.invoke(FxaDeviceConstellation.kt:35)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Utils.kt:64)
        at mozilla.components.service.fxa.UtilsKt$handleFxaExceptions$5.invoke(Unknown Source:0)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:30)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:56)
        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:63)
        at mozilla.components.service.fxa.FxaDeviceConstellation$processRawEventAsync$1.invokeSuspend(FxaDeviceConstellation.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by jonalmeida** [comment]
This should be fixed with the [0.37.1 release](https://github.com/mozilla/application-services/tree/v0.37.1) of a-s that is in a-c 9.0.0.

**Comment by jonalmeida** [comment]
With the Rust changes I still can't figure out what's causing the issues with nightly failing. Send Tab + push seems to be working fine in release, so either:
1. Something has changed in nightly configurations that has broken.
2. Something has changed in 1.3 that I can't seem to reproduce on a debug build.

**Comment by jonalmeida** [comment]
This is working now, so I'm just going to close this issue before it breaks again.
