### ISSUE TITLE
IllegalStateException: Fragment SearchFragment{c8236a4 (9416f8ea-eb64-450b-a71b-cca8bcb9148e)} not attached to a context.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#4725]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6103753/

```
IllegalStateException: Fragment SearchFragment{c8236a4 (9416f8ea-eb64-450b-a71b-cca8bcb9148e)} not attached to a context.
    at org.mozilla.fenix.search.SearchFragment.updateSearchEngineIcon(SearchFragment.kt:4)
    at org.mozilla.fenix.search.SearchFragment.access$updateSearchEngineIcon(SearchFragment.kt:1)
    at org.mozilla.fenix.search.SearchFragment$onViewCreated$5.invoke(SearchFragment.kt:38)
...
(10 additional frame(s) were not displayed)

Fragment SearchFragment{c8236a4 (9416f8ea-eb64-450b-a71b-cca8bcb9148e)} not attached to a context.
```

**Comment by pocmo** [comment]
There seems to be an edge case where we can crash from inside `consumeFrom`. @csadilek and I looked at this recently.

The number of crashes have spiked a little bit in the last days so I'm going to investigate this. It's suspicious that this is only happening in `SearchFragment`.

**Comment by pocmo** [comment]
Okay, I have a theory what happens and will continue in AC:
https://github.com/mozilla-mobile/android-components/issues/4125

**Comment by pocmo** [comment]
Sentry issue: [FENIX-26F](https://sentry.prod.mozaws.net/operations/fenix/issues/6125575/)

**Comment by pocmo** [comment]
Should be fixed with the next snapshot/release.
