### ISSUE TITLE
IllegalStateException: JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tr...

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#4820]
https://sentry.prod.mozaws.net/operations/fenix/issues/5888950/

```
IllegalStateException: Apps may not schedule more than 100 distinct jobs
    at android.os.Parcel.readException(Parcel.java:1692)
    at android.os.Parcel.readException(Parcel.java:1637)
    at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
    at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
    at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:5)
...
(6 additional frame(s) were not displayed)

IllegalStateException: JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tracked jobs in our DB; our Configuration limit is 20.
    at androidx.work.impl.background.systemjob.SystemJobScheduler.scheduleInternal(SystemJobScheduler.java:17)
    at androidx.work.impl.background.systemjob.SystemJobScheduler.schedule(SystemJobScheduler.java:31)
    at androidx.work.impl.Schedulers.schedule(Schedulers.java:15)
    at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
...
(2 additional frame(s) were not displayed)

JobScheduler 100 job limit exceeded.  We count 101 WorkManager jobs in JobScheduler; we have 2 tracked jobs in our DB; our Configuration limit is 20.
```

**Comment by jonalmeida** [comment]
We have two consumers for WorkManager that are only in a-c not Fenix (but tracking this bug here): Glean and Sync.

The device seems fairly niche and the errors showed up repeatedly in a short span of time. 

I think I should look into what unique work we're scheduling:
- Are we cancelling the work?
- Are we using any back-off techniques if we aren't able to reach our telemetry or sync servers?

**Comment by jonalmeida** [comment]
> Are we cancelling the work?
> Are we scheduling the same work with a different unique id that makes it seem as a new job?

Yes, the `PingUploadWorker`, `WorkManagerSyncDispatcher` and `MetricsPingScheduler` all have work tasks that are either replace scheduled jobs that never completed or don't schedule new jobs if there is one already pending.

> Are we using any back-off techniques if we aren't able to reach our telemetry or sync servers?

With the above, I don't think we'd need to worry about backing off, but that is a policy option available.

Since this hasn't happened on a recent build, I'm going to close this issue as invalid; I don't think there's anything we can do with the logs we have and the one-off instance.

**Comment by ding33211** [comment]
Same for me. fixed now?
