### ISSUE TITLE
[Bug] Fenix Crashes while opening 

### ISSUE THREAD

**Issue by jawadalkassim** [mozilla-mobile/fenix#4827]
## Steps to reproduce
Launch fenix
the app crashes and force stop it self also go back to home screen
with a window to send crash data to mozilla

### Expected behavior
Launch the browser without issues
### Actual behavior
Crashes , can't open the browser
### Device information
Huawei P8 lite 2017
* Android device: 
Android 8.0
* Fenix version: 
Nightly 190820 06.04

**Comment by Mugurell** [comment]
This happens because of a recent change from #4744 
```
Caused by: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
        at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:918)
        at android.view.ViewTreeObserver.removeOnPreDrawListener(ViewTreeObserver.java:645)
        at org.mozilla.fenix.home.TransitionPreDrawListener$onPreDraw$2.invoke(TransitionPreDrawListener.kt:43)
        at org.mozilla.fenix.home.TransitionPreDrawListener$onPreDraw$2.invoke(TransitionPreDrawListener.kt:16)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1286)
```

Will work on a fix asap.

**Comment by jawadalkassim** [comment]
Sounds good, new nightly update
fix the issue
