### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#4882]
https://sentry.prod.mozaws.net/operations/fenix/issues/6152338/

```
IllegalStateException: Can not perform this action after onSaveInstanceState
    at org.mozilla.fenix.home.HomeFragment.restoreLayoutState(HomeFragment.kt:5)
    at org.mozilla.fenix.home.HomeFragment.access$restoreLayoutState(HomeFragment.kt:1)
    at org.mozilla.fenix.home.HomeFragment$preDrawListener$1$onPreDraw$1.invokeSuspend(HomeFragment.kt:6)
...
(15 additional frame(s) were not displayed)

Can not perform this action after onSaveInstanceState
```

**Comment by kbrosnan** [comment]
Might be related to/dupe #3258 or #4652

**Comment by boek** [comment]
This issue hasn't been seen since 1.3.1.

Going to close this until we see it again
