### ISSUE TITLE
[Bug] (regression) start-up crash on debug builds

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#4960]
### Steps to reproduce

1. start Fenix

### Expected behavior

No crash.

### Actual behavior

Fenix crashes.

```
2019-08-27 22:19:24.234 31429-31429/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 31429
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.DebugFenixApplication: kotlin.UninitializedPropertyAccessException: lateinit property fretboard has not been initialized
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6259)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property fretboard has not been initialized
        at org.mozilla.fenix.FenixApplication.getFretboard(FenixApplication.kt:40)
        at org.mozilla.fenix.ExperimentsKt.isInExperiment(Experiments.kt:28)
        at org.mozilla.fenix.components.BackgroundServices.<init>(BackgroundServices.kt:82)
        at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:17)
        at org.mozilla.fenix.components.Components$backgroundServices$2.invoke(Components.kt:15)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.mozilla.fenix.components.Components.getBackgroundServices(Unknown Source:7)
        at org.mozilla.fenix.FenixApplication.setupPush(FenixApplication.kt:187)
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:69)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:49)
        at org.mozilla.fenix.DebugFenixApplication.onCreate(DebugFenixApplication.kt:42)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1167)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6254)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:210) 
        at android.app.ActivityThread.main(ActivityThread.java:7124) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898) 
```

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: Fenix from master branch (revision bfb2beabe7f508946165ab45e506fcd3d40cf3bf)

**Comment by cadeyrn** [comment]
Yes, it's fixed. Thank you!
