### ISSUE TITLE
[Bug] Fenix crashes when sharing to copy to clipboard

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/fenix#5099]
## Steps to reproduce
Press share from the Quick Action Sheet or the overflow menu.
Choose copy to clipboard.

### Expected behavior
The URL gets copied to the clipboard.

### Actual behavior
Fenix crashes.

### Device information

* Android device: Pixel 3 XL, Android 10
* Fenix version: Latest Nightly

**Comment by Mugurell** [comment]
A crash for the following stacktrace
```
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.SEND typ=text/plain flg=0x10000001 cmp=com.google.android.apps.maps/com.google.android.apps.gmm.sharing.SendTextToClipboardActivity clip={text/plain T:https://support.mozilla.org/en-US/products/firefox-preview?as=u&utm_source=inproduct} (has extras) } from ProcessRecord{f89381f 30577:org.mozilla.fenix.debug/u0a720} (pid=30577, uid=10720) not exported from uid 10156
        at android.os.Parcel.readException(Parcel.java:1967)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4884)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
        at android.app.Activity.startActivityForResult(Activity.java:4564)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:790)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
        at androidx.fragment.app.Fragment.startActivity(Fragment.java:1225)
        at androidx.fragment.app.Fragment.startActivity(Fragment.java:1213)
        at org.mozilla.fenix.share.DefaultShareController.handleShareToApp(ShareController.kt:63)
        at org.mozilla.fenix.share.ShareInteractor.onShareToApp(ShareInteractor.kt:37)
        at org.mozilla.fenix.share.viewholders.AppViewHolder$1.onClick(AppViewHolder.kt:26)
```
is to be resolved in #5053
Closing this as a dupe. If you think this is not the case please reopen.
