### ISSUE TITLE
[Bug] FxA Sign in does not work with QR scanning

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5175]
## Steps to reproduce
1. Attempt to scan a QR code.
2. Click the approve button on both devices (desktop & fenix).

### Expected behavior
- A paired Fenix device.

### Actual behavior
- You see the pair screen again.
- You are not signed in.

### Device information

* Android device: Android 10 (Pixel 2)
* Fenix version: master (1b2e67b8)

> 1.0.1937 (Build #1)
> 📦: 12.0.0, 5a039210c
> 🦎: 71.0a1-20190908094652

### Crash log
```
    --------- beginning of crash
2019-09-09 11:57:12.318 org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 3712
    kotlin.KotlinNullPointerException
        at mozilla.components.feature.accounts.FirefoxAccountsAuthFeature$interceptor$1.onLoadRequest(FirefoxAccountsAuthFeature.kt:71)
        at org.mozilla.fenix.AppRequestInterceptor.onLoadRequest(AppRequestInterceptor.kt:29)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:312)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:565)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:519)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:80)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:373)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by kbrosnan** [comment]
Dupe #3580

**Comment by jonalmeida** [comment]
Closing!
