### ISSUE TITLE
CannotUpdateRoot: Invalid place info: Cannot update the bookmark root Root

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#5198]
From the stacktrace, it seems like we're trying to add a folder with Root as a parent.. (updating its children list). Not sure what else would trigger a root update otherwise.

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6249053/

```
mozilla.appservices.places.CannotUpdateRoot: Invalid place info: Cannot update the bookmark root Root
    at mozilla.appservices.places.RustError.intoException(RustError.kt:5)
    at mozilla.appservices.places.PlacesWriterConnection.doInsert(PlacesConnection.kt:17)
    at mozilla.appservices.places.PlacesWriterConnection.createFolder(PlacesConnection.kt:5)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$addFolder$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
    at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$addFolder$2.invoke
    at io.reactivex.plugins.RxJavaPlugins.startUndispatchedOrReturn(RxJavaPlugins.java:2)
    at io.reactivex.plugins.RxJavaPlugins.withContext(RxJavaPlugins.java:9)
    at org.mozilla.fenix.library.bookmarks.addfolder.AddBookmarkFolderFragment$onOptionsItemSelected$1.invokeSuspend(AddBookmarkFolderFragment.kt:9)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:47)
```

**Comment by grigoryk** [comment]
cc @colintheshots @thomcc

**Comment by ValentinTimisica** [comment]
I saw in the [sentry issue](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6249053/) that "This issue has been marked as resolved.". Seems like the crash hasn't happened for several months. I think we should close this.
