### ISSUE TITLE
Failing megazord: ExceptionInInitializerError

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#5199]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6242594/

```
UnsatisfiedLinkError: Native library (com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource path (.)
    at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:12)
    at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:35)
    at com.sun.jna.Native.<clinit>(Native.java:12)
    at com.sun.jna.Native.load(Native.java:3)
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:4)
...
(16 additional frame(s) were not displayed)

MegazordNotAvailable: Failed to locate megazord library: 'viaduct'
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1$$special$$inlined$loadIndirect$1.invoke(Helpers.kt:1)
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1$$special$$inlined$loadIndirect$1.invoke
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy0.viaduct_force_enable_ffi_backend
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:9)
...
(16 additional frame(s) were not displayed)

UndeclaredThrowableException: None
    at $Proxy0.viaduct_force_enable_ffi_backend
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:9)
    at mozilla.appservices.httpconfig.LibViaduct$Companion$INSTANCE$1.invoke(LibViaduct.kt:1)
    at mozilla.appservices.httpconfig.LibViaduct$Companion.<clinit>(LibViaduct.kt:2)
    at mozilla.appservices.httpconfig.LibViaduct.<clinit>
...
(13 additional frame(s) were not displayed)

ExceptionInInitializerError: None
    at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:26)
    at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
...
(9 additional frame(s) were not displayed)
```

**Comment by grigoryk** [comment]
cc @thomcc @eoger

**Comment by ekager** [comment]
Last seen 25 days ago so this feels safe to close
