### ISSUE TITLE
IllegalStateException: No selected session (ToolbarUIView)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#521]
```
java.lang.IllegalStateException: No selected session
    at mozilla.components.browser.session.SessionManager.getSelectedSessionOrThrow(SessionManager.kt:1)
    at org.mozilla.fenix.components.toolbar.ToolbarUIView$2$1.invoke(ToolbarUIView.kt:1)
    at mozilla.components.browser.menu.item.BrowserMenuCompoundButton.bind(BrowserMenuCompoundButton.kt:3)
    at mozilla.components.browser.menu.BrowserMenuAdapter.onBindViewHolder(BrowserMenuAdapter.kt:2)
    at mozilla.components.browser.menu.BrowserMenuAdapter.onBindViewHolder(BrowserMenuAdapter.kt:1)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:63)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:8)
```

This happens when you're in a Custom Tab session and you try to open the menu. It doesn't crash if the app adds it's own menu items in.

**Comment by ekager** [comment]
From what I can tell the Yelp app doesn't add any custom menu items, and I can't reproduce this. @jonalmeida are you still seeing this with whatever app you were using?

**Comment by jonalmeida** [comment]
Can't seem to reproduce this because Fenix is no longer in the share menu.. 🤔

**Comment by jonalmeida** [comment]
Filed https://github.com/mozilla-mobile/fenix/issues/1054 to fix this and I'll verify this issue after that.

**Comment by jonalmeida** [comment]
Verified locally, LTGM!
