### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5381]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6307868/

```
IndexOutOfBoundsException: Invalid index 0, size is 0
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at androidx.lifecycle.LifecycleRegistry.calculateTargetState(LifecycleRegistry.java:5)
    at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:6)
    at org.mozilla.fenix.components.metrics.GleanMetricsService$start$1.invokeSuspend(GleanMetricsService.kt:43)
...
(4 additional frame(s) were not displayed)

Invalid index 0, size is 0
```

**Comment by ekager** [comment]
Looks like this was only happening for a few hours that day. Closing!
