### ISSUE TITLE
IllegalArgumentException: Display not attached

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#5413]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6318758/

```
IllegalArgumentException: Display not attached
    at org.mozilla.geckoview.GeckoSession.releaseDisplay(GeckoSession.java:4)
    at org.mozilla.geckoview.GeckoView.releaseSession(GeckoView.java:5)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:4)
    at mozilla.components.browser.engine.gecko.GeckoEngineView$observer$1.onProcessKilled(GeckoEngineView.kt:2)
    at -$$LambdaGroup$ks$Z8dqYW9GoSSuB-RCTvkI6noFY1k.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:17)
...
(14 additional frame(s) were not displayed)

Display not attached
```

**Comment by pocmo** [comment]
Still 1 user and 1 event. Removing from the AC triage list for now.

**Comment by ekager** [comment]
If this has only 1 user 1 event still we can probably close it?
