### ISSUE TITLE
IllegalStateException: Display already acquired

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#575]
https://sentry.prod.mozaws.net/operations/fenix/issues/5226813/

```
IllegalStateException: Display already acquired
    at org.mozilla.geckoview.GeckoSession.acquireDisplay(GeckoSession.java:6)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:17)
    at org.mozilla.geckoview.GeckoView.setSession(GeckoView.java:4)
    at mozilla.components.browser.engine.gecko.GeckoEngineView.render(GeckoEngineView.kt:5)
    at mozilla.components.feature.session.EngineViewPresenter.renderSession$feature_session_release(EngineViewPresenter.kt:1)
...
(44 additional frame(s) were not displayed)

RuntimeException: Failed to call observer method
    at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:6)
    at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:2)
    at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:2)
    at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:3)
    at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:40)
...
(34 additional frame(s) were not displayed)

Failed to call observer method
```

**Comment by pocmo** [comment]
This exception happens if there are two `GeckoView` instances rendering the same session.

We fixed a similar issue previously where the browser activity and the custom tab activity accidentally tried to render the same session. This seems to be another case.

**Comment by pocmo** [comment]
STR:

```
- Open fenix and open a tab
- Open a private tab too.
- Switch to a different app with a link that opens a custom tab -> click
- Go to the launcher so that the app is in the background.
- Kill the app process via adb
- Resume the custom tab ... it won't get restored and you are in the third-party app again
- Click again on a link to open a custom tab -> Crashes every time
```

Some steps may not be needed.

**Comment by colintheshots** [comment]
Those STR aren't reliable for me. Here's what does work reliably for me:

```
- Start app.
- Open a custom tab from Slack.
- Force stop the app.
- Open any custom tab from Slack.
```

**Comment by colintheshots** [comment]
Having done some diagnosis, I can say with some confidence that the bug was introduced in e5fe80f9283713f97472b5e67838addd057656f9.

**Comment by colintheshots** [comment]
I got it.

The DefaultBrowsingModeManager keeps a reference to the HomeActivity. This on its own is bad. On restarting the app after the OS kills it off, this reference becomes stale. Then we recreate the Activity immediately to apply the public/private theme while the app already started loading the custom tabs.
