### ISSUE TITLE
[Bug] NullPointerException at org.mozilla.fenix.browser.BaseBrowserFragment$adjustBackgroundAndNavigate$$inlined$let$lambda$1$1.invokeSuspend(BaseBrowserFragment.kt:5)

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/fenix#6013]
## Steps to reproduce

Unknown

### Expected behavior

No NullPointerException

### Actual behavior

This is a recent top crash regression in Fenix Nightly with GV 71. Here is a crash report in Socorro:

https://crash-stats.mozilla.org/report/index/268ce68d-c8f8-4805-b175-d96c20191012

Why did this unhandled Java exception get sent to Socorro instead of Sentry?

```
Java stack trace:

java.lang.NullPointerException
	at org.mozilla.fenix.browser.BaseBrowserFragment$adjustBackgroundAndNavigate$$inlined$let$lambda$1$1.invokeSuspend(BaseBrowserFragment.kt:5)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:17)
	at io.reactivex.plugins.RxJavaPlugins.startCoroutineCancellable(RxJavaPlugins.java:1)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:13)
	at io.reactivex.plugins.RxJavaPlugins.launch(RxJavaPlugins.java:5)
	at io.reactivex.plugins.RxJavaPlugins.launch$default(RxJavaPlugins.java:2)
	at org.mozilla.fenix.browser.BaseBrowserFragment$adjustBackgroundAndNavigate$$inlined$let$lambda$1.invoke(BaseBrowserFragment.kt:2)
	at mozilla.components.browser.engine.gecko.GeckoEngineView$captureThumbnail$1.onValue(GeckoEngineView.kt:2)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(Unknown Source:8)
	at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

This crash bug was originally filed in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1588513

### Device information

* Android device: Samsung Starqltesq SM-G960U (Android 9.0 Pie)
* Fenix version: Fenix Nightly with GV 71 build 20191004094656.

**Comment by pocmo** [comment]
> Why did this unhandled Java exception get sent to Socorro instead of Sentry?

See #4736

**Comment by Baron-Severin** [comment]
Not sure what to make of this crash report.  `BaseBrowserFragment#adjustBackgroundAndNavigate` null checks everything it touches.  The stack trace includes `RxJavaPlugins`, and afaict there's no Rx anywhere near this code path (in fact, we've recently removed Rx from our project entirely).  We're reaching out for other opinions on this, but otherwise unclear on how to proceed.

**Comment by Baron-Severin** [comment]
We've also been unable to find any instances of this crash since October 27th.

**Comment by kbrosnan** [comment]
Agreed after talking with @boek lets close this.
