### ISSUE TITLE
[Bug] Fenix crashes when opening a custom tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#6259]
### Steps to reproduce

1. make sure Fenix is your default browser
2. press a link in an external app with custom tab support

### Expected behavior

no crash.

### Actual behavior

```
2019-10-24 22:21:28.142 12291-12291/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 12291
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/Integer;Landroid/graphics/Bitmap;ZLmozilla/components/browser/state/state/CustomTabActionButtonConfig;ZZLjava/util/List;Landroid/os/Bundle;Ljava/lang/Integer;ZLandroidx/browser/customtabs/CustomTabsSessionToken;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lmozilla/components/browser/state/state/CustomTabConfig; or its super classes (declaration of 'mozilla.components.browser.state.state.CustomTabConfig' appears in /data/app/org.mozilla.fenix.debug-h4pkVGVzjKsclu7SRAwEnw==/base.apk!classes3.dex)
        at mozilla.components.feature.customtabs.CustomTabConfigHelperKt.createCustomTabConfigFromIntent(CustomTabConfigHelper.kt:89)
        at mozilla.components.feature.customtabs.CustomTabIntentProcessor.process(CustomTabIntentProcessor.kt:40)
        at org.mozilla.fenix.IntentReceiverActivity.processIntent(IntentReceiverActivity.kt:65)
        at org.mozilla.fenix.IntentReceiverActivity$onCreate$1.invokeSuspend(IntentReceiverActivity.kt:35)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:898)
```

### Device information

* Android device: HTC U11 / Android 9.0
* Fenix version: master branch revision 6290c0c82610be319cdc39de3b633a28947bab1f

**Comment by cadeyrn** [comment]
I can no longer reproduce.
