### ISSUE TITLE
[Bug]Crash after closing or force stopping Fenix 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/fenix#6452]
## Steps to reproduce
1. Open Fenix
2. Close the app from the recent applications menu (or Force stop it)
3. Reopen the app

### Expected behavior
No issues starting up Fenix again

### Actual behavior
Crash

### Device information
* Android device: 
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

* Fenix version: Nightly 191105 06:01 (Build #13090608) 📦: 20.0.0, 1bae81951 🦎: 72.0a1-20191103094618

### Notes
► **Video**
![20191105_155034](https://user-images.githubusercontent.com/51314259/68213472-4cf10100-ffe4-11e9-8e44-0fb55492dffa.gif)

► **Crash log**
`    --------- beginning of crash
2019-11-05 15:40:40.172 14649-14649/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 14649
    java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: Unexpected format in VersionString
        at mozilla.components.service.experiments.util.VersionString.compareTo(VersionString.kt:11)
        at mozilla.components.service.experiments.ExperimentEvaluator.findActiveExperiment$service_experiments_release(ExperimentEvaluator.kt:30)
        at mozilla.components.service.experiments.ExperimentsInternalAPI.findAndStartActiveExperiment$service_experiments_release(Experiments.kt:4)
        at org.mozilla.fenix.FenixApplication.setupApplication(FenixApplication.kt:98)
        at org.mozilla.fenix.FenixApplication.onCreate(FenixApplication.kt:2)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-11-05 15:40:40.172 14649-14672/? D/App: Experiments active: {asFeatureSyncDisabled=false}
2019-11-05 15:40:40.172 14649-14649/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.lang.IllegalArgumentException: Unexpected format in VersionString, breadcrumbs=[])
2019-11-05 15:40:40.173 14649-14649/? I/mozac/CrashReporter: Showing prompt
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load sqlite done
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load nss start
2019-11-05 15:40:40.174 14649-14669/? E/GeckoLibLoad: Load nss done
2019-11-05 15:40:40.175 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libxul.so: unhandled flags #8 not handled
2019-11-05 15:40:40.175 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/liblgpllibs.so: unhandled flags #8 not handled
2019-11-05 15:40:40.182 1171-1561/? I/ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10170
2019-11-05 15:40:40.185 767-767/? D/android.hardware.power@1.3-service.bonito-libperfmgr: LAUNCH ON
2019-11-05 15:40:40.191 1171-1196/? I/ActivityManager: Showing crash dialog for package org.mozilla.fenix.nightly u0
2019-11-05 15:40:40.194 1171-1195/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
2019-11-05 15:40:40.195 1171-1195/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
2019-11-05 15:40:40.202 14649-14669/? E/GeckoLibLoad: Loaded libs in 27.382919ms total, 13ms(26ms) user, 0ms(6ms) system, 0(0) faults
2019-11-05 15:40:40.202 14649-14669/? D/GeckoThread: State changed to LIBS_READY
2019-11-05 15:40:40.202 14649-14669/? W/GeckoThread: zerdatime 2254382 - runGecko
2019-11-05 15:40:40.209 14649-14669/? D/GeckoProfile: Loading profile at: null name: default
2019-11-05 15:40:40.210 14649-14669/? D/GeckoProfile: Found profile dir: /data/user/0/org.mozilla.fenix.nightly/files/mozilla/d71t33mc.default
2019-11-05 15:40:40.218 1171-1197/? I/ActivityManager: Start proc 14686:org.mozilla.fenix.nightly:tab/u0a170 for service org.mozilla.fenix.nightly/org.mozilla.gecko.process.GeckoServiceChildProcess$tab
2019-11-05 15:40:40.222 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.changepixelformat"
2019-11-05 15:40:40.227 14686-14686/? E/nix.nightly:ta: Not starting debugger since process cannot load the jdwp agent.
2019-11-05 15:40:40.252 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.256 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.263 14686-14686/? I/nix.nightly:ta: The ClassLoaderContext is a special shared library.
2019-11-05 15:40:40.267 1171-6599/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-11-05 15:40:40.271 14686-14686/? W/nix.nightly:ta: resources.arsc in APK '/data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/base.apk' is compressed.
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
2019-11-05 15:40:40.292 14686-14686/? W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2019-11-05 15:40:40.293 14686-14686/? D/io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.
2019-11-05 15:40:40.301 14686-14686/? D/RustNativeSupport: findMegazordLibraryName(viaduct, 0.42.2
2019-11-05 15:40:40.302 14686-14686/? D/RustNativeSupport: lib in use: none
2019-11-05 15:40:40.302 14686-14686/? D/RustNativeSupport: lib configured: fenix
2019-11-05 15:40:40.302 14686-14686/? D/RustNativeSupport: lib version configured: 0.42.2
2019-11-05 15:40:40.302 14686-14686/? D/RustNativeSupport: settled on fenix
2019-11-05 15:40:40.313 14686-14686/? D/RustNativeSupport: findMegazordLibraryName(rustlog, 0.42.2
2019-11-05 15:40:40.313 14686-14686/? D/RustNativeSupport: lib in use: none
2019-11-05 15:40:40.313 14686-14686/? D/RustNativeSupport: lib configured: fenix
2019-11-05 15:40:40.313 14686-14686/? D/RustNativeSupport: lib version configured: 0.42.2
2019-11-05 15:40:40.313 14686-14686/? D/RustNativeSupport: settled on fenix
2019-11-05 15:40:40.315 14686-14686/? I/rc_log_ffi::ios: rc_log adapter initialized!
2019-11-05 15:40:40.320 14686-14686/? D/GeckoThread: State changed to LAUNCHED
2019-11-05 15:40:40.320 14686-14706/? I/GeckoThread: preparing to run Gecko
2019-11-05 15:40:40.354 14649-14669/? I/Gecko:DumpUtils: Fifo watcher disabled via pref.
2019-11-05 15:40:40.399 14649-14669/? D/GeckoSysInfo: System memory: 3593MB.
2019-11-05 15:40:40.400 14649-14669/? D/GeckoThread: State changed to JNI_READY
2019-11-05 15:40:40.563 14649-14669/? I/Gecko: 1572961240561	addons.xpi	WARN	List of valid built-in add-ons could not be parsed.: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: startup :: line 2362"  data: no] Stack trace: startup()@resource://gre/modules/addons/XPIProvider.jsm:2362
    callProvider()@resource://gre/modules/AddonManager.jsm:215
    _startProvider()@resource://gre/modules/AddonManager.jsm:651
    startup()@resource://gre/modules/AddonManager.jsm:875
    startup()@resource://gre/modules/AddonManager.jsm:3534
    observe()@resource://gre/modules/addonManager.js:87
2019-11-05 15:40:40.630 14649-14669/? D/GeckoThread: State changed to PROFILE_READY
2019-11-05 15:40:40.676 14649-14669/? W/GeckoEventDispatcher: No listener for AndroidCastDevice:SyncDevice
2019-11-05 15:40:40.679 14649-14669/? I/Gecko: -*- nsDNSServiceDiscovery.js : nsDNSServiceDiscovery
2019-11-05 15:40:40.684 1171-1195/? W/ActivityManager: Activity pause timeout for ActivityRecord{53f15e0 u0 org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity t55 f}
2019-11-05 15:40:40.758 575-607/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen org.mozilla.fenix.nightly#0
2019-11-05 15:40:40.758 575-607/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen org.mozilla.fenix.nightly#0
2019-11-05 15:40:40.764 1171-1313/? W/WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5512 com.android.server.wm.WindowManagerService.removeWindow:1641 com.android.server.wm.Session.remove:226 
2019-11-05 15:40:40.766 1171-1194/? I/ActivityManager: Displayed org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity: +825ms
2019-11-05 15:40:40.771 14649-14669/? I/Gecko: Attempting load of libEGL.so
2019-11-05 15:40:40.768 14649-14649/? W/Gecko: type=1400 audit(0.0:853): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20402 scontext=u:r:untrusted_app:s0:c170,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2019-11-05 15:40:40.773 14649-14669/? E/libc: Access denied finding property "vendor.debug.egl.profiler"
2019-11-05 15:40:40.774 14649-14669/? I/Adreno: QUALCOMM build                   : 97eb455, I987d6683f9
    Build Date                       : 11/29/18
    OpenGL ES Shader Compiler Version: EV031.25.03.02
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2019-11-05 15:40:40.774 14649-14669/? I/Adreno: Build Config                     : S P 4.0.10 AArch32
2019-11-05 15:40:40.777 14649-14669/? E/libc: Access denied finding property "ro.vendor.graphics.memory"
2019-11-05 15:40:40.775 14649-14649/? W/Gecko: type=1400 audit(0.0:854): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=20402 scontext=u:r:untrusted_app:s0:c170,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2019-11-05 15:40:40.778 14649-14669/? I/Adreno: PFP: 0x016ee176, ME: 0x00000000
2019-11-05 15:40:40.780 14649-14669/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
2019-11-05 15:40:40.781 14649-14669/? I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
2019-11-05 15:40:40.784 767-767/? D/android.hardware.power@1.3-service.bonito-libperfmgr: LAUNCH OFF
2019-11-05 15:40:41.005 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libsoftokn3.so: unhandled flags #8 not handled
2019-11-05 15:40:41.006 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libsoftokn3.so: Relocation to NULL @0x00025ffc for symbol "__cxa_type_match"
2019-11-05 15:40:41.007 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libfreebl3.so: unhandled flags #8 not handled
2019-11-05 15:40:41.008 14649-14669/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libfreebl3.so: Relocation to NULL @0x00041ffc for symbol "__cxa_type_match"
2019-11-05 15:40:41.036 14649-14736/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libnssckbi.so: unhandled flags #8 not handled
2019-11-05 15:40:41.037 14649-14736/? W/GeckoLinker: /data/app/org.mozilla.fenix.nightly-IAGyNfpglfY2FZ1lZZ_36A==/lib/arm/libnssckbi.so: Relocation to NULL @0x00051ffc for symbol "__cxa_type_match"
2019-11-05 15:40:41.775 1576-1576/? I/PowerUI: currentTemp=30.490002,overheatType=1,isOverheatAlarm=false,thresholdTemp=63.0,batteryStatus=2,recentTemps=30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.490002,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.392002,30.392002,30.392002,30.392002,30.392002,30.392002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.490002,30.490002,30.441002,30.441002,30.490002,30.441002,30.441002,30.441002,30.490002,30.441002,30.490002,
2019-11-05 15:40:42.962 2014-2712/? W/GCoreFlp: No location to return for getLastLocation()
2019-11-05 15:40:43.032 1576-1576/? I/PowerUI: currentTemp=30.441002,overheatType=1,isOverheatAlarm=false,thresholdTemp=63.0,batteryStatus=2,recentTemps=30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.490002,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.392002,30.392002,30.392002,30.392002,30.392002,30.392002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.490002,30.490002,30.441002,30.441002,30.490002,30.441002,30.441002,30.441002,30.490002,30.441002,30.490002,30.441002,
2019-11-05 15:40:43.283 768-1055/? I/CHRE: @ 2259.773: [AR_CHRE] still: 100
2019-11-05 15:40:44.165 1576-1576/? I/PowerUI: currentTemp=30.490002,overheatType=1,isOverheatAlarm=false,thresholdTemp=63.0,batteryStatus=2,recentTemps=30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.490002,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.392002,30.392002,30.392002,30.392002,30.392002,30.392002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.490002,30.490002,30.441002,30.441002,30.490002,30.441002,30.441002,30.441002,30.490002,30.441002,30.490002,30.441002,30.490002,
2019-11-05 15:40:45.208 14649-14670/? E/GeckoProcessManager: Cannot connect to process tab
2019-11-05 15:40:46.480 768-1055/? I/CHRE: @ 2262.971: [AR_CHRE] still: 100
2019-11-05 15:40:47.129 1576-1576/? I/PowerUI: currentTemp=30.490002,overheatType=1,isOverheatAlarm=false,thresholdTemp=63.0,batteryStatus=2,recentTemps=30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.686,30.490002,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.294,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.343002,30.392002,30.392002,30.392002,30.392002,30.392002,30.392002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.441002,30.490002,30.490002,30.441002,30.441002,30.490002,30.441002,30.441002,30.441002,30.490002,30.441002,30.490002,30.441002,30.490002,30.490002,
`

**Comment by AndiAJ** [comment]
Dupe of #6441
