### ISSUE TITLE
[Bug]Crash after force close Fenix

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#6533]
1. Install latest fennec production
https://tools.taskcluster.net/index/project.mobile.fenix.v2.fennec-production/latest
2.Open
3.Force close
4.Reopen

Crash:
 java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException: Unrecognized migration type: Migration$FxA
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5965)
	at android.app.ActivityThread.access$1200(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalStateException: Unrecognized migration type: Migration$FxA
	at mozilla.components.support.migration.MigrationResultsStore.fromJSON(MigrationResultsStore.kt:12)
	at mozilla.components.support.base.utils.SharedPreferencesCache.getCached(SharedPreferencesCache.kt:2)
	at mozilla.components.support.migration.FennecMigrator.migrateAsync(FennecMigrator.kt:3)
	at org.mozilla.fenix.MigratingFenixApplication.setupApplication(MigratingFenixApplication.kt:144)
	at org.mozilla.fenix.MigratingFenixApplication.onCreate(MigratingFenixApplication.kt:2)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5960)
	... 8 more

**Comment by grigoryk** [comment]
Will be fixed in https://github.com/mozilla-mobile/android-components/issues/5041

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on: 
• Nightly Build #13250607 from 11/21 
• Beta 3.0.0-beta.1 Build #13112229 from 11/7
• RC 2.3.0 Build #13031728 from 10/30

using the following devices:
• Google Pixel 3a XL (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► **Nightly**
![nightly](https://user-images.githubusercontent.com/51314259/69339747-bd4b8380-0c6e-11ea-9047-5545a27f3925.gif)

► **Beta**
![beta](https://user-images.githubusercontent.com/51314259/69339840-e53ae700-0c6e-11ea-89e0-bd3d563ee799.gif)

► **RC**
![RC](https://user-images.githubusercontent.com/51314259/69340037-4498f700-0c6f-11ea-9c11-bdfeec4657b1.gif)
