### ISSUE TITLE
AutoPush - StorageError: Error("No record for uaid:chid")

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#6626]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6667676/

```
StorageError: Error(

Storage Error: "No record for uaid:chid \"3a6fdcxxxxxxxxxxxxxxxxxxxxxxxxxx\":\"992a0fxxxxxxxxxxxxxxxxxxxxxxxxxx\"")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:8)
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:16)
    at mozilla.components.feature.push.RustPushConnection.decrypt(Connection.kt:3)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:20)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke
...
(6 additional frame(s) were not displayed)

Error(

Storage Error: "No record for uaid:chid \"3a6fdcxxxxxxxxxxxxxxxxxxxxxxxxxx\":\"992a0fxxxxxxxxxxxxxxxxxxxxxxxxxx\"")
```

**Comment by jonalmeida** [comment]
We started throwing unrecoverable errors recently, and Firebase Push was recently enable (yesterday) so that explains why we're seeing this error now. So far, only 3 users are affected.

**Comment by jonalmeida** [comment]
Closing in favour of #6663 since it had STR.
