### ISSUE TITLE
[Bug] [Crash] lateinit property browserToolbarView has not been initialized

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/fenix#6763]
New crash in latest Nightly:

Sentry: https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6717047/?environment=fenixNightly

```
kotlin.UninitializedPropertyAccessException: lateinit property browserToolbarView has not been initialized
    at io.reactivex.plugins.RxJavaPlugins.throwUninitializedPropertyAccessException(RxJavaPlugins.java:2)
    at org.mozilla.fenix.browser.BaseBrowserFragment.getBrowserToolbarView(BaseBrowserFragment.kt:1)
    at org.mozilla.fenix.browser.BrowserFragment.onStart(BrowserFragment.kt:6)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:5)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:99)
    at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:215)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2)
    at androidx.fragment.app.Fragment.performStart(Fragment.java:14)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:99)
    at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:215)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:18)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
    at android.app.Activity.performStart(Activity.java:7169)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3155)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:215)
    at android.app.ActivityThread.main(ActivityThread.java:6939)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by csadilek** [comment]
For QA: We don't have STRs here, but we're already seeing this crash go away while Nightly updates roll out. This crash would most likely be reproducible by configuring "no background processes" in developer options, and then pausing/resuming Fenix a few times.

I'd recommend closing this issues once the crashes are gone in Sentry.

**Comment by softvision-miralobontiu** [comment]
This is not fixed yet. I was able to reproduce the crash, following these steps:
1. In the device Settings - Developer Options - set the Background process limit to No background processes.
2. Open Fenix, browse a few pages. (I had twitter.com, and talky.io).
3. Resume Fenix, leave it in the background for a few minutes.
4. Crash after 3-4 minutes.
Tested on the latest Nightly build from 11/26 with Samsung Galaxy Note 8 (Android 9).

**Comment by csadilek** [comment]
@softvision-miralobontiu hm we haven't seen this crash in Sentry since `Nightly 191124 06:01`. Can you attach a logcat when you get a chance. "No background processes" is a great way to spot problems, so it might be you ran into a different crash or different variant of this one.

**Comment by softvision-miralobontiu** [comment]
Sure @csadilek, here is the logcat:

[logcat.txt](https://github.com/mozilla-mobile/fenix/files/3892521/logcat.txt)

This time, the STR were:
1. In the device Settings - Developer Options - set the Background process limit to No background processes.
2. Open Fenix, browse a few pages. 
3. Resume Fenix a couple of times.
4. Crash.

**Comment by csadilek** [comment]
@softvision-miralobontiu hm I am not seeing this crash (browserToolbarView has not been initialized) in the logcat you shared so it must be something else. Let's file this separately?

**Comment by softvision-miralobontiu** [comment]
I wasn't able to reproduce the crash on the latest Nightly build from 11/27.
@csadilek should I close this issue?
Thanks!

**Comment by csadilek** [comment]
Thanks, @softvision-miralobontiu. Yes, let's close this one then.
