### ISSUE TITLE
CustomTabsIntegration: ClassCastException: com.google.android.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinat...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6811]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6738220/

```
ClassCastException: com.google.android.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams
    at org.mozilla.fenix.customtabs.CustomTabsIntegration.<init>(CustomTabsIntegration.kt:6)
    at org.mozilla.fenix.customtabs.ExternalAppBrowserFragment.initializeUI(ExternalAppBrowserFragment.kt:23)
    at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:1)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:85)
    at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:6)
...
(25 additional frame(s) were not displayed)

com.google.android.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams
```

**Comment by NotWoods** [comment]
Related: #6827

**Comment by ekager** [comment]
If we think this is the same as #6827 we can probably close this and reopen if we see anything similar come up?
