### ISSUE TITLE
RuntimeException: FenixApplication: KeyNotYetValidException: Key not yet valid

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#6813]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6735021/

```
KeyNotYetValidException: Key not yet valid
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:856)
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
...
(25 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: android.security.keystore.KeyNotYetValidException: Key not yet valid
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
    at android.app.ActivityThread.access$1100(ActivityThread.java:200)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
...
(4 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.FenixApplication: android.security.keystore.KeyNotYetValidException: Key not yet valid
```

**Comment by ValentinTimisica** [comment]
I saw in the [sentry issue](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6735021/) that "This issue has been marked as resolved." @pocmo should we close this?

**Comment by pocmo** [comment]
> Sentry marked this issue as resolved due to inactivity

Yeah, looks like this crash hasn't happened in multiple months.

**Comment by charlag** [comment]
We observe the same issue in Tutanota (https://github.com/tutao/tutanota/issues/1851) so it would be really cool if you shared how you fixed it. Thanks.
