### ISSUE TITLE
[Bug][CRASH] Crash after clicking on Privacy notice

### ISSUE THREAD

**Issue by marcinwiacek** [mozilla-mobile/fenix#6827]
## Steps to reproduce
1. settings
2. privacy notice

### Expected behavior
Privacy notice

### Actual behavior

```
11-26 21:39:14.306  2766  2766 W App     : Could not read from intent.
11-26 21:39:14.306  2766  2766 W App     : kotlin.TypeCastException: null cannot be cast to non-null type T
11-26 21:39:14.306  2766  2766 W App     : 	at io.reactivex.plugins.RxJavaPlugins.createCustomTabConfigFromIntent(RxJavaPlugins.java:6)
11-26 21:39:14.306  2766  2766 W App     : 	at mozilla.components.feature.customtabs.CustomTabIntentProcessor.process(CustomTabIntentProcessor.kt:9)
11-26 21:39:14.306  2766  2766 W App     : 	at org.mozilla.fenix.IntentReceiverActivity.processIntent(IntentReceiverActivity.kt:41)
11-26 21:39:14.306  2766  2766 W App     : 	at org.mozilla.fenix.IntentReceiverActivity$onCreate$1.invokeSuspend(IntentReceiverActivity.kt:6)
11-26 21:39:14.306  2766  2766 W App     : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
11-26 21:39:14.306  2766  2766 W App     : 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
11-26 21:39:14.306  2766  2766 W App     : 	at android.os.Handler.handleCallback(Handler.java:789)
11-26 21:39:14.306  2766  2766 W App     : 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-26 21:39:14.306  2766  2766 W App     : 	at android.os.Looper.loop(Looper.java:164)
11-26 21:39:14.306  2766  2766 W App     : 	at android.app.ActivityThread.main(ActivityThread.java:6944)
11-26 21:39:14.306  2766  2766 W App     : 	at java.lang.reflect.Method.invoke(Native Method)
11-26 21:39:14.306  2766  2766 W App     : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-26 21:39:14.306  2766  2766 W App     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
	

11-26 21:39:14.563  2766  2766 E AndroidRuntime: FATAL EXCEPTION: main
11-26 21:39:14.563  2766  2766 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 2766
11-26 21:39:14.563  2766  2766 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mozilla.fenix.nightly/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity}: java.lang.ClassCastException: com.google.android.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.google.android.material.appbar.AppBarLayout$LayoutParams cannot be cast to androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at org.mozilla.fenix.customtabs.CustomTabsIntegration.<init>(CustomTabsIntegration.kt:6)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at org.mozilla.fenix.customtabs.ExternalAppBrowserFragment.initializeUI(ExternalAppBrowserFragment.kt:23)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at org.mozilla.fenix.browser.BaseBrowserFragment.onViewCreated(BaseBrowserFragment.kt:1)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:85)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:6)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:54)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:11)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:4)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:9)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:90)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:215)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:9)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7200)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
11-26 21:39:14.563  2766  2766 E AndroidRuntime: 	... 9 more
```

### Device information

* Android device: Galaxy S7 / Android 8
* Fenix version: nightly 191126

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on latest Nightly Build #13371032 from 12/3 using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• Motorola G4 (Android 6.0.1)
• LG Nexus 4 (Android 5.1.1)

► Video
![20191203_152136](https://user-images.githubusercontent.com/51314259/70054908-20c7a080-15e1-11ea-9a95-d5a697c43284.gif)
