### ISSUE TITLE
[Bug] Fenix nightly crashes on startup - java.lang.NoSuchMethodError: No interface method onLoadRequest

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#6878]
## Steps to reproduce
Install latest Nightly.
Open it. Try to visit a site.

### Expected behavior
Visit site
### Actual behavior
Crash
### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-NIGHTLY-194](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6767051/)

**Comment by kbrosnan** [comment]
```
java.lang.NoSuchMethodError: No interface method onLoadRequest(Ljava/lang/String;ZZLkotlin/jvm/functions/Function2;)V in class Lmozilla/components/concept/engine/EngineSession$Observer; or its super classes (declaration of 'mozilla.components.concept.engine.EngineSession$Observer' appears in /data/app/org.mozilla.fenix.nightly-xJh3XhlKDNk0gQu5KtAC3g==/base.apk)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:6)
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:1)
    at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:4)
    at mozilla.components.concept.engine.EngineSession.notifyObservers
    at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:16)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:41)
    at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:1)
    at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:2)
    at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:1)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6762)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-NIGHTLY-196](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6767112/)

**Comment by kbrosnan** [comment]
Sentry issue: [FENIX-NIGHTLY-192](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6766907/)

**Comment by LittleAngelwings** [comment]
Here also:

[2019-11-30-23-36-49.txt](https://github.com/mozilla-mobile/fenix/files/3907653/2019-11-30-23-36-49.txt)

**Comment by csadilek** [comment]
Looks like the latest A-C snapshots didn't get published correctly. Some maven-metadata.xml files point to older and now incompatible versions, see https://bugzilla.mozilla.org/show_bug.cgi?id=1593278

I will try and publish them again now, but we really need to run (more) smoke tests before publishing Nightly going forward...

**Comment by LittleAngelwings** [comment]
With the latest Nightly I have no more crashes.

Nightly 191201 06:00 (Build #13350607)
📦: 24.0.0, cf9d95c05
🦎: 72.0a1-20191129094247

**Comment by andreicristianpetcu** [comment]
Damn! That was a fast fix! Works fine on my phone also.
