### ISSUE TITLE
[Bug] Fenix crashes when selecting and then releasing two sections in settings menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6889]
## Steps to reproduce
1. Launch Fenix.
2. Reach settings screen.
3. Tap on 2 or more settings option for example on `Accessibility` and `Theme` menu options.
4. Release the menu options.
### Expected behavior
After releasing them, one of the menu should open and Fenix will work correctly.
### Actual behavior
After releasing the
### Device information

* Android device: **Google Pixel 3a XL(Android 10), Samsung Galaxy S10+(Android 9)**
* Fenix version: Latest **Nightly from 12/2.**

### Notes
Note that this maybe is not really a normal user behavior but sometimes 2 menus can be selected by mistake and this issue occurs for any menu in the settings section.

![ezgif-6-cbf302c90b11](https://user-images.githubusercontent.com/42831109/69962212-2e642400-1516-11ea-9ff3-f61bb824ab1e.gif)

<details><summary>Crashlog 1</summary>
<p>

```Kotlin
--------- beginning of crash
2019-12-02 15:08:45.451 30507-30507/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 30507
    java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_settingsFragment_to_themeFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:50)
        at androidx.navigation.NavController.navigate(NavController.java:55)
        at org.mozilla.fenix.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:92)
        at androidx.preference.Preference.performClick(Preference.java:7)
        at androidx.preference.Preference.performClick(Preference.java:1)
        at androidx.preference.Preference$1.onClick(Preference.java:1)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-12-02 15:08:45.452 30507-30507/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_settingsFragment_to_themeFragment is unknown to this NavController, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:08:39 GMT+02:00 2019), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:08:43 GMT+02:00 2019), Breadcrumb(message=Changing to fragment defaultBrowserSettingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:08:45 GMT+02:00 2019)])
2019-12-02 15:08:45.452 30507-30507/? I/mozac/CrashReporter: Showing notification
2019-12-02 15:08:45.470 1304-30716/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
```
</p>
</details>

<details><summary>Crashlog 2</summary>
<p>

```Kotlin
2019-12-02 15:09:35.166 30742-30742/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 30742
    java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_settingsFragment_to_searchEngineFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:50)
        at androidx.navigation.NavController.navigate(NavController.java:55)
        at org.mozilla.fenix.settings.SettingsFragment.onPreferenceTreeClick(SettingsFragment.kt:5)
        at androidx.preference.Preference.performClick(Preference.java:7)
        at androidx.preference.Preference.performClick(Preference.java:1)
        at androidx.preference.Preference$1.onClick(Preference.java:1)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-12-02 15:09:35.167 30742-30742/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_settingsFragment_to_searchEngineFragment is unknown to this NavController, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:09:31 GMT+02:00 2019), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:09:32 GMT+02:00 2019), Breadcrumb(message=Changing to fragment accessibilityFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Mon Dec 02 15:09:35 GMT+02:00 2019)])
2019-12-02 15:09:35.167 30742-30742/? I/mozac/CrashReporter: Showing notification
2019-12-02 15:09:35.186 1304-30952/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2019-12-02 15:09:35.186 1304-2655/? W/ActivityTaskManager:   Force finishing activity org.mozilla.fenix.nightly/org.mozilla.fenix.HomeActivity
2019-12-02 15:09:35.194 1304-1386/? I/ActivityManager: Showing crash dialog for package org.mozilla.fenix.nightly u0
</p>
</details>

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly build from **12/3** with **Samsung Galaxy S10+(Android 9) and Google Pixel 3a XL(Android 10).**
