### ISSUE TITLE
ui-test-x86-debug is failing on master

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#6912]
It's failing since the commit https://github.com/mozilla-mobile/fenix/commit/401cc37f99b16185659fe9324ec53d2864a79b64 3 days ago.

Here is the first failure: https://github.com/mozilla-mobile/fenix/runs/330001588

**Comment by AaronMT** [comment]
I'm seeing an  app crash in the recent failures.

```Kotlin
Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "places" was compiled expecting app-services version "0.44.0", but the megazord "fenix" provides version "0.42.2"
```

```Kotlin
	at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
     FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: org.mozilla.fenix.debug, PID: 9063
java.lang.ExceptionInInitializerError
	at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:35)
	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:65)
	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:35)
	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:26)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
	at mozilla.components.browser.storage.sync.PlacesStorage$runMaintenance$2.invokeSuspend(PlacesStorage.kt:47)
	at mozilla.components.browser.storage.sync.PlacesStorage$runMaintenance$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at mozilla.components.browser.storage.sync.PlacesStorage.runMaintenance$suspendImpl(PlacesStorage.kt:46)
	at mozilla.components.browser.storage.sync.PlacesStorage.runMaintenance(Unknown Source:0)
	at org.mozilla.fenix.FenixApplication$runStorageMaintenance$1.invokeSuspend(FenixApplication.kt:143)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "places" was compiled expecting app-services version "0.44.0", but the megazord "fenix" provides version "0.42.2"
	at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:124)
	at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:142)
	at mozilla.appservices.places.LibPlacesFFI$Companion.<clinit>(LibPlacesFFI.kt:295)```

deleteBookmarkTest
bookmarkButtonTest
searchScreenItemsTest
etc

Weird, what is IncompatibleMegazordVersion?

**Comment by AaronMT** [comment]
This seems resolved.
