### ISSUE TITLE
[Bug] Nightly crashes on startup

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#6916]
## Steps to reproduce
Start Nightly
### Expected behavior
Start
### Actual behavior
Crash
### Device information

* Android device: OnePlus 5t
* Fenix version: nightly

**Comment by hawkinsw** [comment]
I *think* that I am seeing the same thing. I *think* that is happening because `version requested by component doesn't match initialized megazord version (0.42.2 != 0.44.0)`. Is this a valid trace?

```
12-03 02:17:55.723 11076 11117 D GeckoProfile: Creating profile dir: /data/user/0/org.mozilla.fenix.performancetest/files/mozilla/x7a7cxch.default
12-03 02:17:55.727 11076 11102 D RustNativeSupport: findMegazordLibraryName(places, 0.42.2
12-03 02:17:55.728 11076 11102 D RustNativeSupport: lib in use: none
12-03 02:17:55.728 11076 11102 D RustNativeSupport: lib configured: fenix
12-03 02:17:55.728 11076 11102 D RustNativeSupport: lib version configured: 0.44.0
12-03 02:17:55.728 11076 11102 E RustNativeSupport: version requested by component doesn't match initialized megazord version (0.42.2 != 0.44.0)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
12-03 02:17:55.745 11076 11102 E AndroidRuntime: Process: org.mozilla.fenix.performancetest, PID: 11076
12-03 02:17:55.745 11076 11102 E AndroidRuntime: java.lang.ExceptionInInitializerError
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:35)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:65)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:35)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:26)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
12-03 02:17:55.745 11076 11102 E AndroidRuntime: 	at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
```

**Comment by hawkinsw** [comment]
@jonalmeida It looks like this was/is the issue you referenced on #fenix-team today in Slack. I just wanted to confirm.

**Comment by lindongbin** [comment]
`java.lang.NoClassDefFoundError: mozilla.appservices.fxaclient.rust.LibFxAFFI
	at mozilla.appservices.fxaclient.FirefoxAccount$Companion.fromJSONString(FirefoxAccount.kt:2)
	at mozilla.components.service.fxa.FirefoxAccount$Companion.fromJSONString$default(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.SecureAbove22AccountStorage.read(AccountStorage.kt:5)
	at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:205)
	at mozilla.components.service.fxa.manager.FxaAccountManager$processQueueAsync$1.invokeSuspend(FxaAccountManager.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	at mozilla.appservices.fxaclient.rust.LibFxAFFI.<clinit>(Unknown Source:0)
	... 10 more
Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "fxaclient" was compiled expecting app-services version "0.44.0", but the megazord "fenix" provides version "0.42.2"
	at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:13)
	at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:4)
	at mozilla.appservices.fxaclient.rust.LibFxAFFI$Companion.<clinit>(LibFxAFFI.kt:2)
	... 11 more
`

**Comment by lindongbin** [comment]
> java.lang.NoClassDefFoundError: mozilla.appservices.fxaclient.rust.LibFxAFFI
	at mozilla.appservices.fxaclient.FirefoxAccount$Companion.fromJSONString(FirefoxAccount.kt:2)
	at mozilla.components.service.fxa.FirefoxAccount$Companion.fromJSONString$default(FirefoxAccount.kt:1)
	at mozilla.components.service.fxa.SecureAbove22AccountStorage.read(AccountStorage.kt:5)
	at mozilla.components.service.fxa.manager.FxaAccountManager.stateActions(FxaAccountManager.kt:205)
	at mozilla.components.service.fxa.manager.FxaAccountManager$processQueueAsync$1.invokeSuspend(FxaAccountManager.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	at mozilla.appservices.fxaclient.rust.LibFxAFFI.<clinit>(Unknown Source:0)
	... 10 more
Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "fxaclient" was compiled expecting app-services version "0.44.0", but the megazord "fenix" provides version "0.42.2"
	at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:13)
	at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:4)
	at mozilla.appservices.fxaclient.rust.LibFxAFFI$Companion.<clinit>(LibFxAFFI.kt:2)
	... 11 more

**Comment by davehunt** [comment]
Looks like this might be causing the performance tests to fail. See https://treeherder.mozilla.org/#/jobs?repo=fenix&selectedJob=279221329&revision=7208ce95a5f25cd05c32b704f295d687bc9780a4&searchStr=Rap for affected jobs.

**Comment by andreicristianpetcu** [comment]
It's fixed now.

**Comment by AndiAJ** [comment]
Hi, **no crash** on Debug build from Master 1.0.1949 (Build #1)📦: 24.0.0, 31e8119c4 🦎: 72.0a1-20191202091209 from Tuesday 12/3 using a Google Pixel 3a (Android 9)
