### ISSUE TITLE
[Bug] Fenix crashes when selecting and then releasing the two options from the passwords section

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/fenix#6922]
## Steps to reproduce
1. Launch Fenix.
2. Reach passwords section(from settings)
3. Tap and hold on the two options from there `Sync logins` and `Saved logins`
4. Release the menu options.
### Expected behavior
After releasing them, one of the menus should open and Fenix will work correctly.
### Actual behavior
Fenix crashes when selecting and then releasing two sections in the passwords section menu.
### Device information

* Android device: **Google Pixel 3a XL(Android 10), Samsung Galaxy S10+(Android 9)**
* Fenix version: Latest **Nightly from 12/3.**

### Notes
Note that this issue cannot be reproduced if a fingerprint is set as an unlocking method for the passwords section as the unlocking method will always be displayed first after releasing the two options.

![ezgif-6-27783176d44a](https://user-images.githubusercontent.com/42831109/70067955-c8e86400-15f7-11ea-8504-e2b9ce816093.gif)

<details><summary>Crashlog</summary>
<p>

```Kotlin
--------- beginning of crash
2019-12-03 18:03:32.518 23885-23885/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 23885
    java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_loginsFragment_to_turnOnSyncFragment is unknown to this NavController
        at androidx.navigation.NavController.navigate(NavController.java:50)
        at androidx.navigation.NavController.navigate(NavController.java:55)
        at org.mozilla.fenix.settings.LoginsFragment.access$navigateToTurnOnSyncFragment(LoginsFragment.kt:3)
        at -$$LambdaGroup$js$I0nUSZnz1fi29lYCFO9bGSE6AKA.onPreferenceClick(java-style lambda group:4)
        at androidx.preference.Preference.performClick(Preference.java:4)
        at androidx.preference.Preference.performClick(Preference.java:1)
        at androidx.preference.Preference$1.onClick(Preference.java:1)
        at android.view.View.performClick(View.java:7352)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27801)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-12-03 18:03:32.519 23885-23885/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix.nightly:id/action_loginsFragment_to_turnOnSyncFragment is unknown to this NavController, breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:19 GMT+02:00 2019), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:26 GMT+02:00 2019), Breadcrumb(message=Changing to fragment loginsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:27 GMT+02:00 2019), Breadcrumb(message=Changing to fragment turnOnSyncFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:29 GMT+02:00 2019), Breadcrumb(message=Changing to fragment loginsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:31 GMT+02:00 2019), Breadcrumb(message=Changing to fragment savedLoginsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Tue Dec 03 18:03:32 GMT+02:00 2019)])
2019-12-03 18:03:32.519 23885-23885/? I/mozac/CrashReporter: Showing prompt
2019-12-03 18:03:32.529 5699-12018/? I/ActivityManager: START u0 {act=null typ=null flg=0x10018000 cmp=ComponentInfo{org.mozilla.fenix.nightly/mozilla.components.lib.crash.prompt.CrashReporterActivity}} from uid 10371
2019-12-03 18:03:32.531 5699-12018/? D/CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 2530000  uid : 1000  pid : 5699  pkgName : AMS_APP_SWITCH@CPU_MIN@41
2019-12-03 18:03:32.534 5699-12018/? D/ActivityManagerPerformance: AMP_acquire() APP_SWITCH
```
</p>
</details>

**Comment by abodea** [comment]
Verified as fixed on the latest **Nightly 12/10** with **Google Pixel 3a XL(Android 10).**
