### ISSUE TITLE
RuntimeException: Unable to create application: KeyStoreException: Signature/MAC verification failed

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#7043]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6796163/

```
KeyStoreException: Signature/MAC verification failed
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
...
(25 additional frame(s) were not displayed)

InvalidKeyException: Keystore operation failed
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:901)
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:926)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
...
(25 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.security.InvalidKeyException: Keystore operation failed
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
    at android.app.ActivityThread.access$1100(ActivityThread.java:200)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
...
(4 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.FenixApplication: java.security.InvalidKeyException: Keystore operation failed
```

**Comment by ekager** [comment]
35 events, 5 users, 10% rooted

**Comment by kbrosnan** [comment]
This crash is not happening any more, seems fixed by https://github.com/mozilla-mobile/android-components/issues/5342
