### ISSUE TITLE
RuntimeException: Unable to create application: KeyStoreException: -49

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#7044]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6766621/

```
KeyStoreException: -49
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:781)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
...
(25 additional frame(s) were not displayed)

InvalidKeyException: Keystore operation failed
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:760)
    at android.security.KeyStore.getInvalidKeyException(KeyStore.java:781)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
    at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
...
(25 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.security.InvalidKeyException: Keystore operation failed
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5784)
    at android.app.ActivityThread.-wrap1
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
...
(4 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.FenixApplication: java.security.InvalidKeyException: Keystore operation failed
```

**Comment by vesta0** [comment]
How often does this happen? Need an S label.

**Comment by ekager** [comment]
This only has 4 events and none in the last month

**Comment by vesta0** [comment]
Thanks @ekager !!!

**Comment by ValentinTimisica** [comment]
I saw in the [sentry issue](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6766621/) that "This issue has been marked as resolved.". Seems like the crash hasn't happened for several months. @ekager should we close this?
