### ISSUE TITLE
KeyStoreException: Invalid operation handle - IllegalBlockSizeException

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#7045]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6768842/

```
KeyStoreException: Invalid operation handle
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:851)
    at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
    at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
...
(15 additional frame(s) were not displayed)

IllegalBlockSizeException: None
    at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
    at javax.crypto.Cipher.doFinal(Cipher.java:2055)
    at mozilla.components.lib.dataprotect.SecurePreferencesImpl23.putString(SecureAbove22Preferences.kt:8)
    at mozilla.components.lib.dataprotect.SecureAbove22Preferences.putString(SecureAbove22Preferences.kt:1)
    at mozilla.components.service.fxa.SecureAbove22AccountStorage.write(AccountStorage.kt:1)
...
(12 additional frame(s) were not displayed)
```

**Comment by ekager** [comment]
> Samsung devices have different implementation of Cipher class running in their JVM and in my case I only had to make operations with it synchronized.

https://github.com/iamMehedi/Secured-Preference-Store/issues/17#issuecomment-380678611

**Comment by ekager** [comment]
Only 4 events, none in the last month, 50% rooted

**Comment by ValentinTimisica** [comment]
I saw in the [sentry issue](https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6768842/) that "This issue has been marked as resolved.". Seems like the crash hasn't happened for several months. @ekager should we close this?
