### ISSUE TITLE
RuntimeException: Unable to create application KeyStoreException: Invalid key blob

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/fenix#7046]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6764160/

```
KeyStoreException: Invalid key blob
    at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
    at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:236)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:356)
    at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:101)
    at java.security.KeyStore.getKey(KeyStore.java:1062)
...
(23 additional frame(s) were not displayed)

UnrecoverableKeyException: Failed to obtain information about key
    at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:234)
    at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:356)
    at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:101)
    at java.security.KeyStore.getKey(KeyStore.java:1062)
    at mozilla.components.lib.dataprotect.KeyStoreWrapper.getKeyFor(Keystore.kt:4)
...
(22 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.FenixApplication: java.security.UnrecoverableKeyException: Failed to obtain information about key
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5887)
    at android.app.ActivityThread.access$1100(ActivityThread.java:200)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
...
(4 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.FenixApplication: java.security.UnrecoverableKeyException: Failed to obtain information about key
```

**Comment by ekager** [comment]
only 40 events, 5 users, 95% rooted

**Comment by kbrosnan** [comment]
No crashes with KeyStore in Sentry or Crash-Stats. Closing as fixed by https://github.com/mozilla-mobile/android-components/issues/5342

**Comment by jonalmeida** [comment]
Seeing instances of this crashing in newer versions of AC (90+). Re-opening to investigate: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9857826/
