### ISSUE TITLE
IllegalStateException: Missing Profile path

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#7069]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6837582/

```
IllegalStateException: Missing Profile path
    at mozilla.components.support.migration.FennecMigrator.migrateLogins(FennecMigrator.kt:6)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:62)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

[INFO] Missing Profile path
```

**Comment by pocmo** [comment]
From the `fennecNightly` build type.

It's not actually a crash but a reported exception. I wonder if we need to act on it or if that is a normal use case? 🤔

**Comment by pocmo** [comment]
As expected this was happening for setups where we didn't need to migrate (new installation). Since we started to detect this and stopped running the migration, this has not shown up anymore.
