### ISSUE TITLE
Repeated crash on startup - Row too big to fit into CursorWindow requiredPos=0, totalRows=6

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#715]
## Steps to reproduce
* unsure
* clicked on a data: uri several times then Fenix crashed

### Expected behavior
no crash

### Actual behavior
    2019-02-27 12:53:23.868 24238-24285/? E/SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=6; query: SELECT * FROM bundles ORDER BY saved_at DESC LIMIT ?
    2019-02-27 12:53:23.870 24238-24285/? E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
        Process: org.mozilla.fenix, PID: 24238
        android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=6
            at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
            at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
            at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
            at mozilla.components.feature.session.bundling.db.BundleDao_Impl$4.compute(BundleDao_Impl.java:9)
            at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:3)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:764)
    2019-02-27 12:53:23.870 24238-24285/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=6)

### Device information

* Android device: Pixel 3
* Fenix version: ?

**Comment by kbrosnan** [comment]
Stefan says that this Sentry crash is the same, https://sentry.prod.mozaws.net/operations/fenix/issues/5294813/?query=is:unresolved

**Comment by sblatz** [comment]
This may be related to #716.

**Comment by kbrosnan** [comment]
Yes It seems so. Small URIs such as bbc.com result in a session getting into 1k tabs. However if you open the Fenix about page which is a large data URI this results in the crash in 2 or so taps of the session.

**Comment by sblatz** [comment]
@kbrosnan after a fresh install of master are you able to reproduce this?

**Comment by kbrosnan** [comment]
If I load about:version (which is a 20k character URI) in about 10+ tabs I can still reproduce. Though it is much harder to trigger now that we don't duplicate the session.

**Comment by sblatz** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/issues/2216

**Comment by sblatz** [comment]
This is fixed by [this a-c change](https://github.com/mozilla-mobile/android-components/issues/2216)
