### ISSUE TITLE
[Bug] Crash when use device back button

### ISSUE THREAD

**Issue by lindongbin** [mozilla-mobile/fenix#7173]
Open a tab
Use back button of device
Crash

> java.lang.NoSuchMethodError: No interface method canClearSelection()Z in class Lmozilla/components/concept/engine/EngineView; or its super classes (declaration of 'mozilla.components.concept.engine.EngineView' appears in base.apk)
	at mozilla.components.feature.session.SessionFeature.onBackPressed(SessionFeature.kt:4)
	at mozilla.components.support.base.feature.ViewBoundFeatureWrapper.onBackPressed(ViewBoundFeatureWrapper.kt:3)
	at org.mozilla.fenix.browser.BaseBrowserFragment.onBackPressed(BaseBrowserFragment.kt:3)
	at org.mozilla.fenix.browser.BrowserFragment.onBackPressed(BrowserFragment.kt:1)
	at org.mozilla.fenix.HomeActivity.onBackPressed(HomeActivity.kt:5)
	at android.app.Activity.onKeyUp(Activity.java:3147)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2729)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3430)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:346)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5213)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5081)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4619)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4759)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4816)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4619)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4619)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4792)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4955)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2582)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2092)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2083)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2559)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

* Android device: ?
* Fenix version: ?
Nightly 191214 18:00 (Build #13481809)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

**Comment by LittleAngelwings** [comment]
Confirmed..
A log from my device:

[2019-12-14-23-58-47.txt](https://github.com/mozilla-mobile/fenix/files/3964633/2019-12-14-23-58-47.txt)

**Comment by lindongbin** [comment]
fixed

Nightly 191215 06:01 (Build #13490610)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326

**Comment by LittleAngelwings** [comment]
Verified as fixed in lasted Nightly.

Nightly 191215 06:01 (Build #13490609)
26.0.0, d06f59e53
GV: 73.0a1-20191212095326
