### ISSUE TITLE
[Bug] Fix intermittent error on UI Bookmarks tests - Nexus 6, Virtual, API Level 25 

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/fenix#7417]
There are at least two tests:
-deleteMultipleSelectionTest
-multipleBookmarkDeletions

failing intermittently on Firebase on Nexus 6, API Level 25, for Pixel 2 API 28 tests are working.
Opening the issue to track those failures and investigate their flakiness.
@sv-ohorvath I think you are the owner of the Bookmark tests? assign it to you but please correct me if I'm wrong :) Thanks!

**Comment by sv-ohorvath** [comment]
Thank you @isabelrios! I'll work on them.

**Comment by isabelrios** [comment]
Thanks @sv-ohorvath! 
I don't have any example, I lost the Firebase execution number in which I saw the failure but I will try to find it

**Comment by jonalmeida** [comment]
Firebase link: https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9103096340937677306/executions/bs.427f0e62eb99f4a3/testcases/1

Here's a stack trace for multipleBookmarkDeletions that I just came across:

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.mozilla.fenix.debug:id/add_bookmark_folder

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1440, height=2560, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81010100 pfl=0x20000 wanim=0x7f130302 vsysui=0x2000 needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+->LinearLayout{id=-1, visibility=VISIBLE, width=1440, height=2392, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c2db9e4, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+-->ViewStub{id=16909295, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@873ce4d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+-->FrameLayout{id=-1, visibility=VISIBLE, width=1440, height=2308, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eb87d02, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=84.0, child-count=1}
|
+--->FitWindowsLinearLayout{id=2131296325, res-name=action_bar_root, visibility=VISIBLE, width=1440, height=2308, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7fe9050, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+---->ViewStubCompat{id=2131296394, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@53c0249, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+---->ContentFrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=1440, height=2308, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@b5674e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}
|
+----->LinearLayout{id=-1, visibility=VISIBLE, width=1440, height=2308, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@70af06f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}
|
+------>Toolbar{id=2131296938, res-name=navigationToolbar, visibility=VISIBLE, width=1440, height=196, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@9c4617c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
+------->AppCompatImageButton{id=-1, desc=Navigate up, visibility=VISIBLE, width=196, height=196, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@397a05, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
+------->ActionMenuView{id=-1, visibility=VISIBLE, width=168, height=196, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@84aa5a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=1272.0, y=0.0, child-count=1}
|
+-------->ActionMenuItemView{id=2131296582, res-name=confirm_add_folder_button, desc=Add folder, visibility=VISIBLE, width=168, height=168, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.ActionMenuView$LayoutParams@248b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=14.0, text=, input-type=0, ime-target=false, has-links=false}
|
+------->AppCompatTextView{id=-1, visibility=VISIBLE, width=349, height=93, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.appcompat.widget.Toolbar$LayoutParams@9b41968, tag=null, root-is-layout-requested=false, has-input-connection=false, x=252.0, y=51.0, text=Add folder, input-type=0, ime-target=false, has-links=false}
|
+------>FragmentContainerView{id=2131296586, res-name=container, visibility=VISIBLE, width=1440, height=2112, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@fdcb181, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=196.0, child-count=1}
|
+------->LinearLayout{id=-1, visibility=VISIBLE, width=1328, height=2000, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@9d31226, tag=null, root-is-layout-requested=false, has-input-connection=false, x=56.0, y=56.0, child-count=6}
|
+-------->AppCompatTextView{id=2131296495, res-name=bookmark_name_label, visibility=VISIBLE, width=1314, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@dca7e67, tag=null, root-is-layout-requested=false, has-input-connection=false, x=14.0, y=56.0, text=NAME, input-type=0, ime-target=false, has-links=false}
|
+-------->ClearableEditText{id=2131296487, res-name=bookmarkNameEdit, visibility=VISIBLE, width=1328, height=144, has-focus=true, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=true, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@721e4bd, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x10001 imeOptions=0x6 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=1 initialSelEnd=1 initialCapsMode=0x0 hintText=null label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=0.0, y=113.0, text=1, input-type=65537, ime-target=true, has-links=false}
|
+-------->AppCompatTextView{id=2131296491, res-name=bookmarkUrlLabel, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@44e2ab2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=URL, input-type=0, ime-target=false, has-links=false}
|
+-------->ClearableEditText{id=2131296490, res-name=bookmarkUrlEdit, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@df69a03, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x11 imeOptions=0x8000005 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0 hintText=null label=null packageName=null fieldId=0 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], x=0.0, y=0.0, text=, input-type=17, ime-target=false, has-links=false}
|
+-------->AppCompatTextView{id=2131296492, res-name=bookmark_folder_label, visibility=VISIBLE, width=1314, height=57, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@63ead80, tag=null, root-is-layout-requested=false, has-input-connection=false, x=14.0, y=313.0, text=FOLDER, input-type=0, ime-target=false, has-links=false}
|
+-------->AppCompatTextView{id=2131296488, res-name=bookmarkParentFolderSelector, visibility=VISIBLE, width=1314, height=84, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@28d0fb9, tag=null, root-is-layout-requested=false, has-input-connection=false, x=14.0, y=398.0, text=mobile, input-type=0, ime-target=false, has-links=false}
|
+->View{id=16908336, res-name=navigationBarBackground, visibility=VISIBLE, width=1440, height=168, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@2f03ffe, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=2392.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
at org.mozilla.fenix.helpers.ViewInteractionKt.click(ViewInteraction.kt:11)
at org.mozilla.fenix.ui.robots.BookmarksRobot.clickAddFolderButton(BookmarksRobot.kt:76)
at org.mozilla.fenix.ui.robots.BookmarksRobot.createFolder(BookmarksRobot.kt:70)
at org.mozilla.fenix.ui.BookmarksTest$multipleBookmarkDeletions$3.invoke(BookmarksTest.kt:324)
at org.mozilla.fenix.ui.BookmarksTest$multipleBookmarkDeletions$3.invoke(BookmarksTest.kt:30)
at org.mozilla.fenix.ui.robots.ThreeDotMenuMainRobot$Transition.openBookmarks(ThreeDotMenuMainRobot.kt:99)
at org.mozilla.fenix.ui.BookmarksTest.multipleBookmarkDeletions(BookmarksTest.kt:321)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)

```

**Comment by AaronMT** [comment]
@mcarare does this need the same style of waits from your other PR?

**Comment by mcarare** [comment]
> @mcarare does this need the same style of waits from your other PR?

Yes, I think so.

**Comment by mcarare** [comment]
I cannot find any samples of `deleteMultipleSelectionTest` failing.

**Comment by liuche** [comment]
`multipleBookmarkDeletions` failing in #7914
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7649035770903088278

**Comment by KMaragh** [comment]
Not sure if this is helpful, but figured I would add it to the list https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9152872747223994561

failing in #8049

**Comment by AaronMT** [comment]
@mcarare Are you able to reproduce this running in a Nexus 6 AVD (API 25)?

**Comment by mcarare** [comment]
@AaronMT Not locally.
