### ISSUE TITLE
[Bug] unable to download file without an extension

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/fenix#7527]
## Steps to reproduce
* visit https://staktrace.github.io/moz-pages/fenix6089.html
* click the link
* accept the download

### Expected behavior

* file is downloaded

### Actual behavior

* `Firefox Nightly can't download the file type`

### Device information

* Android device: Pixel XL2
* Fenix version: Nightly 

followup from #6089

**Comment by Amejia481** [comment]
Now trying to download is causing a crash :

```

824fec20-5233-4ceb-a82f-03f90446bd6b
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1071380 bytes
----
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1071380 bytes
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1211)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1192)
	at mozilla.components.support.utils.Browsers$Companion.findResolvers(Browsers.kt:6)
	at mozilla.components.feature.downloads.DownloadsFeature.processDownload$feature_downloads_release(DownloadsFeature.kt:42)
	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
	at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:11)
	at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:8)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:13)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.TransactionTooLargeException: data parcel size 1071380 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:540)
	at android.content.pm.IPackageManager$Stub$Proxy.queryIntentActivities(IPackageManager.java:5360)
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1201)
	... 17 more
```

**Comment by mcarare** [comment]
@Amejia481 Do we need to use the actual URL to pass it to the intent in https://github.com/mozilla-mobile/android-components/blob/9c143980a869dac5df7ce70cbc0eb995698f87a1/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt#L331 to get the apps that can perform a download? Or can we use a "stub" to get a list of these apps?

**Comment by Amejia481** [comment]
Ideally we want to pass the URL to find all the possible apps for this, What is causing the crash?

**Comment by mcarare** [comment]
Querying the installed packages with specific intent data (larger) causes `TransactionTooLargeException `.

**Comment by Amejia481** [comment]
Do we know if it's us that are sending a lot of data or it's there are too many apps that are can handle the action? 

1) It's us we should try to find a way to limit the data.
2) If it's that are too many apps that can handle the intent maybe we could fallback to a  stub when `TransactionTooLargeException` happens.

**Comment by mcarare** [comment]
I believe it is the data we are sending because I have tested on emulators with no other apps installed and they still throw`TransactionTooLargeException`. 
Maybe we should catch the exception and query for the app list with an `Intent` without any data as a fallback.

**Comment by Amejia481** [comment]
👍🏽

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 2/19 with Pixel 2 (Android 9).
The file from https://staktrace.github.io/moz-pages/fenix6089.html is downloaded and the app does not crash.
I will close this issue and remove the qa:needed label.

**Comment by Amejia481** [comment]
Thanks @ebalazs-sv!
