### ISSUE TITLE
[Bug] Intermittent test failure in BookmarkNodeTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#7556]
Failing tests:

```
[task 2020-01-08T23:00:53.719Z] SUITE: org.mozilla.fenix.ext.BookmarkNodeTest
[task 2020-01-08T23:00:53.719Z]   TEST: GIVEN a bookmark node with children WHEN minusing a sub set of children THEN the children subset is removed and rest remains
[task 2020-01-08T23:00:53.719Z]     [Robolectric] org.mozilla.fenix.ext.BookmarkNodeTest.GIVEN a bookmark node with children WHEN minusing a sub set of children THEN the children subset is removed and rest remains: sdk=28; resources=LEGACY
[task 2020-01-08T23:00:53.719Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-01-08T23:00:53.720Z]     I/AssetManager: no overlays.list file found
[task 2020-01-08T23:00:53.720Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-01-08T23:00:53.720Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b', Original: 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b'
[task 2020-01-08T23:00:53.820Z]   FAILURE
[task 2020-01-08T23:00:53.820Z] 
[task 2020-01-08T23:00:53.820Z] java.lang.AssertionError: expected:<[BookmarkNode(type=ITEM, guid=test, parentGuid=12, position=2, title=Child 2, url=www.mockurl.com, children=null)]> but was:<[]>
[task 2020-01-08T23:00:53.820Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2020-01-08T23:00:53.820Z] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[task 2020-01-08T23:00:53.820Z] 	at org.junit.Assert.assertEquals(Assert.java:118)
[task 2020-01-08T23:00:53.820Z] 	at org.junit.Assert.assertEquals(Assert.java:144)
[task 2020-01-08T23:00:53.820Z] 	at org.mozilla.fenix.ext.BookmarkNodeTest.GIVEN a bookmark node with children WHEN minusing a sub set of children THEN the children subset is removed and rest remains(BookmarkNodeTest.kt:32)
[task 2020-01-08T23:00:53.820Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-01-08T23:00:53.821Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-01-08T23:00:53.821Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-01-08T23:00:53.821Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-01-08T23:00:53.821Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-01-08T23:00:53.821Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-01-08T23:00:53.821Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-01-08T23:00:53.821Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-01-08T23:00:53.821Z] 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
[task 2020-01-08T23:00:53.821Z] 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[task 2020-01-08T23:00:53.821Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[task 2020-01-08T23:00:53.821Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-01-08T23:00:53.821Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-01-08T23:00:53.821Z] 	at java.lang.Thread.run(Thread.java:748)
[task 2020-01-08T23:00:53.821Z] 
[task 2020-01-08T23:00:53.821Z]   TEST: GIVEN a bookmark node with children WHEN minusing a set of all children THEN all children are removed and empty list remains
[task 2020-01-08T23:00:53.821Z]     [Robolectric] org.mozilla.fenix.ext.BookmarkNodeTest.GIVEN a bookmark node with children WHEN minusing a set of all children THEN all children are removed and empty list remains: sdk=28; resources=LEGACY
[task 2020-01-08T23:00:53.821Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-01-08T23:00:53.821Z]     I/AssetManager: no overlays.list file found
[task 2020-01-08T23:00:53.821Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-01-08T23:00:53.821Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b', Original: 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b'
[task 2020-01-08T23:00:53.822Z]   SUCCESS
[task 2020-01-08T23:00:53.822Z] 
[task 2020-01-08T23:00:53.823Z]   TEST: GIVEN a bookmark node with children WHEN minusing a set of non-children THEN no children are removed
[task 2020-01-08T23:00:53.823Z]     [Robolectric] org.mozilla.fenix.ext.BookmarkNodeTest.GIVEN a bookmark node with children WHEN minusing a set of non-children THEN no children are removed: sdk=28; resources=LEGACY
[task 2020-01-08T23:00:53.823Z]     [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
[task 2020-01-08T23:00:53.823Z]     I/AssetManager: no overlays.list file found
[task 2020-01-08T23:00:53.823Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-01-08T23:00:53.824Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b', Original: 'org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader@2813e70b'
[task 2020-01-08T23:00:53.824Z]   FAILURE
```

[Full build logs.](https://firefoxci.taskcluster-artifacts.net/aIZpWZN2RyyfpSDm2LNILA/0/public/logs/live_backing.log)

**Comment by Baron-Severin** [comment]
Root cause analysis

@mcomella noticed this in the stack trace:
> java.lang.AssertionError: expected:<[BookmarkNode(type=ITEM, **_guid=test_**, parentGuid=12, position=2, title=Child 2, url=www.mockurl.com, children=null)]> but was:<[]>

`BookmarkNode.minus` behavior relies on guids being unique.  When running locally, `UUID.randomUUID` is legitimately generating random IDs, but for whatever reason it seems that it is sometimes not on CI.  I'm not sure why, but it gives us enough information to fix it.

Also we don't need Robolectric in this class, so let's pull it out just to keep the file simple.

**Comment by Baron-Severin** [comment]
Fwiw, I'm not sure whether or not this will fix the intermittent failure. I think it might, and the changes are good for test hygiene, so 🤷‍♂ .

**Comment by Baron-Severin** [comment]
I don't think we have any good way of verifying this one, and @AndiAJ I see you removed `qa-needed`, so if you don't mind I'm going to attach `qa-not-needed`.  We can reopen this if the problem reoccurs.
