### ISSUE TITLE
[Bug] Unable to open Fenix

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/fenix#7614]
## Steps to reproduce
Update to  2010807 (2001101801) QQ1B.191205.011

### Expected behavior
Firefox opens

### Actual behavior
Firefox crashes

### Device information
* Android device: Pixel 4XL
* Fenix version: ?

### Other Info
May be related to the previous build being unable to open any pages. Random guess.

**Comment by pwd-github** [comment]
Fixed in latest update.

**Comment by lindongbin** [comment]
`java.lang.NoClassDefFoundError: mozilla.appservices.places.LibPlacesFFI
 at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:6)
 at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:3)
 at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:3)
 at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
 at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
 at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getSuggestions(PlacesHistoryStorage.kt:1)
 at mozilla.components.feature.awesomebar.provider.HistoryStorageSuggestionProvider.onInputChanged(HistoryStorageSuggestionProvider.kt:3)
 at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1.invokeSuspend(BrowserAwesomeBar.kt:2)
 at mozilla.components.browser.awesomebar.BrowserAwesomeBar$onInputChanged$1.invoke(Unknown Source:10)
 at mozilla.components.browser.awesomebar.BrowserAwesomeBar$queryProvidersForSuggestions$1$invokeSuspend$$inlined$forEach$lambda$1$1.invokeSuspend(BrowserAwesomeBar.kt:2)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
 Suppressed: java.lang.NoClassDefFoundError: mozilla.appservices.places.LibPlacesFFI
  at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:6)
  at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:3)
  at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:3)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
  at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:1)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  at mozilla.components.browser.storage.sync.PlacesStorage.getReader$browser_storage_sync_release(Unknown Source:7)
  at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$searchBookmarks$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
 Caused by: java.lang.ExceptionInInitializerError
  at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
  at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:6)
  at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:3)
  at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:3)
  at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:6)
  at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
  at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature$1$historyResults$1.invoke(ToolbarAutocompleteFeature.kt:3)
  at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:3)
  at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:2)
  at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:2)
  at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:10)
  at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:1)
  at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature$1.invokeSuspend(ToolbarAutocompleteFeature.kt:20)
  at mozilla.components.feature.toolbar.ToolbarAutocompleteFeature$1.invoke(ToolbarAutocompleteFeature.kt:2)
  at mozilla.components.browser.toolbar.AsyncFilterListener$invoke$1.invokeSuspend(BrowserToolbar.kt:10)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:764)
 Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "places" was compiled expecting app-services version "0.48.1", but the megazord "fenix" provides version "0.44.0"
  at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:13)
  at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:4)
  at mozilla.appservices.places.LibPlacesFFI$Companion.<clinit>(LibPlacesFFI.kt:2)
  ... 20 more
 [CIRCULAR REFERENCE:java.lang.ExceptionInInitializerError]`
