### ISSUE TITLE
[Bug] Fenix crashes when starting a video

### ISSUE THREAD

**Issue by SamuXzX** [mozilla-mobile/fenix#7956]
## Steps to reproduce

1. Open Firefox Preview
2. Enter some website that shows a video (e.g. Youtube, Reddit, Facebook...)
3. Start the video

### Expected behavior
The video should reproduce.

### Actual behavior
Firefox Preview crashes instantly.

### Device information

* Android device: Huawei p8 lite smart (Android 5.1, EMUI 3.1).
* Fenix version: 3.1.0 (Build #20212102)
27.0.4, cc336f32f
GV: 72.0.1-20200107212822

![ezgif-7-6347a051597a](https://user-images.githubusercontent.com/30182251/73258298-b0469580-41c5-11ea-8621-a841c060dc2a.gif)

**Comment by AaronMT** [comment]
> Android device: Huawei p8 lite smart (Android 5.1, EMUI 3.1).

I'm surprised we're supporting API 22. Is there perhaps a media incompatibility?

Can you attach logging information @SamuXzX? 

https://github.com/mozilla-mobile/fenix/wiki/Logging-Crash-Information

**Comment by SamuXzX** [comment]
First time I do one of these, don't know if it is all okay (it's so long that it exceeded the terminal height).
[Log](https://gist.github.com/SamuXzX/ed1dbf2ff6a14f87486bcdf97ff76af2)

**Comment by AaronMT** [comment]
That's great, thanks.

Relevant info

```Kotlin
02-05 20:25:52.197 W/System.err(17513): java.lang.Exception: codec error:0
02-05 20:25:52.197 D/MtkOmxVdec(  310): [0xf51ef000] add semaphore : 3
02-05 20:25:52.197 W/System.err(17513): 	at org.mozilla.gecko.media.Codec$Callbacks.onError(Codec.java:1)
02-05 20:25:52.198 W/System.err(17513): 	at org.mozilla.gecko.media.LollipopAsyncCodec$CodecCallback$Forwarder.handleMessage(LollipopAsyncCodec.java:3)
02-05 20:25:52.198 W/System.err(17513): 	at org.mozilla.gecko.media.LollipopAsyncCodec$CodecCallback$Forwarder.notify(LollipopAsyncCodec.java:2)
02-05 20:25:52.198 W/System.err(17513): 	at org.mozilla.gecko.media.LollipopAsyncCodec$CodecCallback$Forwarder.onError(LollipopAsyncCodec.java:4)
02-05 20:25:52.198 W/System.err(17513): 	at org.mozilla.gecko.media.LollipopAsyncCodec$CodecCallback$Forwarder.access$400(LollipopAsyncCodec.java:1)
02-05 20:25:52.198 W/System.err(17513): 	at org.mozilla.gecko.media.LollipopAsyncCodec$CodecCallback.onError(LollipopAsyncCodec.java:1)
02-05 20:25:52.198 W/System.err(17513): 	at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:411)
02-05 20:25:52.198 W/System.err(17513): 	at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:366)
02-05 20:25:52.198 W/System.err(17513): 	at android.os.Handler.dispatchMessage(Handler.java:111)
02-05 20:25:52.198 W/System.err(17513): 	at android.os.Looper.loop(Looper.java:194)
02-05 20:25:52.198 W/System.err(17513): 	at android.app.ActivityThread.main(ActivityThread.java:5690)
02-05 20:25:52.198 W/System.err(17513): 	at java.lang.reflect.Method.invoke(Native Method)
02-05 20:25:52.198 W/System.err(17513): 	at java.lang.reflect.Method.invoke(Method.java:372)
02-05 20:25:52.198 W/System.err(17513): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
02-05 20:25:52.198 W/System.err(17513): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
02-05 20:25:52.198 D/ACodec  (17513): [OMX.MTK.VIDEO.DECODER.VP9] onInputBufferFilled ID 0xf51f6940 w/ time 868000 eos 0 mode 1 err 0
02-05 20:25:52.198 D/ACodec  (17513): MetaDataBuffersToSubmit=0 portMode=RESUBMIT
02-05 20:25:52.199 W/InputDispatcher( 1000): channel '2ff6c6fa org.mozilla.fenix/org.mozilla.fenix.HomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-05 20:25:52.205 I/WindowState( 1000): WIN DEATH: Window{3a0a29f3 u0 SurfaceView}
02-05 20:25:52.199 E/InputDispatcher( 1000): channel '2ff6c6fa org.mozilla.fenix/org.mozilla.fenix.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-05 20:25:52.199 D/VP9DEC  (  310): VP9 decode time: 2964
```

(Triage: CC media folks)

**Comment by ekager** [comment]
@SamuXzX can you reproduce on Nightly? (Search "Firefox Preview Nightly" in GP to get it)

**Comment by SamuXzX** [comment]
Same steps and device. [Log](https://gist.github.com/SamuXzX/ed7a25188a32bb3ed4d12a4645ac0384)

![20-02-05-firefox-preview-nightly-crash-report](https://user-images.githubusercontent.com/30182251/73955233-518ac580-4903-11ea-872d-195617d73344.gif)

**Comment by ekager** [comment]
Not sure if this is gecko or GV so filed here in GV for now: https://bugzilla.mozilla.org/show_bug.cgi?id=1615914

**Comment by jhlin** [comment]
Sorry for not responding sooner.
In the [log](https://gist.github.com/SamuXzX/ed1dbf2ff6a14f87486bcdf97ff76af2) from @SamuXzX, the fenix process is in fact killed before the codec error:
```
02-05 20:25:51.938 I/Process (17205): Sending signal. PID: 17205 SIG: 9
```
It could be that the exception of the codec is the consequence of app crash rather than the cause.

@SamuXzX, would you mind downloading an [example app](https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Gy84Tv5XRF-UnrdAwyl9vA/runs/0/artifacts/public/build/geckoview_example.apk) and install it using `adb install`, then see if the bug can be reproduced in it? Thanks a lot!

**Comment by SamuXzX** [comment]
I'm very sorry @jhlin, I just read the reply.

I installed geckoview_example.apk with `adb install`. It didn't crash, I could watch a video and listen to it.

![screen-recording_20200527-121535](https://user-images.githubusercontent.com/30182251/83010465-95234f80-a018-11ea-9dc0-421009eb7b95.gif)


Here the [Log](https://gist.github.com/SamuXzX/616408470825b66338be76a3aaccb943). It's the log of a different attempt, not the one you can see in the gif up here. I don't know if the terminal cut the first lines (if someone could help me understand it...). I'll do it again if you need it.

**Comment by jhlin** [comment]
@SamuXzX Thank you so much! Could you please help try the latest Fenix build again to see if it still crashes? If so, then it must be something in the Fenix code that causes this issue.

**Comment by SamuXzX** [comment]
All done, with Fenix Nighty 200604 (Build #21560609). [Log](https://gist.github.com/SamuXzX/4f7a798568938343cb8e68e28f7c7e7b) and screencast:
![screen-recording_20200604-191417](https://user-images.githubusercontent.com/30182251/83790543-a9aabc00-a698-11ea-8d07-ae5f4213ac76.gif)

**Comment by jhlin** [comment]
The log shows the followings and it looks like some notification view from Fenix failed to inflate and the system killed the app.
```
E/StatusBar( 1263): couldn't inflate view for notification org.mozilla.fenix.nightly/0x2710
E/StatusBar( 1263): android.widget.RemoteViews$ActionException: view: android.view.ViewStub doesn't have method: setTextColor(int)
E/StatusBar( 1263): 	at android.widget.RemoteViews.getMethod(RemoteViews.java:777)
E/StatusBar( 1263): 	at android.widget.RemoteViews.access$300(RemoteViews.java:76)
E/StatusBar( 1263): 	at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:1286)
E/StatusBar( 1263): 	at android.widget.RemoteViews.performApply(RemoteViews.java:2679)
E/StatusBar( 1263): 	at android.widget.RemoteViews.apply(RemoteViews.java:2639)
E/StatusBar( 1263): 	at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:1516)
...
D/NotificationService(  957): onNotification error pkg=org.mozilla.fenix.nightly tag=null id=10000; will crashApplication(uid=10104, pid=25461)
...
I/mozac/CrashReporter(25461): Received crash: UncaughtExceptionCrash(throwable=android.app.RemoteServiceException: Bad notification posted from package org.mozilla.fenix.nightly: Couldn't expand RemoteViews for: StatusBarNotification(pkg=org.mozilla.fenix.nightly user=UserHandle{0} id=10000 tag=null score=-10 key=0|org.mozilla.fenix.nightly|10000|null|10104: Notification(pri=-1 contentView=org.mozilla.fenix.nightly/0x109007e vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=transport actions=1 vis=PUBLIC)), breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 19:14:25 CEST 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Jun 04 19:14:30 CEST 2020)], uuid=8945b443-0462-4706-abd0-d2f9e926641c)

```

**Comment by ekager** [comment]
Oh thanks @jhlin sorry for the bump! 
Looks like this is a known OEM issue for Huawei :/ https://issuetracker.google.com/issues/37078372
