### ISSUE TITLE
[Bug] IndexOutOfBounds Search Engine Manager Index: 0, Size: 0

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/fenix#8035]
Filed from [Sentry report](https://sentry.prod.mozaws.net/operations/fenix/issues/6875697/?query=release:org.mozilla.fenix-3.2.0). 

* Android device: multiple
* Fenix version: 3.2.0 release

**Comment by ekager** [comment]
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at mozilla.components.browser.search.SearchEngineManager.getProvidedDefaultSearchEngineAsync(SearchEngineManager.kt:9)
    at mozilla.components.browser.search.SearchEngineManager.getDefaultSearchEngineAsync(SearchEngineManager.kt:7)
    at mozilla.components.browser.search.SearchEngineManager$getDefaultSearchEngineAsync$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)

**Comment by ekager** [comment]
Moving this to AC
