### ISSUE TITLE
[Bug] IOException crash when clicking a link on CNU under low bandwidth

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#8133]
## Steps to reproduce
- On low bandwidth...
- Visit https://www.cnu.org/publicsquare/2018/03/23/if-houses-were-designed-car-oriented-cities
- Wait for article text to load
- Click "21st Century City Twitter feed" link

### Expected behavior
No crash, twitter loads

### Actual behavior
Crash. If I let the page load fully or have the page cached while loading, I don't seem to experience a crash.

### Device information

* Android device: P2
* Fenix version: Nightly 200130 09:24

Stack trace:
```
    Process: org.mozilla.fennec_aurora, PID: 17888
    java.io.IOException: Unknown error
        at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:19)
        at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:6)
        at androidx.transition.CanvasUtils.copyTo$default(CanvasUtils.java:4)
        at androidx.transition.CanvasUtils.readBytes(CanvasUtils.java:2)
        at mozilla.components.browser.icons.loader.HttpIconLoaderKt$toIconLoaderResult$1.invoke(HttpIconLoader.kt:1)
        at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
        at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:21)
        at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:23)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

@snorp This may be related to GV.

**Comment by softvision-miralobontiu** [comment]
Hi @mcomella 
I wasn't able to reproduce this crash with Xiaomi mi4i (Android 5.0.2) on the 11/2 Nightly build.
I've also tested on an emulator with a poor connection, and no crash there either.
Could you please retry on the latest build?
Thank you!

**Comment by snorp** [comment]
It looks like the download is failing due to a network problem. The `HttpIconLoader` needs to catch `IOException` and retry or something like that.

**Comment by mcomella** [comment]
> I wasn't able to reproduce this crash with Xiaomi mi4i (Android 5.0.2) on the 11/2 Nightly build.
> I've also tested on an emulator with a poor connection, and no crash there either.
> Could you please retry on the latest build?

I don't think I have the cycles to do this – I don't have a convenient set up for testing low bandwidth and I'm skeptical that the website will be unchanged enough that might cause this to reproduce. We could consider looking into the code for the issue or just closing it.
