### ISSUE TITLE
[Bug] Sentry crash: Fragment manager has been destroyed

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#8405]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6457309/?query=is:unresolved

```
java.lang.IllegalStateException: FragmentManager has been destroyed
    at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:4)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by ekager** [comment]
Same as https://github.com/mozilla-mobile/fenix/issues/8413? 
Possible STR in #8374

**Comment by Baron-Severin** [comment]
Yeah, looks like we double posted.  Closing as dup of https://github.com/mozilla-mobile/fenix/issues/8413
