### ISSUE TITLE
[Crash] IOExceptionorg.mozilla.geckoview.GeckoInputStream in read

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/fenix#8414]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7006707/?query=is:unresolved%20GeckoInputStream

```
java.io.IOException: Unknown error
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:19)
    at org.mozilla.geckoview.GeckoInputStream.read(GeckoInputStream.java:6)
    at androidx.transition.CanvasUtils.copyTo$default(CanvasUtils.java:4)
    at androidx.transition.CanvasUtils.readBytes(CanvasUtils.java:2)
    at mozilla.components.browser.icons.loader.HttpIconLoaderKt$toIconLoaderResult$1.invoke(HttpIconLoader.kt:1)
    at mozilla.components.concept.fetch.Response$Body.useStream(Response.kt:1)
    at mozilla.components.browser.icons.loader.HttpIconLoader.load(HttpIconLoader.kt:21)
    at mozilla.components.browser.icons.BrowserIcons$loadIcon$1.invokeSuspend(BrowserIcons.kt:23)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by Baron-Severin** [comment]
Closing as a dup of https://github.com/mozilla-mobile/android-components/issues/5946
