### ISSUE TITLE
[Bug] Crash on rapid selection in addons menu

### ISSUE THREAD

**Issue by s-ankur** [mozilla-mobile/fenix#8699]
## Steps to reproduce
open addons menu, ublock origin
click on the disable addon toggle
quickly click on any other option

### Expected behavior
No crash
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

**Comment by AndiAJ** [comment]
Hi @s-ankur , I wasn't able to reproduce this issue on the latest **`Nightly Build #20560606`** from 02/25 using the following devices:
• Google Pixel 3a XL (Android 10)
• Google Pixel 3a (Android 9)
• Huawei Mate 20 Lite (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• OnePlus A3 (Android 6.0.1)

In case it you are still encountering this problem could you please help us out with a crashlog? ☺️

**Comment by s-ankur** [comment]
Yes , its not reproducible in Nightly anymore

**Comment by s-ankur** [comment]
Ok wait, its still there. You have to remove addon instead of disabling it

**Comment by AndiAJ** [comment]
Thx @s-ankur ! ☺️ 

I've managed to reproduce the issue on the latest **`Nightly Build #20570604 from 02/26`** using the following devices:
• Google Pixel 3a (Android 9)
• OnePlus A3 (Android 6.0.1)

The STR that worked for me:
1. Right after installation, tap and open uBlock
2. Remove and quickly press "Details"

► Video
![20200226-170030](https://user-images.githubusercontent.com/51314259/75357859-b6aa5900-58ba-11ea-9abc-3a5b74484f43.gif)

```kotlin
 --------- beginning of crash
2020-02-26 17:00:41.047 4197-4197/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.nightly, PID: 4197
    org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: enable_switch must not be null
        at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
        at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(Unknown Source:8)
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: enable_switch must not be null
        at -$$LambdaGroup$ks$hLRBNEgzCtgdBnncReSIJE9siKw.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:232)
        at mozilla.components.feature.addons.AddonManager$uninstallAddon$3.invoke(AddonManager.kt:10)
        at -$$LambdaGroup$js$4TkCmOpDQ4Op5MPl4rXDRUWEFCs.onValue(java-style lambda group:12)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(Unknown Source:8) 
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2) 
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-02-26 17:00:41.050 4197-4197/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: enable_switch must not be null, breadcrumbs=[Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:35 GMT+02:00 2020), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:35 GMT+02:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:36 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:37 GMT+02:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:49 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:55:50 GMT+02:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:00 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:01 GMT+02:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:17 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:18 GMT+02:00 2020), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:47 GMT+02:00 2020), Breadcrumb(message=Changing to fragment searchFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:48 GMT+02:00 2020), Breadcrumb(message=Changing to fragment browserFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 16:56:49 GMT+02:00 2020), Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:19 GMT+02:00 2020), Breadcrumb(message=Changing to fragment settingsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:21 GMT+02:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:23 GMT+02:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:33 GMT+02:00 2020), Breadcrumb(message=Changing to fragment addonsManagementFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:34 GMT+02:00 2020), Breadcrumb(message=Changing to fragment installedAddonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:40 GMT+02:00 2020), Breadcrumb(message=Changing to fragment addonDetailsFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Wed Feb 26 17:00:40 GMT+02:00 2020)])
2020-02-26 17:00:41.052 4197-4197/? I/mozac/CrashReporter: Showing prompt```

**Comment by AndiAJ** [comment]
Hi, still reproducible on:
4.0.0-beta.2
Nightly Build #20580605 from 2/27

STR:
1. Right after installation, tap and open uBlock
2. Remove and quickly press "Setings"

Note: After you re-open uBlock, the Settings button isn't displayed even though the Add-on remains enabled.

► Video
![20200227-112155](https://user-images.githubusercontent.com/51314259/75430750-75668780-5954-11ea-8db3-1aeca78678fd.gif) 

```kotlin
 
    --------- beginning of crash
02-27 11:11:19.190 23465-23465/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.beta, PID: 23465
    org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: View android.widget.FrameLayout{88a3b0c V.E..V... .......D 0,48-1080,940} does not have a NavController set
        at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:4)
        at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:4)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:10)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:152)
        at android.app.ActivityThread.main(ActivityThread.java:5507)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalStateException: View android.widget.FrameLayout{88a3b0c V.E..V... .......D 0,48-1080,940} does not have a NavController set
        at androidx.appcompat.app.ResourcesFlusher.findNavController(ResourcesFlusher.java:7)
        at androidx.appcompat.app.ResourcesFlusher.findNavController1(ResourcesFlusher.java:1)
        at -$$LambdaGroup$ks$sxAk0NY9ZndtCeCVjCUjY-QpO6I.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:238)
        at mozilla.components.feature.addons.AddonManager$uninstallAddon$3.invoke(AddonManager.kt:10)
        at -$$LambdaGroup$js$4TkCmOpDQ4Op5MPl4rXDRUWEFCs.onValue(java-style lambda group:12)
        at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:2)
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda) 
        at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:2) 
        at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:152) 
        at android.app.ActivityThread.main(ActivityThread.java:5507) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
02-27 11:11:19.191 23465-23465/? D/AppTracker: App Event: crash
02-27 11:11:19.202 1279-1320/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@224e043
02-27 11:11:19.202 1279-1320/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@cda16c0
02-27 11:11:19.210 1279-1320/? W/ActivityManager:  Dismiss app error dialog : org.mozilla.fenix.beta
02-27 11:11:19.210 1279-1320/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
02-27 11:11:19.213 23465-23465/? I/Process: Sending signal. PID: 23465 SIG: 9
02-27 11:11:19.228 1279-23744/? D/DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@2020-02-27-11_11_19_208.txt
02-27 11:11:19.299 1279-1831/? I/WindowState: WIN DEATH: Window{2c802b5 u0 SurfaceView}
02-27 11:11:19.299 1279-2202/? D/GraphicsStats: Buffer count: 5
02-27 11:11:19.300 1279-2725/? I/ActivityManager: Process org.mozilla.fenix.beta (pid 23465) has died
02-27 11:11:19.301 23553-23553/? I/ServiceChildProcess: Service has been unbound. Stopping.
02-27 11:11:19.303 1279-2605/? I/WindowState: WIN DEATH: Window{735c927 u0 org.mozilla.fenix.beta/org.mozilla.fenix.beta.App}
02-27 11:11:19.303 1279-1695/? W/InputDispatcher: channel '735c927 org.mozilla.fenix.beta/org.mozilla.fenix.beta.App (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-27 11:11:19.303 23533-23533/? I/ServiceChildProcess: Service has been unbound. Stopping.
02-27 11:11:19.303 1279-1695/? E/InputDispatcher: channel '735c927 org.mozilla.fenix.beta/org.mozilla.fenix.beta.App (server)' ~ Channel is unrecoverably broken and will be disposed!
02-27 11:11:19.303 1279-2605/? W/InputDispatcher: Attempted to unregister already unregistered input channel '735c927 org.mozilla.fenix.beta/org.mozilla.fenix.beta.App (server)'
02-27 11:11:19.317 23533-23533/? I/Process: Sending signal. PID: 23533 SIG: 9
02-27 11:11:19.359 1279-2793/? I/ActivityManager: Process org.mozilla.fenix.beta:socket (pid 23553) has died
02-27 11:11:19.369 23393-23393/? D/AppTracker: App Event: start
02-27 11:11:19.374 1279-1317/? V/ActivityManager: killProcessGroupAsync took 73 ms for PID 23465 on thread 14
02-27 11:11:19.375 1279-1317/? V/ActivityManager: killProcessGroupAsync took 0 ms for PID 23553 on thread 14
02-27 11:11:19.375 1279-2725/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 23465 uid 10089
02-27 11:11:19.379 1279-2202/? I/ActivityManager: Process org.mozilla.fenix.beta:tab (pid 23533) has died
02-27 11:11:19.385 1279-1317/? V/ActivityManager: killProcessGroupAsync took 6 ms for PID 23533 on thread 14
02-27 11:11:19.399 1279-1338/? I/ActivityManager: Displayed org.mozilla.fenix.beta/mozilla.components.lib.crash.prompt.CrashReporterActivity: +92ms
02-27 11:11:19.414 23393-23393/? D/AbstractTracker: Event success```

**Comment by softvision-miralobontiu** [comment]
Verified as fixed on the latest Nightly build from 2/28 with Google Pixel (Android 10), OnePlus 5T (Android 9), and Nokia 6 (Android 7.1.1).
