### ISSUE TITLE
[Bug] IllegalStateException: Room cannot verify the data integrity.

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/fenix#8750]
## Steps to reproduce
- Visit website that has credentials saved (for me it's `chase.com`)

### Actual behavior
- Browser crashes

### Device information

* Android device: Samsung S10e, Android 10
* Fenix version: Latest nightly from playstore

```
02-25 15:20:22.504 24805 24805 E AndroidRuntime: FATAL EXCEPTION: main
02-25 15:20:22.504 24805 24805 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 24805
02-25 15:20:22.504 24805 24805 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:10)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:504)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:391)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.db.SitePermissionsDao_Impl.getSitePermissionsBy(SitePermissionsDao_Impl.java:4)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.SitePermissionsStorage.findSitePermissionsBy(SitePermissionsStorage.kt:3)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at mozilla.components.feature.sitepermissions.SitePermissionsFeature$onContentPermissionRequested$permissionFromStorage$1.invokeSuspend(SitePermissionsFeature.kt:7)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-25 15:20:22.504 24805 24805 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
```

**Comment by Amejia481** [comment]
This patch will address that https://github.com/mozilla-mobile/android-components/pull/6076

**Comment by Amejia481** [comment]
@ekager the patch didn't make it to the latest nightly :(

**Comment by Amejia481** [comment]
The fix should be in the latest nightly

**Comment by sv-ohorvath** [comment]
This isn't reproducing on the Nightly 2/26 build. Verified as fixed.

**Comment by Amejia481** [comment]
@concastinator We had a pending migration for `autoplay` site permission, you could find more information here https://github.com/mozilla-mobile/android-components/issues/6075 and https://github.com/mozilla-mobile/android-components/pull/6076
