### ISSUE TITLE
[Bug] InvalidParameterException: 1 is not a valid SitePermissionsRules.AutoplayAction

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/fenix#8752]
This will happen when a user has already saved an invalid value for the `autoplayAudible` permission while running an older version of Preview, then updates to a more recent version where it is expected to be either `ALLOWED` or `BLOCKED`.

```
02-25 14:36:47.679 28768 28768 D AndroidRuntime: Shutting down VM
02-25 14:36:47.679 28768 28768 E AndroidRuntime: FATAL EXCEPTION: main
02-25 14:36:47.679 28768 28768 E AndroidRuntime: Process: org.mozilla.fenix.nightly, PID: 28768
02-25 14:36:47.679 28768 28768 E AndroidRuntime: java.security.InvalidParameterException: 1 is not a valid SitePermissionsRules.AutoplayAction
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at org.mozilla.fenix.utils.Settings$Companion.toAutoplayAction(Settings.kt:2)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at org.mozilla.fenix.utils.Settings.getSitePermissionsCustomSettingsRules(Settings.kt:13)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at org.mozilla.fenix.browser.BaseBrowserFragment.onResume(BaseBrowserFragment.kt:13)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at org.mozilla.fenix.browser.BrowserFragment.onResume(BrowserFragment.kt:1)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performResume(Fragment.java:5)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:112)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:4)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:218)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.completeExecute(FragmentManager.java:8)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$StartEnterTransitionListener.completeTransaction(FragmentManager.java:7)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executePostponedTransaction(FragmentManager.java:16)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:15)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:1)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-25 14:36:47.679 28768 28768 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Comment by Amejia481** [comment]
The fix should be in the latest nightly 🎉

**Comment by sv-ohorvath** [comment]
Talked with Severin and the only way to confirm this bug might be only to look at the telemetry and verify that the exception has stopped being thrown. Since the QA people don't have access to that, we'll leave this open until someone else can confirm.

**Comment by liuche** [comment]
I see very few events in Fenix from Sentry now, just a few a day on really old AC versions. https://sentry.prod.mozaws.net/operations/fenix/issues/6888962/?query=is%3Aunresolved%20InvalidParameterException
