### ISSUE TITLE
[Bug] latest build from master crashes when opening a tab

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/fenix#8878]
### Steps to reproduce

1. open a tab

### Expected behavior

No crash.

### Actual behavior

Fenix crashes.

```
2020-02-29 15:10:53.559 22603-22603/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.debug, PID: 22603
    java.lang.NoClassDefFoundError: mozilla.appservices.places.LibPlacesFFI
        at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:47)
        at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:79)
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:35)
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
        at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:40)
        at mozilla.components.browser.storage.sync.PlacesStorage$reader$2.invoke(PlacesStorage.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mozilla.components.browser.storage.sync.PlacesStorage.getReader$browser_storage_sync_release(Unknown Source:7)
        at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$getBookmarksWithUrl$2.invokeSuspend(PlacesBookmarksStorage.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
     Caused by: java.lang.ExceptionInInitializerError
        at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0)
        at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:47)
        at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:79)
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:35)
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:26)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7)
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHandle(PlacesHistoryStorage.kt:213)
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doSync(WorkManagerSyncManager.kt:340)
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invokeSuspend(WorkManagerSyncManager.kt:326)
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invoke(Unknown Source:10)
        at mozilla.components.service.sync.logins.SyncableLoginsStore.unlocked(AsyncLoginsStorage.kt:466)
        at mozilla.components.service.sync.logins.SyncableLoginsStore$unlocked$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) 
     Caused by: mozilla.appservices.support.native.IncompatibleMegazordVersion: Incompatible megazord version: library "places" was compiled expecting app-services version "0.52.0", but the megazord "megazord" provides version "0.53.0"
        at mozilla.appservices.support.native.HelpersKt.lookupMegazordLibrary(Helpers.kt:124)
        at mozilla.appservices.support.native.HelpersKt.findMegazordLibraryName(Helpers.kt:142)
        at mozilla.appservices.places.LibPlacesFFI$Companion.<clinit>(LibPlacesFFI.kt:317)
        at mozilla.appservices.places.LibPlacesFFI.<clinit>(Unknown Source:0) 
        at mozilla.appservices.places.PlacesApi.<init>(PlacesConnection.kt:47) 
        at mozilla.components.browser.storage.sync.RustPlacesConnection.init(Connection.kt:79) 
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:35) 
        at mozilla.components.browser.storage.sync.PlacesStorage$places$2.invoke(PlacesStorage.kt:26) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at mozilla.components.browser.storage.sync.PlacesStorage.getPlaces$browser_storage_sync_release(Unknown Source:7) 
        at mozilla.components.browser.storage.sync.PlacesHistoryStorage.getHandle(PlacesHistoryStorage.kt:213) 
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker.doSync(WorkManagerSyncManager.kt:340) 
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invokeSuspend(WorkManagerSyncManager.kt:326) 
        at mozilla.components.service.fxa.sync.WorkManagerSyncWorker$doWork$2.invoke(Unknown Source:10) 
        at mozilla.components.service.sync.logins.SyncableLoginsStore.unlocked(AsyncLoginsStorage.kt:466) 
        at mozilla.components.service.sync.logins.SyncableLoginsStore$unlocked$1.invokeSuspend(Unknown Source:12) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) 
```

### Device information

* Android device: OnePlus 7T Pro McLaren Edition
* Fenix version: master branch revision e96732604b76ba9865244e16fe89d9ff56fdfe40 (with refreshed Gradle dependencies)

**Comment by cadeyrn** [comment]
Fenix no longer crashes with a new build I compiled a few hours later, so probably a new AC snapshot fixed the issue.

**Comment by agashlin** [comment]
This is similar to a top crash in build 20200228092428, e.g. https://crash-stats.mozilla.com/report/index/0bd31b12-ae24-4fe9-8a35-7d6f50200229
