### ISSUE TITLE
"Settings|Sign in" (to Firefox Account) causes Fenix to crash

### ISSUE THREAD

**Issue by dholbert** [mozilla-mobile/fenix#900]
## Steps to reproduce
1. Install & start Fenix
2. Tap menu icon in top right corner & choose "Settings"
3. Tap "Sign in

### Expected behavior
I should see some UI to sign into my Firefox account.

### Actual behavior
App crashes ("Sorry, Fenix had a problem and crashed"). Here's the crash info from logcat -- the main exception seems to be "java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix:id/action_homeFragment_to_browserFragment is unknown to this NavController"
```
03-07 15:13:02.999 26442 26442 D AndroidRuntime: Shutting down VM
03-07 15:13:03.001 26442 26442 E AndroidRuntime: FATAL EXCEPTION: main
03-07 15:13:03.001 26442 26442 E AndroidRuntime: Process: org.mozilla.fenix, PID: 26442
03-07 15:13:03.001 26442 26442 E AndroidRuntime: java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix:id/action_homeFragment_to_browserFragment is unknown to this NavController
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:19)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:2)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:1)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.navigation.NavController.navigate(NavController.java:48)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at org.mozilla.fenix.HomeActivity.openToBrowser(HomeActivity.kt:13)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at org.mozilla.fenix.settings.SettingsFragment$getClickListenerForSignIn$1.onPreferenceClick(SettingsFragment.kt:3)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:4)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at androidx.preference.Preference$1.onClick(Preference.java:1)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25885)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-07 15:13:03.001 26442 26442 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-07 15:13:03.003 26442 26442 I mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalArgumentException: navigation destination org.mozilla.fenix:id/action_homeFragment_to_browserFragment is unknown to this NavController)
03-07 15:13:03.003 26442 26442 I mozac/CrashReporter: Showing prompt
03-07 15:13:03.010  1267  3880 I ActivityManager: START u0 {flg=0x10018000 cmp=org.mozilla.fenix/mozilla.components.lib.crash.prompt.CrashReporterActivity (has extras)} from uid 10214
```

### Device information

* Android device: Pixel 3
* Fenix version: 1.0.1910 (Build #10661209), installed from play store today

**Comment by ahal** [comment]
Seeing the same thing.

OnePlus 5
1.0.1910 (Build #10671223)

**Comment by sv-ohorvath** [comment]
Verified as fixed on Nexus 5 (Android 6) & Pixel. Build: master 3/12
