### ISSUE TITLE
Push GeneralError exception after logging in.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9033]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7429399/

```
GeneralError: Error(

General Error: "No subscriptions created yet.")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:15)
    at mozilla.appservices.push.PushManager.unsubscribe(PushManager.kt:9)
    at mozilla.components.feature.push.RustPushConnection.unsubscribe(Connection.kt:4)
    at mozilla.components.feature.push.AutoPushFeature$unsubscribe$3$2.invokeSuspend(AutoPushFeature.kt:5)
    at mozilla.components.feature.push.AutoPushFeature$unsubscribe$3$2.invoke
...
(6 additional frame(s) were not displayed)

Error(

General Error: "No subscriptions created yet.")
```

It seems like just logging in is causing the crash:

```
21:49:21 DestinationChanged - Changing to fragment pairFragment, isCustomTab: false

21:49:22 DestinationChanged - Changing to fragment turnOnSyncFragment, isCustomTab: false

21:49:41 DestinationChanged - Changing to fragment externalAppBrowserFragment, isCustomTab: true
```

**Comment by jonalmeida** [comment]
Our crashes for this have gone down. The GeneralError infos are expected as they can come from web content.
