### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for org.mozilla.geckoview.Base64Utils.encode(byte[])

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/fenix#9113]
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/7492544/

```
UnsatisfiedLinkError: No implementation found for java.lang.String org.mozilla.geckoview.Base64Utils.encode(byte[]) (tried Java_org_mozilla_geckoview_Base64Utils_encode and Java_org_mozilla_geckoview_Base64Utils_encode___3B)
    at org.mozilla.geckoview.Base64Utils.encode(Base64Utils.java)
    at org.mozilla.geckoview.WebPushController.onPushEvent(WebPushController.java:6)
    at org.mozilla.fenix.push.WebPushEngineIntegration$onMessageReceived$1.invokeSuspend(WebPushEngineIntegration.kt:6)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
...
(7 additional frame(s) were not displayed)

No implementation found for java.lang.String org.mozilla.geckoview.Base64Utils.encode(byte[]) (tried Java_org_mozilla_geckoview_Base64Utils_encode and Java_org_mozilla_geckoview_Base64Utils_encode___3B)
```

Parent issue: https://github.com/mozilla-mobile/fenix/issues/9059

**Comment by jonalmeida** [comment]
R-B bug: https://github.com/mozilla-mobile/reference-browser/issues/1042
G-V bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1619778

**Comment by jonalmeida** [comment]
GV patch has landed, it should be in the next nightly.

**Comment by jonalmeida** [comment]
The crashes have gone down so I'm happy with closing this.
