### ISSUE TITLE
[Bug] kotlin.TypeCastException: null cannot be cast to non-null type (BrowserToolbarBottomBehavior) - in beta builds? migration builds?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/fenix#9598]
## Steps to reproduce
* Install `geckoBetaFennecBeta`
* Start browser
* Click toolbar
* Enter URL & enter (I typed "a" which autocompletes to "apple.com")

### Expected behavior
Page loads

### Actual behavior
Crash:

```
2020-04-01 09:48:59.884 7332-7332/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fenix.performancetest, PID: 7332
    kotlin.TypeCastException: null cannot be cast to non-null type mozilla.components.browser.toolbar.behavior.BrowserToolbarBottomBehavior
        at org.mozilla.fenix.components.toolbar.BrowserToolbarView.expand(BrowserToolbarView.kt:245)
        at org.mozilla.fenix.browser.BaseBrowserFragment$initializeUI$$inlined$also$lambda$15.onLoadRequest(BaseBrowserFragment.kt:473)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$8$lambda$1.invoke(Session.kt:249)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$8$lambda$1.invoke(Session.kt:52)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
        at mozilla.components.browser.session.Session.notifyObservers(Unknown Source:7)
        at mozilla.components.browser.session.Session$$special$$inlined$observable$8.afterChange(Delegates.kt:71)
        at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
        at mozilla.components.browser.session.Session.setLoadRequestMetadata(Unknown Source:12)
        at mozilla.components.browser.session.engine.EngineObserver.onLoadRequest(EngineObserver.kt:112)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:398)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1$onLoadRequest$1.invoke(GeckoEngineSession.kt:348)
        at mozilla.components.support.base.observer.ObserverRegistry.notifyObservers(ObserverRegistry.kt:137)
        at mozilla.components.concept.engine.EngineSession.notifyObservers(Unknown Source:7)
        at mozilla.components.browser.engine.gecko.GeckoEngineSession$createNavigationDelegate$1.onLoadRequest(GeckoEngineSession.kt:397)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:493)
        at org.mozilla.geckoview.GeckoSession$3.handleMessage(GeckoSession.java:431)
        at org.mozilla.geckoview.GeckoSessionHandler.handleMessage(GeckoSessionHandler.java:90)
        at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:356)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

To be clear, I reproduced this on the variants:
* geckoBetaFennecBeta
* forPerformanceTest when rebased [this PR](https://github.com/mozilla-mobile/fenix/pull/8634), that adds the migration code to `forPerformanceTest` variants, on master

I suspect the issue is either:
- the beta code is included?
- the migration code is included?

### Device information

* Android device: P2
* Fenix version: master 44432d281e822814cb3db74c8ff092144ca0d2b1

**Comment by mcomella** [comment]
FYI: this caused https://bugzilla.mozilla.org/show_bug.cgi?id=1626541 and I filed https://github.com/mozilla-mobile/fenix/issues/9600 to prevent startup crashes from ever happening again.

**Comment by softvision-miralobontiu** [comment]
I verified the following scenarios, in order to reproduce the crash:
* installed [Fenix Beta](https://github.com/mozilla-mobile/fenix/releases/tag/v4.2.0), started browser, tapped on the toolbar, typed a letter + enter, loaded a page - no crash;
* cleared the Fenix 4.2.0-beta.3 profile, updated the 4.2.0-beta.3 Fenix build from PlayStore with the Migration build 75.0.0-beta.3, started browser, tapped on the toolbar, typed a letter + enter, loaded a page - no crash;
* installed Fennec 68.7b1, updated from PlayStore with the Migration build 75.0.0-beta.3, started browser, tapped on the toolbar, typed a letter + enter, loaded a page - no crash.

Devices used:
* Samsung Galaxy Tab A6 (Android 5.1.1),
* Sony Xperia Z5 Premium (Android 7.1.1), 
* HTC 10 (Android 8),
* OnePlus 5T (Android 9), and
* Google Pixel (Android 10).

@sblatz is there a different build I can test on?
Thanks!

**Comment by sblatz** [comment]
@mcomella might be able to better answer that :)

**Comment by mcomella** [comment]
> @sblatz is there a different build I can test on? I'll remove the qa:needed label.

@softvision-miralobontiu I think that's sufficient, thanks! The bug was due to a build split between debug/nightly and release/beta and only affected beta, which is the build that was tested.. If we wanted to be extra thorough, we can double check on debug/nightly as well.

**Comment by softvision-miralobontiu** [comment]
Thanks!
Based on your response, I'll close this issue.
