### ISSUE TITLE
[Bug] Fix intermittent UI test tabMediaControlButtonTest 

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9670]
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8046457654635721978/executions/bs.4d9073ffb2260f3d/testcases/2

```Log
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with content description text: is "Play"' doesn't match the selected view.
Expected: with content description text: is "Play"
Got: "AppCompatImageButton{id=2131362607, res-name=play_pause_button, desc=Pause, visibility=VISIBLE, width=84, height=84, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@614b60f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=143.0, y=5.0}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.HomeScreenRobot.verifyTabMediaControlButtonState(HomeScreenRobot.kt:201)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$3.invoke(MediaNotificationTest.kt:102)
at org.mozilla.fenix.ui.MediaNotificationTest$tabMediaControlButtonTest$3.invoke(MediaNotificationTest.kt:26)
at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openHomeScreen(BrowserRobot.kt:355)
at org.mozilla.fenix.ui.MediaNotificationTest.tabMediaControlButtonTest(MediaNotificationTest.kt:99)```

**Comment by AaronMT** [comment]
(CC @sv-ohorvath)
