### ISSUE TITLE
[Bug] Fix intermittent UI test verifyReaderViewAppearanceColorSchemeChange

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9672]
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8046457654635721978/executions/bs.aa23afa5a28042ad/testcases/2

```Log
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'view has effective visibility=VISIBLE' doesn't match the selected view.
Expected: view has effective visibility=VISIBLE
Got: "AppCompatImageView{id=2131362562, res-name=notification_dot, desc=Highlighted, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@ff09e53, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}"
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:16)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:36)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:103)
at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:31)
at org.mozilla.fenix.ui.robots.ReaderViewRobotKt.assertReaderViewDetected(ReaderViewRobot.kt:195)
at org.mozilla.fenix.ui.robots.ReaderViewRobotKt.access$assertReaderViewDetected(ReaderViewRobot.kt:1)
at org.mozilla.fenix.ui.robots.ReaderViewRobot.verifyReaderViewDetected(ReaderViewRobot.kt:28)
at org.mozilla.fenix.ui.ReaderViewTest$verifyReaderViewAppearanceColorSchemeChange$3.invoke(ReaderViewTest.kt:270)
at org.mozilla.fenix.ui.ReaderViewTest$verifyReaderViewAppearanceColorSchemeChange$3.invoke(ReaderViewTest.kt:31)
at org.mozilla.fenix.ui.robots.ReaderViewRobotKt.readerViewRobot(ReaderViewRobot.kt:183)
at org.mozilla.fenix.ui.ReaderViewTest.verifyReaderViewAppearanceColorSchemeChange(ReaderViewTest.kt:269)```

**Comment by AaronMT** [comment]
Whoops dupe of https://github.com/mozilla-mobile/fenix/issues/9655
