### ISSUE TITLE
[Bug] Fix intermittent UI test copyBookmarkURLTest

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/fenix#9673]
https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8046457654635721978/executions/bs.245be04c30b9452f/testcases/1/test-cases

```Log
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with content description text: is "Menu")
View Hierarchy:
+>PopupDecorView{id=-1, visibility=VISIBLE, width=747, height=1428, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params={(981,349)(wrapxwrap) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged} ty=APPLICATION_PANEL fmt=TRANSPARENT wanim=0x7f1400fd surfaceInsets=Rect(45, 45 - 45, 45) (manual)


at org.mozilla.fenix.ui.robots.BrowserRobot$Transition.openThreeDotMenu(BrowserRobot.kt:331)
at org.mozilla.fenix.ui.BookmarksTest.copyBookmarkURLTest(BookmarksTest.kt:152)
at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by AaronMT** [comment]
Whoops, dupe of https://github.com/mozilla-mobile/fenix/issues/9653
