### ISSUE TITLE
RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalArgume...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#9733]
https://sentry.prod.mozaws.net/operations/firefox-beta/issues/7743116/

```
IllegalArgumentException: fontSizeFactor cannot be < 0
    at org.mozilla.geckoview.GeckoRuntimeSettings.setFontSizeFactorInternal(GeckoRuntimeSettings.java:6)
    at org.mozilla.geckoview.GeckoFontScaleListener.onSystemFontScaleChange(GeckoFontScaleListener.java:3)
    at org.mozilla.geckoview.GeckoFontScaleListener.start(GeckoFontScaleListener.java:6)
    at org.mozilla.geckoview.GeckoFontScaleListener.onEnabledChange(GeckoFontScaleListener.java:3)
    at org.mozilla.geckoview.GeckoFontScaleListener.setEnabled(GeckoFontScaleListener.java:3)
...
(20 additional frame(s) were not displayed)

RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalArgumentException: fontSizeFactor cannot be < 0
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4631)
    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1374)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
...
(5 additional frame(s) were not displayed)

Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalArgumentException: fontSizeFactor cannot be < 0
```

**Comment by kbrosnan** [comment]
Extremely rare crash on Android 5. We will not be making changes to the migration code. Closing.
