### ISSUE TITLE
UnknownHostException: Unable to resolve host "firefoxusercontent.com": No address associated with hostname

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/fenix#9737]
https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7733080/

```
GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
    at libcore.io.Linux.android_getaddrinfo(Linux.java)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
    at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
...
(21 additional frame(s) were not displayed)

UnknownHostException: Unable to resolve host "firefoxusercontent.com": No address associated with hostname
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
    at java.net.InetAddress.getAllByName(InetAddress.java:1152)
    at com.android.okhttp.Dns$1.lookup(Dns.java:41)
    at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
...
(17 additional frame(s) were not displayed)

Unable to resolve host "firefoxusercontent.com": No address associated with hostname
```

**Comment by pocmo** [comment]
This is already fixed :)

https://github.com/mozilla-mobile/fenix/commit/f76acc5db1458cdae707f462477f1cf7230dcd6e
