### ISSUE TITLE
[Bug] Application crashes when trying to save an image

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla-mobile/fenix#9909]
## Steps to reproduce
1. Navigate to https://file.huobiasia.vip/diag/
2. Tap "Generate an image" button.
3. After image is generated, long tap the screen. 
4. Wait until options popup is displayed.
5. Tap "Save image" and observe behavior. 

### Expected behavior
Image is saved.

### Actual behavior
Application crashes and needs to be restarted.

### Device information

* Android device: Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
* Fenix version: Firefox Preview Nightly 200408 (🦎 77.0a1-20200407093520)

### Notes:
1. Reproducible: 10/10
2. The issue is not reproducible on Firefox Release and Chrome.
3. Might be related to https://github.com/mozilla-mobile/fenix/issues/2436.
4. Gif  attached.
![CrashSaveImage](https://user-images.githubusercontent.com/12184325/79219052-36d05200-7e5a-11ea-9b26-ff9bdae294d7.gif)

Crash log:
```java
2020-04-14 14:01:15.026 17301-17301/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.fennec_aurora, PID: 17301
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2253168 bytes
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1445)
        at android.app.ContextImpl.startService(ContextImpl.java:1387)
        at android.content.ContextWrapper.startService(ContextWrapper.java:656)
        at mozilla.components.feature.downloads.manager.FetchDownloadManager.download(FetchDownloadManager.kt:8)
        at mozilla.components.feature.downloads.DownloadsFeature.access$processDownload(DownloadsFeature.kt:16)
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4)
        at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7)
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:6)
        at kotlin.jvm.internal.Intrinsics.emitAllImpl$FlowKt__ChannelsKt(Intrinsics.java:14)
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2253168 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:628)
        at android.app.ActivityManagerProxy.startService(ActivityManagerNative.java:8766)
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1421)
        at android.app.ContextImpl.startService(ContextImpl.java:1387) 
        at android.content.ContextWrapper.startService(ContextWrapper.java:656) 
        at mozilla.components.feature.downloads.manager.FetchDownloadManager.download(FetchDownloadManager.kt:8) 
        at mozilla.components.feature.downloads.DownloadsFeature.access$processDownload(DownloadsFeature.kt:16) 
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:4) 
        at mozilla.components.support.ktx.kotlinx.coroutines.flow.FlowKt$ifChanged$$inlined$filter$1$2.emit(Collect.kt:7) 
        at mozilla.components.feature.downloads.DownloadsFeature$start$2$invokeSuspend$$inlined$mapNotNull$1$2.emit(Collect.kt:6) 
        at kotlin.jvm.internal.Intrinsics.emitAllImpl$FlowKt__ChannelsKt(Intrinsics.java:14) 
        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:19) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
2020-04-14 14:01:15.083 21339-21342/? E/nightwatch-watcher: Failed to read from logcat: Success
```

**Comment by LaurentiuApahideanSV** [comment]
I can confirm that this issue is reproducible  using the latest version of Firefox Preview Nightly 200512 (Build #21330604).

Devices:
OnePlus 6T (Android 9);
Huawei MediaPad M3 lite 10 (Android 7.0)

**Comment by liuche** [comment]
This is the same issue as #1824 and should be fixed now.

**Comment by softvision-oana-arbuzov** [comment]
Indeed the crash no longer occurs, but the browser becomes unresponsive displaying a popup "Close app/Wait/Send feedback"
![image](https://user-images.githubusercontent.com/12184325/83560317-b60b0980-a51e-11ea-964f-3e9d22055264.png)

Tapping "Wait" and long pressing the screen again displays the popup to "Save the image". 
The image seems to be downloaded but the size is shown as "null".
![image](https://user-images.githubusercontent.com/12184325/83560089-514faf00-a51e-11ea-8575-d7b9dd7f21c6.png)

**Tested with:**
Browser / Version: Firefox Preview Nightly 200601 (🦎 780a1-20200529095426)
Operating System: Huawei P20 Lite (Android 8.0.0) - 1080 x 2280 pixels, 19:9 ratio (~432 ppi density), Samsung Galaxy S6 Edge (Android 7.0) - 1440 x 2560 pixels (~577 ppi pixel density)
